### ISSUE TITLE
Formatting of `pandas.set_option` seems broken

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#31533] opened 2020-02-01 10:56 UTC
![image](https://user-images.githubusercontent.com/33491632/73591030-7f29d600-44e1-11ea-8061-5ac027e3b398.png)

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html

**Comment by charlesdong1991** [comment] 2020-02-01 11:01
duplicate of #31531

**Closed** 2020-02-01 11:02 UTC
