### ISSUE TITLE
.resample documentation too vague

### ISSUE THREAD

**Issue by eddy-ojb** [pandas-dev/pandas#16257] opened 2017-05-05 14:10 UTC
#### Problem description: ".resample" documentation too vague

url: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.resample.html

e.g.:

**rule:** "The offset string or object representing target conversion"

No idea what is meant by that but a more helpful description to amateurs like me seems to be e.g.:
'a frequency or valid rule for re-sampling an inputted time-series object. Expressed as a string. '

Where is the documentation on 'how'? Or is it deprecated. If so, why is it there?

There are 13 parameters with only 9 descriptions.

Lastly, I think that if documentation is structured, a better suited layout is in the form of tables with clear headers but I suppose the documentation is too far in for anyone to be motivated to change it!

Best

Ed

**Comment by jreback** [comment] 2017-05-05 14:25
certainly would take a pull request to add a link to the main docs - these doc strings are more for reference 

http://pandas.pydata.org/pandas-docs/stable/timeseries.html#resampling

**Comment by jreback** [comment] 2017-05-05 14:35
duplicate of #5023

**Closed by jreback** 2017-05-05 14:35 UTC
Labels: Docs, Duplicate, Resample
