### ISSUE TITLE
API cleanup: Remove global duplicates of DataFrame methods

### ISSUE THREAD

**Issue by jondo** [pandas-dev/pandas#15241] opened 2017-01-27 15:48 UTC
In the currently online pandas 0.19.2 documentation, I see the following inconsistency:

* There is [pandas.DataFrame.pivot_table](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pivot_table.html), but also [pandas.pivot_table](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.pivot_table.html).
* In the same way, there is [pandas.DataFrame.pivot](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.pivot.html) and also [pandas.pivot](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.pivot.html). (BTW., the latter has the dataframe argument missing.)
* There is [pandas.melt](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html), but no pandas.DataFrame.melt.

The global versions of these methods (and probably others) are identical to the local ones except for an additional DataFrame argument, I think that all these should only be DataFrame methods. This would e.g. consistently enable chaining.

So let me suggest that the global versions should be removed, of course after a deprecation period.

**Comment by jreback** [comment] 2017-01-27 15:53
duplicate of this https://github.com/pandas-dev/pandas/issues/12640

yes there are a number things that could be done. would you like to do a PR to deprecate?

**Closed by jreback** 2017-01-27 15:53 UTC

**Comment by jondo** [comment] 2017-01-28 22:58
Are the two pivot_table documentation pages both generated from the same docstring in `pivot.py`? Where shall the "DEPRECATED: use DataFrame.pivot_table()" (as seen [here](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort.html)) go?

**Comment by jreback** [comment] 2017-01-28 23:04
https://github.com/pandas-dev/pandas/blob/master/pandas/tools/pivot

but DataFrame.pivot calls this 

so easiest to move this to a private method and deprecate the public one

**Comment by jorisvandenbossche** [comment] 2017-01-28 23:17
I also just commented on the other issue https://github.com/pandas-dev/pandas/issues/12640. I am not sure I agree it is needed to deprecate those
