### ISSUE TITLE
Groupby ignores unobserved combinations when passing more than one categorical column even if observed=True

### ISSUE THREAD

**Issue by harmbuisman** [pandas-dev/pandas#27075] opened 2019-06-27 13:43 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

df_test = pd.DataFrame()
df_test['A'] = pd.Series(np.arange(0,2), dtype='category').cat.set_categories(list(range(0,3)))
df_test['B'] = pd.Series(np.arange(10,12), dtype='category').cat.set_categories(list(range(10,13)))

print("Test DF:")
print(df_test)

print("\nThe following are as expected, unobserved categories have size = 0:")
print(df_test.groupby('A').size())
print(df_test.groupby('B').size())

print("\nThe following does not consider categories, I would expect 9 result lines here:")
print(df_test.groupby(['A','B']).size())

print("\nExpected:")
print(pd.DataFrame({'A':list(range(0,3))*3, 'B':list(range(10,13))*3, '':[1]*2+[0]*7 }).set_index(['A','B']))
```
![image](https://user-images.githubusercontent.com/7702207/60271106-07b01a80-98f2-11e9-9ec2-f6bc07e15069.png)

#### Problem description
groupby([cols]) gives back a result for all categories if only one column that is categorical is provided (e.g. ['A']), but it only shows the observed combinations if multiple categorical columns are provided ['A', 'B'], regardless of the setting of observed. I would expect that I would get a result for all combinations of the categorical columns.

#### Expected Output
A result for all combinations of the categorical categories of the groupby columns. For the example above:
A B    
0 10  1
1 11  1
2 12  0
0 10  0
1 11  0
2 12  0
0 10  0
1 11  0
2 12  0

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: 4.5.0
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.7
numpy: 1.16.3
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: 2.0.1
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.8
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.3
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0
gcsfs: None
</details>

**Comment by TomAugspurger** [comment] 2019-07-08 15:26
Looks like a bug. Interested in investigating where it's coming from? IIRC, groupby may ask the index for the output values, which is where CategoricalIndex says "here's all the categories, including unobserved". But MultiIndex wouldn't have that.

**Comment by bsolomon1124** [comment] 2019-08-07 01:31
Ran into what seems to be the same issue: here's reproducible example, with some different fixes in the answers: https://stackoverflow.com/q/57385009/7954504.

```python
df = pd.DataFrame({
    "state": pd.Categorical(["AK", "AL", "AK", "AL"]),
    "gender": pd.Categorical(["M", "M", "M", "F"]),
    "name": list("abcd"),
})
```

Incorrect result:

```python
>>> df.groupby(["state", "gender"])["name"].count()
state  gender
AK     M         2
AL     F         1
       M         1
Name: name, dtype: int64
```

**Comment by jreback** [comment] 2019-08-07 01:32
please check on 0.25

**Comment by bsolomon1124** [comment] 2019-08-07 01:34
@jreback 

> please check on 0.25

```python
>>> import pandas as pd
>>> pd.__version__
'0.25.0'
>>> df = pd.DataFrame({
...     "state": pd.Categorical(["AK", "AL", "AK", "AL"]),
...     "gender": pd.Categorical(["M", "M", "M", "F"]),
...     "name": list("abcd"),
... })
>>> df.groupby(["state", "gender"])["name"].count()
state  gender
AK     M         2
AL     F         1
       M         1
Name: name, dtype: int64
```

**Comment by bsolomon1124** [comment] 2019-08-07 04:30
### Summary

- `.result_index` excludes the categorical labels that it should include when `observed=False`
- This happens in `groupby()` itself before any further methods are called, namely in [`pandas.core.groupby.grouper._get_grouper`](https://github.com/pandas-dev/pandas/blob/486ade03d5b3fe5fb246dd07351517ef557da3ef/pandas/core/groupby/grouper.py#L431)

```pycon
In [35]: df = pd.DataFrame({ 
    ...:     "state": pd.Categorical(["AK", "AL", "AK", "AL"]), 
    ...:     "gender": pd.Categorical(["M", "M", "M", "F"]), 
    ...:     "name": list("abcd"), 
    ...: })                                                                                                                                                  

In [36]: df.groupby(["state", "gender"]).grouper.result_index                                                                                                
Out[36]: 
MultiIndex([('AK', 'M'),
            ('AL', 'F'),
            ('AL', 'M')],
           names=['state', 'gender'])
```

### Detail

First observation: it seems like this occurs for _some, but not all_, methods of the `GroupBy` object:

```pycon
>>> bn = df.groupby(["state", "gender"])["name"]

>>> bn.size()
state  gender
AK     M         2
AL     F         1
       M         1
Name: name, dtype: int64

>>> bn.count()
state  gender
AK     M         2
AL     F         1
       M         1
Name: name, dtype: int64

>>> bn.nunique()
state  gender
AK     M         2
AL     F         1
       M         1
Name: name, dtype: int64

>>> bn.first()
state  gender
AK     F         NaN
       M           a
AL     F           d
       M           b
Name: name, dtype: object
```

The next thing I did was to step into `df.groupby(["state", "gender"])["name"].count()` and see what looked off, via `pdb.run(bn.count())`.

In `pandas/core/groupby/generic.py`, in the call to `SeriesGroupBy.count()`, several things stand out:

```pytb
(Pdb) list 1310,1331
1310            """
1311            Compute count of group, excluding missing values.
1312
1313            Returns
1314            -------
1315            Series
1316                Count of values within each group.
1317            """
1318 ->         ids, _, ngroups = self.grouper.group_info
1319            val = self.obj._internal_get_values()
1320
1321            mask = (ids != -1) & ~isna(val)
1322            ids = ensure_platform_int(ids)
1323            minlength = ngroups or 0
1324            out = np.bincount(ids[mask], minlength=minlength)
1325
1326            return Series(
1327                out,
1328                index=self.grouper.result_index,
1329                name=self._selection_name,
1330                dtype="int64",
1331            )
(Pdb) unt 1325
> ...lib/python3.7/site-packages/pandas/core/groupby/generic.py(1326)count()
-> return Series(
(Pdb) p ids
array([0, 2, 0, 1])
(Pdb) p ngroups
3
(Pdb) p mask
array([ True,  True,  True,  True])
(Pdb) p out
array([2, 1, 1])
```

Namely:

- `bn.ngroups` is 3, not 4
- Same for `bn.groups`:

```pycon
>>> bn.groups
{('AK', 'M'): Int64Index([0, 2], dtype='int64'),
 ('AL', 'F'): Int64Index([3], dtype='int64'),
 ('AL', 'M'): Int64Index([1], dtype='int64')}
```

But what seems to stand out most is `.grouper.result_index`:

```pycon
>>> bn.grouper.result_index
MultiIndex([('AK', 'M'),
            ('AL', 'F'),
            ('AL', 'M')],
           names=['state', 'gender'])
```

Regardless of whether `ngroups` and `groups` are "right" (e.g. should `observed` control these? that seems undefined), the ultimate output is determined by the final `Series` constructor and it never stood a chance because it gets built with a `MultiIndex` of length 3, not 4, and the corresponding `out` which is length 3.

Something similar happens for `.size()`; here is `pdb.run('bn.grouper.size()')`:

```pytb
(Pdb) list 267, 277
267             """
268             Compute group sizes
269
270             """
271  ->         ids, _, ngroup = self.group_info
272             ids = ensure_platform_int(ids)
273             if ngroup:
274                 out = np.bincount(ids[ids != -1], minlength=ngroup)
275             else:
276                 out = []
277             return Series(out, index=self.result_index, dtype="int64")
(Pdb) unt 277
> ...lib/python3.7/site-packages/pandas/core/groupby/ops.py(277)size()
-> return Series(out, index=self.result_index, dtype="int64")
(Pdb) p out
array([2, 1, 1])
(Pdb) p self.result_index
MultiIndex([('AK', 'M'),
            ('AL', 'F'),
            ('AL', 'M')],
           names=['state', 'gender'])
```

So it would appear initially that both `out` and `result_index` need fixed.

----


... all of the above led me to [`_GroupBy.__init__()`](https://github.com/pandas-dev/pandas/blob/9c37226a228784e993a220a02424fc8b68fe8257/pandas/core/groupby/groupby.py#L342), which calls [`pandas.core.groupby.grouper._get_grouper`](https://github.com/pandas-dev/pandas/blob/486ade03d5b3fe5fb246dd07351517ef557da3ef/pandas/core/groupby/grouper.py#L431).  Stepping into that, the index is already created as a result of `grouper, exclusions, obj = _get_grouper(...)`:

```pytb
(Pdb) p grouper.result_index
MultiIndex([('AK', 'M'),
            ('AL', 'F'),
            ('AL', 'M')],
           names=['state', 'gender'])
```

**Comment by mojones** [comment] 2019-11-28 09:38
I think this is the same issue as https://github.com/pandas-dev/pandas/issues/23865

**Comment by mojones** [comment] 2020-03-20 10:57
This seems to be fixed in versions >=1.0.0

**Comment by jreback** [comment] 2020-03-20 10:59
great love to have a PR with validation tests (note we likely have some of these examples already)

**Comment by smithto1** [comment] 2020-06-26 16:28
take

**Comment by smithto1** [comment] 2020-07-08 21:46
@jreback This issue can also be closed. It is addressed by the linked Pull Request. (The PR wasn't linked at the time it was merged so this wasn't done automatically.)

**Comment by jreback** [comment] 2020-07-08 21:47
thanks @smithto1

**Closed** 2020-07-08 21:47 UTC
Labels: Categorical, Groupby, Needs Tests
