### ISSUE TITLE
Table headers misaligned with to_string(index=False)

### ISSUE THREAD

**Issue by andrewdalecramer** [pandas-dev/pandas#21095] opened 2018-05-17 02:40 UTC
#### Code Sample, a copy-pastable example if possible

```python
>>> foo = pd.DataFrame({"A":["One","Three","Four"], "B": range(3)})
>>> print(foo.to_string())
       A  B
0    One  0
1  Three  1
2   Four  2
>>> print(foo.to_string(index=False))
A  B
  One  0
Three  1
 Four  2
```
#### Problem description

Columns headers lose alignment when `to_string` is passed `index=False`.

#### Expected Output
```python
>>> print(foo.to_string())
    A  B
  One  0
Three  1
 Four  2
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-43-Microsoft
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by mroeschke** [comment] 2018-05-19 04:01
Confirmed the latest release, v0.23.0. PRs welcome!

**Comment by jreback** [comment] 2018-05-19 04:29
this is a duplicate issue

**Comment by mroeschke** [comment] 2018-05-19 04:37
Duplicate of #13032

**Closed by mroeschke** 2018-05-19 04:37 UTC
Labels: Bug, Output-Formatting
