### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by csg-dev** [pandas-dev/pandas#51083] opened 2023-01-31 09:52 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from sqlalchemy import create_engine, text
 return pd.read_sql('select * from test', self.engineweb).set_index('id')
```

### Issue Description

AttributeError: 'OptionEngine' object has no attribute 'execute'

### Expected Behavior

success

### Installed Versions

<details>

 1.5.3
</details>

**Comment by phofl** [comment] 2023-01-31 17:22
Duplicate of #51015 and related

**Closed by phofl** 2023-01-31 17:22 UTC
Labels: Bug, Needs Triage
