### ISSUE TITLE
SettingWithCopyWarning while using .loc

### ISSUE THREAD

**Issue by marcomayer** [pandas-dev/pandas#13226] opened 2016-05-19 09:21 UTC
#### Code Sample, a copy-pastable example if possible

```
df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))

# In ipython-notebook, I'm now just looking at the DF by calling it. This seems to create a view of the DF? If df is not called, the warning doesn't show. It will also show when doing x = df for example.
df

df = df.loc[df['A'] > 0]

# Now calling this, SettingWithCopyWarning shows suggesting to use .loc which is what I do?
df.loc[:, 'A'] = 1

```
#### Expected Output

What works without a warning is to use df.assign. But what about single row changes a la df.loc[1,'A'] = 1

Looking at the docs, df.loc seems to be the suggested way that should work fine.

Maybe I'm just missing something and the mistake is on my side. If so I'd be happy to know.
## INSTALLED VERSIONS

commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Darwin
OS-release: 15.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.1
statsmodels: 0.6.1
xarray: None
IPython: 4.2.0
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5.2
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: 0.2.1

**Comment by jreback** [comment] 2016-05-19 12:39
this is as expected. You are modifying something that *may* be a view. This is *kind* of a false-positive case in that since you have reassigned the variable ``df`` and if no other references are found then we can simply assign it w/o the warning. But this is quite tricky as pandas doesn't support copy-on-write.

So its not a bug per-se, though *maybe* this specifically could be addressed. I'll mark it, but this requires some deep knowledge to dive in.

**Comment by marcomayer** [comment] 2016-05-19 13:26
Thanks Jeff. I just can't really grasp what's happening there. Until now I thought .loc is the "save" way that will keep me out of trouble by always giving back a copy()? So I'd have to explicitly call .loc[].copy()?

Sorry for the question, but I did read the docs regarding this a few times and still didn't fully comprehend it :(

**Comment by jreback** [comment] 2016-05-19 13:29
``.loc`` allows you to simultaneously filter & operate on multi-axes, so do the following.

```
In [9]: df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))

In [10]: df
Out[10]: 
          A         B         C         D
0  0.909465  1.271865  0.740703 -0.721578
1 -0.206009  1.831160 -1.498496  0.866737
2 -0.271777  0.275378 -0.787905 -0.327714
3  1.316702 -0.763188 -0.328237 -0.765706
4  0.118460 -0.275091 -0.263612 -0.498635
5 -0.722549 -1.066199  0.742033  0.692168

In [11]: df.loc[df.A>1,'A'] = 1

In [12]: df
Out[12]: 
          A         B         C         D
0  0.909465  1.271865  0.740703 -0.721578
1 -0.206009  1.831160 -1.498496  0.866737
2 -0.271777  0.275378 -0.787905 -0.327714
3  1.000000 -0.763188 -0.328237 -0.765706
4  0.118460 -0.275091 -0.263612 -0.498635
5 -0.722549 -1.066199  0.742033  0.692168
```

**Comment by p-himik** [comment] 2017-02-16 18:07
Maybe as the first step pandas could suggest that view modification via `loc` is what caused this warning?

**Comment by jreback** [comment] 2017-02-16 18:16
if u would like to improve the warning and/or docs would be great

**Comment by mroeschke** [comment] 2021-04-30 05:30
I don't get the warning anymore on master. Not sure if we should explicity be testing for the this specific warning so just going to close for now.

```
In [1]: df = pd.DataFrame(np.random.randn(6,4), columns=list('ABCD'))

In [2]: df = df.loc[df['A'] > 0]

In [3]: df.loc[:, 'A'] = 1

In [4]: df
Out[4]:
   A         B         C        D
5  1 -0.190929 -0.352006 -1.21157
```

**Closed by mroeschke** 2021-04-30 05:30 UTC
Labels: API Design, Copy / view semantics, Indexing
