### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Darshanroy** [pandas-dev/pandas#54811] opened 2023-08-28 13:55 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

books = pd.read_csv("Dataset/BX-Book-Ratings.csv", encoding="latin-1",engine='python',warn_bad_lines=True, error_bad_lines=False)
```

### Issue Description

'error_bad_lines '  argument is not working 

### Expected Behavior

import pandas as pd

books = pd.read_csv("Dataset/BX-Book-Ratings.csv", encoding="latin-1",engine='python',warn_bad_lines=True, error_bad_lines=False)

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_India.1252
pandas           : 2.0.3
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.11.1
snappy           : None
sqlalchemy       : 2.0.15
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by DavidToneian** [comment] 2023-08-28 15:34
Hi Darshanroy,

thanks for reporting an issue.

Your report states you're using version 2.0.3, but since 2.0.0, `warn_bad_lines` and `error_bad_lines` have been removed (see https://pandas.pydata.org/docs/whatsnew/v2.0.0.html).

Could you please

1. Verify which version of pandas you are using, and
2. Explain in more detail what behavior you are observing, and what behavior you would expect?

Also, if you could give this bug report a suitable title, that would be appreciated!

**Comment by johannes-mueller** [comment] 2023-09-03 13:49
I think this is not a bug, as it is documented that the argument `error_bad_lines` is deprecated since 1.3.0. According to the documentation it should now work like:

```python
books = pd.read_csv("Dataset/BX-Book-Ratings.csv", encoding="latin-1",engine='python', on_bad_lines='warn')
```

**Comment by mroeschke** [comment] 2024-07-17 22:39
Closing as the expected behavior

**Closed by mroeschke** 2024-07-17 22:39 UTC
Labels: Bug, Needs Triage
