### ISSUE TITLE
Semantics between `Series.apply` and `Series.agg` incorrect

### ISSUE THREAD

**Issue by mhriemers** [pandas-dev/pandas#51880] opened 2023-03-10 14:57 UTC
Correct me if I'm wrong, but isn't `Series.agg` supposed to reduce all rows to a singular value and `Series.apply` supposed to apply an operation to each individual row? Currently, when a function doesn't throw one of `ValueError, AttributeError, TypeError`, it is assumed to be a function meant for `Series.apply` even when passed to `Series.agg`. 

Consider the following example:
```python
def one_sample_t_test(r, mu_0):
    return (np.mean(r) - mu_0) / (np.std(r) / np.sqrt(len(r)))

s.agg(lambda r: one_sample_t_test(r, 0))
```

This generates exactly the same series as before because the function is called with individual values instead of the whole frame. When used in conjunction with another aggregator, like mean, it crashes since it can't concatenate a singular value with a series. 

https://github.com/pandas-dev/pandas/blob/c293caf2e94ca50d8036d43324d05b516392eb16/pandas/core/apply.py#L1040-L1051

Why would somebody ever call `Series.agg` with a function that only works on singular values?

**Comment by rhshadrach** [comment] 2023-04-23 15:27
Thanks for the report - I think this is a duplicate of #49673 and #52140. Please comment here if you think this is not accurate and can reopen.

**Closed by rhshadrach** 2023-04-23 15:27 UTC
Labels: Apply, Series
