### ISSUE TITLE
Tracking issue for EA Series Operations Support

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#26913] opened 2019-06-18 00:53 UTC
*Stale*

**Comment by jorisvandenbossche** [comment] 2019-06-19 08:12
> Series.isna which (via pd.core.dtypes.missing._isna_new) , calls np.asarray(obj). This is contrary to documentation which says:

This should not be the case (if it is, it is a bug that should be fixed). `_isna_new` calls the `isna` method on the object through `_isna_ndarraylike`

**Comment by pilkibun** [comment] 2019-06-19 16:05
You're right. I don't know what happened, but I tested this again now and the method is called.  Perhaps I was testing while I had an `__array_function__` implemented in the EA.

Anyway, my mistake. sorry.

**Comment by jorisvandenbossche** [comment] 2019-06-19 16:13
>  Perhaps I was testing while I had an __array_function__ implemented in the EA.

If that is the case, it was not your mistake, and it would be interesting to know. Because the `isna` machinery should work regardless of having `__array_function__` defined or not.

**Comment by pilkibun** [comment] 2019-06-28 19:05
I can't reproduce, so not an issue.

There are lots of EA issues on here, and work elsewhere. Since I've moved on to other things, I'm closing.

**Comment by simonjayhawkins** [comment] 2020-09-19 14:35
@jorisvandenbossche closing as with the OP deleted this issue does not appear actionable.

**Closed by simonjayhawkins** 2020-09-19 14:35 UTC
Labels: ExtensionArray
