### ISSUE TITLE
BUG: Unexpected Behaviour `pd.merge` using `left_on` and `right_index=True` with single level MultiIndex

### ISSUE THREAD

**Issue by Romain-Vuillez** [pandas-dev/pandas#52331] opened 2023-03-31 19:08 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# merge fails to join the DataFrames with a single level MultiIndex
# expected successful join on first row =='A'
import pandas as pd
left_col = ['A', 'B']
right_index = [('A',)]
left_df = pd.DataFrame({"col":left_col})
right_df = pd.DataFrame(data={"b":[100]}, index=pd.MultiIndex.from_tuples(right_index, names=["col"]))
pd.merge(left_df, right_df, left_on=["col"], right_index=True, how="left", validate="m:1")

# merge succeeds to join the DataFrames if the MultiIndex has 2 levels
import pandas as pd
left_col = ['A', 'B']
right_index = [('A','A',)]
left_df = pd.DataFrame({"col1":left_col, "col2":left_col})
right_df = pd.DataFrame(data={"b":[100]}, index=pd.MultiIndex.from_tuples(right_index, names=["col1", "col2"]))
pd.merge(left_df, right_df, left_on=["col1", "col2"], right_index=True, how="left", validate="m:1")

# merge succeeds if it's an Index
import pandas as pd
left_col = ['A', 'B']
right_index = ['A']
left_df = pd.DataFrame({"col":left_col})
right_df = pd.DataFrame(data={"b":[100]}, index=pd.Index(right_index, name="col"))
pd.merge(left_df, right_df, left_on="col", right_index=True, how="left", validate="m:1")
```

### Issue Description

In the first example, even though a list of 1 column is provided for `left_on`, matching the length of the index levels, merge fails to join successfully.
I think that given that it works for 2 levels, and that it works when there is a single level index, it should work for 1 as well, especially because it fails silently.
Alternatively, it should raise an Error if something is not correct.

### Expected Behavior

First example returns:

|   | col | b    |
|---|-----|------|
| 0 | A   | None |
| 1 | B   | None |

pd.DataFrame.from_dict({'col': {0: 'A', 1: 'B'}, 'b': {0: None, 1: None}})

I would expect the first example to return the following DataFrame (same than example 3):

|   | col | b    |
|---|-----|------|
| 0 | A   | 100. |
| 1 | B   | None |

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.1.0
Version          : Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 63.2.0
pip              : 23.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by topper-123** [comment] 2023-05-04 11:39
Thanks @Romain-Vuillez for the bug report.

Can you add expected output to the bug report, it makes it easier to ensure all readers of the bug report understand the issue the same way.  However, I think I see the same as you, so I agree this is a bug.

This is possibly related/to a duplicate of #32067.

**Comment by Romain-Vuillez** [comment] 2023-05-04 12:43
Thanks a lot for your help @topper-123 !
I tried to provide the outputs in the expected behaviour - is this ok now?

Cheers,
Romain

**Comment by topper-123** [comment] 2023-05-04 16:48
Yes, it's fine, though we normally just give the repr output as that is typically easier to read. I agree this is a bug.

**Comment by Charlie-XIAO** [comment] 2023-05-13 05:34
@topper-123 I think this is because `("A",)` is not considered the same as `"A"`, so the merged result gives `nan`. If we do want to fix this, what about the following approach:
```python
def _left_join_on_index(left_ax, right_ax, join_keys, sort=False):
    if len(join_keys) > 1:
        # ...
    else:
        jkey = join_keys[0]

        if isinstance(right_ax, MultiIndex):  # Add these lines to convert into Index
            right_ax = right_ax.get_level_values(0)

        left_indexer, right_indexer = _get_single_indexer(jkey, right_ax, sort=sort)

    # ...

    return left_ax, None, right_indexer
```

**Comment by topper-123** [comment] 2023-05-13 06:09
I think keeping all the multiindex handling in one place could be better:

```
def _left_join_on_index(left_ax, right_ax, join_keys, sort=False):
    if len(join_keys) > 1 or isinstance(right_ax, MultiIndex):
        # ...
    else:
        jkey = join_keys[0]
```

Can you look into that?

**Comment by Charlie-XIAO** [comment] 2023-05-13 18:12
@topper-123 Oh you are totally right. Even to make it simpler, I'm thinking of doing this:
```python
def _left_join_on_index(left_ax, right_ax, join_keys, sort=False):
    if isinstance(right_ax, MultiIndex):
        left_indexer, right_indexer = _get_multiindex_indexer(
            join_keys, right_ax, sort=sort
        )
    else:
        left_indexer, right_indexer = _get_single_indexer(
            join_keys[0], right_ax, sort=sort
        )
```
I think that the condition `len(join_keys) == right_ax.nlevels` is already guaranteed in advance. I will open a PR for this. Thanks for your suggestion!

**Closed** 2023-05-16 16:57 UTC
Labels: Bug, Reshaping
