### ISSUE TITLE
Fix SS03 Issues in Docstrings

### ISSUE THREAD

**Issue by deepandas11** [pandas-dev/pandas#29315] opened 2019-11-01 00:25 UTC
Running the following:
```scripts/validate_docstrings.py --errors=SS03``` 
returns the following instances of cases where the Summary doesn't end with a period. 
SS03 is one of the pending docstring-related errors as mentioned in #27977

- [ ] pandas.tseries.frequencies.to_offset: Summary does not end with a period
- [ ] pandas.Int64Index: Summary does not end with a period
- [ ] pandas.UInt64Index: Summary does not end with a period
- [ ] pandas.Float64Index: Summary does not end with a period
- [ ] pandas.IntervalIndex.left: Summary does not end with a period
- [ ] pandas.IntervalIndex.right: Summary does not end with a period
- [ ] pandas.IntervalIndex.mid: Summary does not end with a period
- [ ] pandas.IntervalIndex.closed: Summary does not end with a period
- [ ] pandas.IntervalIndex.length: Summary does not end with a period
- [ ] pandas.io.stata.StataReader.data: Summary does not end with a period
- [ ] pandas.plotting.plot_params: Summary does not end with a period
- [ ] pandas.io.formats.style.Styler.loader: Summary does not end with a period
- [ ] pandas.Timestamp.combine: Summary does not end with a period
- [ ] pandas.Timestamp.fromordinal: Summary does not end with a period
- [ ] pandas.Timestamp.isoweekday: Summary does not end with a period
- [ ] pandas.Timestamp.weekday: Summary does not end with a period
- [ ] pandas.Period.strftime: Summary does not end with a period
- [ ] pandas.Interval.closed: Summary does not end with a period
- [ ] pandas.Interval.left: Summary does not end with a period
- [ ] pandas.Interval.length: Summary does not end with a period
- [ ] pandas.Interval.mid: Summary does not end with a period
- [ ] pandas.Interval.right: Summary does not end with a period

The way to go about resolving this issue with such a large number of files has been nicely setup by @datapythonista in #27977 itself. Quoting from the issue:

_**> VERY IMPORTANT
The main challenge will be not repeating the same work as other sprinters, which is very frustrating, and happened massively at every sprint. My recommendation is BEFORE doing any work, to create an issue for the error code you plan to work on (check that it hasn't already been created). In the error write the list of errors that validate_docstrings.py returns. Then in a comment, take 10 of them, and write that you're going to fix them. Other people can work on a different 10. When opening a PR, reference the issue.**_

[UPDATE 1] 
List has been updated after @datapythonista's recommendation to remove the ones starting with ```pandas.tseries.offsets``` .

**Comment by SebStrug** [comment] 2019-11-01 07:55
I'll work on the bottom 10:
- [ ]  pandas.Timestamp.combine: Summary does not end with a period
- [ ]  pandas.Timestamp.fromordinal: Summary does not end with a period
- [ ]  pandas.Timestamp.isoweekday: Summary does not end with a period
- [ ]  pandas.Timestamp.weekday: Summary does not end with a period
- [ ]  pandas.Period.strftime: Summary does not end with a period
- [ ]  pandas.Interval.closed: Summary does not end with a period
- [ ]  pandas.Interval.left: Summary does not end with a period
- [ ]  pandas.Interval.length: Summary does not end with a period
- [ ]  pandas.Interval.mid: Summary does not end with a period
- [ ]  pandas.Interval.right: Summary does not end with a period

**Comment by datapythonista** [comment] 2019-11-01 19:56
Afaik all the ones starting with `pandas.tseries.offsets` are false positives, we're working on fixing the script so they are not mistakenly reported.

**Comment by SebStrug** [comment] 2019-11-02 09:59
Sorry for the delay @deepandas11 @datapythonista .
As a first-time contributor I'm trying to follow the example of @sparalic in #28053 editing `pandas\_libs\tslibs\nattype.pyx` and `pandas\_libs\tslibs\timestamps.pyx` (for the timestamps SS03 error), but the error still keeps coming up.

Am I looking in the wrong place? Should I submit a preliminary PR and go from there?

**Comment by datapythonista** [comment] 2019-11-04 20:59
When changing `.pyx` files, you need to recompile pandas with `python setup.py build_ext --inplace -j 0` for the script to see the changes. If that's not the problem, please send me a link to of the docstring you're changing, and the output of the script, and I'll have a look.

**Comment by SebStrug** [comment] 2019-11-06 06:55
I'll take the remaining 12.

- [ ]  pandas.tseries.frequencies.to_offset: Summary does not end with a period
- [ ]  pandas.Int64Index: Summary does not end with a period
- [ ]  pandas.UInt64Index: Summary does not end with a period
- [ ]  pandas.Float64Index: Summary does not end with a period
- [ ]  pandas.IntervalIndex.left: Summary does not end with a period
- [ ]  pandas.IntervalIndex.right: Summary does not end with a period
- [ ]  pandas.IntervalIndex.mid: Summary does not end with a period
- [ ]  pandas.IntervalIndex.closed: Summary does not end with a period
- [ ]  pandas.IntervalIndex.length: Summary does not end with a period
- [ ]  pandas.io.stata.StataReader.data: Summary does not end with a period
- [ ]  pandas.plotting.plot_params: Summary does not end with a period
- [ ]  pandas.io.formats.style.Styler.loader: Summary does not end with a period

**Comment by mroeschke** [comment] 2021-11-20 05:42
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/25306

**Closed by mroeschke** 2021-11-20 05:42 UTC
Labels: Docs
