### ISSUE TITLE
Pandas .apply function parameter axis to match rest of classes

### ISSUE THREAD

**Issue by teddywaweru** [pandas-dev/pandas#47541] opened 2022-06-29 07:21 UTC
Basically, every other function(that I have utilized), for the axis variable in functions, 0 represents 'index', while 1 represents 'columns'. But this is somehow reversed in the .apply function. Maybe this is by design? I stand to be advised. I personally find it confusing a bit:
![image](https://user-images.githubusercontent.com/57697272/176376109-0fbfb3d8-88df-4323-9bd7-6b3c006913f2.png)
For pandas.DataFrame.dropna()
![image](https://user-images.githubusercontent.com/57697272/176376208-8b9210ea-9923-4e2a-94f4-26a02c42a4aa.png)
For pandas.DataFrame.apply()

**Comment by phofl** [comment] 2022-06-29 08:57
Closing as duplicate of #47542

**Closed by phofl** 2022-06-29 08:57 UTC
Labels: Enhancement, Needs Triage
