### ISSUE TITLE
writer.save() prevents the creation of addtional sheets

### ISSUE THREAD

**Issue by phil20686** [pandas-dev/pandas#11985] opened 2016-01-07 15:52 UTC
When using pd.ExcelWriter, it appears that calling the save method prevents you from subsequently creating new sheets. E.g. see the following test script

``` python
import pandas as pd
import numpy as np
import os


if __name__ == "__main__" :
    dates = pd.date_range('20130101', periods=6)
    df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

    currentpath = os.path.realpath(__file__)
    outputpath = os.path.join(currentpath, "..\\test.xlsx")

    writer = pd.ExcelWriter(outputpath)
    df.to_excel(writer, "thing1")

    writer.save() #if you remove this line it works as expected

    new_sheet = writer.book.add_worksheet("thing2")
    new_sheet.write(1,1,"test")

    print writer.book.sheetnames

    writer.save()
    writer.close()
```

**Comment by jreback** [comment] 2016-01-07 16:58
it appears that ``engine='xlsxwriter'`` (the default) does a ``.close()`` when saving, while ``engine='openpyxl'`` does not (it just saves).

not sure if this is a function of the engine.

you want to adjust the code and see if the test suite still passes? (and this is not tested obviously)

**Comment by WillAyd** [comment] 2019-01-21 04:44
Closing as duplicate of #9145

**Closed by WillAyd** 2019-01-21 04:44 UTC
Labels: API Design, Duplicate, IO Excel
