### ISSUE TITLE
Pandas dropna throwing ValueError: "Cannot convert non-finite values (NA or inf) to integer"

### ISSUE THREAD

**Issue by dumbledad** [pandas-dev/pandas#29734] opened 2019-11-20 07:47 UTC
#### Code Sample, a copy-pastable example if possible

```python
long_summary = long_summary.dropna(axis='columns', how='all') 
```
#### Problem description

that simple line throws an exception:

> ValueError: Cannot convert non-finite values (NA or inf) to integer

I cannot see how calling dropna would lead to this exception. Why would dropna try to convert any values to an integer? Is this a bug or am I misunderstanding dropna?

#### Actual output

````

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-88-b4926abd4d81> in <module>
    ----> 1 long_summary = long_summary.dropna(axis='columns', how='all')

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py in dropna(self, axis, how, thresh, subset, inplace)
    4860                 agg_obj = self.take(indices, axis=agg_axis)
    4861 
    -> 4862             count = agg_obj.count(axis=agg_axis)
    4863 
    4864             if thresh is not None:

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py in count(self, axis, level, numeric_only)
    7848                 result = Series(counts, index=frame._get_agg_axis(axis))
    7849 
    -> 7850         return result.astype("int64")
    7851 
    7852     def _count_level(self, level, axis=0, numeric_only=False):

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\generic.py in astype(self, dtype, copy, errors, **kwargs)
    5880             # else, only a single dtype is given
    5881             new_data = self._data.astype(
    -> 5882                 dtype=dtype, copy=copy, errors=errors, **kwargs
    5883             )
    5884             return self._constructor(new_data).__finalize__(self)

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\managers.py in astype(self, dtype, **kwargs)
        579 
        580     def astype(self, dtype, **kwargs):
    --> 581         return self.apply("astype", dtype=dtype, **kwargs)
        582 
        583     def convert(self, **kwargs):

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
        436                     kwargs[k] = obj.reindex(b_items, axis=axis, copy=align_copy)
        437 
    --> 438             applied = getattr(b, f)(**kwargs)
        439             result_blocks = _extend_blocks(applied, result_blocks)
        440 

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors, values, **kwargs)
        557 
        558     def astype(self, dtype, copy=False, errors="raise", values=None, **kwargs):
    --> 559         return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
        560 
        561     def _astype(self, dtype, copy=False, errors="raise", values=None, **kwargs):

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\blocks.py in _astype(self, dtype, copy, errors, values, **kwargs)
        641                     # _astype_nansafe works fine with 1-d only
        642                     vals1d = values.ravel()
    --> 643                     values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
        644 
        645                 # TODO(extension)

    c:\users\timregan\appdata\local\programs\python\python37\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy, skipna)
        698         if not np.isfinite(arr).all():
        699             raise ValueError(
    --> 700                 "Cannot convert non-finite values (NA or inf) to " "integer"
        701             )
        702 

    ValueError: Cannot convert non-finite values (NA or inf) to integer
````

#### Expected Output

I expect columns containing only NaNs to be dropped, without any attempt at conversion to int64

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 41.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
None

</details>

**Comment by dumbledad** [comment] 2019-11-22 16:44
@alimcmaster1 added a 'missing data' tag. The redacted CSV is available on Dropbox [here](https://www.dropbox.com/s/rm2w4oqsnrb6yqd/dropna.csv?dl=0).



    df = pd.read_csv('E:\\Temp\\dropna.csv')
    df.dropna(axis='columns', how='all') 

But be warned, the CSV is 3.3 GB and the resulting data frame has over 60 million rows. It tried cutting out rows, but it seems to need to be this long to trigger the error.

**Comment by mzeitlin11** [comment] 2021-06-26 02:11
Sorry for late response here @dumbledad, thanks for the report! Contributions to investigate this would be very welcome (a copy-pastable reproducer would help, but that might be tricky if it needs to be so large :)

(Also the missing-data tag just refers to the fact that this issue is somewhat about NaNs)

**Comment by mroeschke** [comment] 2021-07-23 04:56
Thanks for the report. As mentioned, we would need a [minimal example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) (like a `DataFrame` generated with random data from `np.random.rand`) in order to reproduce this behavior, determine a fix and add a self contained regression test.

Going to close this issue due to a lack of minimal example, but happy to reopen if someone could produce one.

**Closed by mroeschke** 2021-07-23 04:56 UTC
Labels: Missing-data
