### ISSUE TITLE
DataFrame:iterrows() damages data integrity during interations

### ISSUE THREAD

**Issue by ZHANGGU** [pandas-dev/pandas#23946] opened 2018-11-27 09:27 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
 for _, row_arr in DataFrame.iterrows():
```
#### Problem description
For a DataFrame, there is one column that contains complex numbers

Once interating rows, all the values in each row become complex, where the real part is the original and the imagine part is given by 0*j

This is annoying, because one has to take care about this auto-conversion.

I would expect resolution on this, as data integrity shall not be polluted by iterations.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
0.1.2
</details>

**Comment by jreback** [comment] 2018-11-27 09:37
pls edit your post to remove the images and instead show code that demonstrates the issue

**Comment by ZHANGGU** [comment] 2018-11-27 09:39
code only one line is given. images help understanding the issue. sorry!

**Comment by TomAugspurger** [comment] 2018-11-27 12:19
@ZHANGGU see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for how to write a bug report.

**Comment by TomAugspurger** [comment] 2018-11-27 12:29
OK, closing. We won't delete it, in case someone is is able to provide a reproducible example.

FYI, we ask for reproducible examples precisely because it saves time.

**Closed by TomAugspurger** 2018-11-27 12:29 UTC

**Comment by ZHANGGU** [comment] 2018-11-27 12:31
It is a pity that you would not look at this issue. BYE PANDAS

**Comment by TomAugspurger** [comment] 2018-11-27 12:35
FWIW, I tried this simple example, with complex data and iterrows, and everything is fine:

```python
In [4]: list(pd.DataFrame(pd.Series([1j, 2j])).iterrows())
Out[4]:
[(0, 0    1j
  Name: 0, dtype: complex128), (1, 0    2j
  Name: 1, dtype: complex128)]
```

Perhaps there's an issue with your code?
