### ISSUE TITLE
BUG: could be a problem related to dropna()

### ISSUE THREAD

**Issue by Conxz** [pandas-dev/pandas#32190] opened 2020-02-22 23:29 UTC
#### Code Sample

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})
#df
#        born      name        toy
#0        NaT    Alfred        NaN
#1 1940-04-25    Batman  Batmobile
#2        NaT  Catwoman   Bullwhip

df.dropna(inplace=True)
#df 
#        born    name        toy 
#1 1940-04-25  Batman  Batmobile

# A. 
dat_df = pd.DataFrame(data=np.zeros(1), columns=['Score'])
dat_df['SID'] = df['name']
#dat_df 
#   Score  SID 
#0    0.0  NaN 

# B.
dat_df = pd.DataFrame(data=np.zeros(1), columns=['Score'])
dat_df['SID'] = df['name'].values
#dat_df 
#   Score     SID
#0    0.0  Batman 

```
#### Problem description
Have a look at the code in block A and B. In A, df['name'] was used, while in B, df['name'].values was used. Apperantly, output of A was not correct, where it seems that the first term in the original df (before applying dropna()) was assign to the new dat_df. 
I tested this issue with version 0.18.1, 0.25.1, and 1.0.1.

**Comment by pandrey-fr** [comment] 2020-02-24 09:46
Hi,

What is happening here is that executing `dat_df['SID'] = df['name']` tries to match values from `dat_df` and `df` based on row indices. However, in your example, `dat_df` only has one row, of index 0, while `df` has one row of index 1, which is why the latter's value is not merged into the former's newly declared column.
Note that if you run:
```python
dat_df = pd.DataFrame(data=np.zeros(2), columns=['Score'])
dat_df['SID'] = df['name']
```
you get
```
   Score     SID
0    0.0     NaN
1    0.0  Batman
```

When using `df.values`, you are dropping the index by merging directly the underlying numpy array, hence the different behaviour.

I hope this helps!

**Comment by mroeschke** [comment] 2020-02-24 17:08
Thanks for the explanation @pandrey-fr. This is indeed the expected behavior due to index alignment.

**Closed by mroeschke** 2020-02-24 17:08 UTC
Labels: Bug

**Comment by Conxz** [comment] 2020-03-24 21:51
I did not get the point by @pandrey-fr . Here it seems to be a probme of dropna(). 
After applying df.dropna(inplace=True), there should be only 1 row in df. It does not make sense to me that when you asign the df to the new dat_df, it could generate 2 rows. (actually you could generate 3 if you data=np.zeros(3). But this is not correct.)

**Comment by pandrey-fr** [comment] 2020-03-25 07:41
I will repeat then:
> dat_df['SID'] = df['name'] triggers an attempt to match values from dat_df and df based on row indices

You may think of it as a left outer join between the tables, based on rows' index Since the table on the right does not share any index with the left one, no value can be successfully carried over. This is fixed by assigning `df['name'].values`, which triggers a join on rows' _positions_ rather than index (due to the lack of one on the `.values` resulting numpy array).

I hope this helps.
