### ISSUE TITLE
read_csv: Warn when column cannot be parsed as dates

### ISSUE THREAD

**Issue by malinkallen** [pandas-dev/pandas#40447] opened 2021-03-15 16:21 UTC
#### Is your feature request related to a problem?
As a part of a research project, me and two co-authors have been mining GitHub for Jupyter notebooks and studied a number of frequent function calls in the notebooks. It appears that users sometimes make calls to `read_csv` where they specify that non-date data should be parsed as dates. The most common case is that `parse_date` is set to `True` while the index cannot be parsed as dates. We have also seen cases where columns whose data cannot be parsed as dates are specified, by name (e.g. `parse_dates=["REQUEST_DATE", "AUTHORIZATION_DATE"]`) or column index (e.g. `parse_dates=[1]`). As a result, data will be stored as objects while the user thinks that it is stored on datetime format. Then results of e.g. filtering or merging on the column (or index) in question may be incorrect. I think that `read_csv` should issue a warning in these cases.

Moreover, the fact that the user tries to parse a non-date column as dates may be an indication that the input data does not look as the user expects, which is also worth a warning!

#### Describe the solution you'd like
The function `read_csv` should warn when the value of the parameter `parse_dates` specifies that a column (or index) should be parsed as dates but the column (or index) in question is on non-date format.

#### API breaking implications
If only a warning is issued, I don't see how this could break anything.

#### Describe alternatives you've considered
An alternative could be to issue an error instead of a warning.

**Comment by lithomas1** [comment] 2021-03-16 16:04
This looks like a duplicate of #35520

**Closed** 2021-03-16 16:16 UTC
Labels: Duplicate
