### ISSUE TITLE
BUG: DataFrame.fillna() doesn't work for 0/0 with Int64Dtype

### ISSUE THREAD

**Issue by YunJD** [pandas-dev/pandas#46677] opened 2022-04-07 01:13 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'a': [0.0,0.0], 'b':0})
df.b = df.b.astype(pd.Int64Dtype())
df['c'] = df.a / df.b
df.fillna(0.0) # Doesn't fill
df.iloc[0].fillna(0.0) # Does fill
```

### Issue Description

As shown above, creating a `pd.NA` value using `pd.Int64Dtype` as the dtype causes `.fillna()` to malfunction.  `.fillna(0.0)` still works after using `.iloc[0]`.

This behavior suddenly manifested when I upgraded to version 1.4.2.  I am grabbing a table from Big Query and some of the columns are set to Int64Dtype.

### Expected Behavior

```python
import pandas as pd
df = pd.DataFrame({'a': [0.0,0.0], 'b':0})
df.b = df.b.astype(pd.Int64Dtype())
df['c'] = df.a / df.b
df.fillna(0.0)

# Should output:
"""
     a  b    c
0  0.0  0  0.0
1  0.0  0  0.0
"""

# But got:
"""
     a  b    c
0  0.0  0  NaN
1  0.0  0  NaN
"""
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.4.0
Version          : Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2[/RELEASE_ARM64_T6000]()
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 62.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
brotli           : None
fastparquet      : None

</details>

**Comment by phofl** [comment] 2022-04-08 13:48
duplicate of #39926

**Closed by phofl** 2022-04-08 13:48 UTC
Labels: Bug, Needs Triage

**Comment by simonjayhawkins** [comment] 2022-04-10 15:18
> `.fillna(0.0)` still works after using `.iloc[0]`

There maybe an indexing issue here that is not explicitly discussed in https://github.com/pandas-dev/pandas/issues/39926 which may have created the confusion.

`df.iloc[0]` gives

```
a     0.0
b     0.0
c    <NA>
Name: 0, dtype: Float64
```

if we are preseving `np.nan` in FloatArray, I think this should be

```
a     0.0
b     0.0
c    NaN
Name: 0, dtype: Float64
```

as for instance, `df["c"]` gives

```
0    NaN
1    NaN
Name: c, dtype: Float64
```

> This behavior suddenly manifested when I upgraded to version 1.4.2. I am grabbing a table from Big Query and some of the columns are set to Int64Dtype.

@YunJD AFAICT The code sample in the OP gave the same output in prior versions of pandas. Have you got an reproducible code sample (preferably without using Big Query) that demonstrates the behavioral change

**Comment by YunJD** [comment] 2022-04-10 18:30
@simonjayhawkins I can confirm the behaviour was consistent in 1.4.0.

Reverting back to our old configuration, the type was indeed using `numpy.dtype('int64')` rather than `Int64Dtype()`.  I have some other details that I find curious, and I will jump on the other open issue to add them.
