### ISSUE TITLE
ENH: Add a `reset` parameter to `cumsum`

### ISSUE THREAD

**Issue by JivanRoquet** [pandas-dev/pandas#44690] opened 2021-11-30 11:58 UTC
#### Is your feature request related to a problem?

There is a plethora of StackOverflow questions on how to reset the cumsum based on some criteria. The most common scenario seems to be to reset the cumsum on 0 or NaN values, so that it produces the following results (example with reset on NaN):

```
orig     cumsum
 1.0        1.0
 1.5        2.5
-2.0        0.5
 NaN        0.0
 1.0        1.0
-0.5        0.5
```

The problem is that there doesn't seem to be any standard way to do this, and the most commonly used methods are cumbersome and highly error-prone, despite the actual problem being conceptually simple (just reset the cumsum when encountering some criteria).

#### Describe the solution you'd like

Using a `reset` parameter could make resetting the cumsum as simple as:

```python
c = df['orig'].cumsum(reset=df['orig'].isnull())
```

Optionally, there could be a `reset_init` optional parameter which would be `0` by default, which would allow the cumsum to be set to `reset_init` value when encountering the reset condition.

#### API breaking implications

As this would be a new optional parameter (`None` by default), I don't see any potential API breaking.

#### Describe alternatives you've considered

The alternative is using a complicated series of unintuitive combinations of `cumsum` to get to the desired result.

An example of such convoluted way that is currently available is of the form:

```pyhon
v = pd.Series([1., 3., 1., np.nan, 1., 1., 1., 1., np.nan, 1.])
cumsum = v.cumsum().fillna(method='pad')
reset = -cumsum[v.isnull()].diff().fillna(cumsum)
result = v.where(v.notnull(), reset).cumsum()
```

Which is extremely hard to read and, again, makes a very complicated solution for what is conceptually a simple problem.

**Comment by jreback** [comment] 2021-11-30 12:02
pls show examples of the use (a naive or error prone implementation is fine) as well as links to SO posts

**Comment by JivanRoquet** [comment] 2021-11-30 12:07
Examples of questions/posts that show interest in this (mostly StackOverflow but not only):

- https://stackoverflow.com/questions/45964740/python-pandas-cumsum-with-reset-everytime-there-is-a-0
- https://stackoverflow.com/questions/18196811/cumsum-reset-at-nan
- https://stackoverflow.com/questions/55880900/pandas-cumsum-that-resets-when-some-value-is-reached
- https://stackoverflow.com/questions/43524997/cumsum-entire-table-and-reset-at-zero
- https://stackoverflow.com/questions/53079313/cumsum-reset-based-on-a-condition-in-pandas
- https://newbedev.com/python-pandas-cumsum-with-reset-everytime-there-is-a-0
- https://github.com/pandas-dev/pandas/issues/27935

**Comment by jreback** [comment] 2021-11-30 12:37
suggestion on the other issue was to see if numpy would implement 

also not averse to having an implementation in pandas by a community PR

**Comment by jbrockmendel** [comment] 2021-12-01 21:01
is this a duplicate of #27935?

**Comment by JivanRoquet** [comment] 2021-12-02 14:01
@jbrockmendel depends on the definition of duplicate. It's surely related, but it's a somewhat different thing.

**Comment by mroeschke** [comment] 2021-12-27 19:46
Generally appears like this is the same request as https://github.com/pandas-dev/pandas/issues/27935. https://github.com/pandas-dev/pandas/issues/27935 could be altered to generally encompass any condition besides upper/lower boundary. Closing to centralize discussion there.

**Closed by mroeschke** 2021-12-27 19:46 UTC
Labels: Enhancement, Needs Triage
