### ISSUE TITLE
Unintended behaviour (?) of item "in" Series 

### ISSUE THREAD

**Issue by me9hanics** [pandas-dev/pandas#57435] opened 2024-02-15 15:30 UTC
### Pandas version checks

- [] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

mySeries = pd.Series(["a", "b", "c"])
print("a" in mySeries)
print("a" in mySeries.tolist())
```

### Issue Description

The returns:

```
False
True
```

When trying to check if a character is in a Pandas series, unlike with general lists, the "in" keyword returns False even when the element is in the series.

This is quite unexpected. Of course there are simple workarounds, and I think one could probably explain why this is not a feature, but the False value can be very confusing and it would be better to throw an error. I'm not sure if this is not a Python mistake however (a limitation of the keyword "in" maybe).

I did not find this reported among the issues.

### Expected Behavior

```python
import pandas as pd

mySeries = pd.Series(["a", "b", "c"])
print("a" in mySeries)
print("a" in mySeries.tolist())

```

Results:

```
True
True
```

---or---

Any type of error thrown

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f538741432edf55c6b9fb5d0d496d2dd1d7c2457
python                : 3.10.11.final.0
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22000
machine               : AMD64
processor             : Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : Hungarian_Hungary.1250

pandas                : 2.2.0
numpy                 : 1.26.1
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 65.5.0
pip                   : 23.0.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : 5.1.0
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.17.2
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2023.12.2
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : 0.58.1
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.11.4
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : 2.0.1
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by mroeschke** [comment] 2024-02-15 17:41
Thanks for the report. This is the intended behavior as documented in https://pandas.pydata.org/docs/user_guide/dsintro.html#series-is-dict-like

There is an open issue discussing changing this behavior (I can't find it right now) so closing

**Closed by mroeschke** 2024-02-15 17:41 UTC
Labels: Bug, Needs Triage
