### ISSUE TITLE
netCDF4 / cftime real_datetime object is not supported

### ISSUE THREAD

**Issue by TimoRoth** [pandas-dev/pandas#23419] opened 2018-10-30 14:18 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas, numpy, netCDF4
time=netCDF4.num2date([0,1,2,3,4,5,500,1000], 'days since 1801-10-01')
pandas.Series(numpy.arange(len(time)), index=time)
```
#### Problem description

NetCDF4 is giving us arrays with cftime.real_datetime objects in them, which leads to the following error:

```
>>> import pandas, numpy, netCDF4
>>> time=netCDF4.num2date([0,1,2,3,4,5,500,1000], 'days since 1801-10-01')
>>> pandas.Series(numpy.arange(len(time)), index=time)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/timo/oggm_venv/lib/python3.7/site-packages/pandas/core/series.py", line 183, in __init__
    index = _ensure_index(index)
  File "/home/users/timo/oggm_venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4974, in _ensure_index
    return Index(index_like)
  File "/home/users/timo/oggm_venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 417, in __new__
    name=name, **kwargs)
  File "/home/users/timo/oggm_venv/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 399, in __new__
    yearfirst=yearfirst)
  File "/home/users/timo/oggm_venv/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 467, in to_datetime
    result = _convert_listlike(arg, box, format)
  File "/home/users/timo/oggm_venv/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 368, in _convert_listlike
    require_iso8601=require_iso8601
  File "pandas/_libs/tslib.pyx", line 492, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 544, in pandas._libs.tslib.array_to_datetime
AttributeError: 'real_datetime' object has no attribute 'nanosecond'
```

#### Expected Output

Well, not an error would be nice.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.78-gentoo
machine: x86_64
processor: Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 3.9.3
pip: 18.1
setuptools: 40.5.0
Cython: 0.29
numpy: 1.15.3
scipy: 1.1.0
pyarrow: None
xarray: 0.10.9
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

netCDF4 version is 1.4.2

**Comment by jbrockmendel** [comment] 2018-10-30 15:55
I’m guessing these subclass datetime.datetime?

**Comment by gfyoung** [comment] 2018-10-30 16:57
IIUC, this looks like an ask to support another class object for indexing purposes.  Not sure if that is something we want to do *per se*...

cc @jreback

**Comment by fmaussion** [comment] 2018-10-30 17:00
cc @spencerkclark @jhamman as developers of cftime (https://github.com/Unidata/cftime) - indeed I'm not sure if this is a pandas issue or a cftime issue...

**Comment by jbrockmendel** [comment] 2018-10-30 17:10
It looks like `real_datetime` does subclass `datetime.datetime`.  The issue is caused by the fact that pandas' timestamp-conversion functions uses a heuristic that assumes that any datetime-subclass is a `pd.Timestamp`.

@TimoRoth can you try pinning a `nanosecond = 0` attribute to `real_datetime` and see if that solves the problem?

**Comment by jhamman** [comment] 2018-10-30 17:18
@spencerkclark is going to be the definitive solution here. He wrote the [CFTimeIndex](http://xarray.pydata.org/en/latest/generated/xarray.CFTimeIndex.html#xarray.CFTimeIndex) to provide the sort of functionality that @TimoRoth is trying to achieve here.

**Comment by TimoRoth** [comment] 2018-10-30 18:54
> @TimoRoth can you try pinning a `nanosecond = 0` attribute to `real_datetime` and see if that solves the problem?

I added "if not hasattr(t, 'nanosecond'): t.nanosecond = 0" and it now runs through smoothly.

An idea I would have to address this on the pandas side would be to replace PyDateTime_CheckExact(val) check at
https://github.com/pandas-dev/pandas/blob/7191af9b47f6f57991abdb20625d9563877370a2/pandas/_libs/tslib.pyx#L539
with a hasattr(val, 'nanosecond'), assuming that's possible in that context.

**Comment by jbrockmendel** [comment] 2018-10-30 19:05
We considered that and decided against it because of the performance impact; `hasattr` is a python call whereas `PyDateTime_CheckExact` is a C call.

We may be able to figure out a C-speed way to do a check equivalent to `isinstance(obj, _Timestamp)`.

**Comment by spencerkclark** [comment] 2018-10-30 19:56
Yes, @TimoRoth, I would recommend trying an `xarray.CFTimeIndex`.  The one caveat is that it requires using purely objects that inherit from `cftime.datetime` objects (which mimic `datetime.datetime` objects, but don't ultimately inherit from them), but this is easily accomplished in recent versions of cftime which include an `only_use_cftime_datetimes` argument to `num2date`.  Here's a short example:
```
In [1]: import cftime; import pandas as pd; import xarray as xr

In [2]: times = cftime.num2date([0,1,2,3,4,5,500,1000], units='days since 1801-10-01',
   ...:                         only_use_cftime_datetimes=True)

In [3]: pd.Series(range(len(times)), index=xr.CFTimeIndex(times))
Out[3]:
1801-10-01 00:00:00    0
1801-10-02 00:00:00    1
1801-10-03 00:00:00    2
1801-10-04 00:00:00    3
1801-10-05 00:00:00    4
1801-10-06 00:00:00    5
1803-02-13 00:00:00    6
1804-06-27 00:00:00    7
dtype: int64
```

**Comment by fmaussion** [comment] 2018-11-06 11:34
We have solved the issue downstream, but it still looks like a regression to me (it used to work - albeit possibly for the wrong reasons). Do you by chance know what broke here? Is it a change in netcdf4/cftime or a change in pandas?

**Comment by jreback** [comment] 2018-11-06 11:38
I suppose we would take a patch to let arbitrary datetime like scalars here but these are not supported in any way

**Comment by spencerkclark** [comment] 2018-11-06 12:39
> Do you by chance know what broke here?

@fmaussion it looks like a recent change in cftime broke this.  In the past for standard calendars, by default `cftime.num2date` would return an array of normal `datetime.datetime` objects.  As of https://github.com/Unidata/cftime/pull/66 it now returns an array of `cftime.real_datetime` objects (which subclass `datetime.datetime`).

So I agree with @jreback that this is not a pandas issue -- it might be worth bringing this up in the cftime issue tracker to discuss options there.

**Comment by fmaussion** [comment] 2018-11-06 13:33
Thanks panda team for the quick help! 

We move the discussion to https://github.com/Unidata/cftime/issues/77 instead. 

Feel free to close the issue, for some reason I can't do it

**Closed** 2018-11-06 14:16 UTC
Labels: Enhancement, Indexing, Needs Discussion, Timeseries
