### ISSUE TITLE
BUG: AttributeError: 'PandasArray' object has no attribute '_str_len'

### ISSUE THREAD

**Issue by wellingtonf-souza** [pandas-dev/pandas#40404] opened 2021-03-12 18:26 UTC
I am having the following error.

Python 3.7.4 (default, Aug 9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

import pandas as pd
pd.version

'1.1.5'

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

Traceback (most recent call last):
File "", line 1, in
File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 751, in repr
show_dimensions=show_dimensions,
File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 883, in to_string
return formatter.to_string(buf=buf, encoding=encoding)
File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
return self.get_result(buf=buf, encoding=encoding)
File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
self.write_result(buf=f)
File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
max_len = Series(lines).str.len().max()
File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\strings\accessor.py", line 2579, in len
result = self._data.array._str_len()
AttributeError: 'PandasArray' object has no attribute '_str_len'

**Comment by MarcoGorelli** [comment] 2021-03-12 18:54
Hi @wellingtonf-souza 

`pandas` doesn't have an attribute `version`, can you please check your example?

I also couldn't reproduce:
```python
>>> import pandas as pd
>>> pd.__version__
'1.1.5'
>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4
```

**Comment by MarcoGorelli** [comment] 2021-03-13 15:08
closing to keep the queue down, but please ping if you revise your example

**Comment by wellingtonf-souza** [comment] 2021-03-15 01:25
Sorry, the correct one was "pd .__ version__", I just typed it wrong. But the error occurs after this part.

Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__version__
'1.1.5'
>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> pd.DataFrame(data=d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 751, in __repr__
    show_dimensions=show_dimensions,
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 883, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
    self.write_result(buf=f)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
    max_len = Series(lines).str.len().max()
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\strings\accessor.py", line 2579, in len
    result = self._data.array._str_len()
AttributeError: 'PandasArray' object has no attribute '_str_len'
>>>

**Comment by wellingtonf-souza** [comment] 2021-03-15 01:26
Sorry, the correct one was "pd .__ version__", I just typed it wrong. But the error occurs after this part.
``Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__version__
'1.1.5'
>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> pd.DataFrame(data=d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 751, in __repr__
    show_dimensions=show_dimensions,
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 883, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
    self.write_result(buf=f)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
    max_len = Series(lines).str.len().max()
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\strings\accessor.py", line 2579, in len
    result = self._data.array._str_len()
AttributeError: 'PandasArray' object has no attribute '_str_len'
>>>

**Comment by wellingtonf-souza** [comment] 2021-03-15 01:29
Sorry, the correct one was "pd .__ version__", I just typed it wrong. But the error occurs after this part.

Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
`import pandas as pd`
`pd.__version__`
'1.1.5'
`d = {'col1': [1, 2], 'col2': [3, 4]}`
`pd.DataFrame(data=d)`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 751, in __repr__
    show_dimensions=show_dimensions,
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 883, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
    self.write_result(buf=f)
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
    max_len = Series(lines).str.len().max()
  File "C:\Users\wellington.souza\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\strings\accessor.py", line 2579, in len
    result = self._data.array._str_len()
AttributeError: 'PandasArray' object has no attribute '_str_len'

**Comment by MarcoGorelli** [comment] 2021-03-15 08:34
No worries - next time please copy-and-paste

Can you also show the output of `pd.show_versions()` (as per the issue templated)?

**Comment by wellingtonf-souza** [comment] 2021-03-15 11:34
`pd.show_versions()`

INSTALLED VERSIONS
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : pt_BR.UTF-8
LOCALE           : None.None

pandas           : 1.1.5
numpy            : 1.16.5
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 5.2.1
hypothesis       : 5.36.1
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.1
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : 0.9.3
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fsspec           : 0.5.2
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.9
tables           : 3.5.2
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.45.1

**Comment by MarcoGorelli** [comment] 2021-03-15 19:04
Thanks @wellingtonf-souza 

Still can't reproduce, could you try [making a new conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html), install pandas==1.1.5, and trying again?

**Comment by wellingtonf-souza** [comment] 2021-03-16 00:28
With a new environment it runs normally

**Comment by MarcoGorelli** [comment] 2021-03-21 15:25
OK, I don't know what the issue was in the other environment but it sounds like it wasn't related to pandas, so closing for now

**Comment by niall0** [comment] 2021-03-21 23:00
I fixed the same problem with the following:

pd.set_option("display.max_columns", None)

Possibly something broke with the latest version of pandas whereby the '_str_len' attribute seems to no longer exist.
If you don't like the way the results are displayed when you use the "pd.set_option("display.max_columns", None)" solution, you can also fix the issue by editing line 844 in the Anaconda3\Lib\site-packages\pandas\io\formats\format.py file (in Windows) from:

max_len = Series(lines).str.len().max()

to:

max_len = len(str(Series(lines).values.max()))

which avoids use of the .len() method, which is the cause of the error being thrown. However I am relatively new to python coding and perhaps editing a package file in this way is considered bad practice!

I am running python 3.8 with anaconda, my version of pandas is 1.2.3.

**Comment by MarcoGorelli** [comment] 2021-03-22 19:08
Thanks @niall0 for the report

Do you have a self-contained example that we can run with which we can reproduce the error?

**Comment by niall0** [comment] 2021-03-22 22:32
Hi @MarcoGorelli 

Yes, here is a simple example:

```
import pandas as pd

df = pd.DataFrame(
    {
        "column_name1": [1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
        "column_name2": [2.1, 2.2, 2.3, 2.4, 2.5, 2.6],
        "column_name3": [3.1, 3.2, 3.3, 3.4, 3.5, 3.6],
        "column_name4": [4.1, 4.2, 4.3, 4.4, 4.5, 4.6],
        "column_name5": [5.1, 5.2, 5.3, 5.4, 5.5, 5.6],
        "column_name6": [6.1, 6.2, 6.3, 6.4, 6.5, 6.6],
    }
)

print(df.describe())
```
Produces the following error:

```
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-64ea50983177>", line 1, in <module>
    runfile('C:/Users/User/PycharmProjects/hoML/housing/example.py', wdir='C:/Users/User/PycharmProjects/hoML/housing')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/User/PycharmProjects/hoML/housing/example.py", line 14, in <module>
    print(df.describe())
  File "C:\Users\User\Anaconda3\lib\site-packages\pandas\core\frame.py", line 744, in __repr__
    self.to_string(
  File "C:\Users\User\Anaconda3\lib\site-packages\pandas\core\frame.py", line 883, in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
  File "C:\Users\User\Anaconda3\lib\site-packages\pandas\io\formats\format.py", line 921, in to_string
    return self.get_result(buf=buf, encoding=encoding)
  File "C:\Users\User\Anaconda3\lib\site-packages\pandas\io\formats\format.py", line 520, in get_result
    self.write_result(buf=f)
  File "C:\Users\User\Anaconda3\lib\site-packages\pandas\io\formats\format.py", line 844, in write_result
    max_len = Series(lines).str.len().max()
  File "C:\Users\User\Anaconda3\lib\site-packages\pandas\core\strings\accessor.py", line 2579, in len
    result = self._data.array._str_len()
AttributeError: 'PandasArray' object has no attribute '_str_len'
```
FYI, I get the same error when I run

`print(df.head())
`

Now  add the max_columns option to my original code block:

```
import pandas as pd

df = pd.DataFrame(
    {
        "column_name1": [1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
        "column_name2": [2.1, 2.2, 2.3, 2.4, 2.5, 2.6],
        "column_name3": [3.1, 3.2, 3.3, 3.4, 3.5, 3.6],
        "column_name4": [4.1, 4.2, 4.3, 4.4, 4.5, 4.6],
        "column_name5": [5.1, 5.2, 5.3, 5.4, 5.5, 5.6],
        "column_name6": [6.1, 6.2, 6.3, 6.4, 6.5, 6.6],
    }
)

pd.set_option("display.max_columns", None)
print(df.describe())

```

Produces the following output:

```
       column_name1  column_name2  column_name3  column_name4  column_name5  \
count      6.000000      6.000000      6.000000      6.000000      6.000000   
mean       1.350000      2.350000      3.350000      4.350000      5.350000   
std        0.187083      0.187083      0.187083      0.187083      0.187083   
min        1.100000      2.100000      3.100000      4.100000      5.100000   
25%        1.225000      2.225000      3.225000      4.225000      5.225000   
50%        1.350000      2.350000      3.350000      4.350000      5.350000   
75%        1.475000      2.475000      3.475000      4.475000      5.475000   
max        1.600000      2.600000      3.600000      4.600000      5.600000   
       column_name6  
count      6.000000  
mean       6.350000  
std        0.187083  
min        6.100000  
25%        6.225000  
50%        6.350000  
75%        6.475000  
max        6.600000  
```

Alternatively,  editing line 844 in the Anaconda3\Lib\site-packages\pandas\io\formats\format.py file (in Windows) from:

`max_len = Series(lines).str.len().max()`

to:

`max_len = len(str(Series(lines).values.max()))
`

And running the following code block:
```
import pandas as pd

df = pd.DataFrame(
    {
        "column_name1": [1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
        "column_name2": [2.1, 2.2, 2.3, 2.4, 2.5, 2.6],
        "column_name3": [3.1, 3.2, 3.3, 3.4, 3.5, 3.6],
        "column_name4": [4.1, 4.2, 4.3, 4.4, 4.5, 4.6],
        "column_name5": [5.1, 5.2, 5.3, 5.4, 5.5, 5.6],
        "column_name6": [6.1, 6.2, 6.3, 6.4, 6.5, 6.6],
    }
)

print(df.describe())
```

I get the following output:
```
       column_name1  column_name2  ...  column_name5  column_name6
count      6.000000      6.000000  ...      6.000000      6.000000
mean       1.350000      2.350000  ...      5.350000      6.350000
std        0.187083      0.187083  ...      0.187083      0.187083
min        1.100000      2.100000  ...      5.100000      6.100000
25%        1.225000      2.225000  ...      5.225000      6.225000
50%        1.350000      2.350000  ...      5.350000      6.350000
```

I'm using the pycharm console, here is some information that gets spat out when I execute the code:
```
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\User\\PycharmProjects\\hoML\\housing', 'C:/Users/User/PycharmProjects/hoML/housing'])
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.18.1
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] on win32
```

And I've installed pandas version 1.2.3.  

It seems all that the format.py script is doing is formatting the output to make it look ok when printed, but the original version of the code relies on the .len() method which uses the ._str_len attribute, which is missing. 

I hope this helps!

Niall

**Comment by MarcoGorelli** [comment] 2021-04-04 20:11
I still can't reproduce - is this all I need to run?
```python
import pandas as pd

df = pd.DataFrame(
    {
        "column_name1": [1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
        "column_name2": [2.1, 2.2, 2.3, 2.4, 2.5, 2.6],
        "column_name3": [3.1, 3.2, 3.3, 3.4, 3.5, 3.6],
        "column_name4": [4.1, 4.2, 4.3, 4.4, 4.5, 4.6],
        "column_name5": [5.1, 5.2, 5.3, 5.4, 5.5, 5.6],
        "column_name6": [6.1, 6.2, 6.3, 6.4, 6.5, 6.6],
    }
)

print(df.describe())
```
?
Because it works fine for me in an IPython repl on master:
```
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd
   ...: 
   ...: df = pd.DataFrame(
   ...:     {
   ...:         "column_name1": [1.1, 1.2, 1.3, 1.4, 1.5, 1.6],
   ...:         "column_name2": [2.1, 2.2, 2.3, 2.4, 2.5, 2.6],
   ...:         "column_name3": [3.1, 3.2, 3.3, 3.4, 3.5, 3.6],
   ...:         "column_name4": [4.1, 4.2, 4.3, 4.4, 4.5, 4.6],
   ...:         "column_name5": [5.1, 5.2, 5.3, 5.4, 5.5, 5.6],
   ...:         "column_name6": [6.1, 6.2, 6.3, 6.4, 6.5, 6.6],
   ...:     }
   ...: )
   ...: 
   ...: print(df.describe())
       column_name1  column_name2  ...  column_name5  column_name6
count      6.000000      6.000000  ...      6.000000      6.000000
mean       1.350000      2.350000  ...      5.350000      6.350000
std        0.187083      0.187083  ...      0.187083      0.187083
min        1.100000      2.100000  ...      5.100000      6.100000
25%        1.225000      2.225000  ...      5.225000      6.225000
50%        1.350000      2.350000  ...      5.350000      6.350000
75%        1.475000      2.475000  ...      5.475000      6.475000
max        1.600000      2.600000  ...      5.600000      6.600000

[8 rows x 6 columns]
```

Likewise, it works for me on 1.2.3, so not sure what to do here

**Comment by niall0** [comment] 2021-04-07 14:30
Hi @MarcoGorelli, yes - without my edit to the format.py file, or specifying display.max_columns to None, I get an error. But I see you are on a slightly newer version of python, 3.8.6 versus my version 3.8.5, so perhaps this bug has been fixed in the newer release.

Best wishes

Niall

**Comment by MarcoGorelli** [comment] 2021-04-07 15:04
@niall0 could you try in a new virtual environment, in which you only install pandas and then don't modify any files in site-packages?

**Comment by niall0** [comment] 2021-04-12 12:21
Hi @MarcoGorelli  - I haven't set up a virtual environment before but I can give it a go. Not sure when I will get to it though!

**Comment by kild95** [comment] 2021-04-15 00:01
@niall0 - just a note to say that I was experiencing this today, but by simply updating pandas, the problem no longer persists.

I had been on pandas version 1.0.5

This is my current env setup that I have had success on: 
![image](https://user-images.githubusercontent.com/47833090/114795227-f17f8280-9d42-11eb-9dca-0982f1fb7267.png)

**Comment by MarcoGorelli** [comment] 2021-04-15 06:25
Thanks @kild95 - do you have a reproducible example so we can check when it was fixed?

**Comment by MarcoGorelli** [comment] 2021-04-15 06:29
Seeing as both you and @niall0 mention pandas-profiling, I'm inclined to suggest the bug might be there

**Comment by kild95** [comment] 2021-04-15 15:47
@MarcoGorelli - Sorry, but I don't have a reproducible example as I was using sensitive datasets from work. 

That said, the only thing I had to do was update pandas (using conda). 
I did not change any formatting of my data, add any 'hacky' workaround, nor did I need to update any other package.

You are correct in that this error arose when I was using pandas-profiling, but I was on version 2.10.0 of that throughout.

Hope this extra info is of some help, in lieu of a reproducible example!

**Comment by MarcoGorelli** [comment] 2021-04-25 17:42
Every single post here (without exception) has some link to pandas-profiling, and there are people on that repo commenting about this issue, so I'd suggest taking the issue forward there: https://github.com/pandas-profiling/pandas-profiling/issues/662

**Comment by MarcoGorelli** [comment] 2021-05-03 11:20
closing as per the above, if anyone has a reproducible example which doesn't involve pandas-profiling then please post and and I'll reopen

**Closed by MarcoGorelli** 2021-05-03 11:20 UTC
Labels: Closing Candidate, Needs Info

**Comment by qoffee** [comment] 2021-05-17 11:15
I have the same error with version of pandas==1.1.4
On line:
`print(outputs.head())`
Full Traceback is:
`tip/models/base.py:57: in wrapper
    decorated(self, **kwargs)
tip/models/dl_models/gcn_ppi_model/model.py:161: in predict
    print(outputs.head())
/opt/miniconda/lib/python3.7/site-packages/pandas/core/frame.py:751: in __repr__
    show_dimensions=show_dimensions,
/opt/miniconda/lib/python3.7/site-packages/pandas/core/frame.py:883: in to_string
    return formatter.to_string(buf=buf, encoding=encoding)
/opt/miniconda/lib/python3.7/site-packages/pandas/io/formats/format.py:921: in to_string
    return self.get_result(buf=buf, encoding=encoding)
/opt/miniconda/lib/python3.7/site-packages/pandas/io/formats/format.py:520: in get_result
    self.write_result(buf=f)
/opt/miniconda/lib/python3.7/site-packages/pandas/io/formats/format.py:844: in write_result
    max_len = Series(lines).str.len().max()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <pandas.core.strings.accessor.StringMethods object at 0x7f035403a390>
    def len(self):
        """
        Compute the length of each element in the Series/Index.
    
        The element may be a sequence (such as a string, tuple or list) or a collection
        (such as a dictionary).
    
        Returns
        -------
        Series or Index of int
            A Series or Index of integer values indicating the length of each
            element in the Series or Index.
    
        See Also
        --------
        str.len : Python built-in function returning the length of an object.
        Series.size : Returns the length of the Series.
    
        Examples
        --------
        Returns the length (number of characters) in a string. Returns the
        number of entries for dictionaries, lists or tuples.
    
        >>> s = pd.Series(['dog',
        ...                 '',
        ...                 5,
        ...                 {'foo' : 'bar'},
        ...                 [2, 3, 5, 7],
        ...                 ('one', 'two', 'three')])
        >>> s
        0                  dog
        1
        2                    5
        3       {'foo': 'bar'}
        4         [2, 3, 5, 7]
        5    (one, two, three)
        dtype: object
        >>> s.str.len()
        0    3.0
        1    0.0
        2    NaN
        3    1.0
        4    4.0
        5    3.0
        dtype: float64
        """
>       result = self._data.array._str_len()
E       AttributeError: 'PandasArray' object has no attribute '_str_len'
/opt/miniconda/lib/python3.7/site-packages/pandas/core/strings/accessor.py:2579: AttributeError`

**Comment by MarcoGorelli** [comment] 2021-05-17 12:02
@qoffee do you have a reproducible example?

**Comment by Ash1One** [comment] 2021-08-24 09:56
I have met the same error with pandas == 1.2.4, and it was installed by pip.
Then I reinstall pandas 1.2.4 from conda-forge, no error report again.
