### ISSUE TITLE
value assignment bug for multi-indexed dataframes in v1.0.0rc0

### ISSUE THREAD

**Issue by leo4183** [pandas-dev/pandas#30892] opened 2020-01-10 16:52 UTC
#### Problem Description
in new pre-release 1.0.0.rc0, sliced value assignment for multi-indexed dataframe with duplicated datetime indices would fail

```python
import pandas as pd
x = pd.DataFrame([[1,2,3],['a','a','c']],index=['c1','index2'],
                 columns=pd.to_datetime(['20190101','20190101','20190102'])).T
x['c2'] = np.nan
x.index.name = 'index1'
x.set_index(['index2'],append=True,inplace=True)


In [0]: x
Out[0]:
                 c1  c2
index1   index2       
20190101 a       1  NaN
         a       2  NaN
20190102 c       3  NaN


x.loc[(pd.to_datetime('20190101'),'a'),'c2'] = 1.0     # ok
x.loc[[(pd.to_datetime('20190101'),'a')],'c2'] = 1.0   # ValueError
```

**Comment by jorisvandenbossche** [comment] 2020-01-12 19:32
@leo4183 Thanks a lot for trying out 1.0.0rc, and for the report! That's indeed a regression.

cc @jbrockmendel from the traceback, this seems to be caused by the exception cleaning from https://github.com/pandas-dev/pandas/pull/28361. Can you take a look?

**Comment by jbrockmendel** [comment] 2020-01-12 20:25
Will take a look

**Comment by TomAugspurger** [comment] 2020-01-22 14:19
@jbrockmendel did you have a chance to look into this?

**Comment by jbrockmendel** [comment] 2020-01-27 17:28
Looks like catching InvalidIndexError in the spot @jorisvandenbossche pointed out in #28361 fixes one of the two problems (on master both of the examples raise, not just the second).  i expect that the other can be fixed by catching elsewhere fairly high-up.  I'll get a PR for this in hopefully today.

Longer-term, the underlying problem looks like MultiIndex.get_loc is doing something weird that we need to dig into.

**Closed** 2020-01-28 01:59 UTC
Labels: Indexing, Regression
