### ISSUE TITLE
BUG: raised error when converting (`.dt.tz_convert`) a NaT Series

### ISSUE THREAD

**Issue by igonro** [pandas-dev/pandas#47592] opened 2022-07-04 06:33 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
>>> df1 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': [np.nan,np.nan,np.nan,'2022-07-02T09:45:33Z',np.nan]})
>>> df2 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': [np.nan,np.nan,np.nan,np.nan,np.nan]})
>>> pd.to_datetime(df1['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce").dt.tz_convert("Europe/Madrid").dt.tz_localize(None)
0                   NaT
1                   NaT
2                   NaT
3   2022-07-02 11:45:33
4                   NaT
Name: resolved, dtype: datetime64[ns]
>>> pd.to_datetime(df2['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce").dt.tz_convert("Europe/Madrid").dt.tz_localize(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/accessor.py", line 94, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/accessors.py", line 123, in _delegate_method
    result = method(*args, **kwargs)
  File "/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 268, in tz_convert
    arr = self._data.tz_convert(tz)
  File "/home/x/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py", line 874, in tz_convert
    raise TypeError(
TypeError: Cannot convert tz-naive timestamps, use tz_localize to localize
```

### Issue Description

`.dt.tz_convert` is able to transform a Series with mixed tz-aware datetimes and NaTs, but it raises an error when trying to convert a Series with only NaTs.

I understand that this error should be the expected when having tz-naive datetimes (for example "2022-07-02 09:45:33" instead of "2022-07-02T09:45:33Z"), but when trying to convert a Series of NaTs I think that everyone would expect a Series of NaTs as well.

### Expected Behavior

Expected behaviour:
- **Return a Series of NaT when converting a Series of NaT**

```python
>>> pd.to_datetime(df2['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce").dt.tz_convert("Europe/Madrid")
0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
```

Keep the behaviour of:
- Return a Series of NaT and converted tz datetimes when converting a Series of NaT and tz-aware datetimes.
- Raise `Cannot convert tz-naive timestamps, use tz_localize to localize` error when converting a Series with tz-naive datetimes.

### Installed Versions

<details>

commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 58.0.4
pip              : 21.2.4
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.2.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by igonro** [comment] 2022-07-08 06:05
Hi @ProgrammingDao, thanks for your response.

You're right. It is the `pd.to_datetime` the one who is generating some inconsistency in these two cases. I don't have the answer to your question, I think other people would be in a better position to figure out which is the best option. But I do think that this behaviour should be consistent.

So I think: either it sets to UTC in the second case, or it doesn't sets to UTC in either case.

**Comment by simonjayhawkins** [comment] 2022-07-23 11:50
Thanks @igonro for the report.

> Hi @ProgrammingDao, thanks for your response.
> 
> You're right. It is the `pd.to_datetime` the one who is generating some inconsistency in these two cases. I don't have the answer to your question, I think other people would be in a better position to figure out which is the best option. But I do think that this behaviour should be consistent.
> 
> So I think: either it sets to UTC in the second case, or it doesn't sets to UTC in either case.

This is expected [documented](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) behavior

> utc : bool, default None
> Control timezone-related parsing, localization and conversion.

>
> If True, the function always returns a timezone-aware UTC-localized [Timestamp](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html#pandas.Timestamp), [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html#pandas.Series) or [DatetimeIndex](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html#pandas.DatetimeIndex). To do this, timezone-naive inputs are localized as UTC, while timezone-aware inputs are converted to UTC.

>
> If False (default), inputs will not be coerced to UTC. Timezone-naive inputs will remain naive, while timezone-aware ones will keep their time offsets. Limitations exist for mixed offsets (typically, daylight savings), see [Examples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html?highlight=to_datetime#to-datetime-tz-examples) section for details.

>
> See also: pandas general documentation about [timezone conversion and localization](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#time-zone-handling).

given this, I think the title of this issue may not be representative of the problem? and that the exception raised is appropriate?

**Comment by igonro** [comment] 2022-07-27 10:21
Hi @simonjayhawkins,

Yes, it would be hard to justify this behavior as a bug. Yet I still think the behavior is not 100% correct according the documentation (or maybe the documentation should explain this behavior).

```python
>>> df1 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': [np.nan,np.nan,np.nan,'2022-07-02T09:45:33Z',np.nan]})
>>> df2 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': [np.nan,np.nan,np.nan,np.nan,np.nan]})
>>> df3 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': ['2022-07-02 09:53:21',np.nan,np.nan,'2022-07-02T09:45:33Z',np.nan]})
>>> pd.to_datetime(df1['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce")
0                         NaT
1                         NaT
2                         NaT
3   2022-07-02 09:45:33+00:00
4                         NaT
Name: resolved, dtype: datetime64[ns, UTC]
>>> pd.to_datetime(df2['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce")
0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: resolved, dtype: datetime64[ns]
>>> pd.to_datetime(df3['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce")
0          2022-07-02 09:53:21
1                          NaN
2                          NaN
3    2022-07-02 09:45:33+00:00
4                          NaN
Name: resolved, dtype: object
```

In this example, we have:
- NaNs are converted to UTC NaTs for `df1`
- NaNs are converted to tz-naive NaTs for `df2`
- NaNs are kept as NaNs because we have a mixed Series with tz-naive and tz-aware datetimes.

If NaNs are interpreted as tz-naive NaTs, then the 1st case... shouldn't return an object Series?
```python
# Expected behavior according to my understanding of the docs (?)
>>> pd.to_datetime(df1['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce")
0                         NaN
1                         NaN
2                         NaN
3   2022-07-02 09:45:33+00:00
4                         NaN
Name: resolved, dtype: object
```

As this case is very specific and complex, I don't think the behavior should change because I'm not sure if the behavior I expect is the desirable behavior. 
Maybe it's fine as it is. In this case, I think the docs should be updated to point out that sometimes NaN values are considered as tz-naive and sometimes tz-aware.

Again, this case is very specific and complex, and I could fix my error after I understood what was the behavior without much trouble. But maybe the docs could be a bit better if it includes some of these examples. The documentation of pandas is one of the best I've seen, and adding these details could be helpful for someone (?)

Thanks! 🙂

**Comment by igonro** [comment] 2022-07-27 10:30
PS: my suggestion in case it's preferable to modify the behavior and leave the docs as it is would be:

```python
>>> df1 = pd.DataFrame({'id': [1,2,3,4,5], 'resolved': [np.nan,np.nan,np.nan,'2022-07-02T09:45:33Z',np.nan]})
>>> pd.to_datetime(df1['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce", utc=True)
0                         NaT
1                         NaT
2                         NaT
3   2022-07-02 09:45:33+00:00
4                         NaT
Name: resolved, dtype: datetime64[ns, UTC]
>>> pd.to_datetime(df1['resolved'], format="%Y-%m-%dT%H:%M:%S", errors="coerce")
0                         NaN
1                         NaN
2                         NaN
3   2022-07-02 09:45:33+00:00
4                         NaN
Name: resolved, dtype: object
```

Currently both `utc=True` and `utc=False` return a Series of dtype `datetime64[ns, UTC]` .

**Comment by simonjayhawkins** [comment] 2022-07-27 14:45
Thanks @igonro for the comments. 

> Maybe it's fine as it is. In this case, I think the docs should be updated to point out that sometimes NaN values are considered as tz-naive and sometimes tz-aware.

The examples in the docs are fairly extensive but because the examples are using different data to your comments (and don't include missing values), probably difficult for the casual reader to grasp. Is it possible, here in the issue, to suggest the doc changes and additions you would like to see.

> If NaNs are interpreted as tz-naive NaTs, then the 1st case... shouldn't return an object Series?

NaT is a python object that is used to represent a scalar missing value (e.g. Indexing) in datetimelike arrays where the missing values are stored internally as sentinel values or using a mask.

NaT is neither tz-naive or tz-aware. These are properties of the array. So I am not sure what the question is. NaNs are treated as missing values in the array, and the result array type, tz-aware or tz-naive is determined by the other values in the data. (which cannot be determined if there are no other values for all NaN data)

I hope this code sample helps

```python
s = pd.Series(pd.date_range("2022", periods=7))
s[3] = np.nan
s[4] = None
s[5] = pd.NaT
s[6] = ""
print(s)
# 0   2022-01-01
# 1   2022-01-02
# 2   2022-01-03
# 3          NaT
# 4          NaT
# 5          NaT
# 6          NaT
# dtype: datetime64[ns]

vals = s.astype(int)
print(vals)
# 0    1640995200000000000
# 1    1641081600000000000
# 2    1641168000000000000
# 3   -9223372036854775808
# 4   -9223372036854775808
# 5   -9223372036854775808
# 6   -9223372036854775808
# dtype: int64

np.iinfo(vals.dtype).min
# -9223372036854775808
```

> * NaNs are kept as NaNs because we have a mixed Series with tz-naive and tz-aware datetimes.

Yes, the mixed case which is clearly ambiguous, casts to object. adding `utc=True` clears up the ambiguity and limitations of mixed cases is called out in the docs. Probably best not to add more complexity to this discussion.

> Currently both `utc=True` and `utc=False` return a Series of dtype `datetime64[ns, UTC]`

That's because "If False (default), inputs will not be coerced to UTC. Timezone-naive inputs will remain naive, while timezone-aware ones will keep their time offsets. Limitations exist for mixed offsets (typically, daylight savings), see [Examples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html#to-datetime-tz-examples) section for details."

so the values have timezone data and since "timezone-aware ones will keep their time offsets" and the NaNs are treated as missing values, a Series of dtype `datetime64[ns, UTC]` appears correct to me with  `utc=False` and I don't think the behavior should be changed on the basis of consistency on the mixed case.

**Comment by mroeschke** [comment] 2023-11-21 17:58
Closing as described above as the intended behavior

**Closed by mroeschke** 2023-11-21 17:58 UTC
Labels: Usage Question, Timezones, Closing Candidate
