### ISSUE TITLE
Scatter plot incorrect when 2 columns have the same name

### ISSUE THREAD

**Issue by lebigot** [pandas-dev/pandas#25606] opened 2019-03-08 11:19 UTC
```python
s1 = pd.Series(range(5), name="x")
s2 = pd.Series(range(10, 15), name="x")  # The following would work with "y" instead
pd.concat([s1, s2], axis=1).plot.scatter(x=0, y=1)
```
#### Problem description

The first column should be plotted against the second one.

Instead, it is as if the two columns were concatenated (into a 10 elements series), with the resulting new column being plotted against itself.

Everything works if the second series is named differently from the first one.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-642.6.2.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.21.1
pytest: 3.2.3
pip: 9.0.1
setuptools: 28.8.0
Cython: 0.27.3
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: 0.8.2
IPython: 5.1.0
sphinx: 1.4.4
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.2.1
numexpr: 2.6.5
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 0.9.7
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by danielwlogan** [comment] 2019-03-08 17:24
Could this issue be related to #22088?

**Comment by mroeschke** [comment] 2019-03-13 05:25
Yes this looks like a duplicate of #22088.

**Closed by mroeschke** 2019-03-13 05:25 UTC

**Comment by lebigot** [comment] 2019-03-13 08:57
I trust you guys on this one but unless there is a strong connection in the implementation between both issues, they are not the same. In fact, #22088 is about plotting a column against _itself_, while this one is about plotting a column against a *different* one that has the same name.

**Comment by mroeschke** [comment] 2019-03-13 16:11
Thanks for the explanation @lebigot. I suspect the correct fix should resolve both these issues. With that being said, I'll include your example in the first issue as another regression tests that should be tested
