### ISSUE TITLE
File mode in `to_csv` is ignored, when passing a file object instead of a path

### ISSUE THREAD

**Issue by colobas** [pandas-dev/pandas#19827] opened 2018-02-21 21:24 UTC
#### Code Sample, a copy-pastable example if possible

```
>>> import pandas as pd
>>> df = pd.read_csv("example.csv")
>>> df.head()
   just  a  file
0     1  2     3
1     4  5     6
2     7  8     9
>>> with open("someother.csv", "wb") as f:
...     df.to_csv(f, mode="wb")
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 1524, in to_csv
    formatter.save()
  File "/usr/lib/python3.6/site-packages/pandas/io/formats/format.py", line 1652, in save
    self._save()
  File "/usr/lib/python3.6/site-packages/pandas/io/formats/format.py", line 1740, in _save
    self._save_header()
  File "/usr/lib/python3.6/site-packages/pandas/io/formats/format.py", line 1708, in _save_header
    writer.writerow(encoded_labels)
TypeError: a bytes-like object is required, not 'str'
```
#### Problem description

When passing a file opened in binary mode to `df.to_csv` and also passing `mode='wb'`, this mode is ignored. I think it's because of these lines: https://github.com/pandas-dev/pandas/blob/master/pandas/io/common.py#L407-L411 and these ones: https://github.com/pandas-dev/pandas/blob/master/pandas/io/formats/format.py#L1660-L1662

It seems that `is_text` isn't passed, and so it assumes the default value of `True`

#### Expected Output
A file should just be written.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.14.20-1-lts
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.22.0
pytest: 3.4.0
pip: 9.0.1
setuptools: 38.5.1
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.7.0
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.6.0
html5lib: 1.0b10
sqlalchemy: 1.2.3
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: 0.1.2
fastparquet: 0.1.3
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by chris-b1** [comment] 2018-02-21 21:59
Isn't csv sort of fundamentally a text format?  The python csv writer, which we call out to, is ultimately what's choking.  Certainly could raise a better error.

```
In [36]: import csv

In [37]: writer = csv.writer(open('test.csv', mode='wb'))

In [38]: writer.writerow(['a', 'b', 'c'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-bb2ef92b0247> in <module>()
----> 1 writer.writerow(['a', 'b', 'c'])

TypeError: a bytes-like object is required, not 'str'
```

**Comment by colobas** [comment] 2018-02-21 22:51
It is, but sometimes you have a filesystem-sort-of-interface (like Azure's Data Lake Store one - [here](https://github.com/Azure/azure-data-lake-store-python) ) that requires files to be written in binary mode, regardless of the format.

**Comment by TomAugspurger** [comment] 2018-02-22 02:00
Does passing a ADL's file-like object to `to_csv`, without the `mode` argument, work? I know you can pass an `s3fs.S3File` opened in binary mode to `to_csv` and everything works fine.

**Comment by colobas** [comment] 2018-02-22 16:36
Hey @TomAugspurger , just tried it. Same error:

```
with adlfs_client.open("/dummy.csv", "wb") as f:
    dummy.to_csv(f)
```

As of now the workaround is to create a temporary file and upload it explicitly, so it' not like I'm stuck, but it's just ugly.

**Comment by TomAugspurger** [comment] 2018-02-22 16:48
I *think* it works for s3fs because of this line: https://github.com/pandas-dev/pandas/blob/abc4ef9132d8bcc8ad987c18fdd757595fd65d8c/pandas/io/common.py#L326

Perhaps you can wrap your `f` in an `io.TextIOWrapper`?

I'm not sure what the best way to solve this is generically.

**Comment by TomAugspurger** [comment] 2018-02-22 16:49
Perhaps just checking the buffer for a `mode` and if it's binary then we know we need to wrap in in a `TextIOWrapper`?

**Comment by colobas** [comment] 2018-02-22 18:47
I can confirm that this does work:
```
from io import TextIOWrapper

with adlfs_client.open("/dummy.csv", "wb") as f:
    buf = TextIOWrapper(f)
    dummy.to_csv(buf)
```

Thanks for the suggestion

**Comment by jreback** [comment] 2018-02-23 01:56
I suppose we could add a mini-example like this to the docs (io.rst). It is a useful case I think.
@colobas would you do a PR?

**Comment by TomAugspurger** [comment] 2018-02-23 13:22
Can anyone think of a reason not to layer a TextIOWrapper over any buffer
opened in binary mode? I wonder why the stdlib CSV writer doesn't do this.

On the one hand, the user has explicitly given a binary-mode buffer to a
thing writing text, which is "wrong". But I think there's no ambiguity to
laying
a TextIOWrapper on top of the binary buffer. We'll be using the same
default encoding as if they user had just passed a text-mode file.

**Comment by colobas** [comment] 2018-02-23 14:49
@TomAugspurger doesn't the `mode` parameter in `read_csv` stop having a purpose in that case?

**Comment by TomAugspurger** [comment] 2018-02-23 14:55
I assume you meant `to_csv`. In that case the mode still matters for write
vs. append vs. exclusive. It's just the text vs. binary part of `mode` that
would be "ignored".

Given that the current behavior is so unfriendly (raising a not great error
message), is there a harm in ignoring the text vs. binary part?

**Comment by colobas** [comment] 2018-02-23 17:35
No I think there would be no harm. I can make a PR during the weekend

**Comment by cbrnr** [comment] 2018-06-20 07:17
Appending to a file doesn't work for text mode either:

```
import pandas as pd


with open("test.csv", "w") as f:
    f.write("A,B,C\n")


df = pd.DataFrame({"A": [1, 2, 3, 4],
                   "B": [5, 6, 7, 8],
                   "C": [9, 10, 11, 12]})

with open("test.csv", "a") as f:
    df.to_csv(f, header=False, index=False)
```

Even though `f` is open in append mode, the file gets overwritten by `to_csv`.

However, appending does work when a file name is passed instead of a file handle:

```
df.to_csv("test.csv", header=False, index=False, mode="a")
```

I think this issue came up only recently, because I *think* this worked with a previous pandas version (although I didn't check).

**Comment by jmerkin** [comment] 2018-06-27 18:08
I updated my conda install after probably 6-12 months and this issue crept up for me, so I can confirm that it arose recently.

Roughly, I was doing the following (essentially as cbrnr describes):
```
with open(filename, 'w') as fout:
    for input in inputs:
        result = some_function(input)
        result.to_csv(fout)
```

Looking through the installed versions in anaconda2/pkgs/ I see pandas-0.20.1 and pandas-0.23.1. Previously, the code would produce a single file with all the results produced. Now, the resulting file only contains the final results from the last iteration. The above code would work fine with 0.20, but produces the error as cbrnr describes now.

**Comment by mariusvniekerk** [comment] 2018-07-02 18:33
Setting `mode='a'` does clear it in the second example.  This seems to have changed between  0.22.0 and 0.23.1

**Comment by Huite** [comment] 2018-07-03 17:06
I've downgraded to 0.23.0 to check, and 0.23.0 works as expected. It appears to be specific to 0.23.1.

**Comment by yrhooke** [comment] 2018-07-06 20:21
Testing on current dev version (pandas: 0.24.0.dev0+232.g04caa569e) on my machine:

append works fine.

Wrapping the  file with TextIOWrapper inside the with open() block as suggested above doesn't raise an error, but doesn't write to file either. 

binary write mode appears to be an issue with python3 csv module (see @chris-b1 's comment).

Is there a particular fix that needs to happen? I'd be happy to work on it.

**Comment by harshit-ag** [comment] 2019-04-06 08:15
can i work on this issue ?

**Comment by harshit-ag** [comment] 2019-04-07 08:09
`import io
import pandas as pd
towrite = io.BytesIO()
df = pd.read_csv("example.csv")

df.to_excel(towrite)
towrite.seek(0)

with open("someother.csv", "wb") as f:

    f.write(towrite.getvalue())
    f.close()
`
This can be a probable solution by checking the mode and  converting it to a byte-like object. I have tried to make changes  but  could not figure out  the flow of code.  @TomAugspurger  can you help me to do that?

**Comment by Enteee** [comment] 2020-05-13 19:40
Hi folks, I wrote an article on my blog on [how to Support Binary File Objects with `pandas.DataFrame.to_csv`](https://duckpond.ch/python/bash/2020/05/07/support-binary-file-objects-with-pandas.dataframe.to_csv.html). At the end of the article I added a monkey patch I think can also be used as a work around for this problem. Hope this helps until this is resolved in `pandas`.

**Comment by remram44** [comment] 2020-06-08 22:41
I'm very confused about this, because passing a `io.BytesIO` to pandas will not work (so whatever detection you do isn't very good) but passing a simple file-like object with a `write()` method will make `to_csv()` write bytes to it for some reason. Why `to_csv()` puts bytes into anything is beyond me.

How can I make a file-like object that pandas will accept to write strings to?

**Closed** 2020-08-07 11:53 UTC
Labels: Docs, IO CSV, good first issue
