### ISSUE TITLE
Dataframe Groupby with Quantile Can't handle q=tuple

### ISSUE THREAD

**Issue by ahowe42** [pandas-dev/pandas#28285] opened 2019-09-04 15:19 UTC
In version 0.24.1, a groupby with `quantile(q)`, where `q` is a tuple works. However, with 0.25, a `TypeErr` exception is thrown. This works as expected:

`pd.DataFrame([[0,1,2,3],[0,4,5,6],[1,7,8,9],[1,10,11,12]],columns=['a','b','c','d']).quantile((0.01,0.99))`

but this does not:

`pd.DataFrame([[0,1,2,3],[0,4,5,6],[1,7,8,9],[1,10,11,12]],columns=['a','b','c','d']).groupby(by=['a']).b.quantile((0.01,0.99))`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.3.5
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8

</details>

**Comment by WillAyd** [comment] 2019-09-04 15:21
Can you try on master? I think this is a duplicate of something already fixed

**Comment by badge** [comment] 2019-09-04 18:28
Fixed in 0.25.1

https://github.com/pandas-dev/pandas/issues/27526

**Comment by TomAugspurger** [comment] 2019-09-04 19:06
Thanks for checking.

**Closed by TomAugspurger** 2019-09-04 19:06 UTC
