### ISSUE TITLE
ENH: use oldest-supported-numpy in pyproject.toml

### ISSUE THREAD

**Issue by henryiii** [pandas-dev/pandas#43141] opened 2021-08-20 21:08 UTC
#### Is your feature request related to a problem?

Currently using Pandas on Python 3.10 RC 1 gets the wrong version of numpy (1.19) and builds the wheel manually, instead of getting the first wheel for NumPy + Python 3.10 (1.21).

#### Describe the solution you'd like

This problem has already been solved by https://github.com/scipy/oldest-supported-numpy/blob/master/setup.cfg - by using SciPy (the org, not the package)'s oldest-supported-numpy, you get a thorough and up-to-date listing of the oldest supported numpy's for compiling. You can further control it using normal requirements (such as setting a higher requirement for some version, etc). That's literally all the package does, and is maintained by NumPy maintainers.

#### API breaking implications

None, just a build improvement.

#### Describe alternatives you've considered

Otherwise, the contents of https://github.com/scipy/oldest-supported-numpy/blob/master/setup.cfg should be placed in pyproject.toml and maintained for each new Python release - 3.10 is currently missing.

#### Additional context

Before:

```python
    # Numpy requirements for different OS/architectures
    # Copied from https://github.com/scipy/scipy/blob/master/pyproject.toml (which is also licensed under BSD)
    "numpy==1.17.3; python_version=='3.7' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64'",
    "numpy==1.18.3; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64'",
    "numpy==1.19.3; python_version>='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64'",
    # Aarch64(Python 3.9 requirements are the same as AMD64)
    "numpy==1.19.2; python_version=='3.7' and platform_machine=='aarch64'",
    "numpy==1.19.2; python_version=='3.8' and platform_machine=='aarch64'",
    # Darwin Arm64
    "numpy>=1.20.0; python_version=='3.8' and platform_machine=='arm64' and platform_system=='Darwin'",
    "numpy>=1.20.0; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin'"
```

After:

```python
    "oldest-supported-numpy"
```

(Optionally pinned if you want)

**Comment by jreback** [comment] 2021-08-20 21:43
we already do this - i suppose it needs updating for 3.10

**Comment by TomAugspurger** [comment] 2021-08-20 23:12
I think the proposal is to replace https://github.com/pandas-dev/pandas/blob/5410fb79946c11c0754e8f5679e61b41066a15f7/pyproject.toml#L8-L19 with just `"oldest-supported-numpy"`, which will keep things up to date for us. That sounds great to me.

**Comment by lithomas1** [comment] 2021-08-21 00:11
Duplicate of #40307.

**Closed by lithomas1** 2021-08-21 00:11 UTC
Labels: Enhancement, Needs Triage

**Comment by henryiii** [comment] 2021-08-21 02:13
> Duplicate of #40307.

I searched for the string `oldest-supported-numpy` before opening and didn't see anything, guess because it was in a link?

> I think the proposal is to replace

Yes, it was.

> we already do this - i suppose it needs updating for 3.10

That was the point (and this is something in this issue not in the issue from 6 months ago), the current list needs updating, but instead of continually updating it, it's better to just take `oldest-supported-numpy`.
