### ISSUE TITLE
BUILD: Docker build failed 'Connection to raw.githubusercontent.com timed out.'

### ISSUE THREAD

**Issue by srkds** [pandas-dev/pandas#52561] opened 2023-04-10 13:47 UTC
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-10-10.0.19044-SP0

### Installation Method

Built from source

### pandas Version

from source (main)

### Python Version

3.10.9

### Installation Logs

Hi
I'm trying to setup pandas dev-environment for contribution. 
And followed the below given documentation. But build failed.
[Environment Setup -> using Docker](https://pandas.pydata.org/docs/dev/development/contributing_environment.html#option-3-using-docker)

Command that I executed.
```sh
Mypc\path\pandas> docker build -t pandas-dev .
```

> executor failed running [/bin/sh -c python -m pip install     -r https://raw.githubusercontent.com/pandas-dev/pandas/main/requirements-dev.txt]: exit code: 1

Is it a problem with this site `https://raw.githubusercontent.com/pandas-dev/pandas/main/requirements-dev.txt` or I'm missing any step?

👇 see logs
<details>

```sh
[+] Building 102.1s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                        0.0s
 => => transferring dockerfile: 32B                                         0.0s
 => [internal] load .dockerignore                                           0.0s
 => => transferring context: 2B                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.10.8            3.1s
 => [1/7] FROM docker.io/library/python:3.10.8@sha256:0e3142c4c50c73e89a07  0.0s
 => CACHED [2/7] WORKDIR /home/pandas                                       0.0s
 => CACHED [3/7] RUN apt-get update && apt-get -y upgrade                   0.0s
 => CACHED [4/7] RUN apt-get install -y build-essential                     0.0s
 => CACHED [5/7] RUN apt-get install -y libhdf5-dev                         0.0s
 => CACHED [6/7] RUN python -m pip install --upgrade pip                    0.0s
 => ERROR [7/7] RUN python -m pip install     -r https://raw.githubuserco  98.8s
------
 > [7/7] RUN python -m pip install     -r https://raw.githubusercontent.com/pandas-dev/pandas/main/requirements-dev.txt:
#10 15.92 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f673dc30940>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /pandas-dev/pandas/main/requirements-dev.txt
#10 31.46 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f673dc30ca0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /pandas-dev/pandas/main/requirements-dev.txt
#10 47.50 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f673dc30f70>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /pandas-dev/pandas/main/requirements-dev.txt
#10 64.52 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f673dff6da0>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /pandas-dev/pandas/main/requirements-dev.txt
#10 83.55 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f673dff6740>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /pandas-dev/pandas/main/requirements-dev.txt
#10 98.66 ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /pandas-dev/pandas/main/requirements-dev.txt (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f673dff6a40>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)'))
#10 98.66
------
executor failed running [/bin/sh -c python -m pip install     -r https://raw.githubusercontent.com/pandas-dev/pandas/main/requirements-dev.txt]: exit code: 1
```

</details>

Thanks!

**Comment by phofl** [comment] 2023-04-11 21:27
Hi, are you behind a proxy or similar?

**Comment by srkds** [comment] 2023-04-12 02:43
> Hi, are you behind a proxy or similar?

No!

Just for a general check I tried opening this URL `https://raw.githubusercontent.com/pandas-dev/pandas/main/requirements-dev.txt` in a normal browser(or without VPN) and then tried opening into the TOR browser with VPN.

without VPN it says: `This site can’t be reached` `raw.githubusercontent.com took too long to respond.`
and in TOR with VPN it opens(worked) `requirements-dev.txt` file as response.

Without VPN 👇
![image](https://user-images.githubusercontent.com/61644078/231333595-489156c7-1c2d-4825-b279-4376d119b9e4.png)

With VPN 👇
![image](https://user-images.githubusercontent.com/61644078/231333663-319e47d1-103f-4111-9dda-eeda0cfb5028.png)

**Comment by phofl** [comment] 2023-04-12 07:42
The link works for me without anything, this seems to be a problem with your connection

**Comment by srkds** [comment] 2023-04-12 16:52
> The link works for me without anything, this seems to be a problem with your connection

I tried different connections.
It would be helpful if anyone try accessing this site from India and confirm.

**Comment by phofl** [comment] 2023-04-22 17:15
This is not on our side, rather has something do to with your connection. I tried again and couldn't reproduce. Closing for now

**Closed by phofl** 2023-04-22 17:15 UTC
Labels: Build, Needs Triage

**Comment by srkds** [comment] 2023-04-22 17:26
> This is not on our side, rather has something do to with your connection. I tried again and couldn't reproduce. Closing for now

Sounds good. Thanks @phofl for looking into it.
As of now, I have done a manual setup.
