### ISSUE TITLE
Support multiple characters for `comment` in read_csv

### ISSUE THREAD

**Issue by orangeSi** [pandas-dev/pandas#21725] opened 2018-07-04 05:53 UTC
my code is:
```python

vcf = pd.read_table("com8-2.N85-2.merge.snp.vcf", header=0, sep="\t", comment="##")

```
and get this error:

`ValueError: Only length-1 comment characters supported`
the error means the length of comment must be one ? why not allowed for  two characters ?

The python version is python3.6, 
pandas version is pandas-0.20.3

thanks~
Si

**Comment by TomAugspurger** [comment] 2018-07-04 11:08
It doesn't look like this will be easy to support, but people are welcome to try to implement it if they want.

**Comment by jreback** [comment] 2018-07-04 12:05
dupe of #8727

**Closed by jreback** 2018-07-04 12:05 UTC
Labels: Difficulty Advanced, Effort High, Enhancement, IO CSV

**Comment by krishdb38** [comment] 2020-01-22 06:08
me same Problem
ValueError: Only length-1 comment characters supported
df = pd.read_csv("/BiO/Preterm/raw_data/1009/1009.vcf", comment="##",low_memory = False)
i am doing reasearch in genome data 
very difficult to convert medical data to pandas df

**Comment by duolin1986** [comment] 2020-07-17 03:01
the same problem, it's really weired

**Comment by bioXiaoheng** [comment] 2022-07-21 06:41
Same here

**Comment by Lewis-W-S-Fisher** [comment] 2023-10-23 12:53
Did this get a fix or anything, I'm having this problem too?

**Comment by luxurystorecc1** [comment] 2026-05-11 01:00
Raleigh Refined: Merging Innovation with High-Level Athletic Gear
As a key part of the Research Triangle, Raleigh is a city that values intelligence, innovation, and active living. Whether you're on a tech campus or the basketball court, your gear needs to perform at the highest level. For sneaker enthusiasts in the 919, [authentic retro leather high-top sneakers in Raleigh](https://www.airjordan-1.com/) provide a polished look that bridges the gap between classic performance and modern professional style.

The local passion for college and professional sports is immense. Fans frequently search for [authentic pro league fan merchandise online](https://www.nflshopofficialonline-store.com/) to support their favorite teams. Given the sunny North Carolina climate, [unisex performance sun hats for sports](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) are an essential gear item for any outdoor adventure or tailgating event.

Technical Quality and Trend-Setting
The professional and academic lifestyle in the Triangle is mirrored in the demand for [high-end technical casual wear for men](https://www.peter-milla.com/), providing a sharp look for business and leisure. For those following the latest footwear trends, [exclusive designer collaboration sneakers](https://www.yeezyboost-350.com/collections/adidas-yeezy) are a common fashion statement in the city’s trendy districts.

Swimming and aquatic training are major local priorities, making [high-performance aquatic gear and training equipment](https://www.swim-outlet.com/) a top-selling category. For formal galas and local weddings, [elegant plus size evening wear for special occasions](https://www.cheapdressesformal.com/) allows everyone to dress with confidence.

The international soccer community is thriving in Central NC, with fans gathering wearing [European national team soccer jerseys](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain). To complete the look, [structured team logo football caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) are a staple. For a personalized touch, [personalized team jerseys with custom lettering](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) are highly sought after. Finally, for the cooler winter nights, [official pro hockey league apparel](https://www.custombaseball-jerseys.com/) remains a popular choice for local fans.
