### ISSUE TITLE
 Initializing from file failed

### ISSUE THREAD

**Issue by JafferWilson** [pandas-dev/pandas#21828] opened 2018-07-09 14:36 UTC
Kindly, share your insights regarding the following error
```
  File "source\matrix_gen.py", line 68, in <module>
    main()
  File "source\matrix_gen.py", line 22, in main
    data = pd.read_csv(sys.argv[1], parse_dates=True, dayfirst=True)# argv[1]: stock_symbol.txt
  File "C:\Users\aims\Anaconda3\envs\py35\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\aims\Anaconda3\envs\py35\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\aims\Anaconda3\envs\py35\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\aims\Anaconda3\envs\py35\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\aims\Anaconda3\envs\py35\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 697, in pandas._libs.parsers.TextReader._setup_parser_source
OSError: Initializing from file failed
```

**Comment by mroeschke** [comment] 2018-07-09 16:50
Could you provide a minimally reproducible example? 

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by JafferWilson** [comment] 2018-07-10 05:20
sure. Here you can see. I am trying to run this repository: https://github.com/hardyqr/CNN-for-Stock-Market-Prediction-PyTorch
From this, I have tried running the file: https://github.com/hardyqr/CNN-for-Stock-Market-Prediction-PyTorch/blob/master/source/matrix_gen.py
The csv samples I have downloaded from Kaggle sources as mentioned in the repository's READ.ME file. 
I hope the information required is fulfilled.
Please let me know if anything more needed.

**Comment by mroeschke** [comment] 2018-07-10 05:47
From your traceback you issue looks to be when reading in the file:

`data = pd.read_csv(sys.argv[1], parse_dates=True, dayfirst=True)# argv[1]: stock_symbol.txt`

You may want to make sure that the path to the file you are passing in is fully specified.

**Comment by mroeschke** [comment] 2018-07-10 14:59
This _may_ be a duplicate of #15086, but it's hard to tell since your example is not a [MCVE](https://stackoverflow.com/help/mcve)

**Comment by mroeschke** [comment] 2018-07-11 04:42
Based on your configuration and similar traceback, this may be an issue reading files with Windows as described in #15086. Tentatively closing as a duplicate of that open issue.

Looks like there are some suggestions to resolve that issue; a partial workaround for now seems to be here: https://github.com/pandas-dev/pandas/issues/15086#issuecomment-357481412

**Closed by mroeschke** 2018-07-11 04:42 UTC
Labels: Needs Info

**Comment by JafferWilson** [comment] 2018-07-11 04:59
I had gone through the comments and suggestions from this blog my friend. But none is helpful. But if there is no solution then I can say anything. Thank you for closing the issue and marking duplicate.

**Comment by mroeschke** [comment] 2018-07-11 05:08
If you feel that your issue is different from #15086, feel free to reopen this thread with a representative example. We hope that issue can be resolved soon from a community contribution.

Otherwise, you can also try using StackOverflow.

**Comment by JafferWilson** [comment] 2018-07-11 05:31
@mroeschke Thank you. I will try it on my own this time as there was no reply on the same from Stackoverflow. I tried it already. Otherwise I guess that I will have to move on to Linux instead of Windows.

**Comment by breckuh** [comment] 2018-09-11 20:49
I ran into a similar issue with a Jupyter notebook downloaded from the internet with an accompanying CSV. Turned out the CSV had no read permissions--sigh--and Pandas didn't give a hint as to that underlying cause. Not sure if this was the same thing happening to you @JafferWilson--I forget how permissions work on Windows--but figured I post this in case anyone else hits a similar issue.

**Comment by Silence-python** [comment] 2019-03-07 11:56
txtPath = 'E:/Defensive/textlog'
    txtLists = os.listdir(txtPath)
    # txtLists = os.path.isdir(txtPath)
    for txt in txtLists:
        file_name = txtPath + "/" + txt
        reader = pd.read_table(file_name, sep=",", names=[i for i in range(4)], iterator=True)


error：OSError: Initializing from file failed  
why?

**Comment by kailichou** [comment] 2019-11-18 01:52
Same issue happened to me while trying to read csv file at Spyder. However, it worked perfectly fine when I tried at Terminal.

`Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> items = pd.read_csv('/Users/kailic/Downloads/competitive-data-science-predict-future-sales/items.csv')
>>> items.head()
                                           item_name  item_id  item_category_id
0          ! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.)         D        0                40
1  !ABBYY FineReader 12 Professional Edition Full...        1                76
2      ***В ЛУЧАХ СЛАВЫ   (UNV)                    D        2                40
3    ***ГОЛУБАЯ ВОЛНА  (Univ)                      D        3                40
4        ***КОРОБКА (СТЕКЛО)                       D        4                40
>>> 
`

**Comment by kpiyush04** [comment] 2020-10-26 05:03
Hey! there I'm facing the same issue. But could not find any solution for it.

![image](https://user-images.githubusercontent.com/44132300/97135532-83380b00-1776-11eb-95eb-80e7ff79d581.png)
