### ISSUE TITLE
to_timedelta str int discrepancy

### ISSUE THREAD

**Issue by harishmk** [pandas-dev/pandas#30850] opened 2020-01-09 15:44 UTC
#### Code Sample, a copy-pastable example if possible

```python
assert pd.to_timedelta(1,unit='s') == pd.to_timedelta('1',unit='s')
```
fails
```python
>>> pd.to_timedelta(20000,unit='s')
Timedelta('0 days 05:33:20')

>>> pd.to_timedelta('20000',unit='s')
Timedelta('0 days 00:00:00.000020')
```

#### Problem description
it looks like the `unit` parameter has no effect in `pd.to_timedelta('1',unit='s')`
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-957.27.2.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.0.1
Cython           : 0.29.13
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.5.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.13.0
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.7
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by mroeschke** [comment] 2020-01-09 16:33
Thanks for the report. Duplicate of https://github.com/pandas-dev/pandas/issues/12136

**Closed by mroeschke** 2020-01-09 16:33 UTC
