### ISSUE TITLE
BUG: Newer Version Pandas loc does not return correct value

### ISSUE THREAD

**Issue by ARBQuant** [pandas-dev/pandas#46813] opened 2022-04-20 19:27 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
a = [-1, np.nan, np.nan, np.nan, np.nan]
df = pd.DataFrame(a, index=[0, 1, 2, 3, 4], columns=['Signal'])
print(df.loc[0, 'Signal'])
```

### Issue Description

This sometimes prints a nan rather than -1. In another project with pandas 1.3.0 installed, the error never happened, and it only happened when the pandas was upgraded to 1.4.1 and later versions. 

### Expected Behavior

It should print a -1 all the time.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.1
numpy            : 1.22.3
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 22.0.4
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

**Comment by MarcoGorelli** [comment] 2022-04-20 21:01
I just tried executing that multiple times and always got `-1` - when do you get `nan`?
```console
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % python t.py
-1.0
(venv) marcogorelli@OVMG025 tmp % cat t.py 
import pandas as pd
import numpy as np
a = [-1, np.nan, np.nan, np.nan, np.nan]
df = pd.DataFrame(a, index=[0, 1, 2, 3, 4], columns=['Signal'])
print(df.loc[0, 'Signal'])
```

**Comment by ARBQuant** [comment] 2022-04-20 21:09
> I just tried executing that multiple times and always got `-1` - when do you get `nan`?
> 
> ```
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % python t.py
> -1.0
> (venv) marcogorelli@OVMG025 tmp % cat t.py 
> import pandas as pd
> import numpy as np
> a = [-1, np.nan, np.nan, np.nan, np.nan]
> df = pd.DataFrame(a, index=[0, 1, 2, 3, 4], columns=['Signal'])
> print(df.loc[0, 'Signal'])
> ```

The sample code I provided was a very simple demo. The error occurs in my code where it looks like this:

signal = self.data.loc[entryIdx, 'Signal']

the self.data is a DataFrame with about 40 columns, and this line of code belongs to a method within the class called "addPst". There is a do-work type function using a while loop and when certain conditions are met, this addPst will be called, the entryIdx is given every time this method is called.

I verified that there were no column name change or deleted in my process, and it does not return a nan all the time, just occasionally. And what is more weird is that if I simply add a line of print(self.data.loc[entryIdx]), that same position where nan is returned will be gone.

**Comment by MarcoGorelli** [comment] 2022-04-20 21:16
Can you make a minimal reproducible example which reproduces the issue out of your code? Try removing bits until the issue is no longer present, see if you can isolate when it occurs

**Comment by ARBQuant** [comment] 2022-04-20 21:22
> Can you make a minimal reproducible example which reproduces the issue out of your code? Try removing bits until the issue is no longer present, see if you can isolate when it occurs

Thank you, I will try doing that as you suggested, and see if I can provide a reproducible example that is minimal enough to isolate the error and upload here.
In my own work my solution was that I downgraded the pandas version to 1.3.0 as used by the original project, and the error does not happen anymore. The same code has been used in the original project for over 8 months and never had this issue, but that project got too large and I decided to split things up to have a clearer view, and then I observed the error as the newer projects interpreter was set up with the newer pandas.

**Comment by ARBQuant** [comment] 2022-04-20 22:16
There is some new observations: I am printing the signal value after the loc line with these two lines of code:
signal = self.data.loc[entryIdx, 'Signal']
print(signal)
and this is what I got:
-1
-1
nan
So the 3rd time this method was called, the signal value extracted was turned nan, and my code afterwards broke. However, if I print it like this:
signal = self.data.loc[entryIdx, 'Signal']
print(signal)
print(self.data.loc[entryIdx])
and this print was added after the signal got value from the DataFrame, it actually can get that -1 value from the self.data, and the code can run without any break.

**Comment by rhshadrach** [comment] 2022-04-21 01:58
Thanks for the additional info @ARBQuant, but there isn't much we can do without a reproducible example. I recommend focusing your efforts on providing an example we can look into.

**Comment by ARBQuant** [comment] 2022-04-21 13:11
> Thanks for the additional info @ARBQuant, but there isn't much we can do without a reproducible example. I recommend focusing your efforts on providing an example we can look into.

Thank you for the reply. I will definitely work on that example, but it probably needs to wait until the weekend, I have other things to accomplish for work. I will update here as soon as I can get the minimal reproducible example. Thank you again.

**Comment by ARBQuant** [comment] 2022-04-24 21:15
Hi, I have been trying to create a reproducible example, but I still cannot make it, because when I use the help of a locally stored file, things become correct, as my initial plan was to isolate that part of the calculation, and upload a data file for you to help me. This is very very very strange. Please see my this part of the code:

print("BeforeLoc: ", self.data.loc[idx, 'Signal'])
self.data.loc[idx, 'Signal'] = signal
print("PassedValue: ", signal)
print("PrintedValue: ", self.data.loc[idx, 'Signal'])

This is part of a method that is called hundreds of times inside a while loop through my data frame, and in the first 3 loops it totally works fine. However, from the 4th time it was called, as I have printed out everything as you see here, the output changed from:
BeforeLoc:  nan
PassedValue:  -1
PrintedValue:  -1
to:
BeforeLoc:  nan
PassedValue:  -1
PrintedValue:  nan

However, I created a separate while loop just to test this loc assigning value and it never fails. And what is more bizarre than this is that I have another line of code right after this method is called to save the self.data data frame after each time the values are written, and actually, even when that printed value shows nan, the local output file does have the -1 value in it. As I wrote 4 days ago, another very strange thing here is that if I added a line of print the whole row of data inside the self.data, even it is printed after that assigning value happens, it seems to fix that issue also. 

I know that it is not helpful that I cannot offer a reproducible example, as I am very very far away from a professional developer, I do lack the very basic knowledge of the deep level programming knowledge. I am wondering if, by any chance, it could be some kind of "translation" miscommunication within the compiling process of Python, and because I am using the loc in a legacy way that in the updates to pandas 1.4.0, those legacy features was totally depreciated, so I am experiencing troubles ever since? Also, is there any suggestion on how I can prepare some code or info to help you here help me? I really appreciate the help from the community.

**Comment by phofl** [comment] 2022-06-19 19:24
Unfortunately, we can not debug this without a reproducible example. I am closing this for now. Please ping to reopen, if you can provide an example.

**Closed by phofl** 2022-06-19 19:24 UTC
Labels: Indexing, Needs Info
