### ISSUE TITLE
Abnormal results on multiIndex difference

### ISSUE THREAD

**Issue by heury** [pandas-dev/pandas#26977] opened 2019-06-21 02:17 UTC
#### Code Sample, a copy-pastable example if possible

```
arrays = [['a', 'b', 'c', 'd'],
         [1,2,3,4]]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
index1 = index.copy()
index1.difference(index)
#This should be empty results but I got following results

Out[65]: 
MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3, 4]],
           codes=[[], []],
           names=['first', 'second'])

index1 = index[:index.size-1]
index1.difference(index)

#This results is empty as I expected
Out[67]: 
MultiIndex(levels=[[], []],
           codes=[[], []],
           names=['first', 'second'])


```
#### Problem description
MultiIndex difference returns all indexes if two indexes are same.
I guess it should be empty.

SingleIndex difference returns empty if  two indexes are same.
Refer to following example
```
idx1 = pd.Index([2, 1, 3, 4])
idx2 = idx1.copy()
idx1.difference(idx2)

Out[60]: Int64Index([], dtype='int64')
```

#### Output of ``pd.show_versions()``
NSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.24.2
pytest: 4.3.1
pip: 19.0.3
setuptools: 40.8.0
Cython: 0.29.6
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: 1.8.5
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: 1.8.1
bottleneck: 1.2.1
tables: 3.5.1
numexpr: 2.6.9
feather: None
matplotlib: 3.0.3
openpyxl: 2.6.1
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.5
lxml.etree: 4.3.2
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by WillAyd** [comment] 2019-06-22 01:12
> MultiIndex difference returns all indexes if two indexes are same.

Not quite though I can see where this is confusing. `codes` are empty in your above example which are used in the actual construction of the MI though not in the representation on your version of pandas.

Actually if you run this on master now you may get something closer to what you expect:

```python
In [3]: index1.difference(index)
Out[3]: MultiIndex([], names=['first', 'second'])
```

Are you facing an issue in utilization of this or is it merely a matter of the repr not being very intuitive?

**Comment by WillAyd** [comment] 2019-06-22 01:46
Closing as I think this is simply confusion over repr but lmk if this is causing an actual issue

**Closed by WillAyd** 2019-06-22 01:46 UTC
Labels: MultiIndex, Usage Question

**Comment by heury** [comment] 2019-06-25 00:29
I modified my sample code.
My pandas version is 0.24.2. It is same as master version.
I am using anaconda, but I got same results  from other python packages.
I can't get empty results from this codes.

```
import pandas as pd
arrays = [['a', 'b', 'c', 'd'],
         [1,2,3,4]]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
index1 = index.copy()
index1.difference(index)
```
This should be empty results but I got following results
```
MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3, 4]],
           codes=[[], []],
           names=['first', 'second'])
```

**Comment by heury** [comment] 2019-06-25 01:01
I modified my sample code.
My pandas version is 0.24.2. It is same as master version.
I am using anaconda, but I got same results  from other python packages.
I can't get empty levels from this codes.

```
import pandas as pd
arrays = [['a', 'b', 'c', 'd'],
         [1,2,3,4]]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
index1 = index.copy()
index1.difference(index)
```
This should be empty levels but I got following results
```
MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3, 4]],
           codes=[[], []],
           names=['first', 'second'])
```
It is very confusing to me. Because it only happens if two index are equal.
For example, following codes returns empty levels

```
index1 = index[:index.size-1]
index1.difference(index)
```

```
MultiIndex(levels=[[], []],
           codes=[[], []],
           names=['first', 'second'])
Int64Index([], dtype='int64')
```

I guess difference in multi.py also returns empty levels if two indexes are equal.
```
        if self.equals(other):
            return MultiIndex(levels=self.levels,
                              codes=[[]] * self.nlevels,
                              names=result_names, verify_integrity=False)
```

**Comment by WillAyd** [comment] 2019-06-25 01:13
> My pandas version is 0.24.2. It is same as master version.

This is an incorrect assumption which might be the cause of confusion. You can get more details on how to work with master in our contributing guide:

https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#working-with-the-code

**Comment by heury** [comment] 2019-06-26 02:11
You are right. Master version returns results as I expected.
Thanks for your comments.
