### ISSUE TITLE
Categoricals are not preserved by groupby.Groupby.last()

### ISSUE THREAD

**Issue by tobiasraabe** [pandas-dev/pandas#19207] opened 2018-01-12 12:30 UTC
#### Code Sample, a copy-pastable example if possible

```python
a = pd.DataFrame({
    'ID': [1, 1, 2, 2],
    'GENDER': ['male', 'male', 'female', 'female'],
})

a.GENDER = a.GENDER.astype('category')

a.groupby('ID').last().GENDER

```
Output
````
ID
1      male
2    female
Name: GENDER, dtype: object
````

#### Problem description

I would expect that categoricals are preserved by such transformations. At best, the transformation returns an updated categorical if some categories are missing in the process.

#### Expected output
````
ID
1      male
2    female
Name: GENDER, dtype: category
Categories (2, object): [female, male]
````

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment] 2018-01-13 22:11
duplicate of #18502

**Closed by jreback** 2018-01-13 22:11 UTC
