### ISSUE TITLE
Unexpected behaviour with pd.filter in pandas 2.1

### ISSUE THREAD

**Issue by shuai-b-zhang** [pandas-dev/pandas#55195] opened 2023-09-19 07:51 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
ban = df_merged.filter([col2, col4, col3])
```

### Issue Description

I'm user of Padans, I found a issue, when I update to 2.1. 
We have some dataframe with the following columns:
> col1, col2, col3, col4

We want to filter for a subset of those columns:
> # note the ordering: 2, 4, 3
> ban = df_merged.filter([col2, col4, col3])

However, in 2.1, the function returns the columns in the dataframe ordering:
> col2, col3, col4

### Expected Behavior

In 1.5, the function would return the columns in the order we passed them in as:
> col2, col4, col3

### Installed Versions

2.1

**Comment by rhshadrach** [comment] 2023-09-19 21:13
Thanks for the report - can you:

 - Give a descriptive title to this issue (right now it is just `BUG:`)
 - Give a reproducible example - it needs to be something anyone investigating this issue can run
 - Tell the full version of pandas you are using. Are you using 2.1.0 or 2.1.1?

**Comment by rhshadrach** [comment] 2023-09-19 21:14
This is likely a duplicate of #55075

**Comment by shuai-b-zhang** [comment] 2023-09-19 23:53
@rhshadrach thanks your quickly reply, sorry for raise duplicate issue. it is same with https://github.com/pandas-dev/pandas/issues/55075

**Closed** 2023-09-20 02:22 UTC
Labels: Bug, Duplicate Report, Needs Info, Needs Triage
