### ISSUE TITLE
Add an ends function that shows both head and tail of the df

### ISSUE THREAD

**Issue by icfly2** [pandas-dev/pandas#18691] opened 2017-12-08 13:53 UTC
#### Add the following function to pd. dataFrame and pd.Series

```python
def ends(df, x=5):
    """Returns both head and tail of the dataframe or series.
    
    Args:
        x (int): Optional number of rows to return for each head and tail
    """
    print('{} rows x {} columns'.format(np.shape(df)[0],np.shape(df)[1]))
    return df.head(x).append(df.tail(x))

```
#### Problem description
Often both the beginning and end of a df are of interest, fore example in a time series. 

This leads to calling df.head() df.tail()  in two seperate notebook cells. This is not only tedious, but also leads to a cluttered notebook. A function that returns both of these + a print on the number of rows and columns, thus allowing a check if the index matches the number of rows.

#### Example
```python

import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(1500,6))
print(ends(df,2))
```
1500 rows x 6 columns

|      | 0        | 1        | 2        | 3        | 4        | 5        |
|------|----------|----------|----------|----------|----------|----------|
| 0    | 0.949695 | 0.160928 | 0.434134 | 0.943103 | 0.477830 | 0.903479 |
| 1    | 0.736711 | 0.103746 | 0.028694 | 0.205910 | 0.226061 | 0.458452 |
| 1498 | 0.362950 | 0.586887 | 0.399681 | 0.115366 | 0.239049 | 0.386281 |
| 1499 | 0.018102 | 0.852198 | 0.880993 | 0.671604 | 0.705586 | 0.802237 |

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.3.1
pip: 9.0.1
setuptools: 38.2.4
Cython: 0.26.1
numpy: 1.12.1
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 0.9.8
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jorisvandenbossche** [comment] 2017-12-08 14:43
I thought we discussed this before, but can't find such issue. 

That said, this is closely related to https://github.com/pandas-dev/pandas/pull/17023. Because if we reduce the default number of rows, I think such a feature becomes less needed IMO. 

In general, we are not very keen on adding more methods to DataFrame, unless there is a very clear need.

**Comment by TomAugspurger** [comment] 2017-12-08 17:16
FWIW, my utils file has a context manager for this:

```python
def show(df):
    with pd.option_context("display.max_rows", 10):
        display(df)
```

And I called it with `df.pipe(show)`. Agreed that we shouldn't add a new method, especially given #17023.

**Comment by jreback** [comment] 2017-12-09 14:50
see #4193 and #1889

**Comment by jreback** [comment] 2017-12-09 14:52
this seems quite duplicate of what we already have, by default the repr *already does this*. using ``display.max_rows`` to control the break of this.

**Comment by icfly2** [comment] 2017-12-13 12:41
Perhaps it might be worth adding a line to the docs as it seems quite an obscure but very useful trick.

I would suggest referring to head in the docs for tail and vice versa and adding the comment about ` display.max_rows` 

I'm happy to try my hand at that addition if there is some general support for the idea.

**Comment by jreback** [comment] 2017-12-13 14:07
@icfly2 #18749 already is updating he doc-strings, so natural to add there.

Love to have you contribute on other issues!

**Closed** 2017-12-15 23:56 UTC
Labels: Docs, Output-Formatting

**Comment by adamrossnelson** [comment] 2021-08-03 15:54
Woth a mention that this issue also relates to: https://github.com/pandas-dev/pandas/issues/42837

The idea is that there is a way to preserve vertical screen space when inspecting 'tall' (many rows, few cols) data frames.
