### ISSUE TITLE
BUG: MultiIndex.set_labels not correctly verifying

### ISSUE THREAD

**Issue by swevrywhere** [pandas-dev/pandas#15157] opened 2017-01-18 21:16 UTC
I believe that 
        label_length = len(self.labels[0])
should actually be
        label_length = len(labels[0])

I tested my proposed change and it fixed the problem I had in my code that started when I updated Pandas from 0.18.1 to 0.19.2. 

    def _verify_integrity(self, labels=None, levels=None):
        """
        Parameters
        ----------
        labels : optional list
            Labels to check for validity. Defaults to current labels.
        levels : optional list
            Levels to check for validity. Defaults to current levels.
        Raises
        ------
        ValueError
            * if length of levels and labels don't match or any label would
            exceed level bounds
        """
        # NOTE: Currently does not check, among other things, that cached
        # nlevels matches nor that sortorder matches actually sortorder.
        labels = labels or self.labels
        levels = levels or self.levels

        if len(levels) != len(labels):
            raise ValueError("Length of levels and labels must match. NOTE:"
                             " this index is in an inconsistent state.")
        label_length = len(self.labels[0])
        for i, (level, label) in enumerate(zip(levels, labels)):
            if len(label) != label_length:
                raise ValueError("Unequal label lengths: %s" %
                                 ([len(lab) for lab in labels]))
            if len(label) and label.max() >= len(level):
                raise ValueError("On level %d, label max (%d) >= length of"
                                 " level  (%d). NOTE: this index is in an"
                                 " inconsistent state" % (i, label.max(),
                                                          len(level)))

**Comment by jreback** [comment] 2017-01-18 21:30
can u show a reproducible example of what the issue is?

**Comment by swevrywhere** [comment] 2017-01-18 22:07
I will work on getting a compact, standalone example, but you can see an example of the errors and inputs here: http://stackoverflow.com/questions/41729212/new-error-during-set-labels-in-pandas-0-19-2-valueerror-unequal-label-lengths/41729634#41729634

**Comment by jreback** [comment] 2017-01-19 01:16
yeah I suppose that is incorrect.

```
In [1]: levels = [['1', '2', 'Total'], ['nextLevel']]

In [2]: labels = [[0, 1, 2], [0, 0, 0]]

In [3]: i = MultiIndex(levels=[[u'1', u'2'], [u'nextLevel']],
   ...:            labels=[[0, 1], [0, 0]],
   ...:            names=[u'segment..ASRinfo..supportedUtt', u'label'])

In [4]: i.set_levels(levels).set_labels(labels)
Out[4]: 
MultiIndex(levels=[['1', '2', 'Total'], ['nextLevel']],
           labels=[[0, 1, 2], [0, 0, 0]],
           names=['segment..ASRinfo..supportedUtt', 'label'])

In [5]: quit()
(pandas) bash-3.2$ git diff
diff --git a/pandas/indexes/multi.py b/pandas/indexes/multi.py
index 2afafae..f4061b8 100644
--- a/pandas/indexes/multi.py
+++ b/pandas/indexes/multi.py
@@ -141,7 +141,7 @@ class MultiIndex(Index):
         if len(levels) != len(labels):
             raise ValueError("Length of levels and labels must match. NOTE:"
                              " this index is in an inconsistent state.")
-        label_length = len(self.labels[0])
+        label_length = len(labels[0])
         for i, (level, label) in enumerate(zip(levels, labels)):
             if len(label) != label_length:
                 raise ValueError("Unequal label lengths: %s" %
```

Though I have no idea why you would actually do this (in user code). There are much more user friendly ways to manipulate things. If you want to do a proper PR with tests would be fine.

**Comment by swevrywhere** [comment] 2017-01-19 19:15
I am new to Pandas, and I found the documentation on MultiIndexing difficult to adapt to solving my own problem. Basically, I want to add some extra rows. This is the solution I came up with. There is probably a much better way to do it. Feel free to share if you'd like.

    groupbyColumns = ['label0', 'label1']
    data_slice = dataframe.groupby(by=groupbyColumns).sum()

    index = data_slice.index
    
    levels = list()
    for levelIter in range(len(data_slice.index.levels)):
        levels.append([x for x in data_slice.index.levels[levelIter]])
    levels[0].append('Total')
    if len(resultList)==2:
        levels[-1].append('Difference')
        addIndexCountForDifferenceRow = 1
    else:
        addIndexCountForDifferenceRow = 0
        
    # Create new indexing sequence since we are adding Total (and Difference if doing comparison) rows
    labels = list()
    for labelIter in range(len(data_slice.index.labels)):
        labels.append(list())
    if len(data_slice.index.labels)==2:
        labels0 = [x for x in data_slice.index.labels[0]]
        labels1 = [x for x in data_slice.index.labels[1]]
        for iter0 in range(max(labels0)+2):
            for iter1 in range(max(labels1)+1+addIndexCountForDifferenceRow):
                labels[0].append(iter0)
                labels[1].append(iter1)
    if len(data_slice.index.labels)==3:
        labels0 = [x for x in data_slice.index.labels[0]]
        labels1 = [x for x in data_slice.index.labels[1]]
        labels2 = [x for x in data_slice.index.labels[2]]
        for iter0 in range(max(labels0)+2):
            for iter1 in range(max(labels1)+1):
                for iter2 in range(max(labels2)+1+addIndexCountForDifferenceRow):
                    labels[0].append(iter0)
                    labels[1].append(iter1)
                    labels[2].append(iter2)

    index = index.set_levels(levels)
    index = index.set_labels(labels)
    data_slice = data_slice.reindex(index)

**Comment by jreback** [comment] 2017-01-19 19:17
can i show a start and end frame?

**Comment by jreback** [comment] 2017-01-19 19:45
```
In [13]: i = MultiIndex(levels=[[u'1', u'2'], [u'nextLevel']],
    ...:    ...:            labels=[[0, 1], [0, 0]],
    ...:    ...:            names=[u'segment..ASRinfo..supportedUtt', u'label'])
    ...: 

In [14]: df = pd.DataFrame({'A' : [1, 2]}, index=i)

In [15]: df
Out[15]: 
                                          A
segment..ASRinfo..supportedUtt label       
1                              nextLevel  1
2                              nextLevel  2

In [17]: df.reindex([('1', 'nextLevel'), ('2', 'nextLevel'), ('Total', 'nextLevel')])
Out[17]: 
                                            A
segment..ASRinfo..supportedUtt label         
1                              nextLevel  1.0
2                              nextLevel  2.0
Total                          nextLevel  NaN
```

**Comment by jreback** [comment] 2017-09-23 21:09
@chris-b1 can you see if this is still an issue?

**Comment by mroeschke** [comment] 2021-05-08 00:34
It appears that `MultiIndex.set_labels` was remove in some release so this is probably no longer an issue. Closing

**Closed by mroeschke** 2021-05-08 00:34 UTC
Labels: Bug, MultiIndex
