### ISSUE TITLE
Panel.ffill ignores axis parameter and fill along axis=1

### ISSUE THREAD

**Issue by Tux1** [pandas-dev/pandas#14499] opened 2016-10-26 11:01 UTC
#### A small, complete example of the issue

``` python
a = pd.Panel({'a':np.arange(15).reshape((5,3)), 'b':np.arange(15,30).reshape((5,3))})
a['a'].loc[1,1] = np.nan

a['a']
Out[36]:
    0     1   2
0   0   1.0   2
1   3   NaN   5
2   6   7.0   8
3   9  10.0  11
4  12  13.0  14

a.ffill(axis=2)['a']
Out[38]:
      0     1     2
0   0.0   1.0   2.0
1   3.0   1.0   5.0
2   6.0   7.0   8.0
3   9.0  10.0  11.0
4  12.0  13.0  14.0
```
#### Expected Output

`a.at['a', 1, 1] == 3`
If you ffill along axis=2, you should get `3` instead of `1`
#### Output of `pd.show_versions()`

Pandas 0.19.0

**Comment by jorisvandenbossche** [comment] 2016-10-26 12:48
@Tux1 Thanks for the report. 

PRs with a fix are certainly welcome (should be rather easy, I think `axis` has to be passed here: https://github.com/pandas-dev/pandas/blob/v0.19.0/pandas/core/generic.py#L3238). But note that we are not giving Panels many attention anymore for new features: https://github.com/pandas-dev/pandas/issues/13563

**Comment by Tux1** [comment] 2016-10-26 14:39
@jorisvandenbossche Yes, it is quite easy to fix. Will do it as soon as i have free time
Yes I know, I am disappointed by this decision

**Comment by Tux1** [comment] 2016-10-29 09:07
@jorisvandenbossche finally, it is not as easy as we thought.
I don't see how to handle the case `axis=0` because I don't want to loop over `major_axis` or `minor_axis`. Any suggestion ?

**Comment by jorisvandenbossche** [comment] 2016-10-29 09:23
@Tux1 In the PR, you now took the approach of raising a NotImplementedError for those cases? I think that is OK to start with

**Comment by Tux1** [comment] 2016-10-29 09:26
@jorisvandenbossche yes but I will break compatibility with `pct_change` when `axis=0` and probably some other function which use `fillna`
I could bypass forward filling in `pct_change` when `axis=0` but it is a bit dirty

**Comment by Tux1** [comment] 2016-11-02 14:00
@jorisvandenbossche Finally, it is fine. I handle the case `axis=0`, it is a bit ugly (I swap axes twice in case `axis=0` to fall back on a trivial case) but it works fine.

**Comment by jreback** [comment] 2017-01-20 12:16
dupe of #8251

**Closed by jreback** 2017-01-20 12:16 UTC
Labels: Bug, Duplicate, Missing-data, Panel
