### ISSUE TITLE
QST: Indexing over empty DataFrame

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#41415] opened 2021-05-11 08:10 UTC
- [x] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

Is it correct behavior when indexing over empty DataFrame?
```python
import pandas
df = pandas.DataFrame()
df
Empty DataFrame
Columns: []
Index: []

df.iloc[:, 3:9] # this doesn't throw an exception
Empty DataFrame
Columns: []
Index: []

df.iloc[:, 3] # this throws the exception
IndexError: single positional indexer is out-of-bounds

df[3:9] # this doesn't throw an exception
Empty DataFrame
Columns: []
Index: []

df[3] # this throws the exception
KeyError: 3
```

**Comment by YarShev** [comment] 2021-05-13 05:36
@attack68 , @asishm-wk , thanks! That makes sense.

**Comment by mroeschke** [comment] 2021-08-20 03:00
Closing since the expected behavior has been explained.

**Closed by mroeschke** 2021-08-20 03:00 UTC
Labels: Usage Question
