### ISSUE TITLE
Assignment of subpart of data frame with multi index yields user surprise

### ISSUE THREAD

**Issue by kghosesbg** [pandas-dev/pandas#18120] opened 2017-11-05 03:01 UTC
```python
from collections import OrderedDict
import random
import pandas as pd


pd.__version__
```

    '0.20.3'

```python
df = pd.DataFrame.from_dict(OrderedDict(
    [
        ((lv1, lv2, lv3), {'KG': random.randint(0, 100)})
        for lv1 in ['A', 'B']
        for lv2 in ['M', 'N', 'O']
        for lv3 in ['X', 'Y', 'Z']
    ]
))
df     
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="9" halign="left">A</th>
      <th colspan="9" halign="left">B</th>
    </tr>
    <tr>
      <th></th>
      <th colspan="3" halign="left">M</th>
      <th colspan="3" halign="left">N</th>
      <th colspan="3" halign="left">O</th>
      <th colspan="3" halign="left">M</th>
      <th colspan="3" halign="left">N</th>
      <th colspan="3" halign="left">O</th>
    </tr>
    <tr>
      <th></th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>KG</th>
      <td>16</td>
      <td>71</td>
      <td>27</td>
      <td>8</td>
      <td>83</td>
      <td>0</td>
      <td>100</td>
      <td>72</td>
      <td>100</td>
      <td>42</td>
      <td>26</td>
      <td>21</td>
      <td>91</td>
      <td>5</td>
      <td>36</td>
      <td>98</td>
      <td>96</td>
      <td>52</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.loc[:, idx[:, :, 'X']]
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="3" halign="left">A</th>
      <th colspan="3" halign="left">B</th>
    </tr>
    <tr>
      <th></th>
      <th>M</th>
      <th>N</th>
      <th>O</th>
      <th>M</th>
      <th>N</th>
      <th>O</th>
    </tr>
    <tr>
      <th></th>
      <th>X</th>
      <th>X</th>
      <th>X</th>
      <th>X</th>
      <th>X</th>
      <th>X</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>KG</th>
      <td>44</td>
      <td>83</td>
      <td>-28</td>
      <td>5</td>
      <td>-31</td>
      <td>44</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.xs('Y', level=2, axis=1) - df.xs('Z', level=2, axis=1)
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="3" halign="left">A</th>
      <th colspan="3" halign="left">B</th>
    </tr>
    <tr>
      <th></th>
      <th>M</th>
      <th>N</th>
      <th>O</th>
      <th>M</th>
      <th>N</th>
      <th>O</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>KG</th>
      <td>44</td>
      <td>83</td>
      <td>-28</td>
      <td>5</td>
      <td>-31</td>
      <td>44</td>
    </tr>
  </tbody>
</table>
</div>

```python
idx = pd.IndexSlice
df.loc[:, idx[:, :, 'X']] = (df.xs('Y', level=2, axis=1) - df.xs('Z', level=2, axis=1))
df
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="9" halign="left">A</th>
      <th colspan="9" halign="left">B</th>
    </tr>
    <tr>
      <th></th>
      <th colspan="3" halign="left">M</th>
      <th colspan="3" halign="left">N</th>
      <th colspan="3" halign="left">O</th>
      <th colspan="3" halign="left">M</th>
      <th colspan="3" halign="left">N</th>
      <th colspan="3" halign="left">O</th>
    </tr>
    <tr>
      <th></th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>KG</th>
      <td>NaN</td>
      <td>71</td>
      <td>27</td>
      <td>NaN</td>
      <td>83</td>
      <td>0</td>
      <td>NaN</td>
      <td>72</td>
      <td>100</td>
      <td>NaN</td>
      <td>26</td>
      <td>21</td>
      <td>NaN</td>
      <td>5</td>
      <td>36</td>
      <td>NaN</td>
      <td>96</td>
      <td>52</td>
    </tr>
  </tbody>
</table>
</div>

This was unexpected. I realize that the indexes do not match, and hence this behavior, but I expect Pandas to throw an Exception, rather than silently do this

```python
idx = pd.IndexSlice
df.loc[:, idx[:, :, 'X']] = (df.xs('Y', level=2, axis=1) - df.xs('Z', level=2, axis=1)).values
df
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="9" halign="left">A</th>
      <th colspan="9" halign="left">B</th>
    </tr>
    <tr>
      <th></th>
      <th colspan="3" halign="left">M</th>
      <th colspan="3" halign="left">N</th>
      <th colspan="3" halign="left">O</th>
      <th colspan="3" halign="left">M</th>
      <th colspan="3" halign="left">N</th>
      <th colspan="3" halign="left">O</th>
    </tr>
    <tr>
      <th></th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>KG</th>
      <td>44</td>
      <td>71</td>
      <td>27</td>
      <td>83</td>
      <td>83</td>
      <td>0</td>
      <td>-28</td>
      <td>72</td>
      <td>100</td>
      <td>5</td>
      <td>26</td>
      <td>21</td>
      <td>-31</td>
      <td>5</td>
      <td>36</td>
      <td>44</td>
      <td>96</td>
      <td>52</td>
    </tr>
  </tbody>
</table>
</div>

This was, of course, the behavior I was expecting

**Comment by gfyoung** [comment] 2017-11-05 05:03
@kghosesbg : Thanks for reporting this!  Looks quite odd to me indeed.  This is reproducible on `master`, so feel free to investigate and see what's going on here.

**Comment by jreback** [comment] 2017-11-05 12:18
This is expected, you are assigning mismatched levels. It is pretty tricky to actually figure out what you are doing is invalid. Sure you can make an assumption that you are assigning based on sub-levels, or that the levels don't match on the left and right sides, but this is pretty fragile.
xref https://github.com/pandas-dev/pandas/issues/12343, https://github.com/pandas-dev/pandas/issues/7475, duplicate of https://github.com/pandas-dev/pandas/issues/10440

```
In [13]: df.loc[:, idx[:, :, 'X']] = (df.xs('Y', level=2, axis=1) - df.xs('Z', level=2, axis=1))

In [14]: df.loc[:, idx[:, :, 'X']]
Out[14]: 
     A           B        
     M   N   O   M   N   O
     X   X   X   X   X   X
KG NaN NaN NaN NaN NaN NaN
```

This is the correct method, essentially no alignment and a direct assignment.
```
In [16]: df.loc[:, idx[:, :, 'X']] = (df.xs('Y', level=2, axis=1) - df.xs('Z', level=2, axis=1)).values

In [17]: df
Out[17]: 
     A                                  B                                 
     M          N           O           M           N           O         
     X   Y   Z  X   Y   Z   X   Y   Z   X   Y   Z   X   Y   Z   X   Y    Z
KG  79  98  19  4  34  30 -52  34  86  29  70  41 -66  14  80 -58  42  100
```

This is very simliar in concept to the warning at the end of this section.
If you wanted to make an example for MultiIndexing would be great.

http://pandas.pydata.org/pandas-docs/stable/indexing.html#basics

**Closed by jreback** 2017-11-05 12:18 UTC
Labels: Bug, MultiIndex

**Comment by jreback** [comment] 2017-11-05 12:20
@kghosesbg we need someone to collect the cases for MultiIndex and write/re-write the logic a bit. I am not opposed to raising in a case like this, but this requires some investigation. Would be great just to have the cases listed (and we can xfail them). Then tackle later. would you be interested in this?

**Comment by kghosesbg** [comment] 2017-11-05 12:29
Hi @jreback I'm happy to help as needed, though it might go slowly. Could you please clarify the task. From you previous comment I understand that you'd like to add this example to the multi-indexing docs, which I can do. Is the next to collect these reports and put them in the test suite?

**Comment by kghosesbg** [comment] 2017-11-05 12:36
@jreback I'll probably also do this with my mild mannered private individual role which I'm tagging @kghose

**Comment by jreback** [comment] 2017-11-05 14:53
yep those are the tasks
