### ISSUE TITLE
QST: pd.pivot_table() generates wrong sums

### ISSUE THREAD

**Issue by zybex86** [pandas-dev/pandas#33587] opened 2020-04-16 10:11 UTC
- [ X ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ X ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

I have stumbled upon a strange phenomenon...

The same question asked on [StackOverflow](https://stackoverflow.com/questions/60883087/pandas-pivot-table-generates-wrong-sums)

I have a working code to generate pivoted tables from data uploaded from excels. I have stumbled on a strange case where after applying pivot_table to the data, I get different summed values than before pivot...

I generate data from xlsx and xls files, do some stuff with it and then want to generate a pivoted table. Before the pivot I do df.VAL1.sum() and df.VAL2.sum() and the values are the same ones as the ones summed in excels using =sum(), but after I run my pd.pivot_table() code I get a different result when I do pivot.sum()

The data has the following columns:
```
COL1 COL2 COL3 time_period VAL1 VAL2 UNIT_VAL1 COL4 COL5 COL6 UNIT_VAL2 COL7 COL8 COL9
```
where time_period is a string - YYYY-MM

and here is the pivot_table attributes:

```python
pivot = pd.pivot_table(
    df[[
        'COL1', 'COL2', 'COL3', 'COL9', 'time_period',
        'VAL1','COL8', 'COL4', 'COL5', 'COL6', 'COL7', 'UNIT_VAL1'
    ]],
    values='VAL1',
    columns='time_period',
    index=[
        'COL7', 'COL8', 'COL3', 'COL1',
        'COL5', 'COL2', 'COL9',
        'COL4', 'COL6', 'UNIT_VAL1'
    ],
    aggfunc=np.sum
)
```
Can the string `time_period` be the problem here or the order of the passed column names? Or maybe I am doing something wrong here? I want to note that this happens only with 2 dataframes, as other dataframes work well.

I did observe that this pivot code produces different sums after 4 decimal spaces, but that shouldn't change the sums IMHO... Maybe I should use `df.picot_table` instead of `pd.pivot_table` ? The problem is I need two tables from the data frame - one in KG and one in local CUR...

**Comment by zybex86** [comment] 2020-04-16 10:11
Probably I wont be able to give you the data to test it...

**Comment by TomAugspurger** [comment] 2020-04-16 21:14
Let us know if you can provide a reproducible example and we'll take a look.

**Comment by zybex86** [comment] 2020-04-17 08:48
unfortunately I can't give any data as this is a job project... I'll try to fiddle with the data some more, and keep u posted

**Comment by zybex86** [comment] 2020-04-28 07:06
I think I might've found the culprit - `np.sum` might be the problem, as numpy has problems with large floats. I might have to change the `aggfunc` to a regular sum or sth else. To my knowledge I might have to write a custom `pivot` ? Or is there a way to use custom `aggfunc` and not only `numpy`?

**Comment by MarcoGorelli** [comment] 2020-05-07 13:34
> Or is there a way to use custom aggfunc and not only numpy?

Yes, you can pass a custom function (e.g. `aggfunc = lambda x: sum(x)`)

Anyway, thanks @zybex86  for the report

Closing due to lack of reproducible example, but feel free to reopen if you provide one

**Closed by MarcoGorelli** 2020-05-07 13:34 UTC
Labels: Needs Info, Needs Triage, Usage Question
