### ISSUE TITLE
BUG: `read_csv` with list causes segfault

### ISSUE THREAD

**Issue by camillescott** [pandas-dev/pandas#46407] opened 2022-03-17 19:17 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

test = ['test.csv']
pd.read_csv(test)
```

### Issue Description

Running this code results in an immediate segfault. Specifying `engine = 'python'` does not, so presumably bad data is passed to the C engine. If `test` is a `dict`, `set`, or `numpy.ndarray`, a `ValueError` is raised as expected.

We discovered this error in a Snakemake rule, where the user passed `input`, which by default a list, directly to `read_csv` in a `run` block. Given Snakemake's popularity, this seems like something that could pop up fairly often.

### Expected Behavior

It should raise a `ValueError`.

### Installed Versions

My environment seems to break with this.

<details>

File ~/miniconda/envs/dissertation/lib/python3.8/site-packages/setuptools/__init__.py:8, in <module>
      5 import os
      6 import re
----> 8 import _distutils_hack.override  # noqa: F401
     10 import distutils.core
     11 from distutils.errors import DistutilsOptionError

File ~/miniconda/envs/dissertation/lib/python3.8/site-packages/_distutils_hack/override.py:1, in <module>
----> 1 __import__('_distutils_hack').do_override()

File ~/miniconda/envs/dissertation/lib/python3.8/site-packages/_distutils_hack/__init__.py:71, in do_override()
     69 if enabled():
     70     warn_distutils_present()
---> 71     ensure_local_distutils()

File ~/miniconda/envs/dissertation/lib/python3.8/site-packages/_distutils_hack/__init__.py:59, in ensure_local_distutils()
     57 # check that submodules load as expected
     58 core = importlib.import_module('distutils.core')
---> 59 assert '_distutils' in core.__file__, core.__file__

AssertionError: /home/camille/miniconda/envs/dissertation/lib/python3.8/distutils/core.py

</details>

**Comment by mroeschke** [comment] 2022-03-17 19:52
Thanks for the report. This was a duplicate of https://github.com/pandas-dev/pandas/issues/45957 which was fixed in #46325, planned to be released in 1.4.2 soon

**Closed by mroeschke** 2022-03-17 19:52 UTC
Labels: Bug, Needs Triage
