### ISSUE TITLE
BUG: `axvspan` breaks when using pandas `.plot()` wrapper

### ISSUE THREAD

**Issue by DanielHabenicht** [pandas-dev/pandas#51795] opened 2023-03-05 01:36 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
df = pd.read_csv("export.csv", index_col="Timestamp", parse_dates=True)

start = pd.Timestamp("2019-01-15 23:00:00+0000", tz="UTC")
end = pd.Timestamp("2019-02-01 09:50:00+0000", tz="UTC")
print(start)
print(df.index[0])
print(end)

fig, ax = plt.subplots()
ax.axvspan(
    start, # or df.index[0]
    end, # or df.index[-1]
    color="red",
    alpha=0.1,
    lw=0,
    zorder=1,
)

# Using the `ax.plot` method works
# ax.plot(df2.index, df2["n1"], color="black", alpha=0.2, linestyle="solid", zorder=3)

df.plot(ax=ax, alpha=0.2, linestyle="solid", zorder=3)

# Using `axvspan` before and after the plot actually works too
# Only using this axvspan method results in a blank graph
# ax.axvspan(
#     start,
#     end,
#     color="red",
#     alpha=0.1,
#     lw=0,
#     zorder=1,
# )

plt.show()
```

### Issue Description

Using the wrapper functions somehow generates weird behaviour for plotting. 
Interestingly only with the data I used here: [export.csv](https://github.com/pandas-dev/pandas/files/10890558/export.csv)

Using the `axvspan` before `df.plot()`: 
![image](https://user-images.githubusercontent.com/13590797/222936744-9fce79df-2ab3-4854-94fe-b053d5caf994.png)

Using the `axvspan` after `df.plot()`: 
![image](https://user-images.githubusercontent.com/13590797/222936779-135fe04d-3d1c-43d6-bae8-c0e68f1ab3c0.png)

### Expected Behavior

Using `axvspan` before **and** after `df.plot` or using the standard `ax.plot(x,y)` function:
![image](https://user-images.githubusercontent.com/13590797/222936820-bc782f98-964a-4d82-a6ae-9c87f4c2666f.png)

### Related

There was some weirdness reported before; https://github.com/pandas-dev/pandas/issues/5092

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.90.1-microsoft-standard-WSL2
Version          : #1 SMP Fri Jan 27 02:56:13 UTC 2023
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.4.0
pip              : 23.0
Cython           : None
pytest           : 7.2.1
hypothesis       : None
...
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by ritikBhandari** [comment] 2023-03-07 07:16
Hi @DanielHabenicht ,

When I run the code, I got the same result as it was expected to show for using axvspan() after df.plot().
![download](https://user-images.githubusercontent.com/69508348/223349601-e2eb2e49-d830-41d5-a855-4741a68edad8.png)

Regarding why the stuff works different when applied to different position is when you call `df.plot()`, it creates a new plot on the current figure with a new set of axes(). When we `axvspan()` after that, it is applied to the current set of axes which by default is the last set of axes created by the most recent plot command. So when you call `axvspan()` after `df.plot()`, it applies the shaded region to the plot that was just created by `df.plot()`.

On the other hand, when you call `axvspan()` before it, the shaded region is created on the plot before `df.plot()` is called. So it is drawn behind the plot.

You can play around with `zorder` parameter to make sure it is shown in front of the plot.

**Comment by DanielHabenicht** [comment] 2023-03-07 07:33
Hi @ritikBhandari, thanks for taking the time to reproduce the issue.

I did try it with zorder, as you can see in my example. It did not change the result:

- If I apply `axvspan` only before `df.plot` only the graph shows up
 
- If I apply 'axvspan` only after `df.plot` nothing shows up. 

- If I apply it at both position or use `ax.plot` it works as expected. 

So in short, you can't reproduce it? Then I will try to reproduce it on another machine. 

One more question: 
For `df.plot(ax=ax)` I was under the impression that it would reuse my supplied axis, because I don't see why it is supplied otherwise?

**Comment by ritikBhandari** [comment] 2023-03-07 12:06
So I tried to reproduce the code and it is showing me the shades when I apply `axvspan` after `df.plot`. This issue is mostly because of the machine you are using I guess.

And regarding why it isn't applying shades when used before `df.plot`, it is because matplotlib by-default covers the first layer (which in our case is the shade) when it  is covered by another layer(our actual plot). So that is the reason it doesn't work when applied before `df.plot`.

**Comment by DanielHabenicht** [comment] 2023-03-07 21:02
Alright, seems like I also can't reproduce the `df.plot()` => `axvspan` case on a different machine. 

But I would still expect that:
```py
ax.axvspan(start, end)
ax.plot(df.index, df["n1"], linestyle="solid", zorder=3)
```
behaves the same as:
```py
ax.axvspan(start, end)
df.plot(ax=ax, alpha=0.2, linestyle="solid", zorder=3)
```

**Comment by azjps** [comment] 2023-12-26 21:02
I didn't reproduce the exact same issue but I'm fairly certain this is the same underlying issue as #52895; `df.plot() & axvspan()` look as expected after ignoring `inferred_freq`

**Comment by mroeschke** [comment] 2024-07-17 21:12
Closing as a similar issue to https://github.com/pandas-dev/pandas/issues/52895

**Closed by mroeschke** 2024-07-17 21:12 UTC
Labels: Bug, Needs Triage
