### ISSUE TITLE
BUG: read_csv() encoding latin1 gives KeyError on 1st column in new version 1.0.3

### ISSUE THREAD

**Issue by tosingithub** [pandas-dev/pandas#34303] opened 2020-05-22 07:56 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
#data = pd.read_csv("dataset.csv", encoding="latin1").fillna(method="ffill")
data = pd.DataFrame({'Sentence #': ['Sentence 1','',''],
                   'Word': ['Thousands','of','demonstrators'],
                   'POS': ['NNS', 'IN', 'NNS']}) # this should be in the csv file to reproduce the error
gk = data.groupby('Sentence #')
print(gk.first())

```

#### Problem description
read_csv() encoding 'latin1' gives KeyError on 1st column in new version 1.0.3
This works perfectly in old version 0.25.3 but gives KeyError when run in new version 1.0.3
Works correctly when changed to 'utf-8'

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Expected Output
                 Word  POS
Sentence #
Sentence 1  Thousands  NNS

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.3
numpy            : 1.17.0
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 40.8.0
Cython           : 0.29.13
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-76-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 9.0.1
setuptools       : 39.0.1
Cython           : 0.29.14
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None

pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by asishm** [comment] 2020-09-24 23:48
I'm unable to reproduce this @tosingithub using the dataframe you have defined there.
Would you be able to share the actual csv?

**Comment by tosingithub** [comment] 2020-09-26 08:08
Thanks for your attention. CSV gladly attached.

________________________________

**Comment by tosingithub** [comment] 2020-09-26 08:10
[dataset.zip](https://github.com/pandas-dev/pandas/files/5286383/dataset.zip)

**Comment by asishm** [comment] 2020-09-28 22:31
@tosingithub the dataset you shared doesn't seem to be encoded with latin1

```py
In [14]: with open("dataset.csv", encoding="latin1") as f:
    ...:     data = f.readlines()
    ...: 

In [15]: data[0]
Out[15]: 'ï»¿Sentence #,Word,POS,Tag\n'

In [16]: with open("dataset.csv", encoding="utf8") as f:
    ...:     data = f.readlines()
    ...: 

In [17]: data[0]
Out[17]: '\ufeffSentence #,Word,POS,Tag\n'  # this gets stripped out by pandas with utf8 encoding

In [18]: with open("dataset.csv", encoding="utf-8-sig") as f:
    ...:     data = f.readlines()
    ...: 

In [19]: data[0]
Out[19]: 'Sentence #,Word,POS,Tag\n'
```

this is a UTF8-BOM encoded file (opening in VSCode shows that as well). of course using the incorrect encoding to open a file can lead to such issues.

**Comment by tosingithub** [comment] 2020-09-29 10:57
Ok thanks. But my concern was why it ran perfectly in the previous version and not the new version, which took me time to identify for my actual program?

**Comment by asishm** [comment] 2020-09-29 19:28
I did some more digging.

it seems in v0.25.3, `pd.read_csv` with defaults was just passing in the string file path to the `TextReader` at `parsers.pyx`.
but in 1.x.x onwards, a file like object is passed on to the TextReader.

this started getting a bit convoluted, but here's what I have right now.
```py
from io import TextIOWrapper
import pandas._libs.parsers as parsers

kwds = {'delimiter': ',', 'escapechar': None, 'quotechar': '"', 'quoting': 0, 'doublequote': True,
 'skipinitialspace': False, 'lineterminator': None, 'header': 0, 'index_col': None, 'names': None,
 'skiprows': None, 'na_values': {'', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
  '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan', 'null'}, 'keep_default_na': True,
 'true_values': None, 'false_values': None, 'converters': {}, 'dtype': None, 'thousands': None, 'comment': None,
 'decimal': '.', 'usecols': None, 'verbose': False, 'encoding': 'latin1', 'compression': None, 'mangle_dupe_cols': True,
 'skip_blank_lines': True, 'delim_whitespace': False, 'na_filter': True, 'low_memory': True, 'memory_map': False,
 'error_bad_lines': True, 'warn_bad_lines': True, 'float_precision': None, 'na_fvalues': set(), 'allow_leading_cols': True}

data = b'\xef\xbb\xbfSentence #,Word,POS,Tag\r\n'

with open('test.csv', 'wb') as f:
    f.write(data)

src = 'test.csv'

_reader = parsers.TextReader(src, **kwds)
print("Passing string source to TextReader", _reader.header)

kwds2  = kwds.copy()
kwds2['encoding'] = 'utf8' # as per master - not sure what this is doing
src = open('test.csv', 'rb')
src = TextIOWrapper(src, encoding="latin1", newline="")

_reader = parsers.TextReader(src, **kwds2)
print("Passing TextIOWrapper source to TextReader", _reader.header)
```

this outputs:
```
Passing string source to TextReader [['Sentence #', 'Word', 'POS', 'Tag']]
Passing TextIOWrapper source to TextReader [['ï»¿Sentence #', 'Word', 'POS', 'Tag']]
```


cc: @gfyoung if you have any other thoughts

**Comment by gfyoung** [comment] 2020-09-29 21:17
This is some great work here @asishm to try and debug this.

You may want to consider doing a `git bisect` to understand when and how this behavior change was introduced.

**Comment by JMBurley** [comment] 2020-10-22 15:37
FYI, this can be closed.  Not sure what the fix was, but it is resolved in 1.0.5 onwards.

```
import pandas as pd
# --- Two tests that should return identical results
# -- option 1
data = pd.DataFrame({'Sentence #': ['Sentence 1','',''],
                   'Word': ['Thousands','of','demonstrators'],
                   'POS': ['NNS', 'IN', 'NNS']}) # this should be in the csv file to reproduce the error
gk = data.groupby('Sentence #')
print(gk.first())
print(f"\n\n")

# -- option 2
data.to_csv("dataset.csv",index=False)
data = pd.read_csv("dataset.csv", encoding="latin1").fillna(method="ffill")
gk = data.groupby('Sentence #')
print(gk.first())
```

**Comment by asishm** [comment] 2020-10-22 16:17
I don't believe the first post gives a reproducible example (and that is not an issue on 1.0.3 as I had mentioned) - see the attached csv in https://github.com/pandas-dev/pandas/issues/34303#issuecomment-699455924

**Comment by MarcoGorelli** [comment] 2021-03-13 15:35
@JMBurley are the two printed DFs meant to be exactly the same? I just tried running your snippet on master and got
```ipython
In [1]: import pandas as pd
   ...: # --- Two tests that should return identical results
   ...: # -- option 1
   ...: data = pd.DataFrame({'Sentence #': ['Sentence 1','',''],
   ...:                    'Word': ['Thousands','of','demonstrators'],
   ...:                    'POS': ['NNS', 'IN', 'NNS']}) # this should be in the csv file to reproduce the error
   ...: gk = data.groupby('Sentence #')
   ...: print(gk.first())
   ...: print(f"\n\n")
   ...: 
   ...: # -- option 2
   ...: data.to_csv("dataset.csv",index=False)
   ...: data = pd.read_csv("dataset.csv", encoding="latin1").fillna(method="ffill")
   ...: gk = data.groupby('Sentence #')
   ...: print(gk.first())
                 Word  POS
Sentence #                
                   of   IN
Sentence 1  Thousands  NNS



                 Word  POS
Sentence #                
Sentence 1  Thousands  NNS
```

**Comment by mroeschke** [comment] 2021-08-07 22:14
Since the original issue seems resolved, I think this issue can be closed.

The example above does seem to have a difference result, but I think that's because of a `ffill`? If there is a hidden bug somewhere, probably best to open a new issue for it.

```
   Sentence #           Word  POS
0  Sentence 1      Thousands  NNS
1                         of   IN
2              demonstrators  NNS

vs 

   Sentence #           Word  POS
0  Sentence 1      Thousands  NNS
1  Sentence 1             of   IN
2  Sentence 1  demonstrators  NNS
```

**Closed by mroeschke** 2021-08-07 22:14 UTC
Labels: IO CSV, Closing Candidate
