### ISSUE TITLE
Fix validation error type `PR02` and check in CI

### ISSUE THREAD

**Issue by MarckK** [pandas-dev/pandas#25376] opened 2019-02-19 18:48 UTC
#### Problem description
In order to have a continuous check by the CI on validation error `PR02` (Unknown parameters), fixing them in the code base enables the addition to the CI for automated testing in the future.

Please see [overview of the errors](https://gist.github.com/198cfa552c727d71bd7360fda66fdbb4).

Todo:

* [ ]       get rid of the errors in the code base
* [ ]       update the `code_check.sh` script to take into account the `PR02` type of errors

**Comment by nickagian** [comment] 2019-02-21 18:00
I'll work on that if no objection!

**Comment by MarckK** [comment] 2019-02-21 18:02
Yes, please do @nickagian. :)

**Comment by nickagian** [comment] 2019-02-27 20:49
Ok, I'd like some help.

There are many cases that have the same root cause but I don't know how to solve this.

It happens when a method gets delegated from a class to another. Usually by using the `pandas.core.accessor.delegate_names` decorator.

The problem is that the new class gets a method `method_name(self, *args, **kwargs)` but the docstring it inherits` has the parameters by their names and this obviously creates validation errors.

Any ideas on how to solve this?

I thought perhaps of passing also the desired docstring to the decorator instead of using the one from the original class, but I am not sure if that is a good idea.

**Comment by TomAugspurger** [comment] 2019-02-27 20:51
@nickagian do you have an example of a method that is failing this check?

**Comment by TomAugspurger** [comment] 2019-02-27 21:06
Found one, `pd.Series.dt.to_period`. I think the proper fix is to ensure that the signature of these (generated) methods is correct. This is possible, but not the most straightforward.

**Comment by nickagian** [comment] 2019-02-27 21:12
@TomAugspurger Yes exactly, or `pandas.CategoricalIndex.rename_categories` and many more.

**Comment by TomAugspurger** [comment] 2019-02-27 21:18
If you're interested,
https://github.com/pandas-dev/pandas/blob/fe1654faa86836a0007bb513504e57c5c9935b8b/pandas/util/_decorators.py#L200-L215
provides an example of rewriting signatures. But I wouldn't include this
under "Good first issue" :)

**Comment by nickagian** [comment] 2019-03-02 22:43
I have another question, regarding the `pandas.core.groupby.base.whitelist_method_generator` function. I think there is a bug here when we check `if isinstance(f, types.MethodType):`.

This is wrong if applied directly to a class, since f is only a function not bound to any object yet. Thus, the check we do here will give False anyways.

This creates a family of PR02 errors, for example for `pandas.core.groupby.DataFrameGroupBy.quantile`. This is wrongly treated as property due to the bug (it is actually a method) and this results in this validation error.

My question is: Is there a way to do this check correctly?
I haven't found a way so I think one solution would be to add an additional parameter to the `pandas.core.groupby.base.whitelist_method_generator` function that defines the type (method or property).

The only drawback is we have to provide the method names in the `whitelist` parameter each time it is called. If you spend one minute in the code you'll notice that right now the approach is that we basically define this list in the `pandas.core.groupby.base` module (`common_apply_whitelist`, `dataframe_apply_whitelist` etc.). An alternative would be to modify these lists into dictionaries, where also the type (property or method) is provided.

**Comment by mroeschke** [comment] 2021-11-20 06:03
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/27976

**Closed by mroeschke** 2021-11-20 06:03 UTC
Labels: Docs, CI, Code Style
