### ISSUE TITLE
BUG: When the value in the data set has underscore i.e "_" and forward slash "/", the select query with where clause does not fetch actual result set.

### ISSUE THREAD

**Issue by santhosh92c** [pandas-dev/pandas#35975] opened 2020-08-29 13:34 UTC
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by MarcoGorelli** [comment] 2020-08-29 14:06
Hi @santhosh92c - please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

**Comment by santhosh92c** [comment] 2020-08-30 06:05
Hi @MarcoGorelli - Please find the example of my data set as shown below.

var data = [{ column1: "data1", column2: "data1_key_2020"}, { column1: "data2", column2: "data1" }, { column1: "data3", column2: "data1_key" }];
new Dataframe(data, ['column1', 'column2']);

SELECT distinct column1 FROM dataFrameTable where column2 IN ("data1_key_2020") 
The select query above should ideally fetch data1 only, but the result set includes data1, data2 and data3. 
This happens only when the value has an underscore or forward slash. 
Hope this information is sufficient.

**Comment by MarcoGorelli** [comment] 2020-08-30 09:26
TBH I don't know enough about SQL to figure out how to run this example - perhaps someone else here can pick this up, but ideally if you could post an example which can be copied-and-pasted that would expedite resolution

**Comment by dsaxton** [comment] 2020-08-30 13:05
@santhosh92c From your first code snippet it looks like you may be using a Javascript library. Note this is the issue tracker for the Python pandas library.

**Comment by dsaxton** [comment] 2020-08-31 13:31
Closing as unrelated to the Python library, @santhosh92c feel free to reopen if you have a question about Python pandas

**Closed by dsaxton** 2020-08-31 13:31 UTC
Labels: Needs Info
