### ISSUE TITLE
[Feature Request] Plot T/F mask directly as ones and zeros

### ISSUE THREAD

**Issue by halolord01** [pandas-dev/pandas#30292] opened 2019-12-16 22:12 UTC
#### Code Sample, a copy-pastable example if possible

```python
x = pd.Series([False,True,True,False])
x.plot()
# Error thrown!
# Running version 0.24.2
```
#### Problem description

It would be nice to be able to directly use .plot() on true / false masks. Matplotlib currently supports plotting true / false masks with the below code (using the same x variable as above): 

plt.plot(x.index, x.values)

#### Expected Output

Would be great if the code in the "code sample" section outputted the same as the matplotlib equivalent of ( plt.plot(x.index, x.values)  ), where True translates to 1, and False to zero, and plots against the index values of the series. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Windows
OS-release: 10
pandas: 0.24.2
numpy: 1.16.4
scipy: 1.2.2
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jschendel** [comment] 2019-12-17 00:15
This is a dupe of #23719 and has been fixed/enabled by #27665 where the `include_bool` kwarg was added. This will be part of the upcoming 1.0 release.

```python
In [1]: import pandas as pd; pd.__version__
Out[1]: '0.26.0.dev0+1327.g37dfcc1ac'

In [2]: x = pd.Series([False,True,True,False])

In [3]: x.plot(include_bool=True)
Out[3]: <matplotlib.axes._subplots.AxesSubplot at 0x123212518>
```

**Closed by jschendel** 2019-12-17 00:15 UTC
