### ISSUE TITLE
BUG: loading from ods ignores newlines

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#53924] opened 2023-06-29 08:26 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
In [1]: import pandas as pd

In [2]: pd.DataFrame(['a\nb']).to_csv('out.csv')

In [3]: # Then open file in LibreOffice and save as out.ods, out.xlsx and out.xls. Then:

In [4]: pd.read_excel('out.xlsx').iloc[0, 1]
Out[4]: 'a\nb'

In [5]: pd.read_excel('out.xls').iloc[0, 1]
Out[5]: 'a\nb'

In [6]: pd.read_excel('out.ods').iloc[0, 1]
Out[6]: 'ab'
```

### Issue Description

Note that this seems to depend on which application produced the file. For instance,

```python3
In [7]: pd.DataFrame(['a\nb']).to_excel('out.ods')

In [8]: pd.read_excel('out.ods').iloc[0, 1]
Out[8]: 'a\nb'
```

Still, I could reproduce with files not generated by LibreOffice (but by Google Docs).

### Expected Behavior

Newlines should appear just like when loading from Excel format.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.1.0-7-amd64
Version          : #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1 (2023-03-19)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : it_IT.UTF-8
LOCALE           : it_IT.UTF-8

pandas           : 2.0.3
numpy            : 1.24.2
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 66.1.1
pip              : 23.0.1
Cython           : 0.29.33
pytest           : 7.2.1
hypothesis       : 6.67.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.5
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : 4.11.2
bottleneck       : 1.3.5
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 1.4.46
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by rhshadrach** [comment] 2023-06-30 02:49
It's not clear to me if this is an issue with the sheet writer or the odf package, but it doesn't appear to me to be a pandas bug. Stepping through the code, we never encounter a newline to includes. However I'm not too familiar with odf, and maybe the way we're using it excludes the newline somehow?

The content of the ods file when written by LibreOffice is:

```
<table:table-cell office:value-type="string" calcext:value-type="string">
<text:p>a</text:p>
<text:p>b</text:p>
</table:table-cell>
```
It's not clear to me if two `<text:p>...</text:p>` tags back to back implies a newline or not.

**Comment by rhshadrach** [comment] 2023-06-30 02:52
Creating a cell with a newline within LibreOffice using `ctrl-enter` produces the same file structure, so I'm no longer suspecting that to be the issue.

**Comment by rhshadrach** [comment] 2023-06-30 02:55
This was reported here; closing as an upstream issue.

https://github.com/eea/odfpy/issues/114

**Closed by rhshadrach** 2023-06-30 02:55 UTC
Labels: Bug, IO Excel, Upstream issue

**Comment by toobaz** [comment] 2023-06-30 13:42
> This was reported here; closing as an upstream issue.

Great, thanks!

**Comment by dimastbk** [comment] 2023-10-03 08:00
@rhshadrach maybe fix this bug with something like https://github.com/dimastbk/pandas/commit/01a94e43ccbac0593dab1c888d142de8a46ffb65 ? I can create PR for this.

**Comment by rhshadrach** [comment] 2023-10-04 01:48
I believe such a fix would produce incorrect results for the example in `Issue Description` in the OP. The problem is that we do not reliably get line breaks or not get line breaks - as the OP reported it depends on how the file was created.

**Comment by dimastbk** [comment] 2023-10-04 05:10
It's a bug in ODSWriter, which should convert \n to `text:p`. Below are files from popular office applications: 
- [newline_office365.ods](https://github.com/pandas-dev/pandas/files/12799422/newline_office365.ods)
- [newline_libreoffice.ods](https://github.com/pandas-dev/pandas/files/12799423/newline_libreoffice.ods)
- [newline_google.ods](https://github.com/pandas-dev/pandas/files/12799424/newline_google.ods)

And handlers in some ods readers: 
* https://git.sheetjs.com/sheetjs/sheetjs/src/branch/master/bits/80_parseods.js#L606
* https://github.com/miachm/SODS/blob/master/src/com/github/miachm/sods/OdsReader.java#L502
* https://github.com/ropensci/readODS/blob/7548c3ab8778efc2d6058fc56ca84920b2e3a92f/src/read_ods_internals.cpp#L43
* https://github.com/tafia/calamine/blob/master/src/ods.rs#L561
