### ISSUE TITLE
Not supported for DataFrames Exception triggered by a simple inspect.getmembers() call on a DataFrame

### ISSUE THREAD

**Issue by RichardBruskiewich** [pandas-dev/pandas#31474] opened 2020-01-31 00:19 UTC
#### Code Sample, a copy-pastable example if possible

```python
import inspect
import pandas as pd
df = pd.DataFrame()
try:
   members = inspect.getmembers(df)
except Exception as e:
   print(e)

```
#### Problem description

A "**Not supported for DataFrames Exception**" is triggered by a simple inspect.getmembers() call on a DataFrame instance.  There are some useful libraries like the Python 'fire' library which are disabled by this bug, which was not present in Pandas Release 0.24.2 but emerged in 0.25.0

#### Expected Output

A list of DataFrame members (without crashing)

#### Output of ``pd.show_versions()``

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by s-scherrer** [comment] 2020-01-31 22:28
This is caused by this:

```python
    @property
    def _constructor_expanddim(self):
        raise NotImplementedError("Not supported for DataFrames!")
```

If we would raise an `AttributeError` here instead of `NotImplementedError` then `inspect.getmembers` should work.

**Comment by RichardBruskiewich** [comment] 2020-02-01 03:26
Yes, that would be a solution. It would fix the `inspect.getmembers` call for sure.  I don't know if there are any other exception contexts where this Exception would matter but that's a primary one.  

Can you directly fix this or should I issue a pull request on the change?

**Comment by s-scherrer** [comment] 2020-02-01 07:40
I guess you can issue a pull request, I'm not a pandas developer either.

**Comment by TomAugspurger** [comment] 2020-02-04 18:23
Moving this off 1.0.1, but can likely include it if https://github.com/pandas-dev/pandas/pull/31549 is updated in time.

**Comment by jorisvandenbossche** [comment] 2020-02-04 21:41
@TomAugspurger there is a 1.0.2 milestone for things that are not urgent enough for / blockers for 1.0.1, but still can be tracked for a bugfix release in general

**Comment by TomAugspurger** [comment] 2020-03-10 13:56
Moving off 1.0.2

**Comment by jorisvandenbossche** [comment] 2020-03-11 13:30
> Moving off 1.0.2

Let's create a 1.0.3 milestone to move issues that might be relevant for a bugfix but don't make it to 1.0.2? (not sure it is necessarily relevant for this issue, but there might be others as well)

**Comment by TomAugspurger** [comment] 2020-03-11 13:51
I'd prefer to have a label for that type of thing, to avoid polluting the 1.0.3 milestone with stuff that isn't high-priority / actively being worked on.

Perhaps labels for "Target: bugfix", "Target: minor", "Target: major", describing which release the PR is appropriate for?

**Closed** 2020-04-21 12:53 UTC
Labels: Compat
