### ISSUE TITLE
Comparison of identical values found by LGTM.com

### ISSUE THREAD

**Issue by AlexTereshenkov** [pandas-dev/pandas#26827] opened 2019-06-13 10:26 UTC
LGTM.com code analysis website found an interesting issue of comparison of identical values:

https://lgtm.com/projects/g/pandas-dev/pandas/snapshot/fe32cc08cf2e4dbdfa4aad33f3a74fada201600f/files/pandas/core/sparse/frame.py?sort=name&dir=ASC&mode=heatmap#L340

The line https://github.com/pandas-dev/pandas/blob/429078b01af47b356084c1da270b5b275fbf50f4/pandas/core/sparse/frame.py#L340

The `value == value` looks suspicious. It is there either by mistake or one was trying to check whether the value is float or not since as far as I know, the Boolean value of the comparison will always be the same, unless the value is the floating point value `float('nan')`.

If the latter, then there is a better way to do it with the `cmath.isinf(value) and not cmath.isnan(value)` to be explicit in the intention. However, maybe there is some bug in `numpy` or similar that you are trying to work around? @rockg @jreback 

I wanted to check with core developers before submitting a PR.

**Comment by jreback** [comment] 2019-06-13 10:42
this is indeed to check for float null
np.isnan would be better - note this is deprecated code

**Comment by AlexTereshenkov** [comment] 2019-06-13 10:44
I see, thanks. Is it clear to the developers that this is deprecated code? I may have missed it.
Would you still like getting a PR on this anyway?

**Comment by jreback** [comment] 2019-06-13 11:05
you can PR if u want

**Comment by jbrockmendel** [comment] 2020-09-22 01:44
close-to-duplicate of #20589

**Comment by mzeitlin11** [comment] 2021-06-26 02:25
Closing since I think that code is gone, but please ping to reopen if I've misunderstood

**Closed by mzeitlin11** 2021-06-26 02:25 UTC
Labels: Clean
