### ISSUE TITLE
API/BUG: pd.array(float_ndarray_with_nans) casts np.nan to pd.NA

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#39039] opened 2021-01-08 18:35 UTC
I was under the impression we meant to keep these as distinct concepts

**Comment by jbrockmendel** [comment] 2021-01-08 18:36
setting `data[-3] = np.nan` also gets cast to pd.NA

**Comment by phofl** [comment] 2021-01-19 20:03
Docs sound like this is intended? https://pandas.pydata.org/docs/reference/api/pandas.array.html

```
Changed in version 1.2.0: Pandas now also infers nullable-floating dtype for float-like input data
```

**Comment by jbrockmendel** [comment] 2021-01-19 20:07
@jorisvandenbossche is the one to ask on this

**Comment by jorisvandenbossche** [comment] 2021-01-20 13:50
Yes, this is not a bug but intentional behaviour. 

See the 4th bullet points in the top post of the PR implementing it (https://github.com/pandas-dev/pandas/pull/34307), but this just mentions it. Some actual discussion about is scattered through the issue on this: https://github.com/pandas-dev/pandas/issues/32265

The main reason is that any code that currently deals with numpy arrays and pandas (also internally in pandas) assumes that NaNs are treated as missing data. So for compatibility with this (preserving the "missing" semantics), we convert any NaN to NA by default when converting numpy array to a masked/nullable array. 

Now, this certainly is a topic that still needs more attention (eg adding an option to be able to preserve NaNs on input instead of converting to NA, we still need to discuss how to treat NaNs that get introduced by computations, default conversion *to* numpy, ..)

**Comment by jbrockmendel** [comment] 2021-01-20 18:48
Thanks @jorisvandenbossche.  Is there (supposed to be?) a way to actually set `data[3] = np.nan` and actually get np.nan instead of pd.NA?

**Comment by simonjayhawkins** [comment] 2021-01-22 14:51
duplicate of/covered by #32265

**Comment by mroeschke** [comment] 2021-08-15 02:43
Does look similar to #32265, continued discussion can happen on that issue

**Closed by mroeschke** 2021-08-15 02:43 UTC
Labels: API Design, Needs Discussion, NA - MaskedArrays, Closing Candidate
