### ISSUE TITLE
to_json() output format issue

### ISSUE THREAD

**Issue by hupili** [pandas-dev/pandas#14825] opened 2016-12-08 07:22 UTC
https://github.com/hupili/pandas-to-json-multi-index-issue/blob/master/pandas%20to_json%20test.ipynb

#### Code Sample, a copy-pastable example if possible

```python

df = pd.DataFrame(
    [
        ['1', '2', 'a'],
        ['1', '3', 'b'],
        ['2', '4', 'c'],
        ['3', '5', 'd']
    ],
    columns=['key1', 'key2', 'key3']
)
j = df.set_index(['key1', 'key2']).to_json()
json.loads(j)

```
#### Problem description

The exported JSON is ill-formatted

```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-8-5f4db1ed154c> in <module>()
----> 1 json.loads(j)

/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    317             parse_int is None and parse_float is None and
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:
    321         cls = JSONDecoder

/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py in raw_decode(self, s, idx)
    353         """
    354         try:
--> 355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
    357             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting ':' delimiter: line 1 column 13 (char 12)

```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.1.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 7.1.2
setuptools: 28.6.1
Cython: None
numpy: 1.11.2
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.5.1
html5lib: None
httplib2: 0.9.2
apiclient: 1.5.4
sqlalchemy: 1.1.2
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
jinja2: 2.8
boto: 2.43.0
pandas_datareader: None
In [4]:
</details>

**Comment by chris-b1** [comment] 2016-12-08 15:01
Thanks for the report - this is duplicate of #4889

**Closed by chris-b1** 2016-12-08 15:01 UTC
