### ISSUE TITLE
QST: Pandas read_excel parsing in wrong format

### ISSUE THREAD

**Issue by pathikg** [pandas-dev/pandas#49770] opened 2022-11-18 13:29 UTC
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/63067926/how-to-stop-python-auto-date-parsing-while-reading-a-excel-file

### Question about pandas

I was facing an issue for some dates in my `xlsx` file separated by dashes
![image](https://user-images.githubusercontent.com/55437218/202715110-99636d48-63a6-44ad-aa30-334235678e88.png)

after doing reading the excel, 
pandas converts this dates to ISO format but also interchanges month and day in the format

e.g. for 09-11-2018 (MM-DD-YYYY), ISO format should look like 2018-09-11T00:00:00.000Z but panda converts it into 2018-11-09T00:00:00.000Z  which is wrong since 11 is not a month 
but nothing happens for the dates in the form MM/DD/YYYY

Debugger output after doing:
```python
claim = pd.read_excel(
    file_name,
    engine='openpyxl',
    sheet_name='claim',
)
```
![image](https://user-images.githubusercontent.com/55437218/202715378-b1c73f3a-ad8c-45db-a078-d15570ef98ce.png)

why is this happening and how can i resolve this isssue?

I tried to do stop the parsing by using all the suggestions given in the StackOverflow question but none of them worked in my case as well as that question's author's case

**Comment by MarcoGorelli** [comment] 2022-11-18 14:48
Hi @pathikg - could you make your example reproducible please?

**Comment by vamsi-verma-s** [comment] 2022-11-18 15:10
@pathikg can you check if excel is converting the strings as dates by checking the data type of the cell in excel.

since you are using `openpyxl` you may also want to just try reading the sheet using `openpyxl` itself, that way it will be easier to figure out if pandas converts the strings later or not.

**Comment by MarcoGorelli** [comment] 2022-11-25 07:44
closing for now, but can reopen if you address https://github.com/pandas-dev/pandas/issues/49770#issuecomment-1320095197

**Closed by MarcoGorelli** 2022-11-25 07:44 UTC
Labels: Usage Question, Needs Info
