### ISSUE TITLE
unexpected numpy array returned when using `.loc`

### ISSUE THREAD

**Issue by sunt05** [pandas-dev/pandas#27695] opened 2019-08-01 14:18 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
dt=pd.date_range('2012','2013',freq='d')
df_test=pd.DataFrame(index=dt)
df_test['x']=123
df_test.loc['2012 2','x']

```

#### Problem description

`.loc` operation above used to return a `pd.Series` but in v0.25.0 returns a numpy array.

#### Expected Output

output:
```
array([123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
       123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
       123, 123, 123])
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.3.5
tables           : 3.5.2
xarray           : 0.12.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8

</details>

**Comment by TomAugspurger** [comment] 2019-08-01 14:32
Duplicate of https://github.com/pandas-dev/pandas/issues/27516 (I just changed the title to be more accurate).

Going to fix for 0.25.1. In the meantime you can do two indexing calls, `df_test.loc['2012-02']['x']`.

**Closed by TomAugspurger** 2019-08-01 14:32 UTC
