### ISSUE TITLE
ENH: better support for reading/writing complex numbers to a file

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#4906] opened 2013-09-20 20:49 UTC
http://stackoverflow.com/questions/18924908/remove-parentheses-from-complex-numbers-pandas/18925604#18925604

**Comment by mroeschke** [comment] 2020-05-02 03:48
Seems like a duplicate of https://github.com/pandas-dev/pandas/issues/9379

**Closed by mroeschke** 2020-05-02 03:48 UTC
Labels: Complex, Enhancement, IO Data
