### ISSUE TITLE
ENH: Different behavior of pandas when saving and restoring from a CSV file

### ISSUE THREAD

**Issue by pevogam** [pandas-dev/pandas#44639] opened 2021-11-27 12:34 UTC
#### Is your feature request related to a problem?

It seems that `df.to_csv(filename)` will automatically save the index (because of the choice of default) while `pd.read_csv(filename)` will then automatically add its own index (again because of the choice of default). A user relying on simple default behaviors doing multiple reading and writing to an CSV file will end up accumulating indices:
```
      Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1         p       q    r
0              0             0               0                 0  54.78  0.0005  1.0
1              1             1               1                 1  54.78  0.0005  1.0
2              2             2               2                 2  54.78  0.0005  1.0
3              3             3               3                 3  54.78  0.0005  1.0
4              4             4               4                 4  54.78  0.0005  1.0
...          ...           ...             ...               ...       ...     ...  ...
2360        2360          2360            2360              2360  54.78  0.0005  0.0
```
and thus can get tripped by this difference in choice of defaults.

#### Describe the solution you'd like

I would recommend settling on the same default behavior when both storing and retrieving from CSV, possibly simply not storing the index *by default* when using `to_csv` to obtain a symmetric result.

#### API breaking implications

I assume this might break the current API unless we provide a warning for the ongoing change at least for a couple of versions. After all, API is also not meant to be frozen and never improved just because it is being used.

#### Describe alternatives you've considered

None, this is just a suggestion.

#### Additional context

Possibly added above.

```

**Comment by phofl** [comment] 2021-11-27 12:48
Duplicate of #24468

**Closed by phofl** 2021-11-27 12:48 UTC
Labels: Enhancement, Needs Triage

**Comment by jreback** [comment] 2021-11-27 12:50
see #4595 and there are some others

long discussed and rejected

**Comment by pevogam** [comment] 2021-11-27 12:51
Yes, I will monitor the issue this one turned to be a duplicate of. Thanks for the hints!
