### ISSUE TITLE
Bug: groupby TimeGrouper and plotting --> TypeError: cannot concatenate a non-NDFrame object

### ISSUE THREAD

**Issue by RolandRitt** [pandas-dev/pandas#12455] opened 2016-02-26 13:01 UTC
Wan't to group a Dataframe with a DatetimeIndex by a defined frequency. I managed to get the groups by using a TimeGrouper object.

But if I plot the `DataFrameGroupBy` object i get the following

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-85ee4aed1e5a> in <module>()
     27 
     28 ax1 = grouped_data1.hist(bins = 20, normed=True) # --> groubb
---> 29 ax2 = grouped_data2.hist(bins = 20, normed=True) # --> groupby

C:\Anaconda3\lib\site-packages\pandas\core\groupby.py in wrapper(*args, **kwargs)
    528             # exception below
    529             if name in _plotting_methods:
--> 530                 return self.apply(curried)
    531 
    532             try:

C:\Anaconda3\lib\site-packages\pandas\core\groupby.py in apply(self, func, *args, **kwargs)
    637         # ignore SettingWithCopy here in case the user mutates
    638         with option_context('mode.chained_assignment', None):
--> 639             return self._python_apply_general(f)
    640 
    641     def _python_apply_general(self, f):

C:\Anaconda3\lib\site-packages\pandas\core\groupby.py in _python_apply_general(self, f)
    644 
    645         return self._wrap_applied_output(keys, values,
--> 646                                          not_indexed_same=mutated)
    647 
    648     def _iterate_slices(self):

C:\Anaconda3\lib\site-packages\pandas\core\groupby.py in _wrap_applied_output(self, keys, values, not_indexed_same)
   3318             # Handle cases like BinGrouper
   3319             return self._concat_objects(keys, values,
-> 3320                                         not_indexed_same=not_indexed_same)
   3321 
   3322     def _transform_general(self, func, *args, **kwargs):

C:\Anaconda3\lib\site-packages\pandas\core\groupby.py in _concat_objects(self, keys, values, not_indexed_same)
    807                 group_names = self.grouper.names
    808                 result = concat(values, axis=self.axis, keys=group_keys,
--> 809                                 levels=group_levels, names=group_names)
    810             else:
    811 

C:\Anaconda3\lib\site-packages\pandas\tools\merge.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
    832                        keys=keys, levels=levels, names=names,
    833                        verify_integrity=verify_integrity,
--> 834                        copy=copy)
    835     return op.get_result()
    836 

C:\Anaconda3\lib\site-packages\pandas\tools\merge.py in __init__(self, objs, axis, join, join_axes, keys, levels, names, ignore_index, verify_integrity, copy)
    888         for obj in objs:
    889             if not isinstance(obj, NDFrame):
--> 890                 raise TypeError("cannot concatenate a non-NDFrame object")
    891 
    892             # consolidate

TypeError: cannot concatenate a non-NDFrame object
```

If I only plot a specific column (SeriesGroupBy) there is no problem!

My code:

```
import os
import sys
import datetime
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.dates as mdates
import numpy as np


%matplotlib notebook


dates = pd.date_range('2013-07-14 11:00:00', '2013-07-16 11:00:00', freq = 's')
cats = np.random.choice(['m', 'f', 'c'], len(dates))
data =np.random.randn(len(dates),1)
data2 =np.random.randn(len(dates),1)

df = pd.DataFrame(data, dates)
df.columns = ['data']
df['cats']= cats
df['data2'] = data2


plt.figure()
grouped_data1 = df.groupby(pd.TimeGrouper('1D'))['data'] # SeriesGroupBy object
grouped_data2 = df.groupby(pd.TimeGrouper('1D')) # DataFrameGroupBy object

ax1 = grouped_data1.hist(bins = 20, normed=True) # Does work
ax2 = grouped_data2.hist(bins = 20, normed=True) # gives Type Error
```

Pandas Version:

```
pd.__version__
'0.18.0rc1'
```

**Comment by jreback** [comment] 2016-02-27 02:19
cc @TomAugspurger @sinhrks

**Comment by sinhrks** [comment] 2016-02-27 22:31
Thanks for the report.

This occurs when a closure passed to ``apply`` returns other than ``pandas`` concatable instance. Still not sure whether we can use the same path in normal groupby and ``TimeGrouper``.

```
def f(x):
    return np.array([1, 1])

# OK
df.groupby('cats').apply(f)
# cats
# c    [1, 1]
# f    [1, 1]
# m    [1, 1]
# dtype: object

df.groupby(pd.TimeGrouper('1D')).apply(f)
# TypeError: cannot concatenate a non-NDFrame object
```

**Comment by discort** [comment] 2018-08-29 14:30
@jreback @sinhrks 

I couldn't reproduce the issue.

### Version
<details>

INSTALLED VERSIONS
------------------
commit: d5f30fa36a405a567a7733141dfce348601e5bbe
python: 3.5.3.candidate.1
python-bits: 64
OS: Darwin
OS-release: 16.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.0.dev0+518.gd5f30fa36
pytest: 3.7.2
pip: 18.0
setuptools: 33.1.1
Cython: 0.28.4
numpy: 1.12.0
scipy: None
pyarrow: None
xarray: None
IPython: 5.2.2
sphinx: 1.6.6
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.5
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

<img width="1083" alt="screen shot 2018-08-29 at 5 28 21 pm" src="https://user-images.githubusercontent.com/4944021/44794335-f6eb2700-abb0-11e8-874c-da7dac2c7bc0.png">

Original issue:

<img width="939" alt="screen shot 2018-08-29 at 5 29 44 pm" src="https://user-images.githubusercontent.com/4944021/44794432-30239700-abb1-11e8-9752-bc03076a4948.png">

**Comment by mroeschke** [comment] 2019-10-16 04:09
`TimeGrouper` has been removed so I don't think this is an issue anymore. Closing

**Closed by mroeschke** 2019-10-16 04:09 UTC
Labels: Difficulty Intermediate, Effort Low, Groupby, Resample, Visualization
