### ISSUE TITLE
BUG: `date_range` with `end`, `periods`, and `freq` failing for very long range

### ISSUE THREAD

**Issue by Charlie-XIAO** [pandas-dev/pandas#53604] opened 2023-06-11 16:46 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> start = pd.Timestamp("1700-01-01")
>>> end = pd.Timestamp("2000-01-01")
>>> dti = pd.date_range(start=start, end=end, freq="1D")
>>> dti
DatetimeIndex(['1700-01-01', '1700-01-02', '1700-01-03', '1700-01-04',
               '1700-01-05', '1700-01-06', '1700-01-07', '1700-01-08',
               '1700-01-09', '1700-01-10',
               ...
               '1999-12-23', '1999-12-24', '1999-12-25', '1999-12-26',
               '1999-12-27', '1999-12-28', '1999-12-29', '1999-12-30',
               '1999-12-31', '2000-01-01'],
              dtype='datetime64[ns]', length=109573, freq='D')
>>> pd.date_range(end=end, periods=len(dti), freq="1D")
DatetimeIndex([], dtype='datetime64[ns]', freq='D')
```

### Issue Description

This bug does not exist on the latest version of pandas, but exists on the main branch on my local machine. When using a very long date range and specifying `end`, `periods`, and `freq`, `date_range` returns an empty `DateIndex`. For more details, please see #53293 and #53294.

### Expected Behavior

The following is the behavior on the latest version of pandas (v2.1.0):

```python
>>> import pandas as pd
>>> start = pd.Timestamp("1700-01-01")
>>> end = pd.Timestamp("2000-01-01")
>>> dti = pd.date_range(start=start, end=end, freq="1D")
>>> dti
DatetimeIndex(['1700-01-01', '1700-01-02', '1700-01-03', '1700-01-04',
               '1700-01-05', '1700-01-06', '1700-01-07', '1700-01-08',
               '1700-01-09', '1700-01-10',
               ...
               '1999-12-23', '1999-12-24', '1999-12-25', '1999-12-26',
               '1999-12-27', '1999-12-28', '1999-12-29', '1999-12-30',
               '1999-12-31', '2000-01-01'],
              dtype='datetime64[ns]', length=109573, freq='D')
>>> pd.date_range(end=end, periods=len(dti), freq="1D")
DatetimeIndex(['1700-01-01', '1700-01-02', '1700-01-03', '1700-01-04',
               '1700-01-05', '1700-01-06', '1700-01-07', '1700-01-08',
               '1700-01-09', '1700-01-10',
               ...
               '1999-12-23', '1999-12-24', '1999-12-25', '1999-12-26',
               '1999-12-27', '1999-12-28', '1999-12-29', '1999-12-30',
               '1999-12-31', '2000-01-01'],
              dtype='datetime64[ns]', length=109573, freq='D')
```

### Installed Versions

<details>

<p></p>

```
INSTALLED VERSIONS
------------------
commit           : 5cf5c734cf01a8994aab29828acb36065592d3a4
python           : 3.9.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : Chinese (Simplified)_China.936

pandas           : 2.1.0.dev0+941.g5cf5c734cf.dirty
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 56.0.0
pip              : 21.1.3
Cython           : 0.29.33
pytest           : 7.3.1
hypothesis       : 6.75.9
sphinx           : 6.2.1
blosc            : 1.11.1
feather          : None
xlsxwriter       : 3.1.2
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : 1.0.3
psycopg2         : 2.9.6
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : 1.3.7
brotli           :
fastparquet      : 2023.4.0
fsspec           : 2023.5.0
gcsfs            : 2023.5.0
matplotlib       : 3.7.1
numba            : 0.57.0
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 12.0.0
pyreadstat       : 1.2.2
pyxlsb           : 1.0.10
s3fs             : 2023.5.0
scipy            : 1.10.1
snappy           :
sqlalchemy       : 2.0.15
tables           : 3.8.0
tabulate         : 0.9.0
xarray           : 2023.5.0
xlrd             : 2.0.1
zstandard        : 0.21.0
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
```

</details>

**Comment by Charlie-XIAO** [comment] 2023-06-12 09:12
There is actually a similar test and it does not fail in the CI for pandas Windows builds, so I think it's even a more specific issue.

**Comment by topper-123** [comment] 2023-06-12 16:33
This is the result on my machine (m1 mac):

```
>>> import pandas as pd
>>> start = pd.Timestamp("1700-01-01")
>>> end = pd.Timestamp("2000-01-01")
>>> dti = pd.date_range(start=start, end=end, freq="1D")
>>> dti
DatetimeIndex(['1700-01-01', '1700-01-02', '1700-01-03', '1700-01-04',
               '1700-01-05', '1700-01-06', '1700-01-07', '1700-01-08',
               '1700-01-09', '1700-01-10',
               ...
               '1999-12-23', '1999-12-24', '1999-12-25', '1999-12-26',
               '1999-12-27', '1999-12-28', '1999-12-29', '1999-12-30',
               '1999-12-31', '2000-01-01'],
              dtype='datetime64[ns]', length=109573, freq='D')
>>> pd.date_range(end=end, periods=len(dti), freq="1D")
DatetimeIndex(['1700-01-01', '1700-01-02', '1700-01-03', '1700-01-04',
               '1700-01-05', '1700-01-06', '1700-01-07', '1700-01-08',
               '1700-01-09', '1700-01-10',
               ...
               '1999-12-23', '1999-12-24', '1999-12-25', '1999-12-26',
               '1999-12-27', '1999-12-28', '1999-12-29', '1999-12-30',
               '1999-12-31', '2000-01-01'],
              dtype='datetime64[ns]', length=109573, freq='D')
```

Looks as expected.

**Comment by mroeschke** [comment] 2024-07-17 21:47
I cannot reproduce this issue either on my end and since it doesn't fail on the CI as well unfortunately closing

**Closed by mroeschke** 2024-07-17 21:47 UTC
Labels: Bug, Datetime, Needs Triage
