### ISSUE TITLE
BUG: split(expand=True) with boolean indexing set existing columns to np.NaN

### ISSUE THREAD

**Issue by jouvin** [pandas-dev/pandas#44726] opened 2021-12-02 18:49 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
#!/bin/env python
#
# Script to test/demonstrate a problem with Pandas split(expand=True) with Pandas 1.3.4
# when trying to assign values to existing columns

import numpy as np
import pandas as pd

# Create a dataframe with 2 columns
df = pd.DataFrame(
    data=[
        ["A", "B", "B / Z"],
#        ["A", "B", np.NaN],
        ["C", "D", "Y"],
        ["E", "F", np.NaN],
    ],
    columns=["master", "project", "project_saved"],
)
print("Initial dataframe")
print(df)
print()

# Attempt to update the initial "master" and "project" columns by splitting "project_saved" on /.
# Works but unfortunately set these columns to np.NaN when project_saved is np.Nan, as expected.
df.project_saved = df.project_saved.astype("object")
df[["master", "project"]] = df.project_saved.str.split(" / ", 1, expand=True)
print(
    "Updated master and project columns by splitting project_saved"
)
print(df)
print()

# Reset dataframe to original values
df = pd.DataFrame(
    data=[
        ["A", "B", "B / Z"],
#        ["A", "B", np.NaN],
        ["C", "D", "Y"],
        ["E", "F", np.NaN],
    ],
    columns=["master", "project", "project_saved"],
)
print("Reset dataframe to initial values")
print(df)
print()


# Attempt to update the initial "master" and "project" columns when "project_saved" is not np.Nan
# by splitting "project_saved" value into 2 parts (separator=/).
# Unfortunately doesn't work: the columns are set to np.NaN if the condition project_saved.notna()
# is true (and preserved when false as expected).
df.project_saved = df.project_saved.astype("object")
df.loc[
    df.project_saved.notna(),
    ["master", "project"],
] = df.project_saved.str.split(" / ", 1, expand=True)
print(
    "Updated master and project columns by splitting project_saved if not np.Nan"
)
print(df)
```

### Issue Description

I want to split a column value into 2 parts and assigned the returned values to 2 existing columns in the dataset, if the column to split has a value different than `np.NaN` (values for this column are initialized to `np.Nan`). Unfortunately, the result is that the 2 columns are set to `np.Nan` for the selected rows. It works as expected if assigning to new columns (except if no row can be successfully splitted because of  https://github.com/pandas-dev/pandas/issues/35807#issuecomment-676912441). It also works as expected with the existing columns if removing the boolean indexing condition but with the (unwanted) side effect of setting to `np.NaN` the rows where the column to split has a value equals to `np.NaN` (thus the boolean indexing).

### Expected Behavior

Existing columns updated by the `split()` result.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : fr_FR.UTF-8
LOCALE           : fr_FR.cp1252

pandas           : 1.3.4
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 59.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.4.27
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
</details>

**Comment by mroeschke** [comment] 2021-12-27 20:01
This is the expected behavior due to the indexing behavior.

When setting a the split result which is a `DataFrame`, column alignment must match as well

```
In [12]: assign = df.project_saved.str.split(" / ", 1, expand=True)

In [13]: assign.columns = ["master", "project"]

In [14]: df = pd.DataFrame(
    ...:     data=[
    ...:         ["A", "B", "B / Z"],
    ...: #        ["A", "B", np.NaN],
    ...:         ["C", "D", "Y"],
    ...:         ["E", "F", np.NaN],
    ...:     ],
    ...:     columns=["master", "project", "project_saved"],
    ...: )

In [15]: df.loc[
    ...:     df.project_saved.notna(),
    ...:     ["master", "project"],
    ...: ] = assign

In [16]: df
Out[16]:
  master project project_saved
0      B       Z         B / Z
1      Y    None             Y
2      E       F           NaN
```

Closing due to a usage question.

**Closed by mroeschke** 2021-12-27 20:01 UTC
Labels: Bug, Needs Triage
