### ISSUE TITLE
pd.merge on Categoricals duplicating unique rows

### ISSUE THREAD

**Issue by cdknox** [pandas-dev/pandas#16767] opened 2017-06-24 17:24 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

# create our dataframe
m = 5
temp = pd.DataFrame({
        'a': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] * m,
        'b': ['t', 'w', 'x', 'y', 'z'] * 2 * m,
        'c': [letter 
              for each in ['m', 'n', 'u',  'p', 'o']
              for letter in [each] * 2 * m],
        'd': [letter 
              for each in ['aa', 'bb', 'cc', 'dd', 'ee',
                           'ff', 'gg', 'hh','ii', 'jj']
              for letter in [each] * m],

    })

# change them all to categorical variables
for c in temp.columns:
    temp[c] = temp[c].astype('category')

# get the dimensions before we do anything
print(temp.shape)

# drop duplicates to make sure this is unqiue
# it should be unique
id_df = temp.drop_duplicates()
print(id_df.shape)

# join a row-wise unique dataset to itself on all variables
# when they're categorical variables it duplicates rows
# when they're strings things behave as they're suppposed to
temp1 = pd.merge(temp, id_df, on = list(temp.columns))
print(temp1.shape)

```
#### Problem description
Using merge on Categorical dtypes doesn't appear to be checking equality correctly.  Merging a unique dataframe to itself on 4 Categorical columns appears to duplicate rows.  The above code example is simpler than what I experienced the issue on but the behavior is there.

The dataframe as it is created is a 50 row by 4 column dataframe of strings.  Casting the strings to Categoricals to save on RAM appears to work well.  Running the drop_duplicates method and checking the dimensions shows that each row is unique.  Then simply merging the dataframes together results in a 54 row by 4 column dataframe.

My guess is that there is something about the way the values are assigned that underlie the labels differs and that the underlying values may be equal when the labels aren't.  It appears to be a fairly specific case, as commenting any of those columns out results in what I'd expect in terms of output.

#### Expected Output

Running the same code and steps as illustrated in the prior paragraph without casting the columns to a Categorical dtype results in what I would expect: a 50 row by 4 column dataframe.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.20.2
pytest: 2.8.5
pip: 9.0.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.13.0
scipy: 0.17.0
xarray: None
IPython: 4.1.2
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
feather: None
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by chris-b1** [comment] 2017-06-26 17:44
Yeah, something strange going on here - not sure where it's going wrong- @jreback any guess?

```python
In [109]: temp1[temp1.duplicated()]
Out[109]: 
    a  b  c   d
4   d  y  m  aa
6   c  x  u  ee
12  i  y  m  bb
14  h  x  u  ff

In [110]: f = lambda x: (x.a == 'd') & (x.b == 'y') & (x.c == 'm') & (x.d == 'aa')

In [111]: temp1[f]
Out[111]: 
   a  b  c   d
3  d  y  m  aa
4  d  y  m  aa

In [112]: left = temp[f]; left
Out[115]: 
   a  b  c   d
3  d  y  m  aa

In [113]: right = id_df[f]; right
Out[116]: 
   a  b  c   d
3  d  y  m  aa

In [114]: left.merge(right)
Out[114]: 
   a  b  c   d
0  d  y  m  aa

```

**Comment by jorisvandenbossche** [comment] 2017-06-27 07:46
This seems to be a regression from 0.19.2 as well, as there I get the correct (50, 4) shape.

**Comment by cdknox** [comment] 2017-06-27 13:26
Ah, yeah I can confirm that it was working back on 0.18.1 as well if that's of any use

**Comment by jreback** [comment] 2017-06-28 11:06
fixed in #16786 

so when we have only a *single* categorical merge column, factorization is the same as the codes themselves. However for multiple this is not true (as we expand the space to allow for potential i8 overflow, which we then must factorize).

This still allows the perf benefits (IOW we are using codes, which are i8 rather than the categories datatype).

**Comment by cdknox** [comment] 2017-06-28 14:50
Awesome!

For my own edification, factorizing the codes effectively gives them an integer label for quick checking of equality if I understand correctly.  This meant that we gave every combination an integer label, which caused it to overflow?

Greatly appreciate the time spent!  Also, as I am new to Github, and it sounds like the issue is fixed, is convention for the author of the issue (me) to close it or for the person who fixed the issue to close it?

**Comment by jorisvandenbossche** [comment] 2017-06-28 16:08
> Also, as I am new to Github, and it sounds like the issue is fixed, is convention for the author of the issue (me) to close it or for the person who fixed the issue to close it?

We only close the issue when the fix is actually merged (at the moment it is only a proposed change in an open PR). But when we merge the PR, this issue will be automatically closed.

**Closed** 2017-06-30 19:49 UTC
Labels: Bug, Categorical, Regression, Reshaping
