### ISSUE TITLE
DOC: Example for plotting scatterplot matrices is incomplete

### ISSUE THREAD

**Issue by GMTSE** [pandas-dev/pandas#39527] opened 2021-02-01 12:41 UTC
#### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/visualization.html#scatter-matrix-plot

#### Documentation problem

In the above-mentioned documentation, the following code is suggested to build/display a scatterplot matrix:
```
df = pd.DataFrame(np.random.randn(1000, 4), columns=["a", "b", "c", "d"])
scatter_matrix(df, alpha=0.2, figsize=(6, 6), diagonal="kde");
```

This code indeed builds something, and returns a numpy array, but it does not display the graphics.

If one does not have a look at the source code or at one a the very few other docs on the subject, like:
https://stackoverflow.com/questions/7941207/is-there-a-function-to-make-scatterplot-matrices-in-matplotlib
https://stackoverflow.com/questions/34347145/pandas-plot-doesnt-show
Or if one is a newbie in Python/DataScience/Pandas and does not know about matplotlib. One will never know how to get the graphics to display. And neither the numpy array returned nor the docs/proposed-completions proposed by most IDE will give you any hint of the problem and/or its solution :{ 

#### Suggested fix for documentation

- Suggested correction to the doc: add the fact that to display the graph you need both 1/ to import an external module & 2/ to call a method of this module
 
```
import matplotlib.pyplot as plt, plt.show()
```

- Why? Because documentation examples should be self sufficient and provide MVE.

PS: I've not looked at the other type of graphs' example, but the problem might be the same for their MVE.

**Comment by MarcoGorelli** [comment] 2021-02-01 13:14
Hi @GMTSE 

This displays fine for me without importing matplotlib, in JupyterLab:

![image](https://user-images.githubusercontent.com/33491632/106463169-fac0b900-648e-11eb-9c70-3b919dea90b4.png)

How did you run the example?

**Comment by GMTSE** [comment] 2021-02-03 21:20
Hi,

Thanks for your quick response.

Initially I ran it from Emacs, in a Python (IPython?) Shell...

I just tried to run your example from CLI, with `python3`, and it did not display either, I had to import `matplotlib`.

**Comment by MarcoGorelli** [comment] 2021-02-04 10:13
Found it - closing as a duplicate of #39130 , there's a PR already open to address it

**Closed by MarcoGorelli** 2021-02-04 10:13 UTC
Labels: Docs, Needs Triage
