### ISSUE TITLE
BUG: RangeIndex is not being appened correctly

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#38104] opened 2020-11-27 03:19 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> df1 = pd.DataFrame({'a':[1, 2, 3]})
>>> df1.to_parquet('abc/one.parquet')
>>> df2 = pd.DataFrame({'a':[4, 5, 6]})
>>> df2.to_parquet('abc/two.parquet')
>>> df3 = pd.DataFrame({'a':[7, 8, 9]})
>>> df3.to_parquet('abc/three.parquet')
>>> pd.read_parquet('abc/')
   a
0  1
1  2
2  3
3  7
4  8
5  9
6  4
7  5
8  6

```

#### Problem description

When there are multiple parquet files with identical/non-identical  RangeIndex objects I think doing `pd.read_parquet` should ideally be appending all the RangeIndex objects of each parquet file.

#### Expected Output

```python
>>> pd.read_parquet('abc/')
   a
0  1
1  2
2  3
0  7
1  8
2  9
0  4
1  5
2  6
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.1.0
Version          : Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.4
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 50.3.0
Cython           : None
pytest           : None
hypothesis       : 5.29.0
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jorisvandenbossche** [comment] 2020-11-27 08:23
Similarly as in https://github.com/pandas-dev/pandas/issues/38058, this is behaviour that is controlled by `pyarrow`. At the moment, pyarrow only tries to restore the RangeIndex if the one in the metadata can match for the *full* resulting DataFrame, which is not the case when reading from partitioned files.

If you want to preserve the index, I recommend you to specify `index=True` in `to_parquet()` so that the index is stored as an actual physical column, and then you will get your expected behaviour.

**Comment by mroeschke** [comment] 2021-08-14 16:54
Thanks for the report. Since this behavior is due to pyarrow, doesn't seem that there's anything to address in pandas. Closing.

**Closed by mroeschke** 2021-08-14 16:54 UTC
Labels: IO Parquet, Upstream issue
