### ISSUE TITLE
BUG: v1.3.1 ImportError: DLL load failed

### ISSUE THREAD

**Issue by codedawi** [pandas-dev/pandas#42733] opened 2021-07-26 16:38 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```sh
pip install pandas==1.3.1
```

```python
import pandas as pd
```

#### Problem description

After upgrading from `v1.3.0` to patch fix `v1.3.1` we began receiving Import Errors on all of our scripts. We were able to resolve this by installing [Visual Studio C++ Build Tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) on our Windows Servers.

- 2019 Windows Server
- Python 3.7

### Output `` ImportError: DLL load failed``

<details>

```
    import pandas._libs.window.aggregations as window_aggregations
ImportError: DLL load failed: The specified module could not be found.
```

</details>

**Comment by jbrockmendel** [comment] 2021-07-26 18:16
@simonjayhawkins have we dropped py37 in 1.3.1?

**Comment by simonjayhawkins** [comment] 2021-07-26 18:38
no. but the vm image for windows builds was updated. https://github.com/MacPython/pandas-wheels/pull/145 cc @lithomas1

**Comment by lithomas1** [comment] 2021-07-27 04:07
On it, will send PR tmrw(it's nighttime now for me). Looks like I either copied the wrong DLLs or missed some. We should really figure out an automated way to do this.(auditwheel/delocate do this for  Linux and macos) Feel free to revert the offending Or in the meantime.

Sorry for the hassle everyone.

**Comment by lithomas1** [comment] 2021-07-27 04:38
IIUC, wheels are a manual upload, so it might be possible to delete the bad 1.3.1 wheel and replace it?

**Comment by simonjayhawkins** [comment] 2021-07-27 08:56
> IIUC, wheels are a manual upload, so it might be possible to delete the bad 1.3.1 wheel and replace it?

I don't have access to delete wheels. PyPI doesn't have a build number like conda? cc @jreback

**Comment by jreback** [comment] 2021-07-27 09:28
no we cannot delete - do for 1.3.2

**Comment by lithomas1** [comment] 2021-07-27 15:57
This comment might be relevant.
https://github.com/pandas-dev/pandas/issues/32857#issuecomment-608023745

Looking at the aggregations pyd file in Dependencies(https://github.com/lucasg/Dependencies) and this is what I see.
![image](https://user-images.githubusercontent.com/47963215/127186145-0a5bc019-a0e0-4e92-8b72-a7f3d69c9d9e.png)
Perhaps we need to also redistribute vcruntime140_1.dll? Not sure if we need to copy vcruntime140.dll. We are already copying msvcp140.dll and concrt140.dll. 

This stuff is a PITA for me to test since you can't reproduce if you already have the VS Build Tools, which is present on CI and on my computer. Will try to get a docker environment set up to fix.

**Comment by lithomas1** [comment] 2021-07-28 20:38
I've successfully repro'ed on a docker container on azure pipelines. 
See this build.
https://dev.azure.com/thomasli1234567890/pandas/_build/results?buildId=14&view=logs&j=ebcc7698-9622-5b0b-70f1-97d524978b97&t=35171cfe-4e12-5594-dedd-5aa138cbadd2
Testing my solution now.

**Comment by simonjayhawkins** [comment] 2021-08-11 18:13
@lithomas1 https://github.com/MacPython/pandas-wheels/pull/148 has been merged. can we close this issue?

**Comment by lithomas1** [comment] 2021-08-11 20:41
Sure I guess. I think that we probably want to open a new issue about automatically catching the missing DLL issue, as this is the second time its happened(and we don't want it to happen every time we upgrade Visual Studio).

**Comment by simonjayhawkins** [comment] 2021-08-12 10:33
> open a new issue about automatically catching the missing DLL issue

issue should be in https://github.com/MacPython/pandas-wheels

**Closed by simonjayhawkins** 2021-08-12 10:33 UTC
Labels: Build, Windows, Blocker
