### ISSUE TITLE
DOC: Frames not displayed correctly in Styler user guide 

### ISSUE THREAD

**Issue by geo7** [pandas-dev/pandas#49800] opened 2022-11-20 13:16 UTC
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html

### Documentation problem

Seems that something is off with the number of digits displayed - I've not looked into the reason for this - just a heads up: 

![image](https://user-images.githubusercontent.com/8526351/202904001-c93486f7-27da-4182-b0ae-d8fd902c54ef.png)

### Suggested fix for documentation

No suggestion - just reporting.

**Comment by rhshadrach** [comment] 2022-11-20 13:31
Thanks for the report! Further investigations and PRs to fix are welcome.

cc @attack68

**Comment by attack68** [comment] 2022-11-20 14:01
This is a duplicate of #48644.

There seems to be a change with the way Sphinx handles HTML frames and/or how default CSS is handled moving from 1.4.x to 1.5.0.

I do not believe this a caused by a pandas change but the versions of those external doc builder extensions.

Haven't managed to narrow it down or come up with a solution as of yet.

**Comment by rhshadrach** [comment] 2022-11-20 14:05
Thanks @attack68 - closing as duplicate.

**Closed by rhshadrach** 2022-11-20 14:05 UTC
Labels: Bug, Docs, Duplicate Report, Styler
