### ISSUE TITLE
BUG: qcut bins error

### ISSUE THREAD

**Issue by 0x30** [pandas-dev/pandas#57209] opened 2024-02-02 06:30 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
res, bins = pd.qcut([500, 600, 600, 500, 600, 1000, 2000, 3000], q=2, retbins=True)
print(res, bins)

res = pd.cut([500, 600, 600, 500, 600, 1000, 2000, 3000], bins=bins)
print(res)
```

### Issue Description

```python
res, bins = pd.qcut([500, 600, 600, 500, 600, 1000, 2000, 3000], q=2, retbins=True)
res, bins
# ([(499.999, 600.0], (499.999, 600.0], (499.999, 600.0], (499.999, 600.0], (499.999, 600.0], (600.0, 3000.0], (600.0,  3000.0], (600.0, 3000.0]]
# Categories (2, interval[float64, right]): [(499.999, 600.0] < (600.0, 3000.0]], 
# array([ 500.,  600., 3000.]))
```

```python
pd.cut([500, 600, 600, 500, 600, 1000, 2000, 3000], bins=bins)
# [NaN, (500.0, 600.0], (500.0, 600.0], NaN, (500.0, 600.0], (600.0, 3000.0], (600.0, 3000.0], (600.0, 3000.0]]
# Categories (2, interval[float64, right]): [(500.0, 600.0] < (600.0, 3000.0]]
```

![image](https://github.com/pandas-dev/pandas/assets/6121524/22af0411-b34a-4894-836e-9148118df054)

### Expected Behavior

`bins` should start `499.999 `

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : fd3f57170aa1af588ba877e8e28c158a20a4886d
python                : 3.11.3.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.3.0
Version               : Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
machine               : x86_64
processor             : i386
byteorder             : little
LC_ALL                : None
LANG                  : zh_CN.UTF-8
LOCALE                : zh_CN.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 66.0.0
pip                   : 23.0.1
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : 1.0.3
psycopg2              : None
jinja2                : None
IPython               : 8.13.2
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : 2.0.13
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment] 2024-02-03 11:59
Thanks for the report. Closing as a duplicate of #51532.

**Closed by rhshadrach** 2024-02-03 11:59 UTC
Labels: Bug, Needs Triage

**Comment by 0x30** [comment] 2024-02-04 02:19
I'm sorry, personally I think it's not that the cut accuracy is inaccurate, but rather that qcut gave the wrong bins. I'm not very sure if this is the same mistake

I think what qcut should return in the above example is `array([ 499.99.,  600., 3000.]))`

**Comment by rhshadrach** [comment] 2024-02-04 14:41
From that issue:

> NOTE 1: The same problem exists with `pd.qcut` which cuts the data into buckets based on data quantiles. In that case it could be argued that that is desirable, so that you have the correct proportion of data in each bin. E.g. if using the quartiles, then the way it currently works means that 25% of the data will get into each bucket. Whereas the way I am suggesting, you can get more or less data in each bucket. However that argument isn't very strong with pd.cut. And in any case, I think that correctly binning data should always be the primary consideration, and size of bins secondary to that.

Your result separates the data into two bins each of size 3 - satisfying `q=2` but at the expense of not binning certain data points. I think that makes this the same issue.

Let me know if you still disagree!

**Comment by 0x30** [comment] 2024-02-05 03:17
Sorry to bother you

in [qcut document](https://github.com/pandas-dev/pandas/blob/46fd7114d6ded7dcd58499776175d4ccfd04d9da/pandas/core/reshape/tile.py#L319)

```
Examples
--------
>>> pd.qcut(range(5), 4)
... # doctest: +ELLIPSIS
[(-0.001, 1.0], (-0.001, 1.0], (1.0, 2.0], (2.0, 3.0], (3.0, 4.0]]
Categories (4, interval[float64, right]): [(-0.001, 1.0] < (1.0, 2.0] ...
```
use qcut will return right close interval `Categories (4, interval[float64, right]): [(-0.001, 1.0] < (1.0, 2.0]` 

Here is what I want to do. I have a batch of data here, and i hope `quct` group data and give me `bins`, i use `bins` to group other data

```python
res, bins = pd.qcut([1, 2], q=2, retbins=True)

# get result
# ([(0.999, 1.5], (1.5, 2.0]]
# Categories (2, interval[float64, right]): [(0.999, 1.5] < (1.5, 2.0]],
# array([1. , 1.5, 2. ]))
```

and use qcut return bins to exec `pd.cut([1,2], bins = bins)` get

```
pd.cut([1, 2], bins=bins)

# get result
# [NaN, (1.5, 2.0]]
# Categories (2, interval[float64, right]): [(1.0, 1.5] < (1.5, 2.0]]
```

I didn't get the result I wanted until I used `include_lowest`

```python
pd.cut([1, 2], bins=bins, include_lowest=True)

# get result
# [(0.999, 1.5], (1.5, 2.0]]
# Categories (2, interval[float64, right]): [(0.999, 1.5] < (1.5, 2.0]]
```

I hope qcut will return me `[0.999, 1.5, 2.0]` by default.

I'm not sure if this is a problem or if Pandas was originally designed this way

**Comment by rhshadrach** [comment] 2024-02-05 21:04
> Perhaps there are also issues with cut, but I think the problem I am currently facing should be due to the incorrect bins returned by qcut

No disagreement there. Issue #51532 is also about qcut, as I quoted above.

**Comment by 0x30** [comment] 2024-02-06 02:13
👌
