### ISSUE TITLE
BUG: Can't pass start with UTC-offset to `date_range`, if timezone is also specified.

### ISSUE THREAD

**Issue by rwijtvliet** [pandas-dev/pandas#46738] opened 2022-04-11 10:51 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

i_error = pd.date_range('2020-10-25 02:00+0200', freq='H', periods=3, tz='Europe/Berlin') 
# AssertionError: Inferred time zone not equal to passed time zone
```

Note that specifying the UTC-offset is necessary here, as `2020-10-25 02:00` occurs twice in the `Europe/Berlin` timezone. Also, omitting the `tz` parameter is not possible, as in that case a `DatetimeIndex` with a fixed UTC-offset is returned.

### Issue Description

Passing a timestamp with UTC-offset to the `date_range` function raises an error, even though it is a valid timestamp in the specified timezone.

### Expected Behavior

The expected behaviour is to return the same `DatetimeIndex` as is done by the nested function below:

```python
# Working: first turning into timestamp...and then using that as start of date_range:
i_works = pd.date_range(pd.Timestamp('2020-10-25 02:00+0200', tz='Europe/Berlin'), freq='H', periods=3)
# DatetimeIndex(['2020-10-25 02:00:00+02:00', '2020-10-25 02:00:00+01:00', '2020-10-25 03:00:00+01:00'],
#               dtype='datetime64[ns, Europe/Berlin]', freq='H')
```

The same behaviour arises when the other valid 2AM timestamp at the last sunday of october is used (`'2020-10-25 02:00+0100'`)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.4.1
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : None
pytest           : 7.1.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.1.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.4.32
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by shyamsantoki** [comment] 2022-04-16 14:05
You can get the expected output by converting the tz
```py
 In: pd.date_range('2020-10-25 02:00+0200', freq='H', periods=3).tz_convert('Europe/Berlin')
Out: DatetimeIndex(['2020-10-25 02:00:00+02:00', '2020-10-25 02:00:00+01:00',
                    '2020-10-25 03:00:00+01:00'],
                   dtype='datetime64[ns, Europe/Berlin]', freq='H')
```

**Comment by rwijtvliet** [comment] 2022-04-17 06:18
Thanks for replying.

Yes, first creating a fixed-utc-offset index and then converting to Europe/Berlin is another workaround.

However, my users might pass a string with or without utc offset, and so it would be practical if `date_range` could handle both cases, as neither has ambiguity.

**Comment by simonjayhawkins** [comment] 2022-06-04 11:03
Thanks @rwijtvliet for the report.

This is moreless a duplicate of #17189 which was closed as not a bug, see https://github.com/pandas-dev/pandas/issues/17189#issuecomment-320629577

**Comment by simonjayhawkins** [comment] 2022-06-04 11:23
> Yes, first creating a fixed-utc-offset index and then converting to Europe/Berlin is another workaround.

"first turning into timestamp...and then using that as start of date_range" seems the more appropriate usage.

**Comment by mroeschke** [comment] 2022-07-05 23:06
Closing as the intended behavior as explained in https://github.com/pandas-dev/pandas/issues/17189#issuecomment-320629577=

**Closed by mroeschke** 2022-07-05 23:06 UTC
Labels: Usage Question, Timezones, Closing Candidate
