### ISSUE TITLE
Occuring error when trying to install with setup.py (from source code) and tar file from pypi is not working

### ISSUE THREAD

**Issue by nithinreddyy** [pandas-dev/pandas#36420] opened 2020-09-17 08:08 UTC
[16/40] Cythonizing pandas\_libs/reduction.pyx

Error compiling Cython file:
------------------------------------------------------------
...

        self.orig_data = self.buf.data
        self.orig_len = self.buf.shape[0]
        self.orig_stride = self.buf.strides[0]

        self.buf.data = self.values.data
               ^
------------------------------------------------------------

pandas\_libs\reduction.pyx:318:16: Assignment to a read-only property

Error compiling Cython file:
------------------------------------------------------------
...

    cdef move(self, int start, int end):
        """
        For slicing
        """
        self.buf.data = self.values.data + self.stride * start
               ^
------------------------------------------------------------

pandas\_libs\reduction.pyx:325:16: Assignment to a read-only property

Error compiling Cython file:
------------------------------------------------------------
...
        self.buf.shape[0] = end - start

    cdef reset(self):

        self.buf.shape[0] = self.orig_len
        self.buf.data = self.orig_data
               ^
------------------------------------------------------------

pandas\_libs\reduction.pyx:331:16: Assignment to a read-only property

Error compiling Cython file:
------------------------------------------------------------
...
        # move blocks
        for i in range(self.nblocks):
            arr = self.blocks[i]

            # axis=1 is the frame's axis=0
            arr.data = self.base_ptrs[i] + arr.strides[1] * start
              ^
------------------------------------------------------------

pandas\_libs\reduction.pyx:452:15: Assignment to a read-only property

Error compiling Cython file:
------------------------------------------------------------
...
        # reset blocks
        for i in range(self.nblocks):
            arr = self.blocks[i]

            # axis=1 is the frame's axis=0
            arr.data = self.base_ptrs[i]
              ^
------------------------------------------------------------

pandas\_libs\reduction.pyx:472:15: Assignment to a read-only property
Traceback (most recent call last):
  File "setup.py", line 791, in <module>
    setup_package()
  File "setup.py", line 761, in setup_package
    ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
  File "setup.py", line 540, in maybe_cythonize
    return cythonize(extensions, *args, **kwargs)
  File "D:\Pickle Examples\examples_aix\example_aix\lib\site-packages\Cython\Build\Dependencies.py", line 1110, in cythonize
    cythonize_one(*args)
  File "D:\Pickle Examples\examples_aix\example_aix\lib\site-packages\Cython\Build\Dependencies.py", line 1277, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pandas\_libs/reduction.pyx

**Comment by jreback** [comment] 2020-09-17 11:10
duplicate of #34213
we don't support cython 3 yet
you are welcome to help out

**Closed** 2020-09-17 11:10 UTC
Labels: Build, Dependencies, Duplicate
