### ISSUE TITLE
BUILD: Can't found module wrapt nor detect right meson version

### ISSUE THREAD

**Issue by latot** [pandas-dev/pandas#57038] opened 2024-01-23 15:22 UTC
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Linux-6.1.67-gentoo-x86_64-x86_64-AMD_Ryzen_7_5800H_with_Radeon_Graphics-with-glibc2.38

### Installation Method

pip install

### pandas Version

Git

### Python Version

3.11.7

### Installation Logs

Install Logs
<details>
Collecting git+https://github.com/pandas-dev/pandas
  Cloning https://github.com/pandas-dev/pandas to /tmp/pip-req-build-1a98i_co
  Running command git clone --filter=blob:none --quiet https://github.com/pandas-dev/pandas /tmp/pip-req-build-1a98i_co
  Resolved https://github.com/pandas-dev/pandas to commit 72814750548b5ead5b08cd9b90d56a23c9a520ea
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      pip_system_certs: ERROR: could not register module: No module named 'wrapt'
      
      meson-python: error: Could not find meson version 0.63.3 or newer, found pip_system_certs: ERROR: could not register module: No module named 'wrapt'
      meson-python: error: 1.2.1
      meson-python: error: .
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
</details>

Python Meson + wrapt (pip freeze in venv)
<details>
meson==1.3.1

wrapt==1.16.0
</details>

Meson + wrapt (on system)
<details>
dev-python/wrapt-1.16.0

dev-build/meson-1.3.0
</details>

**Comment by lithomas1** [comment] 2024-01-24 16:00
Are you installing from source, or trying to install from a wheel?

Can you also provide your install command?

**Comment by latot** [comment] 2024-01-24 16:30
Hi, here the commands:

```bash
pip install git+https://github.com/pandas-dev/pandas
```

The package ```wheel``` is installed on the python env.

**Comment by lithomas1** [comment] 2024-01-24 16:34
Are you able to install ``meson-python`` in your venv with pip?

e.g. does ``pip install meson-python`` work?

**Comment by lithomas1** [comment] 2024-01-25 23:06
That's strange.

If you install all the build dependencies for pandas manually beforehand(listed [here](https://github.com/pandas-dev/pandas/blob/d928a5cc222be5968b2f1f8a5f8d02977a8d6c2d/pyproject.toml#L5-L15)), are you able to install pandas with the ``--no-build-isolation`` flag passed to the pip install command?

Your error message seems very strange to me btw - I haven't seen this before. The message makes me want to suspect that there's a broken meson/meson-python installation somewhere.

also cc @eli-schwartz from meson

**Comment by eli-schwartz** [comment] 2024-01-26 00:29
I'm finding it difficult to interpret the output which pip caught from meson-python... it superficially looks like meson-python tried to check what minimum version of meson was available and instead of detecting

> great, you have meson version
> ```
> 1.3.1
> ```

It found

> Oh no, you have meson version
> ```
> pip_system_certs: ERROR: could not register module: No module named 'wrapt'
> ```

Which is, erm, dunno what to say about that. What is pip_system_certs in this context anyway?

**Comment by eli-schwartz** [comment] 2024-01-26 00:30
The name itself comes from https://pypi.org/project/pip-system-certs/ which is a monkey-patching software that uses wrapt, but why is it interjecting itself here...

**Comment by latot** [comment] 2024-01-26 12:47
Hi! without isolation:

```
pip install --no-build-isolation  git+https://github.com/pandas-dev/pandas
Collecting git+https://github.com/pandas-dev/pandas
  Cloning https://github.com/pandas-dev/pandas to /tmp/pip-req-build-k0onpkj_
  Running command git clone --filter=blob:none --quiet https://github.com/pandas-dev/pandas /tmp/pip-req-build-k0onpkj_
  Resolved https://github.com/pandas-dev/pandas to commit d928a5cc222be5968b2f1f8a5f8d02977a8d6c2d
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      + meson setup /tmp/pip-req-build-k0onpkj_ /tmp/pip-req-build-k0onpkj_/.mesonpy-08ey_y7x -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-req-build-k0onpkj_/.mesonpy-08ey_y7x/meson-python-native-file.ini
      The Meson build system
      Version: 1.3.1
      Source dir: /tmp/pip-req-build-k0onpkj_
      Build dir: /tmp/pip-req-build-k0onpkj_/.mesonpy-08ey_y7x
      Build type: native build
      
      ../meson.build:5:13: ERROR: Command `/home/pipe/pyenv/bin/python3.11 /tmp/pip-req-build-k0onpkj_/generate_version.py --print` failed with status 1.
      
      A full log can be found at /tmp/pip-req-build-k0onpkj_/.mesonpy-08ey_y7x/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

For some reason, the pip install path does not exists, so I run it with ```--log logs.txt``` to extract them, I'm appending the logs.
[logs.txt](https://github.com/pandas-dev/pandas/files/14064986/logs.txt)

**Comment by eli-schwartz** [comment] 2024-01-26 13:43
You can get the log file by using the pip option `-Cbuilddir=$PWD/build_dir/` if I recall correctly. By default pip deleted everything it is aware of on a failed build, this tells meson-python to configure meson with a persistent build directory.

**Comment by latot** [comment] 2024-01-26 13:47
mmm...

```
Build started at 2024-01-26T10:45:27.354015
Main binary: /home/pipe/pyenv/bin/python3.11
Build Options: -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dvsenv=True --native-file=/tmp/build_dir/meson-python-native-file.ini
Python system: Linux
The Meson build system
Version: 1.3.1
Source dir: /tmp/pip-req-build-9vzgvbf0
Build dir: /tmp/build_dir
Build type: native build
Running command: /home/pipe/pyenv/bin/python3.11 /tmp/pip-req-build-9vzgvbf0/generate_version.py --print
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "/tmp/pip-req-build-9vzgvbf0/generate_version.py", line 8, in <module>
    import versioneer
ModuleNotFoundError: No module named 'versioneer'



../pip-req-build-9vzgvbf0/meson.build:5:13: ERROR: Command `/home/pipe/pyenv/bin/python3.11 /tmp/pip-req-build-9vzgvbf0/generate_version.py --print` failed with status 1.
```

So.. meson forgot to add a dep?

**Comment by eli-schwartz** [comment] 2024-01-26 13:49
No, but if you disable build isolation you need to manually install dependencies.

**Comment by latot** [comment] 2024-01-26 14:28
No idea what to say....

Installing without isolation works, first need to install ```versioneer``` and ```cython``` from pip, then pandas is installed correctly.

Still, with isolation fails with the weird ```wrapt``` error....

**Comment by latot** [comment] 2024-01-26 14:32
here the logs with debug mode

[debug.txt](https://github.com/pandas-dev/pandas/files/14066011/debug.txt)

**Comment by lithomas1** [comment] 2024-01-26 17:43
Ok, marking this one as a closing candidate then since you seem to be able to install pandas from source (even if it forces the use of no-build-isolation).

You might want to take a look at what's going on with pip-system-certs on your system.

**Comment by latot** [comment] 2024-01-26 19:24
I was able to do a reprex, is little big, I'll reduce it and then show it here, I was able to confirm is a version on some packages issue.

**Comment by latot** [comment] 2024-01-26 19:59
Oks, finally steps to reproduce it:

```bash
python3 -m venv venv
source venv/bin/activate
pip install pip-system-certs==4.0
pip install pip install git+https://github.com/pandas-dev/pandas
```

**Comment by mroeschke** [comment] 2024-05-19 18:35
Since this doesn't seem to be an issue with pandas itself going to close

**Closed by mroeschke** 2024-05-19 18:35 UTC
Labels: Build, Needs Info, Closing Candidate

**Comment by latot** [comment] 2024-05-20 13:14
@mroeschke D: why!?

**Comment by eli-schwartz** [comment] 2024-05-20 14:18
I would assume you should submit the same bug report you submitted here, except to the pip-system-certs project.

It does no use keeping the pandas bug open since it's nothing to do with pandas and by default no pandas users ever see this issue. What's the objective to consider it good to keep open?

**Comment by latot** [comment] 2024-05-20 14:26
Well, bugs are not always the best to be reproducible, some of them are pretty hard to found, so is not like there will be always more than one ppl reporting something, and is good to someone found this things. so I think, even for a weird, is good to keep track of it, and know when is ready, also if someone else found it, is good to know it exists, and is being fixed or at least reported.

**Comment by eli-schwartz** [comment] 2024-05-20 14:42
Just to clarify:

It's not being fixed.

No one has reported it to the actual project that is broken (pip-system-certs).

Pandas works fine for me, and for everyone else that tried to install pandas. So we have nothing to report. I suggest that if you *can* reproduce this issue, you should report it (to the correct project) so that it can be fixed.

**Comment by eli-schwartz** [comment] 2024-05-20 14:44
Also note that if someone else does encounter the same issue, they can find the bug in the list of closed bugs too. It doesn't need to be kept open.

Open bugs aren't "the list of bugs that users can find", open bugs are "the list of pending TODO items for the project developers to handle, fix, implement, or otherwise respond to".
