### ISSUE TITLE
BUG: Disable Numpy memory allocation while concat

### ISSUE THREAD

**Issue by sandeyshc** [pandas-dev/pandas#59957] opened 2024-10-04 06:30 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.concat(df_list,axis=1)
```

### Issue Description

We have sparse data with many null values, and while reading it using Pandas with PyArrow, it doesn't consume much memory because of pandas internal compression logic. However, during concatenation, NumPy allocates memory that isn't actually used, causing our Python script to fail due to memory allocation issues. Can you provide an option to disable NumPy memory allocation when concatenating DataFrames along axis=1?

### Expected Behavior

Numpy should not allocate memory when it is not used

### Installed Versions

<details>

pandas                : 2.2.2
numpy                 : 2.1.0

</details>

**Comment by mroeschke** [comment] 2024-10-04 17:58
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/59956

**Closed by mroeschke** 2024-10-04 17:58 UTC
Labels: Bug, Needs Triage
