### ISSUE TITLE
BUG/CLN?:  get_duplicates in _build_names_mapper 

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas#52229] opened 2023-03-26 23:47 UTC
This function looks like it doesn't do what it is intended to do:
https://github.com/pandas-dev/pandas/blob/5c4cc4a51c71a2620dedcf033ca9e36fa185974e/pandas/core/reshape/pivot.py#L864

Based on the implementation it can be replaced by just `set(names)` but that doesn't match with the intention of the name.

**Comment by samjeffrees** [comment] 2023-03-28 11:13
Hi @twoertwein,

I've just had a look and based on the docstring in `_build_names_mapper()` and it looks like this isn't working as intended. This can be fixed by changing `get_duplicates` to something like the following:

```
def get_duplicates(names):
    seen: set = set()
    duplicate: set = set()
    for name in names:
        if name not in seen:
            seen.add(name)
        else:
            duplicate.add(name)
    return duplicate
```

Is it okay if I pick this up?

I'm new here so pls forgive the ignorance :-)

**Comment by twoertwein** [comment] 2023-03-28 12:43
> This can be fixed by changing get_duplicates to something like the following

Sorry, I can't help you with that - I'm not familair with that code, just stumbled into it accidentaly.

**Comment by topper-123** [comment] 2023-03-28 13:39
This does look weird. @samjeffrees, could you try your solution and and see if it breaks some tests?

**Comment by tqa236** [comment] 2024-03-09 07:00
take

**Closed** 2024-03-09 19:51 UTC
Labels: Bug, Reshaping
