### ISSUE TITLE
ENH:  pd.to_numeric() should handle stripping commas and % symbols as an additional option for error handling

### ISSUE THREAD

**Issue by s-github-2** [pandas-dev/pandas#55329] opened 2023-09-29 21:05 UTC
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

commas and % symbols are pretty common in tabular data but pdl.to_numeric() doesnt handle number strings liike 1,234 or 10%.
I wish there were addtional options for errors such as 'coerce_after_cleaning' so a single line of code can handle commonly used cleaning such as removing special characters from number strings.
#pd convert to numberic
pd.to_numeric('1,234' ,errors='coerce_after_cleaning') will result in 1234

### Feature Description

```
coerce_numeric = errors not in ("ignore", "raise")  # existing line in numeric.py file of pandas source code
# new code after  the above existing line to pre-process when appropriate value for errors is passed
        if errors == "coerce_after_cleaning":
            coerce_numeric = True
            errors = "coerce"
             # Step 1: Pre-processing loop to handle '12,345.1' and '1.234%'
           
            for i in range(values.size):
                val = values[i]
                if isinstance(val, str):
                    # Remove commas and % signs

                    val = val.replace(',', '').replace('%','')
                    # maybe convert percentages to fractions - if so uncomment the next lines
                    # and drop the 2nd replace in the line above
                    #if '%' in val:
                    #    val = str(float(val.replace('%', '')) / 100)
                    values[i] = val
                    # end of cleaning
```

### Alternative Solutions

None that I am aware of but of course the  above is possible with additional coding and the point is to make it seamless without addtional lines of code

**Comment by mroeschke** [comment] 2023-09-29 21:16
Comma as a decimal parameter seems to have been proposed in https://github.com/pandas-dev/pandas/issues/4674

% and other characters as a `coerce_after_cleaning` step is a very subjective operation though. pandas also provides APIs through the `str` accessor to pre-process data as needed before calling `to_numeric`.

Thank for the suggestion but closing as a duplicate of the linked issue

**Closed by mroeschke** 2023-09-29 21:16 UTC
Labels: Enhancement, Needs Triage
