### ISSUE TITLE
Pandas replacing values on specific columns. view vs. copy

### ISSUE THREAD

**Issue by mcocdawc** [pandas-dev/pandas#11984] opened 2016-01-07 11:18 UTC
Hello,

I asked a question on StackExchange which is explaining my bug/feature:
http://stackoverflow.com/questions/34653215/pandas-replacing-values-on-specific-columns

pd.show_versions() gives:
## INSTALLED VERSIONS

commit: None
python: 3.5.0.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-57-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.0
nose: 1.3.7
pip: 7.1.2
setuptools: 18.4
Cython: 0.23.4
numpy: 1.10.1
scipy: 0.16.0
statsmodels: 0.6.1
IPython: 4.0.0
sphinx: 1.3.1
patsy: 0.4.0
dateutil: 2.4.2
pytz: 2015.7
blosc: None
bottleneck: None
tables: 3.2.2
numexpr: 2.4.4
matplotlib: 1.4.3
openpyxl: 2.2.6
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.7.7
lxml: 3.4.4
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: None

**Comment by jreback** [comment] 2016-01-07 11:20
please show a fully reproducible example

**Comment by mcocdawc** [comment] 2016-01-07 11:35
This is a minimal example of the problem I have.

>In [1]: import pandas as pd
>
>In [2]: df=pd.DataFrame([[1, 2, 8],[3, 4, 8], [5, 1, 8]], columns=['A', 'B', 'C'])
>
>In [3]: df
>Out[3]: 
>   A  B  C
>0  1  2  8
>1  3  4  8
>2  5  1  8
>
>In [4]: df.loc[:, ['A', 'B']].replace([1, 3, 2], [3, 6, 7], inplace=True)
>
>In [5]: df
>Out[5]: 
>   A  B  C
>0  1  2  8
>1  3  4  8
>2  5  1  8
>
>In [6]: df.loc[:, 'A'].replace([1, 3, 2], [3, 6, 7], inplace=True)
>
>In [7]: df
>Out[7]: 
>   A  B  C
>0  3  2  8
>1  6  4  8
>2  5  1  8

If I slice only one column `In [6]` it works different to slicing several columns `In [4]`. As I understand the .loc method it returns a view and not a copy. In my logic this means that making an inplace change on the slice should change the whole DataFrame. This is what happens at line `In [6]`.

**Comment by jreback** [comment] 2016-01-07 13:01
This should ideally show a ``SettingWithCopyWarning``, but I think this is quite difficult to detect.

You should NEVER do this type of chained inplace setting. It is simply bad practice.

idiomatic is:

```
In [7]: df[['A','B']] = df[['A','B']].replace([1, 3, 2], [3, 6, 7])

In [8]: df
Out[8]: 
   A  B  C
0  3  7  8
1  6  4  8
2  5  3  8
```

(you can do with ``df.loc[:,['A','B']]`` as well, but more clear as above.

I'll mark it, but will require some deep digging for a marginal case.

**Comment by jreback** [comment] 2016-01-07 13:02
see docs on chained indexing [here](http://pandas.pydata.org/pandas-docs/stable/indexing.html#why-does-the-assignment-when-using-chained-indexing-fail)

**Comment by mcocdawc** [comment] 2016-01-09 18:02
Thank you very much for your answer.

**Comment by BLMeltdown** [comment] 2017-06-28 07:40
Hello
I had this problem and searched the issues; I found these explanations but find myself dumbfounded in the end. I have read the docs here (http://pandas.pydata.org/pandas-docs/stable/indexing.html#why-does-the-assignment-when-using-chained-indexing-fail) and here (http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy), and left with the feeling that I don't know what is recommended. Usually, loc and iloc are preferred methods, but they are incompatible with in place operations. On the other hand, regular indexing with [] is even triggering warnings all over the place.

In the end, we have;
df_copy.iloc[:,columns].fillna(0, inplace=True)
>Not working

and 
df_copy.iloc[:,columns]=df_copy.iloc[:,columns].fillna(0, inplace=True )
> Not working,

but 
df_copy.iloc[:,columns]=df_copy.iloc[:,columns].fillna(0)
working.

And I am not really sure that it would in every use case, since even in the docs we have sentences like
" Of course, dfmi.loc.__getitem__(idx) may be a view or a copy of dfmi."

My thoughts is that attribute functions should have constant behavior, so inplace should work even on loc/iloc frames, since they have the same purpose of working over a view instead of a copy.
This has already debatted, I guess, but I wanted to precise the fact that fillna also doesn't work, and the problem is present for iloc as well.

**Comment by jreback** [comment] 2017-06-28 09:36
The docs / examples above are clear on this.

 Setting ``inplace`` is:

- much harder to read
- not any more performant

If you use it you are subject to the warnings above. Setting inplace returns ``None`` so you cannot generally use it as a rhs of an expression. If you think the docs need updating pls submit a PR for that.

**Comment by jreback** [comment] 2017-06-28 09:36
closing this as already answered is great detail in the documentation.

**Closed by jreback** 2017-06-28 09:36 UTC
Labels: Bug, Difficulty Advanced, Effort Low, Indexing

**Comment by RAHAAMA** [comment] 2018-02-19 01:51
I Try to change some values in a column of dataframe but I dont want the other values change in the column 
df1.loc[df1.contStackIndex==c,'contDepth'].shift().fillna(0)

0    0.0
1    0.0
2    1.0
Name: contDepth, dtype: float64
but I want to have : 
	contid	coordLotX	coordLotY	contDepth	lotid	contStackHeigth	contStackIndex	platfCoordX	platfCoordY	slotDepth	platfSequIndex	coordplatid	dist
**0	17	95	100	0	0	3	0	245	0	1	4	4	0
1	16	95	100	0	0	3	0	245	0	0	4	4	0
2	19	95	100	1	0	3	0	35	0	1	0	0	0**
17	9	95	160	0	0	3	6	565	0	1	9	9	0
18	8	95	160	1	0	3	6	565	0	0	9	9	0
19	0	95	160	2	0	3	6	305	0	0	5	5	0

**Comment by srijagummula** [comment] 2019-10-01 08:25
I am trying to change the particular element in the column using if condition 
for row in df2["Geners2"]:
    if row == "Animation":
        Animations.append("1")
    **else :
        Animations.append("0")**

but I am unable to retain the previous value could you please help me
