### ISSUE TITLE
BUG: indexing with string in multi-index for Period gives KeyError

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#9892] opened 2015-04-14 12:41 UTC
From [SO](http://stackoverflow.com/questions/29627143/setting-value-in-pandas-mulitindex-fails/29627444#29627444): 

```
import pandas as pd
import itertools
a = pd.period_range('2013Q1','2013Q4', freq='Q')
i = (1111, 2222, 3333)
idx = pd.MultiIndex.from_tuples(list(itertools.product(a, i)),
                            names=('Periode', 'CVR'))
df = pd.DataFrame(index=idx,
              columns=('OMS', 'OMK','RES','DRIFT_IND','OEVRIG_IND','FIN_IND','VARE_UD','LOEN_UD','FIN_UD'))
```

Trying to select with a string gives a ValueError:

```
In [15]: df.loc[('2013Q1',1111),'OMS']
---------------------------------------------------------------------------
KeyError: ('2013Q1', 1111)
```

while it works with an explicit Period:

```
In [16]: df.loc[(pd.Period('2013Q1'),1111),'OMS']
Out[16]: nan
```

and it also works when not using multi-index notation (only accessing the first level): `df.loc['2013Q1', 'OMS']`

and this **did work in 0.14.1**.

**Comment by jorisvandenbossche** [comment] 2015-04-14 12:48
Further, the string syntax also does not work for assigning (but this was also the case in 0.14.2). While for a DatetimeIndex both accessing and assigning using a string indexer works.

**Comment by jreback** [comment] 2015-04-14 14:48
this is essentially a dupe of #3462 as the multi-index delegation is to the PeriodIndex which doesn't support this ATM.

**Comment by jorisvandenbossche** [comment] 2015-04-14 14:53
@jreback Possibly, but this *did* work in 0.14.1, while the issue you linked to was already broken (or not implemented) then.

**Comment by jorisvandenbossche** [comment] 2015-04-14 14:53
But of course possible the underlying issue is the same

**Comment by jreback** [comment] 2015-04-14 14:56
hmm, ok, Period does need a bit of attention

**Comment by mroeschke** [comment] 2016-12-18 06:21
This works again in 0.19.1:

```
In [31]: df.loc[('2013Q1',1111),'OMS']
Out[31]: 
Periode  CVR 
2013Q1   1111    NaN
Name: OMS, dtype: object
```

However the result isn't the same as:
```
In [32]: df.loc[(pd.Period('2013Q1'),1111),'OMS']
Out[32]: nan
```

Should these return the same result?

**Closed** 2020-01-03 23:23 UTC
Labels: Needs Tests, good first issue

**Comment by jbrockmendel** [comment] 2021-06-29 16:30
@mroeschke was there discussion somewhere else about the expected result here?  i think the scalar np.nan makes more sense than a DataFrame
