### ISSUE TITLE
Wrong output of GroupBy transform with string input (e.g., transform('rank'))

### ISSUE THREAD

**Issue by marioga** [pandas-dev/pandas#22509] opened 2018-08-26 01:23 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame([[1, 10], [1, 20], [2, 40], [2, 30]], columns=['a', 'b'])

print("%s\n" % df)

print("Output of df.groupby('a')['b'].transform('rank'):\n%s\n" %
        df.groupby('a')['b'].transform('rank'))

print("Output of df.groupby('a')['b'].rank():\n%s\n" %
        df.groupby('a')['b'].rank())

print("Output of df.groupby('a')['b'].transform(lambda x: x.rank()):\n%s\n" %
        df.groupby('a')['b'].transform(lambda x: x.rank()))

print("Output of df.groupby('a')['b'].transform('cumcount'):\n%s\n" %
        df.groupby('a')['b'].transform('cumcount'))

print("Output of df.groupby('a')['b'].cumcount():\n%s\n" %
        df.groupby('a')['b'].cumcount())

```
#### Problem description

For simplicity, I will explain the issue for `SeriesGroupBy`, though the bug is present in `DataFrameGroupBy` as well. 

When calling `transform` on a `SeriesGroupBy` object with a string input `'string_input'` (e.g., `.transform('mean')`), the relevant code inside [`pandas/pandas/core/groupby/generic.py`](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/generic.py) will end up calling `SeriesGroupBy._transform_fast` on the function 
```
func = getattr(SeriesGroupBy, 'string_input')
```
(unless `'string_input'` is inside `base.cython_transforms`, currently consisting of `['cumprod', 'cumsum', 'shift', 'cummin', 'cummax']`). Inside `_transform_fast`, the result of applying `func` to the `SeriesGroupBy` object is then broadcast to the entire index of the original object. This works as expected if `func` returns a single value per group in the `GroupBy` object (e.g., for functions like `'mean'`, `'std'`, etc.). However, for functions like `rank`, `cumcount`, etc., that return several values per group, the result of broadcasting is nonsensical to my best knowledge.

Note: Index broadcasting works correctly if `transform` is called with a (non-cython) function, for example `lambda x: x.rank()`. In that case, `_fast_transform` is never called and the result is a simple concatenation of the results for each group.

#### Expected Output

The results of `df.groupby('a')['b'].transform('rank')` and `df.groupby('a')['b'].rank()` should be identical. Same for 'cumcount' and maybe other `GroupBy` functions.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.18.3-arch1-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 10.0.1
setuptools: 40.0.0
Cython: None
numpy: 1.15.0
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.5.0
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.7
feather: None
matplotlib: 2.2.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by gfyoung** [comment] 2018-08-27 09:50
@marioga : Thanks for reporting this!  For reference, do you mind posting what output you got?

cc @jreback

**Comment by marioga** [comment] 2018-08-27 19:32
Here is the output I get after running the code I submitted:
```
   a   b
0  1  10
1  1  20
2  2  40
3  2  30

Output of df.groupby('a')['b'].transform('rank'):
0    1.0
1    1.0
2    2.0
3    2.0
Name: b, dtype: float64

Output of df.groupby('a')['b'].rank():
0    1.0
1    2.0
2    2.0
3    1.0
Name: b, dtype: float64

Output of df.groupby('a')['b'].transform(lambda x: x.rank()):
0    1
1    2
2    2
3    1
Name: b, dtype: int64

Output of df.groupby('a')['b'].transform('cumcount'):
0    0
1    0
2    1
3    1
Name: b, dtype: int64

Output of df.groupby('a')['b'].cumcount():
0    0
1    1
2    0
3    1
dtype: int64
```

**Comment by pilkibun** [comment] 2019-06-11 19:11
To illustrate:
```python
In [34]: df=pd.DataFrame(dict(price=[10,10,20,20,30,30],cost=(100,200,300,400,500,600)))
    ...: df
Out[34]: 
   price  cost
0     10   100
1     10   200
2     20   300
3     20   400
4     30   500
5     30   600

# correct
In [36]: df.groupby('price').cost.rank()
Out[36]: 
0    1.0
1    2.0
2    1.0
3    2.0
4    1.0
5    2.0
Name: cost, dtype: float64

# wrong
In [35]: df.groupby('price').cost.transform('rank')
Out[35]: 
0    1.0
1    1.0
2    2.0
3    2.0
4    1.0
5    1.0
Name: cost, dtype: float64

# the above generated via
In [47]: ids, _, _ = df.groupby('price').grouper.group_info
    ...: ids
Out[47]: array([0, 0, 1, 1, 2, 2])
In [48]: df.groupby('price').rank().loc[ids]
Out[48]: 
   cost
0   1.0
0   1.0
1   2.0
1   2.0
2   1.0
2   1.0

```

**Comment by pilkibun** [comment] 2019-06-14 00:38
same issue with 'ffill' and 'bfill', xref #14274

**Comment by pilkibun** [comment] 2019-06-14 01:34
@jorisvandenbossche , do you know if there is any case where `grouby.transform('foo', ...)` != `grouby.foo(...)` and it's not a bug? I don't understand why there's a separate code path
instead of it being an alias for the same call, so that half of the things return the wrong answer.

**Comment by jreback** [comment] 2019-06-14 01:44
transforming on a non aggregating function doesn’t make any sense as how would u broadcast the results?

**Comment by pilkibun** [comment] 2019-06-14 01:49
if its non-agg AND shape-preserving, as many are, you don't need to broadcast.

**Comment by pilkibun** [comment] 2019-06-14 01:52
but if you're suddenly a purist, see #26743

**Comment by jreback** [comment] 2019-06-14 02:04
@pilkibun you are missing the point

transform works by using groupby with an aggregator then broadcasting
that how I wrote it a while back

not sure why you have 2 issues here - just needs to raise on on aggregated outputs

**Comment by pilkibun** [comment] 2019-06-14 03:46
> @pilkibun you are missing the point

I'm sure one of us is.

**Comment by mzeitlin11** [comment] 2021-03-29 21:00
This is fixed on master but could use tests

**Comment by mroeschke** [comment] 2021-05-28 03:44
This seems to be the same issue as https://github.com/pandas-dev/pandas/issues/19354, closing

**Closed by mroeschke** 2021-05-28 03:44 UTC
Labels: Groupby, Needs Tests, good first issue
