### ISSUE TITLE
BUG: index name is lost when doing groupby where by is a dict and at least one value in the by dict is a list of of size zero

### ISSUE THREAD

**Issue by jasonaue** [pandas-dev/pandas#33545] opened 2020-04-14 16:22 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

To reproduce:

```
example = pd.DataFrame({'foo':[1,2,3],'bar1':[1,2,3],'bar2':[1,2,3]})

#index name is foo
display(example.groupby('foo').agg({'bar1': ['min'], 'bar2':['max']}))

#index name is None
display(example.groupby('foo').agg({'bar1': ['min'], 'bar2':[]}))
```

#### Output of ``pd.show_versions()``
```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-7642-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : 0.29.13
pytest           : 5.2.1
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.1
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.9
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.1
```

**Comment by phofl** [comment] 2020-04-19 21:23
Will be fixed with #33086 if merged.

--> Is a duplicate of #32580

**Closed** 2020-06-14 18:04 UTC
Labels: Bug, Groupby
