### ISSUE TITLE
Can't .loc[label] on a CategoricalIndex with labels being integer

### ISSUE THREAD

**Issue by aavanian** [pandas-dev/pandas#17569] opened 2017-09-18 10:58 UTC
I came around this and this seemed related to #9595 but could also be a bug in the above interacting with the CategoricalIndex. Using the same example as #15470 with pandas 0.20.3:

#### Code Sample
```python
    s = pd.Series([2, 1, 0], index=pd.CategoricalIndex([2, 1, 0]))
    s[2]  # works (interpreting as label)
    s.loc[2]  # fails with TypeError: cannot do label indexing on <class 'pandas.core.indexes.category.CategoricalIndex'> with these indexers [2] of <class 'int'>

    # of course the below works!
    s = pd.Series([2, 1, 0], index=[2, 1, 0])
    s[2]  # works (interpreting as label)
    s.loc[2]  # works (interpreting as label)
```

#### Problem description

`s.loc[2]` shouldn't fail and should select the label '2'.
Note this happens also with a pd.DataFrame.

**Comment by jreback** [comment] 2017-09-18 11:02
duplicate of #15470

**Comment by jreback** [comment] 2017-09-18 11:03
why don't you just show this example there (IOW your top section). its the same issue.

**Comment by jorisvandenbossche** [comment] 2017-09-18 11:04
Actually, this is about the TypeError that `loc` raises, not about `__getitem__`

**Comment by jreback** [comment] 2017-09-18 11:04
and its the exact same issue

**Comment by jorisvandenbossche** [comment] 2017-09-18 11:08
It's clearly not the same user facing issue, so I suppose you mean "it probably has the same underlying  reason/bug for this failure" ? If so, can you give a bit more explanation?

The other issue is not necessarily a bug (although if we decide not to be a bug, very confusing behaviour), it is a API design question where we have to ask whether a categorical index with numerical indices is actually a numerical index or not

**Closed** 2019-12-11 13:18 UTC
Labels: Categorical, Indexing
