### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by shawnxu1111** [pandas-dev/pandas#25393] opened 2019-02-21 04:39 UTC
#### Code Sample, a copy-pastable example if possible

```python
class PatternManager:
     __community_alias_df = pd.read_csv(const.COMMUNITY_ALIAS, encoding='utf-8').fillna(value = "") 
     __community_alias_not_changed = False

     def __del__(self):
        PatternManager.writeDF()
        pass
    
    @classmethod
    def writeDF(cls):
        if cls.__community_alias_not_changed is False:
            cls.__community_alias_df.to_csv(const.COMMUNITY_ALIAS, index=False)
            cls.__community_alias_not_changed = True
            print('writng this DF successfully')
            return True
        return False

if __name__ == "__main__":
    pm = PatternManager()
```
#### Problem description

  File "C:\Users\XXX\.virtualenvs\XXX\lib\site-packages\pandas\core\generic.py", line 3007, in to_csv
ImportError: sys.meta_path is None, Python is likely shutting down

#### Expected Output

writing this DF successfully

#### Output of ``pd.show_versions()``

<details>

I have try to comment 'cls.__community_alias_df.to_csv(const.COMMUNITY_ALIAS, index=False)'. If it's commented, the program works well, so the problem must be using pandas in __del__. SO!! Can pandas be used in __del__. If not, do I have a simillar solution for this. Or is that a bug of pandas?

</details>

**Comment by WillAyd** [comment] 2019-02-21 17:07
How do you know what the garbage collector is doing here? Isn't this going to be an implementation detail of CPython? Not sure this is really an issue with pandas as much as the way you have constructed your class

**Comment by nmusolino** [comment] 2019-02-22 03:07
Here's a simpler reproduction:
```python
import pandas

class C():
    def __init__(self):
        self.df = pandas.DataFrame()

    def __del__(self):
        self.df.to_csv('test.csv')

if __name__ == '__main__':
    c = C()
```

The traceback doesn't show the import statement, but presumably this was causing the exception:
https://github.com/pandas-dev/pandas/blob/9c0f6a8d703b6bee48918f2c5d16418a7ff736e3/pandas/core/generic.py#L3005-L3006

This is not really a pandas bug.  A similar case is discussed on the Python tracker in [Python issue 26637](https://bugs.python.org/issue26637).  To be clear, in that case, the goal was to improve the exception that Python raises; the behavior was not considered a bug.

In this case, pandas is simply trying to import something in a function.  The cause is that the `DataFrame.to_csv()` method is called at Python interpreter shutdown, when Python is not able to perform the import.

A better approach is to change your class/program to not do this work in `__del__`.  As a temporary hack, you could try deleting all the references to your `PatternManager` object (i.e. add `del pm` in your script) and hope that the object will get GCed before interpreter shutdown.

**Comment by WillAyd** [comment] 2019-02-22 15:37
Thanks for the research @nmusolino ! Closing as not a pandas bug

**Closed by WillAyd** 2019-02-22 15:37 UTC
