### ISSUE TITLE
BUG: unstack() sorts automatically, default is preferably unsorted?

### ISSUE THREAD

**Issue by MatthiVH** [pandas-dev/pandas#34112] opened 2020-05-11 00:07 UTC
The unstack() function is automatically sorting my labels in my boxplot-code. Isn't it nice to have a sort = False option (probably the default?)

My labels are perfectly ordered, it's just after unstacking they get messed-up.

my post on stack-overflow: https://stackoverflow.com/questions/61720090/issues-with-boxplot-figure-x-label-are-alphabetically-and-extra-nan-label-is-cr

another example: https://stackoverflow.com/questions/32163063/pandas-plotting-incorrectly-sorts-the-binned-values-on-the-graph

**Comment by MarcoGorelli** [comment] 2020-05-11 12:59
Thanks @MatthiVH for the report

So, this is a feature request for `sort` in `unstack`? If so, seems it's a duplicate of #15105, so I'll close it (but feel free to reopen if you disagree that it's a duplicate)

**Closed by MarcoGorelli** 2020-05-11 12:59 UTC
Labels: Bug, Needs Triage

**Comment by MatthiVH** [comment] 2020-05-11 13:15
Oh yeah sure, didn't see that this suggestion was already there for a long time. 
Now I see, yes then it's a duplicate!
