### ISSUE TITLE
BUG: modulo of pd.Int64Index returns negative values under some conditions

### ISSUE THREAD

**Issue by felixpatzelt** [pandas-dev/pandas#36526] opened 2020-09-21 16:38 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
(pd.Int64Index(list(range(0,24))*500) - 5) % 24

# returns Int64Index([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,
#            ...
#             9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
#           dtype='int64', length=12000)

# note: (pd.Int64Index(list(range(0,24))*400) - 5) % 24 does not return negative values
```

#### Problem description

In Pandas 1.1.2, taking the modulo of an Int64Index can return negative values depending on the values in the index and on its length. This problem was not present in pandas 1.0.5. It is also inconsistent with the generally expected behaviour of modulo in python and numpy.

#### Expected Output

```
Int64Index([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,
            ...
             9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
           dtype='int64', length=9600)
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2a7d3326dee660824a8433ffd01065f8ac37f7d6
python           : 3.7.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.1.2
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : 6.0.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 0.10.1
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.8.2
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.5.2
sqlalchemy       : 1.3.19
tables           : 3.6.1
tabulate         : None
xarray           : 0.16.1
xlrd             : None
xlwt             : None
numba            : 0.51.2

</details>

**Comment by jorisvandenbossche** [comment] 2020-09-21 17:40
@felixpatzelt Thanks a lot for the report, that's indeed a regression and wrong result ..

It's not specific to Index, also a Series (or DataFrame) operation has the same issue:

```
In [43]: (pd.Series(list(range(0,24))*500) - 5) % 24
Out[43]: 
0        -5
1        -4
2        -3
3        -2
4        -1
         ..
11995    14
11996    15
11997    16
11998    17
11999    18
Length: 12000, dtype: int64
```

**Comment by dishak331** [comment] 2020-09-21 19:41
I would like to work on this

**Comment by dishak331** [comment] 2020-09-21 19:42
take

**Comment by jorisvandenbossche** [comment] 2020-09-21 19:52
@dishak331 Thanks!

See also https://github.com/pandas-dev/pandas/issues/35685 in case you might first want to find out which change caused the regression (sometimes that can be helpful)

**Comment by asishm** [comment] 2020-09-21 19:55
is this related? #36047
don't have access to an environment right now

**Comment by dishak331** [comment] 2020-09-21 20:05
@jorisvandenbossche thanks!

**Comment by jbrockmendel** [comment] 2020-09-21 22:57
xref https://github.com/pydata/numexpr/issues/365

**Comment by dishak331** [comment] 2020-09-22 05:03
okay so i just checked, this is a bug in Python itself. When we are doing -5%24 it is outputting as 19 instead of -5

**Comment by m1nde** [comment] 2020-09-22 09:26
@dishak331 No, it's not a bug in Python. Thats the defined behaviour of the module operation in Python 3. It's numexpr that is wrong here by applying C conventions into Python.

**Comment by dishak331** [comment] 2020-09-22 09:59
oh okay okay @m1nde

**Comment by simonjayhawkins** [comment] 2020-09-22 18:30
> possibly duplicate of #36047

looks like the same PR responsible, https://github.com/pandas-dev/pandas/issues/36047#issuecomment-685212708

first bad commit: [01623f8f733fff3bec26a06a82e2c216f03fb226] CLN: Refactor pandas/tests/base - part3 (#30147)

https://github.com/simonjayhawkins/pandas/runs/1150901284?check_suite_focus=true

**Comment by simonjayhawkins** [comment] 2020-09-22 19:20
I think can close this as duplicate of #36047

**Closed by simonjayhawkins** 2020-09-22 19:20 UTC
Labels: Numeric, Regression
