### ISSUE TITLE
Creating DataFrame from dict with columns orientation does not preserve order of index

### ISSUE THREAD

**Issue by bchu** [pandas-dev/pandas#26072] opened 2019-04-13 02:00 UTC
```
import pandas as pd
d = {'column': {'one': 1, 'two': 2, 'three': 3}}
pd.DataFrame(d) # Or pd.DataFrame.from_dict(d, orient='columns')
```

results in:

```
       column
one         1
three       3
two         2
```

instead of what we expect:

```
       column
one         1
two         2
three       3
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.4.0
pip: 19.0.3
setuptools: 39.0.1
Cython: 0.28.3
numpy: 1.15.4
scipy: 1.2.1
pyarrow: 0.13.0
xarray: 0.10.0
IPython: 7.4.0
sphinx: None
patsy: 0.4.1
dateutil: 2.7.2
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.9
feather: None
matplotlib: 2.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.2.0
bs4: None
html5lib: 0.9999999
sqlalchemy: 1.1.10
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: 0.3.0
pandas_gbq: None
pandas_datareader: None
gcsfs: 0.2.1

</details>

**Comment by jreback** [comment] 2019-04-13 02:04
dict ordering is not guaranteed before 3.6; so this is as expected; you didn’t show which version you are using

**Comment by bchu** [comment] 2019-04-13 02:05
Sorry, just added.

**Comment by jreback** [comment] 2019-04-13 02:17
this a duplicate of #24859 with a slight variation. you are welcome to have a look.

**Closed by jreback** 2019-04-13 02:17 UTC
