### ISSUE TITLE
Overflow warning when using HDFStore to save large dataframe as table format.

### ISSUE THREAD

**Issue by kid3night** [pandas-dev/pandas#22391] opened 2018-08-17 01:06 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
self.feature_concated.to_hdf(self.h5_result_name, key='feature_data', mode='a', format='table')
self.feature_concated.to_hdf(self.h5_result_name, key='feature_data', mode='a')
```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]
I need to save a large DataFrame to Hdf5 file so I use the code above to save the DataFrame. And a RuntimeWarning will show up:

F:\Anaconda3\lib\site-packages\tables\leaf.py:357: RuntimeWarning: overflow encountered in long_scalars
expected_mb = (expectedrows * rowsize) // MB

But when I don't use table format hdf to save it, it will not have such problem and everything goes well.
I'm wondering what the cause of this problem is and how could I solve it?

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
F:\Anaconda3\lib\site-packages\tables\leaf.py:357: RuntimeWarning: overflow encountered in long_scalars
expected_mb = (expectedrows * rowsize) // MB
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 2012ServerR2
machine: AMD64
processor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.3
pytest: 3.6.3
pip: 18.0
setuptools: 39.2.0
Cython: 0.28.3
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.5
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: 4.2.2
bs4: 4.6.0
html5lib: 0.9999999
sqlalchemy: 1.2.8
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by WillAyd** [comment] 2018-08-17 02:40
duplicate of #22392

**Closed by WillAyd** 2018-08-17 02:40 UTC
Labels: Duplicate
