### ISSUE TITLE
BUG: GroupBy sum on an Int64 column with min_count=1 is wrong when all values are null

### ISSUE THREAD

**Issue by ali-tny** [pandas-dev/pandas#34172] opened 2020-05-14 07:17 UTC
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---
```python
import pandas as pd

df = pd.DataFrame(
    [
        {"key": 1, "value": None},
    ],
    dtype="Int64",
)

>>> df["value"].sum(min_count=1)
<NA>
>>> df.groupby("key")["value"].sum(min_count=1)
key
1    -9223372036854775808
Name: value, dtype: Int64
```

#### Problem description

When summing with min_count=1 (so that groups with all nulls sum to null), DataFrame.sum exhibits expected behaviour (ie, all nulls sum to null), but GroupBy.sum returns the minimum Int64 -9223372036854775808 rather than `<NA>`. 

#### Expected Output
```python
>>> df.groupby("key")["value"].sum(min_count=1)
key
1    <NA>
Name: value, dtype: Int64
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.3
numpy            : 1.18.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.14.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jreback** [comment] 2020-05-14 10:16
pls try on master 
a patch was recently merged for this

**Comment by jorisvandenbossche** [comment] 2020-05-14 16:34
Yes, master gives

```
In [21]: import pandas as pd 
    ...:  
    ...: df = pd.DataFrame( 
    ...:     [ 
    ...:         {"key": 1, "value": None}, 
    ...:     ], 
    ...:     dtype="Int64", 
    ...: )                                                                                                                                                                                                         

In [22]: df.groupby("key")["value"].sum(min_count=1)                                                                                                                                                               
Out[22]: 
key
1    <NA>
Name: value, dtype: Int64
```

Duplicate of #32861

**Closed by jorisvandenbossche** 2020-05-14 16:34 UTC
Labels: Bug, Needs Triage

**Comment by ali-tny** [comment] 2020-05-15 00:50
Thanks! Sorry I missed the closed issue
