### ISSUE TITLE
merge of sparse dataframe fails

### ISSUE THREAD

**Issue by simonm3** [pandas-dev/pandas#13665] opened 2016-07-15 14:43 UTC
This works fine:

```
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df2 = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
df.merge(df2, how="left", on="A")
```

This fails with "TypeError: type object argument after \* must be a sequence, not map"

```
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD')).to_sparse()
df2 = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD')).to_sparse()
df.merge(df2, how="left", on="A")
```

**Comment by sinhrks** [comment] 2016-07-16 18:50
Thx for the report. Currently sparse doesn't support all the functionality and should raise understandable error. 

I feel supporting merge op in sparse data should have some limitations. Can you describe what type of data you actually have (pls show a sample data)?

**Comment by simonm3** [comment] 2016-07-16 18:58
Thanks for reply. Would be better to have sensible error and list in the
docs what is and is not supported.

Even the small example I gave does not work. My real example has 32m rows
merged with 1m rows. It fails with memory error if not sparse. Is there a
way of merging two large dataframes without using any extra memory e.g.
inplace=True for merge? I tried copy=False but it did not help. My
workaround is to merge a few columns at a time which allows me to release
memory from the original once copied.

**Comment by sinhrks** [comment] 2016-07-16 19:06
> Is there a way of merging two large dataframes without using any extra memory

It may worth to try https://github.com/dask/dask.

Pls let me know more about your data for future merging support.

- is merging key is unique?
- they matches one to one (inner join meets your needs?)

**Comment by simonm3** [comment] 2016-07-16 19:11
unique key. In this case was inner join. first table just 2 columns. second
table 500 columns.

will try dask. looks interesting

**Comment by hexgnu** [comment] 2018-01-02 17:09
So I took a look at this. The problem is that inside of how merging is done the sparse blocks get cast to dense blocks while invoking `get_values()`.

The simple fix would be to convert the whole thing to a dense data frame although that seems confusing. So I will dig to see if I can use sparse blocks instead of the dense blocks.

**Comment by matanster** [comment] 2018-09-02 16:07
While this PR was not merged yet, it could be worth noting that merging currently also breaks when merging a sparse dataframe with a non-sparse one.

**Comment by TomAugspurger** [comment] 2018-10-17 13:49
This should be fixed on master.

```python
In [4]: df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD')).to_sparse()
   ...: df2 = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD')).to_sparse()
   ...: df.merge(df2, how="left", on="A").head()
Out[4]:
    A  B_x  C_x  D_x   B_y   C_y   D_y
0  93   45   47   17  55.0  14.0  70.0
1  93   45   47   17  11.0  59.0  79.0
2  93   45   47   17  36.0  97.0  61.0
3  93   45   47   17  42.0  14.0  24.0
4  83   68   60   85   NaN   NaN   NaN

```

A confirmatory test would be appreciated, if anyone wants to do that.

**Closed** 2019-09-18 14:02 UTC
Labels: Effort Low, Error Reporting, Reshaping, Sparse, good first issue
