### ISSUE TITLE
Consider moving tests/ outside the pandas module

### ISSUE THREAD

**Issue by joaoe** [pandas-dev/pandas#31327] opened 2020-01-26 16:23 UTC
#### Problem description

Hi.
After a `pip install pandas` the `lib/site-packages/pands/tests/` includes a lot of testing code which is definitely not relevant for me and many other end users of pandas.
This bloats the installation and makes installation slower.
I'm working on packaging a python environment to distribute with a preinstalled set of modules and application and there are too many popular 3rd-party modules which include unneeded test code, like `numpy`, `IPython` `jupyterlab`, etc, which needs to be striped to keep the package size down. I'll be reporting issues to these projects as well.

#### Suggestion

Therefore, my suggestion is to keep the `pandas` module streamlined, and move the tests out. Perhaps create a `pandas-unittests` module if people are interested in it, or just expect users to checkout the code. Another possibility would be to skip packaging the `tests` folder and `conftest.py` when creating packages to upload to `pypi.org`.

Since you are now almost releasing 1.0 it might be a bit short notice to include this is such a big release. But for the next major release, it could work.

Thank you very much for your attention.

**Comment by MarcoGorelli** [comment] 2020-01-26 18:13
Thanks for the suggestion - I think this is a duplicate of #30741 and so will close the issue for now, but please feel free to reopen if you disagree :)

**Closed by MarcoGorelli** 2020-01-26 18:13 UTC

**Comment by joaoe** [comment] 2020-01-26 19:03
That seems like it. Thanks. I did search but could not find that issue.
