### ISSUE TITLE
ENH: Show data types under column names

### ISSUE THREAD

**Issue by pwwang** [pandas-dev/pandas#45813] opened 2022-02-04 00:32 UTC
#### Describe the solution you'd like

Data types are shown directly in `R` under column names:

```R
# A tibble: 4 × 2
      x     y
  <dbl> <int>
1     1     1
2     1     2
3     2     3
4     2     4
```

Wish pandas could have this feature as well.

#### Describe alternatives you've considered

https://github.com/pwwang/pdtypes

| Turn this | into |
| --------- | ---- |
| ![terminal_without_pdtypes][1] | ![terminal_with_pdtypes][2] |
| ![terminal_without_pdtypes_gf][3] | ![terminal_with_pdtypes_gf][4] |
| ![notebook_without_pdtypes][5] | ![notebook_with_pdtypes][6] |
| ![notebook_without_pdtypes_gf][7] | ![notebook_with_pdtypes_gf][8] |

Just wondering if this is a welcome to become a PR.

#### Additional context

[1]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/terminal_without_pdtypes.png
[2]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/terminal_with_pdtypes.png
[3]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/terminal_without_pdtypes_gf.png
[4]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/terminal_with_pdtypes_gf.png
[5]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/notebook_without_pdtypes.png
[6]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/notebook_with_pdtypes.png
[7]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/notebook_without_pdtypes_gf.png
[8]: https://raw.githubusercontent.com/pwwang/pdtypes/master/docs/notebook_with_pdtypes_gf.png

**Comment by jreback** [comment] 2022-02-04 00:38
we already have df.dtypes

not sure this adds anything here

**Comment by attack68** [comment] 2022-02-04 17:40
duplicate of #43875

**Comment by attack68** [comment] 2022-02-04 17:43
> we already have df.dtypes
> 
> not sure this adds anything here

I think seeing `dtypes` in context of the data is useful. Sometimes when importing big data the column name is not as informative as seeing the structure of the data and column name together, and then checking the `dtype`.

**Comment by phofl** [comment] 2022-02-06 20:16
Closing as duplicate then @attack68 ?

**Closed** 2022-02-06 20:17 UTC
Labels: Enhancement, Duplicate Report, Closing Candidate
