### ISSUE TITLE
BUG: index_col in read_csv ignores dtype

### ISSUE THREAD

**Issue by metazoic** [pandas-dev/pandas#35431] opened 2020-07-28 04:28 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

If `index.csv` contains:
```
id,key
00,11
22,33
```
then
```python
df = pandas.read_csv('index.csv', dtype=str, index_col='id')
df.index.dtype
```
results in
```
dtype('int64')
```

#### Problem description

This does not result in an index of strings.

#### Expected Output

By contrast,
```python
df = pandas.read_csv('index.csv', dtype=str)
df.set_index('id', inplace=True)
df.index.dtype
```
results in
```
dtype('O')
```
as intended.

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8
 
pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : 0.29.21
pytest           : 5.4.3
hypothesis       : None
sphinx           : 3.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.2
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.4.4
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.50.1
```

</details>

**Comment by simonjayhawkins** [comment] 2020-07-28 09:35
Thanks @metazoic for the report.

Further investigation and PRs welcome.

**Comment by jreback** [comment] 2020-07-28 10:01
look for a duplicate issue

**Comment by simonjayhawkins** [comment] 2020-07-28 10:09
duplicate of #32930 so closing

**Closed by simonjayhawkins** 2020-07-28 10:09 UTC
Labels: Bug, IO CSV, Index

**Comment by metazoic** [comment] 2020-07-29 03:38
@simonjayhawkins @jreback I promise I searched open issues, but the other issue didn't pop up with a "read_csv index_col" query (because it was labeled "pd.read_csv ...")!
