### ISSUE TITLE
Why we cannot use openpyxl to read excel files in pandas?

### ISSUE THREAD

**Issue by reaCodes** [pandas-dev/pandas#21099] opened 2018-05-17 08:01 UTC
When using `read_excel` to read excel files, I have to install `xlrd.` 
`read_excel` has parameter `engine,` but its value only can be `None` or `xlrd.` 
`ExcelWrite` can use `openpyxl` as `engine.`

Why we cannot use `openpyxl` to read excel files in `pandas`? Or whether I can or not?

**Comment by chris-b1** [comment] 2018-05-17 19:54
From what I recall this is because 1) `xlrd` is mature is works well, and 2) `openpyxl` doesn't support the legacy xls binary format.

Would probably take a pr supporting `openpyxl` as a reader if there are performance or other benefits

**Comment by cloje** [comment] 2018-08-11 22:27
I will write the PR to add openpyxl as a reader

**Comment by WillAyd** [comment] 2018-11-14 00:35
Closing as a duplicate of #11499

**Closed by WillAyd** 2018-11-14 00:35 UTC
Labels: Duplicate, Enhancement, IO Excel

**Comment by Themanwithoutaplan** [comment] 2018-11-14 13:31
@chris-b1 xlrd may be mature but it's XLSX support is limited. For example charts, images, formatting, pivot tables are all supported by openpyxl. xlrd is, at the time of writing, faster but this will change once openpyxl 2.6 is released.

**Comment by chris-b1** [comment] 2018-11-14 16:56
Thanks for the color @Themanwithoutaplan  - definitely didn't mean to disparage openpyxl, only meant for our purposes (not currently reading any formatting, charts, etc) xlrd works well.  If performance is improved in 2.6 definitely would be excited for that as an option!
