### ISSUE TITLE
The site ahead may contain harmful programs on doc website DOC:

### ISSUE THREAD

**Issue by vincentdavis** [pandas-dev/pandas#39910] opened 2021-02-19 14:17 UTC
#### The site ahead may contain harmful programs
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

<img width="1439" alt="Screen Shot 2021-02-19 at 7 08 58 AM" src="https://user-images.githubusercontent.com/232564/108515589-7b025f00-7282-11eb-93e3-ad844d272c5a.png">

**Comment by MarcoGorelli** [comment] 2021-02-19 14:19
dupe of #39862

**Closed by MarcoGorelli** 2021-02-19 14:19 UTC
Labels: Docs, Needs Triage
