### ISSUE TITLE
DataFrame.mad() results inconsistent with scipy.stats.median_absolute_deviation

### ISSUE THREAD

**Issue by manasIU** [pandas-dev/pandas#28995] opened 2019-10-15 09:29 UTC
```python
>>> import pandas as pd
>>> from scipy.stats import median_absolute_deviation
>>> data = [1, 1, 2, 2, 4, 6, 9] # taken from https://en.wikipedia.org/wiki/Median_absolute_deviation
>>> pd.DataFrame(data).mad()
0    2.367347
dtype: float64
>>> median_absolute_deviation(data)
1.4826
>>> median_absolute_deviation(data, scale=1)
1.0
```
#### Problem description
I want to calculate the Median Absolute Deviation for a 1D array. For the example dataset given on Wikipedia, I compared the results of `pandas.DataFrame.mad()` with the same function in scipy and found that the results are different.
**Expected output :** 
The wikipedia article states that the MAD for `data` should be 1. 
pandas gives `2.367347`.
scipy gives `1.4826`. 
scipy with `scale=1` gives `1`.
Going through [documentation](https://scipy.github.io/devdocs/generated/scipy.stats.median_absolute_deviation.html#rdfe996141950-1) for `scipy`, I found that the `scale` parameter by default assumes input data is normally distributed. Changing it to `1` gave me the expected result.

I don't understand why the pandas method returns `2.367`. The [documentation page](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mad.html) does not list anything similar to the scale parameter. 

**What am I missing?**

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-65-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_IN
LOCALE           : en_IN.ISO8859-1

pandas           : 0.25.1
numpy            : 1.16.4
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.2
setuptools       : 41.0.1
Cython           : None
pytest           : 5.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.14.1
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
>>> 

</details>

**Comment by lukasbk** [comment] 2019-10-15 10:27
According to the [docs](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.mad.html), the method pandas.DataFrame.mad is the "mean absolute deviation", not the "median absolute deviation". The first one is defined as the arithmetic mean of the deviations from the arithmetic mean:
mean(|x-mean(x)|)
The second one is the same but using the median instead of the mean:
median(|x-median(x)|)
Hence the result 2.367347 is indeed correct. As far as I can tell, there is no direct implementation of the "median absolute deviation" in pandas, yet. Should this feature be added?

**Comment by manasIU** [comment] 2019-10-15 11:00
Ahhh, my bad. However what you said is true - `mad` usually stands for median absolute deviation in all the articles I have read. 
If you do decide to implement `median absolute deviation` , please rename this method appropriately since it might lead to more confusion later. 
I guess that is why in scipy they use the full string `median_absolute_deviation`.

**Comment by jreback** [comment] 2019-10-15 11:11
duplicate of https://github.com/pandas-dev/pandas/issues/11787

we are going to deprecate .mad() entirely 

PR for that is welcome

**Closed by jreback** 2019-10-15 11:11 UTC

**Comment by lukasbk** [comment] 2019-10-15 11:28
I'd like to do that. Since I just started working on the project, can you give me a hint what to do for deprecation?

**Comment by jreback** [comment] 2019-10-15 11:50
https://github.com/pandas-dev/pandas/pull/28621/files was a recent deprecation, you can follow a similar pattern.
