### ISSUE TITLE
pd.where OverflowError with large numbers

### ISSUE THREAD

**Issue by wailashi** [pandas-dev/pandas#31687] opened 2020-02-05 08:43 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

df = pd.DataFrame([[1.0, 2e25],[np.nan, 0.1]])

# Works when applied to individual columns
print(df[0].where(pd.notnull(df[0]), None))
print(df[1].where(pd.notnull(df[1]), None))

# Breaks for whole dataframe
print(df.where(pd.notnull(df), None))

```
#### Problem description
The above code does not work with 1.0.0, but used to work with at least 0.25.0.
Replacing large floats with pd.where breaks 
Running pd.where on a dataframe that contains large float values and the replacement value is of a different dtype throws `OverflowError: int too big to convert`:

```
    applied = getattr(b, f)(**kwargs)
  File "***\venv\lib\site-packages\pandas\core\internals\blocks.py", line 1426, in where
    return self._maybe_downcast(blocks, "infer")
  File "***\venv\lib\site-packages\pandas\core\internals\blocks.py", line 514, in _maybe_downcast
    return _extend_blocks([b.downcast(downcast) for b in blocks])
  File "***\venv\lib\site-packages\pandas\core\internals\blocks.py", line 514, in <listcomp>
    return _extend_blocks([b.downcast(downcast) for b in blocks])
  File "***\venv\lib\site-packages\pandas\core\internals\blocks.py", line 552, in downcast
    return self.split_and_operate(None, f, False)
  File "***\venv\lib\site-packages\pandas\core\internals\blocks.py", line 496, in split_and_operate
    nv = f(m, v, i)
  File "***\venv\lib\site-packages\pandas\core\internals\blocks.py", line 549, in f
    val = maybe_downcast_to_dtype(val, dtype="infer")
  File "***\venv\lib\site-packages\pandas\core\dtypes\cast.py", line 135, in maybe_downcast_to_dtype
    converted = maybe_downcast_numeric(result, dtype, do_round)
  File "***\venv\lib\site-packages\pandas\core\dtypes\cast.py", line 222, in maybe_downcast_numeric
    new_result = trans(result).astype(dtype)
OverflowError: int too big to convert
```

Replacing data one column at a time works.

#### Expected Output
```
Name: 1, dtype: float64
      0      1
0     1  2e+25
1  None    0.1
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.0.0
numpy            : 1.16.2
pytz             : 2018.9
dateutil         : 2.8.0
pip              : 10.0.1
setuptools       : 39.1.0
Cython           : None
pytest           : 4.4.0
hypothesis       : None
sphinx           : 2.0.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.3.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.3
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 4.4.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.3
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by wailashi** [comment] 2020-02-10 14:23
Seems to be still broken on 1.0.1.

**Comment by rmsilva1973** [comment] 2020-04-13 22:15
**print(df.where(pd.notnull(df), 'some_str'))** raises the same exception.
However **print(df.where(pd.notnull(df), 1))** works.

Debugging through the code, it seems on this line **new_result = trans(result).astype(dtype)**, the astype method is to blame. **dtype** here is **int64**

**Comment by simonjayhawkins** [comment] 2020-04-25 14:44
> The above code does not work with 1.0.0, but used to work with at least 0.25.0.

looks like #29139 (i.e. 1.0.0)

225cc9284d1abfbcc9d13203419516575a63cc7a is the first bad commit
commit 225cc9284d1abfbcc9d13203419516575a63cc7a
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Thu Oct 24 05:10:07 2019 -0700

    CLN: remove Block._try_coerce_arg (#29139)

cc @jbrockmendel

**Comment by eloyfelix** [comment] 2020-06-12 21:57
also affected by this bug

**Comment by uchoa91** [comment] 2020-06-16 15:29
Same here. However got it using df.replace({pd.NaT: None}) instead of df.where(pd.notnull(df), None)

**Comment by simonjayhawkins** [comment] 2020-06-16 15:36
@TomAugspurger adding the blocker tag as several users affected by this regression.

**Comment by jreback** [comment] 2020-06-16 16:50
@simonjayhawkins i suppose this is ok for 1.1 as a blocker, though generally we should not simply block on things, this would delay releases indefinitly which is a much worse problem.

**Comment by eloyfelix** [comment] 2020-10-16 13:00
still broken in 1.1.3

**Comment by jreback** [comment] 2020-10-16 14:31
for all those commenting 'this is still broken' - well it's an open issue

you are welcome to propose a patch

**Comment by eloyfelix** [comment] 2020-10-16 14:37
sorry, it was marked as a blocker for 1.1 and I was not sure about its situation

**Comment by skvrahul** [comment] 2020-11-13 10:16
An added observation is that this seems to still be breaking with numbers smaller than `sys.maxsize`
Trying the same piece of code with a change in number:

```
import pandas as pd
import numpy as np
import sys

df = pd.DataFrame([[1.0, sys.maxsize-5],[np.nan, 0.1]])

# Works when applied to individual columns
print(df[0].where(pd.notnull(df[0]), None))
print(df[1].where(pd.notnull(df[1]), None))

# This line still breaks
print(df.where(pd.notnull(df), None))
```

This still causes the same error

**Comment by suvayu** [comment] 2020-11-30 21:34
take

**Comment by mroeschke** [comment] 2021-07-28 04:38
This looks to work on master now (`None` should coerce to `nan`). Could use a test.

```
In [2]: import pandas as pd
   ...: import numpy as np
   ...:
   ...: df = pd.DataFrame([[1.0, 2e25],[np.nan, 0.1]])
   ...:
   ...: # Works when applied to individual columns
   ...: print(df[0].where(pd.notnull(df[0]), None))
   ...: print(df[1].where(pd.notnull(df[1]), None))
   ...:
   ...: # Breaks for whole dataframe
   ...: print(df.where(pd.notnull(df), None))
0    1.0
1    NaN
Name: 0, dtype: float64
0    2.000000e+25
1    1.000000e-01
Name: 1, dtype: float64
     0             1
0  1.0  2.000000e+25
1  NaN  1.000000e-01
```

**Comment by eloyfelix** [comment] 2021-12-29 16:40
It's great that it doesn't crash anymore, many thanks!

What is lost from previous pandas versions (and it could be for a good reason) is that when reading from sql it is not possible anymore to keep null (None) as values on int and float columns. When you read a null from an int or float SQL column you don't really want to have <NA> and NaN. And if one wants to get dicts as records to insert/update database tables it is preferable to have None that will be converted to null.

In the past it was possible to translate NaN to null using `df.where(pd.notnull(df), None)`. It would be cool if it was still possible to replace <NA> and NaN for None.

Checking a bit polars dataframe, which is the other dataframe with nice database interoperability (sqlite, postgresql, mysql, sqlite, oracle... via connector-x), it keeps `null` type which is very convinient when using a dataframe for ETL.

**Comment by mliu08** [comment] 2022-11-17 23:18
take

**Comment by MarcoGorelli** [comment] 2022-11-27 12:31
Looks like this was fixed by https://github.com/pandas-dev/pandas/pull/39761

https://www.kaggle.com/code/marcogorelli/pandas-regression-example/notebook?scriptVersionId=112217500

**Closed** 2022-11-28 09:08 UTC
Labels: Dtype Conversions, good first issue, Needs Tests
