### ISSUE TITLE
TST: groupby of idxmax/min with mixed types

### ISSUE THREAD

**Issue by Leejung8763** [pandas-dev/pandas#40346] opened 2021-03-10 08:27 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df.groupby('teamId').idxmax()
tmp.groupby('teamId').idxmax()
```

#### Problem description

DataFrame df is consist of **teamId(int64)** and **neutralMinionsKilled(int64)** and 'tmp' is consist of **teamId(Int64)** and **neutralMinionsKilled(Int64)**
`df.groupby('teamId').idxmax()` is working
But `tmp.groupby('teamId').idxmax()` is not working and showing 'TypeError: argmax() takes 1 positional argument but 2 were given' 

#### Expected Output
![image](https://user-images.githubusercontent.com/50440358/110598649-559fab80-81c5-11eb-8327-33928f36605c.png)

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]
![image](https://user-images.githubusercontent.com/50440358/110598822-8c75c180-81c5-11eb-902a-1d743f0ad890.png)

</details>

**Comment by erfannariman** [comment] 2021-03-10 11:04
Can you add a reproducible example as mentioned when you opened the bug report, see [link](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

**Comment by Leejung8763** [comment] 2021-03-13 05:32
```
tmp = pd.DataFrame({'teamId': [100,100,100,200,200,200],
                   'value': [0,0,0,1,2,0],
                   })
tmp.groupby('teamId').idxmax()
```
It's working and the results are as follows.
![image](https://user-images.githubusercontent.com/50440358/111020372-ae12bb00-8408-11eb-8dd7-5b973aaa2377.png)

But,
```
tmp = pd.DataFrame({'teamId': [100,100,100,200,200,200],
                   'value': [0,0,0,1,2,0],
                   })
tmp = tmp.convert_dtypes()
tmp.groupby('teamId').idxmax()
```
It's not working with "TypeError: argmax() takes 1 positional argument but 2 were given" message

**Comment by MarcoGorelli** [comment] 2021-03-13 14:55
Thanks @Leejung8763 for the report

This works on master, but indeed fails in 1.1.3, will do a bisect

**Comment by MarcoGorelli** [comment] 2021-03-13 15:11
Fixed in #38195
```
4749fd611e0a303b7325686901c90e6a362bf3cd is the first bad commit
commit 4749fd611e0a303b7325686901c90e6a362bf3cd
Author: jbrockmendel
Date:   Wed Dec 2 04:11:05 2020 -0800

    BUG: DataFrame.idxmin/idxmax with mixed dtypes (#38195)
```

Could do with an extra test for this though, pull requests welcome

**Comment by bsun94** [comment] 2021-03-31 03:01
hi Marco, I'd love to take this on. I'm still somewhat new to pandas - hope you don't mind me reverting back if I have any questions!

**Comment by bsun94** [comment] 2021-04-03 19:07
Actually, I think more tests have been added since the PR quoted above - looking at the test_reductions.py module, it seems more has been appended to test_idxmax_mixed_dtype since what's displayed in the file changes in the PR.

**Comment by bsun94** [comment] 2021-04-03 19:51
One new case I thought of was adding a new column with all NaNs except one numeric value. Please let me know if that's valid

**Comment by MarcoGorelli** [comment] 2021-04-04 20:02
Hi @bsun94 - could you point me to which tests is like the one in this issue, i.e.
```python
tmp = pd.DataFrame({'teamId': [100,100,100,200,200,200],
                   'value': [0,0,0,1,2,0],
                   })
tmp = tmp.convert_dtypes()
tmp.groupby('teamId').idxmax()
```
? If there's already one like this or very similar, then we can close - thanks :+1:

**Comment by bsun94** [comment] 2021-04-04 21:32
no worries, this is what I currently see for pandas/tests/frame/test_reductions.py, in `TestDataFrameAnalytics`. The last block with the NaNs I've just added in my local, and haven't pushed out yet:

```python
def test_idxmax_mixed_dtype(self):
        # don't cast to object, which would raise in nanops
        dti = date_range("2016-01-01", periods=3)

        df = DataFrame({1: [0, 2, 1], 2: range(3)[::-1], 3: dti})

        result = df.idxmax()
        expected = Series([1, 0, 2], index=[1, 2, 3])
        tm.assert_series_equal(result, expected)

        result = df.idxmin()
        expected = Series([0, 2, 0], index=[1, 2, 3])
        tm.assert_series_equal(result, expected)

        # with NaTs
        df.loc[0, 3] = pd.NaT
        result = df.idxmax()
        expected = Series([1, 0, 2], index=[1, 2, 3])
        tm.assert_series_equal(result, expected)

        result = df.idxmin()
        expected = Series([0, 2, 1], index=[1, 2, 3])
        tm.assert_series_equal(result, expected)

        # with multi-column dt64 block
        df[4] = dti[::-1]
        df._consolidate_inplace()

        result = df.idxmax()
        expected = Series([1, 0, 2, 0], index=[1, 2, 3, 4])
        tm.assert_series_equal(result, expected)

        result = df.idxmin()
        expected = Series([0, 2, 1, 2], index=[1, 2, 3, 4])
        tm.assert_series_equal(result, expected)

        # with a column of NaNs? (In my local repo - not pushed)
        df[5] = [0] + [np.NaN] * 2

        result = df.idxmax()
        expected = Series([1, 0, 2, 0, 0], index=[1, 2, 3, 4, 5])
        tm.assert_series_equal(result, expected)

        result = df.idxmin()
        expected = Series([0, 2, 1, 2, 0], index=[1, 2, 3, 4, 5])
        tm.assert_series_equal(result, expected)
```

In terms of simulating dataframes containing data of different types, I think a few cases here achieve that. At least in my last case, I believe NaNs are treated as floats, and would be "mixed" with the rest of the integers in there. Please let me know if I'm on the right track!

**Comment by MarcoGorelli** [comment] 2021-04-05 10:10
These look different to the test case here, in which there aren't mixed types, but both are nullable integers:
```python
In [1]: tmp = pd.DataFrame({'teamId': [100,100,100,200,200,200],
   ...:                    'value': [0,0,0,1,2,0],
   ...:                    })
   ...: tmp = tmp.convert_dtypes()

In [2]: tmp
Out[2]: 
   teamId  value
0     100      0
1     100      0
2     100      0
3     200      1
4     200      2
5     200      0

In [3]: tmp.dtypes
Out[3]: 
teamId    Int64
value     Int64
dtype: object
```
 I think if you just make a new test case with the example from this issue that should be enough

**Comment by bsun94** [comment] 2021-04-06 04:22
sure thing, will put up a PR for this, thanks Marco!

**Closed** 2021-04-14 12:55 UTC
Labels: Groupby, Needs Tests, good first issue
