### ISSUE TITLE
BUG: `replace` throws `TypeError: Invalid value` with Extension dtypes

### ISSUE THREAD

**Issue by bollard** [pandas-dev/pandas#49022] opened 2022-10-10 08:36 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

pd.Series([False, True], dtype=pd.BooleanDtype()).replace(False, 10).dtype
> TypeError: Invalid value '10' for dtype boolean

pd.Series([False, True], dtype=np.bool_).replace(False, 10).dtype
> dtype('O')
```

### Issue Description

Hi there,

Notice some inconsistent behaviour between Pandas native extension arrays, and numpy equivalent dtypes. Specifically, in the numpy case, the dtype of the Series is downcast from `bool` -> `object`, whereas in the extension array case an error is thrown instead.

I can understand why the error is thrown, but the inconsistent behaviour is confusing. I'd expect either the first case to also downcast to object, or the second case to also throw a TypeError - but open to suggestions / discussion.

Thanks!

### Expected Behavior

```python
pd.Series([False, True], dtype=pd.BooleanDtype()).replace(False, 10).dtype
> dtype('O')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.5.0
numpy            : 1.23.1
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment] 2022-10-10 13:03
Hi, thanks for your report. This Is basically a duplicate of #47577

**Closed by phofl** 2022-10-10 13:03 UTC
Labels: Bug, Needs Triage
