### ISSUE TITLE
BUG: to_datetime with specific format are incorrectly matching

### ISSUE THREAD

**Issue by dadiego91** [pandas-dev/pandas#48707] opened 2022-09-22 09:30 UTC
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

ser = pd.Series(["2022\\12\\25"])

pd.to_datetime(ser, format="%Y-%m-%d") # this should fail, because format does not match
```

### Issue Description

There is an inconsisten behaviour between datetime library and pandas.to_datetime function when dealing with specific format.
When using slashes, it matches format though it shouldn't

### Expected Behavior

It should throw an Exception because the format does not match the values in the Series

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763
python           : 3.10.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0
numpy            : 1.23.3
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by MarcoGorelli** [comment] 2022-09-22 09:46
thanks for the report - looks like a duplicate of https://github.com/pandas-dev/pandas/issues/12649 ?

**Comment by MarcoGorelli** [comment] 2022-09-22 10:34
I think it's the same, it's due to the ISO8601 fastpath

```
(Pdb) p format_is_iso(format)
True
```

**Comment by MarcoGorelli** [comment] 2022-09-22 10:35
closing for now, but thanks for the report, I'll looking into addressing this as I also find it to be surprising

**Closed by MarcoGorelli** 2022-09-22 10:35 UTC
Labels: Bug, Timeseries
