### ISSUE TITLE
DOC: Create link from "Creating a development environment" to "pre-commit"

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#48941] opened 2022-10-04 20:12 UTC
~~I had to recreate my pandas environment from `environment.yml` .   Then when I updated a PR, the pre-commit was failing because `autotyping` was not installed.  It needs to be added to `environment.yml`~~

This is a docs issue.  See https://github.com/pandas-dev/pandas/issues/48941#issuecomment-1270114184

**Comment by MarcoGorelli** [comment] 2022-10-04 20:13
can you show the error please? I wouldn't expect it to fail, because it's listed in the additional dependencies

https://github.com/pandas-dev/pandas/blob/8bcc1ebb8babdfc95afe89219dabcaa98614caea/.pre-commit-config.yaml#L281

**Comment by Dr-Irv** [comment] 2022-10-04 20:15
```text
autotyping..............................................................................................Failed
- hook id: autotyping
- exit code: 1

Could not find autotyping in any configured modules
```

I had to install `autotyping` myself.

**Comment by MarcoGorelli** [comment] 2022-10-04 20:22
🤔 how odd, I don't have it installed in my environment
```
(pandas-dev) marcogorelli@DESKTOP-U8OKFP3:~/pandas-dev$ pre-commit run autotyping -a
autotyping...............................................................Passed
(pandas-dev) marcogorelli@DESKTOP-U8OKFP3:~/pandas-dev$ pip freeze | grep autotyping
```

I'll take a look tomorrow, but I wouldn't think you'd need to add it to `environment.yml` too

**Comment by MarcoGorelli** [comment] 2022-10-04 20:39
I tried again, with a new virtual environment, and it worked fine again:
```
(.venv) (base) marcogorelli@DESKTOP-U8OKFP3:~/pandas-dev$ pre-commit run autotyping -a
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
autotyping...............................................................Passed
```

I've never seen `Could not find autotyping in any configured modules` TBH - perhaps try opening a bug in https://github.com/pre-commit/pre-commit ? The `additional_dependencies` should definitely provide you with all you need in a local hook

**Comment by MarcoGorelli** [comment] 2022-10-04 20:45
Ah, got it (maybe)

The only way I can reproduce this error is by removing `autotyping` from 

https://github.com/pandas-dev/pandas/blob/main/.libcst.codemod.yaml

Does
```
git diff upstream/main -- .libcst.codemod.yaml .pre-commit-config.yaml
```
show nothing?

**Comment by Dr-Irv** [comment] 2022-10-04 21:15
> Does
> 
> ```
> git diff upstream/main -- .libcst.codemod.yaml .pre-commit-config.yaml
> ```
> 
> show nothing?

Yes, it shows nothing.

**Comment by Dr-Irv** [comment] 2022-10-04 21:15
Maybe there is something I needed to do to set up the pre-commit hook/installs?

**Comment by rhshadrach** [comment] 2022-10-04 22:23
One needs to run `pre-commit install` within the project directory to setup.

**Comment by twoertwein** [comment] 2022-10-05 12:50
Could it maybe be an issue on windows with how LibCST calls autotyping?

**Comment by MarcoGorelli** [comment] 2022-10-06 14:08
It you don't do `pre-commit install`, then `pre-commit` wouldn't run automatically on commit - if it ran for you then you must have already done it, or triggered it manually. `pre-commit install` isn't necessary for running it manually

I'll try this out on Windows to see if that's the issue

**Comment by EdwinCXM** [comment] 2022-10-10 13:54
Hi, I'm a first time contributor, has someone taken this yet? If not I would love to take this

**Comment by MarcoGorelli** [comment] 2022-10-10 13:55
go ahead, thanks!

**Comment by EdwinCXM** [comment] 2022-10-10 14:01
Thanks! Do I need to get assigned this?

**Comment by MarcoGorelli** [comment] 2022-10-10 14:08
if you comment "take" it'll be assigned to you - no  need if you've already commented though

**Comment by EdwinCXM** [comment] 2022-10-10 14:11
take

**Comment by HatimZ** [comment] 2022-10-25 16:51
take

**Closed** 2022-10-28 13:18 UTC
Labels: Docs, good first issue, Typing
