### ISSUE TITLE
Inconsistent results between `rolling.corr` and `corr`

### ISSUE THREAD

**Issue by evanzd** [pandas-dev/pandas#29264] opened 2019-10-29 09:52 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
x = pd.Series([0.125, 0.625, 0.5, 0.8125, 0.1875])
y = pd.Series([0.2, 0.2, 0.2, 0.2, 0.2])
print('rolling.corr:', x.rolling(5).corr(y).iloc[-1])
print('corr:', x.corr(y))
```

Output:

```
rolling.corr: -inf
corr: nan
```

#### Problem description

For constant vector (e.g., [0.2, 0.2, 0.2, 0.2, 0.2]), `corr` should be `nan` but not `inf`.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.16.5
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by mmitalidis** [comment] 2019-11-02 16:26
It seems that this happens because of arithmetic on floating point numbers and the different implementations of ```x.corr(y)``` and ```x.rolling(5).corr(y)```

Specifically, ```x.corr(y)``` calls:
https://github.com/pandas-dev/pandas/blob/825f811e79d011b7ffd7797ac5735b5d93bd610f/pandas/core/nanops.py#L1253
which works as expected.

However, ```x.rolling(5).corr(y)``` will calculate the correlation at: https://github.com/pandas-dev/pandas/blob/1effb56d0f91623641122fd8555bd9037a530443/pandas/core/window/rolling.py#L1636
where ```a = x.rolling(5)``` and ```b = y.rolling(5)```.

```x.rolling(5).cov(y)``` is calculated at:
https://github.com/pandas-dev/pandas/blob/1effb56d0f91623641122fd8555bd9037a530443/pandas/core/window/rolling.py#L1503
which returns a very small number (but not 0.0).

Thus, the correlation is not a (0. / 0.) operation and you don't get nan.

To reproduce the non-zero covariance result:
```
import numpy as np

x = np.array([0.125, 0.625, 0.5, 0.8125, 0.1875])
y = np.array([0.2, 0.2, 0.2, 0.2, 0.2])

print(np.mean(x*y))
# 0.09
print(np.mean(x) * np.mean(y))
# 0.09000000000000001
print(np.mean(x * y) - np.mean(x) * np.mean(y))
# -1.3877787807814457e-17
```
or similarly with pandas:
```
import pandas as pd

x = pd.Series([0.125, 0.625, 0.5, 0.8125, 0.1875])
y = pd.Series([0.2, 0.2, 0.2, 0.2, 0.2])

print(x.rolling(5).cov(y).iloc[-1])
# -1.734723475976807e-17
```

**Comment by simonjayhawkins** [comment] 2020-05-22 16:09
closing as duplicate of #24019

**Closed by simonjayhawkins** 2020-05-22 16:09 UTC
Labels: Duplicate
