### ISSUE TITLE
BUG: read_sql_query ignores the DB API column type for coercing non-datatime objects leading to inconsistent behavior

### ISSUE THREAD

**Issue by john-bodley** [pandas-dev/pandas#46263] opened 2022-03-08 03:11 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd 
from sqlalchemy import create_engine

pd.read_sql_query(
    sql="SELECT TIMESTAMP('2022-01-01 00:00:00') AS ts", 
    con=create_engine("mysql://root@localhost:3360"),
).to_json()

pd.read_sql_query(
    sql="SELECT TIMESTAMP '2022-01-01 00:00:00' AS ts", 
    con=create_engine("trino://localhost:8080"),
).to_json()
```

### Issue Description

Thought the [read_query](https://github.com/pandas-dev/pandas/blob/d0cf9b5f419d4a3f0dc92a3af3a592f8bbf0bd15/pandas/io/sql.py#L2040-L2077) method has the explicit functionality to coerce non-datetime columns to read as such (via the `parse_date` argument) it seems to ignore the implicit `type_code` per the [DB API](https://www.python.org/dev/peps/pep-0249/) which is returned by the cursor object's description attribute, i.e., it only relies on the name per [here](https://github.com/pandas-dev/pandas/blob/d0cf9b5f419d4a3f0dc92a3af3a592f8bbf0bd15/pandas/io/sql.py#L2053).

There seems to be merit in implicit trying to coerce these non-datetime temporal columns to datetime objects for consistency. The alternatives are to try to ensure all underlying DB APIs conform (difficult) or attempting to use the `parse_date` argument which is also difficult given that the DB API column types are not known a prori. 

### Expected Behavior

The `read_sql_query` method should be more consistent with regards to the return types when reading temporal SQL fields into a DataFrame.

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.1
setuptools       : 49.2.1
Cython           : None
pytest           : 6.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.24
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None
</details>

**Comment by attack68** [comment] 2022-03-08 06:12
close as duplicate of #46264

**Closed by attack68** 2022-03-08 06:12 UTC
Labels: Bug, Needs Triage
