### ISSUE TITLE
v0.20 added dependency on being able to connect to X server

### ISSUE THREAD

**Issue by rmjarvis** [pandas-dev/pandas#16383] opened 2017-05-18 06:01 UTC
#### Code Sample, a copy-pastable example if possible

Running on an ssh terminal that doesn't use `ssh -X`:
```bash
$ python -c 'import pandas; print pandas.__version__'
0.19.2
$ pip install pandas==0.20.1 --user
Collecting pandas==0.20.1
  Using cached pandas-0.20.1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: pytz>=2011k in /direct/astro+u/mjarvis/.local/lib/python2.7/site-packages (from pandas==0.20.1)
Requirement already satisfied: python-dateutil in /direct/astro+u/mjarvis/.local/lib/python2.7/site-packages (from pandas==0.20.1)
Requirement already satisfied: numpy>=1.7.0 in /direct/astro+u/mjarvis/.local/lib/python2.7/site-packages (from pandas==0.20.1)
Requirement already satisfied: six>=1.5 in /gpfs/mnt/gpfs01/astro/packages/anaconda/default/lib/python2.7/site-packages (from python-dateutil->pandas==0.20.1)
Installing collected packages: pandas
  Found existing installation: pandas 0.19.2
    Uninstalling pandas-0.19.2:
      Successfully uninstalled pandas-0.19.2
Successfully installed pandas-0.20.1
$ python -c 'import pandas; print pandas.__version__'
: cannot connect to X server localhost:26.0
```
#### Problem description

`import pandas` should work on terminals without X11 forwarding, but starting with version 0.20 (both 0.20.0 and 0.20.1), it doesn't.

#### Expected Output

`0.20.1`

#### Output of ``pd.show_versions()``

<details>
/gpfs/mnt/gpfs01/astro/packages/anaconda/default/lib/python2.7/site-packages/mpl_toolkits/__init__.py:2: UserWarning: Module matplotlib was already imported from /gpfs01/astro/packages/anaconda/default/lib/python2.7/site-packages/matplotlib/__init__.pyc, but /direct/astro+u/mjarvis/.local/lib/python2.7/site-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 2.6.32-358.18.1.el6.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.1
pytest: 2.8.5
pip: 9.0.1
setuptools: 0.6
Cython: 0.23.4
numpy: 1.12.1
scipy: 0.17.0
xarray: None
IPython: 4.1.2
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
feather: None
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
pandas_gbq: None
pandas_datareader: None
None
</details>

**Comment by jreback** [comment] 2017-05-18 10:21
this is a dupe of #16288 and fixed for 0.20.2 (not released yet) in #16294

**Closed by jreback** 2017-05-18 10:21 UTC
