### ISSUE TITLE
Add `inplace` input param to `add_prefix` and `add_suffix`

### ISSUE THREAD

**Issue by deponovo** [pandas-dev/pandas#43472] opened 2021-09-09 08:34 UTC
I find myself often wanting to rename columns with a prefix or suffix **inplace** and want to avoid creating copies, so I end up with code as:

`df.rename(columns={col: add_prefix_or_suffix_func_prototype(col) for col in df.columns}, inplace=True)`

It would be a simple feature addition if the `add_prefix` and `add_suffix` would expose this `kwarg` (**inplace**) to simplify the code to:

`df.add_prefix('prefix', **inplace**=True)  # same for add_suffix`

**Comment by attack68** [comment] 2021-09-09 09:58
-1 on adding api that is very specific.

are there not other ways of acheiving this, such as at dataframe construction, or just relying on the way you have already used: dont really see the need to improve a one line code solution?

**Comment by deponovo** [comment] 2021-09-09 11:22
This is a suggestion. There is always a way. In the above comment, the suggested version with `add_prefix` is easier to read than the `rename` one. And in the end `add_prefix` is a special wrapper around `rename`, so I would not see a problem exposing args of `rename` through `add_prefix` where applicable.

**Comment by phofl** [comment] 2021-09-09 11:25
We are discussing deprecating inplace for most functions, -1 until we have decided how to move forward there

**Comment by mroeschke** [comment] 2021-09-30 23:38
Agreed, until https://github.com/pandas-dev/pandas/issues/16529 has been fully resolved, pandas kinda has a moratorium on `inplace`. Closing for now but we can resurrect after the outcome of that discussion

**Closed by mroeschke** 2021-09-30 23:38 UTC
Labels: Enhancement, Needs Triage

**Comment by janosh** [comment] 2022-03-10 18:02
Related/duplicate of #28132.
