### ISSUE TITLE
pandas dataframe to rpy2 dataframe gives me unwanted data

### ISSUE THREAD

**Issue by smartie-dieter** [pandas-dev/pandas#14746] opened 2016-11-25 18:29 UTC
#### Code Sample

```python
           df.to_csv("output_df.csv", sep=',', encoding='utf-8')
           df2 = pandas2ri.py2ri(df)
           df2.to_csvfile("output_df2.csv")
```
#### Problem description

I want to convert my pandas data.frame (df) into a rpy2 data.frame.
But unfortunately, it generates me a massive amount of unwanted data.
Data which isn't present in my original data.frame

#### Expected Output - ``which is the print out of df``
```xlsx
,AssociatedTaxa,BasisofRecord,Behavior,CanonicalName,CatalogNumber,CollectionCode,Conf,CoordinateUncertaintyInMeters,Country,CountryCode,DataGeneralizations,DataSetID,DataSetName,DateIdentified,Day,DecimalLatitude,DecimalLongitude,DeterminationID,EstablishmentMeans,EventDate,EventID,EventRemarks,Family,FieldDate,FilenameID,GBIFtaxoMatch,Genus,GeodeticDatum,IdentificationRemarks,IdentificationVerificationStatus,IdentifiedBy,IndividualCount,InstitutionCode,LifeStage,Locality,LocationRemarks,Modified,Month,Municipality,OccurrenceRemarks,Ordre,OrganismsQuantity,OrganismsQuantityType,ProviderID,RecordNumber,RecordedBy,SamplingProtocol,ScientificName,Sex,SpecificEpithet,StateProvince,TaxonRank,VerbatimCoordinates,VerbatimCoordinatesystem,VerbatimElevation,VerbatimEventDate,VerbatimLatitude,VerbatimLongitude,VerbatimScientificName,Year,cond_id,fips,ifbl,occurrenceID,spec_id,spec_id_orig,stat_id,uuid
0,None,HumanObservation,None,Ailanthus altissima,None,None,4,10.0,Belgium,BE,Subselection of  priority classified invasive species within the compiled datasets,17,Fusion BDs invasives,2013-09-26,26,55.73,-3.9049,None,Invasive,2013-09-26,None,None,Simaroubaceae,2013-09-26,demma_invasives2.sqlite,EXACT,Ailanthus,WGS84,None,5,"Muir, Malcolm",1,DEMNA-SPW,None,Lanarkshire,None,None,09,None,Presence,Sapindales,None,None,demma,2,"Muir, Malcolm",None,Ailanthus altissima (Miller) Swingle,None,altissima ,None,species,deg 55.73 -3.9049,WGS84,None,20130926,55.73,-3.9049,Ailanthus altissima,2013,2,None,,17:2,2,None,2,d73298b8-b32c-11e6-a3ef-0a1c6976a2db
1,None,HumanObservation,None,Ailanthus altissima,None,None,4,15.0,Belgium,BE,Subselection of  priority classified invasive species within the compiled datasets,17,Fusion BDs invasives,2014-10-19,19,51.4591,-2.6021,None,Invasive,2014-10-19,None,None,Simaroubaceae,2014-10-19,demma_invasives2.sqlite,EXACT,Ailanthus,WGS84,None,5,"Anonymous, Anonymous",1,DEMNA-SPW,None,West Gloucestershire,None,None,10,None,Presence,Sapindales,None,None,demma,3,"Anonymous, Anonymous",None,Ailanthus altissima (Miller) Swingle,None,altissima ,None,species,deg 51.4591 -2.6021,WGS84,None,20141019,51.4591,-2.6021,Ailanthus altissima,2014,3,None,,17:3,3,None,3,d73298b9-b32c-11e6-a3ef-0a1c6976a2db
2,None,HumanObservation,None,Ailanthus altissima,None,None,4,nan,Belgium,BE,Subselection of  priority classified invasive species within the compiled datasets,17,Fusion BDs invasives,2015-08-08,08,50.8102,3.3562,None,Invasive,2015-08-08,None,None,Simaroubaceae,2015-08-08,demma_invasives2.sqlite,EXACT,Ailanthus,WGS84,None,5,"vanhee, dave",1,DEMNA-SPW,None,None,None,None,08,None,Presence,Sapindales,None,None,demma,4,"vanhee, dave",None,Ailanthus altissima (Miller) Swingle,None,altissima ,None,species,deg 50.8102 3.3562,WGS84,None,20150808,50.8102,3.3562,Ailanthus altissima,2015,4,None,E23433,17:4,4,None,4,d73298ba-b32c-11e6-a3ef-0a1c6976a2db

```
#### Output of ``df2`` -  if you scroll to the right, you'll notice the problem.
```xlsx
"AssociatedTaxa","BasisofRecord","Behavior","CanonicalName","CatalogNumber","CollectionCode","Conf","CoordinateUncertaintyInMeters","Country","CountryCode","DataGeneralizations","DataSetID","DataSetName","DateIdentified","Day","DecimalLatitude","DecimalLongitude","DeterminationID","EstablishmentMeans","EventDate","EventID","EventRemarks","Family","FieldDate","FilenameID","GBIFtaxoMatch","Genus","GeodeticDatum","IdentificationRemarks","IdentificationVerificationStatus","IdentifiedBy","IndividualCount","InstitutionCode","LifeStage","Locality","LocationRemarks","Modified","Month","Municipality","OccurrenceRemarks","Ordre","OrganismsQuantity","OrganismsQuantityType","ProviderID","RecordNumber","RecordedBy","SamplingProtocol","ScientificName","Sex","SpecificEpithet","StateProvince","TaxonRank","VerbatimCoordinates","VerbatimCoordinatesystem","VerbatimElevation","VerbatimEventDate","VerbatimLatitude","VerbatimLongitude","VerbatimScientificName","Year","cond_id","fips","ifbl.0","ifbl.1","ifbl.2","ifbl.3","ifbl.4","ifbl.5","ifbl.6","ifbl.7","ifbl.8","ifbl.9","ifbl.10","ifbl.11","ifbl.12","ifbl.13","ifbl.14","ifbl.15","ifbl.16","ifbl.17","ifbl.18","ifbl.19","ifbl.20","ifbl.21","ifbl.22","ifbl.23","ifbl.24","ifbl.25","ifbl.26","ifbl.27","ifbl.28","ifbl.29","ifbl.30","ifbl.31","ifbl.32","ifbl.33","ifbl.34","ifbl.35","ifbl.36","ifbl.37","ifbl.38","ifbl.39","ifbl.40","ifbl.41","ifbl.42","ifbl.43","ifbl.44","ifbl.45","ifbl.46","ifbl.47","ifbl.48","ifbl.49","ifbl.50","ifbl.51","ifbl.52","ifbl.53","ifbl.54","ifbl.55","ifbl.56","ifbl.57","ifbl.58","ifbl.59","ifbl.60","ifbl.61","ifbl.62","ifbl.63","ifbl.64","ifbl.65","ifbl.66","ifbl.67","ifbl.68","ifbl.69","ifbl.70","ifbl.71","ifbl.72","ifbl.73","ifbl.74","ifbl.75","ifbl.76","ifbl.77","ifbl.78","ifbl.79","ifbl.80","ifbl.81","ifbl.82","ifbl.83","ifbl.84","ifbl.85","ifbl.86","ifbl.87","ifbl.88","ifbl.89","ifbl.90","ifbl.91","ifbl.92","ifbl.93","ifbl.94","ifbl.95","ifbl.96","ifbl.97","ifbl.98","ifbl.99","ifbl.100","ifbl.101","ifbl.102","ifbl.103","ifbl.104","ifbl.105","ifbl.106","ifbl.107","ifbl.108","ifbl.109","ifbl.110","ifbl.111","ifbl.112","ifbl.113","ifbl.114","ifbl.115","ifbl.116","ifbl.117","ifbl.118","ifbl.119","ifbl.120","ifbl.121","ifbl.122","ifbl.123","ifbl.124","ifbl.125","ifbl.126","ifbl.127","ifbl.128","ifbl.129","ifbl.130","ifbl.131","ifbl.132","ifbl.133","ifbl.134","ifbl.135","ifbl.136","ifbl.137","ifbl.138","ifbl.139","ifbl.140","ifbl.141","ifbl.142","ifbl.143","ifbl.144","ifbl.145","ifbl.146","ifbl.147","ifbl.148","ifbl.149","ifbl.150","ifbl.151","ifbl.152","ifbl.153","ifbl.154","ifbl.155","ifbl.156","ifbl.157","ifbl.158","ifbl.159","ifbl.160","ifbl.161","ifbl.162","ifbl.163","ifbl.164","ifbl.165","ifbl.166","ifbl.167","ifbl.168","ifbl.169","ifbl.170","ifbl.171","ifbl.172","ifbl.173","ifbl.174","ifbl.175","ifbl.176","ifbl.177","ifbl.178","ifbl.179","ifbl.180","ifbl.181","ifbl.182","ifbl.183","ifbl.184","ifbl.185","ifbl.186","ifbl.187","ifbl.188","ifbl.189","ifbl.190","ifbl.191","ifbl.192","ifbl.193","ifbl.194","ifbl.195","ifbl.196","ifbl.197","ifbl.198","ifbl.199","ifbl.200","ifbl.201","ifbl.202","ifbl.203","ifbl.204","ifbl.205","ifbl.206","ifbl.207","ifbl.208","ifbl.209","ifbl.210","ifbl.211","ifbl.212","ifbl.213","ifbl.214","ifbl.215","ifbl.216","ifbl.217","ifbl.218","ifbl.219","ifbl.220","ifbl.221","ifbl.222","ifbl.223","ifbl.224","ifbl.225","ifbl.226","ifbl.227","ifbl.228","ifbl.229","ifbl.230","ifbl.231","ifbl.232","ifbl.233","ifbl.234","ifbl.235","ifbl.236","ifbl.237","ifbl.238","ifbl.239","ifbl.240","ifbl.241","ifbl.242","ifbl.243","ifbl.244","ifbl.245","ifbl.246","ifbl.247","ifbl.248","ifbl.249","ifbl.250","ifbl.251","ifbl.252","ifbl.253","ifbl.254","ifbl.255","ifbl.256","ifbl.257","ifbl.258","ifbl.259","ifbl.260","ifbl.261","ifbl.262","ifbl.263","ifbl.264","ifbl.265","ifbl.266","ifbl.267","ifbl.268","ifbl.269","ifbl.270","ifbl.271","ifbl.272","ifbl.273","ifbl.274","ifbl.275","ifbl.276","ifbl.277","ifbl.278","ifbl.279","ifbl.280","ifbl.281","ifbl.282","ifbl.283","ifbl.284","ifbl.285","ifbl.286","ifbl.287","ifbl.288","ifbl.289","ifbl.290","ifbl.291","ifbl.292","ifbl.293","ifbl.294","ifbl.295","ifbl.296","ifbl.297","ifbl.298","ifbl.299","ifbl.300","ifbl.301","ifbl.302","ifbl.303","ifbl.304","ifbl.305","ifbl.306","ifbl.307","ifbl.308","ifbl.309","ifbl.310","ifbl.311","ifbl.312","ifbl.313","ifbl.314","ifbl.315","ifbl.316","ifbl.317","ifbl.318","ifbl.319","ifbl.320","ifbl.321","ifbl.322","ifbl.323","ifbl.324","ifbl.325","ifbl.326","ifbl.327","ifbl.328","ifbl.329","ifbl.330","ifbl.331","ifbl.332","ifbl.333","ifbl.334","ifbl.335","ifbl.336","ifbl.337","ifbl.338","ifbl.339","ifbl.340","ifbl.341","ifbl.342","ifbl.343","ifbl.344","ifbl.345","ifbl.346","ifbl.347","ifbl.348","ifbl.349","ifbl.350","ifbl.351","ifbl.352","ifbl.353","ifbl.354","ifbl.355","ifbl.356","ifbl.357","ifbl.358","ifbl.359","ifbl.360","ifbl.361","ifbl.362","ifbl.363","ifbl.364","ifbl.365","ifbl.366","ifbl.367","ifbl.368","ifbl.369","ifbl.370","ifbl.371","ifbl.372","ifbl.373","ifbl.374","ifbl.375","ifbl.376","ifbl.377","ifbl.378","ifbl.379","ifbl.380","ifbl.381","ifbl.382","ifbl.383","ifbl.384","ifbl.385","ifbl.386","ifbl.387","ifbl.388","ifbl.389","ifbl.390","ifbl.391","ifbl.392","ifbl.393","ifbl.394","ifbl.395","ifbl.396","ifbl.397","ifbl.398","ifbl.399","ifbl.400","ifbl.401","ifbl.402","ifbl.403","ifbl.404","ifbl.405","ifbl.406","ifbl.407","ifbl.408","ifbl.409","ifbl.410","ifbl.411","ifbl.412","ifbl.413","ifbl.414","ifbl.415","ifbl.416","ifbl.417","ifbl.418","ifbl.419","ifbl.420","ifbl.421","ifbl.422","ifbl.423","ifbl.424","ifbl.425","ifbl.426","ifbl.427","ifbl.428","ifbl.429","ifbl.430","ifbl.431","ifbl.432","ifbl.433","ifbl.434","ifbl.435","ifbl.436","ifbl.437","ifbl.438","ifbl.439","ifbl.440","ifbl.441","ifbl.442","ifbl.443","ifbl.444","ifbl.445","ifbl.446","ifbl.447","ifbl.448","ifbl.449","ifbl.450","ifbl.451","ifbl.452","ifbl.453","ifbl.454","ifbl.455","ifbl.456","ifbl.457","ifbl.458","ifbl.459","ifbl.460","ifbl.461","ifbl.462","ifbl.463","ifbl.464","ifbl.465","ifbl.466","ifbl.467","ifbl.468","ifbl.469","ifbl.470","ifbl.471","ifbl.472","ifbl.473","ifbl.474","ifbl.475","ifbl.476","ifbl.477","ifbl.478","ifbl.479","ifbl.480","ifbl.481","ifbl.482","ifbl.483","ifbl.484","ifbl.485","ifbl.486","ifbl.487","ifbl.488","ifbl.489","ifbl.490","ifbl.491","ifbl.492","ifbl.493","ifbl.494","ifbl.495","ifbl.496","ifbl.497","ifbl.498","ifbl.499","occurrenceID","spec_id","spec_id_orig","stat_id","uuid"
"0","None","HumanObservation","None","Ailanthus altissima","None","None","4","10.0","Belgium","BE","Subselection of  priority classified invasive species within the compiled datasets","17","Fusion BDs invasives","2013-09-26","26","55.73","-3.9049","None","Invasive","2013-09-26","None","None","Simaroubaceae","2013-09-26","demma_invasives2.sqlite","EXACT","Ailanthus","WGS84","None","5","Muir, Malcolm","1","DEMNA-SPW","None","Lanarkshire","None","None","09","None","Presence","Sapindales","None","None","demma","2","Muir, Malcolm","None","Ailanthus altissima (Miller) Swingle","None","altissima ","None","species","deg 55.73 -3.9049","WGS84","None","20130926","55.73","-3.9049","Ailanthus altissima","2013","2","None",NA,NA,"E23433","E24213",NA,"?71423",NA,NA,"C72332","C14541",NA,"C44624","C14814","C14832","C24144","C04843","C04843","C04843","C04843","C04843","C35234","C35234","E11641","F32812",NA,"H74232",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"C22243","C24143","C04843","C25121","C04843","C04843","C15814","C35243","C35234","D21131","D21133","D31143","D11743","E31821","E22511","F45223","F45241","H74232",NA,NA,NA,NA,"F45241","F45232",NA,NA,NA,"?71522","B74223",NA,NA,NA,NA,NA,NA,"C11444","C72332","C22331","C32633","C32633","C32633","C32633","C32633","C22144","C14611","C23142","C23132","C23211","C24332","C24332","C14632","C24143","C04843","C04843","E31821","E41133","E25111","E35114","E45413","F43411",NA,NA,NA,NA,NA,NA,"C24142","C04843","C04843","C04843","C04843","C04843","C35522","C04843","C04843","C04843","C04843","C04843","C04843","C04843","C75722","C75722","C15612","C35241","C35234","C35234","C35234","D31143","D11732","D21133",NA,"D14834","D14744","E31821","E23413","E13833","E35114","F35521","F45331","H74232","J54113",NA,NA,NA,"C35241","F44341",NA,NA,NA,NA,NA,"D21132","D13833","E31823","F55342","E41133","J54113",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"<55643","<55544","<55623",NA,NA,">62723",NA,NA,"E23433","E24213",NA,"?71423",NA,NA,"C72332","C14541",NA,"C44624","C14814","C14832","C24144","C04843","C04843","C04843","C04843","C04843","C35234","C35234","E11641","F32812",NA,"H74232",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"C22243","C24143","C04843","C25121","C04843","C04843","C15814","C35243","C35234","D21131","D21133","D31143","D11743","E31821","E22511","F45223","F45241","H74232",NA,NA,NA,NA,"F45241","F45232",NA,NA,NA,"?71522","B74223",NA,NA,NA,NA,NA,NA,">62723",">62723",">75821","?71414",NA,"@71523",NA,NA,NA,NA,NA,NA,"@45434",NA,"E31821","E31823","E31823","C11444","C72332","C22331","C32633","C32633","C32633","C32633","C32633","C22144","C14611","C23142","C23132","C23211","C24332","C24332","C14632","C24143","C04843","C04843","E31821","E41133","E25111","E35114","E45413","F43411",NA,NA,NA,NA,NA,NA,"C24142","C04843","C04843","C04843","C04843","C04843","C35522","C04843","C04843","C04843","C04843","C04843","C04843","C04843","C75722","C75722","C15612","C35241","C35234","C35234","C35234","D31143","D11732","D21133",NA,"D14834","D14744","E31821","E23413","E13833","E35114","F35521","F45331","H74232","J54113",NA,NA,NA,"C35241","F44341",NA,NA,NA,NA,NA,"D21132","D13833","E31823","F55342","E41133","J54113",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"E31823","E31823","E31823","E31823","E31823","E31824","E31823","E41133","E22322","E22411","E22511","E12831","E23412","E23213","E13724","E23213","E23413","E23433","E23344","E14811","F35521",NA,"A33112",NA,NA,NA,"B41544",NA,NA,NA,NA,NA,"B74212",NA,NA,NA,NA,NA,NA,NA,NA,"<55643","<55544","<55623",NA,NA,">62723",">62723",">62723",">75821","?71414",NA,"@71523",NA,NA,NA,NA,NA,NA,"@45434",NA,"E31821","E31823","E31823","E31823","E31823","E31823","E31823","E31823","E31824","E31823","E41133","E22322","E22411","E22511","E12831","E23412","E23213","E13724","E23213","E23413","E23433","E23344","E14811","F35521",NA,"A33112",NA,NA,NA,"B41544",NA,NA,NA,NA,NA,"B74212",NA,NA,"B74211","C11533","C04843","C04843","C35243","C04843","C04843","C35243",NA,"B74211","C11533","C04843","C04843","C35243","C04843","C04843","C35243","17:2","2","None","2","d73298b8-b32c-11e6-a3ef-0a1c6976a2db"
"1","None","HumanObservation","None","Ailanthus altissima","None","None","4","15.0","Belgium","BE","Subselection of  priority classified invasive species within the compiled datasets","17","Fusion BDs invasives","2014-10-19","19","51.4591","-2.6021","None","Invasive","2014-10-19","None","None","Simaroubaceae","2014-10-19","demma_invasives2.sqlite","EXACT","Ailanthus","WGS84","None","5","Anonymous, Anonymous","1","DEMNA-SPW","None","West Gloucestershire","None","None","10","None","Presence","Sapindales","None","None","demma","3","Anonymous, Anonymous","None","Ailanthus altissima (Miller) Swingle","None","altissima ","None","species","deg 51.4591 -2.6021","WGS84","None","20141019","51.4591","-2.6021","Ailanthus altissima","2014","3","None",NA,NA,"E23433","E24213",NA,"?71423",NA,NA,"C72332","C14541",NA,"C44624","C14814","C14832","C24144","C04843","C04843","C04843","C04843","C04843","C35234","C35234","E11641","F32812",NA,"H74232",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"C22243","C24143","C04843","C25121","C04843","C04843","C15814","C35243","C35234","D21131","D21133","D31143","D11743","E31821","E22511","F45223","F45241","H74232",NA,NA,NA,NA,"F45241","F45232",NA,NA,NA,"?71522","B74223",NA,NA,NA,NA,NA,NA,"C11444","C72332","C22331","C32633","C32633","C32633","C32633","C32633","C22144","C14611","C23142","C23132","C23211","C24332","C24332","C14632","C24143","C04843","C04843","E31821","E41133","E25111","E35114","E45413","F43411",NA,NA,NA,NA,NA,NA,"C24142","C04843","C04843","C04843","C04843","C04843","C35522","C04843","C04843","C04843","C04843","C04843","C04843","C04843","C75722","C75722","C15612","C35241","C35234","C35234","C35234","D31143","D11732","D21133",NA,"D14834","D14744","E31821","E23413","E13833","E35114","F35521","F45331","H74232","J54113",NA,NA,NA,"C35241","F44341",NA,NA,NA,NA,NA,"D21132","D13833","E31823","F55342","E41133","J54113",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"<55643","<55544","<55623",NA,NA,">62723",NA,NA,"E23433","E24213",NA,"?71423",NA,NA,"C72332","C14541",NA,"C44624","C14814","C14832","C24144","C04843","C04843","C04843","C04843","C04843","C35234","C35234","E11641","F32812",NA,"H74232",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"C22243","C24143","C04843","C25121","C04843","C04843","C15814","C35243","C35234","D21131","D21133","D31143","D11743","E31821","E22511","F45223","F45241","H74232",NA,NA,NA,NA,"F45241","F45232",NA,NA,NA,"?71522","B74223",NA,NA,NA,NA,NA,NA,">62723",">62723",">75821","?71414",NA,"@71523",NA,NA,NA,NA,NA,NA,"@45434",NA,"E31821","E31823","E31823","C11444","C72332","C22331","C32633","C32633","C32633","C32633","C32633","C22144","C14611","C23142","C23132","C23211","C24332","C24332","C14632","C24143","C04843","C04843","E31821","E41133","E25111","E35114","E45413","F43411",NA,NA,NA,NA,NA,NA,"C24142","C04843","C04843","C04843","C04843","C04843","C35522","C04843","C04843","C04843","C04843","C04843","C04843","C04843","C75722","C75722","C15612","C35241","C35234","C35234","C35234","D31143","D11732","D21133",NA,"D14834","D14744","E31821","E23413","E13833","E35114","F35521","F45331","H74232","J54113",NA,NA,NA,"C35241","F44341",NA,NA,NA,NA,NA,"D21132","D13833","E31823","F55342","E41133","J54113",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"E31823","E31823","E31823","E31823","E31823","E31824","E31823","E41133","E22322","E22411","E22511","E12831","E23412","E23213","E13724","E23213","E23413","E23433","E23344","E14811","F35521",NA,"A33112",NA,NA,NA,"B41544",NA,NA,NA,NA,NA,"B74212",NA,NA,NA,NA,NA,NA,NA,NA,"<55643","<55544","<55623",NA,NA,">62723",">62723",">62723",">75821","?71414",NA,"@71523",NA,NA,NA,NA,NA,NA,"@45434",NA,"E31821","E31823","E31823","E31823","E31823","E31823","E31823","E31823","E31824","E31823","E41133","E22322","E22411","E22511","E12831","E23412","E23213","E13724","E23213","E23413","E23433","E23344","E14811","F35521",NA,"A33112",NA,NA,NA,"B41544",NA,NA,NA,NA,NA,"B74212",NA,NA,"B74211","C11533","C04843","C04843","C35243","C04843","C04843","C35243",NA,"B74211","C11533","C04843","C04843","C35243","C04843","C04843","C35243","17:3","3","None","3","d73298b9-b32c-11e6-a3ef-0a1c6976a2db"
"2","None","HumanObservation","None","Ailanthus altissima","None","None","4","nan","Belgium","BE","Subselection of  priority classified invasive species within the compiled datasets","17","Fusion BDs invasives","2015-08-08","08","50.8102","3.3562","None","Invasive","2015-08-08","None","None","Simaroubaceae","2015-08-08","demma_invasives2.sqlite","EXACT","Ailanthus","WGS84","None","5","vanhee, dave","1","DEMNA-SPW","None","None","None","None","08","None","Presence","Sapindales","None","None","demma","4","vanhee, dave","None","Ailanthus altissima (Miller) Swingle","None","altissima ","None","species","deg 50.8102 3.3562","WGS84","None","20150808","50.8102","3.3562","Ailanthus altissima","2015","4","None",NA,NA,"E23433","E24213",NA,"?71423",NA,NA,"C72332","C14541",NA,"C44624","C14814","C14832","C24144","C04843","C04843","C04843","C04843","C04843","C35234","C35234","E11641","F32812",NA,"H74232",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"C22243","C24143","C04843","C25121","C04843","C04843","C15814","C35243","C35234","D21131","D21133","D31143","D11743","E31821","E22511","F45223","F45241","H74232",NA,NA,NA,NA,"F45241","F45232",NA,NA,NA,"?71522","B74223",NA,NA,NA,NA,NA,NA,"C11444","C72332","C22331","C32633","C32633","C32633","C32633","C32633","C22144","C14611","C23142","C23132","C23211","C24332","C24332","C14632","C24143","C04843","C04843","E31821","E41133","E25111","E35114","E45413","F43411",NA,NA,NA,NA,NA,NA,"C24142","C04843","C04843","C04843","C04843","C04843","C35522","C04843","C04843","C04843","C04843","C04843","C04843","C04843","C75722","C75722","C15612","C35241","C35234","C35234","C35234","D31143","D11732","D21133",NA,"D14834","D14744","E31821","E23413","E13833","E35114","F35521","F45331","H74232","J54113",NA,NA,NA,"C35241","F44341",NA,NA,NA,NA,NA,"D21132","D13833","E31823","F55342","E41133","J54113",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"<55643","<55544","<55623",NA,NA,">62723",NA,NA,"E23433","E24213",NA,"?71423",NA,NA,"C72332","C14541",NA,"C44624","C14814","C14832","C24144","C04843","C04843","C04843","C04843","C04843","C35234","C35234","E11641","F32812",NA,"H74232",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"C22243","C24143","C04843","C25121","C04843","C04843","C15814","C35243","C35234","D21131","D21133","D31143","D11743","E31821","E22511","F45223","F45241","H74232",NA,NA,NA,NA,"F45241","F45232",NA,NA,NA,"?71522","B74223",NA,NA,NA,NA,NA,NA,">62723",">62723",">75821","?71414",NA,"@71523",NA,NA,NA,NA,NA,NA,"@45434",NA,"E31821","E31823","E31823","C11444","C72332","C22331","C32633","C32633","C32633","C32633","C32633","C22144","C14611","C23142","C23132","C23211","C24332","C24332","C14632","C24143","C04843","C04843","E31821","E41133","E25111","E35114","E45413","F43411",NA,NA,NA,NA,NA,NA,"C24142","C04843","C04843","C04843","C04843","C04843","C35522","C04843","C04843","C04843","C04843","C04843","C04843","C04843","C75722","C75722","C15612","C35241","C35234","C35234","C35234","D31143","D11732","D21133",NA,"D14834","D14744","E31821","E23413","E13833","E35114","F35521","F45331","H74232","J54113",NA,NA,NA,"C35241","F44341",NA,NA,NA,NA,NA,"D21132","D13833","E31823","F55342","E41133","J54113",NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"E31823","E31823","E31823","E31823","E31823","E31824","E31823","E41133","E22322","E22411","E22511","E12831","E23412","E23213","E13724","E23213","E23413","E23433","E23344","E14811","F35521",NA,"A33112",NA,NA,NA,"B41544",NA,NA,NA,NA,NA,"B74212",NA,NA,NA,NA,NA,NA,NA,NA,"<55643","<55544","<55623",NA,NA,">62723",">62723",">62723",">75821","?71414",NA,"@71523",NA,NA,NA,NA,NA,NA,"@45434",NA,"E31821","E31823","E31823","E31823","E31823","E31823","E31823","E31823","E31824","E31823","E41133","E22322","E22411","E22511","E12831","E23412","E23213","E13724","E23213","E23413","E23433","E23344","E14811","F35521",NA,"A33112",NA,NA,NA,"B41544",NA,NA,NA,NA,NA,"B74212",NA,NA,"B74211","C11533","C04843","C04843","C35243","C04843","C04843","C35243",NA,"B74211","C11533","C04843","C04843","C35243","C04843","C04843","C35243","17:4","4","None","4","d73298ba-b32c-11e6-a3ef-0a1c6976a2db"

```

**Comment by jorisvandenbossche** [comment] 2016-11-25 20:44
@smartie-dieter Can you provide a reproducible example? (start with the creation of a dataframe which reproduces the problem) 
Further, is this a problem in writing the dataframe to csv, or are the values already present in the dataframe itself.

Given that it seems to be related to the conversion rpy2 dataframe or their csv writing, probably better to report it at the rpy2 issue tracker.

**Comment by jorisvandenbossche** [comment] 2017-02-17 22:32
Closing this issue as we do not have enough info, and possibly is a rpy2 issue.

**Closed by jorisvandenbossche** 2017-02-17 22:32 UTC
Labels: IO CSV, Needs Info
