### ISSUE TITLE
BUG: Max aggregator strange behavour

### ISSUE THREAD

**Issue by RavimoShark** [pandas-dev/pandas#33867] opened 2020-04-29 12:55 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
dataset_soft_cl = dataset_soft.loc[y_pred_gyr==0].abs()
max_y_g = dataset_soft_cl.groupby('event_id')[y_g_col].max().max(axis=1)
max_y_g_2=dataset_soft.loc[dataset_soft.event_id.isin(dataset_soft_cl.event_id)].abs().groupby('event_id')[y_g_col].max().max(axis=1)

```

#### Problem description

max_y_g is different from max_y_g_2 basically if the max per line is in the first line of the group max_y_g does not see it as opposed to max_y_g_2

#### Expected Output
max_y_g == max_y_g_2
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-46-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.3.post20200330
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 0.9.3
psycopg2         : None
jinja2           : None
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy             : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by mroeschke** [comment] 2020-04-29 17:05
Could you post a minimal-reproducible example? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment] 2020-05-07 13:28
Thanks @RavimoShark for the report

Closing due to lack of reproducible example, but feel free to reopen if you provide one

**Closed by MarcoGorelli** 2020-05-07 13:28 UTC
Labels: Bug, Needs Info
