### ISSUE TITLE
groupby breaks when using duplicated level names

### ISSUE THREAD

**Issue by guenteru** [pandas-dev/pandas#21075] opened 2018-05-16 09:34 UTC
Hi,
I updated to version 0.23.0 and all of a sudden the following code breaks:
```python
import pandas as pd
df = pd.DataFrame(data={'date': list(pd.date_range('5.1.2018', '5.10.2018')),
                        'vals': list(range(10))})
df.groupby([df.date.dt.month, df.date.dt.day])['vals'].sum()

ValueError: Duplicated level name: "date", assigned to level 1, is already used for level 0.
```
### Expected output:
Using version 0.22.0 the same code yields the following:

```python
date  date
5     1       0
      2       1
      3       2
      4       3
      5       4
      6       5
      7       6
      8       7
      9       8
      10      9
Name: vals, dtype: int64
```

It obviously contains duplicated level names. I get why this might be a problem, but as of version 0.23.0 it's not possible to specify the resulting level names.

**Comment by TomAugspurger** [comment] 2018-05-16 11:16
Thanks.

cc @WillAyd @toobaz if you have ideas.

FYI @guenteru we have release candidates, if you want to try things out and report things before hand. They're announced on the low-traffic pandas-dev mailing list: https://mail.python.org/mailman/listinfo/pandas-dev

**Comment by toobaz** [comment] 2018-05-16 12:25
Duplicate of #19029 I think?

**Comment by TomAugspurger** [comment] 2018-05-17 12:45
Closing in favor of #19029

**Closed by TomAugspurger** 2018-05-17 12:45 UTC
Labels: Groupby, MultiIndex, Regression
