### ISSUE TITLE
DOC: DataFrame.plot options are not documented in docstring form

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas#15458] opened 2017-02-20 02:44 UTC
These can be seen by inspecting the `__call__` attribute, but they are referenced from the particular plotting methods, but not easily learned about in IPython/Jupyter.

https://github.com/pandas-dev/pandas/blob/master/pandas/tools/plotting.py#L3781

**Comment by jorisvandenbossche** [comment] 2017-02-20 08:07
Hmm, I thought this worked correctly. There is this line: https://github.com/pandas-dev/pandas/blob/master/pandas/tools/plotting.py#L3624, adding the actual docs to the `__call__` method. 
But that seems to only work on an actual dataframe instance, not on `pd.DataFrame.plot?`.

We should probably just replace the class docstring with that, instead of only the `__call__` docstring.

**Comment by jorisvandenbossche** [comment] 2017-02-20 08:09
The online docs are correct: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html

**Comment by yinleon** [comment] 2017-03-07 16:12
Hi, I'd like to give this issue a shot. 

If I understand correctly...
This is the problem 
<img width="1280" alt="screen shot 2017-03-07 at 8 03 20 am" src="https://cloud.githubusercontent.com/assets/7376699/23665297/e823c7a2-030c-11e7-95be-bd394f468837.png">

Should look like what @jorisvandenbossche posted:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html

Is the solution to paste the <a href='https://github.com/pandas-dev/pandas/blob/master/pandas/tools/plotting.py#L2550'>shared docstring</a> to the `__call__` class?

**Comment by jorisvandenbossche** [comment] 2017-03-07 23:17
@yinleon that's indeed the problem. The `__call__` docstring is good, but it is the class docstring that should get updated.

**Comment by yinleon** [comment] 2017-03-08 06:46
Ok, I'm working on a Naive solution. This is also a problem for `pd.series.plot()`

**Comment by kylekeppler** [comment] 2017-03-21 19:07
[groupby.DataFrameGroupBy.plot](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.plot.html) documentation is lacking as well.

**Comment by jorisvandenbossche** [comment] 2020-01-22 08:45
Duplicate of https://github.com/pandas-dev/pandas/issues/29489

**Closed by jorisvandenbossche** 2020-01-22 08:46 UTC
Labels: Docs, good first issue
