### ISSUE TITLE
DOC/CI: Doc build is failing with sphinx 2.1

### ISSUE THREAD

**Issue by datapythonista** [pandas-dev/pandas#26723] opened 2019-06-07 23:15 UTC
The doc build is failing with:
```
Recursion error:
maximum recursion depth exceeded while calling a Python object

This can happen with very large or deeply nested source files.  You can carefully increase the default Python recursion limit of 1000 in conf.py with e.g.:
    import sys; sys.setrecursionlimit(1500)
```

I tried increasing the limit from 1,000 to 20,000 but still the same error, so I guess the problem is something else.

I think this is the first job that failed: https://travis-ci.org/pandas-dev/pandas/jobs/542714631 (PR #26697)

**Comment by TomAugspurger** [comment] 2019-06-08 03:19
Sphinx was bumped to 2.1.0 in https://travis-ci.org/pandas-dev/pandas/jobs/542714631.

**Comment by TomAugspurger** [comment] 2019-06-08 03:34
I can reproduce locally with 2.1.0. Pinning to 2.0.1, and will open an issue with sphinx.

**Comment by TomAugspurger** [comment] 2019-06-08 03:37
Quite a few warnings on 2.1. I'll take a closer look next week.

**Comment by mroeschke** [comment] 2020-05-08 03:19
Looks like we're using Sphinx 3 now in our doc builds. Don't think Sphinx 2.1 issues are relevant anymore so closing.

**Closed by mroeschke** 2020-05-08 03:19 UTC
Labels: CI, Docs
