### ISSUE TITLE
BUG: assignment should coerce dtype

### ISSUE THREAD

**Issue by nickmcadden** [pandas-dev/pandas#15657] opened 2017-03-11 21:35 UTC
test in-line here: https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexing/test_partial.py#L208

```python
>>> a = pd.DataFrame(index=[1,2,3],columns=["a"])
>>> a
     a
1  NaN
2  NaN
3  NaN
>>> a.interpolate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/pandas/core/generic.py", line 3670, in interpolate
    raise TypeError("Cannot interpolate with all NaNs.")
TypeError: Cannot interpolate with all NaNs.

>>> a.iloc[0,0]=1
>>> a
     a
1    1
2  NaN
3  NaN
>>> a.interpolate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/pandas/core/generic.py", line 3670, in interpolate
    raise TypeError("Cannot interpolate with all NaNs.")
TypeError: Cannot interpolate with all NaNs.
```
#### Problem description

A dataframe created with index but no data is intitially given NaN content. The interpolate() method will fail on this data. Even when data is added to the frame, the method still fails

#### Expected Output

```python
>>> a.iloc[0,0]=1
>>> a
     a
1    1
2   1
3   1 
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.4.2.final.0
python-bits: 64
OS: Darwin
OS-release: 15.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.19.2
nose: 1.3.6
pip: 1.5.6
setuptools: 2.1
Cython: None
numpy: 1.12.0
scipy: 0.16.1
statsmodels: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: 0.7.5.None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by jreback** [comment] 2017-03-12 15:40
```
In [18]: a = pd.DataFrame(index=[1,2,3],columns=["a"])

In [19]: a.iloc[0,0] = 1

In [20]: a
Out[20]: 
     a
1    1
2  NaN
3  NaN

In [22]: a.dtypes
Out[22]: 
a    object
dtype: object
```

The problem is that the dtype of ``a.a`` should be float. Nothing to do with ``interpolate`` itself.

This *should* change as soon as the assignment is made to a numeric.

**Comment by jreback** [comment] 2017-03-12 15:42
but I don't think we do this by default as it *can* be expensive (to do on every assignment). Though I think in this can its pretty easy to detect, so we should.

**Comment by TomAugspurger** [comment] 2019-12-30 15:14
FWIW, I *might* consider this out of scope. This kind of downcasting may be best handled by the user.

**Comment by jbrockmendel** [comment] 2022-01-01 01:57
I agree with Tom on this one.

We'd either need to always try to downcast on object dtypes or, as the OP seems to suggest, only do it when the DataFrame was initialized without and data.  But actually keeping track of how the constructor was called is a recipe for a Bad Time.

**Comment by jreback** [comment] 2022-01-01 02:04
i wonder if we try to cast object (and non string types) always how much of a perf penalty we would have

**Comment by jbrockmendel** [comment] 2022-01-01 02:10
> i wonder if we try to cast object (and non string types) always how much of a perf penalty we would have

1) even before thinking about perf, we have enough casting-related headaches as it is.
2) when set via .loc we set effectively in a for loop (trying to change that, but that's a ways off), so would end up checking for downcast repeatedly
3) sometimes users actually _want_ object dtype.  shouldn't make them re-upcast after every setitem

**Comment by mroeschke** [comment] 2022-07-05 23:19
Sounds like this behavior would introduce a lot of effort and complexity than its worth. I like the notion that dtypes should be explicitly set by the user as opposed to magically coerced. Closing, but can reopen if we discover there's a great need for this behavior

**Closed by mroeschke** 2022-07-05 23:19 UTC
Labels: Bug, Indexing, Closing Candidate
