### ISSUE TITLE
Merge even on NaN

### ISSUE THREAD

**Issue by b060149ee** [pandas-dev/pandas#28522] opened 2019-09-19 10:06 UTC
#### Sample code

```python
# Your code here
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [1,2,3,4], 'B': [1,2,3,4]})
df1 = pd.DataFrame({'A': [1,2, 3, 3, 4], 'B': [1,2,3, np.NaN, np.NaN],'C': ['a','b','a','c','d']})

df2=df.merge(df1, on=['A','B'], how='left')
![df2](https://user-images.githubusercontent.com/55535963/65235326-fabb5580-daf3-11e9-9c55-9c3b98f14e36.png)


df3=pd.DataFrame({'A': [1,2, 3, 3, 4], 'B': [1,2,3, np.NaN, np.NaN],'C': ['a','b','a', 'c','d']})
![df3](https://user-images.githubusercontent.com/55535963/65235333-fe4edc80-daf3-11e9-8d6e-1fa3d5de8339.png)

```
#### Problem description

Just want an option on merge function, which would take df and df1 to get df3 as well.

**Comment by TomAugspurger** [comment] 2019-09-19 13:21
We've had previous discussions about this. Can you search for them?

**Comment by b060149ee** [comment] 2019-09-24 11:01
I had searched before creating the ticket but clearly didn't seem to have done it properly. Sorry about that.

Is [this](https://github.com/pandas-dev/pandas/issues/22491) what you were referring to?

If so, I was just asking for an option on the merge method. If you think it is against the standards, can you please help me with a neat way of getting the above-expected output? Thanks in advance

**Comment by mroeschke** [comment] 2021-07-21 04:37
Closing as duplicate of https://github.com/pandas-dev/pandas/issues/32306 with a more recent discussion on the future policy we want.

**Closed by mroeschke** 2021-07-21 04:37 UTC
Labels: Reshaping
