### ISSUE TITLE
Pandas TimeDelta instantiation returns different object for same value

### ISSUE THREAD

**Issue by Dgomzi** [pandas-dev/pandas#25544] opened 2019-03-05 12:38 UTC
```python
pd.Timedelta(3,unit= 'M')
Out[26]: Timedelta('91 days 07:27:18')
pd.Timedelta('3M')
Out[27]: Timedelta('0 days 00:03:00')

```
#### Problem description
I tried instantiating Timedelta object using '3M' which returns Timedelta object with 3 minutes rather than 3Months

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 32
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252
pandas: 0.24.1
pytest: None
pip: 10.0.1
setuptools: 39.1.0
Cython: None
numpy: 1.16.1
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.3.0
sphinx: 1.8.4
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None

</details>

**Comment by WillAyd** [comment] 2019-03-05 16:26
Hmm I can see the confusion here. I *think* just a bug with the parser maybe not expecting months to be a valid identifier, though certainly should given the ISO 8601 spec.

Investigation and PRs would certainly be welcome. cc @mroeschke

**Comment by TomAugspurger** [comment] 2019-03-05 16:30
It should raise right? Since 3 months can't be represented as a fixed span of time?

**Comment by WillAyd** [comment] 2019-03-05 16:38
Also a good question. It's valid per the ISO 8601 spec:

https://en.wikipedia.org/wiki/ISO_8601#Durations

Though perhaps that would cause some issues with Python's time delta given it only stores up to days, so seems like it could be ambiguous the span of time we want to represent here. Not entirely sure myself...

**Comment by TomAugspurger** [comment] 2019-03-05 16:45
This came up with JSON table schema too. It wasn't clear to me then that timedeltas were equivalent to durations. I don't think you can say that "P3M" is iso-8601-duration notation is equivalent "n seconds" where `n` is the `.value` of our timedelta.

**Comment by mroeschke** [comment] 2019-03-05 19:28
We just deprecated the ability to pass `M` (month) and `Y` (year) as units because of the fixed span of time issue @TomAugspurger mentioned. https://github.com/pandas-dev/pandas/pull/23264

The behavior of `pd.Timedelta('3M')` _might_ have been changed recently in https://github.com/pandas-dev/pandas/pull/23439, but since we are deprecating `M`, it might be a bug that we expect to go away with the deprecation.

**Comment by mroeschke** [comment] 2020-05-03 21:46
Going to close this issue as it looks like a duplicate of https://github.com/pandas-dev/pandas/issues/27285 with more examples

**Closed by mroeschke** 2020-05-03 21:46 UTC
Labels: Bug, Timedelta
