### ISSUE TITLE
Double requirement given in Python 3.4.7 from version 0.21.0

### ISSUE THREAD

**Issue by jamesstidard** [pandas-dev/pandas#20764] opened 2018-04-20 15:01 UTC
I'm currently trying to install Pandas on a 3.4.7 environment and I am receiving this error from pip:

``` bash
Looking in indexes: https://pypi.python.org/simple
Collecting pandas==0.21.0
  Using cached https://files.pythonhosted.org/packages/84/4c/622301f99725c6da76ae8079cb6b9091d9098098bd6b4eac47fb502b32f4/pandas-0.21.0.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  Complete output from command /home/james/.local/share/virtualenvs/Test-bA7jXwT_/bin/python3.4m -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-6eig66tu https://files.pythonhosted.org/packages/1b/d2/22cde5ea9af055f81814f9f2545f5ed8a053eb749c08d186b369959189a8/wheel-0.31.0-py2.py3-none-any.whl#sha256=9cdc8ab2cc9c3c2e2727a4b67c22881dbb0e1c503d592992594c5e131c867107 https://files.pythonhosted.org/packages/20/d7/04a0b689d3035143e2ff288f4b9ee4bf6ed80585cc121c90bfd85a1a8c2e/setuptools-39.0.1-py2.py3-none-any.whl#sha256=8010754433e3211b9cdbbf784b50f30e80bf40fc6b05eb5f865fab83300599b8 https://files.pythonhosted.org/packages/70/25/1e1521e6ce2cf78ff4a8b06fbc2cd513ce004ec337000eddfe016fdf3fc6/Cython-0.28.2-cp34-cp34m-manylinux1_x86_64.whl#sha256=85f7432776870d65639fed00f951a3c05ef1e534bc72a73cd1200d79b9a7d7d0 https://files.pythonhosted.org/packages/fc/1b/a1717502572587c724858862fd9b98a66105f3a3443225bda9a1bd16ee14/numpy-1.9.3-cp34-cp34m-manylinux1_x86_64.whl#sha256=bff36563f9d6a06a81ae232f49d2946c84c05e391a7dff057496033c79507860 https://files.pythonhosted.org/packages/02/64/c6c1c24ff4dbcd789fcfdb782e343ac23c074f6b8b03e818ff60eb0f937f/numpy-1.12.1-cp34-cp34m-manylinux1_x86_64.whl#sha256=4eac5f2f624c5e7eecbdb51395ff39a099c48cab607a158f16f288c6fe39a2b3 https://files.pythonhosted.org/packages/1b/ee/f65826b2880f67652c21326565b4c166c7cdb1019f84b82af65e625475cd/numpy-1.13.1-cp34-cp34m-manylinux1_x86_64.whl#sha256=838e48df3703c8747f355cd6386e0680b906a2f7b2bbd304e8a2d531692484ce:
  Double requirement given: numpy==1.12.1 from https://files.pythonhosted.org/packages/02/64/c6c1c24ff4dbcd789fcfdb782e343ac23c074f6b8b03e818ff60eb0f937f/numpy-1.12.1-cp34-cp34m-manylinux1_x86_64.whl#sha256=4eac5f2f624c5e7eecbdb51395ff39a099c48cab607a158f16f288c6fe39a2b3 (already in numpy==1.9.3 from https://files.pythonhosted.org/packages/fc/1b/a1717502572587c724858862fd9b98a66105f3a3443225bda9a1bd16ee14/numpy-1.9.3-cp34-cp34m-manylinux1_x86_64.whl#sha256=bff36563f9d6a06a81ae232f49d2946c84c05e391a7dff057496033c79507860, name='numpy')
```

It looks as though it was something introduce in `0.21.0`. I would just upgrade the version of python, but this project currently has a `PySide` dependency which has a max requirement of 3.4.

Any idea's what may be causing this error?
maximin

**Comment by TomAugspurger** [comment] 2018-04-20 15:04
Pandas doesn't support 3.4. There was an issue with our `setup.py` not indicating that, which was fixed in https://github.com/pandas-dev/pandas/pull/20698.

**Comment by TomAugspurger** [comment] 2018-04-20 15:05
To be clear, pandas 0.21 dropped support for python 3.4.

You'll want to require an earlier version.

**Closed** 2018-04-20 15:10 UTC

**Comment by jamesstidard** [comment] 2018-04-20 15:12
Ah, so there were earlier distributions of the binary which allowed 3.4 to install and those have been retroactively fixed but under the same version number? I only ask because I have some 3.4 virtual machines with 2.1 and 2.2 installed.

Thanks

**Comment by jamesstidard** [comment] 2018-04-20 15:33
That's where my confusion has come from. I've been able to install 0.21 and 0.22 to previous Python 3.4 interpreters and the fix you linked looks like it's scheduled for 0.23 and shouldn't be in the releases. I mean if `pandas` hasn't officially supported 3.4 since 0.21, then I guess it doesn't really matter that this has broke, though it might be a symptom of another problem.

**Comment by jorisvandenbossche** [comment] 2018-04-20 15:41
This issue is caused by the pip version 10 release. 
It is certainly partly an issue that the pandas releases 0.21-0.22 didn't clearly indicate in setup.py that it is not compatible with python 3.4, but it is due to changes in pip that the issue now surfaces (before, pip just installed pandas from source for 3.4 since there were no wheels available, but it is this building from source that is now broken with pip 10)

**Comment by jamesstidard** [comment] 2018-04-20 20:55
@jorisvandenbossche Ah, that explains it, thank you. I should have known it was related to the pip 10 release, been having a few troubles with that at the moment.
