### ISSUE TITLE
RLS: 1.2.4

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas#40168] opened 2021-03-02 08:48 UTC
Tracking issue for the 1.2.4 release.

https://github.com/pandas-dev/pandas/milestone/84

Currently scheduled for April 01, 2021

List of open regressions: https://github.com/pandas-dev/pandas/issues?q=is%3Aopen+is%3Aissue+label%3ARegression

**Comment by jreback** [comment] 2021-04-09 19:46
so there is one open PR, but if any other regressions we want to patch, let's do so pretty soon, then can release

@pandas-dev/pandas-core @pandas-dev/pandas-triage

**Comment by simonjayhawkins** [comment] 2021-04-12 11:32
#40878 to be merged. other issues/PRs moved to 1.2.5 https://github.com/pandas-dev/pandas/milestone/85

**Comment by simonjayhawkins** [comment] 2021-04-12 13:35
pre-release checklist

- [ ]  https://github.com/MacPython/pandas-wheels/pull/130
- [ ]  release readiness passing https://github.com/simonjayhawkins/pandas-release/actions?query=workflow%3A%22Tag+Release%22
- [ ]  release notes checked https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.3.html
- [ ]  ci checks https://github.com/pandas-dev/pandas/commits/1.2.x
- [ ]  no manual backports outstanding https://github.com/pandas-dev/pandas/pulls?q=is%3Apr+label%3A%22Still+Needs+Manual+Backport%22+is%3Aclosed
- [ ]  no open issues/PRs (except this one) https://github.com/pandas-dev/pandas/milestone/83

@jorisvandenbossche I'll start to run through these now. (can either start again or maybe skip these depending on discussion in #40878

**Comment by simonjayhawkins** [comment] 2021-04-12 15:46
starting release now. (and re-running pre-release checks. will not push tag till these have passed)

pre-release checklist

- [ ]  https://github.com/MacPython/pandas-wheels/pull/130
- [ ]  release readiness passing https://github.com/simonjayhawkins/pandas-release/actions?query=workflow%3A%22Tag+Release%22
- [ ]  release notes checked https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.4.html
- [ ]  ci checks https://github.com/pandas-dev/pandas/commits/1.2.x
- [ ]  no manual backports outstanding https://github.com/pandas-dev/pandas/pulls?q=is%3Apr+label%3A%22Still+Needs+Manual+Backport%22+is%3Aclosed
- [ ]  no open issues/PRs (except this one) https://github.com/pandas-dev/pandas/milestone/84

1.2.4 release 

- [ ] tag locally
- [ ] build sdist
- [ ] pip test
- [ ] conda test
- [ ] build docs
- [ ] push tag https://github.com/pandas-dev/pandas/tags
- [ ] open PR to build wheels https://github.com/MacPython/pandas-wheels/pull/XXX
- [ ] upload docs https://pandas.pydata.org/pandas-docs/version/1.2.4/
- [ ] wheels in staging area https://anaconda.org/multibuild-wheels-staging/pandas/files
- [ ] github release - https://github.com/pandas-dev/pandas/releases
- [ ] upload wheels to PyPI https://pypi.org/project/pandas/
- [ ] change link for stable docs https://pandas.pydata.org/docs/
- [ ] Start v1.2.5 release notes https://github.com/pandas-dev/pandas/pull/XXXXX
- [ ] conda-forge bot picked up on release https://github.com/conda-forge/pandas-feedstock/pull/XXX
- [ ] available on conda-forge https://anaconda.org/conda-forge/pandas/files
- [ ] announce

**Comment by simonjayhawkins** [comment] 2021-04-12 16:43
building the docs is much slower than the previous release. It looks like it is only using one core. will push tag after ci checks on 1.2x are green. (I did a dummy release on Saturday so hopefully no changes that would cause the docs not to build)

**Comment by simonjayhawkins** [comment] 2021-04-12 17:03
ci checks completed on 1.2.x but since Travis job took a while the doc build is now at 87% so will wait a little and check the docs before pushing tag.

**Comment by jorisvandenbossche** [comment] 2021-04-12 17:23
> building the docs is much slower 

Ah, yes, we should maybe have included https://github.com/pandas-dev/pandas/pull/40761#issuecomment-815095979 for the 1.2.4 release... Otherwise @simonjayhawkins you can also pin the pydata-sphinx-theme to version 0.5.2 instead of using the latest (which is 0.6.0 right now)

**Comment by simonjayhawkins** [comment] 2021-04-12 17:35
docs built and uploaded. will add 1.2.5 milestone #40761

**Comment by simonjayhawkins** [comment] 2021-04-12 18:49
@jorisvandenbossche I recall some issue with caching on the web server in the past. the docs are OK at  https://pandas.pydata.org/pandas-docs/version/1.2.4/ but don't look right at https://pandas.pydata.org/docs/

does this sort itself out or some action needed?

**Comment by simonjayhawkins** [comment] 2021-04-12 19:57
> @jorisvandenbossche I recall some issue with caching on the web server in the past. the docs are OK at https://pandas.pydata.org/pandas-docs/version/1.2.4/ but don't look right at https://pandas.pydata.org/docs/
> 
> does this sort itself out or some action needed?

seems ok now.

**Comment by simonjayhawkins** [comment] 2021-04-13 07:44
https://github.com/conda-forge/pandas-feedstock/pull/110#issuecomment-818520131

> pypy build on drone completed in around 30 mins here on this PR but was killed at the hour mark on the commit.

> I can't see where on the drone console where the job can be restarted @jorisvandenbossche @jreback @TomAugspurger

**Comment by bashtage** [comment] 2021-04-13 07:47
Top right.

![image](https://user-images.githubusercontent.com/5585221/114516015-e76f5e00-9c34-11eb-8cb6-c3539606eecc.png)

**Comment by simonjayhawkins** [comment] 2021-04-13 07:50
Thanks @bashtage wasn't logged in!

**Comment by jorisvandenbossche** [comment] 2021-04-13 07:58
> I recall some issue with caching on the web server in the past.

The underlying issue that we experienced a while ago should be fixed (the CSS file now has a hash in the file name, so whenever there is a change in the CSS, the name changes and browser/server shouldn't incorrectly cache it). 

(but so if you would still notice it later, certainly report it!)

**Comment by rhshadrach** [comment] 2021-04-13 21:21
@jorisvandenbossche - When I clicked on the https://pandas.pydata.org/docs/ link above, I had to refresh the page for the CSS to properly render. Don't know if it as a cache issue or just a glitch.

**Comment by simonjayhawkins** [comment] 2021-04-14 14:27
all conda builds now successful and packages available on conda-forge (including aarch64)

**Closed** 2021-04-14 14:34 UTC
Labels: Release

**Comment by jorisvandenbossche** [comment] 2021-04-14 14:39
Thanks Simon!

> When I clicked on the https://pandas.pydata.org/docs/ link above, I had to refresh the page for the CSS to properly render. Don't know if it as a cache issue or just a glitch.

@rhshadrach yeah, not fully sure (no expert in this area). In any case, the original issue is solved in the theme, so it might be normal that you still might need a refresh for your local cache (the previous time, it was actually the server that was caching it as well, and a local browser refresh didn't automatically solve that)

**Comment by Dr-Irv** [comment] 2021-04-14 14:59
Not sure how this works, but there were some updates to the cheat sheet (https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) available from https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf that I merged in a couple of weeks ago, and I don't think they got pushed out to the server.

**Comment by simonjayhawkins** [comment] 2021-04-14 15:29
The docs are built from the backport branch.

**Comment by Dr-Irv** [comment] 2021-04-14 15:32
> The docs are built from the backport branch.

The concern here is that the cheat sheet isn't in the normal docs hierarchy at https://pandas.pydata.org/docs/

**Comment by simonjayhawkins** [comment] 2021-04-14 15:48
Is it available on the dev docs https://pandas.pydata.org/pandas-docs/dev/index.html

**Comment by jorisvandenbossche** [comment] 2021-04-14 16:20
@simonjayhawkins you might be talking about the pdf docs, and not the pdf cheatsheet? (as I don't see that linked on the docs home page)

@Dr-Irv the cheatsheet is linked at the bottom of https://pandas.pydata.org/pandas-docs/dev/getting_started/index.html, but it should probably get a more prominent place (feel free to open an issue about that, since it is not related to the release)

But so you are saying that https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf isn't the latest version (so the one at https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf has newer changes)? I also don't directly know how this is synced with the server. The website is synced with the github actions workflow, but the cheatsheet might not be included there.

**Comment by simonjayhawkins** [comment] 2021-04-14 16:44
> @simonjayhawkins you might be talking about the pdf docs, and not the pdf cheatsheet? (as I don't see that linked on the docs home page)

sorry I meant https://pandas.pydata.org/pandas-docs/dev/, the index.html is the default.

shouldn't the cheatsheet be under a version branch instead of at the top level?

**Comment by Dr-Irv** [comment] 2021-04-14 16:59
@jorisvandenbossche 
> @Dr-Irv the cheatsheet is linked at the bottom of https://pandas.pydata.org/pandas-docs/dev/getting_started/index.html, but it should probably get a more prominent place (feel free to open an issue about that, since it is not related to the release)

I'm fine with where the link is, but the link is to https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf so there needs to be something that regularly updates that top level PDF with what is in the repo.

> But so you are saying that https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf isn't the latest version (so the one at https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf has newer changes)? 

Yes, that is correct.  The one in the GitHub repo is the latest.

> I also don't directly know how this is synced with the server. The website is synced with the github actions workflow, but the cheatsheet might not be included there.

We had some issue with this some time ago, and I don't know what happened on the back end to automate the process.  See discussion here:  https://github.com/pandas-dev/pandas/pull/20366#issuecomment-373724162

**Comment by Dr-Irv** [comment] 2021-04-14 17:00
> shouldn't the cheatsheet be under a version branch instead of at the top level?

Decision was made and discussed here:  https://github.com/pandas-dev/pandas/pull/20366#issuecomment-373695756

Certainly worthwhile to consider moving it, although I think there are now people who link to the cheat sheet at its current location, so if it is moved, we may have to add a redirect to the site.

**Comment by simonjayhawkins** [comment] 2021-04-14 17:47
presumably the top level link should be linked to 'stable' branch which is the latest release.
