### ISSUE TITLE
xtick label setting with improper scale

### ISSUE THREAD

**Issue by fonnesbeck** [pandas-dev/pandas#2980] opened 2013-03-06 19:33 UTC
I have some data that I have used to generate a stacked bar graph. 

```
by_conclusion = measles_data.groupby(["AGE", "CONCLUSION"])
counts_by_cause = by_conclusion.size().unstack().fillna(0)
ax = counts_by_cause.plot(kind='bar', stacked=True)
```

However, I get a pretty crowded x-axis:

![too_many_ticks](https://f.cloud.github.com/assets/81476/229080/29637982-8694-11e2-96bd-24a96c3e2dcd.png)

So, I try to use `set_xticks` to try and thin them out, either as an argument to plot, or as a separate command:

```
ax.xticks(arange(0,80,10))
```

However, for some reason, the labels end up being downscaled by a factor of 10:

![wrong_ticks](https://f.cloud.github.com/assets/81476/229081/2be6bf8e-8694-11e2-8d5c-46288606d785.png)

(might be hard to see, but it is printing "0.0, 1.0, 2.0, ..." instead of "0, 10, 20, ...")

Its not clear why this is happening, or how to get around it, so I'm either going about this wrong or its a bug. I get the same behavior when I try using `MaxNLocator`:

```
ax.xaxis.set_major_locator( MaxNLocator(nbins = 7) )
```

[The data are here](https://dl.dropbox.com/u/233041/measles.csv)

**Comment by jorisvandenbossche** [comment] 2017-04-06 07:45
Closing as duplicate of  #7612

**Comment by jreback** [comment] 2019-04-30 12:58
re-opening as not fixed by #26185

**Comment by NumberPiOso** [comment] 2022-02-08 16:15
I am trying to build a small reproducible example, I will leave it here in case it helps someone:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

n = 200
ages = np.random.choice(np.arange(0, 81), n)
outcome = np.random.choice(["Clinical", "Confirmed", "Discarded"], n)
df = pd.DataFrame({
    "conclusion": outcome,
    "age": ages
})
print(df)
#     conclusion  age
# 0    Discarded   74
# 1    Confirmed   63
# ...




counts = df.groupby(["conclusion", "age"]).size().unstack().fillna(0)
print(counts)
# age          0    1    2    3    4    5   ...   75   76   77   78   79   80
# conclusion                                ...                              
# Clinical    1.0  0.0  0.0  1.0  1.0  0.0  ...  1.0  2.0  0.0  2.0  1.0  0.0
# Confirmed   1.0  1.0  1.0  0.0  2.0  1.0  ...  0.0  1.0  1.0  0.0  1.0  1.0
# Discarded   0.0  1.0  1.0  1.0  1.0  2.0  ...  1.0  0.0  1.0  0.0  0.0  1.0


ax = counts.plot(kind='bar', stacked=True)
plt.show()
```

However the result is quite different in pandas version `1.5.0.dev0+305.g6a5cdf585d`
![image](https://user-images.githubusercontent.com/46936498/153026914-ec60c16a-024b-4ae6-bd45-ff2e1a1fe0ac.png)

**Comment by NumberPiOso** [comment] 2022-02-08 16:25
So I am trying to build a completely different example, more minimalistic to show the error, but everything is working fine for me:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
n = 80
df = pd.DataFrame({"Clinical": np.random.choice([0, 1, 2, 3], n),
                   "Confirmed": np.random.choice([0, 1, 2, 3], n),
                   "Discarded": np.random.choice([0, 1, 2, 3], n),
                   }, index=np.arange(0, n))

ax = df.plot(kind='bar', stacked=True)

```
produces
![image](https://user-images.githubusercontent.com/46936498/153029720-299777f9-4157-481d-830b-b0f1014e9c67.png)


if we try:
```python
ax.xticks(np.arange(0,80,10))
AttributeError: 'AxesSubplot' object has no attribute 'xticks'
```

but using 
```python
ax.set_xticks(np.arange(0,80,10))
```
will produce the desired result

![image](https://user-images.githubusercontent.com/46936498/153030274-929aad89-5c68-4625-b9e8-921445708278.png)


So I am not sure if this issue should be marked as information needed or if it is already solutioned. @jreback  and @mroeschke.

**Comment by mroeschke** [comment] 2022-02-08 17:19
@NumberPiOso thanks for investigating. If all appears well for your minimal example might be good to add your example as a unit test.

**Closed** 2022-02-10 00:07 UTC
Labels: Bug, Visualization
