### ISSUE TITLE
Missing <th> for index in notebook display of pd.DataFrame in 0.25.1

### ISSUE THREAD

**Issue by xflr6** [pandas-dev/pandas#28240] opened 2019-08-31 09:30 UTC
#### Code Sample, a copy-pastable example if possible

![screen](https://user-images.githubusercontent.com/6342379/64061988-c6820280-cbe1-11e9-8ae7-7bedd4828489.png)

#### Problem description

Since `0.25.1`, the row index ("A" and "B" in [2]) is not shown in boldface any more.

#### Expected Output

Same as in [3] (pre `0.25.1` output)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 7
machine          : AMD64
processor        : Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.17.1
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.13
pytest           : 5.1.2
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.8.0
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : 0.11.0
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.8
tables           : 3.5.2
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by simonjayhawkins** [comment] 2019-08-31 10:48
@xflr6 Thanks for the report. This is a duplicate of #28204

**Closed by simonjayhawkins** 2019-08-31 10:48 UTC
