### ISSUE TITLE
BUG: test_rolling_var_numerical_issues fails on 32-bit platforms

### ISSUE THREAD

**Issue by misuzu** [pandas-dev/pandas#55789] opened 2023-11-01 12:56 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
The issue is reproducible on 32-bit platforms using pandas tests suite (tested 2.1.1, 2.1.2 and main branch)
```

### Issue Description

`test_rolling_var_numerical_issues` fails on i686-linux and armv7l-linux

```
=========================== short test summary info ============================
FAILED tests/window/test_rolling.py::test_rolling_var_numerical_issues[var-1-values0] - AssertionError: Series are different
FAILED tests/window/test_rolling.py::test_rolling_var_numerical_issues[std-1-values1] - AssertionError: Series are different
FAILED tests/window/test_rolling.py::test_rolling_var_numerical_issues[var-2-values2] - AssertionError: Series are different
FAILED tests/window/test_rolling.py::test_rolling_var_numerical_issues[std-2-values3] - AssertionError: Series are different
= 4 failed, 176645 passed, 22922 skipped, 1658 xfailed, 91 xpassed, 6 warnings in 817.26s (0:13:37) =
```

[pandas-2.1.1-i686-linux.log](https://github.com/pandas-dev/pandas/files/13226947/pandas-2.1.1-i686-linux.log)

[pandas-2.1.1-armv7l-linux.log](https://github.com/pandas-dev/pandas/files/13226945/pandas-2.1.1-armv7l-linux.log)

### Expected Behavior

Tests suite doesn't fail on 32-bit platforms

### Installed Versions

i686-linux:
<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.6.final.0
python-bits         : 32
OS                  : Linux
OS-release          : 6.1.59
Version             : #1-NixOS SMP PREEMPT_DYNAMIC Thu Oct 19 21:08:58 UTC 2023
machine             : x86_64
processor           :
byteorder           : little
LC_ALL              : None
LANG                : uk_UA.UTF-8
LOCALE              : uk_UA.UTF-8

pandas              : 2.1.1
numpy               : 1.25.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : None
pip                 : None
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
</details>

armv7l-linux
<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.6.final.0
python-bits         : 32
OS                  : Linux
OS-release          : 6.1.60
Version             : #1-NixOS SMP Wed Oct 25 10:03:17 UTC 2023
machine             : aarch64
processor           :
byteorder           : little
LC_ALL              : None
LANG                : uk_UA.UTF-8
LOCALE              : uk_UA.UTF-8

pandas              : 2.1.1
numpy               : 1.25.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : None
pip                 : None
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</details>

**Comment by mroeschke** [comment] 2023-11-01 17:14
Thanks for the report. Duplicate of https://github.com/pandas-dev/pandas/issues/37398

**Closed by mroeschke** 2023-11-01 17:14 UTC
Labels: Bug, Needs Triage
