### ISSUE TITLE
BUG: DataFrame.query can not work well with string

### ISSUE THREAD

**Issue by yanyu2015** [pandas-dev/pandas#48391] opened 2022-09-05 02:40 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# example1
USERS = pd.DataFrame(
    {'email':['a@g.com','b@g.com','b@g.com','c@g.com','d@g.com']})
print (USERS)
#      email
# 0  a@g.com
# 1  b@g.com
# 2  b@g.com
# 3  c@g.com
# 4  d@g.com
EXCLUDE = pd.DataFrame(
    {'email':['a@g.com','d@g.com']})
print (EXCLUDE)
#      email
# 0  a@g.com
# 1  d@g.com

USERS.query("email == @EXCLUDE.email")

# example2
df11 = {'Purchase_Price': [23000000, 30000000, 26300000], 
       'NIY': [0.15, 0.08, 0.069],
       'Purchaser': ['1','JKK','JJK']}
df11 = pd.DataFrame(data=df11)
df11
df31 = {'Purchase_Price': [23000000, 50000000, 66600000], 
       'NewCol': ['1','JJK','C']}
df31 = pd.DataFrame(data=df31)
df31
df11.query("Purchaser == @df31.NewCol")
```

### Issue Description

```
# about example 1
ValueError: Can only compare identically-labeled Series objects
```
so why the example1 cannot work?
```
# about example 2
Purchase_Price	NIY	Purchaser
0	23000000	0.15	1
```

### Expected Behavior

the result of example 2 should be as follows:
```
Purchase_Price	NIY	Purchaser
0	23000000	0.15	1
1      26300000	0.069	JJK
```
Because "JJK" equals each other.

### Installed Versions

<details>
python           : 3.9.7.final.0
pandas           : 1.4.2
</details>

**Comment by ParfaitG** [comment] 2022-09-08 01:02
What is your main issue here? Why Example 1 errs out or undesired Example 2 result? See below explanation at the correct behavior of this method.

Example 1 error

In example 1, you are comparing a 5-row DataFrame to a 2-row DataFrame. So, the `DataFrame.query` call compares different length Series (5 values to 2 values). However, in example 2, you compare a 3-row DataFrame with a 3-row DataFrame. So the `DataFrame.query` call compares equal length Series of 3 values and hence no error is raised. The labeling mentioned in error refers to mismatched indexes.

Example 2 result

`DataFrame.query` is not `DataFrame.merge` where the latter scans rows for proper matching. Rather, the `query` call is comparing row to row (or index to index) and only the first row matches by position and value. Indeed, as [docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html) note, `DataFrame.loc` is first called. Even though both DataFrames share identically labeled indexes, the 'JJK' value resides at different index/row between the two DataFrames. Therefore, that row does not return as expected by method. In fact, move 'JJK' to last row of second DataFrame, then `query` will return your desired result.

**Comment by yanyu2015** [comment] 2022-09-08 01:32
thx, the key reason is **the query call is comparing row to row**.
So, if I want to get the expected result. What's the best practice?

**Comment by ParfaitG** [comment] 2022-09-10 00:38
It is unclear what you are trying to do. Best practice is to use the appropriate method for the job. `DataFrame.query` works best for simple logical filters not really for matching values across DataFrames. Consider `DataFrame.merge`, `DataFrame.join`, or `Series.isin` for this need:

```python
USERS.merge(EXCLUDE, on="email")

USERS.set_index("email").join(
    EXCLUDE.set_index("email"), how="inner"
)

USERS[USERS["email"].isin(EXCLUDE["email"].tolist())]
```

Actually, you can use `DataFrame.query` on a list variable:

```python
vals = EXCLUDE["email"].tolist()
USERS.query("email == @vals")
```

**Comment by mroeschke** [comment] 2024-07-16 22:00
Thanks for the report, but it seems like this may be the intended behavior so closing

**Closed by mroeschke** 2024-07-16 22:00 UTC
Labels: Bug, expressions, Needs Triage
