### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by xieyirmvb** [pandas-dev/pandas#55717] opened 2023-10-27 02:11 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

a = pd.DataFrame([['1'],['2'],['3']],columns=['sales'])
a_copy = a.copy()
a_copy.loc[:,'sales'] = pd.Series(a['sales'], dtype='float64')
a_copy.loc[:,'sales'] = pd.Series(a['sales'], dtype='float64[pyarrow]')
```

### Issue Description

Set value for an entire column not working
Using   a_copy.loc[:,'sales'] 
![image](https://github.com/pandas-dev/pandas/assets/26783716/e757d63f-2e93-4902-a94e-3fe58b27979b)

![image](https://github.com/pandas-dev/pandas/assets/26783716/6a454112-dc13-40e1-a1c7-8f74e5adc790)

![image](https://github.com/pandas-dev/pandas/assets/26783716/5ce23731-e0a9-4845-974f-5cdbee3ea7a3)

### Expected Behavior

Expected
![image](https://github.com/pandas-dev/pandas/assets/26783716/d79a561a-4d4b-46ec-8200-afa1c3558dd6)

### Installed Versions

INSTALLED VERSIONS
------------------
commit              : a60ad39b4a9febdea9a59d602dad44b1538b0ea5
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.22621
machine             : AMD64
processor           : Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : Chinese (Simplified)_China.936
pandas              : 2.1.2
numpy               : 1.24.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.4.0
hypothesis          : None
sphinx              : 5.0.2
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : None
pymysql             : 1.4.6
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.5
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.4.0
gcsfs               : None
matplotlib          : 3.7.2
numba               : 0.57.1
numexpr             : 2.8.4
odfpy               : None
openpyxl            : 3.0.10
pandas_gbq          : None
pyarrow             : 11.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : 2023.4.0
scipy               : 1.11.1
sqlalchemy          : 1.4.39
tables              : 3.8.0
tabulate            : 0.8.10
xarray              : 2023.6.0
xlrd                : None
zstandard           : 0.19.0
tzdata              : 2023.3
qtpy                : 2.2.0
pyqt5               : None

**Comment by xieyirmvb** [comment] 2023-10-27 02:16
the second is wrong  this is correct：
![image](https://github.com/pandas-dev/pandas/assets/26783716/a8fb47af-e5b4-4c0c-b1fe-8749093d5fed)

**Comment by lukemanley** [comment] 2023-10-29 11:10
duplicate of #52593

**Comment by mroeschke** [comment] 2023-11-21 18:50
Closing as a duplicate

**Closed by mroeschke** 2023-11-21 18:50 UTC
Labels: Bug, Duplicate Report
