### ISSUE TITLE
Bug in regex engine

### ISSUE THREAD

**Issue by ianhbell** [pandas-dev/pandas#27592] opened 2019-07-25 18:04 UTC
#### Code Sample

```python
# This one fails
import pandas as pd
import numpy as np
import io
data = io.StringIO(r"""401.000000  383.1216 0.0000 0.0000 0.5140 0.4860   MASLENN 116616 NH3N2         1
401.000000  383.1216 0.0000 0.0000 0.5140 0.4860   MASLENN 116616 NH3N2         1""")
df = pd.read_csv(data, sep=r'\w+', engine='python', names=['T/K','p/MPa','x0','x1','y0','y1','ref','refnum','pair','index'])
print(np.log10(df['p/MPa']))
```
with error:

```
Traceback (most recent call last):
  File "D:\Code\bug.py", line 7, in <module>
    print(np.log10(df['p/MPa']))
AttributeError: 'str' object has no attribute 'log10'
```

```python
# This one succeeds
import pandas as pd
import numpy as np
import io
data = io.StringIO(r"""401.000000,383.1216,0.0000,0.0000,0.5140,0.4860,MASLENN,116616,NH3N2,1
401.000000,383.1216,0.0000,0.0000,0.5140,0.4860,MASLENN,116616,NH3N2,1""")
df = pd.read_csv(data, sep=',', names=['T/K','p/MPa','x0','x1','y0','y1','ref','refnum','pair','index'])
print(np.log10(df['p/MPa']))
```

#### Problem description

There is a very odd bug in pandas regarding the use of the python engine in concert with a regex.  Somehow this combination corrupts numpy <-> pandas interaction; note how python thinks that numpy is a string above.  I finally was able to put together a runnable example showing the problem as detailed above.  When I modify my example to use comma delimiters instead, there is no corruption of numpy

#### Output of pd.show_versions()

``` python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.4
pytest: None
pip: 19.0.3
setuptools: 27.2.0
Cython: 0.29.10
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.7.2
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.0
openpyxl: 2.4.8
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: 4.1.1
bs4: 4.7.1
html5lib: 0.999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

**Comment by WillAyd** [comment] 2019-07-25 18:08
Do you mean to be using the whitespace sequence for your regex?  This works fine:

```python
df = pd.read_csv(data, sep=r'\s+', engine='python', names=['T/K','p/MPa','x0','x1','y0','y1','ref','refnum','pair','index'])
```

**Comment by ianhbell** [comment] 2019-07-25 18:11
You're right about that point, I do indeed mean r'\s+', but that doesn't take away from the fact that with the wrong delimiter I corrupt numpy somehow

**Comment by WillAyd** [comment] 2019-07-25 18:13
You aren't corrupting anything you are just building a frame of all string data with the wrong delimiter. Numpy is complaining that you can't take the log of a string

**Comment by ianhbell** [comment] 2019-07-25 18:13
That error message is very confusing though....

**Comment by ianhbell** [comment] 2019-07-25 18:15
I'm not so sure about that either, because df.info() says that field ``p/MPa`` is a float:
```
RangeIndex: 2 entries, 0 to 1
Data columns (total 10 columns):
T/K       2 non-null float64
p/MPa     2 non-null float64
x0        2 non-null float64
x1        2 non-null float64
y0        2 non-null float64
y1        2 non-null float64
ref       2 non-null object
refnum    2 non-null int64
pair      2 non-null object
index     2 non-null int64
dtypes: float64(6), int64(2), object(2)
memory usage: 240.0+ bytes
```

**Comment by WillAyd** [comment] 2019-07-25 18:17
I think you are mixing frames. Your first example produces the following

```python
>>> import pandas as pd
>>> import numpy as np
>>> import io
>>> data = io.StringIO(r"""401.000000  383.1216 0.0000 0.0000 0.5140 0.4860   MASLENN 116616 NH3N2         1
... 401.000000  383.1216 0.0000 0.0000 0.5140 0.4860   MASLENN 116616 NH3N2         1""")
>>> df = pd.read_csv(data, sep=r'\w+', engine='python', names=['T/K','p/MPa','x0','x1','y0','y1','ref','refnum','pair','index'])
>>> df.info()
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 2 entries, (nan, .,   , .,  , .,  ) to (nan, .,   , .,  , .,  )
Data columns (total 10 columns):
T/K       2 non-null object
p/MPa     2 non-null object
x0        2 non-null object
x1        2 non-null object
y0        2 non-null object
y1        2 non-null object
ref       2 non-null object
refnum    2 non-null object
pair      2 non-null object
index     0 non-null float64
dtypes: float64(1), object(9)
memory usage: 334.0+ bytes
>>> df['p/MPa']
NaN  .      .     .
```

**Comment by WillAyd** [comment] 2019-07-25 18:18
Closing as not a bug (just a slight misunderstanding of the regex). If you have further usage questions give StackOverflow a shot as its better oriented towards Q&A

**Closed by WillAyd** 2019-07-25 18:18 UTC
Labels: Usage Question

**Comment by ianhbell** [comment] 2019-07-25 18:19
Ok, now I see what you mean, but the error message is very obtuse, and I've spent many hours trying to debug this.

**Comment by ianhbell** [comment] 2019-07-25 18:20
I still think this is a bug in pandas, in that it doesn't provide a more explicit message about what the problem is.  It seems like a numpy bug, but it is a pandas use bug

**Comment by WillAyd** [comment] 2019-07-25 18:26
Hmm OK the error message is different on master. Is that not more explicit?

```python-traceback
AttributeError: 'str' object has no attribute 'log10'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-1-fac0dcd4d4ef> in <module>
      5 401.000000  383.1216 0.0000 0.0000 0.5140 0.4860   MASLENN 116616 NH3N2         1""")
      6 df = pd.read_csv(data, sep=r'\w+', engine='python', names=['T/K','p/MPa','x0','x1','y0','y1','ref','refnum','pair','index'])
----> 7 print(np.log10(df['p/MPa']))

~/clones/pandas/pandas/core/series.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    849
    850         inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
--> 851         result = getattr(ufunc, method)(*inputs, **kwargs)
    852         if len(set(names)) == 1:
    853             # we require names to be hashable, right?

TypeError: loop of ufunc does not support argument 0 of type str which has no callable log10 method
```

If you have a concrete proposal on how to improve feel free to open a separate issue, but as far as this one goes there is no bug

**Comment by ianhbell** [comment] 2019-07-25 18:28
master is *exactly* what I'm looking for.  Are there nightly wheels being built automatically?

**Comment by WillAyd** [comment] 2019-07-25 18:29
That same behavior is also available on 0.25 which you can install from normal channels

**Comment by ianhbell** [comment] 2019-07-25 18:33
But conda is stuck at 0.24: https://anaconda.org/anaconda/pandas

**Comment by TomAugspurger** [comment] 2019-07-25 20:05
Conda-forge has 0.25. Defaults should be updated this week.
