### ISSUE TITLE
ENH: read_hdf() - support for generic buffers has not been implemented

### ISSUE THREAD

**Issue by lucasthahn** [pandas-dev/pandas#36392] opened 2020-09-16 01:03 UTC
#### Is your feature request related to a problem?

As of the latest verison of master, `read_hdf()` does not support generic buffers as input, and raises a `NotImplementedError` if one is passed in. This stems from line 374 of `pandas/pandas/io/pytables.py`. 

#### Describe the solution you'd like

There's already a nice stub in which to insert this code; somebody just needs to implement it. If nobody is currently working on this, I'm happy to give a try myself! 

#### API breaking implications

Shouldn't break anything; just would be adding more functionality.

#### Describe alternatives you've considered

For my specific use case I've found a workaround which involves not writing to a generic buffer, but if `pandas` were to have this functionality, my own code would certainly be more elegant.

#### Additional context

As I said above, happy to try to do this myself - seems like a good first contribution and not really any potential to break anything else! But if someone's already working on this, please let me know and I will spare myself the effort. Thanks!

**Comment by phofl** [comment] 2020-09-16 01:38
Hey, thanks for your report. This is a duplicate of #31902. Seems like no one is working on this, so you could give it a try if you like. 

Closing this.

**Closed by phofl** 2020-09-16 01:38 UTC
Labels: Enhancement, Needs Triage
