### ISSUE TITLE
to_pickle doesn't support file handles

### ISSUE THREAD

**Issue by jluttine** [pandas-dev/pandas#29790] opened 2019-11-22 11:41 UTC
`to_pickle` supports only file names, not file handles. See: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html

Is there some particular reason for this? `to_csv` does support file handles so I would have expected `to_pickle` to support too.

To reproduce:

```
>>> with open("tmp.p", 'w') as fp:
...     pd.Series([1,2,3]).to_pickle(fp)

ValueError: Unrecognized compression type: infer
```

**Comment by jluttine** [comment] 2019-11-22 11:43
The reason I'd like to have support for file handles is that then I can explicitly flush.

**Comment by jreback** [comment] 2019-11-22 12:03
duplicate of https://github.com/pandas-dev/pandas/issues/26237

nothing stopping this, submit a PR today!

**Closed by jreback** 2019-11-22 12:03 UTC
