### ISSUE TITLE
Timedeltas cast as datetime in DataFrames

### ISSUE THREAD

**Issue by nbonnotte** [pandas-dev/pandas#15560] opened 2017-03-03 15:57 UTC
#### Code Sample, a copy-pastable example if possible

```python
In [10]: pandas.DataFrame([[datetime.datetime(2017, 1, 1)]]) - datetime.datetime(2001, 1, 1)
Out[10]: 
           0
0 1986-01-01

In [11]: pandas.Series([datetime.datetime(2017, 1, 1)]) - datetime.datetime(2001, 1, 1)
Out[11]: 
0   5844 days
dtype: timedelta64[ns]
```
#### Problem description

For dataframe, the value "5844 days" is cast as a datetime, so it becomes "1970-01-01 + 5844 days = 1986-01-01"

#### Expected Output

In [10]: pandas.DataFrame([[datetime.datetime(2017, 1, 1)]]) - datetime.datetime(2001, 1, 1)
Out[10]: 
           0
0 5844 days

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: 211ecd5d829e6ff9019261680f1d4e6f1b193a13
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-59-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.0+527.g211ecd5
pytest: 3.0.6
pip: 9.0.1
setuptools: 22.0.0
Cython: 0.24
numpy: 1.11.0
scipy: 0.17.1
xarray: None
IPython: 4.2.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by chris-b1** [comment] 2017-03-03 16:07
Yep, looks buggy.

**Comment by jreback** [comment] 2017-03-03 16:10
yes, but dupe of this: https://github.com/pandas-dev/pandas/issues/8554

**Comment by jreback** [comment] 2017-03-03 16:10
of course PR's to fix welcome!

**Closed by jreback** 2017-03-03 16:10 UTC
Labels: Bug, Timedelta, Timeseries
