### ISSUE TITLE
BUG: Pandas extension Int dtypes break dataframe interchange protocol

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#56777] opened 2024-01-08 16:24 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> import pandas as pd
>>> df = pd.DataFrame([[1,]], columns=["a"], dtype="Int64")
>>> df.__dataframe__().get_column(0).get_buffers()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/willayd/clones/pandas/pandas/core/interchange/column.py", line 247, in get_buffers
    "data": self._get_data_buffer(),
  File "/home/willayd/clones/pandas/pandas/core/interchange/column.py", line 270, in _get_data_buffer
    if self.dtype[0] in (
  File "properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "/home/willayd/clones/pandas/pandas/core/interchange/column.py", line 128, in dtype
    return self._dtype_from_pandasdtype(dtype)
  File "/home/willayd/clones/pandas/pandas/core/interchange/column.py", line 147, in _dtype_from_pandasdtype
    byteorder = dtype.byteorder
AttributeError: 'Int64Dtype' object has no attribute 'byteorder'
```

### Issue Description

Integral extension types should still be serializable via the interchange protocol

### Expected Behavior

Should return proper buffers

### Installed Versions

on main

**Comment by MarcoGorelli** [comment] 2024-01-31 14:05
thanks Will for reporting this - going to close as duplicate of  #55069 , there's a fix open anyway

**Closed by MarcoGorelli** 2024-01-31 14:05 UTC
Labels: Bug, Interchange
