### ISSUE TITLE
BUG:I am using Latest python 3.8 ,the pip install pandas is working and is successful but showing an when importing it is showing an error, need help

### ISSUE THREAD

**Issue by canaraphil** [pandas-dev/pandas#33305] opened 2020-04-05 17:02 UTC
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by canaraphil** [comment] 2020-04-05 17:07
![image](https://user-images.githubusercontent.com/63202754/78504984-f0119680-778d-11ea-8c8d-9a1b035fcd7a.png)

**Comment by mroeschke** [comment] 2020-04-05 17:38
Thanks for the report. Looks like a duplicate of https://github.com/pandas-dev/pandas/issues/32857

**Closed by mroeschke** 2020-04-05 17:38 UTC
Labels: Bug, Needs Triage
