### ISSUE TITLE
ENH: df.query has no identity, can we set it to df.query("")?

### ISSUE THREAD

**Issue by gabrieldernbach** [pandas-dev/pandas#53867] opened 2023-06-26 20:04 UTC
### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I couldn't find an identity operator for `df.query`. If there is one please let me know.

Pandas `df.query` is a very flexible interface for programmatically evaluating a set of conditions. 
However I tend to always wrap it to implement the fallback to self.
```subset = df.query(condition) if condition else df```

### Feature Description

Can we have `df.query("")` return the `df` so we have a proper identity (providing no conditions should perform no filtering)?

### Alternative Solutions

Continue manual wrapping

**Comment by rhshadrach** [comment] 2023-06-26 22:16
Thanks for the request. Closing as a duplicate of #37941.

**Closed by rhshadrach** 2023-06-26 22:16 UTC
Labels: Enhancement, Needs Triage
