### ISSUE TITLE
BUG: Numexpr engine - Name of the returned series dropped when using user function in `DataFrame.eval`

### ISSUE THREAD

**Issue by domsmrz** [pandas-dev/pandas#58069] opened 2024-03-29 09:58 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
def rename_to_foo(s):
  return s.rename('foo')
df = pd.Series([1,2], name='bar').to_frame()
sr = df.eval('@rename_to_foo(bar)', engine='numexpr')
print(sr.name)

## Different example:
import numpy as np
floor = np.floor
df = pd.Series([0.2, 1.5, 2.8], name='baz').to_frame
sr = df.eval('@floor(baz)', engine='numexpr')
print(sr.name)
```

### Issue Description

When running with `numexpr` engine, the name of the returned series (`sr`) is `None` even though it should be `foo` in the first example and `baz` in the second. This creates discrepancies between using `my_func(df['foo'])` and `df.eval('@my_func(foo)')` where the former preserves the correct name.

Note that this is an issue when using `engine='numexpr'` only. Using `engine='python'` preserves the `name`.

### Expected Behavior

Names of the series to be preserved (i.e., `sr.name == "foo"` in the first case and `sr.name  == "baz"` in the second).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.11.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.6.13-1rodete3-amd64
Version          : #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1rodete3 (2024-03-04)
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2023.3.post1
dateutil         : 2.8.2
setuptools       : 68.1.2
pip              : 23.3
Cython           : 3.0.8
pytest           : 7.4.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 5.1.0
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.20.0
pandas_datareader: None
bs4              : 4.12.3
bottleneck       : 1.3.5
brotli           : 1.1.0
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.6.3
numba            : 0.57.1
numexpr          : 2.9.0
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : 
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by asishm** [comment] 2024-03-29 17:13
Looks like this only happens when `numexpr` is installed. Without `numexpr`, I see the series name is preserved.

**Comment by domsmrz** [comment] 2024-04-02 09:02
Thanks for pointing that out @asishm . It seems like that is closer to the issue, i.e., using `eval` with `engine='python'` "fixes" the issue on Linux. So it is probably the issue of inconsistencies between the engines rather that OSes (?)

**Comment by domsmrz** [comment] 2024-04-02 18:57
I've updated the bug name and description, to reflect the fact that this is not directly os-dependent issue, but directly related to the used `engine`.

**Comment by sofiasimass** [comment] 2024-04-04 07:59
take

**Comment by domsmrz** [comment] 2024-04-24 21:54
take

**Comment by domsmrz** [comment] 2024-04-25 20:53
Just found out that this is actually duplicate of #10239

**Comment by mroeschke** [comment] 2024-04-29 17:42
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/10239

**Closed by mroeschke** 2024-04-29 17:42 UTC
Labels: Bug, expressions
