### ISSUE TITLE
`duration[ns][pyarrow]` missing `.dt` attribute

### ISSUE THREAD

**Issue by mattharrison** [pandas-dev/pandas#56269] opened 2023-11-30 23:21 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
>>> classes = ['cs106', 'cs150', 'hist205', 'hist206', 'hist207']
>>> start_dates = (pd.Series(['2015-03-08',
...  '2015-03-08',
...  '2015-03-09',
...  '2015-03-09',
...  '2015-03-11'], dtype='datetime64[ns]', index=classes)
...  .astype('timestamp[ns][pyarrow]'))
>>> classes = ['cs106', 'cs150', 'hist205', 'hist206', 'hist207']
>>> start_dates = (pd.Series(['2015-03-08',
...  '2015-03-08',
...  '2015-03-09',
...  '2015-03-09',
...  '2015-03-11'], dtype='datetime64[ns]', index=classes)
...  .astype('timestamp[ns][pyarrow]'))   
>>> duration = (end_dates - start_dates)
>>> duration.dt
```

### Issue Description

The pandas 1 era `timedelta[ns]` type had a `.dt` accessor to do math on the series.

### Expected Behavior

Similar behavior to Pandas 1.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.13.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 21.6.0
Version             : Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : en_US.UTF-8
LANG                : None
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.23.5
pytz                : 2023.3
dateutil            : 2.8.2
setuptools          : 67.6.1
pip                 : 23.2.1
Cython              : 3.0.4
pytest              : 7.2.0
hypothesis          : 6.81.2
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : 3.1.2
lxml.etree          : 4.9.2
html5lib            : 1.1
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.8.0
pandas_datareader   : None
bs4                 : 4.11.1
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.3.0
gcsfs               : None
matplotlib          : 3.6.2
numba               : 0.56.4
numexpr             : 2.8.4
odfpy               : None
openpyxl            : 3.0.10
pandas_gbq          : None
pyarrow             : 13.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.10.0
sqlalchemy          : 2.0.21
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : 2.0.1
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

## df.strftime

Selection deleted

</details>

**Comment by mroeschke** [comment] 2023-11-30 23:22
Thanks closing as a duplicate of https://github.com/pandas-dev/pandas/issues/52284

**Closed by mroeschke** 2023-11-30 23:22 UTC
Labels: Bug, Needs Triage
