### ISSUE TITLE
incorrect calculation of centered moving averages for even length series

### ISSUE THREAD

**Issue by simonm3** [pandas-dev/pandas#14425] opened 2016-10-14 11:39 UTC
For even numbered periods the centered moving average is calculated incorrectly. Suppose the period length is 5. Then the center of 5 periods is 3. However if the period length is 4 then the center of the period is 2.5. The value at index 3 should be the average of the values at 2.5 and 3.5. Pandas is showing the 2.5 value at 3 which is incorrect.

EXAMPLE:
a=pd.Series(range(1,6), index=range(1,6))
a.rolling(4, center=True).mean()

1    NaN
2    NaN
3    2.5
4    3.5
5    NaN

**Comment by jreback** [comment] 2016-10-14 20:43
center is a very funny beast. The computation is done then the results are shifted. To be honest we should just remove this.

**Comment by jreback** [comment] 2016-10-14 20:45
actually this is a duplicate of #2953. has been open a long time.

**Closed by jreback** 2016-10-14 20:45 UTC
Labels: API Design, Needs Discussion, Numeric

**Comment by simonm3** [comment] 2016-10-14 22:25
This is not the same issue. The one you refer to is apparently affecting
only the edge values. I am saying all values are shifted half an index so
wrong.

Also it is easy to fix. It is just an test for length even and then
averaging each consecutive pair. And the suggestion it might be slower is
bizarre. It is slower to calculate 2+2 =4 than to just set it to 1 but that
would be incorrect.

**Comment by simonm3** [comment] 2016-10-14 22:27
And SPSS, sas, and minitab all calculate centred moving averages correctly.

**Comment by chris-b1** [comment] 2016-10-14 23:29
@simonm3  - there's a lot going on in that issue, but changing the centered mean was part of it - this reference, which I think is the approach you expect?
http://www.itl.nist.gov/div898/handbook/pmc/section4/pmc422.htm

I'm guessing centered mean isn't used that often, but if there is a standard approach for double smoothing an even window, and you would like to submit a PR to support that, I think that would be great.

**Comment by chris-b1** [comment] 2016-10-14 23:39
I guess you can also fairly easily solve it like this?
```
s.rolling(4, center=True).mean().rolling(2).mean()
```

**Comment by pkch** [comment] 2018-07-17 08:41
It would have to be:

`a.rolling(4, center=True).mean().rolling(2).mean().shift(-1)`

The current calculation is just plain wrong, it's simply not centered.

Also, IMHO, the issue linked to this as a duplicate really is not about even-sized centered windows, it's about some more complex issues.

Given how easy it is to fix this, perhaps it's worth reopening it, so someone can fix it with a small PR?
