### ISSUE TITLE
BUG: DataFrame.nlargest() returns incorrect result when DataFrame has non-unique index

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas#14846] opened 2016-12-09 21:01 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df=pd.DataFrame({'variable': ['a','a','b','b','c','c'],
                 'value' : [1000,2000,10,20,100,200]},
                 index=[1,2]*3)
df.nlargest(3,'value')

```
#### Problem description

The result should only have 3 rows.  If the index has unique values, it is correct.  But when the index has duplicate values, the incorrect result is produced.

The example produces the following output:
```
   value variable
2   2000        a
2   2000        a
1   1000        a
2    200        c
2    200        c
1    100        c
2     20        b
2     20        b
1     10        b
```

#### Expected Output
```
   value variable
2  2000       a
1  1000       a
2  200        c
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.0
nose: None
pip: 8.1.2
setuptools: 27.2.0
Cython: None
numpy: 1.11.2
scipy: None
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.5.1
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.8
boto: None
pandas_datareader: None
</details>

**Comment by chris-b1** [comment] 2016-12-09 21:17
This looks to be a duplicate of #13412 - which is fixed on master

**Closed** 2016-12-09 21:25 UTC

**Comment by gordonda** [comment] 2017-02-21 13:02
I have a similar problem with a slight change to the example above
```python
df=pd.DataFrame({'variable': ['a','a','b','b','c','c'],
                 'value' : [1000,2000,1000,20,100,200]},
                 index=[1,2]*3)
df.nlargest(3, 'value')
```

An expected output would be
```   
    value variable
2   2000        a
1   1000        a
1   1000        b
```

Instead it is

```
   value variable
2   2000        a
1   1000        a
1   1000        b
1   1000        a
1   1000        b
```

It seems that duplicate values in the column specified in nlargest leads to this behaviour

**Comment by jreback** [comment] 2017-02-21 14:44
@gordonda see #15297 which is the same
