### ISSUE TITLE
Constructor reorders columns and rows for (lists or dicts) of dicts

### ISSUE THREAD

**Issue by soerenwolfers** [pandas-dev/pandas#26587] opened 2019-05-31 08:27 UTC
#### Code Sample

```python
import pandas as pd
print(pd.DataFrame({0:{'B':'First row','A':'Second row'}}))
print(pd.DataFrame([{'B':'First column','A':'Second column'}]))
```
Results in 
```
            0
A  Second row
B   First row
               A             B
0  Second column  First column
```
#### Problem description

The two constructor calls above reorder the rows or columns, respectively, alphabetically, so the row or column, respectively, indexed by 'A' always comes first. 

#### Expected Output

The order of the dict should be preserved now that Python dictionaries are officially ordered.
Hence, the row or column, respectively, indexed by 'A' should come second.

I don't need to make an argument for this, because pandas itself has already decided so:
https://pandas.pydata.org/pandas-docs/version/0.23.0/whatsnew.html#whatsnew-0230-api-breaking-dict-insertion-order

#### Versions

Tested with pandas 0.24.2 and Python 3.7

**Comment by WillAyd** [comment] 2019-05-31 12:35
This is a duplicate of quite a few issues.  The problem with this is that there is no such thing as guaranteed ordering in two dimensions.

**Comment by WillAyd** [comment] 2019-06-02 02:55
Closing as a duplicate of #24859

**Closed by WillAyd** 2019-06-02 02:55 UTC

**Comment by soerenwolfers** [comment] 2019-06-02 09:59
I don't understand 

> There is no such thing as guaranteed ordering in two dimensions.

 Do you mean

> There may not be a unique ordering if multiple dicts are passed in.

 If so, what prevents pandas from using the unique order if it exists?
