### ISSUE TITLE
df.plot with two plots in the same axes and 2nd one is line plot makes different chart between 0.23.4 and 0.25.0

### ISSUE THREAD

**Issue by wh243s** [pandas-dev/pandas#27686] opened 2019-08-01 07:47 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('iris.csv')
dfg = df.groupby('species').mean()
dfg['swratio'] = dfg.sepal_width / dfg.sepal_length

fig, ax = plt.subplots(figsize=(10, 6))
dfg[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].plot.bar(ax=ax, rot=0, stacked=False)
dfg[['swratio']].plot.line(label='Sepal Width Ratio', 
                 ax=ax, secondary_y=True, mark_right=False, 
                 rot=0, marker='o', markersize=3, color='c')
ax.grid(True)
pngfile = 'Output.png'
fig = plt.gcf()
fig.savefig(pngfile, bbox_inches = 'tight', dpi=100)
```
#### Problem description

dataframe.plot with secondary_y=True makes different chart between 0.23.4 and 0.25.0 as attached.
![GeneratedFromPahdas0 23 4](https://user-images.githubusercontent.com/26564474/62275057-13a47480-b47c-11e9-8020-dc137be70aa6.png)
![GeneratedFromPahdas0 25 0](https://user-images.githubusercontent.com/26564474/62275058-143d0b00-b47c-11e9-8ef4-8152bfda8f71.png)

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment] 2019-08-05 16:17
@wh243s can you debug to figure out what is going on?

**Comment by charlesdong1991** [comment] 2019-08-05 19:42
this does not look like caused by `secondary_y` though

**Comment by wh243s** [comment] 2019-08-06 01:03
I've tried three different parameters on 0.25.0.
1. dfg[['swratio']].plot.line(ax=ax, secondary_y=True)
2. dfg[['swratio']].plot.line(ax=ax)
3. dfg[['swratio']].plot.line()

The attached are the results and csv being used.
![1  GeneratedFromPahdas0 25 0_ax=ax, secondary_y=True](https://user-images.githubusercontent.com/26564474/62503804-c7b54f00-b830-11e9-9d8e-15f8ac19f50b.png)
![2  GeneratedFromPahdas0 25 0_plot line(ax=ax)](https://user-images.githubusercontent.com/26564474/62503805-c84de580-b830-11e9-80d0-f4ce5b4b1771.png)
![3  GeneratedFromPahdas0 25 0_plot line()](https://user-images.githubusercontent.com/26564474/62503806-c84de580-b830-11e9-9cc8-58efc10e89f9.png)

[iris _renamed_from_csv.txt](https://github.com/pandas-dev/pandas/files/3469904/iris._renamed_from_csv.txt)

**Comment by wh243s** [comment] 2019-08-06 01:08
3. dfg[['swratio']].plot.line() has two chart in png and only the last one shows.  The attached is the first one.
![GeneratedFromPahdas0 25 0_plot line()_2](https://user-images.githubusercontent.com/26564474/62504141-2202df80-b832-11e9-90d4-1a8ff8ef981a.png)

**Comment by wh243s** [comment] 2019-08-06 05:39
When line and bar charts are switched, it looks fine.

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('iris.csv')
dfg = df.groupby('species').mean()
dfg['swratio'] = dfg.sepal_width / dfg.sepal_length

fig, ax = plt.subplots(figsize=(10, 6))
dfg[['swratio']].plot.line(ax=ax, color='c', rot=0)
dfg[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].plot.bar(ax=ax, secondary_y=True, rot=0)
ax.grid(True)
plt.title('plot.bar(ax=ax, secondary_y=True, rot=0)')
pngfile = 'GeneratedFromPahdas0.25.0_switched_line_and_bar.png'
fig = plt.gcf()
fig.savefig(pngfile, bbox_inches = 'tight', dpi=100)
![GeneratedFromPahdas0 25 0_switched_line_and_bar](https://user-images.githubusercontent.com/26564474/62513707-e4b14880-b857-11e9-8e53-2cd94c5fa14f.png)

**Comment by wh243s** [comment] 2019-08-06 07:23
It happens when the second chart is the line chart in the same axes.

**Comment by arthurire** [comment] 2019-08-08 03:09
@TomAugspurger [https://github.com/pandas-dev/pandas/issues/27796](Issue 27796). Same issue. This also happens when I use seaborn to plot a heatmap.

**Comment by TomAugspurger** [comment] 2019-08-08 11:00
You're saying https://github.com/pandas-dev/pandas/issues/27796 is a duplicate of this?

**Comment by arthurire** [comment] 2019-08-08 12:16
> You're saying #27796 is a duplicate of this?

I guess so.

**Comment by TomAugspurger** [comment] 2019-08-08 16:23
Ok I'll close that one then.

**Closed** 2019-08-20 14:18 UTC
Labels: Visualization

**Comment by ryanrolds** [comment] 2019-11-08 17:38
The fix to this causes broader limits set were prior to calls to pandas.DataFrame.plot.(line|area) to narrow the plot. The fix is to manually set the desired axis after the calls, but it was still a bit of a surprise to have it narrow the x-axis after the was specifically set larger so that projection lines (pyplot.axvline) would be visible.
