### ISSUE TITLE
BUG: read_json returns wrong value for big integer

### ISSUE THREAD

**Issue by mle-els** [pandas-dev/pandas#33766] opened 2020-04-24 16:16 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

---

#### Code Sample, a copy-pastable example

```bash
$ cat first-line.json
{"col":"72057594038135102"}
```

```python
>>> pd.read_json("first-line.json", lines=True)
                 col
0  72057594038135104
>>> pd.read_json("first-line.json", lines=True, dtype=False)
                 col
0  72057594038135102
```

#### Problem description

`pd.read_json()` silently returns a wrong value when reading a big integer. This creates a problem when the integers are used as unique IDs.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 17.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by jschendel** [comment] 2020-04-24 16:55
This is a duplicate of #20608 and is caused by an intermediate conversion to float:
```python
In [1]: int(float(72057594038135102))
Out[1]: 72057594038135104
```

**Closed by jschendel** 2020-04-24 16:55 UTC
Labels: Bug, Needs Triage
