### ISSUE TITLE
Unable to use lambda function in pandas NamedAgg function

### ISSUE THREAD

**Issue by allen-q** [pandas-dev/pandas#27914] opened 2019-08-14 02:18 UTC
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({'kind': ['cat', 'dog', 'cat', 'dog'],
                         'height': [9.1, 6.0, 9.5, 34.0],
                         'weight': [7.9, 7.5, 9.9, 198.0]})

# using lambda with the new NamedAgg function doesn't work
(
    df.groupby(by='kind')
    .agg(height_sqr_min=pd.NamedAgg(column='height', aggfunc=lambda x: np.min(x**2)), 
         height_max=pd.NamedAgg(column='height', aggfunc='max'),
         weight_max=pd.NamedAgg(column='weight', aggfunc='max')
        )
)

# using lambda with implicit NamedAgg function doesn't work either
(
    df.groupby(by='kind')
    .agg(height_sqr_min=('height', lambda x: np.min(x**2)), 
         height_max=('height', 'max'),
         weight_max=('weight', 'max'),
        )
)
```
#### Problem description

NamedAgg function introduced in pandas 0.25 doesn't seem to work with lambda functions.

#### Expected Output

| kind|height_sqr_min |  height_max |weight_max|
|----------|:-------------:|------:|------:|
| cat |  82.81 | 9.5 |9.9 |
| dog|  36.00 |  34.0 |198.0 |

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.0
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.5
tables           : 3.5.2
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
</details>

**Comment by TomAugspurger** [comment] 2019-08-14 13:26
Duplicate of https://github.com/pandas-dev/pandas/issues/27519. There's some suggestions there, if you're interested in working on this.

**Closed by TomAugspurger** 2019-08-14 13:26 UTC
