### ISSUE TITLE
to_sql to postgres database，error shows bug on insert statement

### ISSUE THREAD

**Issue by zhaopansong** [pandas-dev/pandas#24425] opened 2018-12-25 10:08 UTC
#### Code Sample, a copy-pastable example if possible
engine = create_engine('postgresql://xx@xxxxxx:xxxxx/postgres')
re.to_sql('c_s_f_c',con=engine,schema='nlp_share',if_exists='append',index=False)

#### Problem description
The first few lines of error log are：
ProgrammingError: (psycopg2.ProgrammingError) column "FACTOR_CONF_SN" of relation "c_s_f_c" does not exist
LINE 1: INSERT INTO nlp_share.c_s_f_c ("FACTOR_CONF_SN...
                                       ^
 [SQL: 'INSERT INTO nlp_share.c_s_f_c ("FACTOR_CONF_SN", "PARENT_SN", "PARENT_NAME", "FACTOR_LVL", "FACTOR_COLUMN", "FACTOR_NAME", "HIGH", "LOW", "IS_DISPLAY", "DESCRIPTION") VALUES (%(FACTOR_CONF_SN)s, %(PARENT_SN)s, %(PARENT_NAME)s, %(FACTOR_LVL)s, %(FACTOR_COLUMN)s, %(FACTOR_NAME)s, %(HIGH)s, %(LOW)s, %(IS_DISPLAY)s, %(DESCRIPTION)s)'] [parameters:....]

I notice the sql  statement automatically add "" on variable names such as "PARENT_SN", which is not how we usually write. I think that is the problem because when I write in loop mode and drop quotes, it's working:

insert='INSERT INTO nlp_share.c_s_f_c (FACTOR_CONF_SN, PARENT_SN,PARENT_NAME, FACTOR_LVL, FACTOR_COLUMN, FACTOR_NAME, HIGH, LOW, IS_DISPLAY, DESCRIPTION) VALUES (%(FACTOR_CONF_SN)s, %(PARENT_SN)s, %(PARENT_NAME)s, %(FACTOR_LVL)s, %(FACTOR_COLUMN)s, %(FACTOR_NAME)s, %(HIGH)s, %(LOW)s, %(IS_DISPLAY)s, %(DESCRIPTION)s)'
curs2=conn2.cursor()
curs2.executemany(insert,re.to_dict('records'))
conn2.commit()

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.6.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None

pandas: 0.23.3
pytest: 3.6.2
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.3
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.5
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.2
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: 4.2.2
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.8
pymysql: None
psycopg2: 2.7.5 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by jbaehne** [comment] 2018-12-26 14:17
Can you share the table structure of _c_s_f_c_, double quotes around the column names should be okay if you are writing to a postgresql db.

**Comment by zhaopansong** [comment] 2018-12-28 02:46
> Can you share the table structure of _c_s_f_c_, double quotes around the column names should be okay if you are writing to a postgresql db.

The table structure is shown by creating statement below. I was inserting only parts of columns.
CREATE TABLE "nlp_share"."c_s_f_c" (
"security_factor_conf_sn" numeric(38),
"parent_sn" numeric(38),
"parent_name" varchar(200) COLLATE "default",
"factor_lvl" numeric(38),
"factor_column" varchar(200) COLLATE "default",
"factor_name" varchar(200) COLLATE "default",
"high" numeric(38,18),
"low" numeric(38,18),
"is_display" numeric(38),
"description" varchar(200) COLLATE "default",
"isneutralized" int2
)

**Comment by mroeschke** [comment] 2018-12-28 04:41
It's not exactly clear to me that this is a pandas issue as your error states that the column in the table doesn't exist?

We would need a minimally, reproducible example to indicate whether this is a bug and to ensure we have a test avoid regressions.

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by alimcmaster1** [comment] 2019-01-05 16:33
@zhaopansong if possible could you provide a minimal bug report as per the guide above. There isn’t enough info for us to go on here.

**Comment by WillAyd** [comment] 2019-04-10 02:30
Closing due to lack of info. If you can provide above feel free to reopen

**Closed by WillAyd** 2019-04-10 02:30 UTC
Labels: Needs Info
