### ISSUE TITLE
ENH: NamedAgg support for time windows/Expanding

### ISSUE THREAD

**Issue by ddofer** [pandas-dev/pandas#34685] opened 2020-06-10 08:41 UTC
#### Is your feature request related to a problem?
I am using aggregations over data with groups over time, to create features. I had hoped to use the "new" namedAgg functionality to efficiently calculate and rename the many feature columns. 
I find that named Aggregations only works with the "default"groupby.agg, when used with a rolling window or expanding, it's not supported. 
(I note that the functions documentation doesn't mention this,[ the named agg is mainly in the general documentation](https://pandas-docs.github.io/pandas-docs-travis/user_guide/groupby.html#groupby-aggregate-named), not method-level. i.e the [groupby.agg method's documentatio](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.aggregate.html)n doesn't mention or demonstrate this functionality at all). 

By "named aggregations" I refer to the functionality:
`animals.groupby("kind").agg(**min_height=('height', 'min')**)`

#### Describe the solution you'd like

Expand named aggregation support (NamedAgg) to the groupby aggregation used in [expanding.aggregate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.expanding.Expanding.aggregate.html) and [rolling.aggregate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.window.rolling.Rolling.aggregate.html)

#### API breaking implications
Should not affect it. Seems 1:1. 

#### Additional context
Example usage/errors:

```
df_actions.set_index("age").groupby('uuid').rolling(30).agg(unique_actions=('action', 'nunique'), 
                                total_actions=('counter', 'sum'))

TypeError: aggregate() missing 1 required positional argument: 'func'
```
When used without the window, we get the benefit of namedAggs. (The real code has many more columns and transformations and the columns the features are calculated in are dynamic, so setting a list of column names to use is not desirable. Additionally, data is time-sorted):

```
df_actions.set_index("age").groupby('uuid').agg(unique_actions=('action', 'nunique'), 
                               total_actions=('counter', 'sum'))

>>>

  | unique_actions | total_actions

0 | 0.0
0 | 0.0
...
```

**Comment by MarcoGorelli** [comment] 2020-06-10 09:02
Thanks @ddofer 

Is this the same as #34064?

**Comment by ddofer** [comment] 2020-06-10 10:06
> Thanks @ddofer
> 
> Is this the same as #32803?

It definetely overlaps. Not sure if it's a duplicate, since that is refering a different specific usage

**Comment by mroeschke** [comment] 2020-10-05 01:21
I think this is a duplicate of https://github.com/pandas-dev/pandas/issues/28333, closing.

**Closed by mroeschke** 2020-10-05 01:21 UTC
Labels: Enhancement, Window
