### ISSUE TITLE
BUG: Pandas plot ignores timezone information

### ISSUE THREAD

**Issue by littlegreenbean33** [pandas-dev/pandas#38608] opened 2020-12-21 11:36 UTC
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
dti = pd.date_range('2018-01-01', periods=12, freq='H')
df=pd.DataFrame(range(12),dti)
df.index=df.index.tz_localize(datetime.now().astimezone().tzinfo.tzname(None))
df.plot();plt.show()

```

#### Problem description

While using the plotting functionality of pandas, with timezone aware data/index, the plotted values are aligned with the date values, but not corrected to the timezone time differences.

Often data is stored in UTC, however when retrieved, if timezone is set, the expectation is that data will be plotted on the right timming.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-58-generic
Version          : #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 19.0.3
setuptools       : 40.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.20
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jbrockmendel** [comment] 2020-12-24 21:56
Possibly related to #26676?

**Comment by mroeschke** [comment] 2022-07-01 20:45
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/26676

**Closed by mroeschke** 2022-07-01 20:45 UTC
Labels: Bug, Visualization, Timezones
