### ISSUE TITLE
TypeError when setting MultiIndex in DataFrame

### ISSUE THREAD

**Issue by SteveDoyle2** [pandas-dev/pandas#29297] opened 2019-10-30 19:11 UTC
#### Code Sample

```python
from pandas import read_pickle
df = read_pickle('test.txt')
print(df)
df.set_index(['ElementID', 'NodeID', 'Location'])  # fails
#df.set_index(['ElementID'])  # also fails
```

The pickle file (that I renamed to be a .txt file):
[test.txt](https://github.com/pandas-dev/pandas/files/3790733/test.txt)

#### Problem description

I'm trying to set a MultiIndex on a DataFrame.  I'm getting an error saying that the index (iblockno) is not an integer array, except it is.  Looking at the point in the code  Searching for the error message:

    block = self.blocks[iblockno]
    TypeError: only integer scalar arrays can be converted to a scalar index

 brought me to `pandas\core\internals\managers.py", line ~977`.  I split out iblockno and iblockloc to see understand the error better.
 
```python
    def iget(self, i):
        iblockno = self._blknos[i]
        iblockloc = self._blklocs[i]
        block = self.blocks[iblockno]  # error is here


        values = block.iget(iblockloc)
```

where:

    iblockno
    >>> array([1], dtype=int64)

What I'm confused on is the data is an integer array, so shouldn't I not be getting an error?

#### Expected Output

The dataframe with a MultiIndex of ElementID, NodeID, and Location.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 0.25.1
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3
setuptools       : 41.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
</details>

**Comment by mroeschke** [comment] 2019-10-30 20:30
Do you mind providing a more minimal example? https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If we need to create a unit test for this bug, we don't want to be using pickle necessarily.

**Comment by MarcoGorelli** [comment] 2020-03-02 13:59
Closing due to lack of reproducible example / response.

Feel free to reopen if you paste the content of `df` into your post so we can reproduce the error

**Closed by MarcoGorelli** 2020-03-02 13:59 UTC
Labels: Needs Info
