### ISSUE TITLE
DOC: pandas.json_normalize documentation appears to be missing

### ISSUE THREAD

**Issue by trenton3983** [pandas-dev/pandas#44340] opened 2021-11-07 00:03 UTC
### 

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.json_normalize.html

https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html

https://pandas.pydata.org/docs/dev/reference/api/pandas.json_normalize.html

### Documentation problem

dead links

### Suggested fix for documentation

make the link work

**Comment by asishm** [comment] 2021-11-07 00:25
thanks for the report. duplicate - #42540

**Comment by mroeschke** [comment] 2021-11-07 02:41
Yes appears a duplicate of https://github.com/pandas-dev/pandas/issues/42540. Happy to have a PR to add this to the API reference!

**Closed by mroeschke** 2021-11-07 02:41 UTC
Labels: Docs, Needs Triage
