### ISSUE TITLE
Specify the column name in the mixed data type warning message

### ISSUE THREAD

**Issue by arunkumar413** [pandas-dev/pandas#17989] opened 2017-10-26 09:38 UTC
_/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result_)

#### Problem description

I'm getting a mixed data type warning in a column. The column number is shown as 17. However it isn't clear if the error is in 18 th column considering the column index starts at 0 or 17th column by general counting.

It would be better and easier if the column name also shows up in the warning message to avoid ambiguity and confusion.

Thanks,
Arun

**Comment by jreback** [comment] 2017-10-26 10:02
duplicate of this https://github.com/pandas-dev/pandas/issues/16286

sure would take a PR for this

**Closed by jreback** 2017-10-26 10:02 UTC
