### ISSUE TITLE
to_json() Flat Output

### ISSUE THREAD

**Issue by r-barnes** [pandas-dev/pandas#8333] opened 2014-09-20 20:12 UTC
The to_json() I/O command current provides the following output:

```
split   dict like {index -> [index], columns -> [columns], data -> [values]}
records list like [{column -> value}, ... , {column -> value}]
index   dict like {index -> {column -> value}}
columns dict like {column -> {index -> value}}
values  just the values array
```

It would be handy if the output could also be provided in the format:

```
mdarray    [ [index1,value1a,value1b,...] , [index2,value2a,value2b,...], ... ]
```

This format is, for instance, used by the DyGraphs JS library for plotting data.

The following command provides the output I am looking for:

```
np.column_stack((df.index,df.as_matrix())).tolist()
```

(where `df` is a DataFrame)

**Comment by grafa** [comment] 2016-10-08 10:02
Hi there,

this feature is really needed. These flat arrays `[val, val, val, ...]` are used by Javascript libraries.

All the solutions above don't work so my way was `df.to_csv()` where I get the flat rows and then I'm reading this csv. It's nasty but I had no choice.

**Comment by jreback** [comment] 2016-10-08 14:49
well @grafa pull-requests are welcome.

**Comment by grafa** [comment] 2016-10-08 15:03
I would like to help but I'm not such experienced to deliver solution that matches Pandas code quality.

**Comment by jreback** [comment] 2017-09-18 10:57
closing as dupe of #5729

**Closed by jreback** 2017-09-18 10:57 UTC
Labels: Enhancement, IO JSON
