### ISSUE TITLE
BUG: DataFrame groupby apply produces a wide DataFrame instead of Series if there happens to be only a single group

### ISSUE THREAD

**Issue by thadd3us** [pandas-dev/pandas#56562] opened 2023-12-19 13:43 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.DataFrame({"A": [1, 2, 3]}).groupby([0, 0, 1]).apply(lambda df: "hello " + df["A"].astype(str))
```
Produces a Series (this behavior seems correct and is here to contrast with the bug part below):
```
0  0    hello 1
   1    hello 2
1  2    hello 3
Name: A, dtype: object
```

Whereas making all the groupby values the same, resulting in a single group, creates a pivoted wide DataFrame with a column for each value:
```
pd.DataFrame({"A": [1, 2, 3]}).groupby([0, 0, 0]).apply(lambda df: "hello " + df["A"].astype(str))
```
Produces a DataFrame -- this seems INCORRECT:
```
A        0        1        2
0  hello 1  hello 2  hello 3
```

### Issue Description

When using groupby...apply with:
* A function that produces a Series.
* Data that happens to produce only a single group

You end up with a DataFrame with many columns instead of a Series. 

Googling revealed other people confused about this: https://stackoverflow.com/questions/37715246/pandas-groupby-apply-behavior-returning-a-series-inconsistent-output-type

### Expected Behavior

 I would have expected to get a Series -- the result type should not depend on whether there happen to be multiple groups in the groupby or not.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : ac170fdc3570b55bfcaf44b8587825bcb274bc60
python                : 3.12.0.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.1.0
Version               : Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_CA.UTF-8
LOCALE                : en_CA.UTF-8

pandas                : 2.2.0.dev0+925.gac170fdc35
numpy                 : 1.26.2
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment] 2023-12-19 15:31
Thanks for the report. This is a duplicate of #42749.

**Closed by rhshadrach** 2023-12-19 15:31 UTC
Labels: Bug, Needs Triage
