### ISSUE TITLE
Nothing assigned (except nan) when use `loc`

### ISSUE THREAD

**Issue by BjmWang** [pandas-dev/pandas#22379] opened 2018-08-16 03:02 UTC
```
In [3]: rrDF = pd.DataFrame()
In [4]: rrDF.loc[:,'c']=thatDF.c

In [5]: rrDF
Out[5]:
   c
0  9
1  8
2  8
...
18 5
19 9
20 0


In [6]: x
Out[6]:
    result
0      0.0
1      0.0
2      0.0
...
18     0.0
19     0.0
20     0.0

In [7]: type(x)
Out[7]: pandas.core.frame.DataFrame


In [8]: rrDF.loc[:,'r']=x

In [9]: rrDF # NOTE: nothing assigned
Out[9]:
    c   r
0   9 NaN
1   8 NaN
2   8 NaN
3   1 NaN
...
18  5 NaN
19  9 NaN
20  0 NaN


In [16]: rrDF['r']=x

In [17]: rrDF
Out[17]:
    c    r
0   9  0.0
1   8  0.0
2   8  0.0
3   1  0.0
...
18  5  0.0
19  9  0.0
20  0  0.0

In [18]: rrDF.loc[:,'r']=x  # NOTE: reset values to nan

In [19]: rrDF
Out[19]:
    c   r
0   9 NaN
1   8 NaN
2   8 NaN
3   1 NaN
...
17  0 NaN
18  5 NaN
19  9 NaN
20  0 NaN
```
#### Problem description

When using `rrDF.loc[:,'r']=x`, the expected output is to assign `x` to `rrDF.r` (same with `rrDF['r']=x`).

```
In [20]: pd.__version__
Out[20]: '0.23.0'
```

**Comment by jorisvandenbossche** [comment] 2018-08-16 08:37
@BjmWang Can you please provide a reproducible example? (http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) Eg `thatDF` and `x` are not defined

**Comment by BjmWang** [comment] 2018-08-16 13:42
```
>>> import pandas as pd
>>> print(pd.__version__)
0.23.0
>>> 
>>> thatDF=pd.DataFrame()
>>> thatDF['c']=range(5)
>>> 
>>> rrDF = pd.DataFrame()
>>> rrDF.loc[:,'c']=thatDF.c
>>> print(rrDF)
   c
0  0
1  1
2  2
3  3
4  4
>>> 
>>> x=pd.DataFrame()
>>> x['result'] = range(5)
>>> 
>>> rrDF.loc[:,'r']=x
>>> print(rrDF)
   c   r
0  0 NaN
1  1 NaN
2  2 NaN
3  3 NaN
4  4 NaN
>>> 
>>> rrDF.loc[:,'c']=x
>>> print(rrDF)
    c   r
0 NaN NaN
1 NaN NaN
2 NaN NaN
3 NaN NaN
4 NaN NaN
>>> rrDF['c']=x
>>> print(rrDF)
   c   r
0  0 NaN
1  1 NaN
2  2 NaN
3  3 NaN
4  4 NaN
```


@jorisvandenbossche  Thanks for reply.
Here I write a new small example, which can also reproduce the problem.

```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
```

**Comment by jorisvandenbossche** [comment] 2018-08-16 13:54
When assigning to a single column (with `df.loc[:, 'col'] = ..` or `df['col'] = ..`), the value you assign should rather be a Series (or array, or scalar), and not a DataFrame (which is 2D dimensional).

Because when assigning with a DataFrame as right-hand-side, pandas will try to align that to the dataframe in which you want to assign it. And in this case, your column names do not match.

So assigning only the column itself:

```
# what you did
In [26]: rrDF.loc[:,'r']=x

In [27]: rrDF
Out[27]: 
   c   r
0  0 NaN
1  1 NaN
2  2 NaN
3  3 NaN
4  4 NaN

# assigning as a column
In [28]: rrDF.loc[:,'r'] = x['result']

In [29]: rrDF
Out[29]: 
   c  r
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4
```

**Comment by jorisvandenbossche** [comment] 2018-08-16 13:55
Closing this as it is not a bug in or feature request for pandas itself. 
But please indicate if anything in the documentation can be improved.

**Closed by jorisvandenbossche** 2018-08-16 13:55 UTC
Labels: Usage Question
