### ISSUE TITLE
Inconsistency in `to_datetime` parsing as day and as month for different rows

### ISSUE THREAD

**Issue by vshkolyar** [pandas-dev/pandas#26304] opened 2019-05-07 08:03 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

s = pd.Series(['12.01.2017 17:18', '01.02.2017 11:12', '15.04.2017 02:40'])
pd.to_datetime(s)
```

#### Problem description

In our example the result will be as following:
```
0   2017-12-01 17:18:00
1   2017-01-02 11:12:00
2   2017-04-15 02:03:00
dtype: datetime64[ns]
```

#### Expected Output
```
0   2017-01-12 17:18:00
1   2017-02-01 11:12:00
2   2017-04-15 02:03:00
dtype: datetime64[ns]
```

#### Workaround

Specifiyng explicitly `dayfirst=True` parameter in `pd.to_datetime()` call.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: None
pip: 19.0.3
setuptools: 41.0.0
Cython: None
numpy: 1.16.3
scipy: None
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by saraswatmks** [comment] 2019-05-07 12:20
@vshkolyar Can I take this up?

**Comment by jreback** [comment] 2019-05-07 12:25
duplicate of many see https://github.com/pandas-dev/pandas/issues/12585

**Closed by jreback** 2019-05-07 12:25 UTC
