### ISSUE TITLE
BUG: core.util.numba_.py → jit_user_function → using generated_jit → causing Warning

### ISSUE THREAD

**Issue by MichalRIcar** [pandas-dev/pandas#54307] opened 2023-07-29 14:40 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

def Numba_avg(X):
    return np.mean(X)
    
D = pd.DataFrame({'X':[i for i in range(100)]})

D.rolling(5, axis=0, method='single').apply(Numba_avg, engine='numba', raw=True)
```

### Issue Description

The function **jit_user_function** in **core.util.numba_.py** is using **generated_jit** function which is in deprecation and thus causing deprecation warning by numba:

"
numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
"

### Expected Behavior

Substitute generated_jit in jit_user_function by adequate recommendation by numba.

### Installed Versions

INSTALLED VERSIONS
------------------
python           : 3.11.3.final.0
python-bits      : 64

pandas           : 2.0.3
numpy            : 1.24.4
numba            : 0.57.0

**Comment by lithomas1** [comment] 2023-07-30 13:46
Duplicate of #53449.

This should be fixed on main.

**Closed by lithomas1** 2023-07-30 13:46 UTC
Labels: Bug, Needs Triage
