### ISSUE TITLE
BUILD: pandas 1.5.2 can't be installed with conda-incubator/setup-miniconda@v2

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#49894] opened 2022-11-24 14:46 UTC
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Ubuntu 22.04.1 LTS

### Installation Method

conda install

### pandas Version

1.5.2

### Python Version

3.8

### Installation Logs

<details>

```
Encountered problems while solving:
    - nothing provides requested pandas 1.5.2
```
For reference, look at https://github.com/modin-project/modin/issues/5256 and https://github.com/conda-incubator/setup-miniconda/issues/264.

</details>

**Comment by phofl** [comment] 2022-11-24 15:32
Hi, thanks for your report. Not sure what we can do here. Can you reproduce this without setup-miniconda?

**Comment by YarShev** [comment] 2022-11-24 15:35
I can't reproduce this without `conda-incubator/setup-miniconda@v2`. `conda install pandas=1.5.2` works fine locally. I wonder if someone is aware of the problem?

**Comment by YarShev** [comment] 2022-11-24 15:36
However, `conda install pandas=1.5.2 -c conda-forge` doesn't work in GH Actions workflows.

**Comment by phofl** [comment] 2022-11-24 15:47
Your setup miniconda seems to use a local Conda cache instead of loading the newest information all the time from the channel. This would explain why you can't find the 1.5.2 version

**Comment by YarShev** [comment] 2022-11-24 16:18
I tried to remove this [Cache conda](https://github.com/modin-project/modin/blob/master/.github/workflows/ci.yml#L216) step but it didn't help. Also, we had added this step a long time ago and everything has worked well so far.

**Comment by phofl** [comment] 2022-11-24 16:27
If you check the actual solving step, there is no download of channel information. This look odd to me. Anyway, I don't think that we can help here.

**Comment by phofl** [comment] 2022-11-24 16:42
It works when trying this in a fresh repository without a GitHub Actions history. So closing since this is not on our side

**Closed by phofl** 2022-11-24 16:42 UTC
Labels: Build, Needs Triage, Closing Candidate
