### ISSUE TITLE
weekofyear or dt.week() are producing wrong output in some specific cases

### ISSUE THREAD

**Issue by sumitkhanna2222** [pandas-dev/pandas#27041] opened 2019-06-25 18:00 UTC
#### Code Sample, a copy-pastable example if possible

```python

import pandas as pd
date = pd.to_datetime(20191230, format="%Y%m%d")
print(date.weekofyear)

```
#### Problem description

[this should explain **why** the current behavior is a problem and why the expected output is a better solution.]
I'm doing a project in which I want to print the dates of a particular week of the month .
This code is printing 1 as weekofyear when we are giving date '2019-12-30' or '2019-12-31', 
but it should print 53 as output, as these dates lie in the 53rd week of the year. 

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output
53
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: 4.6.2
pip: 19.1.1
setuptools: 41.0.1
Cython: 0.29.10
numpy: 1.16.4
scipy: None
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: 2.1.0
patsy: 0.4.1
dateutil: 2.8.0
pytz: 2019.1
blosc: None
bottleneck: 1.2.1
tables: None
numexpr: None
feather: None
matplotlib: 3.1.0
openpyxl: 2.6.2
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.8
lxml.etree: 4.3.3
bs4: 4.7.1
html5lib: 1.0.1
sqlalchemy: 1.3.4
pymysql: None
psycopg2: None
jinja2: 2.10.1
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by jreback** [comment] 2019-06-25 18:21
duplicate of https://github.com/pandas-dev/pandas/issues/6936

this is by definition of the ISO week of year

so it’s correct maybe not what u r expecting

**Closed by jreback** 2019-06-25 18:21 UTC
