### ISSUE TITLE
BUG: __getitem__ with boolean type

### ISSUE THREAD

**Issue by felixlaumon** [pandas-dev/pandas#10607] opened 2015-07-17 02:21 UTC
If a series contains boolean data, `value_counts()` do not return the count in the descending order. However the counts are correct if accessing through `iloc`. I supposed that is because 0 is cast into False and 1 is cast into True?

``` py
import pandas as pd

str_series = pd.Series(['f', 'f', 't', 't', 't'])
bool_series = pd.Series([False, False, True, True, True])

counts = bool_series.value_counts()
assert counts.index[0] == True
assert counts.index[1] == False
assert counts[0] == 3 # counts[0] is actually 2
assert counts[1] == 2 # counts[1] is actually 3

counts = bool_series.value_counts()
assert counts.index[0] == True
assert counts.index[1] == False
assert counts.iloc[0] == 3 # this works
assert counts.iloc[1] == 2 # this works

counts = str_series.value_counts()
assert counts.index[0] == 't'
assert counts.index[1] == 'f'
assert counts[0] == 3
assert counts[1] == 2
```

**Comment by sinhrks** [comment] 2015-07-17 03:43
Thanks for the report. I understand the problem is unrelated to ``value_counts`` and sort, but simply referring to indexing against bool ``Index``?  Following is simple example on my env:

```
s = pd.Series([3, 2], index=[True, False])
# True     3
# False    2
# dtype: int64

# OK
s[True]
# 3
s[False]
# 2

# NG, expects location based indexing?
s[0]
# 2
s[1]
# 3 

# currently, Index can't have bool dtype 
s.index.dtype
# dtype('O')
```

**Comment by felixlaumon** [comment] 2015-07-17 06:54
Yes it's really more about indexing with bool type index.

**Comment by jreback** [comment] 2015-07-17 12:35
yeh this is an edge case; could be addressed by using 

``
In [1]: Index([True,False]).inferred_type
Out[1]: 'boolean'
```

in ``Series.__getitem__``

**Comment by sinhrks** [comment] 2015-07-17 16:45
Looked little, and it is likely to be caused by ``numpy``. Will check whether it is intended or not. 

```
import numpy as np
np.__version__
# '1.9.2'

a = np.array([0, 1, 2])
a[True]
# 1
a[False]
# 0

a[[True]]
# __main__:1: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
# array([1])
a[[False]]
# array([0])

# When we pass array, it works as boolean indexing
a[np.array([True])]
# array([0])
a[np.array([False])]
# array([], dtype=int64)
```

**Comment by mroeschke** [comment] 2024-09-12 21:18
It looks like this raises now and I believe we have tests for this so closing

**Closed by mroeschke** 2024-09-12 21:18 UTC
Labels: Bug, Indexing
