### ISSUE TITLE
`DataFrame.pct_change` should default `fill_method=None` instead of `'pad'`

### ISSUE THREAD

**Issue by selik** [pandas-dev/pandas#28461] opened 2019-09-16 15:01 UTC
Both `DataFrame.pct_change` and `Series.pct_change` should have default behavior that matches the "obvious" implementation:

```python
lag = series.shift(1)
change = (series - lag) / lag
```

Unfortunately, the default behavior is set to `fill_method='pad'` which surprises many people (#6389). We should start a deprecation cycle to change the default to behave as expected, `fill_method=None`. I don't believe this will be disruptive, as most people think that's how it behaves currently, as far as I know.

**Comment by WillAyd** [comment] 2019-09-16 15:17
Can you add a reproducible example? It's not quite clear from the code what you would be looking for.

FWIW #25291 has some new functionality which maybe covers what you are looking for, though that PR has gone stale. If it covers it would certainly welcome you picking that one up

**Comment by selik** [comment] 2019-09-16 15:33
Looks like @TomAugspurger made a comment to this effect on that PR. I'll check it out... someday :-) .

**Comment by WillAyd** [comment] 2019-09-16 16:18
OK - closing this as a duplicate of what the PR already solves then, but again if it's something different feel free to provide a reproducible code sample with expected values and can reopen

**Comment by selik** [comment] 2019-09-16 23:45
Ah, no, I don't think that PR was meant to address this issue directly. There happened to be a discussion of this issue as related to PR #25291.

**Comment by selik** [comment] 2019-09-16 23:49
I misspoke earlier. The referenced PR does *not* put the default behavior into a deprecation cycle, which is the goal of this issue.

**Comment by maartenb** [comment] 2019-10-23 16:13
As this is not a duplicate, can the duplicate label be removed?

What needs to be done to get this issue resolved/implemented?

**Comment by jreback** [comment] 2019-10-23 22:59
this is a duplicate of https://github.com/pandas-dev/pandas/issues/25006

there is a closed PR that almost ready  (referenced from the above issue)

**Closed by jreback** 2019-10-23 22:59 UTC
Labels: Duplicate

**Comment by maartenb** [comment] 2019-10-24 01:07
The approach @selik proposed is different and well defined. If there is a sequence of NaNs it might not make sense to do a pct_change over the gap. Also, it seems that PR for #25006  is not really in play anymore, possibly because it also needs a deprecation period?

**Comment by selik** [comment] 2019-10-24 05:23
@jreback I looked at PR #25006 and don't think it's going to solve this issue. Certainly it's not clear from the discussion.
