### ISSUE TITLE
Nullable integer data type bug in read_csv

### ISSUE THREAD

**Issue by AlexanderSpirin** [pandas-dev/pandas#32453] opened 2020-03-05 07:45 UTC
When reading csv file column with NA fields  loose precision. I think the reason of the problem is the cast to float somewhere under hood.

`/tmp/1.csv:`
```csv
field1,field2
,1577134800018164904
1577134800018226901,1577134800018267738
```

```python
A = pd.read_csv('/tmp/1.csv', dtype='Int64')
A
```

  | field1 | field2
-- | -- | --
0| <NA> | 1577134800018164904
1| **1577134800018226944** | 1577134800018267738

```python
int(float(1577134800018226901))
1577134800018226944
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.16.0-77-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 28.8.0
Cython           : 0.29.14
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by jorisvandenbossche** [comment] 2020-03-10 14:07
@AlexanderSpirin Thanks for the report! 
I think this is caused by https://github.com/pandas-dev/pandas/issues/30268, and the actual CSV issue is also reported at https://github.com/pandas-dev/pandas/issues/32134

So closing as a duplicate of https://github.com/pandas-dev/pandas/issues/32134

**Closed by jorisvandenbossche** 2020-03-10 14:07 UTC
