### ISSUE TITLE
weakrefs on ix objects?

### ISSUE THREAD

**Issue by hhuuggoo** [pandas-dev/pandas#10221] opened 2015-05-28 17:42 UTC
Would it make sense to make the backref from ix objects to the dataframe be weakrefs (and presumably, loc/iloc)  The reason I ask is that it seems that the refcount is incremented once you use ix, and as a result the dataframe won't get garbage collected until the cycle detection runs

**Comment by jreback** [comment] 2015-05-28 17:54
this already is the case. pls show an example if it looks different to you.

**Comment by hhuuggoo** [comment] 2015-05-28 18:11
ok - my mistake. This is what I observed

```
import pandas as pd
import numpy as np
import sys
df = pd.DataFrame({'a' : np.arange(10)})
print sys.getrefcount(df)
df.ix
print sys.getrefcount(df)
```

```

In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: import sys

In [4]: df = pd.DataFrame({'a' : np.arange(10)})

In [5]: print sys.getrefcount(df)
2

In [6]: df.ix
Out[6]: <pandas.core.indexing._IXIndexer at 0x10fd637d0>

In [7]: print sys.getrefcount(df)
3
```

**Comment by jreback** [comment] 2015-05-28 18:20
can you give an example of why this should actually matter?

the semantics of dealing with weakrefs are kind of annoying. this is a normal cyclic reference (e.g. the indexers hold the dataframe reference itself). the cyclic garbage collection takes care of these.

**Comment by hhuuggoo** [comment] 2015-05-28 18:33
This does not cause any real problem - the cyclic GC should work, however I think it does make troubleshooting memory usage on large programs using pandas more difficult.  That was my motivation.  I would be happy to do the PR if we want it, but I wanted to check in with you guys first

**Comment by jreback** [comment] 2015-05-28 18:37
you can certainly try

you could make ``core/indexing.py/NDFrameIndexer`` use ``weakref.ref(obj)`` in ``__init__``. 

Then you have to access via ``self.obj()`` all over the place

Not sure how to test it, and would have to run a perf metric.

But would take a PR for this.

**Comment by jreback** [comment] 2017-03-29 01:07
dupe of #15746

**Closed by jreback** 2017-03-29 01:07 UTC
Labels: API Design, Difficulty Intermediate, Effort Medium, Indexing, Performance
