### ISSUE TITLE
BUG: concat with empty frame upcasts float32 -> float64

### ISSUE THREAD

**Issue by adbull** [pandas-dev/pandas#15525] opened 2017-02-27 22:12 UTC
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> x = pd.DataFrame([[0]], dtype='float32')
>>> pd.concat([x, x.loc[0:]]).dtypes
0    float32
dtype: object
>>> pd.concat([x, x.loc[1:]]).dtypes
0    float64
dtype: object
```
#### Problem description

Calling `concat()` on two float32 DataFrames, one of which is empty, will upcast the data to float64, wasting memory.

#### Expected Output

```python
0    float32
dtype: object

0    float32
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 16.4.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
xarray: 0.9.1
IPython: 4.2.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.4.0
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.1.4
pymysql: None
psycopg2: None
jinja2: 2.8.1
boto: 2.45.0
pandas_datareader: None
</details>

**Comment by jreback** [comment] 2017-02-27 22:17
This is expected. empty frames are not considered for dtype considerations as there are some performance considerations. You can certainly look if you want and see a potential fix. But this is not a bug. marking as wont' fix.

**Comment by jreback** [comment] 2017-02-27 23:05
hmm on second thought we actually have quite a bit off issues where we delt with this.

#12411, #12045, #11594

though these were pretty much datetime related.

**Comment by jreback** [comment] 2017-02-27 23:06
of course community PR's to fix would be really helpful :>

**Comment by jaehoonhwang** [comment] 2017-03-03 07:00
Hi, I'm new to contributing `pandas`.
Can I help with this bug and if so can you point to me at right direction?

**Comment by jreback** [comment] 2017-03-03 13:19
actually this is a dupe of #13247; their is a pull-request #13337 that can be adapted (it is basically done, just needs a little polishing). happy to have you take that over.

**Closed by jreback** 2017-03-03 13:19 UTC
Labels: Bug, Difficulty Intermediate, Dtypes, Effort Low
