### ISSUE TITLE
BUG: comparing TZ-aware timestamps to a scalar results in exception

### ISSUE THREAD

**Issue by chrisaycock** [pandas-dev/pandas#15966] opened 2017-04-10 14:03 UTC
This works as expected:

```
pd.DataFrame({'test': [pd.Timestamp('2012-01-01 13:00:00'),
                       pd.Timestamp('2012-01-01 13:00:00')]}) == -1
```

However, this raises an exception:

```
pd.DataFrame({'test': [pd.Timestamp('2012-01-01 13:00:00+00:00'),
                       pd.Timestamp('2012-01-01 13:00:00+00:00')]}) == -1
```

**Comment by watercrossing** [comment] 2017-11-08 12:45
This has also been fixed at some point, I can't reproduce on master.

**Comment by jreback** [comment] 2017-11-08 12:54
can u put up a validation test to close?

**Comment by TomAugspurger** [comment] 2017-11-08 16:46
Closed by #18170

**Closed** 2017-11-08 20:01 UTC
Labels: Bug, Timezones
