### ISSUE TITLE
BUG: unique() casts its types' elements from `pd.Timestamp` to `numpy.datetime64`

### ISSUE THREAD

**Issue by SebastianoX** [pandas-dev/pandas#35449] opened 2020-07-29 09:39 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample

```python
import pandas as pd 
 
 
df = pd.DataFrame({"date": ["2019-02-10", "2019-02-11"]}) 
df["date"] = pd.to_datetime(df["date"]) 
 
print("Date Types in column date:") 
for day in df["date"]: 
    print(type(day))  # pandas._libs.tslibs.timestamps.Timestamp 
 
print("Unique date Types in column date:") 
for day in df["date"].unique():  
    print(type(day))  # np.datetime64 

```

The code above results in:

```
Date Types in column date:
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

Unique date Types in column date:
<class 'numpy.datetime64'>
<class 'numpy.datetime64'>
```

#### Problem description

The class method `unique()` should not change the type of the elements in the original column.

#### Expected Output

```
Date Types in column date:
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

Unique date Types in column date:
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
```

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

#### Note

Issue related to #35448, where in the thread I have been asked to re-create it with a clearer OP.

**Comment by TomAugspurger** [comment] 2020-09-04 15:37
I'm not sure there's anything to do here. The array type for `datetime64[ns]` is an `ndarray[datetime64[ns]]`. 

```python
In [23]: df['date'].values
Out[23]:
array(['2019-02-10T00:00:00.000000000', '2019-02-11T00:00:00.000000000'],
      dtype='datetime64[ns]')
```

**Comment by TomAugspurger** [comment] 2020-09-04 15:38
I see from https://github.com/pandas-dev/pandas/issues/35448 there's some discussion around making Series.unique always return an extension array (at least for datetimes?). I'm not sure about that either.

**Comment by mroeschke** [comment] 2021-08-08 19:27
Yeah it appears that this is the intended behavior and not a bug as storing `Timestamp` objects in an `ndarray` would be a large change and inefficient (especially for a tz-naive datetime). Thanks for the report but closing as the expected behavior

**Closed by mroeschke** 2021-08-08 19:27 UTC
Labels: Bug
