### ISSUE TITLE
to_csv swallows exception when writing to S3

### ISSUE THREAD

**Issue by vfilimonov** [pandas-dev/pandas#30732] opened 2020-01-06 12:07 UTC
I'm not sure if this issue belongs to `pandas` or `s3fs`.

When writing to non-existing bucket or bucket without proper permissions no exception is raised. E.g. the following code will be executed normally:
```python
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df.to_csv('s3://very.weird.and.certainly.nonexistent.bucket/data.csv')  # No exception
```

In contrast, when writing to a local file without proper permissions results in an exception as it should be:
```python
dff.to_csv('/data.csv')  # PermissionError: [Errno 13] Permission denied: '/data.csv'
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.1.post20191125
Cython           : None
pytest           : 5.3.0
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : None
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.0.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.12.1
pytables         : None
s3fs             : 0.4.0
scipy            : 1.3.1
sqlalchemy       : 1.3.8
tables           : 3.4.4
xarray           : None
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by gfyoung** [comment] 2020-01-07 21:21
I would look into seeing where we call `s3fs` to do the actual writing.  I would be surprised if it was `s3fs` thing that it wouldn't tell us if a bucket didn't exist.

**Comment by alimcmaster1** [comment] 2020-06-30 22:58
Take

**Comment by alimcmaster1** [comment] 2020-09-05 00:01
Duplicate of https://github.com/pandas-dev/pandas/issues/32486 I think. Should now be fixed on master by https://github.com/pandas-dev/pandas/pull/33645

**Closed by alimcmaster1** 2020-09-05 00:01 UTC
Labels: Bug, IO CSV, IO Network
