### ISSUE TITLE
Can't install Pandas on Mac M1 

### ISSUE THREAD

**Issue by mabidou** [pandas-dev/pandas#40611] opened 2021-03-24 13:42 UTC
Environment
Mac M1
Python 3.8.2 created using Xcode Command Line Tools for M1 Macs

On trying to install pandas, it failed and it returns very long erorr message starts as below

                        
(py382tf) mgd@MGD ~ % pip install pandas
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/8a/6f/7fcef020b5b305862cacf376183eaa0f907f2fa42f0b687b2a9a2c6cda4d/pandas-1.2.3.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/mgd/py382tf/bin/python3 /Users/mgd/py382tf/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/px/zqhcsbbx4yxfmhc7927tnfj00000gn/T/pip-build-env-orb4vxpv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.21,<3' 'numpy==1.16.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.5; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy; python_version>='"'"'3.9'"'"''
       cwd: None
  Complete output (4451 lines):
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.9"' don't match your environment
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/9e/d4/b99a960314121a003e9f39c61dfde01a1010bb47661e193a7722f7f32d52/setuptools-54.2.0-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Collecting Cython<3,>=0.29.21
    Using cached https://files.pythonhosted.org/packages/9e/98/bff39b3acaebbc6102be71797f655bbe60738f7339db4ad7bd0772c08daf/Cython-0.29.22-py2.py3-none-any.whl
  Collecting numpy==1.17.3
    Using cached https://files.pythonhosted.org/packages/b6/d6/be8f975f5322336f62371c9abeb936d592c98c047ad63035f1b38ae08efe/numpy-1.17.3.zip
  Installing collected packages: setuptools, wheel, Cython, numpy
    Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/mgd/py382tf/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/px/zqhcsbbx4yxfmhc7927tnfj00000gn/T/pip-install-x_x_2bsb/numpy/setup.py'"'"'; __file__='"'"'/private/var/folders/px/zqhcsbbx4yxfmhc7927tnfj00000gn/T/pip-install-x_x_2bsb/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/px/zqhcsbbx4yxfmhc7927tnfj00000gn/T/pip-record-73r6zlw4/install-record.txt --single-version-externally-managed --prefix /private/var/folders/px/zqhcsbbx4yxfmhc7927tnfj00000gn/T/pip-build-env-orb4vxpv/overlay --compile --install-headers /Users/mgd/py382tf/include/site/python3.8/numpy
           cwd: /private/var/folders/px/zqhcsbbx4yxfmhc7927tnfj00000gn/T/pip-install-x_x_2bsb/numpy/
      Complete output (4428 lines):
      Running from numpy source directory.
  
      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:
  
        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)
  
  
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
        NOT AVAILABLE
  
      blis_info:
      customize UnixCCompiler
        libraries blis not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
        NOT AVAILABLE
  
      openblas_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
        NOT AVAILABLE
  
      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries tatlas not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
        NOT AVAILABLE
  
      atlas_3_10_blas_info:
      customize UnixCCompiler
        libraries satlas not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
        NOT AVAILABLE
  
      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
        NOT AVAILABLE
  
      atlas_blas_info:
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
        NOT AVAILABLE
  
      accelerate_info:
      customize UnixCCompiler
        libraries accelerate not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
      Library accelerate was not found. Ignoring
      customize UnixCCompiler
        libraries veclib not found in ['/Users/mgd/py382tf/lib', '/usr/lib']
      Library veclib was not found. Ignoring

**Comment by jbrockmendel** [comment] 2021-03-24 14:24
Looks like the problem is occuring during the numpy installation.  Can you get `pip install numpy` to go through on its own?

**Comment by mabidou** [comment] 2021-03-24 23:35
> Looks like the problem is occuring during the numpy installation. Can you get `pip install numpy` to go through on its own?

@jbrockmendel `numpy 1.20.1` is installed fine with no issue

**Comment by jbrockmendel** [comment] 2021-03-25 00:40
Does doing the pandas install after a succcessful numpy install affect the behavior?

**Comment by mabidou** [comment] 2021-03-25 02:09
@jbrockmendel  I tried also starting with pandas installation but it failed too.

**Comment by charlesdong1991** [comment] 2021-03-25 08:05
I also came across similar issue using Macs M1, could you please try to choose a lower numpy version to install and then install pandas. This helped me resolve the issue (although mine is with scikit-learn) although i don't really know why the issue occurs, and see if your installation issue can be resolved?

**Comment by mabidou** [comment] 2021-03-25 13:49
@charlesdong1991 As I'm installing tensorflow, Numpy version is decided by https://github.com/apple/tensorflow_macos

**Comment by code280** [comment] 2021-03-25 19:15
Hello,

I faced the same problem, and solved it by doing the following steps:

1. open finder
2. locate terminal
3. right click on the terminal icon
4. click get info
5. click open with rosetta
6. open a new terminal 
7. use your normal package downloading method like "pip3 install pandas"

This should fix the issue.

**Comment by jbrockmendel** [comment] 2021-03-25 19:24
clearly the solution is for Apple to send me an M1 MBP so i can ensure we have testing on the platform.

**Comment by mrpbennett** [comment] 2021-03-25 21:29
I am having a similar issue with M1 and running Pandas. I keep getting the following:

```
/Users/paul/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError. warnings.warn(msg)
```

I have installed the command line tools. I have also installed the following via brew

```
brew install openssl readline sqlite3 xz zlib
```

Then exported the PATHs to my `.zsh` file, as home-brew states I should do this incase I want compilers to find those packages, so my `.zsh` now looks like this:

```zsh
# Path to your oh-my-zsh installation.
export ZSH="/Users/paul/.oh-my-zsh"

# Path for compilers ----
# Path to openssl
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

# Path to readline
export LDFLAGS="-L/opt/homebrew/opt/readline/lib"
export CPPFLAGS="-I/opt/homebrew/opt/readline/include"

# Path to sqlite
export LDFLAGS="-L/opt/homebrew/opt/sqlite/lib"
export CPPFLAGS="-I/opt/homebrew/opt/sqlite/include"

# Path to zlib
export LDFLAGS="-L/opt/homebrew/opt/zlib/lib"
export CPPFLAGS="-I/opt/homebrew/opt/zlib/include"

# Path to openldap
export LDFLAGS="-L/opt/homebrew/opt/openldap/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openldap/include"

# Path to curl
export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/curl/include"
```

I continued to install Python 3.9.2 via asdf following the instructions so I have also installed

```
brew install coreutils curl git
```

When trying to import Pandas into the Python prompt I get the following:

```python
~ took 5m 1s
➜ python
Python 3.9.2 (default, Mar 25 2021, 21:14:35)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
/Users/paul/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
>>>
```

This is what I got when installing pandas via pip.

```zsh
~ took 6s
➜ pip install pandas
Collecting pandas
  Downloading pandas-1.2.3.tar.gz (5.5 MB)
     |████████████████████████████████| 5.5 MB 3.2 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing ./Library/Caches/pip/wheels/46/2b/81/c5cdd9e6c23d21ba8aedab943979e6df7f30fe19001ada0043/numpy-1.20.1-cp39-cp39-macosx_11_2_arm64.whl
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 3.8 MB/s
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 5.3 MB/s
Collecting six>=1.5
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: pandas
  Building wheel for pandas (PEP 517) ... done
  Created wheel for pandas: filename=pandas-1.2.3-cp39-cp39-macosx_11_0_arm64.whl size=9348696 sha256=d0d6bf83405b758813b3a36fca0240ccc5115f5a71c932906925494506bc9f29
  Stored in directory: /Users/paul/Library/Caches/pip/wheels/9d/8a/fd/e73047055ea8d97f6504fce1d04c505dd80ca3c54cad1eb66e
Successfully built pandas
Installing collected packages: numpy, pytz, six, python-dateutil, pandas
Successfully installed numpy-1.20.1 pandas-1.2.3 python-dateutil-2.8.1 pytz-2021.1 six-1.15.0
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/paul/.asdf/installs/python/3.9.2/bin/python3.9 -m pip install --upgrade pip' command.
```

This is what I have installed via pip

```
➜ pip list
Package         Version
--------------- -------
numpy           1.20.1
pandas          1.2.3
pip             20.2.3
python-dateutil 2.8.1
pytz            2021.1
setuptools      49.2.1
six             1.15.0
```

I am pulling my hair out 🤯 here and I have no idea how to fix it. I would like to think I have installed python correctly as I have followed pretty much everything to the letter.

**Comment by jbrockmendel** [comment] 2021-03-25 21:34
> UserWarning: Could not import the lzma module

pandas should run fine without lzma unless you are trying to use lzma-specific features.  You can just ignore this warning.

**Comment by mrpbennett** [comment] 2021-03-25 21:50
I can't as pandas won't run as I can't import it...I get the same error when trying to use pandas within pycharm of VSC

**Comment by fangchenli** [comment] 2021-03-26 16:08
`pip install numpy` only works for `numpy>=1.20` on M1. I think when you run `pip install pandas`, pip is trying to install a numpy of version 1.19.x. 

You could try to build pandas from source like this.
```
git clone https://github.com/pandas-dev/pandas.git
cd pandas
python -m pip install numpy cython pytz python-dateutil
python setup.py build_ext -j 8
python -m pip install -e . --no-build-isolation --no-use-pep517
```

@jbrockmendel We probably should set a min numpy version in `pyproject.toml` for M1.

**Comment by mrpbennett** [comment] 2021-03-26 16:50
I actually resolved my issue by uninstalling the python installed via asdf and installed a fresh version with home-brew. 
So must be the way asdf builds python from source for M1 machines?

**Comment by jbrockmendel** [comment] 2021-03-26 17:40
> We probably should set a min numpy version in pyproject.toml for M1.

I don't doubt your conclusion, but since I have no way to double-check it im abstaining on forming an opinion

**Comment by sidkang** [comment] 2021-03-28 02:44
I just installed Pandas over M1 using Python version 3.8.8 & 3.9.1. The 3.9.1 version works just fine. But for the 3.8.8, I just cannot get Pandas installed.

**Comment by aidenmitchell** [comment] 2021-03-30 18:39
> I just installed Pandas over M1 using Python version 3.8.8 & 3.9.1. The 3.9.1 version works just fine. But for the 3.8.8, I just cannot get Pandas installed.

Can't say the same :(

**Comment by ricardoprins** [comment] 2021-04-14 21:07
Steps I took in a brand new M1 Macbook Air to make it work:

- Updated Python via Homebrew (3.9.4)
- Installed Cython (pip install cython)
- Installed Numpy without PEP517 (pip install numpy --no-use-pep517)
- Installed Pandas without PEP517 (pip install pandas --no-use-pep517)

**Comment by TheCaffeineDev** [comment] 2021-04-23 10:39
I installed pandas in my M1 Macbook Pro today. 

- Installed Python 3.9.4 using Homebrew.
- Then just did `pip3 install pandas`

It took a while but not more than 3 minutes though. It got successfully installed.


Here's my log

```
❯ pip3 install pandas

Collecting pandas
  Downloading pandas-1.2.4.tar.gz (5.5 MB)
     |████████████████████████████████| 5.5 MB 855 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.16.5
  Using cached numpy-1.20.2-cp39-cp39-macosx_11_0_arm64.whl
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 8.8 MB/s
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 10.5 MB/s
Requirement already satisfied: six>=1.5 in /opt/homebrew/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Building wheels for collected packages: pandas
  Building wheel for pandas (PEP 517) ... /

done
  Created wheel for pandas: filename=pandas-1.2.4-cp39-cp39-macosx_11_0_arm64.whl size=9354006 sha256=87fead2b2cacdfdc448c444899dfffca3b82275635ac8d51a39790ede623e342
  Stored in directory: /Users/pks/Library/Caches/pip/wheels/1c/18/1d/96f6fb133a77724bc42fce621a44162d840d037b9289c4a874
Successfully built pandas
Installing collected packages: pytz, python-dateutil, numpy, pandas
Successfully installed numpy-1.20.2 pandas-1.2.4 python-dateutil-2.8.1 pytz-2021.1

```

**Comment by jackwellsxyz** [comment] 2021-04-28 20:06
Hi all - to pile on to the above, I've been able to install numpy fine, but I get the following error when installing pandas (up to and including the current git repo, i.e. version 1.3.0.dev0+1455.g59b2db14f9 59b2db1):

**Comment by jbrockmendel** [comment] 2021-04-28 20:18
@jackwellsxyz can you import numpy? (Not just install)

**Comment by hkennyv** [comment] 2021-06-23 16:47
Just chiming in to note that I was able to install pandas in a clean virtualenv today on an M1 Macbook Air running Big Sur (11.4). Similar to @TheCaffeineDev, it took a while to build the wheel, but it succeeded without any errors and I'm able to successfully import it.

```
$ python --version
Python 3.9.5
```

**Comment by lithomas1** [comment] 2021-07-11 16:15
We don't currently have wheels for arm64(M1) so pip will try to build pandas from source. I think a fix was merged in 1.3 that should allow everyone to install pandas from a clean environment.

**Comment by mroeschke** [comment] 2021-08-19 02:56
Sounds like this issues is relatively resolved in 1.3 at least so closing. Happy to reopen if that didn't fix things.

**Closed by mroeschke** 2021-08-19 02:56 UTC
Labels: Bug, Build, Closing Candidate, ARM

**Comment by mkismy** [comment] 2021-11-04 08:45
Hi @mroeschke,

I have problem installing pandas to M1 mac with the following:
- python 3.9.7 (installed via pyenv)
- numpy 1.21.1

The attached file is an error output when installing pandas via poetry, but the same error appears when simply doing `pip install pandas`

[log.txt](https://github.com/pandas-dev/pandas/files/7473415/log.txt)

**Comment by CcliqueE** [comment] 2021-11-26 06:05
is this still a problem with m1 pro macs? I seem to be encountering the same problem, which is that I am not able to 
'pip3 install pandas'
and then import the pandas module successfully without it throwing me an error!!! X(

**Comment by josh-gree** [comment] 2022-01-10 11:25
@mkismy - I am having exactly the same problem installing via poetry - did you solve?

**Comment by brendankerr1324** [comment] 2022-01-19 15:29
I'm having the same problem as @mkismy. Trying to install pandas 1.3.4 via Poetry, running Python 3.9.8

**Comment by arun-annamalai** [comment] 2022-01-19 18:44
I'm having the same problem as @mkismy. Would really appreciate a fix for the M1 pro so that I can continue developing on this machine

**Comment by jbrockmendel** [comment] 2022-01-19 19:04
> Would really appreciate a fix for the M1 pro so that I can continue developing on this machine

AFAIK none of the pandas devs have access to an M1 machine so we can't solve this on our own.  If you post traceback you're getting we can try to troubleshoot.

**Comment by fangchenli** [comment] 2022-01-19 19:11
> > Would really appreciate a fix for the M1 pro so that I can continue developing on this machine
> 
> AFAIK none of the pandas devs have access to an M1 machine so we can't solve this on our own. If you post traceback you're getting we can try to troubleshoot.

I use M1 machine with Miniforge. And I haven't encountered any problems yet.

**Comment by fangchenli** [comment] 2022-01-19 20:00
I just tried `pip install pandas` in a venv. It works as well.

**Comment by arun-annamalai** [comment] 2022-01-20 02:08
Using Miniforge solved the issue. Thank you!

**Comment by harryghgim** [comment] 2022-04-25 07:09
My solutions are as shown below. 

**Discaimer: YMMV**

I installed python3.8.10 with macOS 64-bit universal2 installer from python.org and faced the same issue when I run `pip install pandas==1.0.5`. For me one of the followings worked.

Method 1
- change my zsh type to intel one
```
arch -x86_64 zsh
```
- run `pip install pandas==1.0.5` and no error appeared.

Method 2
- use macOS 64-bit intel installer in the first place to install python3.8.10
- run `pip install pandas==1.0.5` and no error appeared.

**Comment by erperejildo** [comment] 2022-08-05 14:58
I'm getting th

> Steps I took in a brand new M1 Macbook Air to make it work:
> 
> * Updated Python via Homebrew (3.9.4)
> * Installed Cython (pip install cython)
> * Installed Numpy without PEP517 (pip install numpy --no-use-pep517)
> * Installed Pandas without PEP517 (pip install pandas --no-use-pep517)

my error for example comes from Docker. Even if I do all of this I'm not going to install it inside the image, which is where I'm getting the error from
