### ISSUE TITLE
BUG: Pandas 1.1.0 apply function with axis=1 seems to mishandle the rows

### ISSUE THREAD

**Issue by arshad171** [pandas-dev/pandas#35634] opened 2020-08-08 18:08 UTC
### The functionality of the **apply(func, axis=1)** in the newly released pandas==1.1.0 is not working as expected.

Pandas seems to be overwriting all the rows in the data frame with the 1st row present. This is happening specifically when introducing a new column in the data frame when running **func** method on each of the rows.

This working in pandas==1.0.5, but seems to be a bug in pandas=1.10.

I am attaching a sample script and the logs captured for pandas==1.0.5 and pandas==1.10.

### Attachments:
1. sample script to reproduce the issue (rename to .py before running) --> [script.txt](https://github.com/pandas-dev/pandas/files/5045977/script.txt)

2. output 1 (pandas==1.0.5) - working as expected --> [out_pandas_1.0.5.log](https://github.com/pandas-dev/pandas/files/5045978/out_pandas_1.0.5.log)

3. output 2 (pandas==1.1.0) - **buggy** --> [out_pandas_1.1.0.log](https://github.com/pandas-dev/pandas/files/5045980/out_pandas_1.1.0.log)

As you can see in the *out_pandas_1.1.0.log* log, after preprocessing the data frame using ``` df = df.apply(process_text, axis=1) ``` all the rows in the data frame have been overwritten with the 1st row.

This was not the case with pandas==1.0.5, check the **out_pandas_1.0.5.log** log.

### Environment
- OS: Ubuntu 20.04
- Python: 3.7.7 (anaconda env)

**Comment by simonjayhawkins** [comment] 2020-08-10 13:13
Thanks @arshad171 for the report. This appears to be a duplicate of #35462 so closing.

**Closed by simonjayhawkins** 2020-08-10 13:13 UTC
Labels: Bug, Needs Triage
