### ISSUE TITLE
BUILD: Unable to install Pandas using poetry v1.4.2

### ISSUE THREAD

**Issue by alimaks** [pandas-dev/pandas#52703] opened 2023-04-17 16:42 UTC
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-7-6.1.7601-SP1

### Installation Method

Other

### pandas Version

2.0.0.

### Python Version

3.9.16

### Installation Logs

Installation via Poetry (version 1.4.2)

<details>

Warning: Validation of the RECORD file of pandas-2.0.0-cp39-cp39-win_amd64.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
In C:\Users\alimaskin\AppData\Local\pypoetry\Cache\artifacts\3c\7f\e0\545a548f0746fbe29a26218dc739746953f6d6737ae0f882a6860939fc\pandas-2.0.0-cp39-cp39-win_amd64.whl, pandas/_libs/window/msvcp140.dll is not mentioned in RECORD
In C:\Users\alimaskin\AppData\Local\pypoetry\Cache\artifacts\3c\7f\e0\545a548f0746fbe29a26218dc739746953f6d6737ae0f882a6860939fc\pandas-2.0.0-cp39-cp39-win_amd64.whl, pandas/_libs/window/concrt140.dll is not mentioned in RECORD
In C:\Users\alimaskin\AppData\Local\pypoetry\Cache\artifacts\3c\7f\e0\545a548f0746fbe29a26218dc739746953f6d6737ae0f882a6860939fc\pandas-2.0.0-cp39-cp39-win_amd64.whl, pandas/_libs/window/vcruntime140_1.dll is not mentioned in RECORD

</details>

**Comment by lithomas1** [comment] 2023-04-17 16:55
@alimaks 
This should be a duplicate of #52465, #52697. A fix is scheduled for pandas 2.0.1. 
In the meantime, you can ignore the warnings from poetry, those files are meant for inclusion in the pandas wheel.

Please search the issue tracker next time.
Thanks.

**Closed by lithomas1** 2023-04-17 16:55 UTC
Labels: Build, Duplicate Report

**Comment by alimaks** [comment] 2023-04-17 17:02
Yes, I saw #52465, #52697, but there was a different version of Python (3.11), whereas I have 3.9 and an older operating system. I thought that made a difference.

>>In the meantime, you can ignore the warnings from poetry

Does this message mean that Pandas 2.0.0 will work for me now or should I wait for version 2.0.1?

Sorry for the simple questions, I'm a beginner ))

**Comment by lithomas1** [comment] 2023-04-17 17:07
No worries. 
Unfortunately, you'll still get the warnings on pandas 2.0, since there is no way for us to modify the uploaded wheels on PyPI retroactively. 

(2.0.1 should be out in roughly 2 weeks time)

pandas should still be fine to use despite the warnings, though.

**Comment by alimaks** [comment] 2023-04-17 17:08
Thank you very much! It's all clear now))
