### ISSUE TITLE
BUG: pd.to_datetime does not assign UTC TZ to Unix Epoch Timestamps

### ISSUE THREAD

**Issue by haydenflinner** [pandas-dev/pandas#41360] opened 2021-05-06 22:12 UTC
- [ X ] I have checked that this issue has not already been reported.

- [ X ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
from datetime import datetime

now = datetime.now()

df = pd.DataFrame({'ts_pd': [now.timestamp()], 'ts_py': [now.timestamp()]})
print(f"It is now: {now.timestamp()} seconds from Unix Epoch (00:00:00 UTC on 1 January 1970)")
df['ts_pd'] = pd.to_datetime(df['ts_pd'], unit='s')
df['ts_py'] = df['ts_py'].apply(datetime.fromtimestamp)
print(df)

# It is now: 1620338266.89658 seconds from Unix Epoch (00:00:00 UTC on 1 January 1970)
# ts_pd                           ts_py
# 2021-05-06 21:57:46  2021-05-06 17:57:46
```

#### Problem description
I would expect `to_datetime` to behave the same as `fromtimestamp`. That is, if returning a TZ-naive time, it should probably be  a localtime. If parsing a unix epoch timestamp, we know the value is in UTC, so leaving it TZ-unaware is a footgun as I think a naive user would expect either (1) localtime or (2) to have UTC tzinfo attached to prevent mingling with true localtimes. 

I encountered this problem because I was parsing timestamps from a couple of files. In one file were text-form timestamps, which were parsed as local-time. In the other were epoch-form timestamps, which were parsed as TZ-unaware UTC. If I unconditionally pass utc=True, now my text-form timestamps are mistakenly given UTC tzinfo. In the end I wrote a helper which only passes utc=True if the column is numerical.

This table shows the outputs and workaround:
|    | str                                                 | ts                                  | comment |
|---:|:----------------------------------------------------|:------------------------------------|--|
|  0 | pd.to_datetime(now.isoformat())                     | 2021-05-06 18:03:31.766199          ||
|  1 | datetime.fromtimestamp(now.timestamp())             | 2021-05-06 18:03:31.766199          ||
|  2 | datetime.utcfromtimestamp(now.timestamp())          | 2021-05-06 22:03:31.766199          |This is OK, I specifically asked for UTC not localtime.|
|  3 | pd.to_datetime(now.timestamp(), unit="s")           | 2021-05-06 22:03:31.766199112       |Not OK. I've now parsed a different time than if I had parsed isoformat() of the same time.|
|  4 | pd.to_datetime(now.timestamp(), unit="s", utc=True) | 2021-05-06 22:03:31.766199112+00:00 |OK, but should be default.|

#### Expected Output
| ts_pd | ts_py |
|--------|--------|
| 2021-05-06 21:53:42+00:00 | 2021-05-06 17:53:42|

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : 0.29.21
pytest           : 5.4.3
hypothesis       : None
sphinx           : 3.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.2
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.50.1
</details>

**Comment by ParfaitG** [comment] 2021-05-19 21:55
While not one of the authors of the datetime API in pandas but having discovered similar situation when parsing seconds from epoch and though source code is a bit involved to know for certain, my guess is `pd.to_datetime` is handling conversion differently due to the input:

- With `isoformat`  you are passing in a string representation of time without local timezone or offsets into `pd.to_datetime`. Without local timezone in string, datetime is assumed UTC. 
- With `now.timestamp()` you are passing in a float (precision down to nanoseconds) representation in local timezone into `pd.to_datetime`. With local timezone, datetime is implicitly converted to UTC.
 
Why assume and convert to UTC? For standardization across platforms, datetimes reflect UTC which stands for Coordinated Universal Time. Technically, all datetimes in [`pd.to_datetime`](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html) represent UTC where timezone awareness specify the hour offsets. For isoformat, had you set timezone with `now = datetime.now(tz=timezone.utc)`, the `pd.to_dateime` would convert to tz-aware datetime. No conversion appears to be made with `datetime.datetime` to `datetime64` where times are taken as is and assumed UTC.

Specifically, to illustrate by extending your example:

```python
import pandas as pd
from datetime import datetime, timezone

now = datetime.now()
utcnow = datetime.now(tz=timezone.utc)

df = pd.DataFrame({
    'ts_pd': pd.to_datetime([now.timestamp()], unit="s"),         # CONVERTS LOCAL TO UTC
    'ts_py': [now.timestamp()],                                   # AFTER APPLY, KEEPS LOCAL TIME AS UTC TIME
    'dt_iso': [pd.to_datetime(now.isoformat())],                  # STRING CAST, ASSUMED UTC
    'dt_iso_utc': [pd.to_datetime(utcnow.isoformat())],           # STRING CAST, KEEPS UTC W/ TZ
    'dt_local': [datetime.fromtimestamp(now.timestamp())],        # KEEPS LOCAL TIME AS UTC TIME
    'dt_utc': [datetime.utcfromtimestamp(now.timestamp())],       # KEEPS UTC TIME AS UTC TIME
    'pd_tz': pd.to_datetime(now.timestamp(), unit="s", utc=True)  # CONVERTS LOCAL TO UTC W/ TZ
}).assign(
    ts_py = lambda x: x['ts_py'].apply(datetime.fromtimestamp)
)

df.dtypes
# ts_pd              datetime64[ns]
# ts_py              datetime64[ns]
# dt_iso             datetime64[ns]
# dt_iso_utc    datetime64[ns, UTC]
# dt_local           datetime64[ns]
# dt_utc             datetime64[ns]
# pd_tz         datetime64[ns, UTC]

df.iloc[:, 0:2]
#                           ts_pd                      ts_py
# 0 2021-05-19 21:27:31.142882109 2021-05-19 16:27:31.142882
df.iloc[:, 2:4]
#                       dt_iso                       dt_iso_utc
# 0 2021-05-19 16:27:31.142882 2021-05-19 21:27:31.142882+00:00
df.iloc[:, 4:6]
#                    dt_local                     dt_utc
# 0 2021-05-19 16:27:31.142882 2021-05-19 21:27:31.142882
df.iloc[:, 6:]
#                                 pd_tz
# 0 2021-05-19 21:27:31.142882109+00:00
```

However, data is not entirely lost. As you can return the local timestamp by casting via [`pd.Timestamp`](https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html):

```python
pd.Timestamp(df.loc[0, "ts_pd"]).timestamp()
# 1621459651.142882

now.timestamp()
# 1621459651.142882
```
But not for [`to_pydatetime`](https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.to_pydatetime.html):

```python
df["ts_pd"].dt.to_pydatetime()[0].isoformat()
# 2021-05-19T21:27:31.142882

now.isoformat()
# 2021-05-19T16:27:31.142882
```

**Comment by vgoklani** [comment] 2021-12-23 02:00
<bump>

**Comment by jbrockmendel** [comment] 2023-01-25 22:59
It sounds like the main request here is asking to_datetime to see a float and assume it was created by a tznaive-pydatetime object's .timestamp() method and then reconstruct that datetime and _then_ localize it to UTC.

We cannot make this assumption.  The stdlib .timestamp() behavior with tznaive datetimes is a footgun (https://mail.python.org/archives/list/datetime-sig@python.org/thread/PT4JWJLYBE5R2QASVBPZLHH37ULJQR43/).  We should probably change ours to just raise.

**Comment by haydenflinner** [comment] 2023-01-31 10:37
Not quite, and I'm not sure my request can be satisfied, but let me phrase it like this. 

A Unix epoch timestamp, which I assume to be the primary use-case of to_datetime when called with an int/float value, _is_ UTC, and should have UTC timezone attached by default, because _not_ having TZ vaguely implies a local-timestamp, which a unix Epoch is not. UTC param should default to true if given a numerical value as input, or a series of those. Definition from wikipedia for a Unix timestamp: `It measures time by the number of seconds that have elapsed since 00:00:00 UTC on 1 January 1970, the beginning of the Unix epoch...`

from OP, but this time with Python's potentially confusing .timestamp() removed. 
Right now it is 1675160728 epoch time, let `nowe = 1675160728`.
|    | str                                                 | ts                                  | oldcomment | comment |
|---:|:----------------------------------------------------|:------------------------------------|--|--|
|  1 | datetime.fromtimestamp(nowe)             | datetime.datetime(2023, 1, 31, 5, 25, 28) || OK, this is my local time without TZ associated. |
|  2 | datetime.utcfromtimestamp(nowe)          | datetime.datetime(2023, 1, 31, 10, 25, 28) |This is OK, I specifically asked for UTC not localtime.| I guess this is OK since I asked for it, but it is a UTC timestamp as a naive object, which I guess the Python link you gave says is unidiomatic / likely to cause problems.
|  3 | pd.to_datetime(nowe * 1_000_000_000, unit="s")           | Timestamp('2023-01-31 10:25:28')       |Not OK. I've now parsed a different time than if I had parsed isoformat() of the same time.| Not OK, because it is a local-timestamp and it is known that epoch timestamps are UTC timestamps. This also means that to_datetime on ts.timestamp() yields different results than to_datetime on ts.isoformat()., which was the original confusion in OP.|
|  4 | pd.to_datetime(nowe * 1_000_000_000, unit="s", utc=True) | 2021-05-06 22:03:31.766199112+00:00 |OK, but should be default.| Good, should be default.|

I'm thus not asking for the assumption that a float was created by tznaive .timestamp, but instead to assume that a numerical value is a correct Unix timestamp, which it happens that a tz-naive .timestamp() creates based on the assumption that a tz-naive object is in localtime.

**Comment by wanghaiqiangk** [comment] 2023-06-07 10:35
Any new developments?

The internal of `pandas.Timestamp` is confusing and unpredicable.

If `now` is a standard epoch time (UTC), `assert pd.Timestamp.fromtimestamp(now).timestamp() == now` is `False`.

The Python module `datetime` assumes that the input timestamp is in standard UTC format and that the user is aware of this. However, `pandas.Timestamp` appears to use two different strategies for handling user input and storing data internally. It reads user input as a UTC timestamp and converts it to local time for output. But instead of storing that UTC timestamp in its internal data, it re-parses the local time as UTC and stores this value instead.

So, this accounts for why `assert pd.Timestamp.fromtimestamp(now).timestamp() == now` is `False` and why the result of subtracting them is the number of seconds in timezone offset.

**Comment by jbrockmendel** [comment] 2023-06-07 16:06
> If now is a standard epoch time (UTC), assert pd.Timestamp.fromtimestamp(now).timestamp() == now is False.

This is because .timestamp is a footgun, as I mentioned [above](https://github.com/pandas-dev/pandas/issues/41360#issuecomment-1404333696).

> If this is not going to be changed. What's the best practice to use pandas.Timestamp? For now, it's less error-prone if always explicitly specifying timezone.

The best practice if you have an int/float is to do `pd.Timestamp(item, tz="UTC")` or `pd.to_datetime(item, utc=True)`.

**Comment by wanghaiqiangk** [comment] 2023-06-08 08:46
That's true to specify either a timezone or just UTC for the best accuracy. However, I believe there are many applications where handling naive timestamp is their only consideration.

There are at least three methods we can use to create a `Timestamp` object from int/float,

- `pd.to_datetime()`
- `pd.Timestamp()`
- `pd.Timestamp.fromtimestamp()`

I've notices that `pd.to_datetime(now, unit='s')` == `pd.Timestamp(now, unit='s')` **!=** `pd.Timestamp.fromtimestamp(now)`. The semantic meaning here is to create a `Timestamp` object from the POSIX epoch. These three are supposed to be equal. However, the first two represent themselves using UTC strings, while the last one uses local time. This discrepancy is likely caused by the `.fromtimestamp()` method, which uses `datetime.fromtimestamp()` under the hood.

Before discussing whether we should add UTC timezone to an object by default, we'd better to uniform the representation of tz-naive object. They should either be strict UTC format or in local time format, but not both.

The stdlib `.timestamp()` can be a footgun when used with objects created from `.utcnow()` and `.utcfromtimestamp()`. However, they are semi-deprecated as mentioned in the mail. Other than those, I have been able to use `.timestamp()` without much trouble and am happy with it.

**Comment by haydenflinner** [comment] 2023-06-08 12:27
The issue I have is with `pd.to_datetime()`, not the standard library. A Unix timestamp is by definition in UTC. TZ-naive objects are presumed to be in local time. `to_datetime` not attaching UTC timestamp when parsing a Unix timestamp (unit='s') is thus a bug. I understand this would be both a subtle and a critical breaking change, so maybe we could add a new unit `epoch` or something to guide naive users towards the right behavior.

I spent months of on-and-off time wondering where I was going wrong with timezones before I figured out that Pandas is parsing a unix timestamp neither truly in local time (and thus returning tz-unaware) or truly in UTC time (and thus setting TZ to UTC). I was even more surprised to see that this differs from the standard library's fromtimestamp, which behaves reasonably IMO, since a naively created anydatetimelibrary.now() without timezone info is always in local time, by Unix/C tradition. I am not aware of a date library in any language which returns UTCs for `now` without also attaching some timezone info. I ran into this bug when converting from row-by-row parsing (using stdlib's fromtimestamp()) to vectorized pandas code (using `fromtimestamp`). 



Lib | Value
-- | --
Unix Time | 1686226162
EpochConveter.com Local Time| 8:09:22 AM [GMT-04:00] DST
EpochConverter.com GMT | 12:09:22 PM GMT
datetime.fromtimestamp(1686226162).isoformat() | 08:09:22 (tz-unaware == local)
pandas.to_datetime(1686226162, unit='s') | Timestamp('2023-06-08 12:09:22') (tz-unaware == **wrong**, this is supposed to be UTC, or if no TZ attached, local time)
pandas.to_datetime(1686226162, unit='s', utc=True) | Timestamp('2023-06-08 12:09:22+0000', tz='UTC')

**Comment by jbrockmendel** [comment] 2023-06-08 18:49
> to_datetime not attaching UTC timestamp when parsing a Unix timestamp (unit='s') is thus a bug

You're making the implicit assumption that any integer is a unix timestamp.  That is not the case in practice.

> TZ-naive objects are presumed to be in local time

That is a common interpretation, but not a universal one.  The alternative- that pandas uses- is that tznaive datetimes are abstract.  datetime(2023, 6, 8) means the same thing for different readers located in different timezones.

Changing the behavior of `pd.to_datetime(an_int, unit="s")` is very unlikely as it would introduce many inconsistencies.  If you have other suggestions that would improve the situation we're open to them.  Otherwise, you just need to be explicit when you want timezone-aware objects.

**Comment by haydenflinner** [comment] 2023-06-13 02:10
>You're making the implicit assumption that any integer is a unix timestamp. That is not the case in practice.

Do you mean when origin parameter is not the default Unix epoch? Or do you mean that a quantity of time following the Unix epoch is not by definition a Unix timestamp?


I don't expect any change to the unit param by default, just some documentation of a less footgunny way to use this function. For example the documentation says this:

>Constructing a [Timestamp](https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html#pandas.Timestamp) or [DatetimeIndex](https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.html#pandas.DatetimeIndex) with an epoch timestamp with the tz argument specified will raise a ValueError.

and it says this:

>The default is set at origin='unix', which defaults to 1970-01-01 00:00:00. Commonly called ‘unix epoch’ or POSIX time.

But there is no info box anywhere on the page, and none of the examples show, the fact that you should virtually always be adding (utc=True) when parsing a Unix epoch, since a Unix epoch is by definition in UTC, and mixing it tz-less with tz-naive datetimes acquired in other ways (parsing human-readable timestamps or calling .now()) is sure to lead to trouble. In fact I expect some day there will be a warning when the default kwargs are used to parse a Unix timestamp, that user likely meant to pass utc=True.

**Comment by jbrockmendel** [comment] 2023-07-02 21:05
I think I understand the confusion.  I'm used to ignoring the origin parameter when it is "unix".  Could change it to lib.no_default, and if a user explicitly specifies it as unix then set utc=True.

**Comment by haydenflinner** [comment] 2023-07-03 02:06
Perfect, I love that. How do we make that happen? Just a PR changing it?

**Comment by jbrockmendel** [comment] 2023-07-04 18:49
i think it would need a deprecation cycle.  so a PR changing the default to lib.no_default and, if "unix" is explicitly passed, issuing a warning that the behavior will change in  a future version

But per conversation with @MarcoGorelli, I'd ask if explicitly passing `origin="unix"` is really that much easier than passing `utc=True`?

**Comment by MarcoGorelli** [comment] 2023-07-04 19:56
Thanks for the discussion all

I really don't think this is worth breaking backwards compatibility over

I'd suggest documenting more clearly perhaps, but not changing behaviour

**Comment by MarcoGorelli** [comment] 2023-07-13 07:27
closing as per the above then, but thanks for the issue

**Closed by MarcoGorelli** 2023-07-13 07:27 UTC
Labels: Bug, Docs, Timeseries, Needs Discussion, Closing Candidate
