### ISSUE TITLE
Why [] operation on float index doesn't work the same way as int index?

### ISSUE THREAD

**Issue by GYHHAHA** [pandas-dev/pandas#31344] opened 2020-01-27 15:24 UTC
#### Code Sample, a copy-pastable example if possible

```python
>>> s1 = pd.Series(list('abcde'),index=[5,7,9,11,13])
>>> s2 = pd.Series(list('abcde'),index=[5.5,7.5,9.5,11.5,13.5])
>>> print(s1[2:])
>>> print(s2[2:])
9     c
11    d
13    e
dtype: object
5.5     a
7.5     b
9.5     c
11.5    d
13.5    e
dtype: object
```
#### Problem description

I'm a little confused with the [] operation on numerical index.
It seems that when [] applied to the int index, it is compared with the exact position, whereas the [] operation on float is compared with the index's value.
Thanks!

**Comment by MarcoGorelli** [comment] 2020-01-27 16:01
Thanks for the report, seems like it's an open issue (see #7501)

In the meantime, to avoid ambiguity, it's recommended to use either `.loc` for label-based indexing, or `.iloc` for position-based indexing

**Comment by mroeschke** [comment] 2021-07-27 05:27
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/7501

**Closed by mroeschke** 2021-07-27 05:27 UTC
Labels: Indexing
