### ISSUE TITLE
ENH: Drop dependency on pytz in favor of zoneinfo

### ISSUE THREAD

**Issue by aDramaQueen** [pandas-dev/pandas#47748] opened 2022-07-16 12:26 UTC
### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

Hi,
pytz is/was a good llibrary. But it's obsolete since [PEP 615](https://peps.python.org/pep-0615/). In the long run, you should not use 3rd party package, but the language integrated functionality.
Even big frameworks like Django [(Django Release Info)](https://docs.djangoproject.com/en/4.0/releases/4.0/#what-s-new-in-django-4-0) already dropped pytz.

### Feature Description

Nothing should change for any user, therefore i post here standard code:

`pd.Timestamp('2017-01-01T12')`

### Alternative Solutions

Ignore it and hope pytz will be supported as long as possible

**Comment by phofl** [comment] 2022-07-16 14:56
Hi,

thabks for your report. This is a duplicate of #34916

**Closed by phofl** 2022-07-16 14:56 UTC
Labels: Enhancement, Needs Triage
