### ISSUE TITLE
json_normalize skips an entry in a pymongo cursor

### ISSUE THREAD

**Issue by languitar** [pandas-dev/pandas#30323] opened 2019-12-18 14:36 UTC
I am sorry for not being able to provide a reproducible example, but any attempt to reduce the problem to something limited makes the problem disappear.

```python
In [54]: res = client.events.api.longterm.find({'foo': 'bar'})

In [55]: res.count()
Out[55]: 76845

In [56]: len(pd.io.json.json_normalize(res))
Out[56]: 76844

In [57]: res = client.events.api.longterm.find({'foo': 'bar'})

In [58]: len(pd.io.json.json_normalize(list(res)))
Out[58]: 76845
```
#### Problem description

I have a pretty large collection of documents in MongoDB, which I am querying using pymongo. The resulting cursor is passed to `pd.io.json.json_normalize` to convert the resulting data into a data frame. In one example, which I am unfortunately unable to reduce to something reproducible, a single element of the 76845 entries in the cursor is not present in the resulting data frame. If I convert the cursor to a list before using `json_normalize`, all entries are present. The affected document itself looks completely sane and without anything suspicious. Moreover, the default for `json_normalize` should be to raise errors and not to swallow rows.

#### Expected Output

All 76845 rows are present in the result when passing the cursor directly to `json_normalize`.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.0.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.3-arch1-1
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.10.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by mroeschke** [comment] 2020-05-08 21:22
Can this be reproduced without the external library? What type of object is `res`?

**Comment by languitar** [comment] 2020-05-10 18:47
Unfortunately, at that time I was unable to get a reproduction without a MongoDB result.

The result type of `find` is a [`Cursor`](https://pymongo.readthedocs.io/en/stable/api/pymongo/cursor.html#pymongo.cursor.Cursor)

**Comment by alex005005** [comment] 2020-06-11 08:52
Hi,
I can reproduce using this code and data. Transforming to list() before json_normalize fixes the issue for me - so I don't know if I'm just using it incorrectly. 

`#%%
import json
from pymongo import MongoClient

client = MongoClient('localhost', 27017)
db = client['bikedata']
testcollection = db['test']

with open('/home/alex/Desktop/db_berlin_neu_aggregate_sort_.json.txt') as f:
    file_data = json.load(f)

testcollection.insert_many(file_data)

doc = testcollection.aggregate([
    { "$sort" : {"date" : -1 } },
    { "$limit" : 50 },
    # { "$unwind" : {
    #     "path" : "$items"
    #     }
    # },
    { "$unset" : ["items.rentalObject.href", "items.rentalObject.attributes", "items.position.type", "items.area.href", "items.distance", "items._links" ]},
    ])

df = json_normalize(doc)
df.head(50)
#%%
doc = testcollection.aggregate([
    { "$sort" : {"date" : -1 } },
    { "$limit" : 50 },
    # { "$unwind" : {
    #     "path" : "$items"
    #     }
    # },
    { "$unset" : ["items.rentalObject.href", "items.rentalObject.attributes", "items.position.type", "items.area.href", "items.distance", "items._links" ]},
    ])

df = json_normalize(list(doc))
df.head(50)
#%%
client.close()`


[db_berlin_neu_aggregate_sort_.json.txt](https://github.com/pandas-dev/pandas/files/4763666/db_berlin_neu_aggregate_sort_.json.txt)

**Comment by alex005005** [comment] 2020-06-11 09:05
Hi,
I can reproduce with following code and data.

Problem doesn't occur if I transform to list before json_normalize - maybe I'm using it incorrectly and that is how it's supposed to work.


`#%%

import json
from pymongo import MongoClient

client = MongoClient('localhost', 27017)
db = client['bikedata']
testcollection = db['test1']

with open('/home/alex/Desktop/db_berlin_neu_aggregate_sort_.json.txt') as f:
    file_data = json.load(f)

testcollection.insert_many(file_data)
#%%
doc = testcollection.aggregate([
    { "$sort" : {"date" : -1 } },
    { "$limit" : 50 }
    ])

df = json_normalize(doc)
df.head(50)

#%%

doc = testcollection.aggregate([
    { "$sort" : {"date" : -1 } },
    { "$limit" : 50 }
    ])

df = json_normalize(list(doc))
df.head(50)

#%%
f.close()
client.close()`

[db_berlin_neu_aggregate_sort_.json.txt](https://github.com/pandas-dev/pandas/files/4763729/db_berlin_neu_aggregate_sort_.json.txt)

**Comment by miriambenvil** [comment] 2021-03-02 12:21
Hi all,

I have reproduced the error and identified why it is happening

### Code sample

```python
import mongomock
import pandas as pd
test_data = [
    {'_id': 1, 'name': 'Miriam'},
    {'_id': 2, 'name': 'Peter'}
]
mongo_client = mongomock.MongoClient()
mongo_client["db_test"]["col_test"].insert_many(test_data)
cursor = mongo_client["db_test"]["col_test"].find({})
df = pd.json_normalize(cursor)
```

### Output
```python
    _id   name
0    2   Peter
```

### Expected output
```python
   _id     name
0    1   Miriam
1    2    Peter
```

### Problem description
We are using pyarrow cursor as input for `json_normalize` with nullable `record_path` argument. This function itself checks if we have nested structures in the input to be transformed so it's evaluating the first element of the document:

```python
any([isinstance(x, dict) for x in y.values()] for y in data)
```

Hope it helps!
Since it is a cursor next time we want to read the cursor we have "lost" that element.

### Solution
```python
df = pd.json_normalize(list(cursor))
```

**Comment by simonjayhawkins** [comment] 2022-06-03 15:02
This is now fixed. (in pandas 1.3) in commit: [52bdfdc286d678135da87d2e3a797fa74fb9f9f1] BUG: Fix pd.json_normalize to not skip the first element of a generator input (#38698)

#35923 was a duplicate of this issue.

appropriate testing added in #38698, so can just close this as fixed.

**Closed by simonjayhawkins** 2022-06-03 15:02 UTC
Labels: Bug, IO JSON, Compat
