### ISSUE TITLE
Merge matches np.nan and None while merging

### ISSUE THREAD

**Issue by shenaimm** [pandas-dev/pandas#22618] opened 2018-09-06 10:49 UTC
#### Code Sample

```
pd.merge(pd.DataFrame({'a':[None,np.nan,'A','B']}),pd.DataFrame({'a':[None,np.nan,'A']}))

```
#### Problem description

The ouput I get is this
      a
0  None
1  None
2   NaN
3   NaN
4     A

#### Expected Output
The ideal behavior should be
      a
1     A

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-134-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_IN
LOCALE: en_IN.ISO8859-1
pandas: 0.22.0
pytest: 3.3.2
pip: 18.0
setuptools: 38.4.0
Cython: 0.27.3
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.6
patsy: 0.5.0
dateutil: 2.6.0
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.2
openpyxl: 2.4.10
xlrd: 1.0.0
xlwt: None
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.1
pymysql: None
psycopg2: 2.7.4 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment] 2018-09-06 15:42
Arguably a duplicate of #22491 though this does call out `None` as an extra consideration.

Investigation and PRs are welcome

**Comment by mroeschke** [comment] 2021-07-21 04:37
Closing as duplicate of https://github.com/pandas-dev/pandas/issues/32306 with a more recent discussion on the future policy we want.

**Closed by mroeschke** 2021-07-21 04:37 UTC
Labels: Bug, Missing-data, Reshaping
