### ISSUE TITLE
ENH: Add support for `*args` in apply-like functions.

### ISSUE THREAD

**Issue by amotzop** [pandas-dev/pandas#48582] opened 2022-09-16 11:45 UTC
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I think it would be nice if all the various `apply`-like functions had the same way to pass extra arguments for the applied function.
The state now is as follows:
`Series/DataFrame.apply` - can accept `**kwargs`, but to pass non-keyword argument there you pass a tuple `args`, instead of `*args`.
`DataFrame.applymap` - can accept `**kwargs`, but there is no way to pass non-keyword arguments.
`Index/Series.map` - no way to pass any additional arguments.
`GroupBy.apply` - can pass arguments using `*args, **kwargs`.
`GroupBy/Series/DataFrame.transform` - can pass arguments using `*args, **kwargs`.

I think that the `*args, **kwargs` way is the cleanest, so I propose to change the implementation of all other cases to conform to it.

I also think that passing extra arguments to `Series/DataFrame.apply` using the `args` tuple should be deprecated (but while you have both options they should be mutually exclusive).

### Feature Description

The implementation seems easy enough/already exists in most cases.
For example in the `Series.apply` case:
```python
def apply(func, convert_dtype=True, args=(), *nargs, **kwargs):
    if args != () and nargs != ():
        raise ValueError("Can only pass extra arguments using args or nargs, not both")
    args = args if args != () else nargs
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
```

### Alternative Solutions

As I said, it seems that in many places this change is already implemented and just needs to be applied everywhere.

**Comment by Pvlb1998** [comment] 2022-10-20 03:50
Take

**Comment by Pvlb1998** [comment] 2022-11-03 18:45
Are the functions mentioned on the description (like Series/DataFrame.apply, DataFrame.applymap...) the only places where we need to apply the code on the solution? 

Also, is there any possibility to show some examples where I can test these functions? It's just to make sure the code is working properly after the modifications.

**Comment by mroeschke** [comment] 2022-11-03 20:16
@Pvlb1998 just a heads up, please wait for confirmation from members of the core team regarding support of this functionality before moving forward.

**Comment by Pvlb1998** [comment] 2022-11-06 21:57
@mroeschke Oh it's alright! Even if this function doesn't properly work, I would still like to work on it purely for learning (doesn't have to be aproved). But even after making some modifications I still don't know how to test it. If it's possible, could you provide some cases of test so I can at least check if there's anything wrong with my modifications?

**Comment by rhshadrach** [comment] 2022-12-15 01:50
This looks like  a duplicate of https://github.com/pandas-dev/pandas/issues/40112

**Comment by phofl** [comment] 2022-12-18 23:25
Yep agreed, closing then

**Closed by phofl** 2022-12-18 23:25 UTC
Labels: Enhancement, Apply, Closing Candidate
