### ISSUE TITLE
BUG: Cannot use pd.NA in a series with float dtype

### ISSUE THREAD

**Issue by thehomebrewnerd** [pandas-dev/pandas#36587] opened 2020-09-23 21:33 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
pd.Series([1.1, pd.NA], dtype='float64')
```

#### Problem description

Similar to the issue documented in #36586, if the goal of `pd.NA` is to provide a missing indicator that can be used across datatypes, it should also work with a `float` datatype. Currently, if a user attempts to use a `pd.NA` value in a series with dtype of float, an error is raised: `TypeError: float() argument must be a string or a number, not 'NAType'`.

This also appears related to the issue mentioned in #36585

#### Expected Output

```python
import pandas as pd
pd.Series([1.1, pd.NA], dtype='float64')

0    1.1
1    <NA>
dtype: float64
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 40.8.0
Cython           : None
pytest           : 6.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by dsaxton** [comment] 2020-09-23 22:51
Nullable float dtypes don't exist yet but are being worked on, see https://github.com/pandas-dev/pandas/pull/34307.

**Comment by TomAugspurger** [comment] 2020-09-24 11:28
Closing this since it's a duplicate of https://github.com/pandas-dev/pandas/issues/32265#issuecomment-627004139.

FYI @thehomebrewnerd, your "expected output" section isn't possible. `pd.NA` is not a float, so it can't be stored in a NumPy float64 array. That should raise.

**Closed by TomAugspurger** 2020-09-24 11:28 UTC
Labels: NA - MaskedArrays

**Comment by thehomebrewnerd** [comment] 2020-09-24 12:37
@TomAugspurger I guess I didn't search deep enough to see this was being worked in other issued. In any case, I understand your point. As long as there is afloat dtype of some sort that can handle `pd.NA`, analogous to `Int64`, that seems fine to me.
