### ISSUE TITLE
DOC: make scripts/validate_docstrings.py GL01 GL02 be able to exclude a list of known docstrings to ignore 

### ISSUE THREAD

**Issue by dcreekp** [pandas-dev/pandas#25120] opened 2019-02-03 16:48 UTC
#### Problem description

We want this script to return zero errors:
```
$ ./scripts/validate_docstrings.py --prefix=pandas.Time --errors=GL01,GL02
```
to add GL01 and GL02 to the continuous integration checks.
However the remaining errors are caused by docstrings that are inherited from dependencies. Specifically, cpython's datetime module which we do not want to touch.

from trying to fix this [issue](https://github.com/pandas-dev/pandas/issues/24070)

#### Expected Output

For the above script to return zero errors.

**Comment by mroeschke** [comment] 2021-11-20 07:20
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/25324

**Closed by mroeschke** 2021-11-20 07:20 UTC
Labels: Docs
