### ISSUE TITLE
CLN: start using numpy-1.7 API

### ISSUE THREAD

**Issue by immerrr** [pandas-dev/pandas#8329] opened 2014-09-20 07:40 UTC
Now that numpy-1.6 support is dropped we could proceed to use np-1.7 API.

This involves fixing a macro or two deep down in pandas internals, but otherwise should be pretty straightforward. As a bonus we can get rid of these annoying build warnings:

```
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipandas/src/klib -Ipandas/src -I/home/immerrr/.conda/envs/pandas/lib/python2.7/site-packages/numpy/core/include -I/home/immerrr/.conda/envs/pandas/include/python2.7 -c pandas/index.c -o build/temp.linux-x86_64-2.7/pandas/index.o
In file included from /home/immerrr/.conda/envs/pandas/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /home/immerrr/.conda/envs/pandas/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/immerrr/.conda/envs/pandas/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pandas/index.c:244:
/home/immerrr/.conda/envs/pandas/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
```
xref https://github.com/pydata/numexpr/pull/228/files

**Comment by gfyoung** [comment] 2017-05-16 07:17
@jreback : I think you can close this now that #15209 has been issued.

**Comment by jreback** [comment] 2017-05-16 10:19
@gfyoung your reference seems to be off, and this is certainly not closed. we have warning messages in the c-code. need to set a macro.

**Comment by gfyoung** [comment] 2017-05-16 13:31
@jreback : I meant to refer to the issue where we are dropping `numpy < 1.9`.  Certainly that should encapsulate this one?

**Comment by jreback** [comment] 2017-05-16 13:58
this refers to the c api
we are actually using the pre 1.7 one
that's the point of setting the macro

so this issue needs to be fixed before (though of course will work when compiling on later numpy anyhow as they haven't removed the old api)

**Comment by jbrockmendel** [comment] 2018-07-13 00:36
According to the cython docs this warning should be ignored.  I take that to mean we jus have to wait for them to fix it there (no indication if/when that will be).  This is not actionable.  Closing.

**Closed by jbrockmendel** 2018-07-13 00:36 UTC
Labels: Compat, Dependencies, good first issue

**Comment by gfyoung** [comment] 2018-07-13 00:38
@jbrockmendel : Could you add a link for future reference?

**Comment by jreback** [comment] 2018-07-13 00:59
i believe u can set a flag about the api to turn off the old api

**Comment by jbrockmendel** [comment] 2018-07-13 02:44
https://cython.readthedocs.io/en/latest/src/reference/compilation.html#configuring-the-c-build

> Despite this, you will still get warnings like the following from the compiler, because Cython is using a deprecated Numpy API:
>
>> .../include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>
> For the time being, it is just a warning that you can ignore.

@jreback 
> i believe u can set a flag about the api to turn off the old api

The issue isn't pandas using the old API, it is cython using it.  As long as cython-generated C is using the old API, we're not getting rid of those warnings.  The relevant flag would be to add to `setup.macros` the entry `('NPY_NO_DEPRECATED_API', 'NPY_1_7_API_VERSION')`, but doing so causes compile-time errors.
