### ISSUE TITLE
BUG: pandas EWM fails silently if data types are float32 instead of float64

### ISSUE THREAD

**Issue by PCerles** [pandas-dev/pandas#42452] opened 2021-07-09 00:33 UTC
- [X ] I have checked that this issue has not already been reported.

- [ X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import numpy as np
import pandas as pd

kk = pd.DataFrame(np.random.rand(20, 3))
kk = kk.astype(np.float32)
print(kk.ewm(alpha=0.5, axis=1).mean().shape)
# (20, 0)

kk = kk.astype(np.float64)
print(kk.ewm(alpha=0.5, axis=1).mean().shape)

# (20, 3)
```

#### Problem description

This should not depend on dtypes.

#### Output of ``pd.show_versions()``

<details>

commit           : 7c48ff4409c622c582c56a5702373f726de08e96
python           : 3.7.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.5.0
Version          : Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.5
numpy            : 1.17.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 57.0.0
Cython           : None
pytest           : 6.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.23.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : 0.4.1
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : 0.17.1
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : 1.3.19
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : 0.53.1

</details>

**Comment by rhshadrach** [comment] 2021-07-09 02:42
@PCerles - can you provide a reproducible example and expected output.

**Comment by PCerles** [comment] 2021-07-09 03:28
Added!

**Comment by rhshadrach** [comment] 2021-07-09 04:32
Thanks - it appears to me the issue is in the usage of `select_dtypes`:

https://github.com/pandas-dev/pandas/blob/57bb1657a3530a2576a5d05541510840ebe9fd91/pandas/core/window/rolling.py#L225-L231

This drops float32 columns. Under the current implementation, allowing the float32 columns to stay they would then become float64 (even if the cast is removed from this block!), which is perhaps undesirable. Further investigations and PRs to improve are welcome.

**Comment by debnathshoham** [comment] 2021-07-21 18:09
take

**Comment by simonjayhawkins** [comment] 2021-08-03 10:30
The code sample appears to worked in 1.1.5 and the issue not confined to EWM but rolling in general. (`test_rolling_float_dtype` added in #42650)

first bad commit: [00a510bfc0416d890a385697a8a0e5127602f9ec] [BUG]: Rolling.sum() calculated wrong values when axis is one and dtypes are mixed (#36458)

cc @phofl

**Comment by simonjayhawkins** [comment] 2021-08-03 10:38
maybe duplicate of #41779

**Closed** 2021-08-04 04:23 UTC
Labels: Bug, Dtypes, Regression, Window
