### ISSUE TITLE
BUG: specifying fill_value in pandas.DataFrame.shift() messes with index of empty dataframes

### ISSUE THREAD

**Issue by brunocous** [pandas-dev/pandas#41264] opened 2021-05-02 15:39 UTC
- [ x] I have checked that this issue has not already been reported.

- [ x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

# create empty df, and set a multi index
empty_df = pd.DataFrame(columns=["a", "b", "c"])
multi_index_empty_df = empty_df.set_index(keys=["a", "b"])

# index is different when applying shift on grouping when specifying a fill value
assert multi_index_empty_df.groupby(["a","b"]).shift(1).index.names == multi_index_empty_df.groupby(["a","b"]).shift(1, fill_value=0).index.names

```

#### Problem description
I discovered this problem when a unit test failed on a function that performed a groupby and shift on an empty dataframe.

Specifying `fill_value` in pandas.DataFrame.shift() should not alter the index that was set on a dataframe. This is not the case for empty dataframes with a multi-index, as the example above shows. 

#### Expected Output
When executing:
```python
multi_index_empty_df.groupby(["a","b"]).shift(1).index.names
```
I get the output:
```
FrozenList(['a', 'b'])
```

But when executing
```python
multi_index_empty_df.groupby(["a","b"]).shift(1, fill_value=0).index.names
```
I should get the same output, but instead I get
```
FrozenList([None])
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 18.1
setuptools       : 40.6.3
Cython           : 0.29.2
pytest           : 4.0.2
hypothesis       : None
sphinx           : 1.8.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.2
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 3.2.2
numexpr          : 2.6.8
odfpy            : None
openpyxl         : 2.5.12
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 4.0.2
pyxlsb           : None
s3fs             : None
scipy            : 1.5.1
sqlalchemy       : 1.2.15
tables           : 3.4.4
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.2
numba            : 0.41.0

</details>

**Comment by mzeitlin11** [comment] 2021-05-02 19:30
Thanks for the report @brunocous. This works on master (and latest pandas version (1.2.4)), but could probably use a test.

**Comment by benbogart** [comment] 2021-05-03 22:55
I can confirm the behavior exists in 1.2.4.  Can I take this issue?

**Comment by benbogart** [comment] 2021-05-03 22:58
take

**Comment by benbogart** [comment] 2021-05-04 22:53
This appears to be have already been fixed on the master branch (1.3.0.dev0+1510.gfea6799dba)

![Screen Shot 2021-05-04 at 6 52 40 PM](https://user-images.githubusercontent.com/29614010/117079535-f2844e00-ad09-11eb-9947-c9969611c624.png)

**Comment by brunocous** [comment] 2021-05-05 10:54
My bad, I should first have checked my pandas version! Let's close this issue.

**Comment by phofl** [comment] 2021-05-12 09:24
Reopening until investigated if this is tested

**Comment by benbogart** [comment] 2021-05-12 11:49
@phofl Do you mean until there is a unittest?  This is tested and working in 1.3.0.dev0+1510.gfea6799dba as posted above.  I can do further testing but am not sure what is required.

**Comment by phofl** [comment] 2021-05-12 11:51
Could you link the test covering this?

**Comment by benbogart** [comment] 2021-05-12 18:49
While the immediate issue looks resolved, there may still be unexpected behavior in the groupby shift method on empty dataframes.

It does not seem necessary to have a multi index to reproduce the issue.

Working with the current master: 1.3.0.dev0+1510.gfea6799dba

shift without a `fill_value` produces the following:
```
>>> empty_df.groupby(['a']).shift(1) gives:
Empty DataFrame
Columns: [b, c]
Index: []

>>> empty_df.groupby(['a']).shift(1).index.names
[None]
```
![Screen Shot 2021-05-12 at 2 37 43 PM](https://user-images.githubusercontent.com/29614010/118027221-af406580-b32f-11eb-98de-c409f1a283f3.png)

But when including a `fill_value` a named index is left behind

```
>>> empty_df.groupby(['a']).shift(1, fill_value=0)
Empty DataFrame
Columns: [a, b, c]
Index: []

>>> empty_df.groupby(['a']).shift(1, fill_value=0).index.names
['a']
```
![Screen Shot 2021-05-12 at 2 38 50 PM](https://user-images.githubusercontent.com/29614010/118027398-e0209a80-b32f-11eb-9620-3dd4a9460db4.png)

The same is true when grouping by multiple columns
```
>>> empty_df.groupby(['a','b']).shift(1, fill_value=0)
Empty DataFrame
Columns: [a, b, c]
Index: []

>>> empty_df.groupby(['a','b']).shift(1, fill_value=0).index.names
['a', 'b']
```
![image](https://user-images.githubusercontent.com/29614010/118027444-ef074d00-b32f-11eb-93b5-c9926ed9d3d0.png)


This is different behavior from what happens if the DataFrame contains data.

```
>>> num_df = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
>>> num_df.groupby(['a','b']).shift(1, fill_value=0)
   a  b  c
0  0  0  0
1  0  0  0
2  0  0  0

>>> num_df.groupby(['a','b']).shift(1, fill_value=0).index.names
[None]
```
![image](https://user-images.githubusercontent.com/29614010/118027527-06463a80-b330-11eb-8c3e-cb18cf6b672e.png)

However, the original issue is resolved because this is no longer a problem if the groupby columns are already set as the index.
```
>>> empty_df.set_index(['a','b']).groupby(['a','b']).shift(1, fill_value=0)
Empty DataFrame
Columns: [c]
Index: []

>>> empty_df.set_index(['a','b']).groupby(['a','b']).shift(1, fill_value=0).index.names
['a', 'b']
```
![image](https://user-images.githubusercontent.com/29614010/118028365-fa0ead00-b330-11eb-9ec2-c1576145c025.png)


Can I consider this part of the same bug and pursue it here or does it need a separate bug tracker?

**Comment by IamJasonBian** [comment] 2021-09-12 05:42
Is it ok if I take this bug?

To clarify, in the empty dataframe case should all index.names contain None output after the column is groupby and shifted.



```
test1_1 = empty_df.groupby(['a']).shift(1)
test1_2 = empty_df.groupby(['a']).shift(1).index.names

test2_1 = empty_df.groupby(['a']).shift(1, fill_value=0)
test2_2 = empty_df.groupby(['a']).shift(1, fill_value=0).index.names

test3_1 = empty_df.groupby(['a','b']).shift(1, fill_value=0)
test3_2 = empty_df.groupby(['a','b']).shift(1, fill_value=0).index.names
```
For the case when the DataFrame contains data, should the output match the behavior for the empty dataframe. 

```
num_df = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})

test4_1 = num_df.groupby(['a','b']).shift(1, fill_value=0)
test4_2 = num_df.groupby(['a','b']).shift(1, fill_value=0).index.names
```

**Comment by benbogart** [comment] 2021-09-13 01:17
@IamJasonBian I have unassigned myself so you should be able to take it now.

I didn't end up having time to get into this.  I'm glad you will take it over.

**Comment by IamJasonBian** [comment] 2021-09-13 22:44
take

**Comment by IamJasonBian** [comment] 2021-09-15 20:35
@benbogart, this appears fixed on the current master as well (1.33). Can you confirm on your end? I'll add a unittest for this if it looks good. 

![image](https://user-images.githubusercontent.com/16582383/133505516-7cb81146-3d5d-480e-a74a-1039681da61c.png)

**Comment by benbogart** [comment] 2021-09-15 21:29
I believe there are still unresolved issues around groupby.shift detailed [here](https://github.com/pandas-dev/pandas/issues/41264#issuecomment-840017943).  My sense is that these are part of the same issue and should be fixed as part of this request, but I didn't get any other opinions on that.

**Comment by IamJasonBian** [comment] 2021-09-15 23:46
@benbogart, I replicated all the operations in your comment and there doesn't seem to be an issue for 1.3.3. Nevertheless, I'll start on test cases to prevent regression to this bug.

**Comment by benbogart** [comment] 2021-09-16 01:26
Perfect. Thanks!

--- original message ---
On September 15, 2021, 7:46 PM EDT ***@***.*** wrote:



@benbogart, I replicated all the operations in your comment and there doesn't seem to be an issue for 1.3.3. Nevertheless, I'll start on test cases to prevent regression to this bug.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Closed** 2021-10-31 14:58 UTC
Labels: Groupby, good first issue, Needs Tests, Index
