### ISSUE TITLE
BUG:  DataFrameGroupBy.transform with engine='numba' reorder output by index

### ISSUE THREAD

**Issue by havakv** [pandas-dev/pandas#57069] opened 2024-01-25 12:36 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({'vals': [0, 1, 2, 3], 'group': [0, 1, 0, 1]})
df.index = df.index.values[::-1] #reverse index

def foo(values, index):
    return values 

df.groupby('group')['vals'].transform(foo, engine='numba')
# wrong output:
# 3    3.0
# 2    2.0
# 1    1.0
# 0    0.0
# Name: vals, dtype: float64
```

### Issue Description

`DataFrameGroupBy.transform` with `engine='numba'` gives results that are ordered by the index values (and type has changed which is less important). This gives the wrong order unless the index is monotonically increasing. From what I can see we get the correct `values` and `index` in the `foo` function (same ordering as the dataframe), but this are ordered by the `index` before concatenating the results to the final series. This differs from the behaviour when called without `engine='numba'` (see below).

### Expected Behavior

The example above should produce the same results as
```python
df.groupby('group')['vals'].transform(lambda x: x)

```
with output
```
3    0
2    1
1    2
0    3
Name: vals, dtype: int64
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : f538741432edf55c6b9fb5d0d496d2dd1d7c2457
python                : 3.11.7.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.2.0
Version               : Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0
numpy                 : 1.26.3
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 69.0.3
pip                   : 23.3.2
Cython                : None
pytest                : None
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : None
IPython               : 8.20.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : 0.58.1
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : None
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2023.4
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment] 2024-01-26 03:28
Thanks for the report, confirmed on main. Further investigations and an PRs to fix are welcome!

cc @lithomas1

**Comment by andremcorreia** [comment] 2024-03-06 22:48
take

**Comment by andremcorreia** [comment] 2024-03-25 00:44
Hello, after finding a solution to this issue, I encountered a failing local test: "pytest pandas/tests/groupby/transform/test_numba.py::test_index_data_correctly_passed," which, if I undestood correctly, currently expects the results to be in the wrong order due to this bug.
(test in question for reference)
```
def f(values, index):
        return index - 1
df = DataFrame({"group": ["A", "A", "B"], "v": [4, 5, 6]}, index=[-1, -2, -3])
result = df.groupby("group").transform(f, engine="numba")
expected = DataFrame([-4.0, -3.0, -2.0], columns=["v"], index=[-1, -2, -3])
```
It expects a dataframe in which index -1 corresponds to the value -4, index -2 to the value -3, and index -3 to the value -2. I believe the intended behavior would be index -1, value -2, index -2, value -3, and index -3, value -4.
I'd just like to make sure I'm not misunderstanding the test before modifying it and moving to make a pull request for the issue.

**Comment by rhshadrach** [comment] 2024-03-25 01:12
Agreed - I think this is saying the same, but I would think the expected here should be:

    expected = DataFrame([-2.0, -3.0, -4.0], columns=["v"], index=[-1, -2, -3])

**Closed** 2024-03-28 22:42 UTC
Labels: Bug, Groupby, numba, Transformations
