### ISSUE TITLE
ENH: speed up to_excel

### ISSUE THREAD

**Issue by PeterTrefonasIv** [pandas-dev/pandas#42652] opened 2021-07-21 20:02 UTC
#### Is your feature request related to a problem?

to_excel could be faster

#### Describe the solution you'd like

openpyxl's write only workbook is very fast and should be used
https://openpyxl.readthedocs.io/en/stable/optimized.html

```python
# Your code here, if applicable
def to_excel_fast(df,name):
	wb = openpyxl.Workbook(write_only = True)
	ws=wb.create_sheet()
	ws.title = "df"

	#Set up header row
	col_row = []
	BOLD_FONT = openpyxl.styles.Font(bold=True)
	BOTTOM_LEFT_RIGHT_BORDER = openpyxl.styles.Border(bottom=openpyxl.styles.Side(style='thin'),left=openpyxl.styles.Side(style='thin'),right=openpyxl.styles.Side(style='thin'))
	CENTER_ALIGNMENT_NO_WRAP = openpyxl.styles.Alignment(horizontal='center')
	for column in df.columns:
		newCell = openpyxl.cell.WriteOnlyCell(ws,value=column)
		newCell.font = BOLD_FONT
		newCell.border = BOTTOM_LEFT_RIGHT_BORDER
		newCell.alignment = CENTER_ALIGNMENT_NO_WRAP
		col_row.append(newCell)
	ws.append(col_row)

	#Add data
	for i in range(len(df)):
		ws.append(tuple(df.iloc[i]))
	wb.save(name)
```

**Comment by phofl** [comment] 2021-07-21 20:30
Duplicate of #41681

**Closed** 2021-07-23 02:20 UTC
Labels: Closing Candidate, Duplicate, Enhancement, IO Excel
