### ISSUE TITLE
BUG: DataFrame.transform(dict) drops columns not mentioned in the dict

### ISSUE THREAD

**Issue by tilusnet** [pandas-dev/pandas#38296] opened 2020-12-04 19:54 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

I may have a dataframe with 100 columns, of which I want to transform 3.
`DataFrame.transform()` accepts a dict with column -> function mappings, therefore my intuition is to provide 3 mappings for the 3 columns I want transformed. However, upon providing such a mapping dict, the function drops the non mentioned 97 columns.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# create a dataframe with 100 columns
d = {'col%d' % i: [0] for i in range(100)}
df = pandas.DataFrame(d)

# transform 3 arbitrary columns with a function
func42 = lambda x: 42
df.transform({
    'col10': func42,
    'col20': func42,
    'col42': func42
})

```

#### Problem description

The transformation lost the 97 columns for which there was no transformation mapping provided.
The natural intuition is to preserve all columns that were not mentioned in the transformation.

#### Expected Output

A dataframe containing all 100 columns: the 3 transformed columns with the rest of the 97 columns untouched.
The current implementation returns 3 columns.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.7.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-123-generic
Version          : #126~16.04.1-Ubuntu SMP Wed Oct 21 13:48:05 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.1.4
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.3
setuptools       : 49.6.0.post20201009
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 5.8.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by rhshadrach** [comment] 2020-12-05 01:33
Returning only 3 columns is the desired behavior, you can perform your operation as:

```
df[['col10', 'col20', 'col42']] = df.transform({
    'col10': func42,
    'col20': func42,
    'col42': func42
})
```

**Comment by tilusnet** [comment] 2020-12-05 18:49
Thanks, but I consider this a rather unfavourable workaround.
It doesn't even work with method chaining. Consider this common use case scenario:
```
df = pandas.read_csv(...)\
     ...
     .transform(...)\
     .apply(...)\
     .drop(...)\
     .fillna(...)\
     ...
```

Out of curiosity why did you say this is not a Bug?
It clearly doesn't work in line with the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.transform.html): "Produced DataFrame will have same axis length as self." Contradiction: self had 100 length (columns), produced dataframe has only 3. => Bug.

**Comment by jreback** [comment] 2020-12-05 18:54
@tilusnet axis is rows

this is defined behavior and not a bug

you can use .assign to achieve fluent behavior easily

**Closed** 2020-12-05 18:54 UTC
Labels: Usage Question

**Comment by tilusnet** [comment] 2020-12-05 19:27
Thanks @jreback , I wasn't aware of .assign's side effect achieving data transformation.

I am sorry to insist on how misleading/incomplete the .transform documentation is.
First line:
"Call func on self producing a DataFrame with transformed **values**." It says "values" only, not even mentioning structure transformation. When I read about transforming values I expect no structural change.

Is there a better official documentation about the Transform feature apart from this [article here](https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#transform-api)?
I witness significant confusion about it online.

**Comment by jreback** [comment] 2020-12-05 19:40
you are welcome to submit a doc update if you would like though there is extensive documentation

**Comment by tilusnet** [comment] 2020-12-05 19:54
I'll consider helping with the docs once I truly understand it myself first.
