### ISSUE TITLE
pivot_table fails on exception, when margins=True

### ISSUE THREAD

**Issue by stefansimik** [pandas-dev/pandas#18711] opened 2017-12-10 10:37 UTC
#### Sample code

```python
import pandas as pd
from pandas.api.types import CategoricalDtype
import numpy as np

# Load data
df = pd.read_excel('http://pbpython.com/extras/sales-funnel.xlsx')
# Make categories
df["Status"] = pd.Categorical(df["Status"], categories=["won","pending","presented","declined"], ordered=False)

# Create pivot table - WORKS FINE
pd.pivot_table(df, index=['Manager', 'Status'], 
               values=['Quantity', 'Price'], 
               aggfunc={'Quantity': len, 'Price': [np.sum, np.mean]}, 
               fill_value=0, 
               margins=False)

# Here we make the only change: set parameter margins=True

# Create pivot table - FAILS on KeyError: 'Level None not found'
pd.pivot_table(df, index=['Manager', 'Status'], 
               values=['Quantity', 'Price'], 
               aggfunc={'Quantity': len, 'Price': [np.sum, np.mean]}, 
               fill_value=0, 
               margins=True)
```
#### Problem description

Pivot table fails on exception, when margins are set True on previous example.

Thrown exception is:
`KeyError: 'Level None not found'`

#### Expected Output

pivot_table with margins=True should work correctly 
OR
report intuitive error
OR
documentation should be clearly updated to avoid such a problem

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.0
pytest: 3.3.0
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.27.3
numpy: 1.13.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 6.2.1
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.9
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.1
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment] 2017-12-10 11:57
can i show a copy pastable example 
iow start with a code constructed frame

**Comment by jreback** [comment] 2017-12-10 15:06
duplicate of https://github.com/pandas-dev/pandas/issues/12210

**Closed by jreback** 2017-12-10 15:06 UTC
Labels: Needs Info
