### ISSUE TITLE
CI: Failure on Appveyor Master

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#21102] opened 2018-05-17 13:13 UTC
https://ci.appveyor.com/project/pandas-dev/pandas/build/job/0y6fvce0al2yax06?fullLog=true#L1989

cc @WillAyd 

Maybe #21066 was related? Not sure how though. Looking now.

**Comment by WillAyd** [comment] 2018-05-17 15:13
Hmm strange indeed. I have a hard time thinking that change would be the cause (it was passing fine up until the last commit) but who knows.

I recall there being a similar issue with the Mac builds and in the same area of testing (see #19984). I'm not sure there was ever a real resolution to that one outside of time (?)

No chance we changed anything with the build environment right? I see other changes are passing...

**Comment by WillAyd** [comment] 2018-05-17 15:42
I did notice there's one instance in `common.py` where we open a file handle but never explicitly close it. It's tough to say since any information about the `ResourceWarning` is getting suppressed but wonder if the below line is the offender?

https://github.com/pandas-dev/pandas/blob/d623ffd90f57abda2beb34d807da58ca95b3743d/pandas/tests/io/parser/common.py#L57

**Comment by jreback** [comment] 2018-05-17 15:50
that looks like an issue (independent of other things)

**Comment by david-liu-brattle-1** [comment] 2018-05-19 02:54
I think I got the same problem in #21111 (Commit #ce02a40)

**Closed** 2018-05-19 20:08 UTC
Labels: CI, Windows
