### ISSUE TITLE
groupby boxplot example does not work

### ISSUE THREAD

**Issue by ingrid88** [pandas-dev/pandas#28903] opened 2019-10-10 19:35 UTC
#### Problem description
Code found here: 
https://github.com/pandas-dev/pandas/blob/v0.25.1/pandas/plotting/_core.py#L424

Example from https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.boxplot.html does not work properly. 

#### Code Sample

```python
import itertools
tuples = [t for t in itertools.product(range(1000), range(4))]
index = pd.MultiIndex.from_tuples(tuples, names=['lvl0', 'lvl1'])
data = np.random.randn(len(index),4)
df = pd.DataFrame(data, columns=list('ABCD'), index=index)
grouped = df.groupby(level='lvl1')
boxplot_frame_groupby(grouped)
grouped = df.unstack(level='lvl1').groupby(level=0, axis=1)
boxplot_frame_groupby(grouped, subplots=False)
```

#### Resulting Error 
```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-49-1a28c2f7125d> in <module>
      5 df = pd.DataFrame(data, columns=list('ABCD'), index=index)
      6 grouped = df.groupby(level='lvl1')
----> 7 boxplot_frame_groupby(grouped)
      8 grouped = df.unstack(level='lvl1').groupby(level=0, axis=1)
      9 boxplot_frame_groupby(grouped, subplots=False)

NameError: name 'boxplot_frame_groupby' is not defined
```

**Comment by TomAugspurger** [comment] 2019-10-10 19:47
That function isn't imported. I don't think our doc examples typically have
the import.

**Comment by MarcoGorelli** [comment] 2020-05-22 15:21
Thanks @ingrid88 for the report, as far as I can tell the
```python
from pandas.plotting import boxplot_frame_groupby
```
import is missing.

Are you interested in submitting a pull request?

**Comment by monkeydragon** [comment] 2020-05-23 15:15
Hey, I can take this.

**Comment by gsyqax** [comment] 2020-05-23 15:35
I can do it.

**Comment by MarcoGorelli** [comment] 2020-05-23 16:02
Pull requests are welcome, just comment 'take' please so the issue is assigned to you

**Comment by gsyqax** [comment] 2020-05-23 16:14
Take

**Closed** 2020-07-07 11:09 UTC
Labels: Groupby, Visualization, good first issue
