### ISSUE TITLE
BUG: groupby-transform produces NaN for series keys with as_index=False

### ISSUE THREAD

**Issue by thomas-reineking-by** [pandas-dev/pandas#37093] opened 2020-10-13 07:09 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.DataFrame({"X": [1.0]})
df.groupby(pd.Series(["group"]), as_index=False).transform("sum")
```

#### Problem description

With version 1.1.3 this produces a dataframe containing NaN.

#### Expected Output

Expected is 1.0 and this is also what older versions produce (1.0.5).

It seems the following conditions have to be satisfied to trigger this bug:

- grouping by a series which does not contain indices corresponding to the original dataframe (grouping by `pd.Series([0])` works though it seems accidental)
- using `as_index=False`
- using `transform`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.6.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.76-linuxkit
Version          : #1 SMP Tue May 26 11:42:35 UTC 2020
machine          : x86_64
processor        :
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.3
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.15
pytest           : 5.4.3
hypothesis       : 5.6.0
sphinx           : 1.8.5
blosc            : None
feather          : None
xlsxwriter       : 1.2.8
lxml.etree       : 4.5.0
html5lib         : None
pymysql          : None
psycopg2         : 2.8.5 (dt dec pq3 ext lo64)
jinja2           : 2.10.3
IPython          : 7.9.0
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fsspec           : 0.6.2
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.1
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.1.post2
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.15
tables           : None
tabulate         : 0.8.6
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : 0.48.0

</details>

**Comment by ssmssam** [comment] 2020-10-18 19:09
The issue seems to occur with this line in generic.py added in June 
               result = result.reindex(self.grouper.result_index, copy=False)

**Comment by rhshadrach** [comment] 2021-01-21 05:04
Thanks for the report! Agreed that this is an issue, but I don't think the line identified is the cause. This path relies on computing the aggregation and then broadcasting the result to the frame. `as_index=False` changes the result of the reduction so that the broadcasting fails. This can be fixed by temporarily setting `as_index=True` within the transform call via `pandas.core.common.temp_setattr`.

Tangential to this, the code

```
df = pd.DataFrame({0: [1.0]})
gb = df.groupby(pd.Series(["X"]), as_index=False)
print(gb.sum())
```

gives 

```
     0
0  1.0
```

whereas I think "X" should be added as a column to the result. Resolving this won't impact this issue however (and in fact, may make the output worse!). Will open a new issue after a little more investigating.

**Comment by rhshadrach** [comment] 2023-04-23 16:18
The OP now produces

```
     X
0  1.0
```

and this looks like the expected result to me.

**Comment by DevpriyaDave** [comment] 2023-12-20 21:23
First time contributor going to try to write test case for this

**Comment by DevpriyaDave** [comment] 2023-12-20 21:24
take

**Comment by undermyumbrella1** [comment] 2024-03-26 10:48
Hi, I have created an pr with the tests. Can I request for some help reviewing it? thank you!

**Closed** 2024-03-28 17:58 UTC
Labels: Groupby, Apply, good first issue, Needs Tests
