### ISSUE TITLE
BUG: Can't save pyarrow.lib.Decimal128Scalar to_parquet

### ISSUE THREAD

**Issue by jaroszan** [pandas-dev/pandas#39334] opened 2021-01-22 08:16 UTC
- [ X] I have checked that this issue has not already been reported.

- [X ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
Converting value to pyarrow.lib.Decimal128Scalar works in pyarrow: 
```python
>>> t = pyarrow.array([decimal.Decimal('2478463143.1140136719')], pyarrow.decimal128(38,10))[0]
>>> print(t)
2478463143.1140136719
>>>
```

However when attempting to write this value as one of the columns to parquet (**_to_parquet_**) the following happens:

> pyarrow.lib.ArrowInvalid: ('Could not convert 2478463143.1140136719 with type pyarrow.lib.Decimal128Scalar: did not recognize Python value type when inferring an Arrow data type', 'Conversion failed for column X with type object')

#### Problem description

It should be possible to write this value to parquet since it is a valid decimal with precision and scale

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.8.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None

pandas           : 1.2.1
numpy            : 1.19.5
pytz             : 2020.4
dateutil         : 2.8.1
pip              : 20.2.1
setuptools       : 49.2.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jorisvandenbossche** [comment] 2021-01-22 11:22
@jaroszan could you provide a full reproducible example?

**Comment by jaroszan** [comment] 2021-01-22 12:32
testdata.csv:

> s_name,s_start_date,agg_percentile_bps
> TTT-111111,2020-12-01,2478463143.1140136719

python script:

```python
import pandas as pd
import pyarrow
import decimal
        
def decimal_from_value(value):
    return pyarrow.array([decimal.Decimal(value)], pyarrow.decimal128(38,10))[0]
        
df = pd.read_csv('testdata.csv', converters={'agg_percentile_bps': decimal_from_value})
        
df.to_parquet('testdata.parquet')
```

result:

        Traceback (most recent call last):
          File "csv_to_parquet.py", line 10, in <module>
            df.to_parquet('testdata.parquet')
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\util\_decorators.py", line 199, in wrapper
            return func(*args, **kwargs)
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 2455, in to_parquet
            return to_parquet(
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parquet.py", line 390, in to_parquet
            impl.write(
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parquet.py", line 152, in write
            table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
          File "pyarrow\table.pxi", line 1394, in pyarrow.lib.Table.from_pandas
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarrow\pandas_compat.py", line 587, in dataframe_to_arrays
            arrays = [convert_column(c, f)
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarrow\pandas_compat.py", line 587, in <listcomp>
            arrays = [convert_column(c, f)
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarrow\pandas_compat.py", line 574, in convert_column
            raise e
          File "C:\Users\username\AppData\Local\Programs\Python\Python38\lib\site-packages\pyarrow\pandas_compat.py", line 568, in convert_column
            result = pa.array(col, type=type_, from_pandas=True, safe=safe)
          File "pyarrow\array.pxi", line 292, in pyarrow.lib.array
          File "pyarrow\array.pxi", line 83, in pyarrow.lib._ndarray_to_array
          File "pyarrow\error.pxi", line 84, in pyarrow.lib.check_status
        pyarrow.lib.ArrowInvalid: ('Could not convert 2478463143.1140136719 with type pyarrow.lib.Decimal128Scalar: did not recognize Python value type when inferring an Arrow data type', 'Conversion failed for column agg_percentile_bps with type object')

**Comment by jorisvandenbossche** [comment] 2021-01-25 12:22
Thanks for the example.

It's best to not yet convert to actual pyarrow scalars while reading the csv file, but to python decimals:

```
def decimal_from_value(value):
    return decimal.Decimal(value)

df = pd.read_csv('testdata.csv', converters={'agg_percentile_bps': decimal_from_value})
```

Then you have column of those objects, and when writing to parquet, pyarrow will write them as decimal type.

The reason you get this error is because pyarrow scalars are not meant to be used outside of pyarrow (at least right now), and eg at the moment can't be used to create pyarrow data structures (under the hood in `to_parquet`, the pandas DataFrame is converted to a pyarrow Table, and so each column of the dataframe is converted to a pyarrow array). This is covered in https://issues.apache.org/jira/browse/ARROW-5295. 

Since this is in the end a pyarrow issue, closing it here (but feel free to discuss further, here or in the pyarrow issue)

**Closed by jorisvandenbossche** 2021-01-25 12:22 UTC
Labels: Bug, IO Parquet, Upstream issue

**Comment by jaroszan** [comment] 2021-01-25 12:35
Thanks for clarification, the reason I am using it this way is because I need to specify specific attributes, like precision, scale and FIXED_LEN_BYTE_ARRAY length. Otherwise it won't fit into impala table which attributes are out of my control. Your solution is actually the first one I tried and I haven't figured out how to specify these attributes - it looks like this attributes are dynamically determined by pandas depending on values it converts.  Or have I missed something?

**Comment by jorisvandenbossche** [comment] 2021-01-25 12:48
Some options I think about:

- Manually convert the dataframe to a pyarrow Table (`pyarrow.Table.from_pandas(..)`), and in that case you can specify a schema, and thus still specify the exact type you want for certain columns (and then in a second step you can write the pyarrow table to parquet)
- Use the pyarrow csv reader, in which case you can directly read the csv into a pyarrow Table (to then write to parquet) without a conversion through pandas, and with the pyarrow csv reader you can also specify the exact pyarrow type for certain columns (see https://arrow.apache.org/docs/python/csv.html)

**Comment by jaroszan** [comment] 2021-01-26 10:04
Just to leave as a reference, solution that works:

```python

table = csv.read_csv('testdata.csv', convert_options=pa.csv.ConvertOptions(
    column_types={
        's_name': pa.string(),
        's_start_date': pa.string(),
        'agg_percentile_bps': pa.decimal128(precision=38, scale=10),
    }
))

pq.write_table(table, 'testdata.parquet')
```

**Comment by jorisvandenbossche** [comment] 2021-01-29 15:14
@jaroszan sidenote, feel free to contribute such an example to the pyarrow docs, if you would like (https://issues.apache.org/jira/browse/ARROW-11373, https://arrow.apache.org/docs/python/csv.html)
