### ISSUE TITLE
Count Boolean values with .groupby()

### ISSUE THREAD

**Issue by sursu** [pandas-dev/pandas#21031] opened 2018-05-14 09:13 UTC
Take the following dataframe:
```
df = pd.DataFrame({'ID':[1,2,1,1,2,3,4,4,4],
                   'Litmus':[False,False,True,True,False,False,True,True,True]})
```
I want to count the conditional number of True values, that is, I want to count the number of True values for each ID.

This works fine:
`df.groupby('ID')['Litmus'].sum()`

However, this does not:
`df[4:7].groupby('ID')['Litmus'].sum()`

To make it more interesting, this again works fine:
`df[4:8].groupby('ID')['Litmus'].sum()`

Bizarre behavior.

**Comment by jreback** [comment] 2018-05-14 12:26
duplicate of #14873 

pls show the actual return values, rather than 'Bizarre behavior' as well as versioning information as indicated in the template. The more complete reports are the better.

**Closed by jreback** 2018-05-14 12:26 UTC
