### ISSUE TITLE
BUG: Regression in 1.3.0: Exception when setting arrays as cell values

### ISSUE THREAD

**Issue by felixdivo** [pandas-dev/pandas#43422] opened 2021-09-05 20:12 UTC
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas (yes, on version 1.3.2).
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

The following works fine on 1.2.5 and now fails (starting with 1.3.0). I waited for it to be fixed by 1.3.1/1.3.2 but it seems like this one went unnoticed until now.

#### Code Sample, a copy-pastable example

```python
from pandas import DataFrame
from numpy import zeros

# (Leaving out the dtype doesn't change things)
frame = DataFrame(columns=["x", "P"], dtype=object)
data = {"x": zeros((2, )), "P": zeros((2, 2))}

frame.append(data, ignore_index=True)
frame.loc[0] = data
```

#### Problem description

No exception, just the inserted data.

#### Expected Output

None.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-81-generic
Version          : #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.3.2
numpy            : 1.21.0
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 57.0.0
Cython           : None
pytest           : 6.2.5
hypothesis       : 6.17.4
sphinx           : 4.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment] 2021-09-05 20:56
Probably caused by e1dd03295e90bc4419968e4afebb8faa50e34b29 cc @jbrockmendel

**Comment by jbrockmendel** [comment] 2021-09-06 20:10
Looks like this is fixed by moving the `elif dtype == object` check in can_hold_element up to befor the `maybe_infer_dtype_type` call.  PR to do this would be welcome.

BTW I think the `.append` in the OP is extraneous

**Comment by simonjayhawkins** [comment] 2021-09-07 17:34
> Probably caused by [e1dd032](https://github.com/pandas-dev/pandas/commit/e1dd03295e90bc4419968e4afebb8faa50e34b29)

#40709

**Closed** 2021-09-07 21:59 UTC
Labels: Bug, Indexing, Regression

**Comment by felixdivo** [comment] 2021-09-08 13:04
Awesomely fast fix! Thank you, @phofl!
