### ISSUE TITLE
ENH: read_csv(data_url, verify = False)

### ISSUE THREAD

**Issue by Baelfur** [pandas-dev/pandas#36807] opened 2020-10-02 14:38 UTC
#### Is your feature request related to a problem?

Pandas currently allows a csv to be opened from a URL, but does not allow you to set verify to false in the event that URL has an ssl certificate error.

#### Describe the solution you'd like

please add verify=false parameter to the pandas.read_csv() function when reading a file from a weburl.

#### API breaking implications

not sure

#### Describe alternatives you've considered

downloading the file first locally and overriding the ssl error via request.

#### Additional context

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-9-922c6d1e33ad> in <module>
----> 1 df = pd.read_csv(fileDl)

```python
# Your code here, if applicable

```

**Comment by jreback** [comment] 2020-10-02 23:28
duplicate of https://github.com/pandas-dev/pandas/issues/36688

I *think* we can pass these thru using `storage_options={'verify': False}`

**Closed by jreback** 2020-10-02 23:28 UTC
Labels: Enhancement, Needs Triage

**Comment by thoughtfuldata** [comment] 2021-09-30 23:11
This actually doesn't work. still getting URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired

`storage_options={'verify': False}`

**Comment by sohang3112** [comment] 2026-07-25 09:07
`pd.read_csv(url, storage_options={'verify': False})` didn't work for me either on Ubuntu linux. Had to instead download via `urlopen` with ssl verification disabled, and then using `pd.read_csv()`:

```python
from urllib.request import urlopen
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False 
ctx.verify_mode = ssl.CERT_NONE
with urlopen(url, context=ctx) as response:
    text = response.read().decode('utf-8')
    df = pd.read_csv(StringIO(text))
```

This issue should be re-opened as the existing option for disabling SSL verification in `pd.read_csv()` has no effect.
