### ISSUE TITLE
BUG: groupby drops na values of categorical even if dropna=False is set

### ISSUE THREAD

**Issue by atkrueger** [pandas-dev/pandas#39573] opened 2021-02-03 04:03 UTC
- [ x] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---
df = pd.DataFrame({'a': [1,2,3]})
dtype = pd.api.types.CategoricalDtype([1,2])
df['b'] =df.a.astype(dtype)
df.groupby('b',dropna=False).size()

#### Problem description

observations for categorical variables with na values are dropped from groupby() even if dropna=False is specified.

#### Expected Output

b
nan    1
1        1
2        1

#### Actual output
b
1 1
2 1

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 9d598a5e1eee26df95b3910e3f2934890d062caa
python           : 3.9.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : en.UTF-8
LOCALE           : English_United States.1252

pandas           : 1.2.1
numpy            : 1.19.5
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.1
setuptools       : 50.3.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by rhshadrach** [comment] 2021-02-03 04:11
Duplicate of #36327

**Closed by rhshadrach** 2021-02-03 04:11 UTC
Labels: Bug, Needs Triage
