### ISSUE TITLE
df[col].astype('interval') no longer works for interval string

### ISSUE THREAD

**Issue by xiaofanyang002** [pandas-dev/pandas#35671] opened 2020-08-11 16:11 UTC
We used the below code to roundtrip pd.Interval values in 0.25.3, but it throws TypeError in 1.0.5:
```
df = pd.DataFrame(data={'i': [pd.Interval(0, 2, closed='left')]})
df['i'] = df['i'].astype(str) 
df['i'].astype('interval')
# throws: TypeError: type <class 'str'> with value [0, 2) is not an interval
```
We didn't use to_json/read_json because it is also not parsing pd.Interval back properly:
```
df = pd.DataFrame(data={'i': [pd.Interval(0, 2, closed='left')]})
value_json = df.to_json(orient='values')
pd.read_json(value_json, orient='values').values
# returns: array([[{'closed': 'left', 'closed_right': False, 'left': 0, 'mid': 1.0, 'open_right': True, 'right': 2}]],
      dtype=object)
```

**Comment by dsaxton** [comment] 2020-08-12 00:29
Are you sure this worked in 0.25.3?

```python
In [1]: import pandas as pd
   ...:
   ...: print(pd.__version__)
   ...: s = pd.Series([pd.Interval(0, 2, closed="left")])
   ...: s.astype(str).astype("interval")
   ...:
0.25.3
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-6899618274c9> in <module>
      3 print(pd.__version__)
      4 s = pd.Series([pd.Interval(0, 2, closed="left")])
----> 5 s.astype(str).astype("interval")

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/generic.py in astype(self, dtype, copy, errors, **kwargs)
   5879         else:
   5880             # else, only a single dtype is given
-> 5881             new_data = self._data.astype(
   5882                 dtype=dtype, copy=copy, errors=errors, **kwargs
   5883             )

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/internals/managers.py in astype(self, dtype, **kwargs)
    579
    580     def astype(self, dtype, **kwargs):
--> 581         return self.apply("astype", dtype=dtype, **kwargs)
    582
    583     def convert(self, **kwargs):

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/internals/managers.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
    436                     kwargs[k] = obj.reindex(b_items, axis=axis, copy=align_copy)
    437
--> 438             applied = getattr(b, f)(**kwargs)
    439             result_blocks = _extend_blocks(applied, result_blocks)
    440

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/internals/blocks.py in astype(self, dtype, copy, errors, values, **kwargs)
    557
    558     def astype(self, dtype, copy=False, errors="raise", values=None, **kwargs):
--> 559         return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
    560
    561     def _astype(self, dtype, copy=False, errors="raise", values=None, **kwargs):

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/internals/blocks.py in _astype(self, dtype, copy, errors, values, **kwargs)
    641                     # _astype_nansafe works fine with 1-d only
    642                     vals1d = values.ravel()
--> 643                     values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
    644
    645                 # TODO(extension)

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/dtypes/cast.py in astype_nansafe(arr, dtype, copy, skipna)
    648     # dispatch on extension dtype if needed
    649     if is_extension_array_dtype(dtype):
--> 650         return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)
    651
    652     if not isinstance(dtype, np.dtype):

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/arrays/interval.py in _from_sequence(cls, scalars, dtype, copy)
    236     @classmethod
    237     def _from_sequence(cls, scalars, dtype=None, copy=False):
--> 238         return cls(scalars, dtype=dtype, copy=copy)
    239
    240     @classmethod

~/opt/miniconda3/envs/pandas-0.25.3/lib/python3.8/site-packages/pandas/core/arrays/interval.py in __new__(cls, data, closed, dtype, copy, verify_integrity)
    165             # might need to convert empty or purely na data
    166             data = maybe_convert_platform_interval(data)
--> 167             left, right, infer_closed = intervals_to_interval_bounds(
    168                 data, validate_closed=closed is None
    169             )

pandas/_libs/interval.pyx in pandas._libs.interval.intervals_to_interval_bounds()

TypeError: type <class 'str'> with value [0, 2) is not an interval
```

**Comment by xiaofanyang002** [comment] 2020-08-12 18:16
@dsaxton You're right, sorry about the confusion. Digging deeper, it seems that the dtype of `pd.Interval` changes from "object" to "interval", and `astype` failed for the latter. 

Do you have any suggestions on how to properly roundtrip `pd.Interval` through json given the new dtype? It seems reasonable for `astype` to support existing dtypes. Thanks!

Before:
```
>>> import pandas as pd
>>> print(pd.__version__)
0.25.3
>>> s = pd.Series([pd.Interval(0, 2, closed="left")])
>>> s.dtypes
dtype('O')
```
After:
```
>>> import pandas as pd
>>> print(pd.__version__)
1.0.5
>>> s = pd.Series([pd.Interval(0, 2, closed="left")])
>>> s.dtypes
interval[int64]
```

**Comment by dsaxton** [comment] 2020-08-13 00:26
@xiaofanyang002 Is it possible to reconstruct the interval from the dictionary output of read_json rather than trying to use astype (e.g., using a of map with a custom lambda over the column)?

**Comment by dsaxton** [comment] 2020-08-15 15:33
Closing as not a bug, @xiaofanyang002 hopefully the above helps

**Closed by dsaxton** 2020-08-15 15:33 UTC

**Comment by maffinyep** [comment] 2024-01-19 11:59
> @xiaofanyang002 Is it possible to reconstruct the interval from the dictionary output of read_json rather than trying to use astype (e.g., using a of map with a custom lambda over the column)?

Could be added as a feature? At the moment it seems there's no smooth way to convert a string into an Interval, so store and reload a dataframe in .csv and .json that contains Intervals or IntervalIndexes will add extra preprocessing.
