### ISSUE TITLE
BUG: I got empty Dataframe with index from the summation of empty Dataframe with MultiIndex

### ISSUE THREAD

**Issue by llthelinkll** [pandas-dev/pandas#40626] opened 2021-03-25 04:49 UTC
I'm not sure that the current behavior is right, so I would like to ask. 

When I have a non-empty Dataframe I can use `sum(level=['Project', 'Task''])` to get the MultiIndex Dataframe as my expectation. But when I try to sum the empty Dataframe, I got Index Dataframe instead of MultiIndex Dataframe and It has no index name and column name in there.

Is this the correct behavior or this is a bug. If this is the correct one, do you have any suggestions for me to handle this?

Thank you in advance.

## Code Sample

```python
pd.__version__
# non-empty data
data = pd.DataFrame([(1,1,1,1,1,1),(2,2,2,2,2,2)],columns=('Project', 'Task', 'Increasing Length', 'Start Period', 'Period', 'Value'))
data.set_index(['Project', 'Task', 'Increasing Length', 'Start Period', 'Period'], inplace=True)
sum_data = data.sum(level=['Project', 'Task'])
print(sum_data)

# empty data
empty_data = pd.DataFrame([],columns=('Project', 'Task', 'Increasing Length', 'Start Period', 'Period', 'Value'))
empty_data.set_index(['Project', 'Task', 'Increasing Length', 'Start Period', 'Period'], inplace=True)
# sum of empty data
sum_empty_data = empty_data.sum(level=['Project', 'Task'])
print(sum_empty_data)

# my expectation
expected_sum_empty_data = pd.DataFrame([],columns=('Project', 'Task', 'Value'))
expected_sum_empty_data.set_index(['Project', 'Task'], inplace=True)
print(expected_sum_empty_data)
```
## Expected Output
![image](https://user-images.githubusercontent.com/5256282/112418964-1775c080-8d5d-11eb-9caa-4e2852b6f39c.png)

## Installed Version
python : 3.8.8  
pandas : 1.2.3
numpy : 1.20.1
OS: Ubuntu 20.04.1 LTS (docker)

**Comment by rhshadrach** [comment] 2021-03-25 20:24
Thanks for the report! This is a duplicate of #26411 which was fixed and will be released in 1.3. Running on master:

```
empty_data = pd.DataFrame([],columns=('Project', 'Task', 'Increasing Length', 'Start Period', 'Period', 'Value'))
empty_data.set_index(['Project', 'Task', 'Increasing Length', 'Start Period', 'Period'], inplace=True)
sum_empty_data = empty_data.sum(level=['Project', 'Task'])
print(sum_empty_data.index)
print(sum_empty_data.columns)
```

gives

```
MultiIndex([], names=['Project', 'Task'])
Index(['Value'], dtype='object')
```

Reply here if I've missed something and can reopen.

**Closed by rhshadrach** 2021-03-25 20:24 UTC
Labels: Bug, Groupby
