### ISSUE TITLE
keep_tz FutureWarning and generic.py

### ISSUE THREAD

**Issue by danielwlogan** [pandas-dev/pandas#27025] opened 2019-06-24 22:36 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame(index=pd.date_range(start='2019', periods=3, freq='H', tz='America/Los_Angeles'), data={'A': [1, 2, 3]})
df.query('A > 1')
```
#### Problem description

The above code produces a `FutureWarning`:

```
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:407: FutureWarning: The default of the 'keep_tz' keyword will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.
  s = level_values.to_series()
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:415: FutureWarning: The default of the 'keep_tz' keyword will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.
  dindex = axis_index.to_series()
```

#### Expected Output

I believe the internal pandas code (`generic.py`) needs to handle the warning by passing an appropriate keyword (`keep_tz=True`).

#### Output of ``pd.show_versions()``

<details>

commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-52-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8
LOCALE: en_CA.UTF-8

pandas: 0.24.2
pytest: 4.0.0
pip: 19.1.1
setuptools: 40.4.3
Cython: 0.29.10
numpy: 1.16.4
scipy: 1.3.0
pyarrow: None
xarray: None
IPython: 7.5.0
sphinx: None
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.1.0
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.2.1
bs4: None
html5lib: 1.0.1
sqlalchemy: 1.3.1
pymysql: None
psycopg2: 2.8.2 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: 0.9.0
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment] 2019-06-25 11:36
cc @jorisvandenbossche

**Comment by TomAugspurger** [comment] 2019-06-25 11:43
Smaller repro

```python
In [1]: import pandas as pd
id
In [2]: idx = pd.date_range('2000', periods=12, tz="US/Central")

In [3]: idx.to_series()
/Users/taugspurger/.virtualenvs/pandas-dev/bin/ipython:1: FutureWarning: The default of the 'keep_tz' keyword in DatetimeIndex.to_series will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.
  #!/Users/taugspurger/Envs/pandas-dev/bin/python
Out[3]:
2000-01-01 00:00:00-06:00   2000-01-01 06:00:00
2000-01-02 00:00:00-06:00   2000-01-02 06:00:00
2000-01-03 00:00:00-06:00   2000-01-03 06:00:00
2000-01-04 00:00:00-06:00   2000-01-04 06:00:00
2000-01-05 00:00:00-06:00   2000-01-05 06:00:00
2000-01-06 00:00:00-06:00   2000-01-06 06:00:00
2000-01-07 00:00:00-06:00   2000-01-07 06:00:00
2000-01-08 00:00:00-06:00   2000-01-08 06:00:00
2000-01-09 00:00:00-06:00   2000-01-09 06:00:00
2000-01-10 00:00:00-06:00   2000-01-10 06:00:00
2000-01-11 00:00:00-06:00   2000-01-11 06:00:00
2000-01-12 00:00:00-06:00   2000-01-12 06:00:00
Freq: D, dtype: datetime64[ns]
```

**Comment by TomAugspurger** [comment] 2019-06-25 11:45
Err, sorry I may have misunderstood the issue. This is about not being able to control the warning from `.query`?

I'm not sure there's too much we can do right now. If we pass `keep_tz=True` there, we change behavior without warning. And there's not a good place in `.query` to pass along a kwarg.

**Comment by WillAyd** [comment] 2019-06-25 12:02
> And there's not a good place in `.query` to pass along a kwarg.

Not overly familiar with this code but does it need to be passed along through `.query` or should it just be done internally?

**Comment by TomAugspurger** [comment] 2019-06-25 12:13
Same, but it seems strange for query to accept a kwarg for this very specific operation.

**Comment by jorisvandenbossche** [comment] 2019-06-25 12:29
Question that pops up to me: will the behaviour of query actually change in the future? (for datetimetz data)

So the reason that this warning is raised is that `query` / `eval` converts the index into a series to pass that as the data that can be queried to the underlying eval implementation. 
So I suppose this will actually change behaviour *if* you are querying on the datetimetz column (which is not the case here).

But in any case, a warning coming from internal pandas code is not nice ..

**Comment by jorisvandenbossche** [comment] 2019-06-25 12:34
> So I suppose this will actually change behaviour if you are querying on the datetimetz column (which is not the case here).

I think we can actually pass `keep_tz=True` already now (as kind of a bug fix). Querying on a datetimetz index will interpret the values as UTC in the expression.

**Comment by jorisvandenbossche** [comment] 2019-06-25 12:35
To illustrate:

```
In [40]: df.index > '2019-01-01 01:00:00' 
Out[40]: array([False, False,  True])

In [41]: df.eval("index > '2019-01-01 01:00:00'") 
/home/joris/miniconda3/lib/python3.7/site-packages/pandas/core/generic.py:415: FutureWarning: The default of the 'keep_tz' keyword will change to True in a future release. You can set 'keep_tz=True' to obtain the future behaviour and silence this warning.
  dindex = axis_index.to_series()
Out[41]: 
2019-01-01 00:00:00-08:00    True
2019-01-01 01:00:00-08:00    True
2019-01-01 02:00:00-08:00    True
Freq: H, dtype: bool
```

**Comment by jbrockmendel** [comment] 2019-12-11 22:27
This no longer produces a warning since the default is now keep_tz=True

**Comment by jorisvandenbossche** [comment] 2019-12-12 08:42
But the other example (querying on the index) now started to raise:

```
In [20]: df.eval("index > '2019-01-01 01:00:00'")                                                                                                                                                                  
...
TypeError: Cannot compare tz-naive and tz-aware datetime-like objects
```

passing an aware string works:

```
In [21]: df.eval("index > '2019-01-01 01:00:00-08:00'")                                                                                                                                                            
Out[21]: 
2019-01-01 00:00:00-08:00    False
2019-01-01 01:00:00-08:00    False
2019-01-01 02:00:00-08:00     True
Freq: H, dtype: bool
```

But for normal index comparison, a naive string is interpreted in the local timezone of the index:

**Comment by mroeschke** [comment] 2020-03-30 02:29
I think the remaining issue is a duplicate of https://github.com/pandas-dev/pandas/issues/26236 since `query` uses `eval` under the hood

**Closed by mroeschke** 2020-03-30 02:29 UTC
Labels: Bug, Timeseries, Timezones
