### ISSUE TITLE
ENH: Rename multi-level columns or indices using their tupelized names

### ISSUE THREAD

**Issue by normanius** [pandas-dev/pandas#38069] opened 2020-11-25 19:57 UTC
It's currently quite difficult to rename a single column (or row) in a multi-indexed DataFrame. The problem is illustrated also in this [SO article](https://stackoverflow.com/questions/54693188).

The current approach requires at least 3 steps:

```
df = pd.DataFrame([[1,2,3],[3,4,5],[5,6,7], [7,8,9]])
df.columns = pd.MultiIndex.from_tuples([('i','a'),('i','b'),('ii','a')])

# Alternative 1
i = df.columns.get_loc(('i','b'))
cols = df.columns.values
cols[i] = ('i','c')
df.columns = pd.MultiIndex.from_tuples(cols)

# Alternative 2
df.columns = df.columns.to_flat_index()
df = df.rename(columns={('i','b'):('i','c')})
df.columns = pd.MultiIndex.from_tuples(df.columns)
```

#### Enhancement:

In presence of a MultiIndex, `rename()` should support the tupelized representation of a column.

```
df = pd.DataFrame([[1,2,3],[3,4,5],[5,6,7], [7,8,9]])
df.columns = pd.MultiIndex.from_tuples([('i','a'),('i','b'),('ii','a')])

# Rename using tuples:
df.rename(columns={('i','b'):('ii','b')})
# Rename using current column name (equivalent to 1a)
col = df[('i','b')]
df.rename(columns={col.name: ('ii','b')})
```

This would improve the consistency of the API, since many methods accept a tuple to address the name of a multi-index element:

```
df[('i','a')]
df.drop(('i','a'), axis=1)
df.pop(('i','a'), axis=1)
...
```

#### API breaking implications

I regard this improvement as an extension of the current API.

**Comment by jreback** [comment] 2020-11-25 21:06
duplicate of https://github.com/pandas-dev/pandas/issues/20421

you can actually just do this though: https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.Index.set_names.html?highlight=set_names

```
df.index = df.index.set_names(...)
````

**Closed by jreback** 2020-11-25 21:06 UTC
Labels: Enhancement, Needs Triage

**Comment by normanius** [comment] 2020-11-25 22:13
@jreback Is it possible that you misinterpreted my question? It's not about names of index levels. It's about the indices (=name of column). I don't see how it could be done with `set_names` nor how this is related to #20421.

```
# Input:
   i    ii
   a  b  a
0  1  2  3
1  3  4  5
2  5  6  7
3  7  8  9

# Output: same df, except that one column has different index
   i    ii
   a  c  a
0  1  2  3
1  3  4  5
2  5  6  7
3  7  8  9
```

**Comment by jreback** [comment] 2020-11-25 22:25
sorry wrong issue, see https://github.com/pandas-dev/pandas/issues/4160 which is a long time open issue.
