### ISSUE TITLE
BUG: Groupby: Int-Datatype (of group-by-columns) always casted to int64

### ISSUE THREAD

**Issue by Mueller2-Patrick** [pandas-dev/pandas#34598] opened 2020-06-05 12:59 UTC
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas.
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.
---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({'col1':[1,2,3],'col2':[10,11,12]})
df['col1'] = df['col1'].astype(np.int8)

print(df.dtypes)

print(df.groupby('col1', as_index=False)['col2'].count().dtypes)
```

#### Problem description

**Before the groupby:** The dtype of col1 is np.int8:
Output of 
```python
print(df.dtypes):

col1     int8
col2    int64
dtype: object
```

**After the groupby** the dtype of col1 is np.int64
Output of 
```python
print(df.groupby('col1', as_index=False)['col2'].count().dtypes):

col1    int64
col2    int64
dtype: object
```

#### Expected Output
```python
print(df.groupby('col1', as_index=False)['col2'].count().dtypes) gives output:

col1    int8
col2    int64
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.0.4
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 10.0.1
setuptools       : 45.2.0
Cython           : None
pytest           : 5.4.1
hypothesis       : None
sphinx           : 2.3.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.0.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.12.0
pytables         : None
pytest           : 5.4.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.12
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by rhshadrach** [comment] 2020-06-08 22:10
I think this is expected, datatypes may need to change to hold the correct result. For example, taking the mean of a Boolean/integer should result in float. Taking the count of a column with say 10k rows with dtype int8, changing the datatype to int64 so that the correct result can be stored seems preferable.

**Comment by rhshadrach** [comment] 2020-06-08 22:20
Ahh, I missed that it was the grouping column that is changing. That changes things.

**Comment by rhshadrach** [comment] 2020-06-11 21:51
Even when using as_index=False, internally the unique values for the groupby are stored as an Index. I think that makes this a duplicate of #16404.

**Comment by TomAugspurger** [comment] 2020-09-04 13:42
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/16404. To support this we'll need hashtables / algos that operate on all these integer dtypes.

**Closed by TomAugspurger** 2020-09-04 13:42 UTC
Labels: Bug, Dtypes, Groupby, Needs Triage
