### ISSUE TITLE
COMPAT: openpyxl

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#14519] opened 2016-10-27 14:48 UTC
Just noticed in one of the test suites:

```
home/travis/miniconda/envs/pandas/lib/python3.4/site-packages/openpyxl/worksheet/worksheet.py:300: UserWarning: Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead

  warn("Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead")
```

**Comment by jreback** [comment] 2017-01-21 16:30
dupe of #15090

**Closed by jreback** 2017-01-21 16:30 UTC
Labels: Compat, IO Excel
