### ISSUE TITLE
Pandas 0.23.4: when does "ValueError: Values falls before first bin" happens during grouping?

### ISSUE THREAD

**Issue by Nemecsek** [pandas-dev/pandas#22619] opened 2018-09-06 11:58 UTC
I didn't find any reference of a Pandas error that happens during grouping: `"ValueError: Values falls before first bin"`.
Can it be due to a internal bug?

According to my opinion it should never happen that a group cannot be done. None should be returned instead.

The trace is:

      File "new_calc.py", line 584, in calculate_groups
        grouped = df.groupby(pd.Grouper(freq="D"))
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/generic.py", line 6665, in groupby
        observed=observed, **kwargs)
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/groupby/groupby.py", line 2152, in groupby
        return klass(obj, by, **kwds)
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/groupby/groupby.py", line 599, in __init__
        mutated=self.mutated)
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/groupby/groupby.py", line 3189, in _get_grouper
        binner, grouper, obj = key._get_grouper(obj, validate=False)
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/resample.py", line 1281, in _get_grouper
        r._set_binner()
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/resample.py", line 148, in _set_binner
        self.binner, self.grouper = self._get_binner()
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/resample.py", line 156, in _get_binner
        binner, bins, binlabels = self._get_binner_for_time()
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/resample.py", line 888, in _get_binner_for_time
        return self.groupby._get_time_bins(self.ax)
      File "/etc/bluelikon/utilities/env/local/lib/python2.7/site-packages/pandas/core/resample.py", line 1333, in _get_time_bins
        ax_values, bin_edges, self.closed, hasnans=ax.hasnans)
      File "pandas/_libs/lib.pyx", line 554, in pandas._libs.lib.generate_bins_dt64
    ValueError: Values falls before first bin

**Comment by TomAugspurger** [comment] 2018-09-06 12:13
Could you fill out the issue template, including a reproducible example and the output of `pd.show_versions`?

**Comment by Nemecsek** [comment] 2018-09-07 09:18
Got it: it has to do with time localization of df's datetimeindex.

To group my data I need first to convert the index from UTC to local time.
This sample code crashes when data are grouped by week AND datetime is localized.
If you localize to UTC or use a grouping period different from W it works:

```
import pandas as pd
import numpy as np
from datetime import datetime

dt = pd.date_range(start=datetime(2016,3,28,0,0,0), periods=20, freq='15min')
np.random.seed(seed=1111)
data = np.random.randint(1, high=100, size=len(dt))

df = pd.DataFrame({'DTIME': dt, 'VALUE': data})
df = df.set_index('DTIME').tz_localize("Europe/Berlin")   # <==== ok with "UTC"

grouped = df.groupby(pd.Grouper(freq="W"))   # <==== ok with "H", "D", "M", "Y"
for g in grouped:
    print(g)
```

**Comment by mroeschke** [comment] 2018-09-07 20:36
Thanks for the report; this looks like a duplicate of #9119 (`df.groupby(pd.Grouper(freq="W"))` is the same as `df.resample('W')`)

**Closed by mroeschke** 2018-09-07 20:36 UTC
Labels: Needs Info

**Comment by Nemecsek** [comment] 2018-09-08 03:56
Sorry, it looks like I made a mistake with the search string and didn't see the previous issue. It has been open for 4 years!

**Comment by mroeschke** [comment] 2018-09-08 05:05
Hoping to get to it soon; it's tricky since the resampling code has been there for a while. Extra eyes are always appreciated!
