### ISSUE TITLE
BUG: Index.union() drops Index component for duplicate Index elements not sorted

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#36289] opened 2020-09-11 15:15 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

idx1 = pd.Index([0, 0, 1])
idx2 = pd.Index([0, 1])

print(idx1.union(idx2))
# Int64Index([0, 0, 1], dtype='int64')
print(idx2.union(idx1))
# Int64Index([0, 0, 1], dtype='int64')

idx1 = pd.Index([1, 0, 0])

print(idx1.union(idx2))
# Int64Index([0, 0, 1], dtype='int64')
print(idx2.union(idx1))
# Int64Index([0, 1], dtype='int64')

```

#### Problem description

In the fourth call ``idx2.union(idx1)`` one of the ``0`` is dropped. Meaning union() depends on the call order and on the index order, which seems buggy.

#### Expected Output

``Int64Index([0, 0, 1], dtype='int64')`` for every print Statement

#### Output of ``pd.show_versions()``

<details>

master

</details>

**Comment by dsaxton** [comment] 2020-09-11 20:08
Agreed this seems like a bug @phofl. This may be a duplicate of https://github.com/pandas-dev/pandas/issues/31326.

**Comment by phofl** [comment] 2020-09-11 20:13
Similar but not a duplicate. If the indexes both have the same elements it crashes at a different place than the other example.

**Closed** 2021-03-04 02:01 UTC
Labels: Bug, Index
