### ISSUE TITLE
REGR: merge no longer accepts a list for suffixes keyword

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#34741] opened 2020-06-13 09:34 UTC
see https://github.com/pandas-dev/pandas/pull/34208#issuecomment-643598091

The linked PR changed the `merge` routines to now only accept tuples for the `suffixes` keyword, and no longer general sequence.

This is a breaking change (eg it breaks some GeoPandas functions), but actually also changing documented behaviour: the `merge` docstring indeed says "tuple", but eg `merge_asof` still says "tuple or list". And in our user guide, we were ourselves using a list in one example, and it explicitly says "tuple or list" (see https://pandas.pydata.org/pandas-docs/version/1.0/user_guide/merging.html#overlapping-value-columns)

In general, I am certainly fine with restricting the set of accepted types (eg to avoid the confusing issue with sets, the original report), but this is 1) breaking a documented behaviour and 2) a change that could also easily be done with a deprecation warning. 
And given our versioning policy, if it is easy to do a change with a deprecation, then we should try to do that, IMO.

**Comment by jreback** [comment] 2020-06-13 11:03
why are you opening this issue? and how is this a regression?

**Comment by jorisvandenbossche** [comment] 2020-06-13 11:05
Maybe read my linked comment?

**Comment by jreback** [comment] 2020-06-13 12:03
i read your comment

the code was wrong and it’s now fixed
if it happened to work that’s not a reason for a deprecation warning; this is why we have release notes

**Comment by jorisvandenbossche** [comment] 2020-06-13 12:06
It was *documented* to work with a list of strings.

**Comment by jreback** [comment] 2020-06-13 12:27
nope: https://pandas.pydata.org/docs/reference/api/pandas.merge.html?highlight=merge#pandas.merge

**Comment by jorisvandenbossche** [comment] 2020-06-13 12:36
Jeff, please read my original comment: I clearly said that the `merge` user guide indeed indicates that it should be a tuple (the one you linked to), but the `merge_asof` docstring actually mentions list as well (https://pandas.pydata.org/docs/reference/api/pandas.merge_asof.html), and the same for the user guide (https://pandas.pydata.org/pandas-docs/version/1.0/user_guide/merging.html#overlapping-value-columns)

**Comment by jreback** [comment] 2020-06-13 12:47
and your point? deprecating for merge_asof is fine but no action for merge is warranted

just because we can deprecate doesn’t mean we should - this just leaves code around for way too long

so happy to have a patch to deprecate / fix merge_asof as an addendum (which was a doc error initially iirc)

**Comment by jorisvandenbossche** [comment] 2020-06-13 12:55
> deprecating for merge_asof is fine but no action for merge is warranted

It's documented for `merge` as well, in the *user guide*.

> just because we can deprecate doesn’t mean we should - this just leaves code around for way too long

I quote our versioning policy (https://pandas.pydata.org/docs/dev/development/policies.html):

> Whenever possible, a deprecation path will be provided rather than an outright breaking change.

And doing it with a deprecation would be _easily_ possible here.

**Comment by jreback** [comment] 2020-06-13 13:03
it doesn’t matter if it’s easy
and since when does the user guide trump the doc string itself?

as i said i am sympathetic for merge_asof but merge is a good change

if nothing broke in our test suite then there is no reason to revert / change this

geopandas needs a patch here -

**Comment by TomAugspurger** [comment] 2020-06-15 13:06
https://github.com/pandas-dev/pandas/pull/34208 looks like an API breaking change. We'll need to adjust for it here in pandas. Warning that we'll restrict the types in the future seems easiest (and personally I'd be fine with just checking for sets and accepting anything else, but don't have a strong opinion).

**Comment by jorisvandenbossche** [comment] 2020-06-15 13:23
>  personally I'd be fine with just checking for sets and accepting anything else

+1, I think certainly lists would be perfectly fine to keep supporting

**Comment by TomAugspurger** [comment] 2020-06-15 17:16
FWIW, this also broke Dask.

**Comment by jreback** [comment] 2020-06-15 19:34
if u want to change to a deprecation warning ok i guess

but this should be a tuple never a list or anything else iterable

**Comment by jorisvandenbossche** [comment] 2020-06-15 19:50
> but this should be a tuple never a list or anything else iterable

Why not? What is inherently wrong about using a list for this?

**Comment by TomAugspurger** [comment] 2020-06-15 20:57
I think we generally duck-type user arguments like this where there's no ambiguity (i.e. not indexing).

**Closed** 2020-06-30 20:58 UTC
Labels: Blocker
