### ISSUE TITLE
Modifying DataFrame first row produces wrong result

### ISSUE THREAD

**Issue by t6s4** [pandas-dev/pandas#29917] opened 2019-11-28 14:17 UTC
```python
# Reproducing faulty behavior:
dfs = pd.DataFrame([[1,'a1',31],[2,'a2',32],[3,'a3',33]], index=['a','b','c'], columns=['c1','c2','c3'])
dfs.iloc[0] = {'c1':101, 'c2':'A1', 'c3':111}
assert dfs.iloc[0][0] == 101     #FAILED 
assert dfs.iloc[0][1] == 'A1'     #FAILED
assert dfs.iloc[0][2] == 111     #FAILED
```
#### Problem description

Updating first row duplicates column labels.

**Comment by jorisvandenbossche** [comment] 2019-11-28 19:05
Thanks for the report!

According to our docs this should indeed work (https://dev.pandas.io/docs/user_guide/indexing.html#attribute-access, see the "You can also assign a dict to a row of a DataFrame:" a bit below the linked title). The example from there:

```
In [24]: x = pd.DataFrame({'x': [1, 2, 3], 'y': [3, 4, 5]})

In [25]: x.iloc[1] = {'x': 9, 'y': 99}

In [26]: x
Out[26]: 
   x   y
0  1   3
1  9  99
2  3   5
```

Now, in practice, this only seems to work like that if your dataframe has uniform types. Eg if I change the second column to float in the above example, it no longer works:

```
In [63]: x = pd.DataFrame({'x': [1, 2, 3], 'y': [0.3, 0.4, 0.5]})  

In [64]: x.iloc[1] = {'x': 9, 'y': 99}                         

In [65]: x   
Out[65]: 
   x    y
0  1  0.3
1  x    y
2  3  0.5
```

Now, it seems to already been this way for a very long time (tested 0.21 and 0.18, which show the same), so it is certainly not a recent regression (if it ever worked).

BTW, if you want to have this work reliably, you can simply wrap the dict into a Series:

```
In [66]: x = pd.DataFrame({'x': [1, 2, 3], 'y': [0.3, 0.4, 0.5]}) 

In [67]: x.iloc[1] = pd.Series({'x': 9, 'y': 99}) 

In [68]: x 
Out[68]: 
   x     y
0  1   0.3
1  9  99.0
2  3   0.5
```

**Comment by jorisvandenbossche** [comment] 2019-11-28 19:07
See https://github.com/pandas-dev/pandas/issues/16724 for a similar issue (and we came to the same conclusion about the dtypes then :)). 
Closing this as a duplicate.

**Comment by jorisvandenbossche** [comment] 2019-11-28 19:07
Duplicate of https://github.com/pandas-dev/pandas/issues/16724

**Closed by jorisvandenbossche** 2019-11-28 19:07 UTC
Labels: Indexing, Needs Discussion
