### ISSUE TITLE
read_msgpack returns garbage for non-existing files in python2

### ISSUE THREAD

**Issue by languitar** [pandas-dev/pandas#15296] opened 2017-02-03 10:17 UTC
#### Code Sample, a copy-pastable example if possible

```python
In [1]: import pandas as pd

In [2]: pd.__version__
Out[2]: u'0.19.2'

In [3]: pd.read_msgpack('/tmp/bla.txt')
Out[3]: [47, 116, 109, 112, 47, 98, 108, 97, 46, 116, 120, 116]
```

That file does not exist.

The same code with the same version on python 3 correctly raises an exception.

#### Problem description

Reading a non existing file returns a list of integers instead of failing if pandas is used in python 2. This makes detecting error quite hard.

#### Expected Output

An exception.

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.6-1-ARCH
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.utf8
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 34.1.0
Cython: None
numpy: 1.11.3
scipy: 0.18.1
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.5
boto: None
pandas_datareader: None
```

</details>

**Comment by jreback** [comment] 2017-02-03 13:48
I recall this being fixed a little while back. Are you sure you are running with 0.19.2?

```
In [1]: pd.read_msgpack('/tmp/bla.txt')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-7a3c5705a157> in <module>()
----> 1 pd.read_msgpack('/tmp/bla.txt')

/Users/jreback/miniconda3/envs/pandas/lib/python3.5/site-packages/pandas/io/packers.py in read_msgpack(path_or_buf, encoding, iterator, **kwargs)
    216         return read(path_or_buf)
    217 
--> 218     raise ValueError('path_or_buf needs to be a string file path or file-like')
    219 
    220 dtype_dict = {21: np.dtype('M8[ns]'),

ValueError: path_or_buf needs to be a string file path or file-like

In [2]: pd.__version__
Out[2]: '0.19.2'
```

**Comment by languitar** [comment] 2017-02-03 14:02
Yes, definitely 0.19.2. It seems to be fixed only in python 3.

**Comment by jreback** [comment] 2017-02-03 14:05
ahh, that is possible (must not be well tested)

want to add a test and fix? 

I *think* we are doing a better job of this now-a-days in things like ``read_json`` IIRC. IOW if its an actual string, you ask the file system if its valid or not, then raise a *better* error message (e.g. IOError: file not found)

yeah I see this doesn't use ``pandas.io.common.`` to actually open the file, instead it passes it to the msgpack routines. This is where checking for things e.g. in ``read_csv`` happen.

**Comment by chris-b1** [comment] 2017-02-03 15:29
This is a dupe of #12225 (closed that one) - issue is that in python 2 the string is interpreted as bytes.

**Closed** 2017-10-30 12:53 UTC
Labels: 2/3 Compat, Bug, Difficulty Novice, Effort Low, good first issue, Msgpack
