### ISSUE TITLE
Missing spaces between lines and y-axis

### ISSUE THREAD

**Issue by arthurire** [pandas-dev/pandas#27796] opened 2019-08-07 08:14 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import matplotlib.pyplot as plt
plt.plot([1,2],[2,4])
pd.DataFrame([2,4],index=[1,2]).plot()
```
![image](https://user-images.githubusercontent.com/27836456/62605822-750d8d00-b92d-11e9-97ab-964bb09512f7.png)
![image](https://user-images.githubusercontent.com/27836456/62605848-80f94f00-b92d-11e9-9b2b-cf6596595229.png)

#### Problem description

Plots generated by df.plot() and plt.plot() are different and I expected them exactly the same.

As you can see, all the spaces between y-axis and lines are missing when I use pd.DataFrame.plot().

When you have a large dataset and there's a rapid change at the end, the change might be covered by the border, makes the plot hard to read.

![image](https://user-images.githubusercontent.com/27836456/62606618-38db2c00-b92f-11e9-90bc-47c5ed7442e7.png)

![image](https://user-images.githubusercontent.com/27836456/62606610-324cb480-b92f-11e9-92ef-111f705e5a1e.png)

pandas version:0.25.0
matplotlib version:3.1.1

Latest version that works:
pandas:0.23.x
matplotlib 3.0.3

#### Expected Output

Two figures should look exactly the same.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.6.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : zh_CN.UTF-8
LOCALE           : zh_CN.UTF-8

pandas           : 0.25.0
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment] 2019-08-08 16:23
Duplicate of #27686

**Closed by TomAugspurger** 2019-08-08 16:23 UTC
