### ISSUE TITLE
Unable to set origin of inter-day aggregated intervals

### ISSUE THREAD

**Issue by Peque** [pandas-dev/pandas#26808] opened 2019-06-12 11:07 UTC
Having a series like the one bellow, which I resample to `'2D'` frequency and the sum the resulting resampler:

```python
>>> dates = pandas.date_range('2019-01-01', '2019-01-10', freq='D')[[0, 4, 5, 8]]
>>> dates
DatetimeIndex(['2019-01-01', '2019-01-05', '2019-01-06', '2019-01-09'], dtype='datetime64[ns]', freq=None)
>>> pandas.Series(index=dates, data=[0, 1, 2, 3]).resample('2D').sum()
2019-01-01    0
2019-01-03    0
2019-01-05    3
2019-01-07    0
2019-01-09    3
Freq: 2D, dtype: int64
```

As a result, I got an index starting on the first date of the provided dates.

However, if I slightly change the dates so that the first one is `'2019-01-02'` instead of `'2019-01-01'`, I get completely different results:

```python
>>> dates2 = pandas.date_range('2019-01-01', '2019-01-10', freq='D')[[1, 4, 5, 8]]
>>> dates2
DatetimeIndex(['2019-01-02', '2019-01-05', '2019-01-06', '2019-01-09'], dtype='datetime64[ns]', freq=None)
>>> pandas.Series(index=dates2, data=[0, 1, 2, 3]).resample('2D').sum()
2019-01-02    0
2019-01-04    1
2019-01-06    2
2019-01-08    3
Freq: 2D, dtype: int64
```

There is no way to specify a base/origin date for the aggregated intervals like there is for intra-day resampling, right?

Use case
------------

Having multiple time series, not necessarily periodic, not necessarily starting/ending in the same dates, I would like to calculate the correlation between them. To do so, I first need to aggregate the results with a period between 1 day and 1 week (`'2D'`, `'3D'`, `'4D'`...). In order to be able to match the correlation I need indexes to be aligned with respect to a common start date.

Same problem would show up if I wanted to aggregate multiple weeks, months, years... (`'3W'`, `'5M'`, `'2Y'`...)

**Comment by TomAugspurger** [comment] 2019-06-13 20:31
> There is no way to specify a base/origin date for the aggregated intervals like there is for intra-day resampling, right?

That seems to be what the docs indicate, but perhaps things work?

```python
In [31]: s = pd.Series(1, index=dates2)

In [32]: s.resample('2D', base=1).count()
Out[32]:
2019-01-01    1
2019-01-03    0
2019-01-05    2
2019-01-07    0
2019-01-09    1
Freq: 2D, dtype: int64

```

**Comment by Peque** [comment] 2019-06-14 13:29
@TomAugspurger Not really:

```python
def display(begin, end, base):
    series = pandas.Series(1, index=pandas.date_range(begin, end))
    return series.resample('2D', base=base).count()

display('2019-01-01', '2019-01-10', base=1)
"""
2018-12-31    1
2019-01-02    2
2019-01-04    2
2019-01-06    2
2019-01-08    2
2019-01-10    1
Freq: 2D, dtype: int64
"""

display('2018-12-29', '2019-01-10', base=1)
"""
2018-12-28    1
2018-12-30    2
2019-01-01    2
2019-01-03    2
2019-01-05    2
2019-01-07    2
2019-01-09    2
Freq: 2D, dtype: int64
"""
```

Using `base=1` is ambiguous here (is it the first day of the month? of the year? something else?) I think only a date would make sense here.

**Comment by TomAugspurger** [comment] 2019-06-17 13:16
OK, I'm not sure what the expected behavior / API would look like here. I would welcome proposals.

**Comment by mroeschke** [comment] 2021-07-10 04:18
Thanks for the suggestion, but appears this proposal needs more fleshing out and more support from the community and core devs. Closing but happy to reopen if there's more interest

**Closed by mroeschke** 2021-07-10 04:18 UTC
Labels: Enhancement, Resample
