### ISSUE TITLE
PyQt5 and pandas

### ISSUE THREAD

**Issue by dibgerge** [pandas-dev/pandas#16322] opened 2017-05-10 19:28 UTC
I just updated my conda installation to Pandas 0.20.1, and it does not load anymore since it depends on PyQt4 which was updated to PyQt5. 

To make Pandas 0.20.1 load with PyQt5,  I have to modify a function within the ``pandas.io.clipboard.clipboards`` module as follows:

#### Modified function within ``pandas.io.clipboard.clipboards``

```python

def init_qt_clipboard():
    # $DISPLAY should exist
    from PyQt5.QtWidgets import QApplication

    # use the global instance if it exists
    app = QApplication.instance() or QApplication([])

    def copy_qt(text):
        cb = app.clipboard()
        cb.setText(text)

    def paste_qt():
        cb = app.clipboard()
        return text_type(cb.text())

    return copy_qt, paste_qt
```
#### Problem description

The current behavior requires ``PyQt4`` by default, even if it is not needed to be used, which was giving me the error when import pandas:

``ImportError: No module named 'PyQt4.QtGui'``. 

Changing the module as described above solved the problem.

**Comment by jorisvandenbossche** [comment] 2017-05-10 21:45
@dibgerge Thanks for the report. This has (as far as we know) not actually to do with pandas, but we did already fix it by not importing the clipboard (and thus PyQt) functionality on import time (but only when you actually use the `read/to_clipboard` functionality. See https://github.com/pandas-dev/pandas/pull/16294 and https://github.com/pandas-dev/pandas/issues/16288

The reason (at least in my case) you get the error is because `import PyQt4` works, but `from PyQt4 import QtCore, QtGui` failed (I had for some reason an empty PyQt4 directory in my site-packages, maybe leftover from an update).

**Comment by dibgerge** [comment] 2017-05-11 03:27
@jorisvandenbossche Thank you for your clarification. Yes, that is what I have also. It looks like Conda deleted my PyQt4 module content but left the directory when it installed PyQt5.

**Comment by jorisvandenbossche** [comment] 2017-05-11 08:42
Thanks for the confirmation, seems we had the same problem. Although I really don't know how conda can end up there. (tried in in a clean env to first install pyqt 4 and then update, but can't reproduce)

**Comment by kalefranz** [comment] 2017-05-11 10:35
@jorisvandenbossche @dibgerge I know it won't be exact, but could you give me a rough idea of the conda version you were using?  Or just `conda info`.

**Comment by jorisvandenbossche** [comment] 2017-05-11 12:06
Closing this, as further discussion can go on https://github.com/conda/conda/issues/5290 (and in 0.20.2 will already be a fix to not do the PyQt4 check on main pandas import)

**Closed by jorisvandenbossche** 2017-05-11 12:06 UTC
Labels: Duplicate

**Comment by Nikhilkumar8143** [comment] 2020-04-07 18:23
> I just updated my conda installation to Pandas 0.20.1, and it does not load anymore since it depends on PyQt4 which was updated to PyQt5.
> 
> To make Pandas 0.20.1 load with PyQt5, I have to modify a function within the `pandas.io.clipboard.clipboards` module as follows:
> 
> #### Modified function within `pandas.io.clipboard.clipboards`
> ```python
> def init_qt_clipboard():
>     # $DISPLAY should exist
>     from PyQt5.QtWidgets import QApplication
> 
>     # use the global instance if it exists
>     app = QApplication.instance() or QApplication([])
> 
>     def copy_qt(text):
>         cb = app.clipboard()
>         cb.setText(text)
> 
>     def paste_qt():
>         cb = app.clipboard()
>         return text_type(cb.text())
> 
>     return copy_qt, paste_qt
> ```
> 
> #### Problem description
> The current behavior requires `PyQt4` by default, even if it is not needed to be used, which was giving me the error when import pandas:
> 
> `ImportError: No module named 'PyQt4.QtGui'`.
> 
> Changing the module as described above solved the problem.

Even I am having the same problem,I tried doing in your way but the current version already adds with try and catch block for pyqt.Please reply me I need to have a solution for this:

AttributeError: partially initialized module 'pandas' has no attribute 'plotting' (most likely due to a circular import)
