### ISSUE TITLE
BUG:  pandas.to_csv() saves column values as integers when column contains numbers as string

### ISSUE THREAD

**Issue by sudhNau** [pandas-dev/pandas#43621] opened 2021-09-17 15:01 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
pre_save = pd.DataFrame({'b': ['1', '2', '3', '4']})
assert pre_save.b[1] == '2'
pre_save.to_csv('pre_save')

post_save = pd.read_csv('pre_save')
assert post_save.b[1] == '2' ## Results in assertion error
assert post_save.b[1] == 2 ## Run properly
```

### Issue Description

While saving a dataframe that contains numbers as string in its columns as a csv, Pandas converts the data type automatically and saves column values as numbers instead of string. 

One could also verify the behavior by looking at the csv file generated by .to_csv function. It contains normal numbers instead of double quoted ones. 

### Expected Behavior

import pandas as pd
pre_save = pd.DataFrame({'b': ['1', '2', '3', '4']})
assert pre_save.b[1] == '2'
pre_save.to_csv('pre_save')

post_save = pd.read_csv('pre_save')
assert post_save.b[1] == '2' ## This should not result in assertion error

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 57.0.0
Cython           : None
pytest           : 5.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.0
IPython          : 7.5.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.0
pytables         : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by phofl** [comment] 2021-09-17 17:39
This is the expected behavior. Please check the quoting argument

**Comment by sudhNau** [comment] 2021-09-17 20:10
@phofl Not sure about that tbh, I checked the quoting argument it seems to be about floating point to string conversion, the issue here is about automatic character to int conversion. 

fwiw, I tried all the four available options for quoting, but none of them solved the problem. 


```
import pandas as pd
import csv
pre_save = pd.DataFrame({'b': ['1', '2', '3', '4']})
for q in [csv.QUOTE_ALL, csv.QUOTE_MINIMAL, csv.QUOTE_MINIMAL, csv.QUOTE_NONNUMERIC]:
    pre_save.to_csv('pre_save.csv', quoting=q)
    post_save = pd.read_csv('pre_save.csv')
    if post_save.b[1] == '2':
        print('Worked!')
else:
    print('Nope!')
```

**Comment by phofl** [comment] 2021-09-17 21:18
In the end csv files do Not store dtypes. Safest option is to convert when reading

**Comment by sudhNau** [comment] 2021-09-20 08:25
Not actual dtypes but surely char vs integers data types can/should be preserved. 

```
'b'
'1'
'2'
'3'
'4'

v/s

'b'
1
2
3
4 
```

**Comment by phofl** [comment] 2021-09-20 19:33
The following works for me:

```
pre_save = pd.DataFrame({'b': ["1"]})
pre_save.to_csv('pre_save.csv', quoting=csv.QUOTE_ALL, index=False)

pd.read_csv("pre_save.csv", quoting=csv.QUOTE_NONE, engine="python").dtypes
```

This is not interpreted correctly for the c engine, but I think we have an open issue for that

**Comment by phofl** [comment] 2021-09-20 19:44
duplicate of #31821

**Closed** 2021-09-20 19:44 UTC
Labels: Usage Question, IO CSV
