### ISSUE TITLE
REGR: `replace` casts columns to `object`

### ISSUE THREAD

**Issue by dmh43** [pandas-dev/pandas#32988] opened 2020-03-24 22:06 UTC
#### Calling `df.replace` casts columns to `object`

```python
pd.DataFrame(np.eye(2)).replace(to_replace=[None, -np.inf, np.inf], value=pd.NA).dtypes
# 0    object
# 1     object
# dtype: object
```
#### Problem description
I'd expect that the dtypes of the columns remain the same after replacing with pd.NA (especially considering no values are replaced in the above call). We do not get this issue if `to_replace` is any subset of `[None, -np.inf, np.inf]`. We get the same issue if `value` is instead `np.nan`.

#### Expected Output
```python
# 0    float64
# 1     float64
# dtype: object
```
#### Output of ``pd.show_versions()``

<details>
Installed with `pip install -e .` on current master. Was also able to reproduce on `1.0.1`.

INSTALLED VERSIONS
------------------
commit           : bed9103e52ae412774c22b8e198f7b66708981c7
python           : 3.7.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.26.0.dev0+2701.gbed9103e5
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.1.1.post20200323
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment] 2020-03-26 22:50
I debugged this a bit. The reason seems to be here:
[ https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals/blocks.py#L737](
 https://github.com/pandas-dev/pandas/blob/master/pandas/core/internals/blocks.py#L737)

````block = self.astype(object)
            return block.replace(
                to_replace=to_replace,
                value=value,
                inplace=inplace,
                filter=filter,
                regex=regex,
                convert=convert,
            )
```

The function tries the replace again after converting the FloatBlock to an ObjectBlock. We could try to convert the ObjectBlock back after executing the replace. I tried this for the example mentioned above and ran the relevant (I hope I ran all relevant :)) tests.

I committed the small change [here](https://github.com/pandas-dev/pandas/compare/master...phofl:bug_type_casting_replace). If this is a desired fix, I would add tests and create a pull request.

**Comment by dmh43** [comment] 2020-03-27 20:29
Thanks for looking into this! Unfortunately, I'm not familiar enough with pandas internals to review your changes.

**Comment by simonjayhawkins** [comment] 2020-03-28 20:21
> We get the same issue if `value` is instead `np.nan`

this was working in 0.25.3 so this is a regression

```python
>>> import numpy as np
>>>
>>> import pandas as pd
>>>
>>> pd.__version__
'0.25.3'
>>>
>>> pd.DataFrame(np.eye(2)).replace(to_replace=[None, -np.inf, np.inf], value=np.nan).dtypes
0    float64
1    float64
dtype: object
>>>
```

```python
>>> import numpy as np
>>>
>>> import pandas as pd
>>>
>>> pd.__version__
'1.1.0.dev0+1008.g60b0e9fbc'
>>>
>>> pd.DataFrame(np.eye(2)).replace(to_replace=[None, -np.inf, np.inf], value=np.nan).dtypes
0    object
1    object
dtype: object
```

**Comment by simonjayhawkins** [comment] 2020-03-28 21:03
> this was working in 0.25.3 so this is a regression

01f90c187f0eec0e8178371d7c066e600c9e105b is the first bad commit
commit 01f90c187f0eec0e8178371d7c066e600c9e105b
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Mon Aug 12 11:58:42 2019 -0700

    CLN: short-circuit case in Block.replace (#27768)

**Comment by simonjayhawkins** [comment] 2020-04-05 10:20
cc @jbrockmendel

**Closed** 2020-05-09 20:07 UTC
Labels: Dtypes, Regression, replace
