### ISSUE TITLE
BUG: ModuleNotFoundError: No module named 'sqlite3'

### ISSUE THREAD

**Issue by rmarquet21** [pandas-dev/pandas#53523] opened 2023-06-05 08:50 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mariadb+mariadbconnector://root:root@host:3306/database")

query = "SELECT * FROM table"

with engine.connect() as conn:
  dataset = pd.read_sql_query(query, conn)
```

### Issue Description

The execution of my function fails when trying to read a sql query. The system raises a ModuleNotFoundError, unable to find the 'sqlite3' module. Can be a conflict of dependencies between SQLAlchemy and Pandas ? 

## Error:
```
Traceback (most recent call last):
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/bin/alfred", line 8, in <module>
    sys.exit(cli())
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/alfred/cli.py", line 111, in invoke
    super().invoke(ctx)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/alfred/domain/command.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/alfred/pipeline.py", line 45, in pipeline_ner
    dataframe = load_dataset_from_database(insight)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/src/steps/database.py", line 28, in load_dataset_from_database
    dataset = pd.read_sql_query(query, conn)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/pandas/io/sql.py", line 396, in read_sql_query
    pandas_sql = pandasSQL_builder(con)
  File "/Users/robin/Documents/ReportLinker/rd/smart-data/.venv/lib/python3.10/site-packages/pandas/io/sql.py", line 742, in pandasSQL_builder
    import sqlite3
ModuleNotFoundError: No module named 'sqlite3'
```

## Dependencies:
<details>
[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.0.1"
tqdm = "^4.65.0"
pandas = "1.5.3"
alfred-cli = "^2.0.0"
transformers = "^4.29.2"
joblib = "^1.2.0"
sqlalchemy = "2.0.3"
google-api-python-client = "^2.88.0"
boto3 = "^1.26.146"
pymysql = "^1.0.3"
google-auth-oauthlib = "^1.0.0"
mariadb = "^1.1.6"
streamlit = "^1.23.1"
st-annotated-text = "^4.0.0"
jupyter = "^1.0.0"
watchdog = "^3.0.0"
stqdm = "^0.0.5"
scikit-learn = "^1.2.2"
packaging = "^23.1"
pyyaml = "^6.0"
elasticsearch = "<7.14.0"
numpy = "^1.24.3"
black = {extras = ["jupyter"], version = "^23.3.0"}

[tool.poetry.group.dev.dependencies]
mypy = "^1.3.0"
black = "^23.3.0"
isort = "^5.12.0"
autoflake = "^2.1.1"
flake8 = "^6.0.0"
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
</details>

### Expected Behavior

The dataframe should be successfully saved in the SQL database.

### Installed Versions

<details>

/Users/robin/.pyenv/versions/3.10.11/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.11.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.1.0
Version          : Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : 2023.3
</details>

**Comment by asishm-wk** [comment] 2023-06-05 11:40
sqlite3 is a python stdlib library. How did you install python?

**Comment by rmarquet21** [comment] 2023-06-05 12:05
I understood that, but after several re-installation of python, tries on another machine, the problem persists.

**Comment by rmarquet21** [comment] 2023-06-05 12:28
```
import sqlite3

if __name__ == '__main__':
    print(sqlite3.version)
```

Return: `2.6.0`

That works well...

**Comment by matteosantama** [comment] 2023-06-09 23:08
```python
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mariadb+mariadbconnector://root:root@host:3306/database")

query = "SELECT * FROM table"

with engine.connect() as conn:
  dataset = pd.read_sql_query(query, conn)
```

```python
import sqlite3

if __name__ == '__main__':
    print(sqlite3.version)
```

Are you sure these are being run in the same environment? What happens if you modify the first script to `import sqlite3` too?

I see other `pyenv` users reporting a similar [issue](https://stackoverflow.com/a/38842600/20985141) but it doesn't explain why one script would work and the other doesn't.

**Comment by mroeschke** [comment] 2023-07-27 18:49
Thanks for the issue but it seems that others cannot reproduce the behavior and this is not strictly a pandas issue so closing

**Closed by mroeschke** 2023-07-27 18:49 UTC
Labels: Bug, IO SQL, Needs Info
