### ISSUE TITLE
Clip Could take Series/DataFrames

### ISSUE THREAD

**Issue by rhaskett** [pandas-dev/pandas#2657] opened 2013-01-08 16:10 UTC
I was a little surprised when clip would not take other pandas objects as parameters.  I hacked a little something below, but for readability I thought I might suggest that this feature be added.

```
df1 = DataFrame(ones((2, 2)))
data = ones((2, 2))
data[0, 0] = 0
data[1, 1] = 2
df2 = DataFrame(data)
print df2.clip(1.5, 0.5)

df3 = df2.copy()
df3[df2 > df1 * 1.5] = (df1 * 1.5)[df2 > df1 * 1.5]
df3[df2 < df1 * .5] = (df1 * .5)[df2 < df1 * .5]
print df3
```

**Comment by kokes** [comment] 2018-10-19 21:57
Isn't this a duplicate of #6966? I've just tested the second example and it does work.

**Comment by jreback** [comment] 2018-10-19 22:01
yep

**Closed by jreback** 2018-10-19 22:01 UTC
Labels: Enhancement

**Comment by brandon-rhodes** [comment] 2018-10-20 13:53
I was commenting on Pandas issues back in 2013 — five years ago? Wow, I've used Pandas for a long time!

I'm happy to hear that clipping against series is now possible!
