### ISSUE TITLE
dtype passed into read_csv as an arg not passed to the dataframe when being created

### ISSUE THREAD

**Issue by pgospodinov** [pandas-dev/pandas#32496] opened 2020-03-06 16:13 UTC
https://github.com/pandas-dev/pandas/blob/015c1c154b9bc70d3b1981ba1dc31c09676065bf/pandas/io/parsers.py#L1143

Is this the desired behaviour? Maybe I am missing something but when we pass dtype to read_csv, the dtype is not used anywhere. Passing it to the dataframe when creating it seems like a good place for that.

**Comment by jreback** [comment] 2020-03-06 16:23
pls show an actual example

dtypes are handled during parsing

**Comment by pgospodinov** [comment] 2020-03-06 16:37
Sorry, can you elaborate on what sort of information you need? This is the input file I am using:
![Screenshot 2020-03-06 at 16 30 42](https://user-images.githubusercontent.com/30042410/76102643-337ab880-5fc8-11ea-9874-4d738250e917.png)
This is the dtype dict I have passed to read_csv:
![Screenshot 2020-03-06 at 16 34 17](https://user-images.githubusercontent.com/30042410/76102747-63c25700-5fc8-11ea-8af1-2b63da74ebe8.png)

**Comment by jreback** [comment] 2020-03-06 17:05
an example of code that is fully copy pastable to reproduce

**Comment by pgospodinov** [comment] 2020-03-06 17:09
in the meantime, can you tell me where in the code dtype is used/compared to the inferred by pandas data types? I tried debugging without success. Additionally, does pandas always infer dtype object because so far this is my experience with it.

**Comment by jreback** [comment] 2020-03-06 18:06
this is not a bug pls read the docs

if you have a reproducible example show it

**Comment by pgospodinov** [comment] 2020-03-06 21:02
ok, you are saying that dtype shouldnt be passed to the dataframe? where is it passed then? the docs for read_csv have a one liner about dtype which states the obvious. this is why I started debugging the code in the first place? regarding an example anything works. i am talking for a very general case here, where you read the simplest csv file with a specified dtype as an argument

**Comment by TomAugspurger** [comment] 2020-03-06 21:07
By the time you get to the line you highlighted in the original post, the values should have already been parsed with the correct dtypes.

If you have an example where that's not the case, then please provide one.

**Comment by pgospodinov** [comment] 2020-03-06 21:11
@TomAugspurger can you show me where in the code this happens? and why not just pass them to the dataframe since the dataframe has this functionality

**Comment by TomAugspurger** [comment] 2020-03-06 21:14
I'm not sure offhand. Do you have an example of this failing? Otherwise,
we'll likely just close the issue to avoid going around in circles.

**Comment by pgospodinov** [comment] 2020-03-06 21:19
if you don't use the dtype argument anywhere, it is failing in every case where dtype is passed as an argument to read_csv. you don't pass it to the dataframe and you can't show me where you use it in the codebase. if you dont know, can you refer me to someone who does or tag him in this post?

**Comment by jreback** [comment] 2020-03-06 21:29
@pgospodinov you need to show an example with full version information

**Comment by TomAugspurger** [comment] 2020-03-11 14:01
@pgospodinov if you can provide a minimal example we'll reopen. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Closed by TomAugspurger** 2020-03-11 14:01 UTC
Labels: Needs Info
