### ISSUE TITLE
Add parameter always_suffix to DataFrame.merge

### ISSUE THREAD

**Issue by lverweijen** [pandas-dev/pandas#18260] opened 2017-11-13 13:06 UTC
#### Code Sample

```python
A = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
B = pd.DataFrame({'a': [1, 2, 3], 'c': [7, 8, 9]})

def foo(A, B):
    C = A.merge(B, on=['a'])
    C['c']  # Where does c originate from?

```
#### Problem description

There is no way to explicitely specificy whether 'c' originates from A or B. This makes code harder to maintain. Better would be if I could write something like:

```python
C = A.merge(B, on=['a'], always_suffix=True)
C['c_y]  # Obvious that C comes from B, because suffixes are always created
```

**Comment by jreback** [comment] 2017-11-13 13:24
this is a dupe of #17834

**Closed by jreback** 2017-11-13 13:24 UTC
