### ISSUE TITLE
When excel cell with 0x005F_FFFF, pandas read excel with wrong output read value 0FFFF

### ISSUE THREAD

**Issue by Kane-W** [pandas-dev/pandas#58128] opened 2024-04-03 10:17 UTC
pd.read_excel with output 0FFFF
however， 0x004F_FFFF, pd read the right value 0x004F_FFFF

**Comment by rhshadrach** [comment] 2024-04-03 12:03
Thanks for the report. Can you provide a reproducible example.

**Comment by rhshadrach** [comment] 2024-04-07 13:19
Thanks @Kane-W - this is a good reproducible example. It would be helpful if you could make this easier for pandas developers to reproduce. This means providing the code as text rather than a screenshot (so we can copy & paste rather than having to transcribe the screenshot), and removing any need for external files (where possible). Can you create the Excel file by doing something like:

```
df = pd.DataFrame(...)
df.to_excel("test.xlsx")
```

**Comment by Kane-W** [comment] 2024-04-07 13:29
`import pandas as pd

print(pd.__version__)

file = "./test.xlsx"
xls = pd.ExcelFile(file)
print(xls)
data = pd.read_excel(xls, "test", dtype="object")
print(data)`

[test.xlsx](https://github.com/pandas-dev/pandas/files/14897344/test.xlsx)

**Comment by asishm** [comment] 2024-04-07 13:57
```py
import pandas as pd
from io import BytesIO

fo = BytesIO()
data = {'ITEM': ['a', 'b', 'c', 'd'], 'VALUE': ['0x005F_FFFF', '0x004F_FFFF', '0x005f_ffff', '0x004f_ffff']}
df = pd.DataFrame(data)

df.to_excel(fo, index=False)
fo.seek(0)

for engine in ['openpyxl', 'calamine']:
    print(engine)
    print(pd.read_excel(fo, dtype="object", engine=engine))
    print()
```

outputs:

```
openpyxl
  ITEM        VALUE
0    a        0FFFF
1    b  0x004F_FFFF
2    c  0x005f_ffff
3    d  0x004f_ffff

calamine
  ITEM        VALUE
0    a  0x005F_FFFF
1    b  0x004F_FFFF
2    c  0x005f_ffff
3    d  0x004f_ffff
```

looks like this is only with the openpyxl engine, calamine returns fine

**Comment by asishm** [comment] 2024-04-07 14:29
Seems related https://foss.heptapod.net/openpyxl/openpyxl/-/issues/2099

**Comment by rhshadrach** [comment] 2024-04-08 12:39
Thanks @asishm for the investigation - agreed. Closing as an upstream issue.

**Closed by rhshadrach** 2024-04-08 12:39 UTC
Labels: Bug, IO Excel, Needs Triage
