### ISSUE TITLE
Rolling on groupby result gives different result than rolling on each group

### ISSUE THREAD

**Issue by MichaelNorman** [pandas-dev/pandas#24934] opened 2019-01-25 18:03 UTC
#### Tell me if the last 2 out of 3 games played by player were category 3:
```python
import pandas as pd
match = ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'c', 'd', 'd', 'd', 'e', 'e', 'e', 'e']
category = [3, 3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2]
player = ['bar', 'baz', 'chaz', 'baz', 'choo', 'chaz', 'chaz', 'foo', 'baz', 'choo', 'foo', 'char', 'baz', 'choo', 'foo', 'chaz', 'baz']
hc = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
games = pd.DataFrame({'match': match, 'category': category, 'player': player, 'hc': hc})
games['hicat'] = games.category.gt(2)

for k,g in games.groupby('player'):
    print(k)
    print(g.shift().rolling(3, min_periods=2).hicat.sum().fillna(0, downcast='infer').astype(int).gt(1))
# ...
# Relevant bit, and correct:
# choo
# 4     False
# 9     False
# 13    False
#       ^^^^^
# Name: hicat, dtype: bool
# ...

games["hicat_calc"] = games.groupby('player').shift().rolling(3, min_periods=2).hicat.sum().fillna(0, downcast='infer').astype(int).gt(1)
games
# Relevant bit, incorrect, and different than before. (Row 13. hicat_calc should be false, as above):
#    match  category player  hc  hicat  hicat_calc
# ...
# 4      b         2   choo   0  False    False
# ...
# 9      c         3   choo   0   True    False
# ...
# 13     e         2   choo   0  False     True
# ...                                      ^^^^ !!!

```
#### Problem description
Pandas produces different results for rolling() with min_periods when iterating over groups vs. applying operations directly to the rolling() output.

#### Actual Output
`rolling()` must be doing bizarre stuff in the background, because the straightforward calculation above yields different answers for the iterating case vs the straight application. We get `False` in row 13 of the iterating case, and `True` in the latter. ("`False`" is the correct output.)

#### Expected Output
A lot of things, really. `rolling()` is a mess. However, the expected output is either that the incorrect result should be encountered both when iterating over the groups, or that the correct one should be encountered both times. Preferably the latter.
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
pd.show_versions()
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by MichaelNorman** [comment] 2019-01-25 18:25
I might be overlooking a detail. I hate to go all StackOverflow and ask for help, but how does one shift each result of a `groupby()` without iterating? Am I stuck with `apply()` (which is dead slow)? It does seem to me like `df.groupby(column).shift()...` should shift within each group, however.

**Comment by WillAyd** [comment] 2019-01-25 18:40
I misread your original post but at the same time based off of your last response I don't think the issue is where you think it is. You should be able to shift after a groupby, so if you inspect the result of:

```python
games.groupby('player')['hicat'].shift() 
```

It will be roughly equivalent to

```python
for k, g in games.groupby('player'): 
    g['hicat'].shift() 
```

Save the piece of actually glueing all of the elements back together in the former.

Can you take another look and make a *minimal* example which isolates the issue you see:

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MichaelNorman** [comment] 2019-01-25 20:40
I do think you've misread it. For one:
```python
games.groupby('player').shift()['hicat'].fillna(True) == games.groupby('player')['hicat'].shift().fillna(True)
0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
```
So, the order of the selector and the shift doesn't change anything. Also, I'm not shifting a `DataFrame`, I'm shifting a `DataFrameGroupBy` object. I can see why someone would want to "shift groups," but, clearly, people would also want to shift _within_ groups.

Further, this is a minimal example that produces the bug. Shorter examples do not produce it. Longer examples are longer. I'm beginning to doubt whether pandas actually can tell me how many times out of the previous n occurrences that a certain event happened. That's another story, though.

What I'm after is given by:
```python
games.groupby('player').category.apply(lambda x: x.shift().gt(2).rolling(3).sum().fillna(0, downcast='infer').astype(int).gt(1))
```
However, on a modest df with 250k rows, this takes 12s. If this is the right way to get around this bug, I guess I'll have to be fine with that.

**Comment by WillAyd** [comment] 2019-01-29 02:50
So the problem here is that the calls you have aren't equivalent, and the diversion happens right at this point:

```python
In [23]: games.groupby('player').shift()                                                                                             
Out[23]: 
   match  category   hc  hicat hicat_calc
0    NaN       NaN  NaN    NaN        NaN
1    NaN       NaN  NaN    NaN        NaN
2    NaN       NaN  NaN    NaN        NaN
3      a       3.0  0.0   True      False
4    NaN       NaN  NaN    NaN        NaN
5      a       3.0  0.0   True      False
6      b       2.0  0.0  False       True
7    NaN       NaN  NaN    NaN        NaN
8      b       2.0  0.0  False      False
9      b       2.0  0.0  False      False
10     c       3.0  0.0   True      False
11   NaN       NaN  NaN    NaN        NaN
12     c       3.0  0.0   True      False
13     c       3.0  0.0   True      False
14     d       3.0  0.0   True      False
15     c       3.0  0.0   True      False
16     d       3.0  1.0   True       True
```

vs 

```python
In [22]: for k, g in games.groupby('player'): 
    ...:     print(g.shift()) 
    ...:                                                                                                                             
  match  category player  hc hicat hicat_calc
0   NaN       NaN    NaN NaN   NaN        NaN
   match  category player   hc  hicat hicat_calc
1    NaN       NaN    NaN  NaN    NaN        NaN
3      a       3.0    baz  0.0   True      False
8      b       2.0    baz  0.0  False      False
12     c       3.0    baz  0.0   True      False
16     d       3.0    baz  1.0   True       True
   match  category player  hc hicat hicat_calc
11   NaN       NaN    NaN NaN   NaN        NaN
   match  category player   hc  hicat hicat_calc
2    NaN       NaN    NaN  NaN    NaN        NaN
5      a       3.0   chaz  0.0   True      False
6      b       2.0   chaz  0.0  False       True
15     c       3.0   chaz  0.0   True      False
   match  category player   hc  hicat hicat_calc
4    NaN       NaN    NaN  NaN    NaN        NaN
9      b       2.0   choo  0.0  False      False
13     c       3.0   choo  0.0   True      False
   match  category player   hc hicat hicat_calc
7    NaN       NaN    NaN  NaN   NaN        NaN
10     c       3.0    foo  0.0  True      False
14     d       3.0    foo  0.0  True      False
```

The former returns a DataFrame whereas the latter is still iterating over the groups, hence the difference in the application of the `.rolling` function.

**Comment by WillAyd** [comment] 2019-03-26 05:39
Closing per latest response - I don't think there's a bug here but if you disagree feel free to reopen

**Closed by WillAyd** 2019-03-26 05:39 UTC
Labels: Usage Question
