### ISSUE TITLE
Allow custom metadata to be attached to panel/df/series?

### ISSUE THREAD

**Issue by ghost** [pandas-dev/pandas#2485] opened 2012-12-11 06:21 UTC
related:
https://github.com/pydata/pandas/issues/39 (column descriptions)
https://github.com/pydata/pandas/issues/686 (serialization concerns)
https://github.com/pydata/pandas/issues/447#issuecomment-11152782 (Feature request, implementation variant)

Ideas and issues:
- is pickle stable enough?
- serialization req. potentially couples this with storage format
- allow arbitrary python objects?
- impl. option: JSONables-only + type tag + load/save callback hook
- getter/setter or attribute style access (limits naming)?
- flat or hirarchical?

**Comment by bilderbuchi** [comment] 2016-01-21 07:46
Any news on this issue? I just found myself wishing for the possibility to attach metadata (probably in a dict) to a dataframe.

**Comment by jreback** [comment] 2016-01-21 12:35
its certainly possible to add a default propogated attribute like ``.attrs`` via the ``_metadata/__finalize__`` machinery. IIRC geopoandas does this.

But would need quite a bit of auditing and testing. You are welcome to have a go. Can you show your non-trivial use case?

**Comment by bilderbuchi** [comment] 2016-01-21 13:06
My use case would probably be similar to what I imagine @hugadams meant when talking about working with spectroscopy results - data that are constant for the whole dataframe, like
* when working with output from machines/lab setups: a machine ID, calibration settings, user IDs, scaling factors for pressure transducers,...
* when doing data analyis: filenames of input files, git hash of the analysis code (for Reproducibl Science), config file contents,
* when doing simulations: git hash of the simulation code (see above), parameters of a batch run creating the dataframe in question...
Right now I did some systems modelling, and wanted to carry along the name of the scenario that I analyze. As I didn't feel it appropriate to just fill a column with nothing but "scenario 1", I ended up abusing `dataframe.columns.name` for this - doesn't feel appropriate or idiomatic, but sufficient for this one case since I only wanted to attach *one* string.

**Comment by nzjrs** [comment] 2016-01-21 13:09
I have the same use case as @bilderbuchi (recording scientific experimental metadata)

 * subject information - genotype, gender, age
 * experiment information - version hashes, config hashes

**Comment by hugadams** [comment] 2016-01-21 13:54
It's now much easier to subclass a dataframe and add your own attributes
and methods.  This wasn't the case when I started the issue

**Comment by nzjrs** [comment] 2016-01-21 13:56
yeah, but something that round-trips through a vanilla pickled dataframe would be preferable

**Comment by dacoex** [comment] 2016-01-23 13:28
Would the features offered by xarray be somthing that can be adopted here?
[Data Structures](http://xarray.pydata.org/en/stable/data-structures.html)

They have data attributes. If pandas could get the same features, this would be great.
Unit conversion, unit propagation, etc.

**Comment by hugadams** [comment] 2016-01-23 18:32
I think xarrayis what you want.

You may also try this metadataframe class I wrote a few years ago.  It may
not longer work with pandas versions, but I haven't tried.

https://github.com/hugadams/scikit-spectra/blob/b6171bd3c947728e01413fe91ec0bd66a1a02a34/skspec/pandas_utils/metadframe.py

You should be able to download that file, then just make a class that has
attributes like you want. IE

df = MetaDataframe()
df.a = a
df.b = b

I thought that after 0.16, it was possible to simply subclass a dataframe,
right?

IE

class MyDF(DataFrame)
     self.a = 50
     self.b = 20

Or is this not the case?

On Sat, Jan 23, 2016 at 8:28 AM, DaCoEx <notifications@github.com> wrote:

> Would the features offered by xarray be somthing that can be adopted here?
> Data Structures <http://xarray.pydata.org/en/stable/data-structures.html>
>
> They have data attributes. If pandas could get the same features, this
> would be great.
> Unit conversion, unit propagation, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/pandas/issues/2485#issuecomment-174186659>.
>



-- 
Adam Hughes
Physics Ph.D Candidate
George Washington University

**Comment by hugadams** [comment] 2016-01-23 18:37
Here's what I was talking about:

http://pandas.pydata.org/pandas-docs/stable/internals.html#override-constructor-properties

On Sat, Jan 23, 2016 at 1:32 PM, Adam Hughes <hugadams@gwmail.gwu.edu>
wrote:

> I think xarrayis what you want.
>
> You may also try this metadataframe class I wrote a few years ago.  It may
> not longer work with pandas versions, but I haven't tried.
>
>
> https://github.com/hugadams/scikit-spectra/blob/b6171bd3c947728e01413fe91ec0bd66a1a02a34/skspec/pandas_utils/metadframe.py
>
> You should be able to download that file, then just make a class that has
> attributes like you want. IE
>
> df = MetaDataframe()
> df.a = a
> df.b = b
>
> I thought that after 0.16, it was possible to simply subclass a dataframe,
> right?
>
> IE
>
> class MyDF(DataFrame)
>      self.a = 50
>      self.b = 20
>
> Or is this not the case?
>
> On Sat, Jan 23, 2016 at 8:28 AM, DaCoEx <notifications@github.com> wrote:
>
>> Would the features offered by xarray be somthing that can be adopted here?
>> Data Structures <http://xarray.pydata.org/en/stable/data-structures.html>
>>
>> They have data attributes. If pandas could get the same features, this
>> would be great.
>> Unit conversion, unit propagation, etc.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pydata/pandas/issues/2485#issuecomment-174186659>.
>>
>
>
>
> --
> Adam Hughes
> Physics Ph.D Candidate
> George Washington University
>



-- 
Adam Hughes
Physics Ph.D Candidate
George Washington University

**Comment by dacoex** [comment] 2016-01-25 08:45
>I think xarrayis what you want.

So did you want to express that all aiming at using metadata may better use xarray?

**Comment by shoyer** [comment] 2016-01-25 16:13
> They have data attributes. If pandas could get the same features, this would be great.
Unit conversion, unit propagation, etc.

Just to be clear, xarray does support adding arbitrary metadata, but not automatic unit conversion. We could hook up a library like pint to handle this, but it's difficult to get all the edge cases working until numpy has better dtype support.

**Comment by nzjrs** [comment] 2016-01-25 16:24
I think 'automatic unit conversion based on metadata attached to series' is
a significantly different and more involved feature request to this issue.
I hope a simpler upstream supported solution allowing attaching simple
text-only metadata can be found before increasing the scope too much.

**Comment by jreback** [comment] 2016-01-25 16:46
This is quite simple in current versions of pandas.

I am using a sub-class here for illustration purposes.
Really all that would be needed would be adding the ``__finalize__`` to most of the construction methods
(this already exists now for ``Series``, but not really for ``DataFrame``).

unambiguous propogation would be quite easy, and users could add in there own ``__finalize__`` to handle more complicated cases (e.g. what would would you do when you have ``df + df2``)? 
```
In [1]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:from pandas import DataFrame
:
:class MyDataFrame(DataFrame):
:    _metadata = ['attrs']
:
:    @property
:    def _constructor(self):
:        return MyDataFrame
:
:    def _combine_const(self, other, *args, **kwargs):
:        return super(MyDataFrame, self)._combine_const(other, *args, **kwargs).__finalize__(self)
:--

In [2]: df = MyDataFrame({'A' : [1,2,3]})

In [3]: df.attrs = {'foo' : 'bar'}

In [4]: df.attrs
Out[4]: {'foo': 'bar'}

In [5]: (df+1).attrs
Out[5]: {'foo': 'bar'}
```

Would take a patch for this, the modification are pretty straightforward, its the testing that is the key here.

**Comment by postelrich** [comment] 2016-09-30 18:58
@jreback is there a generic way to persist metadata amongst all transforms applied to a dataframe including groupbys? Or would one have to go through and override a lot of methods' to call `__finalize__`?

**Comment by jreback** [comment] 2016-09-30 21:27
@postelrich for most/all things, ``__finalize__`` should already be defined (and so in theory you can make it persist attributes). Its not tested really well though.

**Comment by jbrockmendel** [comment] 2017-07-20 23:28
I've been working on an implementation of this that handles the propagation problem by making the Metadata object itself subclass Series.  Then patch Series to relay methods to Metadata.  Roughly:

```
class MSeries(pd.Series):
    def __init__(self, *args, **kwargs):
        pd.Series.__init__(self, *args, **kwargs)
        self.metadata = SMeta(self)

    def __add__(self, other):
        res = pd.series.__add__(self, other)
        res.metadata = self.metadata.__add__(other)
        return res

class SMeta(pd.Series):
    def __init__(self, parent):
        super(...)
        self.parent = parent

    def __add__(self, other):
        new_meta = SMeta(index=self.index)
        other_meta = [... other or other.metadata or None depending ...]
        for key in self.index:
             new_meta[key] = self[key].__add__(other)
```

So it is up to the individual MetaDatum classes to figure out how to propagate.

I've generally got this working.  The part that I have not gotten working is the desired `MFrame` behavior `df.metadata['A'] is df['A'].metadata`.  Any ideas on how to make that happen?

**Comment by JochemBoersma** [comment] 2017-09-20 09:15
Propagation of attributes (defined in _metadata) gives me some headaches...

Based on the code of jreback, I've tried the following:
```
from pandas import DataFrame
class MyDataFrame(DataFrame):
    _metadata = ['attrs']

    @property
    def _constructor(self):
        return MyDataFrame

    def _combine_frame(self, other, *args, **kwargs):
        return super(MyDataFrame, self)._combine_frame(other, *args, **kwargs).__finalize__(self)

dfA = MyDataFrame({'A' : [1,2,3]})
dfA.attrs = {'foo' : 'bar'}

dfB = MyDataFrame({'B' : [6,7,8]})
dfB.attrs = {'fuzzy': 'busy'}

dfC = dfA.append(dfB)
dfC.attrs   #Returns error: 'MyDataFrame' object has no attribute 'attrs'
            #I would like that it would be {'foo': 'bar'}
```
As jreback mentioned: there should be made choices: what to do with the appended atttributes. 
However: I would be really helped when the attributes of only '''dfA''' simply propagate towards '''dfC'''

**Comment by 21stio** [comment] 2017-11-11 19:15
Can't we just put metadata in the column name and change how columns are accessed? E.g. ["id"] would internally translate to {"name": "id"}. 

Don't know the internals of pandas, so sorry if this might be a little naive. To me it just seems that the column name is really consistent across operations

**Comment by yarikoptic** [comment] 2019-08-19 19:26
My use case would be adding a description to "indicator variables"  (just 0/1) which are otherwise look like `var#1`, `var#2` etc, and I do not want to pollute those names with potentially long values they actually stand for.

**Comment by mroeschke** [comment] 2020-04-03 04:48
I think we have `_metadata` https://pandas.pydata.org/pandas-docs/stable/development/extending.html#define-original-properties and `.attrs` defined for this metadata use cases. If these don't sufficiently cover the necessary use cases, new issues can be created about those 2 methods. Closing

**Closed by mroeschke** 2020-04-03 04:48 UTC
Labels: Enhancement, IO Data, metadata
