### ISSUE TITLE
Slow (and weird) empty dataframe creation

### ISSUE THREAD

**Issue by astyonax** [pandas-dev/pandas#28188] opened 2019-08-28 11:31 UTC
I measured the creation of an empty dataframe with 3 similar arguments:

```python
import pandas as pd
cols = np.arange(100)
index = np.arange(1000)

%timeit pd.DataFrame(columns=cols, index=index)
# 100 loops, best of 3: 18.8 ms per loop
%timeit pd.DataFrame({}, columns=cols, index=index)
100 loops, best of 3: 18.7 ms per loop
%timeit pd.DataFrame(np.nan ,columns=cols, index=index)
1000 loops, best of 3: 434 µs per loop

z1 = pd.DataFrame(columns=cols,index=index) # dtype -> object
z2 = pd.DataFrame({},columns=cols,index=index) # dtype -> object
z3 = pd.DataFrame(np.nan,columns=cols,index=index) # dtype -> float
```

If I understand correctly the code in here:
https://github.com/pandas-dev/pandas/blob/171c71611886aab8549a8620c5b0071a129ad685/pandas/core/frame.py#L399

the first 2 constructions are the same: the default value of data is an empty dictionary. 
The output is a dataframe of type object. 

The 3rd, with np.nan as initial value, is about 40 times faster, and the dtype is float, as expected.

So I would change:
1. the default value of data to np.nan. If one creates an empty dataframe with no specific  dtype, then the best pandas can do is to return the cheapest and fastest dataframe that can contain "empty" values. A dataframe of type float filled with np.nan is so a good candidate.

2. the documentation to report the current behavior.

What is your opinion?

**Comment by astyonax** [comment] 2019-08-28 15:32
Ok. I'll come up with something asap

**Comment by machow** [comment] 2019-08-30 18:23
@WillAyd I am pretty sure this is related to the issue with `_try_cast` running to often on Series construction #28145 

For the slow, cast it takes up half the construction time. This is because np.arange produces an int dtype, so _try_cast does expensive checks on whether it can cast it to a datetime (AFAIK it never will, and shouldn't)

Note how much time is spent sanitizing the array

![image](https://user-images.githubusercontent.com/2574498/64043153-9f6bf800-cb31-11e9-9952-ae5bd3f2adaa.png)

Zooming in further, a big chunk of this is `_try_cast`

![image](https://user-images.githubusercontent.com/2574498/64043195-b9a5d600-cb31-11e9-8688-c78e723b5ec5.png)

AFAICT this will have stark performance implications all across the library, whenever an int array is used.

**Comment by astyonax** [comment] 2019-08-31 20:40
It may well be the case that with my changes `_try_cast` is not called anymore. Here follow the snakeviz (whose existence I didn't know before, btw) for this code
```python
%%snakeviz
for j in range(10000):
    pd.DataFrame(columns=cols, index=index)
```

![Screenshot from 2019-08-31 22-35-23](https://user-images.githubusercontent.com/10552313/64068934-eba55e00-cc3f-11e9-953c-4c0dd0b411bf.png)

and zooming in construction.py
![Screenshot from 2019-08-31 22-35-56](https://user-images.githubusercontent.com/10552313/64068945-23140a80-cc40-11e9-8c44-b6ba7671ce44.png)


BTW: I didn't have time to work on the tests yet

**Comment by simonjayhawkins** [comment] 2020-06-05 17:26
closing as duplicate of #25887

**Closed by simonjayhawkins** 2020-06-05 17:26 UTC
Labels: Constructors, Performance
