### ISSUE TITLE
Inconsistency in to_datetime timezone aware transformation

### ISSUE THREAD

**Issue by Grillard** [pandas-dev/pandas#41591] opened 2021-05-20 20:11 UTC
Hello,

I found this weird behaviour when transforming a timezone aware datetime object into a pandas datetime using to_datetime. If I set the timezone before transforming I get an incorrect result. Here is a small code snippet on how I get this:

```
import pandas as pd
import datetime
import pytz

tz=pytz.timezone("US/Eastern")
year=2021
month=1
day=1
hour=0
minute=0

#Add timezone after to_datetime
t1=datetime.datetime(year=year,month=month,day=day,hour=hour,minute=minute)
t1=pd.to_datetime(t1).tz_localize(tz)

#Add timezone before to_datetime
t2=datetime.datetime(year=year,month=month,day=day,hour=hour,minute=minute,tzinfo=tz)
t2=pd.to_datetime(t2)

print(t1)
print(t2)
```
which gives me:
```
t1 = 2021-01-01 00:00:00-05:00
t2 = 2020-12-31 23:56:00-05:00
```

t1 is the intended output, but t2 gives an strange 4 minutes different.  I tried this with different random timezones and dates, and in most of the cases t1!=t2. I did not found a consistent difference for different  timezones and dates.

I am not sure if this is a bug, or if I am missing something obvious. I tried to find if this was a known issue, but could not find anything, hence decided to share this here.

I am using python 3.8.6, pandas 1.1.2 and pytz 2020.1

Thanks!

**Comment by mroeschke** [comment] 2021-05-20 20:25
Please see the warning section in https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#working-with-time-zones and http://pytz.sourceforge.net/#example-usage on how to correctly initialize a pytz timezone to a `datetime.datetime`

```
In [1]: import pandas as pd
   ...: import datetime
   ...: import pytz
   ...:
   ...: tz=pytz.timezone("US/Eastern")
   ...: year=2021
   ...: month=1
   ...: day=1
   ...: hour=0
   ...: minute=0

In [2]: t2=pd.to_datetime(tz.localize(datetime.datetime(year=year,month=month,day=day,hour=hour,minute=minute)))

In [3]: t2
Out[3]: Timestamp('2021-01-01 00:00:00-0500', tz='US/Eastern')
```

Closing as usage behavior question and not a bug in pandas.

**Closed by mroeschke** 2021-05-20 20:25 UTC
