### ISSUE TITLE
PERF: slow multiplication of DataFrame and a scalar

### ISSUE THREAD

**Issue by vfilimonov** [pandas-dev/pandas#30267] opened 2019-12-13 22:22 UTC
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame(np.random.randn(500, 1000))

%timeit x1 = df * 50  # 258 ms ± 14.6 ms per loop
# For comparison:
%timeit x2 = df * df  # 1.57 ms ± 9.16 µs per loop
%timeit x3 = np.multiply(df, 50)  # 878 µs ± 71.7 µs per loop
```
#### Problem description

Multiplication by a scalar takes enormously large time (e.g. in comparison with an element-wise multiplication of two dataframes or `numpy.multiply`).

Same problem holds for division.

Pandas version: 0.25.3

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.3
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.1.post20191125
Cython           : None
pytest           : 5.3.0
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : None
pymysql          : 0.9.3
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : None
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.0.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.12.1
pytables         : None
s3fs             : 0.4.0
scipy            : 1.3.1
sqlalchemy       : 1.3.8
tables           : 3.4.4
xarray           : None
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by vfilimonov** [comment] 2019-12-13 22:23
Some profiling snapshot:

![image](https://user-images.githubusercontent.com/1324881/70836083-65ccad80-1dff-11ea-9625-cc8eb159c71a.png)

**Comment by jreback** [comment] 2019-12-13 23:29
tho sis a duplicate and well known (and soon to be solved issue)

cc @jbrockmendel

**Comment by vfilimonov** [comment] 2019-12-13 23:32
Thanks for the response, @jreback !

Apologies for the duplicate - I did not find its mentions via search.

**Comment by jbrockmendel** [comment] 2019-12-14 02:44
Closing as duplicate of #24813, but rest assured this is a high priority.

**Closed by jbrockmendel** 2019-12-14 02:44 UTC
