### ISSUE TITLE
ENH: Keeping a GroupBy object after filtering

### ISSUE THREAD

**Issue by G-Guillard** [pandas-dev/pandas#42609] opened 2021-07-19 15:29 UTC
As of today, the result of filtering after grouping is a `DataFrame` :

```
type(df.groupby("foobar").filter(lambda x: len(x)>1)) == pandas.core.frame.DataFrame
```

However in many cases it also makes sense to filter **but keep a DataFrameGroupBy object**.

Surprisingly, I didn’t find such a feature request here, although this topic was raised several times on StackOverflow :

https://stackoverflow.com/questions/36047951/how-to-preserve-pandas-groupby-object-after-filter-operation
https://stackoverflow.com/questions/35832475/how-can-i-filter-a-pandas-groupby-object-and-obtain-a-groupby-object-back
https://stackoverflow.com/questions/36389919/chaining-grouping-filtration-and-aggregation

The last link proposes some interesting workarounds, but they are not convenient or simply fail in more complex cases, when the grouping and filtering is performed on multiple columns.  Furthermore, manually re-applying the grouping is neither elegant nor efficient, but most of all it is error-prone in such cases.

Having a specific filter function (or an optional argument to the existing one) to return a filtered `DataFrameGroupBy` object would come very handy.

**Comment by rhshadrach** [comment] 2021-07-20 20:37
> Furthermore, manually re-applying the grouping is neither elegant **nor efficient**, but most of all it is error-prone in such cases.

Bolding mine.

Not sure if you're aware, but a `.groupby(...)` is very lightweight:

```
size = 1000
df = pd.DataFrame({'a': [1] * size, 'b': [2] * size})
%timeit df.groupby('a')
```

gives

> 18.8 µs ± 117 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

whereas changing size to 100_000 gives

> 18.8 µs ± 423 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

I don't think the need to recreate the groupby has an impact on efficiency.

> but most of all it is error-prone in such cases.

Can you elaborate here? Do you have an example in mind where `df.groupby(...).filter(...).groupby(...).op()` or something of the sort does something unexpected?

It sounds to me that this is a request for a pandas method that does "a groupby-filter and does a groupby again". In general, having a method that just runs two pandas methods seems undesirable from an API standpoint to me.

**Comment by G-Guillard** [comment] 2021-07-22 08:17
Well, the comment about efficiency was based on the timings [from here](https://stackoverflow.com/a/36390210/812102).

By error prone I mean user error.  Consider the following :

```
df.groupby(["colA", "colB", "colC"]).filter(…).groupby(["colA", "colB", "colC"]).whatever()
```
Now if I decide to add another column to the groupby, I have to update both sides.  On a very simple example like this one it does not really matter, but in the context of several dataframes with long column names and many operations it can quickly become a mess.

Of course it would be best for the user to set the column names to group by in a separate variable, but the code may have been written by someone else.

> It sounds to me that this is a request for a pandas method that does "a groupby-filter and does a groupby again". In general, having a method that just runs two pandas methods seems undesirable from an API standpoint to me.

I get your point, although in my mind the filter method rather acted like a filter+flatten.  I will try to have a further look at the source code tomorrow to better understand the underlying implications.

**Comment by rhshadrach** [comment] 2021-07-23 01:48
> Well, the comment about efficiency was based on the timings from here.

When I run on 1.3.x

```
np.random.seed(0)
df = pd.DataFrame(np.random.randint(0, 10, (100000, 2)), columns=list('ab'))
%timeit df.groupby('a', as_index=False).filter(lambda group: group.a.count() >= 5).groupby('a').mean()
```

I get

    11.7 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

as opposed to ~35s in the SO link. Is that the correct benchmark? Also, I can shave off 25% by replacing `group['A'].count()` with `len(group)`, although this is slightly different behavior as `count` doesn't count null values (not sure if that's intended).

> in my mind the filter method rather acted like a filter+flatten

Agreed that we could possible get better performance by having a filter act directly on a groupby object. However I think this is equivalent to modifying the DataFrame that the groupby object was constructed on, and I believe the assumption that it is not changing is deeply embedded into the implementation (but would be happy to be proven wrong here).

**Comment by rhshadrach** [comment] 2022-01-30 15:51
I could not reproduce the performance issue, and don't believe the suggested enhancement is actionable. Closing for now, but can reopen if further discussion is desired.

**Closed by rhshadrach** 2022-01-30 15:51 UTC
Labels: Enhancement, Groupby, Performance, Needs Discussion, Apply
