### ISSUE TITLE
TST: add doc-strings for fixtures

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#19731] opened 2018-02-16 18:28 UTC
``pytest --fixtures`` prints these out. so let's add doc-strings, then we can figure out if we have duplicates / consolidate.

**Comment by TomAugspurger** [comment] 2018-02-16 19:23
Dupe of https://github.com/pandas-dev/pandas/issues/19159 :)

**Closed by TomAugspurger** 2018-02-16 19:23 UTC
Labels: Docs, Effort Low, Testing, good first issue
