### ISSUE TITLE
QST: to_csv slow in python 3 compared to python 2

### ISSUE THREAD

**Issue by ben10he** [pandas-dev/pandas#41468] opened 2021-05-14 09:11 UTC
Same as stackoverflow question:
https://stackoverflow.com/questions/48867875/slow-csv-writing-with-python3-compared-to-python2-with-pandas-to-csv

I found that pandas to_csv is much slower in my python 3 venv compared to python 2. I did a test to write a 7MB to c drive 1000 times and measure the average time used. I found that python 2 venv only use half of the time compared to python 3.

Versions:
python 2: 2.7.9
pandas: 0.19.2
python 3: 3.6.8
pandas: 0.25.1

Does this performance difference between python 2 and 3 expected?

[py3_8_profile.txt](https://github.com/pandas-dev/pandas/files/6486534/py3_8_profile.txt)
[py3_6_profile.txt](https://github.com/pandas-dev/pandas/files/6486536/py3_6_profile.txt)
[py2_7_profile.txt](https://github.com/pandas-dev/pandas/files/6486540/py2_7_profile.txt)

**Comment by ben10he** [comment] 2021-05-14 10:07
I tried pandas 1.1.4 with python 3.8.8. It is marginally faster than 0.25.1 in python 3.6.8, but still far slower than python 2.

**Comment by phofl** [comment] 2021-05-14 16:06
Ok, could you provide something reproducible to profile?

**Comment by ben10he** [comment] 2021-05-14 16:31
What I did was to pick a csv file with size about 7MB and then run these lines:

```
import time

import pandas as pd

df = pd.read_csv("path to csv file")

start = time.time()
for i in range(1000):
  df.to_csv("output path", index=False)
print((time.time()-start)/1000)

```
The average time used in python 2 is 0.149818000078, but in python 3 env this number double.

**Comment by phofl** [comment] 2021-05-14 16:41
And what was in this file?

**Comment by ben10he** [comment] 2021-05-14 20:04
It is normal csv file containing string, date and number. Unfortunately, I cannot share it. But if you use any csv file > 1MB, you should be able to reproduce.

**Comment by phofl** [comment] 2021-05-14 20:12
Can you profile? I don't have a python 2 installation

**Comment by ben10he** [comment] 2021-05-15 11:37
Updated the original question with 3 files as output of cProfile.

**Comment by jbrockmendel** [comment] 2021-06-06 19:47
> It is normal csv file containing string, date and number. Unfortunately, I cannot share it. But if you use any csv file > 1MB, you should be able to reproduce.

It is much easier to help you troubleshoot if you provide a copy-pasteable example (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When posting cProfile output please sort by cumulative-time.

**Comment by mroeschke** [comment] 2021-08-20 05:26
Thanks for the report. Since pandas no longer supports Python 2 and if there is truly a difference due to the Python versions, there would be no fix due to lack of Python 2 support. We recommend using the latest version on Python 3 if possible.

If you are able to spot a difference between more recent pandas version on Python 3, that would be a more valid investigation case since it would be a regression in pandas version most likely. Closing for now, but let us know if you also spot this across newer versions of pandas on Python 3

**Closed by mroeschke** 2021-08-20 05:26 UTC
Labels: Performance, IO CSV
