### ISSUE TITLE
pd.concat reset the tz-aware index to UTC

### ISSUE THREAD

**Issue by alessioarena** [pandas-dev/pandas#18422] opened 2017-11-22 03:30 UTC
Hi, 

Having two DataFrames with index being tz-aware Timestamp objects 

```
print(concat_df[0].index.tz, concat_df[1].index.tz)
fxt = pd.concat(concat_df, axis=1)
print(fxt.index.tz)

```
This leads to the following output
```
Australia/Melbourne Australia/Melbourne
UTC
```
I believe this may be in some way related to https://github.com/pandas-dev/pandas/issues/7562

pandas version = 0.21.0

**Comment by jreback** [comment] 2017-11-22 03:41
pls show a copy pastable example

**Comment by sinhrks** [comment] 2017-11-22 03:43
Thanks for the report. Unfortunatelly, I couldn't reproduce the issue using 0.21.0. Can you attach reproducible code and `pd.show_versions()`?

```
import pandas as pd

idx = pd.date_range('2011-01-01', periods=3, freq='H', 
                    tz='Australia/Melbourne')
df = pd.DataFrame({'a': [1, 2, 3]}, index=idx)

res = pd.concat([df, df], axis=1)
res.index.tz
# <DstTzInfo 'Australia/Melbourne' LMT+9:40:00 STD>
```

**Comment by alessioarena** [comment] 2017-11-23 01:16
Hi there,

Unfortunately those files are quite large, and I cannot upload them.
I tried to make some synthetic data and also could not reproduce it.

However I have some additional information about this issue:

The first dataset (df_concat[0]) has a Timestamp object converted from UTC as following:
```
dft['local_time'] = pd.to_datetime(dft.timestamp_utc, utc=True, format="%d/%m/%Y %H:%M:%S")
dft.index = dft.index.tz_convert('Australia/Melbourne')
```
This lead to
`<DstTzInfo 'Australia/Melbourne' LMT+9:40:00 STD>`


The second dataset (df_concat[1]) has the Timestamp object being localized as following
`df.index = df.index.tz_localize('Australia/Melbourne', ambiguous=np.ones(len(df.index), dtype=bool))`
This lead to 
`<DstTzInfo 'Australia/Melbourne' AEDT+11:00:00 DST>`


As you can see the resulting timezones are both Australia/Melbourne, but they are expressed differently.
I believe that this is the cause of the problem describe, and I also suspect that the datasets are misaligned during this operation. I will do more testing on this and update you.

**Comment by jreback** [comment] 2017-11-27 12:09
closing as no repro.

If you have a copy-pastable example pls open a new issue.

**Closed by jreback** 2017-11-27 12:09 UTC
Labels: Can't Repro, Reshaping, Timezones
