### ISSUE TITLE
BUG: Unable to resample period range with dates above 2262-04-11 

### ISSUE THREAD

**Issue by jmcinto** [pandas-dev/pandas#44326] opened 2021-11-05 16:04 UTC
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
import pandas as pd
from datetime import datetime
print(pd.__version__)
rng = pd.period_range(datetime(2000, 1, 1, 0, 0), datetime(2300, 1, 1, 0, 0), freq="1D")
df = pd.DataFrame(index = rng, data = [i+1 for i in range(0,len(rng))])
resample_df = df.resample("6H").interpolate()
print(resample_df.head(5))
```

### Issue Description

We are working with datasets that extend out past the maximum timestamp date of 2262-04-11, so we generally use period ranges rather than datetime ranges.  However, starting with release 1.1.0, the resample functionality no longer works with period ranges that extend past 2262-04-11.  The error that occurs in these later releases is pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 2300-01-01 22:59:59.

### Expected Behavior

In releases prior to 1.1.0, period ranges that extend past 2262-04-11 are resampled successfully without an out of bounds datetime error.

### Installed Versions

<details>

1.1.1

</details>

**Comment by mroeschke** [comment] 2021-11-14 04:09
Thanks for the report. The core issue (Period out of bound timestamps) is the same as https://github.com/pandas-dev/pandas/issues/28104 so closing as a duplicate of that issue

**Closed by mroeschke** 2021-11-14 04:09 UTC
Labels: Bug, Period, Resample, Needs Triage
