### ISSUE TITLE
.groupby by should indicate it aligns the passed in Series

### ISSUE THREAD

**Issue by kernc** [pandas-dev/pandas#15338] opened 2017-02-07 23:41 UTC
#### Code Sample, a copy-pastable example if possible

```python
>>> series = pd.Series([1, 2, 3], index=range(3))

>>> key = pd.Series([0, 0, 1], index=range(3, 6))  # Note: disjunct index

>>> series.groupby(key).sum()
Series([], dtype: int64)

>>> series.groupby(key.values).sum()
0    3
1    3
dtype: int64
```
#### Problem description

The current behavior is a bug because the [.groupby() documentation](https://github.com/pandas-dev/pandas/blob/v0.19.2/pandas/core/generic.py#L3948-L3949) says about `by` parameter:
> If a dict or Series is passed, the Series or dict **VALUES** will be used to determine the groups

Above example shows this not being the case.

#### Expected Output

With above setup:
```py
>>> series.groupby(key).sum()
0    3
1    3
dtype: int64
```

#### Output of ``pd.show_versions()``

<details>
pandas: 0.19.0+416.ge1390cd
</details>

**Comment by kernc** [comment] 2017-02-07 23:44
Might be related to https://github.com/pandas-dev/pandas/issues/15244.

I followed to problem to [reindexing of the grouper Series](https://github.com/pandas-dev/pandas/blob/ba057443d1b69bb3735a4b18a18e4e4897231867/pandas/core/groupby.py#L2580) which results in the new grouper containing all NaNs.

**Comment by jreback** [comment] 2017-02-08 00:35
this is correct, if you pass a Series if will first ``.align`` it. So that's why you get an empty result set.
This is not a bug, though I suppose could be better documented.

This was brought up here: https://github.com/pandas-dev/pandas/issues/15244

**Comment by jreback** [comment] 2017-03-23 13:29
closing as dupe of #15244

**Closed by jreback** 2017-03-23 13:29 UTC
Labels: Difficulty Novice, Docs, Duplicate, Effort Low, Groupby
