### ISSUE TITLE
index=False not working in to_csv on windows

### ISSUE THREAD

**Issue by gminorcoles** [pandas-dev/pandas#26576] opened 2019-05-30 15:41 UTC
def fix_timestamps(file_path):     df = pd.read_csv(file_path, parse_dates=['dateTime'])     df.to_csv(file_path, date_format='%Y-%m-%d %H:%M:%S',header=True,index=False)

output:

Unnamed: 0,dateTime,ID,open,high,low,close,vol,SplitAdjustment,DivAdjustment,DividendPerShare,SplitFactor
0,2002-05-30 00:00:00,500045,13.5,14.11,12.99,13.03,1663700.0,1.0,1.0,0.0,1.0

I got this version from conda today, python 3, fresh install.
 
this is a bummer I have several thousand files to fix.

**Comment by WillAyd** [comment] 2019-05-30 15:52
Tough to say because this code sample isn't reproducible but I'm guessing that your original write of the file included in the index, so you probably just want to add `index_col=0` to your read_csv call.

Closing as not reproducible otherwise but if the above suggestion doesn't fix and you can provide a reproducible example feel free to reopen

**Closed by WillAyd** 2019-05-30 15:52 UTC

**Comment by gminorcoles** [comment] 2019-05-30 17:06
reading a csv file with no index, when it writes the file there is an index even though I said index=False

it is really simple

**Comment by WillAyd** [comment] 2019-05-30 17:20
Did you try the suggestion above? If it didn’t work for you do you have a reproducible code sample?
