### ISSUE TITLE
Unexpected TypeError with groupby

### ISSUE THREAD

**Issue by fran6w** [pandas-dev/pandas#31605] opened 2020-02-03 09:48 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import numpy as np
import pandas as pd

def fct(group):
    return group[1].values.flatten()

df = pd.DataFrame([('A', 1), ('A', 2), ('A', 3), ('B', 4), ('B', 5), ('C', np.nan),])
df.groupby(0).apply(fct)
```
#### Problem description

This code works with pandas 0.25.1 BUT NOT with pandas 1.0.0.
With pandas 1.0.0, the output is:
TypeError: copy() takes no keyword arguments

#### Expected Output
With pandas 0.25.1, the output is:
Series:
0
A    [1.0, 2.0, 3.0]
B         [4.0, 5.0]
C              [nan]

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 7
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : fr_FR.cp1252

pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.11.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by fjetter** [comment] 2020-02-03 10:21
I believe this is already fixed by #31456

**Comment by jorisvandenbossche** [comment] 2020-02-03 10:22
Indeed, I can confirm this is working again. Fix will be in 1.0.1 normally released tomorrow.

**Comment by jorisvandenbossche** [comment] 2020-02-03 10:22
But thanks for the report!

**Comment by jorisvandenbossche** [comment] 2020-02-03 10:24
Actually, will keep this open as an issue to add an additional test case (it can be added next to the ones added in https://github.com/pandas-dev/pandas/pull/31456/)

**Comment by TomAugspurger** [comment] 2020-02-03 12:39
Moving to 1.0.1, since the extra test case needn't hold up the release.

**Closed** 2020-02-05 01:26 UTC
Labels: Duplicate, Needs Tests, good first issue
