### ISSUE TITLE
BUG:  pandas.cut  doesnt respect to `precision=3` when  `include_lowest=True`

### ISSUE THREAD

**Issue by eromoe** [pandas-dev/pandas#46797] opened 2022-04-18 03:20 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
a  = pd.Series(np.linspace(-0.9999999, 10, 200))
pd.cut(a, 10, retbins=True, include_lowest=True, precision=3)
```

### Issue Description

![image](https://user-images.githubusercontent.com/3938751/163749171-8f834741-78da-4aba-80a3-3ac4ccc57953.png)

### Expected Behavior

lowest value should be precision=3

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.2
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 22.0.4
setuptools       : 44.0.0
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : 0.4.1
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
brotli           : 
fastparquet      : None
fsspec           : 2021.07.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.3.4
numba            : 0.53.1
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2021.07.0
scipy            : 1.6.2
snappy           : None
sqlalchemy       : 1.4.7
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment] 2022-05-29 20:37
Thanks @eromoe for the report.

The bug appears to be in the rounding and adjust logic in `_format_labels` in `pandas/core/reshape/tile.py`

further investigations and PRs welcome.

**Comment by simonjayhawkins** [comment] 2022-05-29 21:10
closing as duplicate of #33912

**Closed by simonjayhawkins** 2022-05-29 21:10 UTC
Labels: Bug, Interval, cut
