### ISSUE TITLE
BUG:np.nan not recognized by isna() or isnull() to be NA

### ISSUE THREAD

**Issue by gitgithan** [pandas-dev/pandas#41568] opened 2021-05-19 13:09 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

pd.options.mode.use_inf_as_na = False
pd.Series([np.nan]).isnull()
pd.Series([np.nan]).isna()
pd.options.mode.use_inf_as_na = True
pd.Series([np.nan]).isnull()
pd.Series([np.nan]).isna()
```
Current Output:
```
0    False
dtype: bool
Out[205]:
0    False
dtype: bool
Out[205]:
0    True
dtype: bool
Out[205]:
0    True
dtype: bool
```
#### Problem description

I'm not able to identify NA values created by np.nan or generated by pandas through it's data manipulation methods using df.isna or df.isnull. I had to change `pd.options.mode.use_inf_as_na` from default False to True to recognize np.nan. 

On my previous experiences with earlier versions of pandas the 2 methods can identify np.nan as NA. Now they mismatch what the docs are saying (https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html), which is by default with `pd.options.mode.use_inf_as_na = False`, np.nan should be recognized as NA, and setting this option to True only adds -INF and INF as NA.

What does the "old way" and "new way" in the statement from docs below mean anyway?

**True means treat None, NaN, -INF, INF as NA (old way), False means None and NaN are null, but INF, -INF are not NA (new way).**

#### Expected Output
```
0    True
dtype: bool
Out[205]:
0    True
dtype: bool
Out[205]:
0    True
dtype: bool
Out[205]:
0    True
dtype: bool
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.4.0
Version          : Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.18.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 56.0.0
Cython           : None
pytest           : 6.2.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.23.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.17.0
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by mzeitlin11** [comment] 2021-05-19 15:10
Thanks for your report @gitgithan, I think you have the right understanding here and agree with your expected output. I can't reproduce this issue - I see your expected output  on both master and 1.2.4.

**Comment by gitgithan** [comment] 2021-05-20 14:37
I compared the pd.show_versions() from another computer which worked, it was numpy 1.19.5. This one that created this issue is 1.18.x (uninstalled before i remember what is x). So i upgraded numpy to 1.19.5 and it's fine now!

I would still like to understand what could be happening in case similar issues happen in future. 
How does pandas depend on numpy in NA value checking?

**Comment by jbrockmendel** [comment] 2021-06-24 02:16
> How does pandas depend on numpy in NA value checking?

in pandas._libs.missing.pyx we use either isnaobj or isnaobj_old depending on the use_inf_as_na option.  They should both recognize np.nan as an NA value.

Closing as not reproducible, can re-open if the problem pops back up.

**Closed by jbrockmendel** 2021-06-24 02:16 UTC
Labels: Missing-data
