### ISSUE TITLE
ENH: Conversion of objects with __array__ attribute to Series

### ISSUE THREAD

**Issue by 502E532E** [pandas-dev/pandas#48816] opened 2022-09-27 18:48 UTC
### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

As described in #47800, the conversion of objects which specify the `__array__` attribute results in an one-entry `Series` of `object` dtype. Example code (as provided in the mentioned issue):
```python
import numpy as np
import pandas as pd

class ArrayLike:
    def __array__(self, dtype=None):
        return np.asarray([0, 1])

a = ArrayLike()
print(pd.Series(a))

#  Output
#  0    <__main__.ArrayLike object at 0x7f8848211330>
#  dtype: object
```
While the bug report was closed as expected behaviour, I would appreciate this to change and give a more useful result.

### Feature Description

In the [`Series`](https://github.com/pandas-dev/pandas/blob/0e93cafb394131c64c4c4cc95c8c43967f09a0c2/pandas/core/series.py#L351-L493) constructor we already have several checks for different kinds of input data. I would suggest to add one more check for the `__array__`-attribute.

This could be put at the end of the `elif`-chain, so it does not interfere with any of the other checks, as it applies to some other objects (e.g. `Series` itself, actual `ndarrays` and some more) which should be filtered out before.

[My attempt](https://github.com/502E532E/pandas/blob/8ce1f74c878bac833d0bea392a24cd6e945bddcd/pandas/core/series.py#L462-L471) to implement this:
```python
[other checks]
elif hasattr(data, "__array__"):
    data = np.asanyarray(data)
    # Perform same checks as above for np.ndarray
    if len(data.dtype):
        # GH#13296 we are dealing with a compound dtype, which
        #  should be treated as 2D
        raise ValueError(
            "Cannot construct a Series from an ndarray with "
            "compound dtype.  Use DataFrame instead."
        )
```

This works fine in my tests. It introduces some code duplication, but the only option I see to avoid this is to move the checks into a separate function, since the order of the `elif` statements matters.

### Alternative Solutions

One option to circumvent this problem currently is to implement an `__iter__` function ([Related stackoverflow answer](https://stackoverflow.com/a/73050962/16563251)). But this might not always be an option and could be significantly less performant compared to direct conversion to an array.

It might also be possible to do the conversion later, but I am not sure where would be an appropriate location and also believe my proposed method works quite well.

### Additional Context

Bug report mentioning this problem: #47800.
[Related stackoverflow question](https://stackoverflow.com/questions/73050883/create-pandas-series-from-array-like/73050962#73050962).

**Comment by rhshadrach** [comment] 2022-09-28 22:42
Thanks for the request - just wanted to note you can comment on closed issues and ask they be turned into enhancement requests as well. 

cc @mroeschke

**Comment by mroeschke** [comment] 2022-09-28 23:41
I think for similar reasoning as described in https://github.com/pandas-dev/pandas/issues/47800#issuecomment-1192935096 (this is a numpy semantic), I would be -1 to have `Series` automatically convert this. One could just call `pd.Series(np.asarray(Arraylike()))`

**Comment by jbrockmendel** [comment] 2022-11-23 21:59
1) I agree with @mroeschke
2) I _think_ Series will convert if you add a `__iter__` method
3) we _do_ convert `__array__`-having objects in the Index constructor even without a `__iter__` method, so it'd be nice to be consistent.

**Comment by mroeschke** [comment] 2024-07-16 22:14
Closing as essentially a duplicate of https://github.com/pandas-dev/pandas/issues/47800

**Closed by mroeschke** 2024-07-16 22:14 UTC
Labels: Enhancement, Series, Constructors, Needs Triage
