### ISSUE TITLE
Pandas dataframe + groupby = failed zooming for x-axis ticks

### ISSUE THREAD

**Issue by mat2py** [pandas-dev/pandas#15912] opened 2017-04-05 21:54 UTC
This was posted onto stackoverflow but it seems more like a bug than anything:

http://stackoverflow.com/questions/43242246/pandas-dataframe-groupby-failed-zooming-for-x-axis-ticks

**Comment by jorisvandenbossche** [comment] 2017-04-06 07:34
Smaller reproducible example:

```
In [43]: df = pd.DataFrame(np.random.randn(4, 2), columns=['A', 'B'], index=pd.MultiIndex.from_product([[2012, 2013], [1,2]]))

In [44]: df
Out[44]: 
               A         B
2012 1  0.144222  0.895911
     2  0.885869  0.075482
2013 1 -0.312316  0.705149
     2 -0.974501  1.443551

In [45]: df.plot()
Out[45]: <matplotlib.axes._subplots.AxesSubplot at 0x7f3e6a262ef0>
```

The xtick label formatter cannot really handle a MultiIndex, as once you zoom in, the labels are put at the wrong place.

But the same is true when eg having a string index. So just a non-numerical / non-datetime index has this issue.

**Comment by jorisvandenbossche** [comment] 2017-04-06 07:35
This is a dupe of https://github.com/pandas-dev/pandas/issues/7612

**Closed by jorisvandenbossche** 2017-04-06 07:35 UTC
