### ISSUE TITLE
Inconsistent behaviour when dividing by zero

### ISSUE THREAD

**Issue by alexeygrigorev** [pandas-dev/pandas#17190] opened 2017-08-07 09:54 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np

def some_func(row):
    try:
        print('type of clicks:', type(row.clicks))
        return row.impressions / row.clicks
    except:
        return np.nan

df = [('a', 1, 1), ('b', 0, 1)]
df = pd.DataFrame(df, columns=['src', 'clicks', 'impressions'])
res = df.apply(lambda row: some_func(row), axis=1)
print(res)

df = [(1, 1), (0, 1)]
df = pd.DataFrame(df, columns=['clicks', 'impressions'])
res = df.apply(lambda row: some_func(row), axis=1)
print(res)
```

#### Problem description

The behavior when dividing by zero is inconsistent in these two examples above. The difference is that in the first case there is a column with strings, while in the second example there are only numerical columns. 
Additionally, in the first case, `type` returns `int`, and in the second - `numpy.int64`
When the type is python `int`, an exception is raised, but numpy only issues a warning and returns `inf`. 

#### Expected Output

These two examples should produce the same output - either `inf` or `NaN`

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

In [2]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.2.0-27-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.3.1
numexpr: 2.6.2
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None

</details>

**Comment by jreback** [comment] 2017-08-07 10:42
``.apply`` does quite a lot of inference, some of this depends on whether its a mixed type (your first example) or not (your 2nd). You are welcome to have a look. Not sure why you aren't using the canonical (which is also vectorized).

```
In [48]: df.impressions/df.clicks
Out[48]: 
0    1.000000
1         inf
dtype: float64
```

**Comment by jorisvandenbossche** [comment] 2017-08-07 10:44
Simpler reproducible example:

```
In [27]: pd.Series([1, 2]) / 0
Out[27]: 
0    inf
1    inf
dtype: float64

In [30]: pd.Series([1, 2], dtype=object) / 0
...
ZeroDivisionError: division by zero
```

This is due to underlying behaviour of numpy (returning inf) vs standard python (raising an error). 
The numpy behaviour can be changed with a setting (https://docs.scipy.org/doc/numpy/reference/generated/numpy.seterr.html)

In this case specifically, the reason you get this difference between the two cases is because `apply` converts the rows to a series, which needs a single dtype, so in the first it become object due to the string, but in the second case it keeps the int64 numpy dtype.

I agree this can be surprising, but given my explanation above, I am not sure we can/should fix this in pandas.

Workaround can also be to first select the needed columns when doing the apply (`df[['clicks', 'impressions']].apply(..)`

And of course in this case it is even much better to just do `df['impressions'] / df['clicks']` (but your example was maybe simplified?).

**Comment by alexeygrigorev** [comment] 2017-08-07 11:46
Yes, of course the example was simplified - it was taken from some existing codebase and I had a lot of fun trying to understand what's going on there.

Thanks for explanation!

**Comment by mroeschke** [comment] 2021-06-12 04:12
As explained, appears we're hesitant to change any behavior here, therefore closing

**Closed by mroeschke** 2021-06-12 04:12 UTC
Labels: Apply, Closing Candidate, Dtypes, Numeric
