### ISSUE TITLE
Plot method ignores upper and lower error bar arguments

### ISSUE THREAD

**Issue by theandygross** [pandas-dev/pandas#11389] opened 2015-10-20 22:35 UTC
This seems to be specific to Pandas as opposed to matplotlib.  Worked as desired as of a few months ago when I last updated from master.

This is the desired behavior in matplotlib:

``` python
plt.barh([0,1], [.3, .5], xerr=[[.1,.2], [.3,.4]],
     color = ['red','green'],
     ecolor='black')
```

![image](https://cloud.githubusercontent.com/assets/1308430/3450982/6507afc8-0189-11e4-9ea6-2cb3b417a9c0.png)

In the Pandas call, it seems to ignore the second error bar argument, both the upper and lower bounds of the error bar are the same:

``` python
s = pd.Series([.3,.5])
s.plot(kind='barh', xerr=[[.1,.2], [.3,.4]],
       color = ['red','green'],
       ecolor='black')
```

![image](https://cloud.githubusercontent.com/assets/1308430/3450991/928769fc-0189-11e4-9b16-670a6c98ce66.png)

**Comment by diazona** [comment] 2016-08-23 15:27
This looks like a duplicate of #9536, which has been fixed in an unmerged commit.

**Comment by alexbeaulieu** [comment] 2018-10-23 01:00
> 
> 
> This looks like a duplicate of #9536, which has been fixed in an unmerged commit.

I agree! How should we request to pull this into the main repository? I also need this feature.

**Comment by mroeschke** [comment] 2021-04-20 05:41
It appears this issue might have been solved due to https://github.com/pandas-dev/pandas/pull/34514.

Going to close, but happy to reopen this issue if this issue still persists

**Closed by mroeschke** 2021-04-20 05:41 UTC
Labels: Visualization
