### ISSUE TITLE
Accessor behavior variances with multiindex

### ISSUE THREAD

**Issue by stuz5000** [pandas-dev/pandas#19916] opened 2018-02-26 19:53 UTC
#### Code Sample, a copy-pastable example if possible

```python
def gen():
    yield '1','2',1,2
    yield '1','2',1,2
    yield '1','3',3,2
    yield '2','4',1,2

ser = pd.DataFrame(gen(), columns=["a", "b", "c", "d",]).set_index(["a", "b"])["c"]
print ser

print ser.loc[('1','3')]
print ser.at[('1','3')]  # TypeError: _get_value() got multiple values for keyword argument 'takeable'
```
#### Problem description

The ```.at``` accessor should return the indexed value ```3```.

There doesn't seem any way reliably look up a single scalar in a multiindex. If this is not supported, a better error would be appreciated.

#### Expected Output

```3```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-24-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 9.0.1
setuptools: 36.0.1
Cython: 0.27.3
numpy: 1.14.0
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: 0.2.1
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: None
tables: 3.1.1
numexpr: 2.6.2
feather: None
matplotlib: 2.0.2
openpyxl: 1.7.0
xlrd: 0.9.2
xlwt: 0.7.5
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by stuz5000** [comment] 2018-02-26 19:56
Seems related to: https://github.com/pandas-dev/pandas/issues/9259

**Comment by stuz5000** [comment] 2018-02-26 22:08
An expanded example with even more weirdness.

It seems that, if want to assign a new row, or lookup an existing row in a series or dataframe, I need to choose different accessors depending on whether the multindex label is defined for all indexes.

```
def gen():
    yield 's',None,'sval'

ser = pd.DataFrame(gen(), columns=["a", "b", "c", ]).set_index(["a", "b"])["c"]
print ser


#ser[('s1',)] = "z" # AttributeError: 'float' object has no attribute 'axes'
ser.at[('s2',)] = "z" # success
#ser.loc[('s3',)] = "z" # AttributeError: 'float' object has no attribute 'axes'

ser[('s4','x')] = "z" # success
#ser.at[('s5','x')] = "z" # ValueError: Not enough indexers for scalar access (setting)!
ser.loc[('s6','x')] = "z" # success


print ser

ser.loc[('s6','x')]  # Success
#ser.at[('s6','x')]  # _get_value() got multiple values for keyword argument 'takeable'
ser[('s6','x')]      # Success


ser.loc[('s2',)]  # Success
#ser.at[('s2',)]  # AttributeError: 'numpy.ndarray' object has no attribute '_values'
ser[('s2',)]      # Success
```

**Comment by jreback** [comment] 2018-02-27 01:04
this is a duplicate of #9259 

``.iat/.at`` are not too multi-index aware currently.

**Closed by jreback** 2018-02-27 01:04 UTC

**Comment by stuz5000** [comment] 2018-02-27 15:00
I guess if you leave it open, someone could work on it. Unless, there’s a
good reason to want this feature
