### ISSUE TITLE
HDF5, to_hdf, read_hdf doesn't support diacritics in filename and path

### ISSUE THREAD

**Issue by Petr886** [pandas-dev/pandas#20798] opened 2018-04-23 16:21 UTC
#### Code Sample, a copy-pastable example if possible

```python
with with pd.HDFStore(r"\\share\fs\ostatní\myproject\test.h5") as store:
    store.put("myproject", df)

df.to_hdf(r"\\share\fs\ostatní\myproject\test.h5", "df")

pd.read_hdf(r"\\share\fs\ostatní\myproject\test.h5")
```
#### Problem description

I tried the above methods to save or open the hdf file to network path with no success. When I try to save it on local drive (C), it works.

I haven't found any answer when searching web so I came here. Hopefully someone will be able to guide me to a solution or a fix.

I tried to create the file locally and copy it and then save or open it, same error.

Error:
<details>

```pytb
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\pandas\io\pytables.py", line 580, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\tables\file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\tables\file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables\hdf5extension.pyx", line 489, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace
  File "C:\ci\hdf5_1510862531115\work\src\H5F.c", line 586, in H5Fopen
    unable to open file
  File "C:\ci\hdf5_1510862531115\work\src\H5Fint.c", line 1236, in H5F_open
    unable to open file: time = Mon Apr 23 18:07:02 2018
, name = '\\share\fs\ostatní\myproject\test.h5', tent_flags = 0
  File "C:\ci\hdf5_1510862531115\work\src\H5FD.c", line 809, in H5FD_open
    open failed
  File "C:\ci\hdf5_1510862531115\work\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = '\\share\fs\ostatní\myproject\test.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
End of HDF5 error back trace
Unable to open/create file '\\share\fs\ostatní\myproject\test.h5'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\Python\lib\site-packages\pandas\io\pytables.py", line 349, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\pandas\io\pytables.py", line 467, in __init__
    self.open(mode=mode, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\pandas\io\pytables.py", line 612, in open
    raise IOError(str(e))
OSError: HDF5 error back trace
  File "C:\ci\hdf5_1510862531115\work\src\H5F.c", line 586, in H5Fopen
    unable to open file
  File "C:\ci\hdf5_1510862531115\work\src\H5Fint.c", line 1236, in H5F_open
    unable to open file: time = Mon Apr 23 18:07:02 2018
, name = '\\share\fs\ostatní\myproject\test.h5', tent_flags = 0
  File "C:\ci\hdf5_1510862531115\work\src\H5FD.c", line 809, in H5FD_open
    open failed
  File "C:\ci\hdf5_1510862531115\work\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = '\\share\fs\ostatní\myproject\test.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
End of HDF5 error back trace
Unable to open/create file '\\share\fs\ostatní\myproject\test.h5'
```

</details>

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None
pandas: 0.22.0
pytest: None
pip: 10.0.1
setuptools: 38.2.1
Cython: None
numpy: 1.14.0
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: 3.4.3
numexpr: 2.6.4
feather: None
matplotlib: None
openpyxl: 2.5.0
xlrd: 1.0.0
xlwt: None
xlsxwriter: 1.0.2
lxml: 3.7.3
bs4: 4.6.0
html5lib: None
sqlalchemy: 1.1.10
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by Petr886** [comment] 2018-04-23 16:25
p.s. pd.to_pickle works fine with same network path.

**Comment by TomAugspurger** [comment] 2018-04-23 18:09
Does your error section contain multiple tracebacks? Can you indicate which one goes with which operation?

It looks like the bottom frame of the traceback is in the HDF5 C library. Can you try to reproduce with just pytables, and not pandas?

**Comment by Petr886** [comment] 2018-04-24 07:56
The error stack is from one call. 
Yesterday, by accident, I put here wrong stack - with wrong paths. I  edited today and then I got an idea - and tested it right after:

Issue is not with network path, but with diacritics [í ý á ž...]:
`df.to_hdf(r"d:\temporary indement files\třešť\test.h5", "df")` doesn't work
`df.to_hdf(r"d:\temporary indement files\test.h5", "df")` works

Then I tried searching for it, found:
https://support.hdfgroup.org/HDF5/doc/Advanced/UsingUnicode/index.html

> Since file access is a system issue, filenames do not fall within the scope of HDF5’s UTF-8 capabilities; filenames are encoded at the system level.
> Linux and Mac OS systems normally handle UTF-8 encoded filenames correctly while **Windows systems generally do not**.

So I guess it isn't an issue in pandas. Though maybe pandas could encode the string on input somehow? Or add a parameter..?

**Comment by TomAugspurger** [comment] 2018-04-24 11:49
My recommendation would be to

1. make a reproducible example using just pytables.
2. If pytables can read and write to the file, but pandas can't, we'll fix the issue in pandas.

**Comment by Petr886** [comment] 2018-04-24 13:09
To me seems like same error. Again I tried opening existing, in path with and without diacritics, writing new one.

`h5file = open_file(r"d:\temporary indement files\ostatní\test.h5")`

<details>
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\Python\lib\site-packages\tables\file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\tables\file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables\hdf5extension.pyx", line 489, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace
  File "C:\ci\hdf5_1510862531115\work\src\H5F.c", line 586, in H5Fopen
    unable to open file
  File "C:\ci\hdf5_1510862531115\work\src\H5Fint.c", line 1236, in H5F_open
    unable to open file: time = Tue Apr 24 15:07:50 2018
, name = 'd:\temporary indement files\ostatní\test.h5', tent_flags = 0
  File "C:\ci\hdf5_1510862531115\work\src\H5FD.c", line 809, in H5FD_open
    open failed
  File "C:\ci\hdf5_1510862531115\work\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = 'd:\temporary indement files\ostatní\test.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
End of HDF5 error back trace
Unable to open/create file 'd:\temporary indement files\ostatní\test.h5'
</details>

**Comment by TomAugspurger** [comment] 2018-04-24 13:30
OK, it sounds like this is going to have to be fixed upstream (presumably HDF5). Closing for now, but we can re-open and add tests once those libraries support it.

**Closed by TomAugspurger** 2018-04-24 13:30 UTC
Labels: IO HDF5, Needs Info
