### ISSUE TITLE
BUG: rounding datetime in series is broken

### ISSUE THREAD

**Issue by Andre-Medina** [pandas-dev/pandas#59131] opened 2024-06-28 02:31 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
pd.Series([pd.to_datetime("2022-01-09T12:00:01")]).round("30min") == pd.Series([pd.to_datetime("2022-01-09T12:00:01").round("30min")])
```

### Issue Description

Repeat of issue of #57002

### Expected Behavior

example should return true

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.10.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.153.1-microsoft-standard-WSL2
Version               : #1 SMP Fri Mar 29 23:14:13 UTC 2024
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0
setuptools            : 69.1.0
pip                   : 24.0
Cython                : None
pytest                : 8.1.1
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None

</details>

**Comment by MarcoGorelli** [comment] 2024-06-28 08:32
dupe of https://github.com/pandas-dev/pandas/issues/57002, please don't repost

**Closed** 2024-06-28 08:31 UTC
Labels: Bug, Needs Triage
