### ISSUE TITLE
BUG: AttributeError: 'FixedTimezone' object has no attribute 'zone'

### ISSUE THREAD

**Issue by danhje** [pandas-dev/pandas#47056] opened 2022-05-18 16:33 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
from datetime import datetime, timezone

now = datetime.now(timezone.utc)
pd.DataFrame({"dates": [now, now]}).to_json(orient="table")
```

### Issue Description

An AttributeError is rasied.

### Expected Behavior

JSON returned.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.72-microsoft-standard-WSL2
Version          : #1 SMP Wed Oct 28 23:40:43 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : nb_NO.UTF-8
LANG             : nb_NO.UTF-8
LOCALE           : nb_NO.UTF-8
pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.3.0
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.3.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment] 2022-05-18 17:00
Thanks @danhje for the report. closing as duplicate of #39537

**Closed by simonjayhawkins** 2022-05-18 17:00 UTC
Labels: Bug, Needs Triage
