### ISSUE TITLE
BUG: xs not working with slice

### ISSUE THREAD

**Issue by wiso** [pandas-dev/pandas#35301] opened 2020-07-15 23:09 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

#### Code Sample, a copy-pastable example

```python
data = """
C1  C2 V
A1  0  10
A1  1  20
A2  0  2
A2  1  3
B1  0  2
B2  1  3
"""

import pandas as pd
from io import StringIO
df = pd.read_csv(StringIO(data), sep=' +').set_index(['C1', 'C2'])

df.xs(pd.IndexSlice['A1', :])
```

#### Problem description

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/***/lib/python3.7/site-packages/pandas/core/generic.py", line 3535, in xs
    loc, new_index = self.index.get_loc_level(key, drop_level=drop_level)
  File "/home/***/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 2835, in get_loc_level
    raise TypeError(key)
TypeError: ('A1', slice(None, None, None))

```

also similar code produce the same problem (`df.xs(('A1', slice(None)))`). Strangely this works:
```python
df = pd.DataFrame({'a': [1, 2, 3, 1], 'b': ['a', 'b', 'c', 'd'], 'v': [2, 3, 4, 5]}).set_index(['a', 'b'])
df.xs(pd.IndexSlice[1, :])
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.7.7-100.fc31.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : it_IT.UTF-8
LOCALE           : it_IT.UTF-8

pandas           : 1.0.5
numpy            : 1.19.0
pytz             : 2019.2
dateutil         : 2.7.5
pip              : 20.1.1
setuptools       : 41.6.0
Cython           : 0.29.15
pytest           : 4.0.0
hypothesis       : None
sphinx           : 3.1.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.16.1
pandas_datareader: 0.8.0
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.0
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 4.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.5.1
sqlalchemy       : None
tables           : 3.5.2
tabulate         : 0.8.5
xarray           : 0.12.1
xlrd             : 1.2.0
xlwt             : 1.1.2
xlsxwriter       : None
numba            : 0.48.0

</details>

**Comment by arw2019** [comment] 2020-07-16 08:45
+1 that this should work. 

I've checked that this is a problem on the 1.1 master
<details><summary><b>Output of pd.versions()</b></summary>
INSTALLED VERSIONS
------------------
commit           : b59831e97091d131528513444a6afcddc94a24cb
python           : 3.8.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-40-generic
Version          : #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.0.dev0+2129.gb59831e97
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.1.0.post20200704
Cython           : 0.29.21
pytest           : 5.4.3
hypothesis       : 5.19.0
sphinx           : 3.1.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fsspec           : 0.7.4
fastparquet      : 0.4.0
gcsfs            : 0.6.2
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : 0.17.1
pytables         : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : 0.15.1
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.50.1

</details>

I think the fix will involve changing
https://github.com/pandas-dev/pandas/blob/b687cd4d9e520666a956a60849568a98dd00c672/pandas/core/generic.py#L3415-L3574
or possibly some of the methods that chunk refers to. Happy to do a PR on this unless @wiso you'd like to?

**Comment by wiso** [comment] 2020-07-16 08:49
@arw2019  thanks for checking. I am just a user, will take ages to understand where to put my hands inside the code.

**Comment by arw2019** [comment] 2020-07-16 16:01
ok! In that case I'll take it

**Comment by zky001** [comment] 2020-07-17 01:07
> ok! In that case I'll take it

hi，could I fix this bug，I have fix this In my own computer！

**Comment by zky001** [comment] 2020-07-17 01:07
> ok! In that case I'll take it

hi，could I fix this bug？I have fix this issue In my own computer！

**Comment by arw2019** [comment] 2020-07-17 02:20
> hi，could I fix this bug？I have fix this issue In my own computer！

Yeah go for it

**Comment by jbrockmendel** [comment] 2020-07-17 20:27
xs is intended for scalar lookups

**Comment by arw2019** [comment] 2020-07-19 03:54
@jbrockmendel ahh thanks! In fairness that *is* stated in the [DataFrame.xs doc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.xs.html) 

@wiso Do you think it's worth adding a clarification there? If yes I'll do a PR for that 

Barring that we can probably close this

**Comment by simonjayhawkins** [comment] 2020-07-19 13:18
maybe a better error message; something like `TypeError: expected label or tuple of label, got ('A1', slice(None, None, None))`

**Comment by zky001** [comment] 2020-07-20 02:33
> maybe a better error message; something like `TypeError: expected label or tuple of label, got ('A1', slice(None, None, None))`

I think it's a good idea!

**Comment by wiso** [comment] 2020-07-20 07:22
Sorry, I am not sure to understand everything. Are you saying I can't pass a pd.IndexSlice to xs? Why not? It is working in one case and it is very useful.

By the way in general, I am searching for an alternative to `loc` that drop the columns automatically since `loc` is doing that only if the index is in the first level, while `xs` has a specific option about this behaviour.

**Comment by simonjayhawkins** [comment] 2020-07-20 10:09
the difference between `xs` and `loc` is that `xs` is a method on the DataFrame class whereas `loc` is an 'accessor' that uses \_\_getitem__ under the hood to allowing indexing using the square bracket operator.

`pd.Indexslice` is a convenience to more easily perform multi-index slicing to get around issues using the bracket annotation.

so at present, the working case is not documented, tested or supported.

I would therefore say, the issue is not a bug, but could maybe be an enhancement if it makes sense.

**Comment by wiso** [comment] 2020-07-20 10:44
I see, so if it is not supported I guess it should trigger an error if the user try to pass `pd.Indexslice` to `xs`.

As I said one big difference between `loc` and `xs` is how the index used by the function are dropped. It would be good to have the same control you have in `xs` (`drop_level: bool`)  in `loc`.

**Comment by simonjayhawkins** [comment] 2020-07-20 10:52
> As I said one big difference between `loc` and `xs` is how the index used by the function are dropped. It would be good to have the same control you have in `xs` (`drop_level: bool`) in `loc`.

Agreed. There has been some previous discussion on deprecating `xs`, but until this capability of `xs` is easily achieved with `loc` that's unlikely to happen.

so rather than enhancing `xs` to accept `pd.Indexslice`, it would probably be time better spent addressing the `loc` functionality.

I'll leave this labelled as `error reporting` for now, as improving the error message raised would be beneficial in the meantime.

**Closed** 2020-08-07 16:58 UTC
Labels: Error Reporting, Indexing
