### ISSUE TITLE
REGR: invalid cache after take operation with non-consolidated dataframe

### ISSUE THREAD

**Issue by on55** [pandas-dev/pandas#35521] opened 2020-08-03 03:05 UTC
a program run ok with pandas 1.0.5,  but after upgrade to 1.1.0.  it fail.
i found sometimes when I change one cell of dataframe value,  print(df) and it doesn't change.
but i use  ==, it says changed.
for example:  original  cell value is A, then i change cell value to B.   A=B
print df, it show still A
df.at(x, x) == B, it says TRUE.

-----

MarcoGorelli's edit: here's a reproducible example:

```
import pandas as pd


position = pd.DataFrame(columns=["code", "startdate"])
position = position.append([{"code": "a", "startdate": 0}])

# These two lines should not change anything.
# BUT, commenting either of them out makes this code run as intendeed
position["code"] == "A"
position[position["startdate"] == 0]

position.at[0, "code"] = "A"

print(position.at[0, "code"])
print(position)
```

output:
```
A
  code startdate
0    a         0
```

expected output:
```
A
  code startdate
0    A         0
```

**Comment by jreback** [comment] 2020-08-03 03:15
pls show an example that reproduces the issue

**Comment by MarcoGorelli** [comment] 2020-08-12 11:38
Closing as I can't reproduce this:

```
>>> import pandas as pd
>>> df = pd.DataFrame({'a': ['A']})
>>> df
   a
0  A
>>> df.loc[0, 'a'] = 'B'
>>> df.at[0, 'a'] == 'B'
True
>>> print(df)
   a
0  B
```

Please ping if you can provide a bug report as is suggested here https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment] 2020-08-14 21:08
@simonjayhawkins noticed you'd put the 1.1.1 milestone - were you able to reproduce this?

**Comment by on55** [comment] 2020-08-15 04:24
MarcoGorelli：
Nice to meet you!  sorry i seldom come to here and just see your comments.

Details is: 
The program read many data and calculate.
after program calculate and output a big dataframe,  then program change several value of the left 1st column in a cycle.
the sentence is  'position.at[index, 'code'] = code‘.
only one cell's value can not be changed. 
when i print(df) , it show original value.   i use 'df.at[x, y] == new value' it say TRUE.
i use 'df.at[x, y] == original value' it  say FALSE. 
since this sentence is ran in a cycle,  other cell's values are changed correctly, only one cell value meet this problem.

now i have degraded  to 1.0.5 and my program run ok again.
my program run ok with many pandas version,  just have issue with pandas 1.1.0.
so i suppose there may be  memory corruption for that version.

thank you and thank pandas.

**Comment by on55** [comment] 2020-08-15 04:46
supplement：
the dataframe is a little big and produced by program automatic,  it is not a simple dataframe with 1X1 matrix.
program change left 1st column's several cell value in a loop , and only one cell meet this issue,  other cell value is changed well.

the cell value printed show original value, 
when i use == new value it say TRUE.  
it looks like value is changed and just print issue.

following program continue run  and report error. 
because following program read dataframe and find the cell value still is original value, it doesn't changed. 
following program can not get correct code value，so it report error.

**Comment by simonjayhawkins** [comment] 2020-08-15 10:50
> @simonjayhawkins noticed you'd put the 1.1.1 milestone - were you able to reproduce this?

not tried to reproduce. using the 1.1.1 milestone as a tracker (for regressions and related PRs). 1.1.1 will be released next week and any items on the milestone still open at that time will be moved to 1.1.2 (or can review). the blocker tag can be used, but less relevant for a patch release as 1.1.2 could follow in 2-3 weeks.

for the minor releases (i.e 1.2) it is common to only apply the milestone when the PR is close to be ready (and then also on the corresponding issue)

when triaging issues i tend to either tag as 1.1.1(for regressions) or contributions welcome

**Comment by MarcoGorelli** [comment] 2020-08-15 12:26
> any items on the milestone still open at that time will be moved to 1.1.2 (or can review).

Thanks for explaining - OK have reopened so it can reviewed, though there's not much to go off of here

**Comment by jreback** [comment] 2020-08-15 12:43
this needs an actual reproducible example

**Comment by simonjayhawkins** [comment] 2020-08-17 19:20
> this needs an actual reproducible example

@on55 if you look at other bug reports, you'll see most use the template (available when opening a new issue) and ideally follow the guidance given in https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by simonjayhawkins** [comment] 2020-08-17 19:41
moved off 1.1.1 milestone (scheduled for this week) as no PRs to fix in the pipeline

**Comment by on55** [comment] 2020-08-21 07:28
today i upgraded pandas to 1.1.1, this issue still exist.

**Comment by asishm** [comment] 2020-08-24 16:42
I tried to do a `git bisect` on this

#34389 

```
760ba37a776947694ec816eaf29ce8937e08f544 is the first bad commit
commit 760ba37a776947694ec816eaf29ce8937e08f544
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Tue May 26 15:47:18 2020 -0700

    CLN: _consolidate_inplace less (#34389)

 pandas/core/generic.py            |  9 ---------
 pandas/core/internals/managers.py | 10 ----------
 2 files changed, 19 deletions(-)
bisect run success
```

**Comment by simonjayhawkins** [comment] 2020-08-25 10:10
cc @jbrockmendel

**Comment by jbrockmendel** [comment] 2020-08-25 16:49
The line `position[position["startdate"] == 0]` goes through `position.take`, which calls `self._mgr.take`, which calls `_consolidate_inplace`, which fails to invalidate the `_item_cache`.

One fix is to restore the `self._consolidate_inplace` done in `NDFrame.take` that was removed in #34389.  Another (my preferred long-term solution) is to remove the `self._consolidate_inplace` done in `BlockManager.take`.

**Closed** 2020-09-04 20:48 UTC
Labels: Bug, Internals, Regression
