### ISSUE TITLE
Silent Failure with Partial Rows

### ISSUE THREAD

**Issue by chelseas** [pandas-dev/pandas#22374] opened 2018-08-15 23:03 UTC
#### I was trying to read a file that looked like this (unbeknownst to me):

```text
1,
2, 1.23, 4.56
3, 1.24, 4.57
4, 1.25, 4.58
...
```
I wrote some code like this:
```python
import pandas as pd
pd.read_csv('file.txt').values

```
And the output I got looked liked this:
```python
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
```
#### Problem description

When I try to parse a text file that has partial rows, pandas silently fails by importing an array of NaNs. It should instead throw an error.

#### Expected Output

'Error: partial rows'

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-24-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.0
pytest: 3.5.1
pip: 18.0
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment] 2018-08-16 11:16
I don't get the same output as you. Can you make a http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports example? I'd recommend using `io.StringIO` to construct the "file"

```python
f = io.StringIO("""\
1,
2,1.23,4.56,
...

pd.read_csv(f)
```

**Comment by chelseas** [comment] 2018-08-20 01:28
I just typed some text into a text editor instead of using io. 
It looks like it has to do with delimiter presence:

1
1,2,3,
4,5,6,

produces 
array([[nan],[nan]])

and 

1,
1,2,3,
4,5,6,

produces

array([[ 3., nan],
       [ 6., nan]])

neither of which throws an error, OR is what I want (two possible options for desired behavior)
[pandas_issue.txt](https://github.com/pandas-dev/pandas/files/2300909/pandas_issue.txt)

**Comment by TomAugspurger** [comment] 2018-08-20 10:54
We ask for fully reproducible examples so that we can efficiently respond to all the issues we have, and help future contributors (maybe you) design unit tests, for a fix if necessary. So could you please put together a minimal example? I have potential suggestions, but it's hard to say since I can't reproduce.

**Comment by chelseas** [comment] 2018-08-20 17:26
I submitted a text file attached to my last reply, were you able to download and parse it?

**Comment by TomAugspurger** [comment] 2018-08-20 17:31
We can't include files in unit tests. Better to just have a StringIO object
for a self-contained example.

**Comment by WillAyd** [comment] 2018-08-20 17:32
This behavior is strictly limited to the header row. In fact if you ignore the header altogether you get the ParserError you are looking for:

```python
>>> pd.read_csv('pandas_issue.txt', header=None
ParserError: Error tokenizing data. C error: Expected 1 fields in line 2, saw 4
```

Not sure what the intention is as this is *extremely nuanced* and your CSV file is simply not well formed. You get a row of all NA values because of the trailing commas and the sole header column is assigned to that.

**Comment by chelseas** [comment] 2018-08-26 22:06
Well it's great if I know to pass "header=None" but what I want is for the file I submitted to return a parse error instead of an array of Nans. OR, perhaps, only read the first column of data, if that's the only one with header data. 

Unfortunately, I don't have ideas about how to do either of these things as I'm not familiar with the inner workings of pandas. I'm just here to report the issue and see if someone can solve it.

**Comment by TomAugspurger** [comment] 2018-08-27 14:28
I don't think we can raise an error. pandas is a tool for wrangling messy data, so it needs to be able to read messy CSVs. By default, we infer the number of columns from the file, but if you know better (say you store the schema in a separate file) then you can use that information to ensure an error is raised when the file doesn't match the schema.

**Comment by WillAyd** [comment] 2018-08-28 02:48
Agree with @TomAugspurger here; closing as won't fix

**Closed by WillAyd** 2018-08-28 02:48 UTC
Labels: IO CSV, Won't Fix
