### ISSUE TITLE
Pandas 1.03: pandas.tseries.offsets.QuarterBegin not showing correct date 

### ISSUE THREAD

**Issue by patrickxli** [pandas-dev/pandas#33194] opened 2020-04-01 01:35 UTC
#### Code Sample, a copy-pastable example if possible

```python
from datetime import datetime
from pandas.tseries.offsets import QuarterBegin

now = datetime.datetime(2020, 1, 12)

now - QuarterBegin()

```
#### Problem description
The code shows the following results:

now - QuarterBegin()
Out[28]: Timestamp('2019-12-01 00:00:00')

which is not expected.

#### Expected Output
Timestamp('2020-01-01 00:00:00')

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
pd.show_versions()
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.0.3
numpy            : 1.18.2
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200210
Cython           : 0.29.15
pytest           : 5.3.5
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0

</details>

**Comment by rockg** [comment] 2020-04-02 06:07
See #8435. The code assumes quarters start on month 3 (so 3, 6, 9, 12). Just pass in `startingMonth=1` to get the behaviour you are after.

**Comment by simonjayhawkins** [comment] 2020-04-08 11:00
Thanks @patrickxli for the report. closing as duplicate of #8435

**Closed by simonjayhawkins** 2020-04-08 11:00 UTC
Labels: Duplicate
