### ISSUE TITLE
DOC: Table Visualization/Styler Documentation Appears garbled

### ISSUE THREAD

**Issue by mrileysamc** [pandas-dev/pandas#48777] opened 2022-09-25 23:37 UTC
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/pandas-docs/version/1.5/user_guide/style.html

### Documentation problem

The samples in the table visualization docs all appear garbled. It looks like an issue with column widths. I have tried using multiple browsers. The issue only appears in 1.5 and dev documentation. 1.4 and below all look fine. See screenshot below:

![Capturepandas](https://user-images.githubusercontent.com/105988873/192170027-20acff9a-4fb5-4ede-b7ab-374c8445d402.JPG)

### Suggested fix for documentation

I don't see any change in code that would have caused this. I'm assuming it was caused by a change in a dependency package such as Jupyter or nbconvert.

**Comment by mrileysamc** [comment] 2022-09-25 23:48
Actually, docs look fine in Firefox. Issue appears to be confined to Chrome and Edge. I don't have access to Safari.

**Comment by asishm** [comment] 2022-09-26 04:46
the docs for 1.4.4 on Chrome look fine

**Comment by riziles** [comment] 2022-09-26 09:12
Yes. As I said, it is only an issue on the 1.5 docs. 1.4 looks fine.

**Comment by phofl** [comment] 2022-09-26 16:41
Duplicate of #48644

**Closed by phofl** 2022-09-26 16:41 UTC
Labels: Docs, Needs Triage
