### ISSUE TITLE
Documentation DataFrame.plot() not available

### ISSUE THREAD

**Issue by fgotzens** [pandas-dev/pandas#28280] opened 2019-09-04 10:11 UTC
#### Problem description

In the current stable pandas documentation both [DataFrame.plot()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.html#pandas.DataFrame.plot) and [Series.plot()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.html?highlight=plot#pandas.Series.plot) pages are broken, i.e. there is no content showing up.

Therefore, currently, one has to go back to an older version (e.g. [this](https://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.plot.html?highlight=plot#pandas.DataFrame.plot)) or a the latest [beta version](https://pandas-docs.github.io/pandas-docs-travis/reference/api/pandas.DataFrame.plot.html?highlight=plot#pandas.DataFrame.plot) .

**Comment by TomAugspurger** [comment] 2019-09-04 10:55
Duplicate of https://github.com/pandas-dev/pandas/issues/27748

**Closed by TomAugspurger** 2019-09-04 10:55 UTC
Labels: Duplicate
