### ISSUE TITLE
DOC: DataFrame.plot is missing most of the docstring

### ISSUE THREAD

**Issue by vlbrown** [pandas-dev/pandas#28046] opened 2019-08-20 21:39 UTC
In the pandas 0.25.0 docs, at
[pandas.DataFrame.plot.html](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.html)

#### Problem description

The page is essentially missing. The only content is 

```
DataFrame.plot(self, *args, **kwargs)[source]
Call self as a function.
```

#### Expected Output

It should look like [0.23.4 DataFrame.plot.html](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DataFrame.plot.html)

**Comment by TomAugspurger** [comment] 2019-08-20 21:43
@datapythonista do you think this is related to the backend refactor?

**Comment by datapythonista** [comment] 2019-08-20 21:49
It's very likely. A bit weird, because I remember checking that the accessors kept the documentation, but may be I changed more things after I did. I'll have a look at it tomorrow.

Thanks for reporting @vlbrown

**Comment by TomAugspurger** [comment] 2019-08-30 21:50
Duplicate of https://github.com/pandas-dev/pandas/issues/27748.

**Closed by TomAugspurger** 2019-08-30 21:50 UTC
Labels: Docs
