### ISSUE TITLE
Parquet file written with fastparquet backend cannot be read with pyarrow backend

### ISSUE THREAD

**Issue by languitar** [pandas-dev/pandas#28252] opened 2019-09-02 15:52 UTC
#### Code Sample, a copy-pastable example if possible

```python
In [63]: pd.DataFrame({'foo': [datetime(2019, 10, 1)], 'bar': ['test']}).to_parquet('/tmp/minimal.parquet', engine='fastparquet')                                                                                   

In [64]: pd.read_parquet('/tmp/minimal.parquet', engine='pyarrow')                                                                                                                                                  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-64-d866d1c8df39> in <module>
----> 1 pd.read_parquet('/tmp/minimal.parquet', engine='pyarrow')

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, **kwargs)
    294 
    295     impl = get_engine(engine)
--> 296     return impl.read(path, columns=columns, **kwargs)

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pandas/io/parquet.py in read(self, path, columns, **kwargs)
    123         kwargs["use_pandas_metadata"] = True
    124         result = self.api.parquet.read_table(
--> 125             path, columns=columns, **kwargs
    126         ).to_pandas()
    127         if should_close:

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib._PandasConvertible.to_pandas()

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pyarrow/table.pxi in pyarrow.lib.Table._to_pandas()

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pyarrow/pandas_compat.py in table_to_blockmanager(options, table, categories, ignore_metadata)
    642         column_indexes = pandas_metadata.get('column_indexes', [])
    643         index_descriptors = pandas_metadata['index_columns']
--> 644         table = _add_any_metadata(table, pandas_metadata)
    645         table, index = _reconstruct_index(table, index_descriptors,
    646                                           all_columns)

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pyarrow/pandas_compat.py in _add_any_metadata(table, pandas_metadata)
    965                 raw_name = 'None'
    966 
--> 967         idx = schema.get_field_index(raw_name)
    968         if idx != -1:
    969             if col_meta['pandas_type'] == 'datetimetz':

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pyarrow/types.pxi in pyarrow.lib.Schema.get_field_index()

~/.pyenv/versions/analytics-3.7/lib/python3.7/site-packages/pyarrow/lib.cpython-37m-x86_64-linux-gnu.so in string.from_py.__pyx_convert_string_from_py_std__in_string()

TypeError: expected bytes, dict found
```
#### Problem description

A parquet file written with the `fastparquet` backend cannot be converted back to a pandas data frame when read with the `pyarrow` implementation. Conversion fails with the shown Exception, which seems to be part of applying the pandas meta data.

#### Expected Output

Successful conversion.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.69-1-lts
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.0
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.2.1
setuptools       : 41.0.1
Cython           : None
pytest           : 5.0.1
hypothesis       : 4.32.2
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.4.0
html5lib         : None
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.7.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.4.0
matplotlib       : None
numexpr          : 2.6.9
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.14.1
pytables         : None
s3fs             : 0.3.1
scipy            : None
sqlalchemy       : 1.2.19
tables           : 3.5.2
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : 1.1.8
</details>

**Comment by TomAugspurger** [comment] 2019-09-03 15:17
FWIW, I can't reproduce with PyArrow 0.14.1, pandas 0.25.1, and fastparquet 0.3.0.

**Comment by languitar** [comment] 2019-09-03 15:37
I am not sure whose fault this is because it is related to pandas metadata. Does the metadata handling originate from pandas or from pyarrow and fastparquet?

**Comment by languitar** [comment] 2019-09-03 15:39
Btw, reproduced in a plain new virtualenv just right now.
```
pip install pandas pyarrow fastparquet python-snappy ipython
```
and then in ipython
```
from datetime import datetime
pd.DataFrame({'foo': [datetime(2019, 10, 1)], 'bar': ['test']}).to_parquet('/tmp/minimal.parquet', engine='fastparquet')
pd.read_parquet('/tmp/minimal.parquet', engine='pyarrow')
```

**Comment by TomAugspurger** [comment] 2019-09-03 16:28
I think it's created by the underlying engine, though pandas defines the
spec for it.

**Comment by languitar** [comment] 2019-09-05 07:17
Here is the reproduction without the pandas backends being involved:
```python
import pandas as pd
from datetime import datetime
import fastparquet
import pyarrow.parquet as pq

df = pd.DataFrame({'foo': [datetime(2019, 10, 1)], 'bar': ['test']})
fastparquet.write('/tmp/test.parquet', df)
pq.read_table('/tmp/test.parquet').to_pandas()
```

`read_table` still works. `to_pandas` is causing the exception.

**Comment by TomAugspurger** [comment] 2019-09-05 15:51
Here's the metadata

```python
{'column_indexes': [{'field_name': None,
                     'metadata': None,
                     'name': None,
                     'numpy_type': 'object',
                     'pandas_type': 'mixed-integer'}],
 'columns': [{'metadata': None,
              'name': 'foo',
              'numpy_type': 'datetime64[ns]',
              'pandas_type': 'datetime'},
             {'metadata': None,
              'name': 'bar',
              'numpy_type': 'object',
              'pandas_type': 'unicode'}],
 'index_columns': [{'kind': 'range',
                    'name': None,
                    'start': 0,
                    'step': 1,
                    'stop': 1}],
 'pandas_version': '0.25.1'}
```

cc @martindurant @jorisvandenbossche if either of you have a chance to look. Looks related to the pyarrow RangeIndex optimizations, but not sure if it's an issue with the reading or writing.

**Comment by martindurant** [comment] 2019-09-05 16:01
That read_table works but not to_pandas suggests to me that this is internal to arrow.

**Comment by jorisvandenbossche** [comment] 2019-09-05 16:41
I can reproduce this with pyarrow 0.14.1 and fastparquet 0.3.2.

It's indeed somewhat related to the RangeIndex optimizations, but it is actually not failing on the index, but on the interpreting the metadata of one of the columns (because there is no "field_name", and then there goes something wrong in our code to deal with the compat code for this case). 
If it's not yet done by then, I can investigate this a bit more next week (currently at EuroScipy).

**Comment by jorisvandenbossche** [comment] 2019-09-09 13:56
Created an issue on the Arrow side (https://issues.apache.org/jira/browse/ARROW-6492#) and created a PR to fix this (https://github.com/apache/arrow/pull/5331). And also opened issue on fastparquet side to get the metadata in a consistent state (https://github.com/dask/fastparquet/issues/462). 

So let's close this issue here, as there is no further action for pandas itself.

Thanks for the report @languitar !

**Closed by jorisvandenbossche** 2019-09-09 13:56 UTC
