### ISSUE TITLE
BUG: Cannot map MultiIndex to more levels

### ISSUE THREAD

**Issue by GPla** [pandas-dev/pandas#47173] opened 2022-05-30 16:01 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({
    'a': [0, 1, 2, 3],
}, index=['a_1/1', 'a_2/2', 'b_1/1', 'b_2/2'])

# split index into multiindex
df.index = df.index.map(lambda x: tuple(x.split('_')))
print(df.index)

# MultiIndex([('a', '1/1'),
#             ('a', '2/2'),
#             ('b', '1/1'),
#             ('b', '2/2')],
#            )

# cannot split the created multiindex into more levels
# ValueError: Length of names must match number of levels in MultiIndex.
df.index.map(lambda x: (x[0], *x[1].split('/')))
```

### Issue Description

An `Index` can be mapped into a `MultiIndex` with any number of levels. However, mapping an `MultiIndex` into more levels does not work. Applying `map` on a `MultiIndex` requires that the return value is either a single element (`Index`) or a tuple with the same number of elements as before. Returning a tuple with more elements than before is not possible.

### Expected Behavior

Expected would be a `MultiIndex` with more levels than the previous one:

```python
import pandas as pd
df = pd.DataFrame({
    'a': [0, 1, 2, 3],
}, index=['a_1/1', 'a_2/2', 'b_1/1', 'b_2/2'])

# split index into multiindex
df.index = df.index.map(lambda x: tuple(x.split('_')))
print(df.index)

#MultiIndex([('a', '1/1'),
#            ('a', '2/2'),
#            ('b', '1/1'),
#            ('b', '2/2')],
#           )

# circumvents the problem by flattening the index first
df.index = df.index.to_flat_index().map(lambda x: (x[0], *x[1].split('/')))
print(df.index)

#MultiIndex([('a', '1', '1'),
#           ('a', '2', '2'),
#            ('b', '1', '1'),
#            ('b', '2', '2')],
#           )



```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.3.1
numpy            : 1.21.4
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 59.2.0
Cython           : 0.29.23
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : 2.9.1 (dt dec pq3 ext lo64)
jinja2           : 3.0.3
IPython          : 7.20.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 2021.10.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.5.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : 1.4.13
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.53.0

</details>

**Comment by simonjayhawkins** [comment] 2022-06-08 10:59
@GPla thanks for the report. closing as duplicate of #24800 to help keep discussion in one place. (looks like need consensus on dropping column names)

**Closed by simonjayhawkins** 2022-06-08 10:59 UTC
Labels: Bug, MultiIndex, Index, Needs Triage
