### ISSUE TITLE
BUG: rank is not supported for double[pyarrow] dtype

### ISSUE THREAD

**Issue by dylan-lee94** [pandas-dev/pandas#51996] opened 2023-03-15 18:12 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
pd.options.mode.dtype_backend = 'pyarrow'

df = pd.DataFrame({
    'tags': pd.Series([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5],dtype='int64[pyarrow]'),
    'value': pd.Series(np.random.rand(15),dtype='double[pyarrow]')
    })

result = df['value'].rank()
result = df.groupby('tags')['value'].rank()
```

### Issue Description

When grouping a dataframe and applying the `rank ` function on a column with data type `double[pyarrow]` I get the following error: 
`TypeError: rank is not supported for double[pyarrow] dtype
`

However, applying the rank function without `groupby ` works. This leads me to believe that the error message is misleading and that in fact the `rank `function does support data type `double[pyarrow]`.

### Expected Behavior

The `rank` function works in combination with `groupby` for data type` double[pyarrow]`.

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by mroeschke** [comment] 2023-03-15 19:53
Thanks for the report.

Looks like for rank specifically we prevent casting to the original data type, probably because rank should be numeric and we don't want to cast the type back to a non-numeric type. 

https://github.com/pandas-dev/pandas/blob/2a983bb1c2e0c962d828dcd9c828d95c5d82bb5a/pandas/core/groupby/ops.py#L376-L379

In the short term, maybe an exception should be make here if the original dtype isn't numeric? In the longer term, I think we'll integrate a way to dispatch to pyarrrows groupby aggregation methods.

**Comment by topper-123** [comment] 2023-05-14 18:37
This looks fixed:

```python
import pandas as pd
import numpy as np
# pd.options.mode.dtype_backend = 'pyarrow'

df = pd.DataFrame({
    'tags': pd.Series([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5],dtype='int64[pyarrow]'),
    'value': pd.Series(np.random.rand(15),dtype='double[pyarrow]')
    })

result = df['value'].rank()
result = df.groupby('tags')['value'].rank()
print(result)
```

with the result being:

```
0     3.0
1     2.0
2     1.0
3     2.0
4     1.0
5     3.0
6     1.0
7     2.0
8     3.0
9     3.0
10    1.0
11    2.0
12    1.0
13    3.0
14    2.0
Name: value, dtype: double[pyarrow]
```

Before I close it, do you agree this works as intended now?

**Comment by topper-123** [comment] 2023-05-15 06:37
Ok, I'm closing, you can open again if you see something that needs to be discussed.

**Closed by topper-123** 2023-05-15 06:37 UTC
Labels: Bug, Groupby, Closing Candidate, Arrow
