### ISSUE TITLE
BUG: Pandas changing values when inferring dtypes

### ISSUE THREAD

**Issue by giovannirescia** [pandas-dev/pandas#40992] opened 2021-04-17 00:14 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python

import pandas as pd

df = pd.read_json('file.jsonl', orient='records', lines=True)

df['uuid']

```

#### Problem description

I have a `jsonlines` file (`file.jsonl`) that looks like this

```
{"id": 1, "uuid": "1344800117571260417"}
{"id": 2, "uuid": "1344900117571260918"}
```

After reading that file using the above code, this is what I get:

```
    id                 uuid
0   1  1344800117571260416
1   2  1344900117571260928
```

So the `uuid`s have changed

#### Expected Output

My output should look like

```
    id                 uuid
0   1  1344800117571260417
1   2  1344900117571260918
```

On Stackoverflow, someone answered [my post](https://stackoverflow.com/questions/67133093/pandas-changing-values-when-inferring-dtypes?noredirect=1#comment118664602_67133093), with the following explanation:

> int(float("1344900117571260918")) is 1344900117571260928 . I assume pandas first uses floats and afterwards converts it to int - so precision is lost. 

So the problem is how `pandas` is inferring the types.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.7.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-49-generic
Version          : #55~20.04.1-Ubuntu SMP Fri Mar 26 01:01:07 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.18.5
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200210
Cython           : 0.29.15
pytest           : 5.4.3
hypothesis       : 5.5.4
sphinx           : 2.4.0
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.2
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.2
fsspec           : 0.6.2
fastparquet      : None
gcsfs            : None
matplotlib       : 3.1.3
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.3
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : 0.8.7
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.48.0
</details>

**Comment by phofl** [comment] 2021-04-17 00:31
This gives you your expected result


```
data = """
{"id": 1, "uuid": "1344800117571260417"}
{"id": 2, "uuid": "1344900117571260918"}
"""

df = pd.read_json(StringIO(data), orient='records', lines=True, dtype="int64")
```

**Comment by phofl** [comment] 2021-04-17 00:38
The inference is done with astype and float64, which causes the precision loss, maybe could document this clearer

**Comment by giovannirescia** [comment] 2021-04-17 00:42
> This gives you your expected result
> 
> ```
> data = """
> {"id": 1, "uuid": "1344800117571260417"}
> {"id": 2, "uuid": "1344900117571260918"}
> """
> 
> df = pd.read_json(StringIO(data), orient='records', lines=True, dtype="int64")
> ```

yes, even using `dtype='int'` or `dtype=False` solves the problem, but I was looking for an explanation on why this was happening, which you just validated.

**Comment by asishm** [comment] 2021-04-17 04:39
imo this should be a bug, having a default that leads to a loss of precision is not desirable. This is also a bit counter intuitive / inconsistent because this doesn't occur with CSVs.

**Comment by phofl** [comment] 2021-04-17 09:42
I think this would be more of a enhancement of the inference logic in read_json

**Comment by asishm** [comment] 2021-04-19 10:13
Can close this as a duplicate of #20608 where it's classified as a bug

**Closed** 2021-04-19 10:45 UTC
Labels: Dtypes, Duplicate, Enhancement, IO JSON
