### ISSUE TITLE
Inplace is not an input argument to pandas.DataFrame.add_prefix

### ISSUE THREAD

**Issue by StavisT** [pandas-dev/pandas#45493] opened 2022-01-20 14:31 UTC
the `add_prefix` method does not have `inplace` as an input argument, while pandas.DataFrame.rename does.

https://github.com/pandas-dev/pandas/blob/66e3805b8cabe977f40c05259cc3fcf7ead5687d/pandas/core/generic.py#L4241-L4303

It is possible to add `inplace` as an input argument to `.add_prefix` to have the same inplace functionality as `.rename`.

**Comment by MarcoGorelli** [comment] 2022-01-20 15:17
Hi @StavisT - closing as a duplicate of https://github.com/pandas-dev/pandas/issues/43472

**Closed by MarcoGorelli** 2022-01-20 15:17 UTC
