### ISSUE TITLE
Not contains Question

### ISSUE THREAD

**Issue by Ayvytr** [pandas-dev/pandas#31807] opened 2020-02-08 10:58 UTC
#### Not contains Question

```python
    # df is a DataFrame contains column "title", then I filter df by column "title" below, it works.
    useless = df[df["title"].str.contains(r"[\d]+[册|本]", regex=True)]
    # but I want a not contains value below, it raise error: ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
    useless = df[not df["title"].str.contains(r"[\d]+[册|本]", regex=True)]
  
```
#### Problem description

How can I get a not contains value?

**Comment by alimcmaster1** [comment] 2020-02-08 13:07
Duplicate of #31806

**Closed by alimcmaster1** 2020-02-08 13:07 UTC
