### ISSUE TITLE
dispatch_to_series is very slow

### ISSUE THREAD

**Issue by RunningToTheEdgeOfTheWorld** [pandas-dev/pandas#26061] opened 2019-04-12 10:39 UTC
Since pandas 0.24.0   I found there is a function in ops.py named dispatch_to_series.
But dispatch_to_series is very slow,  that makes my code slower.
when I use pandas==0.23.0, it cost about 100 seconds,  but  when I use pandas==0.24.*  It cost 583 seconds.

This is my profile result.
![factor_test_1555059433](https://user-images.githubusercontent.com/22519984/56031324-b6ac7380-5d51-11e9-853d-8dcdf7b16417.png)
A and I found pandas become more slower because you call isinstance function too many times
link to history merge : [[PERF] use numexpr in dispatch_to_series #22284](https://github.com/pandas-dev/pandas/pull/22284)

**Comment by jreback** [comment] 2019-04-12 10:57
show a minimal example with code

**Comment by jbrockmendel** [comment] 2019-04-12 15:43
Duplicate of #25883, #24990.

@RunningToTheEdgeOfTheWorld `dispatch_to_series` was implemented because of a correctness/performance tradeoff, and correctness wins every time.  There has been some discussion about how to ameliorate the performance hit, but I'm not aware of any concrete steps.  If you have any ideas, PRs are welcome.

**Comment by TomAugspurger** [comment] 2019-08-09 13:55
Closing in favor of #24990

**Closed by TomAugspurger** 2019-08-09 13:55 UTC
Labels: Numeric, Performance
