### ISSUE TITLE
BUG: inconsistant `MultiIndex` behavior in `.loc`

### ISSUE THREAD

**Issue by auderson** [pandas-dev/pandas#56674] opened 2023-12-29 02:29 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame(index=pd.MultiIndex.from_product([list('ab'), list('cd'), list('e')]), columns=['Val'])

print(df.loc[np.s_[:,'c',:]])
print(df.loc[np.s_[:,'c',:], "Val"])
print(df.loc[np.s_[:,'c',:], :])
```

### Issue Description

When only selecting the index, the second level is dropped. But if I add a selector to the columns, the second level is kept.
![image](https://github.com/pandas-dev/pandas/assets/48577571/4bfe40ee-6131-4817-87c0-56596278eeba)

### Expected Behavior

I'm not sure if this is intended behavior, but it's inconsistant. FYI, I have a relevent report earlier: #43599

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.10.6.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.0-89-generic
Version             : #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 65.5.1
pip                 : 23.3.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by auderson** [comment] 2023-12-29 02:31
Note in the second example, the column "Val" is also dropped. So I think maybe the "c" in the index should also be dropped.

**Comment by rhshadrach** [comment] 2024-01-16 02:42
Thanks for the report. This appears to be a duplicate of #18631. Closing for now - if you think I've missed something, comment here and we can reopen.

**Closed by rhshadrach** 2024-01-16 02:42 UTC
Labels: Bug, Needs Triage
