### ISSUE TITLE
API: Default handling of nans in sum and add methods is inconsistent

### ISSUE THREAD

**Issue by jpeacock29** [pandas-dev/pandas#17416] opened 2017-09-01 19:13 UTC
```python
test_frame = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [1, 2, float('nan')],
})
```

When we use the `.sum(axis=1)` method to add these up, nans are excluded or treated as zeros:

```
> test_frame.sum(axis=1)
2.0
4.0
3.0
```

However, if we use `.add()` (or equivalently `+`), nans are propagated:
```
> test_frame.a.add(test_frame.b)
> test_frame.a + test_frame.b
2.0
4.0
NaN
```

I don't see a clear reason why these two methods should have different nan policys and the principle of least surprise suggests they should perform identically. 

For what it's worth, I think a default policy of propagating nans would be best since the result is more likely to draw attention to the problem and evoke a reasoned response from the user, rather than assuming a solution on the user's behalf.

**Comment by jreback** [comment] 2017-09-01 19:28
[13] and [14] are identical; these are binary operations; you can certainly fill *while* adding [12] if you want.

[11] is a general reducer, which has the ``skipna=True`` default.

I agree that these are slightly inconsistent, but would argue that these are different in purpose and thus deserve different defaults.

The binary operations are nan propogating, which makes it obvious if things get nan-ed out, and you do generally want the nans to propagate. While the aggregators you can very easily accidently include a nan, thus making everything nans out, *not* generally what one would expect.

```
In [11]: test_frame.sum(axis=1)
Out[11]: 
0    2.0
1    4.0
2    3.0
dtype: float64

In [12]: test_frame.a.add(test_frame.b, fill_value=0)
Out[12]: 
0    2.0
1    4.0
2    3.0
dtype: float64


In [13]: test_frame.a.add(test_frame.b)
Out[13]: 
0    2.0
1    4.0
2    NaN
dtype: float64


In [14]: test_frame.a + test_frame.b
Out[14]: 
0    2.0
1    4.0
2    NaN
dtype: float64
```

see #9422 for more discussion. This is an opionated design and not a bug.

**Comment by mroeschke** [comment] 2022-07-05 23:20
Closing as it appears this is the intended behavior

**Closed by mroeschke** 2022-07-05 23:20 UTC
Labels: Bug, Missing-data, Numeric Operations, API - Consistency, Closing Candidate
