### ISSUE TITLE
BUG: Series converted to Nan if index is string

### ISSUE THREAD

**Issue by gsakkis** [pandas-dev/pandas#54358] opened 2023-08-01 18:30 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python

In [1]: import pandas as pd

In [2]: values = [1, 2, 3]

In [3]: index = ["i1", "i2", "i3"]

In [4]: s = pd.Series(values, name='c')

In [5]: pd.DataFrame(s)
Out[5]:
   c
0  1
1  2
2  3

In [6]: pd.DataFrame(s.values, index=index)
Out[6]:
    0
i1  1
i2  2
i3  3

In [7]: pd.DataFrame(s, index=index)
Out[7]:
     c
i1 NaN
i2 NaN
i3 NaN
```

### Issue Description

Line [7] replaces values with NaN

### Expected Behavior

Line [7] should be equivalent to [6]

### Installed Versions

<details>
pandas           : 2.0.3
numpy            : 1.24.2
</details>

**Comment by mroeschke** [comment] 2023-08-01 19:58
Thanks for the report but this is expected due to index alignment of `s` to `index=index`. Since `s` has a different index than `index` the mismatch fills with nan. Since this is the expected behavior closing

**Closed by mroeschke** 2023-08-01 19:58 UTC
Labels: Bug, Needs Triage
