### ISSUE TITLE
BUG: Assigning back dataframe with dropna does not work, but works with inplace = True

### ISSUE THREAD

**Issue by yunkypunky** [pandas-dev/pandas#41220] opened 2021-04-29 18:34 UTC
- [X] I have checked that this issue has not already been reported.

- [X ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd
import numpy as np
test_df1 = pd.DataFrame({'a':[1,2,3,4],'b':['a','b','c','d'],'c':[np.nan,np.nan,np.nan,np.nan]})
test_df2 = pd.DataFrame({'a':[1,2,3,4],'b':[np.nan,np.nan,np.nan,np.nan],'c':['a','b','c','d']})

def drop_na_test1(df):
    df = df.dropna(axis=1,how='all')
    return df

def drop_na_test2(df):
    df.dropna(axis=1,how='all',inplace=True)
    return df

dfs_to_process = [test_df1,test_df2]
for df in dfs_to_process:
    df = drop_na_test1(df)
display(test_df1)
display(test_df2)

for df in dfs_to_process:
    df = drop_na_test2(df)
display(test_df1)
display(test_df2)
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]
Assigning back dataframe with dropna() should yield same result as dropna(inplace=True).

#### Expected Output
Expect same result with df=df.dropna() as df.dropna(inplace=True)
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.9.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : English_United States.1252

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
numba            : None

**Comment by mzeitlin11** [comment] 2021-04-29 19:11
Thanks for the report @yunkypunky. Would you mind elaborating on what the problem is? In your example, you're displaying `test_df1` and `test_df2`. The call to `drop_na_test2` is modifying `test_df1` and `test_df2` inplace, so displaying them the second time will be different than the first time.

**Comment by yunkypunky** [comment] 2021-04-29 19:41
I was expecting the same result for df = df.dropna(axis=1,how='all') and df.dropna(axis=1,how='all',inplace=True),  but  df = df.dropna(axis=1,how='all') is not showing the result of the dropna.  Code below may be more illustrative of the issue.



import pandas as pd
import numpy as np
test_df1 = pd.DataFrame({'a':[1,2,3,4],'b':['a','b','c','d'],'c':[np.nan,np.nan,np.nan,np.nan]})
test_df2 = pd.DataFrame({'a':[1,2,3,4],'b':[np.nan,np.nan,np.nan,np.nan],'c':['a','b','c','d']})
test_df3 = pd.DataFrame({'a':[1,2,3,4],'b':['a','b','c','d'],'c':[np.nan,np.nan,np.nan,np.nan]})
test_df4 = pd.DataFrame({'a':[1,2,3,4],'b':[np.nan,np.nan,np.nan,np.nan],'c':['a','b','c','d']})
def drop_na_test1(df):
    df = df.dropna(axis=1,how='all')
    return df

def drop_na_test2(df):
    df.dropna(axis=1,how='all',inplace=True)
    return df

dfs_to_process = [test_df1,test_df2]
for df in dfs_to_process:
    df = drop_na_test1(df)
display(test_df1)
display(test_df2)

dfs_to_process2 = [test_df3,test_df4]
for df in dfs_to_process2:
    df = drop_na_test2(df)
display(test_df3)
display(test_df4)

**Comment by mzeitlin11** [comment] 2021-04-29 19:49
Sorry, still not sure what you're trying to do based on the above. What I'm saying is that if you operate inplace, the input dataframe will be modified. If you don't, the input dataframe will not be modified.

**Comment by mzeitlin11** [comment] 2021-04-29 20:34
python is a pass by reference language, meaning that if you pass an argument to a function, then assign to that argument, you are not modifying what was originally passed in (you are just reassigning the reference in the function scope).

**Comment by yunkypunky** [comment] 2021-04-29 20:46
Got it.  Guess you should close this out.

**Closed** 2021-04-29 20:56 UTC
Labels: Missing-data, Needs Info
