### ISSUE TITLE
QST: conda_create("r-reticulate") returning error

### ISSUE THREAD

**Issue by lynneitelson** [pandas-dev/pandas#49273] opened 2022-10-24 05:51 UTC
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/74171189/conda-creater-reticulate-returning-error

### Question about pandas

 am trying to install pandas on r using a conda environment. in order to do that i used the following code:

`install.packages("reticulate") library(reticulate)

#create a new conda enviroment

conda_create("r-reticulate")`

installing the package was fine but the following error came up while using conda_create:

![image](https://user-images.githubusercontent.com/109670658/197456617-38ea54af-c3cc-43e3-8c76-020719548b20.png)

Also i looked at the conda_list to see if that's the issue 

![image](https://user-images.githubusercontent.com/109670658/197456669-0597a775-9b36-490c-8b59-d81c55be641e.png)

Thank you,

Lynne

**Comment by MarcoGorelli** [comment] 2022-10-24 08:48
Hi @lynneitelson 

Thanks for the report - if I understand correctly, you did
```
install.packages("reticulate") library(reticulate)
conda_create("r-reticulate")
```
and it failed on the second command?

If so, this sounds like it's not pandas that's the issue? Closing then, but do let us know if you think the issue is on pandas' side

**Closed by MarcoGorelli** 2022-10-24 08:48 UTC
Labels: Usage Question, Needs Triage
