### ISSUE TITLE
BUG: v1.5.0 dataframe.replace function cause python to crash

### ISSUE THREAD

**Issue by WilliamQue** [pandas-dev/pandas#48843] opened 2022-09-29 01:42 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

t = pd.DataFrame({'a':[1,3,2,np.nan]})
t.replace(np.nan,None,inplace=True)
```

### Issue Description

After using replace function, python will crash.

### Expected Behavior

Nothing

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
python           : 3.9.13.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936
pandas           : 1.5.0

</details>

**Comment by phofl** [comment] 2022-09-29 07:51
Hi, this is a duplicate of #45725

**Closed by phofl** 2022-09-29 07:51 UTC
Labels: Bug, Needs Triage
