### ISSUE TITLE
pandas.errors.EmptyDataError: No columns to parse from file despite file being populated

### ISSUE THREAD

**Issue by Lamm-a** [pandas-dev/pandas#33011] opened 2020-03-25 12:17 UTC
#### Code Sample, a copy-pastable example if possible

```python
df = pd.read_csv(filename, sep = r'\s{1,}')

```
#### Problem description
I am trying to read in a txt as a pandas dataframe that I previous edited a column header in using `.replace()` and I get the error:

```
Traceback (most recent call last):
  File "dbcan_to_EC.py", line 26, in <module>
    EC_generator(directory)
  File "dbcan_to_EC.py", line 20, in EC_generator
    df = pd.read_csv(directory, sep = " ")
  File "/home/lamma/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lamma/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/lamma/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/lamma/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/lamma/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

```

#### Sample of the inut file

```
Gene_ID	HMMER	Hotpep	DIAMOND	#ofTools
M32_00003	CBM16(54-167)+GH18(293-521)	GH18(11)+CBM16(1)	CBM16+GH18	3
M32_00048	GH87(65-567)	GH87(2)	GH87	3
M32_00053	GH13_30(36-384)	GH13(4)	GH13_30	3
M32_00083	CE4(60-180)	CE4(33)	CE4	3
M32_00093	GH16(86-322)	GH16(2)+CBM11(2)	GH16	3
M32_00101	GH15(232-611)	GH15(2)	GH15	3
M32_00106	GH114(62-231)	GH114(2)	GH114	3
M32_00164	GH3(61-286)	GH3(15)	GH3	3
M32_00173	GH1(30-487)	GH1(2)	GH1	3
M32_00174	GH2(358-783)	GH2(6)	GH2	3
```

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1062.1.1.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.utf-8
LANG             : en_US.utf-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

**Comment by dsaxton** [comment] 2020-03-25 18:02
It looks like you're using an old version of pandas; does the problem persist if you upgrade? I'm not able to reproduce this error on 1.0.3 or master.

**Comment by simonjayhawkins** [comment] 2020-04-01 09:01
> I'm not able to reproduce this error on 1.0.3 or master.

couldn't reproduce on 0.25.1 either using sample data (same version as @Lamm-a reported)

**Comment by simonjayhawkins** [comment] 2020-04-01 09:05
@Lamm-a We would need a minimal reproducible example to help debug the issue. see https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by Lamm-a** [comment] 2020-04-01 12:30
I will provide what is needed :)

**Comment by MarcoGorelli** [comment] 2020-05-02 10:36
Thanks @Lamm-a for the report

Closing as I can't reproduce either - feel free to reopen if you can provide a reproducible example

**Closed by MarcoGorelli** 2020-05-02 10:36 UTC
Labels: Needs Info

**Comment by Jay484** [comment] 2020-08-13 03:29
error can be reproduced by reading empty file

**Comment by MarcoGorelli** [comment] 2020-08-13 07:26
Wouldn't "empty data error" be the correct thing to raise then?
