### ISSUE TITLE
BUG: pyarrow string not saved for index column when writing parquet

### ISSUE THREAD

**Issue by qltwis** [pandas-dev/pandas#53036] opened 2023-05-02 14:04 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.DataFrame({
 "a":["aiwj","odko"],
 "b":["adwl","gfoe"],
 "c":["okdp","mbna"]
}).astype("string[pyarrow]").set_index("a").to_parquet("test.parq")

pd.read_parquet("test.parq").index.dtype
```

### Issue Description

The dtype information for the index column is lost when saving as parquet. 

### Expected Behavior

`pd.read_parquet("test.parq").index.dtype` should return `string[python]` but instead gives `dtype('O')`

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-41-generic
Version          : #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.1
numpy            : 1.22.4
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.3.0
pip              : 22.2.2
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.4.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.4.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : 0.55.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 1.4.45
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by qltwis** [comment] 2023-05-04 09:56
> Thanks for the report. This will be fixed in pyarrow 12 so closing as it will be fixed upstream: [apache/arrow#34445](https://github.com/apache/arrow/pull/34445)

Thank you for the info. With pyarrow 12 `pd.read_parquet("test.parq", dtype_backend="pyarrow").index.dtype` produces the correct index dtype. 

However, with the numpy backend the index type is still read as object. The other columns are correctly identified as `string[python]`. I imagine that's not intended behavior, right?

**Comment by qltwis** [comment] 2024-02-06 21:57
Unfortunately this bug persists despite the fix in pyarrow 12.

**Comment by mroeschke** [comment] 2024-07-17 21:23
This is unfortunately the intended behavior as long as pandas default string type is `object`. parquet does not encode how the string type implementation from pandas.

This can change in pandas 3.0 when the default string implementation is `pyarrow` if installed as a dependency. Otherwise one will need to specify the `dtype_backend` argument to recover the implementation so closing

**Closed by mroeschke** 2024-07-17 21:23 UTC
Labels: Bug, Dtype Conversions, IO Parquet, Arrow
