### ISSUE TITLE
BUG: pandas.to_datetime() does not respect exact format string with ISO8601

### ISSUE THREAD

**Issue by ssche** [pandas-dev/pandas#12649] opened 2016-03-17 02:28 UTC
#### Code Sample, a copy-pastable example if possible

```
import pandas as pd
s = pd.Series(['2012-01-01 10:00', '2012-02-10 23:20', '2012-03-22 12:40', '2012-05-02 02:00', '2012-06-11 15:20', '2012-07-22 04:40','2012-08-31 18:00', '2012-10-11 07:20', '2012-11-20 20:40', '2012-12-31 10:00'])
print s
0    2012-01-01 10:00
1    2012-02-10 23:20
2    2012-03-22 12:40
3    2012-05-02 02:00
4    2012-06-11 15:20
5    2012-07-22 04:40
6    2012-08-31 18:00
7    2012-10-11 07:20
8    2012-11-20 20:40
9    2012-12-31 10:00
dtype: object
print pd.to_datetime(s, format='%Y-%m-%d', errors='raise', infer_datetime_format=False, exact=True)
0   2012-01-01 10:00:00
1   2012-02-10 23:20:00
2   2012-03-22 12:40:00
3   2012-05-02 02:00:00
4   2012-06-11 15:20:00
5   2012-07-22 04:40:00
6   2012-08-31 18:00:00
7   2012-10-11 07:20:00
8   2012-11-20 20:40:00
9   2012-12-31 10:00:00
dtype: datetime64[ns]
```
#### Expected Output

A ValueError exception because string `'2012-01-01 10:00'` (and all others of this series) does not comply with format string `'%Y-%m-%d'` and exact conversion is required.
## INSTALLED VERSIONS

commit: None
python: 2.7.10.final.0
python-bits: 64
OS: Darwin
OS-release: 15.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None

pandas: 0.17.1
nose: 1.3.6
pip: 8.0.3
setuptools: 18.0
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.16.0
statsmodels: None
IPython: 3.0.0
sphinx: None
patsy: None
dateutil: 2.5.0
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.4.3
openpyxl: 2.2.2
xlrd: 0.9.3
xlwt: 0.8.0
xlsxwriter: 0.7.3
lxml: 3.4.4
bs4: None
html5lib: None
httplib2: 0.9.1
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None

**Comment by ssche** [comment] 2016-03-17 02:44
The problem is this part in `pd.to_datetime()`:
```
       if format is not None:
            # There is a special fast-path for iso8601 formatted
            # datetime strings, so in those cases don't use the inferred
            # format because this path makes process slower in this
            # special case
            format_is_iso8601 = _format_is_iso(format)
            print 'format_is_iso8601', format_is_iso8601
            if format_is_iso8601:
                require_iso8601 = not infer_datetime_format
                format = None
```
When I change the condition to `if format is not None and infer_datetime_format`, it works as expected. Is this something that could be changed in Pandas. I find it quite confusing that despite explicitly setting `infer_datetime_format=False` there's still some internal magic happening in this function. Others may feel the same, not sure...

**Comment by jreback** [comment] 2016-03-17 02:47
nothing to do with that. Its here: https://docs.python.org/3/library/re.html#search-vs-match

if ``format`` is specified and ``exact=True`` (the default) its a ``.match`` like search, meaning it must match at the beginning (as opposed to anywhere). So this is a valid match.

I suppose we could be more stricted on ``exact``, e.g. maybe make it ``exact='match|search|False`` or something.

but why is this a problem? (as an aside you have an ISO8601 string, so you don't need to do anything to parse it).

**Comment by ssche** [comment] 2016-03-17 02:54
I'm trying out a few date formats and want to determine the correct one. If I try `'%Y-%m-%d'` and `'%Y-%m-%d %H:%M:%S'`, they both match which isn't quite true.

**Comment by jreback** [comment] 2016-03-17 03:01
hmm, actually I take that back. it IS removing the format BECAUSE its ISO8601. I am not sure it makes sense to change this as there is a perf penalty for parsing ISO strings with an actual format string (via regex). And we expect (and users expect) that the perf will be the same whether they pass a compat format or not.

Further if it actually does match ISO how is this a problem?

**Comment by ssche** [comment] 2016-03-17 03:14
In my case, I can easily fix this in the application by not checking for multiple iso format strings. I am trying to detect date format ambiguities, i.e. more than one date format matching which is a generalisation of discerning the `%m/%d` vs. `%d/%m` case.

However, I was surprised to get this kind of behaviour from this function as I thought I disabled all auto-magic (`infer_datetime_format=False, exact=True`) behaviour. I wasn't concerned with possible performance hits.

Perhaps a comment in the documentation would suffice to clarify this behaviour if it cannot be turned off through parameters.

**Comment by ssche** [comment] 2016-03-17 03:16
> nothing to do with that (well you can disable if you set infer_datetime_format=False). Its here: https://docs.python.org/3/library/re.html#search-vs-match

Your intuition seemed to have been the same as mine... But `infer_datetime_format=False` doesn't work like this for this iso date case.

**Comment by jreback** [comment] 2016-03-17 03:16
@ssche I don't see any ambiguity in an ISO8601 string. That's the point, it cannot be anything but ``dayfirst=False``, ``yearfirst=False`` by-definition.

**Comment by jreback** [comment] 2016-03-17 03:17
```
        if format is not None:
            # There is a special fast-path for iso8601 formatted
            # datetime strings, so in those cases don't use the inferred
            # format because this path makes process slower in this
            # special case
            format_is_iso8601 = _format_is_iso(format)
            if format_is_iso8601:
                require_iso8601 = not infer_datetime_format
                format = None
```

the code says it all. If you would like to update the doc-string, by all means.

**Comment by ssche** [comment] 2016-03-17 03:18
The ambiguity detection is something I do in my application. I just provided this bit of information as background info because you asked.
The point here is that `infer_datetime_format=False, exact=True` do some auto-magic behaviour which is unexpected.

**Comment by jreback** [comment] 2016-03-17 03:19
@ssche its not unexpected, you gave it a ``format`` string which is ISO8601. I don't see any problem here. If you give it a non-ISO8601 string then it would indeed raise.

**Comment by jreback** [comment] 2016-03-17 03:20
```
In [16]: pd.to_datetime(s, format='%Y-%m-%d%H', infer_datetime_format=False, exact=True, errors='raise')
ValueError: time data '2012-01-01 10:00' does not match format '%Y-%m-%d%H' (match)
```

**Comment by ssche** [comment] 2016-03-17 03:21
So you don't find it confusing that the behaviour of this function is date format-specific, i.e. given another date format an exception is raised?

**Comment by jreback** [comment] 2016-03-17 03:22
@ssche I am not sure what you mean. Of course its date-format specific. Its just special cased to ISO8601 to match the general format.

**Comment by ssche** [comment] 2016-03-17 03:24
In the iso-format case, the date format doesn't need to be exact, but for all other formats and exception will be raised when the format doesn't match.

**Comment by jreback** [comment] 2016-03-17 03:28
and so? again why is this a problem. by definition they are ISO8601 which matches a variety of non-ambiguous formats (where the time is optional), and separators can be optional (pandas actually allows a lot more separators than the standard).

So we tend to parse more easily lots of formats. I still don't understand why this is a problem. It parses correctly as it should, even though you gave an underspecified format.

**Comment by ssche** [comment] 2016-03-17 03:35
> So we tend to parse more easily lots of formats. I still don't understand why this is a problem. It parses correctly as it should, even though you gave an underspecified format.

That's exactly my problem. I have a very specific use case which requires to raise an exception when the date format doesn't match. Trying `'%Y-%m-%d'` and `'%Y-%m-%d %H:%M:%S'` both won't raise an exception for parsing `'2012-01-01 10:00'`, so the application is unable to detect the proper (=exact, =non underspecified) date format (that's all I care about).

I tried to make this more strict through the parameters I quoted a number of times already, but this didn't make the date conversion more strict. I don't know how else I can make this function more strict to only accept date formats that I specify and raise an exception if they don't.

**Comment by jreback** [comment] 2016-03-17 03:39
well you can try to make a change to the code to see if u can make it very strict but I suspect this will be quite tricky (maybe add exact='strict') or something

alternately in your code it's easy enough to check for lengths of the input strings

**Comment by ssche** [comment] 2016-03-17 03:50
So the `if format is not None and infer_datetime_format` "fix" I proposed wouldn't be acceptable?

**Comment by jreback** [comment] 2016-03-17 03:53
no that defeats the purpose of iso format detection

you could allow infer_datetime_format='strict' for maybe exact='striict') which when s format is specified could bypass the inference check (and then would fail because it's not an exact match)

**Comment by rsheftel** [comment] 2016-10-13 22:05
Just adding my two cents because I was running into the same exact problem. My use case is that I have a program that uses read_csv to load a csv file where the index is either just a date, or date and time. If it has a time I want to make it UTC time zone, if not then no time zone. The pythonic way to do it I thought would be try to read_csv with a parser using to_datetime that would try to match one format, and if that raised an exception try the other format. But by not raising the exception if there is not an exact match that approach does not work.

I would be in favor of an exact='strict' or similar to truly enforce the exact match.

**Comment by fersarr** [comment] 2018-04-24 15:36
this breaks a lot of tests for us as well. Very similar use case as @rsheftel

**Comment by philipCrunchboards** [comment] 2019-03-13 16:35
We're having the same problem.
I'd like to be able to add some argument(s) to the following code to make it either `raise` or return `NaT`:
```
> to_datetime(0.0, format="%Y-%m-%d", exact=True)
Timestamp('1970-01-01 00:00:00')
```
I like the sound of `exact="strict"`.

**Comment by jo47011** [comment] 2019-11-04 15:47
We ran into the same problem.  I already raised a question at stackoverflow:
[Pandas to_datetime not setting NaT on wrong format](https://stackoverflow.com/questions/58694383/pandas-to-datetime-not-setting-nat-on-wrong-format)
Is there a decision yet on how to proceed with this issue?

**Comment by jrmistry** [comment] 2020-08-25 21:30
Hello all,

Not sure if my issue is the same but posting here for suggestions.

Core problem: the pd.to_datetime function does not respect original values even if I set errors = 'ignore'

See example below. The column of values is stored in a UTC timestamp in milliseconds. When I try to convert it to a datetime object, pandas automatically fills in the NaN values with NaT even thought I specifically told it to ignore errors. Any suggestions on how to fix this? Thanks

![image](https://user-images.githubusercontent.com/8127024/91229903-98ea6f00-e6f8-11ea-8b25-c3f7edb87d07.png)

**Comment by IngErnestoAlvarez** [comment] 2020-12-12 17:21
I think that's not a problem, to_datetime changes the dtype of the list to datetime, and NaT is the equivalent of NaN on datetime dtype. When u convert NaN to datetime it will change to NaT and that's not an error.

**Comment by rsheftel** [comment] 2021-05-22 18:24
The PR #35741 seems to say that in the future the date_parser in read_csv will be deprecated. Does anyone know what the right way to invoke a custom date parser will be in the future?

**Comment by brandon-leapyear** [comment] 2022-02-28 17:35
We're also coming up against this. As a minimal example, this is very confusing behavior for me:
```py
>>> pd.to_datetime('2022/02/01', format="%Y-%m-%d")
Timestamp('2022-02-01 00:00:00')
>>> pd.to_datetime('2022/02/01', format="%Y-%m")
Timestamp('2022-02-01 00:00:00')
```
We're trying to require the input to EXACTLY be `%Y-%m-%d`; all other formats should error. The logic mentioned earlier in this thread is very odd behavior: if the string passed to `format` is a prefix of any ISO formats, `format` is implicitly converted to allow any ISO string. IMO this "any ISO format" logic should be under a completely different flag, like `iso_format=True`, and `format` should be an exact match

https://github.com/pandas-dev/pandas/blob/3cf30739dbd1162c9c81728ed2f8da949b6e367a/pandas/_libs/tslibs/parsing.pyx#L856

**Comment by aflag** [comment] 2022-04-12 17:25
We have also been bitten by this. Is there any workaround for the time being? The current behaviour is a bit inconsistent, because if I try

```
 pd.to_datetime([1], format="%Y-%m-%d %H:%M")
```

it doesn't raise any errors and parses the date to be `1970-01-01 00:00:00.000000001` however, by just changing the separator it works in a very different way:

```
 pd.to_datetime([1], format="%Y|%m|%d %H:%M")
```

raises ```ValueError: time data '1' does not match format '%Y|%m|%d %H:%M' (match)```.

I feel like this is a regression in the API, as it used to work with older versions of pandas (eg.: in 0.22.0 it would raise an exception as expected). What's the rationale for not respecting the format supplied just because it resembles the ISO 8601 format?

**Comment by ssche** [comment] 2022-09-18 23:49
xref #12585

**Comment by MarcoGorelli** [comment] 2022-10-18 10:56
I think it should be possible to make the fast iso8601 path respect `exact`, that'd make it unnecessary to add an extra argument - I'm giving this a go (will require https://github.com/pandas-dev/pandas/pull/49024 to be in first though)

**Comment by MarcoGorelli** [comment] 2022-10-19 15:27
I've opened https://github.com/MarcoGorelli/pandas/pull/5/files as a POC to address this

The code is very messy, and I'll clean it up before opening a PR to this repo, but @ssche @aflag @brandon-leapyear @philipCrunchboards @fersarr @rsheftel  I just wanted to ask if you could take a look at 

https://github.com/MarcoGorelli/pandas/blob/fc419d526ad1f7cf2a1174dae6f9385734e7283e/pandas/tests/tools/test_to_datetime.py#L1736-L1824

and check if it addresses the issue you ran into - thanks 🙏

**Comment by ssche** [comment] 2022-10-20 23:03
Looks good @MarcoGorelli. One thing I would add is a test that tries to convert a list of datetime strings with a mix of strings (some comply with the format, some don't, so I would expect the whole conversion to fail). I would also add a few ambiguous strings with month/day swapped (https://github.com/pandas-dev/pandas/issues/12649#issuecomment-197672942).

**Comment by MarcoGorelli** [comment] 2022-10-21 06:32
thanks for taking a look!

> I would also add a few ambiguous strings with month/day swapped

Not sure what you mean here, sorry - isn't ISO8601 always month before day? If it doesn't hit this ISO8601 fast-path, then it should be addressed by PDEP0004

If you have a specific test case in mind I can check

**Comment by MarcoGorelli** [comment] 2022-10-21 06:34
thanks for taking a look!

> I would also add a few ambiguous strings with month/day swapped

Not sure what you mean here, sorry - isn't ISO8601 always month before day? If it doesn't hit this ISO8601 fast-path, then it should be addressed by PDEP0004

If you have a specific test case in mind I can check

**Comment by ssche** [comment] 2022-10-23 12:08
From your question and the fact that you renamed the ticket, I think there’s a misunderstanding. This ticket had nothing to do with ISO8601 compliant formats.
The problem was that it would parse dates even though they were not compliant with the format string without raising an exception by using some “auto-magic” behaviour. My use case (and the one of many others here) required exact parsing across a vector of dates. The fact that some date strings resembled/equalled ISO8601 and therefore would be going through some fasttrack code path didn’t matter to me (from a user’s point of view). I simply couldn’t use the current behaviour in my application as it would corerce some dates (what I called “auto-magic) because I was looking for an error message to let the end user decide which format is valid.

**Comment by MarcoGorelli** [comment] 2022-10-23 12:26
> The problem was that it would parse dates even though they were not compliant with the format string without raising an exception by using some “auto-magic” behaviour

Currently, it only does that if the `format` is ISO8601. So yes, this has everything to with ISO8601

For example, the following raises (`format` isn't ISO8601)
```
pd.to_datetime('01-01-2000 00:00:00', format='%d-%m-%Y')
```
whereas the following doesn't (`format` is ISO8601):
```
pd.to_datetime('2000-01-01 00:00:00', format='%Y-%m-%d')
```

I agree that to a user, this shouldn't make a difference. So the issue is about fixing the ISO8601 fast-path so that it also respects `exact`

**Comment by ssche** [comment] 2022-10-23 13:06
> Currently, it only does that if the format is ISO8601. So yes, this has everything to with ISO8601

Oh right, so this is not a general problem, but one that only arises when ISO8601 formats are used. That explains a lot (in particular this lenghty discussion I had at the time).

Thanks for clarifying!

> Not sure what you mean here, sorry - isn't ISO8601 always month before day?

I meant how an array of `[‘2022-01-13’, ‘2022-13-01’]` would be interpreted with `format='%Y-%m-%d'`, but I guess this would raise an error now and not try to coerce the 2nd date also to Jan 13 (not sure if it ever did).

**Closed** 2022-11-17 13:17 UTC
Labels: Enhancement, Timeseries, Needs Discussion
