### ISSUE TITLE
BUG: read_html blocks for a very long time

### ISSUE THREAD

**Issue by quantdata2018** [pandas-dev/pandas#53192] opened 2023-05-12 02:25 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
htmls = '''<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th>0</th>      <th>1</th>      <th>2</th>    </tr>  </thead>  <tbody>    <tr>      <td>负债及股东权益附注</td>      <td>2022年 12月31日</td>      <td>2021年 12月31日</td>    </tr>    <tr>      <td>负债应付短期融资款六 、19拆入资金六 、20交易性金融负债六 、21衍生金融负债六 、4卖出回购金融资产款六 、22代理买卖证券款六 、23代理承销证券款六 、24应付职工薪酬六 、25应交税费六 、26应付款项六 、27合同负债六 、28租赁负债六 、29应付债券六 、30递延所得税负债六 、16其他负债六 、31</td>      <td>18,551,991,95760,846,018,71445,203,291,77711,348,127,49743,156,698,54892,099,956,329–8,706,270,0081,803,268,972109,243,693,220407,792,2612,422,828,848151,983,965,462718,765,0652,796,674,955</td>      <td>22,989,857,48951,477,278,67838,926,786,68418,134,007,50816,376,070,95193,445,165,3077,304,310,90011,168,865,0801,597,169,578134,908,863,413412,950,8742,002,895,426160,508,549,775431,655,2345,380,225,891</td>    </tr>    <tr>      <td>负债合计</td>      <td>549,289,343,613</td>      <td>565,064,652,788</td>    </tr>    <tr>      <td>股东权益股本六 、32其他权益工具六 、33其中 ：永续次级债券资本公积六 、34其他综合收益六 、35盈余公积六 、36一般风险准备六 、37未分配利润六 、38</td>      <td>4,827,256,86816,400,000,00016,400,000,00039,515,216,714431,489,7311,856,673,1236,804,641,31929,352,829,428</td>      <td>4,827,256,8688,500,000,0008,500,000,00039,531,886,525(828,441,057)1,392,448,7975,470,061,17525,528,908,966</td>    </tr>  </tbody></table>'''
df = pd.read_html(htmls)
```

### Issue Description

read_html blocks for a very long time, maybe more than 1 hour. I cannot wait for it to stop

### Expected Behavior

read_html returns success, failure, or time out, instead of blocks

### Installed Versions

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.9.16.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936
pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 23.0.1
Cython           : 0.29.33
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : 4.12.0
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : 2023.3.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.1
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

**Comment by rhshadrach** [comment] 2023-05-12 09:39
May be a duplicate of #52619

**Comment by topper-123** [comment] 2023-05-14 10:01
I tried this with the proposed solution fro [here](https://github.com/pandas-dev/pandas/issues/52619#issuecomment-1531636799) and the result cae back instantaneous:

```
>>> pd.read_html(htmls)[0]
0                                          负债及股东权益附注                                       2022年 12月31日                                       2021年 12月31日
1  负债应付短期融资款六 、19拆入资金六 、20交易性金融负债六 、21衍生金融负债六 、4卖...  18,551,991,95760,846,018,71445,203,291,77711,3...  2298985748951477278678389267866841813400750816...
2                                               负债合计                                       549289343613                                       565064652788
3  股东权益股本六 、32其他权益工具六 、33其中 ：永续次级债券资本公积六 、34其他综合收...  4827256868164000000001640000000039515216714431...  4,827,256,8688,500,000,0008,500,000,00039,531,...
```

**Comment by mroeschke** [comment] 2023-11-21 18:51
Closing a a duplicate

**Closed by mroeschke** 2023-11-21 18:51 UTC
Labels: Bug, Performance, Duplicate Report, IO HTML
