### ISSUE TITLE
ImportError: No module named 'pandas.plotting'

### ISSUE THREAD

**Issue by zhangdm** [pandas-dev/pandas#17850] opened 2017-10-12 07:49 UTC
#### Code Sample, a copy-pastable example if possible

```python

from pandas.plotting import scatter_matrix
df = pd.DataFrame(np.random.randn(1000, 4), columns=['a', 'b', 'c', 'd'])
scatter_matrix(df,alpha=0.2,figsize=(6, 6),diagonal='kde')
plt.show()
```
#### Problem description
ImportError: No module named 'pandas.plotting'

the answer is :　 from pandas.tools.plotting import scatter_matrix

the document have some mistake ,the link is : http://pandas.pydata.org/pandas-docs/stable/visualization.html

**Comment by TomAugspurger** [comment] 2017-10-12 11:11
What's the actual traceback, and what version of pandas to you have? That was moved recently, and you probably have an older version.

**Comment by jreback** [comment] 2017-10-26 10:06
closing as cannot reproduce

**Closed by jreback** 2017-10-26 10:06 UTC
Labels: Can't Repro
