### ISSUE TITLE
Str.encode('base64') turns arrays of strings to NaN and fails on byte strings

### ISSUE THREAD

**Issue by bwanaaa** [pandas-dev/pandas#32049] opened 2020-02-17 04:16 UTC
#### Code Sample, a copy-pastable example if possible
Using pandas 1.0.1 and python 3.7
Using a text file consisting of words separated by carriage returns named sampleTEXT.txt
```
import base64
import numpy as np
import pandas as pd
words = pd.read_table("sampleTEXT.txt",names=['word'],header=None)
words.head()
---      word
---------------
---0    difference
---1    where
---2    mc
---3    is
---4    the
---
---

b64words = words.word.str.encode('base64')
print(b64words)
```
#### Problem description
output is this
```
int(b64words)

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
999995   NaN
999996   NaN
999997   NaN
999998   NaN
999999   NaN
Name: word, Length: 1000000, dtype: float64
```

#### Expected Output
base64 encoding of the words

similar to bug 22613
https://github.com/pandas-dev/pandas/issues/22613

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-28-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.1
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.2.0.post20200209
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by Mxchaeltrxn** [comment] 2020-02-19 01:40
Hey I'd be happy to take this one on

**Comment by devjeetr** [comment] 2020-02-26 15:44
take

**Comment by joaoe** [comment] 2020-04-29 22:52
This problem is exactly the same as described by https://github.com/pandas-dev/pandas/issues/22613 . See my comment in that bug.

In this particular case, if you try the following snippet:
```
>>> "a".encode('base64')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```
That exception is what causes the except block in `pandas.core.strings._map` to be executed and therefore replaces all your strings with `nan`.

I guess someone should add another regex to the except block to check for `^[0-9_a-zA-Z]+\(\) argument [0-9]+ must be`.

**Comment by jreback** [comment] 2020-04-29 23:43
duplicate of #22613

**Closed** 2020-04-29 23:43 UTC
Labels: Bug, Duplicate, Missing-data, Strings
