### ISSUE TITLE
is_sequence is too aggressive for determining how to print

### ISSUE THREAD

**Issue by jnothman** [pandas-dev/pandas#22333] opened 2018-08-14 05:56 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

class Foo(object):
    def __len__(self):
        return 3

    def __iter__(self):
        return iter([1, 2, 3])


class Bar(Foo):
    def __repr__(self):
        return "Hello world"

print(pd.DataFrame([[Foo()],
                    [Bar()]]))
```
Expected output:
```
                                      0
0  <__main__.Foo object at 0x1045b79e8>
1                           Hello world
```
Actual output:
```
           0
0  (1, 2, 3)
1  (1, 2, 3)
```

#### Problem description

`pandas.core.dtypes.inference.is_sequence` appears designed to determine whether an object should be converted directly into a Series, etc. But `is_sequence` is also applied to determine how to `pprint_thing`: if an object in a cell is capable of `len` and `iter` and is not a string-like, [then it is pprinted as a sequence](https://github.com/pandas-dev/pandas/blob/ffae158749c9b72720a7fe3295d323082a5fe420/pandas/io/formats/printing.py#L213-L218). This means the user cannot see the type of the sequence, even when a custom `__repr__` or `__str__` is defined.

This surprised me in the context of putting [`sklearn.model_selection.GridSearchCV`](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html)'s `cv_results_` into a DataFrame and displaying it in Jupyter. If one of the parameters is an ensemble estimator, the elements of the ensemble are displayed, obscuring the fact that the parameter is actually a [GradientBoostingClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html) or [RandomForestClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) instance, for example.

I think appropriate behaviour would be to use a more strict version of `is_sequence` in `pprint_thing`, which has custom printing only for standard types and their subclasses that do not override `__repr__`.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.2.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_AU.UTF-8
LOCALE: en_AU.UTF-8

pandas: 0.23.4
pytest: 3.4.0
pip: 18.0
setuptools: 37.0.0
Cython: 0.27.3
numpy: 1.14.1
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 5.1.0
sphinx: 1.6.2
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2018.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: 2.5.5
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.8.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.3
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jorisvandenbossche** [comment] 2018-08-14 09:04
Related to (possibly duplicate of) https://github.com/pandas-dev/pandas/issues/17695 and https://github.com/pandas-dev/pandas/issues/18843 

I would also like to see this solved, but not sure what the best way would be to detect when to use our custom printer (that eg limits the length) and when not (a while ago that I looked into it)

**Comment by jnothman** [comment] 2018-08-14 09:40
I assume the reason to special-case sequences is that repr of a large
container can be slow. I would think that unless an object was a standard
collection class or had registered a custom pprint, __repr__/__str__ should
be used. But you are right, this is a duplicate.

**Comment by simonjayhawkins** [comment] 2019-06-24 09:46
> But you are right, this is a duplicate.

labelled as duplicate and closing.

**Closed by simonjayhawkins** 2019-06-24 09:46 UTC
Labels: Duplicate, Output-Formatting
