### ISSUE TITLE
AssertionError on groupby max

### ISSUE THREAD

**Issue by trimbilrepo** [pandas-dev/pandas#41183] opened 2021-04-27 16:46 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

def get_data():
    # request data from the server
    return data

datas = get_data()
#datas consist of 2195 rows and 22 column
df = pd.DataFrame(datas)
total = df.groupby('userid').max()['point'].sum()
print(f"sum all point: {total}")

Traceback (most recent call last):
  File "playground-test.py", line 15, in <module>
    total = df.groupby('userid').max()['point'].sum()
  File "/home/playground/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 1560, in max
    numeric_only=numeric_only, min_count=min_count, alias="max", npfunc=np.max
  File "/home/playground/.local/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 1001, in _agg_general
    how=alias, alt=npfunc, numeric_only=numeric_only, min_count=min_count,
  File "/home/playground/.local/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 1022, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only, min_count=min_count
  File "/home/playground/.local/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 1135, in _cython_agg_blocks
    assert len(locs) == result.shape[1]
AssertionError
```

```python
import pandas as pd

def get_data():
    # request data from the server
    return data

datas = get_data()
#let's copy dataframe and only include 2 column
df_copy = df[['userid','point']].copy()
total = df_copy.groupby('userid').max()['point'].sum()
print(f"sum all point: {total}")

64511636

```

#### Problem description

`groupby` `max` function on dataframe that consist of 22 column does make error with AssertionError. However, if I tried to made smaller dataframe with 2 column. It does work.
I am on Pandas 1.1.5 and I dont know why, I can't upgrade to 1.2.4

```linux
$pip3 install pandas --upgrade
Requirement already satisfied: pandas in /home/playground/.local/lib/python3.6/site-packages (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib64/python3.6/site-packages (from pandas) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in /home/playground/.local/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
```
```linux
$$ pip3 install pandas==1.2.4
ERROR: Could not find a version that satisfies the requirement pandas==1.2.4
ERROR: No matching distribution found for pandas==1.2.4
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1160.24.1.el7.x86_64
Version          : #1 SMP Thu Apr 8 19:51:47 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.utf-8≈
LANG             : en_US.utf-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.1
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : 1.4.7
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by mzeitlin11** [comment] 2021-04-27 16:55
Thanks for the report @trimbilrepo. Could you please try to shrink the example down into something reproducible (something copy-pastable, including the data). For example, does it fail with just 1 row?

**Comment by trimbilrepo** [comment] 2021-04-28 09:02
let me try.
```python
# reproduce the data with only 1 row but the same total column
datas = [{'device': 'Android', 'point': 22028, 'friends': 1848, 'geo_loc': 'None', 'geo_loc_str': 'None', 'has_media': 0, 'id': 'msg-1385695144209354761', 'in_reply_to_userid': 2598677, 'is_read': 0, 'listed_count': 8, 'name': 'Roberto', 'name_str': 'Roberto', 'profile_img': 'https://subdomain.domain.com/profile_images/71353910754710233089/71353910754710233089.jpg', 'count': 0, 'reply_count': 31, 'msg_count': 79, 'screen_name': 'Roberto DeGino', 'avg_val': -0.5106, 'message': 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.', 'msg_dtm': ['2021-04-23T20:40:42Z'], 'msg_id': 1385695144209354761, 'type': 'message', 'unix': 1619185242000, 'userid': 71353910754710233089, 'verified': 0, 'raw_data': '', 'likes_count': 378, '_version_': 1698128823273390080, 'media_type': 0, 'media_url': 0, 'domain': [], 'mention': []}]

df = pd.DataFrame(datas)
total = df.groupby('userid').max()['point'].sum()
print(f"sum all point: {total}")

>>> sum all point: 22028
```
its work with one row.
let's try loop, to find out total row that make it break
```python
for length in range(1,len(datas)+1):
	cp_datas = datas[:length]
	df = pd.DataFrame(cp_datas)
	try:
		total = df.groupby('userid').max()['followers'].sum()
	except Exception as e:
		# let me know when it brakes
		print(f"Attempt with data length: {length}")
>>> Attempt with data length: 213
```
so it break with the dataframe consist of 213 rows
however, it does not break when I used repeated data
```python
data = {'device': 'Android', 'point': 22028, 'friends': 1848, 'geo_loc': 'None', 'geo_loc_str': 'None', 'has_media': 0, 'id': 'msg-1385695144209354761', 'in_reply_to_userid': 2598677, 'is_read': 0, 'listed_count': 8, 'name': 'Roberto', 'name_str': 'Roberto', 'profile_img': 'https://subdomain.domain.com/profile_images/71353910754710233089/71353910754710233089.jpg', 'count': 0, 'reply_count': 31, 'msg_count': 79, 'screen_name': 'Roberto DeGino', 'avg_val': -0.5106, 'message': 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.', 'msg_dtm': ['2021-04-23T20:40:42Z'], 'msg_id': 1385695144209354761, 'type': 'message', 'unix': 1619185242000, 'userid': 71353910754710233089, 'verified': 0, 'raw_data': '', 'likes_count': 378, '_version_': 1698128823273390080, 'media_type': 0, 'media_url': 0, 'domain': [], 'mention': []}

for length in range(1,2150):
	datas = []
	for x in range(0,length):
		datas.append(data)
	df = pd.DataFrame(datas)
	try:
		total = df.groupby('userid').max()['point'].sum()
	except Exception as e:
		# let me know when it brakes
		print(f"Error, Attemp with data length: {length}")
		raise e
```
using original data, cut it until row 214
```python
df = pd.DataFrame(datas[:214])
>>> AssertionError
```
```python
df = pd.DataFrame(datas[:210])
>>> its work
df = pd.DataFrame(datas[210:220])
>>> its work
```
I dont know. 
I can provide you the full data if you need it. just tell me where I should to email it

**Comment by mzeitlin11** [comment] 2021-04-28 15:44
Can you please test on the master branch? There have been many groupby-related fixes since 1.1.5, so very possible it's been fixed. If you're not sure how to do that, you could edit your original example and attach a csv with the data (preferably the smallest chunk that still fails) and I can test on master

**Comment by phofl** [comment] 2021-04-28 20:26
Yeah, plese test at least on 1.2.4

I can neither reproduce on master nor on 1.1.5

**Comment by trimbilrepo** [comment] 2021-04-30 06:53
@mzeitlin11 I will try to build manually from source by master branch. Will update when its done
@phofl  I dont know why, but pip3 install pandas, doesnt bring me to the newer version of pandas. still stuck with 1.1.5
I have already upgrade the pip also. but no luck

**Comment by asishm** [comment] 2021-05-02 16:16
pandas 1.2+ supports python 3.7.1 and higher.

https://pandas.pydata.org/docs/whatsnew/v1.2.0.html#increased-minimum-version-for-python

**Comment by jbrockmendel** [comment] 2021-06-24 02:12
@trimbilrepo any progress on getting a copy/pasteable example?

**Comment by mroeschke** [comment] 2021-08-20 02:39
Looks like the team need more information from this report to proceed, so closing in the meantime. Happy to reopen if we can get a more copy/pasteable example

**Closed by mroeschke** 2021-08-20 02:39 UTC
Labels: Groupby, Numeric Operations, Needs Info

**Comment by AgustinPardo** [comment] 2021-08-31 15:14
Same issue with groupby min on 1.1.5 version!

**Comment by AgustinPardo** [comment] 2021-08-31 16:11
> Same issue with groupby min on 1.1.5 version!

I solve it as @trimbilrepo mention, using less columns of the dataframe.

**Comment by mzeitlin11** [comment] 2021-08-31 18:08
> Same issue with groupby min on 1.1.5 version!

@AgustinPardo can you please check if the issue occurs on the latest version (1.3.2)? And if so, would you mind posting a minimal example here?

**Comment by AgustinPardo** [comment] 2021-08-31 19:29
@mzeitlin11 I am using python:3.6.2 so pandas 1.1.5 is the last version I can use.

**Comment by mzeitlin11** [comment] 2021-09-03 00:27
Ok, thanks. Since the original issue couldn't be reproduced on later versions, hopefully yours would work too
