### ISSUE TITLE
Why data in DataFrame(data) can be a generator but not an iterator?

### ISSUE THREAD

**Issue by holymonson** [pandas-dev/pandas#21783] opened 2018-07-07 02:53 UTC
`Generator` inherits from `Iterator`, `Iterator` inherits from `Iterable`. And `list([iterable])` takes an `Iterable` as argument.

 So, why `data` in `DataFrame(data)` can't be an `Iterable`?

https://github.com/pandas-dev/pandas/blob/620abc403d371446afe38fc1e63f0d90ea27b80a/pandas/core/frame.py#L381-L383
https://github.com/pandas-dev/pandas/blob/620abc403d371446afe38fc1e63f0d90ea27b80a/pandas/core/frame.py#L407-L408

**Comment by TomAugspurger** [comment] 2018-07-07 11:18
Duplicate of https://github.com/pandas-dev/pandas/issues/2193

I think we'd be open to making this work (by consuming the Iterable into a list).

**Closed by TomAugspurger** 2018-07-07 11:18 UTC
