### ISSUE TITLE
IOError: File "/home/jasims/Documents/sample.csv" does not exist

### ISSUE THREAD

**Issue by Pabla007** [pandas-dev/pandas#25560] opened 2019-03-06 03:07 UTC
#### Code Sample, a copy-pastable example if possible

```python code 

import ipywidgets as widgets
import fileplot
path=widgets.Text(
    value=raw_input("Enter the Path Csv File You Want to Plot here :  "),
    #placeholder="File Path",
    #descrition="String:",
    #disabled=False  
)

button=widgets.Button(
    description='Plot',
    disabled=False,
    button_style='', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click me',
    icon='check'
)

def on_button_clicked(b):
    #fileplot.load_file(np)
    fileplot.load_file(path.value)
 
display(path,button)
button.on_click(on_button_clicked)

```
#### Problem description

Enter the Path Csv File You Want to Plot here :  "/home/jasims/Documents/sample.csv"

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-5-d33edd47674b> in on_button_clicked(b)
     26 def on_button_clicked(b):
     27     #fileplot.load_file(np)
---> 28     fileplot.load_file(path.value)
     29 
     30 display(path,button)

/home/jasims/Downloads/starkit/starkit/filebox/fileplot.pyc in load_file(filename)
      6 
      7 def load_file(filename):
----> 8         df=pd.read_csv(filename, sep="delimeter", header=None)
      9         df.plot(x=df.columns[0],y=df.columns[1])
     10         plt.show()

/home/jasims/anaconda3/envs/starkit/lib/python2.7/site-packages/pandas/io/parsers.pyc in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    676                     skip_blank_lines=skip_blank_lines)
    677 
--> 678         return _read(filepath_or_buffer, kwds)
    679 
    680     parser_f.__name__ = name

/home/jasims/anaconda3/envs/starkit/lib/python2.7/site-packages/pandas/io/parsers.pyc in _read(filepath_or_buffer, kwds)
    438 
    439     # Create the parser.
--> 440     parser = TextFileReader(filepath_or_buffer, **kwds)
    441 
    442     if chunksize or iterator:

/home/jasims/anaconda3/envs/starkit/lib/python2.7/site-packages/pandas/io/parsers.pyc in __init__(self, f, engine, **kwds)
    785             self.options['has_index_names'] = kwds['has_index_names']
    786 
--> 787         self._make_engine(self.engine)
    788 
    789     def close(self):

/home/jasims/anaconda3/envs/starkit/lib/python2.7/site-packages/pandas/io/parsers.pyc in _make_engine(self, engine)
   1012     def _make_engine(self, engine='c'):
   1013         if engine == 'c':
-> 1014             self._engine = CParserWrapper(self.f, **self.options)
   1015         else:
   1016             if engine == 'python':

/home/jasims/anaconda3/envs/starkit/lib/python2.7/site-packages/pandas/io/parsers.pyc in __init__(self, src, **kwds)
   1706         kwds['usecols'] = self.usecols
   1707 
-> 1708         self._reader = parsers.TextReader(src, **kwds)
   1709 
   1710         passed_names = self.names is None

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

IOError: File "/home/jasims/Documents/sample.csv" does not exist

i have tried changing the file location and name but no luck i have given full paht than also same error

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
![image](https://user-images.githubusercontent.com/35897183/53853386-43457280-3feb-11e9-99cf-a13afe907c2c.png)

</details>

**Comment by TomAugspurger** [comment] 2019-03-06 12:51
Pandas is saying that it can't find the file. I'm guessing you need to check the path.

Closing, since this is likely to not be a bug.

**Closed by TomAugspurger** 2019-03-06 12:51 UTC

**Comment by Pabla007** [comment] 2019-03-06 13:10
But i has given the right path. 
@TomAugspurger help me with the error.

**Comment by WillAyd** [comment] 2019-03-06 16:18
Also looks like it could be an issue with your third party fileplot package. The traceback of that is certainly strange (ex: `sep="delimiter"`). 

Agreed this is almost assuredly not a pandas bug. Try opening up an issue with whomever maintains that package. If you can reproduce the error using pandas **alone** feel free to post a separate issue with that information
