### ISSUE TITLE
DataFrame.dropna() fill Data and interpolating. Why?

### ISSUE THREAD

**Issue by rickymal** [pandas-dev/pandas#25357] opened 2019-02-17 22:47 UTC
As we can see, the dropna() Method drop rows with value and add value from NaN rows. I don't undestood why.

between  1990-04 and 1990-08 u can see that we have value. But the dropna Method drop theses rows, and they are float64 value. And the dropna() method fill 1990-09 and 1990-10 with value that didn't exist.

![image](https://user-images.githubusercontent.com/25715921/52920577-ba40f280-32ec-11e9-8f09-2eb89553d3ba.png)

When I plot de graphic, The original Looks Like:
![image](https://user-images.githubusercontent.com/25715921/52920801-84513d80-32ef-11e9-89cb-ee2e38cab074.png)

but when I use dropna:

![image](https://user-images.githubusercontent.com/25715921/52920882-35f06e80-32f0-11e9-9118-6bc7bd1b0e7f.png)

EDIT:
The output.show_versions:
![image](https://user-images.githubusercontent.com/25715921/53060095-fe242b00-3497-11e9-9564-1bc3fa33545c.png)

**Comment by gfyoung** [comment] 2019-02-18 06:12
@rickymal : Thanks for reporting this!  Could you update your original issue with the following:

* The output `pandas.show_versions`
* The code used to generate the `DataFrame`

**Comment by jorisvandenbossche** [comment] 2019-02-18 13:33
The `dropna` function will drop a row when there is *any* NaN in the columns. So it might be that one of the other columns contained a NaN for that row.

@rickymal In general, it is more useful for a possible bug report to include actual code (text) instead of images of it (unless it is as illustration of the plotting of course, but then it should still accompany text code)

**Comment by rickymal** [comment] 2019-02-20 01:44
I pretty sure that the problem is something wrong that i made. I'm not a good programmer with pandas yet. I'll put  the code right now

**Comment by jorisvandenbossche** [comment] 2019-02-20 10:30
Which new values?

**Comment by jorisvandenbossche** [comment] 2019-03-04 13:47
@rickymal closing this issue, as it is not clear what the problem is. If you still think there is a bug, please provide a reproducible example, and we are happy to re-open the issue.

**Closed by jorisvandenbossche** 2019-03-04 13:47 UTC
Labels: Missing-data, Needs Info
