### ISSUE TITLE
ENH: Allow to group by an empty list

### ISSUE THREAD

**Issue by tomjaguarpaw** [pandas-dev/pandas#35366] opened 2020-07-21 14:29 UTC
#### Is your feature request related to a problem?

Yes, I cannot group by an empty list.

#### Describe the solution you'd like

I would like to be able to group by an empty list of columns.  At the moment I get an error.

```
>>> DataFrame([{"a":1, "b":2}, {"a":3, "b":4}]).groupby([]).agg(aagg=('a', 'sum'), bagg=('b', 'sum'))
Traceback (most recent call last):
...
ValueError: No group keys passed!
```

I would prefer to see

```
>>> DataFrame([{"a":1, "b":2}, {"a":3, "b":4}]).groupby([]).agg(aagg=('a', 'sum'), bagg=('b', 'sum'))
aagg  bagg
   4     6
```

which would generalise grouping by a non-empty list, which works fine.

```
>>> DataFrame([{"a":1, "b":2}, {"a":3, "b":4}]).groupby(["a", "b"]).agg(aagg=('a', 'sum'), bagg=('b', 'sum'))
     aagg  bagg
a b
1 2     1     2
3 4     3     4
```

```
>>> DataFrame([{"a":1, "b":2}, {"a":3, "b":4}]).groupby(["a"]).agg(aagg=('a', 'sum'), bagg=('b', 'sum'))
   aagg  bagg
a
1     1     2
3     3     4
```

It seems to me this would be reasonable behaviour. Is there a particular reason it is not supported?

#### API breaking implications

None that I know of.

#### Describe alternatives you've considered

A partial workaround is to cook up a grouping function for simulating the behaviour I want, but this lacks uniformity.

```
>>> DataFrame([{"a":1, "b":2}, {"a":3, "b":4}]).groupby(lambda _: "Only row").agg(aagg=('a', 'sum'), bagg=('b', 'sum'))
          aagg  bagg
Only row     4     6
```

But I don't really want `"Only row"` to be there.  I just want

```
>>> DataFrame([{"a":1, "b":2}, {"a":3, "b":4}]).groupby([]).agg(aagg=('a', 'sum'), bagg=('b', 'sum'))
aagg  bagg
   4     6
```

**Comment by gurukiran07** [comment] 2020-07-21 15:02
If you don't want to groupby then you can use `pandas.DataFrame.agg` 
```
df.agg({'a':'sum', 'b':'sum'}) # gives Series as output, if DataFrame is needed use `to_frame`
```
But this doesn't support *named aggergation* AFAIK.

**Comment by simonjayhawkins** [comment] 2020-07-21 15:04
> It seems to me this would be reasonable behaviour. Is there a particular reason it is not supported?

seems reasonable. PRs and contributions welcome.

may want to redo the OP and use the feature request template (available when opening issue but repeated in details below)

<details>
#### Is your feature request related to a problem?

[this should provide a description of what the problem is, e.g. "I wish I could use pandas to do [...]"]

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`DataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```
</details>

**Comment by simonjayhawkins** [comment] 2020-07-21 15:11
> But this doesn't support _named aggergation_ AFAIK.

1.1.0 gives
```
>>> pd.__version__
'1.1.0rc0+2.g3e88e170a'
>>>
>>> df = pd.DataFrame([{"a": 1, "b": 2}, {"a": 3, "b": 4}])
>>> df
   a  b
0  1  2
1  3  4
>>>
>>> df.agg(aagg=("a", "sum"), bagg=("b", "sum"))
        a    b
aagg  4.0  NaN
bagg  NaN  6.0
>>>
```

but 1.0.1 raises `TypeError: aggregate() missing 1 required positional argument: 'func'`

The output seems iffy. not looked in detail. This may be an issue with 1.1.0.

**Comment by tomjaguarpaw** [comment] 2020-07-21 15:14
> may want to redo the OP and use the feature request template (available when opening issue but repeated in details below)

I see. I didn't realise that was to be taken as the literal structure. I have edited my OP.

> 1.1.0 gives

Interesting. That output looks like a bug to me. I am on 1.0.3.

**Comment by tomjaguarpaw** [comment] 2020-07-21 15:18
> If you don't want to group by anything (why use DataFrame.groupby in the first place) then you can use pandas.DataFrame.agg

Firstly because allowing an empty list would be more uniform (perhaps it's a parameter passed in my someone else) and secondly, that's what I tried first, but it doesn't support what I want (what I think you refer to as "named aggregation"):

```
>>> DataFrame([{"a":1, "b":2}, {"a":3, "b":4}]).agg(aagg=('a', 'sum'), bagg=('b', 'sum'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: aggregate() missing 1 required positional argument: 'func'
```

**Comment by WillAyd** [comment] 2020-07-21 15:31
Generic support for named aggregations was added very recently in #29116 so I think you can achieve the result you want without the groupby on master, though to @simonjayhawkins point maybe there are sum bugs to be worked out

FWIW I am -1 on changes to groupby here as I agree with @gurukiran07 comment that agg should generically handle

**Comment by gurukiran07** [comment] 2020-07-21 15:46
Here's a related question on SO [How to do a groupby on an empty set of columns pandas](https://stackoverflow.com/q/11492215/12416453) where [Wes Mckinney posted](https://stackoverflow.com/a/11493108/12416453)
> Having an analogous `DataFrame.aggregate` method is a good idea. 

This may be one of the reasons why  `DataFrame.agg` and `Series.agg` are in API.

As @WillAyd and @simonjayhawkins pointed out named aggregations now allowed with `Series.agg`, `DataFrame.agg` (Though buggy as of now) 

> it's a parameter passed in my someone else

A workaround can be:
```
if group_list:
    # call `df.groupby(group_list).agg(...)`
else:
    # call `df.agg(...)`
```

**Comment by simonjayhawkins** [comment] 2020-07-21 15:47
> Generic support for named aggregations was added very recently in #29116 so I think you can achieve the result you want without the groupby on master, though to @simonjayhawkins point maybe there are sum bugs to be worked out

#29116 didn't add documentation on the enhancement (one-line whatsnew add later in #35220). I'm not sure that it's a bug, the tests appear this was intentional. imo the output should maybe be a Series, the output above is confusing.

**Comment by tomjaguarpaw** [comment] 2020-07-21 15:57
> A workaround can be

Sure, but why work around it when it's a perfectly coherent thing for the pandas API to support?

**Comment by douglas-raillard-arm** [comment] 2021-01-14 11:41
+1 for that feature, it currently makes using pandas as a backend of another library difficult.

I'm currently writing functions that expose an optional `group_on` parameter to the user, which obviously defaults to `None`. In order to support that, I'm forced to have a separate path in my code, with different data types (`GroupBy` object on one side, `DataFrame` on the other). Given the subtle differences of various same-looking APIs in pandas, this is a recipe for bug, in addition to gratuitous code complexity. For example, `DataFrame.first()` is totally different from `GroupBy.first()`. Similarly, `GroupBy` does not support `iat` etc.

**Comment by elashrry** [comment] 2023-09-08 16:12
I found myself in the same situation where I wanted `groupby` to have a uniform behaviour even if the user passed an empty array. I dived in the base code and found that a one-line change can allow this behaviour and still passes all the tests, except for the test for not accepting an empty array, of course. I created the PR #55068 with my changes. Please, let me know if it works.

**Comment by rhshadrach** [comment] 2023-09-09 14:34
> FWIW I am -1 on changes to groupby here

I am -1 as well: https://github.com/pandas-dev/pandas/pull/55068#issuecomment-1712524923

From that PR, users can do this if they want without much effort:

```
if len(keys) == 0:
    keys = np.zeros(len(df))
result = df.grouby(keys)...
```

**Comment by mroeschke** [comment] 2023-11-21 17:50
Since there hasn't been much support for this, closing

**Closed by mroeschke** 2023-11-21 17:50 UTC
Labels: Enhancement, Groupby, Closing Candidate
