### ISSUE TITLE
focus/start enhancing performance section within pandas/numpy

### ISSUE THREAD

**Issue by hayd** [pandas-dev/pandas#8178] opened 2014-09-05 02:24 UTC
start of enhancing performance section should begin with tips for speeding up pandas, e.g. no apply, vectorization, pandas methods etc.

Initially I put in:

> This tutorial assumes you have refactored as much as possible in python, for example trying to remove for loops and making use of numpy vectorization, it’s always worth optimising in python first.

I think this should be more strongly worded.

_see [this question](http://stackoverflow.com/q/25676157/1240268), user should not jump to cython!_

**Comment by jreback** [comment] 2017-05-10 11:04
dupe of #16310

**Closed by jreback** 2017-05-10 11:04 UTC
Labels: Difficulty Novice, Docs, Performance
