### ISSUE TITLE
read_sas column limit

### ISSUE THREAD

**Issue by binaryc0de** [pandas-dev/pandas#24794] opened 2019-01-16 04:29 UTC
I get an index error for reading any sas file (sas7bdat) over 2047 columns wide.  This issue can be reproduced simply by generating a 2048 column width file in excel, importing into SAS and writing it back out as sas7bdat file then trying to read with read_sas.

[testdata.zip](https://github.com/pandas-dev/pandas/files/2788506/testdata.zip)

IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by TomAugspurger** [comment] 2019-01-16 12:59
Can you post the full traceback?

**Comment by gfyoung** [comment] 2019-01-23 05:18
@binaryc0de : Would it be possible to share such a file in the issue?  You can upload it as a `.txt` file on GitHub if you like.  That would make it easier for people to contribute or debug this issue (i.e. they can just download the file instead of having to go through the steps of creating one).

**Comment by binaryc0de** [comment] 2019-01-23 17:49
Sure.  


[testdata.txt](https://github.com/pandas-dev/pandas/files/2788494/testdata.txt)

**Comment by binaryc0de** [comment] 2019-01-23 17:52
Here's the sas version of that file (exported via SAS)
[testdata.zip](https://github.com/pandas-dev/pandas/files/2788506/testdata.zip)

**Comment by gfyoung** [comment] 2019-01-23 18:05
@binaryc0de : Thanks!  I moved your file uploads to the issue description.  I'll take a look.

**Comment by gfyoung** [comment] 2019-01-26 01:35
@binaryc0de : Finally got around to this...I can't reproduce this issue.  I can in read the file just fine.  Can you provide the output from `pd.get_versions` ?

**Comment by wwpokenet** [comment] 2019-02-20 12:39
Same issue:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-e2b7d16ce4c7> in <module>
      1 import pandas as pd
----> 2 data = pd.read_sas('testdata.sas7bdat')

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sas/sasreader.py in read_sas(filepath_or_buffer, format, index, encoding, chunksize, iterator)
     59         reader = SAS7BDATReader(filepath_or_buffer, index=index,
     60                                 encoding=encoding,
---> 61                                 chunksize=chunksize)
     62     else:
     63         raise ValueError('unknown SAS format')

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sas/sas7bdat.py in __init__(self, path_or_buf, index, convert_dates, blank_missing, chunksize, encoding, convert_text, convert_header_text)
     96 
     97         self._get_properties()
---> 98         self._parse_metadata()
     99 
    100     def close(self):

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sas/sas7bdat.py in _parse_metadata(self)
    276                 raise ValueError(
    277                     "Failed to read a meta data page from the SAS file.")
--> 278             done = self._process_page_meta()
    279 
    280     def _process_page_meta(self):

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sas/sas7bdat.py in _process_page_meta(self)
    282         pt = [const.page_meta_type, const.page_amd_type] + const.page_mix_types
    283         if self._current_page_type in pt:
--> 284             self._process_page_metadata()
    285         return ((self._current_page_type in [256] + const.page_mix_types) or
    286                 (self._current_page_data_subheader_pointers is not None))

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sas/sas7bdat.py in _process_page_metadata(self)
    312                 self._get_subheader_index(subheader_signature,
    313                                           pointer.compression, pointer.ptype))
--> 314             self._process_subheader(subheader_index, pointer)
    315 
    316     def _get_subheader_index(self, signature, compression, ptype):

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sas/sas7bdat.py in _process_subheader(self, subheader_index, pointer)
    382             raise ValueError("unknown subheader index")
    383 
--> 384         processor(offset, length)
    385 
    386     def _process_rowsize_subheader(self, offset, length):

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/io/sas/sas7bdat.py in _process_format_subheader(self, offset, length)
    582         col.label = column_label
    583         col.format = column_format
--> 584         col.ctype = self.column_types[current_column_number]
    585         col.length = self._column_data_lengths[current_column_number]
    586 

IndexError: index 1 is out of bounds for axis 0 with size 1

`pd.show_versions:`

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.4.final.0
python-bits: 64
OS: Darwin
OS-release: 18.2.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.21.0
pytest: 4.0.1
pip: 18.1
setuptools: 40.6.2
Cython: None
numpy: 1.15.4
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.1.2
openpyxl: None
xlrd: 1.1.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

**Comment by Spark-MC-01** [comment] 2019-07-10 06:40
same issue with python 3.6 pandas 0.22.0

**Comment by mroeschke** [comment] 2019-11-02 00:31
Guessing this was fixed with a recent update as the issue was in older versions (0.21 and 0.22). Closing

**Closed by mroeschke** 2019-11-02 00:31 UTC
Labels: Can't Repro, IO SAS

**Comment by LoganBitszer** [comment] 2020-10-29 19:40
Same issue: python 3.8.5, pandas 1.1.3
