### ISSUE TITLE
Feature Request: symbol datatype (for string compression)

### ISSUE THREAD

**Issue by samkennerly** [pandas-dev/pandas#14819] opened 2016-12-07 22:02 UTC
Should pandas have a  _Symbol_ datatype for strings which are frequently re-used?

For example, consider a table of stock trades with columns ['Timestamp','Price','Size','StockSymbol']. Suppose there are 10 million trades, but only 500 different stock symbols. Instead of storing 10 million strings, we could fill the 'StockSymbol' column with integers 0-499 where 0 represents AAPL, 1 represents AMZN, etc.

The _Symbol_ type in Ruby, Scala, and Q does this compression/expansion automatically. It's a big memory saver in big tables, and _Symbol_ comparison can be much faster than string comparison.

I often use `.astype('category')` for string compression in pandas. But at a talk I saw recently, @wesm suggested this might not be a great idea. I've definitely caused several confusing problems by abusing categoricals this way: comparing two columns with different levels, appending rows with new symbols, wrongly assuming `sort_values()` will sort symbols lexicographically, etc.

Related question: Without a _Symbol_ datatype, is there a consensus on best practice for storing repetitive strings in a Series or DataFrame? Should we leave them as `Object` type? Compress them as un-ordered categoricals? Do something else I haven't thought of?

**Comment by jreback** [comment] 2016-12-07 22:30
duplicate of https://github.com/pandas-dev/pandas/issues/8640

simply use ``category``, which works pretty work for this right now. Yes its not excatly the same thing, but practicality does beat purity (for the time being).

**Closed by jreback** 2016-12-07 22:30 UTC

**Comment by wesm** [comment] 2016-12-07 23:05
We've been discussing the idea of having dictionery-encoded strings (effectively what Symbol is) internally in pandas 2.0 -- see https://pandas-dev.github.io/pandas2/strings.html

**Comment by samkennerly** [comment] 2016-12-15 04:14
Oops, sorry about the duplicate and thanks for the links. I think a `pandas.string` type with built-in dictionary encoding sounds pretty cool.
