### ISSUE TITLE
BUG: pd.Series.rename does not return None with inplace=True

### ISSUE THREAD

**Issue by Omerdan03** [pandas-dev/pandas#42481] opened 2021-07-11 11:56 UTC
- [ X] I have checked that this issue has not already been reported.

- [ X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
ser = pd.Series([1,2,3], name='ser1')
f = ser.rename('ser2', inplace=True)

```

#### Problem description

f should be None like other inplace functionality.
instead f is Series object.

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-59-generic
Version          : #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.5
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : 6.2.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 1.3.9
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.4
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.53.1

**Comment by Omerdan03** [comment] 2021-07-11 12:05
![image](https://user-images.githubusercontent.com/57575138/125194320-6c303f00-e259-11eb-903b-b441c9a58d26.png)

**Comment by mzeitlin11** [comment] 2021-07-11 15:04
Thanks for reporting this @Omerdan03! If you (or anyone else) is interested in contributing a fix, looks like the issue is here: https://github.com/pandas-dev/pandas/blob/844b388e34996f35b6f9e0aeb58c6fce81118168/pandas/core/series.py#L1750-L1763

Hopefully just returning `ser` only if `inplace=False` would fix this and not break anything else

**Comment by Gdango** [comment] 2021-07-12 04:51
Hello, I am new here.  I would like to contribute to this issue.

**Comment by mzeitlin11** [comment] 2021-07-12 15:28
> Hello, I am new here. I would like to contribute to this issue.

Looks like someone already put up a pr, please feel free to contribute to any other issues! (filtering by good first issue is also a good way to find good issues to start with)

**Comment by jbrockmendel** [comment] 2022-01-09 21:27
Closing as duplicate of #28920

**Closed by jbrockmendel** 2022-01-09 21:27 UTC
Labels: Bug, Needs Discussion, Series, rename, inplace
