### ISSUE TITLE
QST: Should list-likes with pd.NA have an inferred nullable dtype if possible?

### ISSUE THREAD

**Issue by dsaxton** [pandas-dev/pandas#33986] opened 2020-05-05 02:36 UTC
It looks like in each of these cases the dtype is inferred as object, but does it make sense to try to use a nullable extension type when possible?
```python
[ins] In [1]: pd.Series([1, 2, pd.NA]).dtype                                                                                                                                                                 
Out[1]: dtype('O')

[ins] In [2]: pd.Series([True, False, pd.NA]).dtype                                                                                                                                                          
Out[2]: dtype('O')

[ins] In [3]: pd.Series(["a", "b", pd.NA]).dtype                                                                                                                                                             
Out[3]: dtype('O')
```

**Comment by simonjayhawkins** [comment] 2020-05-05 08:17
@dsaxton Thanks for the report. closing as duplicate of #33662

**Closed by simonjayhawkins** 2020-05-05 08:17 UTC
Labels: Constructors, NA - MaskedArrays
