### ISSUE TITLE
BUG: read_csv() changed the integer data to 1

### ISSUE THREAD

**Issue by RYO0115** [pandas-dev/pandas#51026] opened 2023-01-27 18:00 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
for filename in statusdata_filenames:
    df = pd.read_csv(filename, header=1,  skiprows=[2,3], index_col=None, dtype=int)
```

### Issue Description

No matter what kind of csv I import, all the data of line 30 alway become 1.0.

### Expected Behavior

Imported as integer value ( not 1.0)

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Japanese_Japan.932

pandas           : 1.5.3
numpy            : 1.24.1
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 58.1.0
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
...
xlrd             : None
xlwt             : None
zstandard        : Non
</details>

**Comment by lithomas1** [comment] 2023-01-27 19:29
Can you provide a [Minimum Reproducible Example](https://matthewrocklin.com/minimal-bug-reports) (i.e. I can't reproduce this without your data file)?

**Comment by phofl** [comment] 2023-02-02 20:35
Closing, please ping to reopen when you can provide an example

**Closed by phofl** 2023-02-02 20:35 UTC
Labels: Bug, Needs Info
