### ISSUE TITLE
trouble building master branch from source in Windows7 x64 version

### ISSUE THREAD

**Issue by peterpanmj** [pandas-dev/pandas#22059] opened 2018-07-26 05:08 UTC
#### Problem description
I can build v0.23.3 from source without any trouble but I just cannot build current master branch (Current master branch at commit 2c7c79779f1ef353d02446504d3b5f5c5cc68759)
The compiler version is:
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25835 for x64

Here is the ouput:

> running build_ext
> building 'pandas._libs.index' extension
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipandas/_libs/src/klib -Ipandas/_libs/src -IC:\ProgramData\Anaconda3\envs\pandas_dev\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\envs\pandas_dev\include -IC:\ProgramData\Anaconda3\envs\pandas_dev\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /Tcpandas\_libs/index.c /Fobuild\temp.win-amd64-3.6\Release\pandas\_libs/index.obj
> index.c
> c:\programdata\anaconda3\envs\pandas_dev\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
> c:\users\public\pandas-peter\pandas\_libs\src\klib\khash.h(574): warning C4090: 'function': different 'const' qualifiers
> pandas/_libs/src/klib\khash_python.h(66): warning C4244: '=': conversion from 'Py_hash_t' to 'khint_t', possible loss of data
> pandas/_libs/src/klib\khash_python.h(72): warning C4244: '=': conversion from 'Py_hash_t' to 'khint_t', possible loss of data
> pandas/_libs/src/klib\khash_python.h(77): warning C4090: 'function': different 'const' qualifiers
> pandas\_libs/index.c(1219): error C2061: syntax error: identifier 'pandas_datetimestruct'
> pandas\_libs/index.c(1222): error C2059: syntax error: '}'
> pandas\_libs/index.c(6470): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
> pandas\_libs/index.c(19369): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
> pandas\_libs/index.c(20841): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
> pandas\_libs/index.c(22313): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
> pandas\_libs/index.c(48803): error C2027: use of undefined type '__pyx_obj_6pandas_5_libs_6tslibs_10conversion__TSObject'
> pandas\_libs/index.c(1217): note: see declaration of '__pyx_obj_6pandas_5_libs_6tslibs_10conversion__TSObject'
> pandas\_libs/index.c(52568): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
> pandas\_libs/index.c(52574): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data

Followed by

> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

#### Output of ``pd.show_versions()``

<details>

python: 3.6.4.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: zh_CN.UTF-8
LOCALE: None.None

</details>

**Comment by jbrockmendel** [comment] 2018-07-26 05:12
Can you go go a few commits back and see where the problem started?  (like git bisect)

**Comment by peterpanmj** [comment] 2018-07-26 05:59
I found it. It is commit 32bf5046f. @jbrockmendel

**Comment by peterpanmj** [comment] 2018-07-26 09:04
I just upgrade my cython package, now everything is OK .
The upgrade includes:

> 2018-07-26 16:52:00  (rev 4)
>      ca-certificates  {2017.08.26 -> 2018.03.07}
>      certifi  {2018.1.18 -> 2018.4.16}
>      cython  {0.27.3 -> 0.28.4}
>      openssl  {1.0.2n -> 1.0.2o}
>      vc  {14 -> 14.1}
>      vs2015_runtime  {14.0.25123 -> 15.5.2}

I guess it is a cython version issue.

**Comment by jbrockmendel** [comment] 2018-07-26 16:39
Glad this is fixed.  Closing as a duplicate of #21829.

**Closed by jbrockmendel** 2018-07-26 16:39 UTC
