### ISSUE TITLE
BUG: pd.Timestamp becomes int in .values printout

### ISSUE THREAD

**Issue by aminnj** [pandas-dev/pandas#53459] opened 2023-05-31 00:25 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

print(pd.DataFrame([dict(
    a=1,
    b=pd.Timestamp('2023-01-01 12:00:00'),
    c=pd.Timestamp('2023-01-01 12:00:00'),
)]).values.tolist())
# [[1, Timestamp('2023-01-01 12:00:00'), Timestamp('2023-01-01 12:00:00')]]

print(pd.DataFrame([dict(
    b=pd.Timestamp('2023-01-01 12:00:00'),
    c=pd.Timestamp('2023-01-01 12:00:00'),
)]).values.tolist())
# [[1672574400000000000, 1672574400000000000]]
```

### Issue Description

When all columns in a dataframe are `pd.Timestamp`, accessing values as strings yields integers. However, when a non-`pd.Timestamp` column exists in the dataframe, the string representation is as expected.

### Expected Behavior

Expected behavior observed when a non-`pd.Timestamp` column is present in the dataframe
```python
import pandas as pd

print(pd.DataFrame([dict(
    b=pd.Timestamp('2023-01-01 12:00:00'),
    c=pd.Timestamp('2023-01-01 12:00:00'),
)]).values.tolist())

# [[Timestamp('2023-01-01 12:00:00'), Timestamp('2023-01-01 12:00:00')]]
```

### Installed Versions

<details>

```
INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.9.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 58.0.4
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 10.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.47
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None
```

</details>

**Comment by topper-123** [comment] 2023-06-01 22:03
Your expected behavior matches actual behavior, can you clarify what think is wrong. currently. Also. Pandas has only control of what's happening until `df.values`. The`tolist` method is a numpy method and is outside of pandas' responisibility,

Looking briefly, everything looks to be working as expected here on pandas's side. The second example returns a numpy array of dtype `dtype='datetime64[ns]'`, which looks right, while the first returns an array with object dtype, which also look alright.

**Comment by aminnj** [comment] 2023-06-01 22:10
hi @topper-123. I made a copy-paste mistake! The expected behavior should be
```python
import pandas as pd

print(pd.DataFrame([dict(
    b=pd.Timestamp('2023-01-01 12:00:00'),
    c=pd.Timestamp('2023-01-01 12:00:00'),
)]).values.tolist())

# [[Timestamp('2023-01-01 12:00:00'), Timestamp('2023-01-01 12:00:00')]]
```
(also edited above)

**Comment by aminnj** [comment] 2023-06-01 22:12
Given the edit, can you clarify if this is still on the numpy side?

**Comment by topper-123** [comment] 2023-06-01 22:25
Your dataframe columns have the same dtype:

```python
>>> df = pd.DataFrame([dict(
...        b=pd.Timestamp('2023-01-01 12:00:00'),
...        c=pd.Timestamp('2023-01-01 12:00:00'),
... )])
>>> df.dtypes
b    datetime64[ns]
c    datetime64[ns]
dtype: object
```

So naturally x.values will give an numpy.array of that type, seems logical to me. In your first example the dataframe dtypes were not the same, so `df.values` gives an array of object dtype.

So IMO this is not a bug and works as expected. I'm closing, but if you post a follow-up, I'll respond and reopen if necessary.

**Closed** 2023-06-01 22:26 UTC
Labels: Bug, Timeseries, Closing Candidate
