### ISSUE TITLE
BUG: Joining dataframe with single-level MultiIndex fails

### ISSUE THREAD

**Issue by soerenwolfers** [pandas-dev/pandas#41537] opened 2021-05-18 12:37 UTC
- [x] I have checked that this issue has not already been reported.
There is https://github.com/pandas-dev/pandas/issues/37277 which is about the same error message but which isn't about the fact that this shows up in a common operation like joining. Maybe there is a way to make the join work without fixing the underlying issue?

- [ ] I have confirmed this bug exists on the latest version of pandas.
Unfortunately my work doesn't allow me to test this on latest pandas versions, but given the related issue above and  given that I haven't found this issue reported anywhere, I would be surprised if this was fixed in the meantime. I apologize if it was.

---

#### Code Sample, a copy-pastable example

```python
df = pd.DataFrame(
    np.random.normal(size=[4,1]), 
    index=pd.MultiIndex.from_product([['a', 'b'], [0.1, 0.2]]),
    columns=['col0']
).rename_axis(index=['level0', 'level1'])
df
df2 = pd.DataFrame(
    np.random.normal(size=[2,1]),
    #index=pd.Index(['a', 'b']),
    index=pd.MultiIndex.from_product([['a', 'b']]),
    columns=['col1']
).rename_axis(index=['level0'])
display(df)
display(df2)
df.join(df2, on=['level0'])
```

#### Problem description

Throws an error

#### Expected Output
Throws no error. Uncomment the commented line above and comment the line below. This should be functionally equivalent.

PS: This probably doesn't belong here, but if I replace the `join` by a `merge` it works, but the `level1` of the MultiIndex disappears, making it useless for me.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17134
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : None.None

pandas           : 1.1.5
numpy            : 1.17.4

</details>

**Comment by phofl** [comment] 2021-05-18 13:34
This is a duplicate of #36909 and is fixed on master

**Closed by phofl** 2021-05-18 13:34 UTC
Labels: Bug, Needs Triage
