### ISSUE TITLE
pandas boxplot props not working

### ISSUE THREAD

**Issue by mdf-github** [pandas-dev/pandas#33743] opened 2020-04-23 07:54 UTC
I cannot change some of the plotting kwargs in `pd.DataFrame.boxplot`. I replot the same in matplotlib with almost the same code and I get the expected results.

Here's a minimum working example:

```
np.random.seed(1234)
df = pd.DataFrame(np.random.randn(10, 4),
                  columns=['Col1', 'Col2', 'Col3', 'Col4'])
df.boxplot(column=['Col1', 'Col2', 'Col3'], showmeans=True,
                     meanprops={'markerfacecolor': 'r'},
                     boxprops={'linewidth':5,'color': 'r'}
                    )
fig2, ax2 = plt.subplots()
ax2.boxplot([df[c] for c in df.columns],showmeans=True,
                     meanprops={'markerfacecolor': 'r'},
                     boxprops={'linewidth':5,'color': 'r'})
```

The resulting plots are different. While the boxes are rendered in the correct color using `ax2.boxplot`, the `df.boxplot` version still has blue boxes (though thicker, which means `linewidth` works here).

**Comment by gabrielvf1** [comment] 2020-05-11 22:15
Can i work on it?

**Comment by charlesdong1991** [comment] 2020-05-13 06:07
thanks for reporting @mdf-github and thanks for your interest in helping contribute @gabrielvf1 

this issue has been fixed on master, so i cannot reproduce it anymore using master branch

**Closed by charlesdong1991** 2020-05-13 06:07 UTC
Labels: Visualization
