### ISSUE TITLE
TypeError: data type not understood

### ISSUE THREAD

**Issue by tusharsp60** [pandas-dev/pandas#29759] opened 2019-11-21 00:19 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

Reducer()
#!/usr/bin/env python3
# coding: utf-8

# In[7]:


import pandas as pd
import sys
import re

data=pd.read_csv(sys.stdin,names=["LOCATION","Value"],dtype=['str','float64'])
data["Value"]=data["Value"].str.strip()
#data1=pd.DataFrame(data,columns=['LOCATION','Value'],dtype=['str','float'])
#data["Value"]=data.Value.astype("float64")
#data["Value"]=data["Value"].str.astype("float64")
#data["Value"]=float(data["Value"])
#data["Value"]=data["Value"].astype(float)
#s=pd.Series(creditsa['Value'])
#pd.to_numeric(s)
#df1=pd.DataFrame(data=s,columns=['Value'])
#df1=data.groupby(["LOCATION"])["Value"].mean()
print(data.info())
```
#### Problem description
unable to convert datatype of column Value to float. I have tried several possible ways of doing it(commented in above code) but I am getting below error. Can you please let me know what is the problem here.
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/dtypes/common.py", line 2050, in pandas_dtype
    npdtype = np.dtype(dtype)
TypeError: data type not understood

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/hadoop/reducer.py", line 13, in <module>
    data=pd.read_csv(sys.stdin,names=["LOCATION","Value"],dtype=['str','float64'])
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 493, in pandas._libs.parsers.TextReader.__cinit__
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/dtypes/common.py", line 2054, in pandas_dtype
    raise TypeError("data type not understood")
TypeError: data type not understood

#### Expected Output
dtype of Value column should be float
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by jbrockmendel** [comment] 2019-12-01 22:20
Can you post an example that we can copy/paste to reproduce https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment] 2020-02-17 15:23
Closing due to lack of reproducible example, but feel free to reopen if you have one

**Closed by MarcoGorelli** 2020-02-17 15:23 UTC
Labels: Needs Info
