### ISSUE TITLE
BUG: `Series.sum` & `Series.mean` are inconsitent for `timedelta64` dtype

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#35644] opened 2020-08-09 17:05 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> pd.__version__
'1.1.0'
>>> s = pd.Series([None, None], dtype='timedelta64[ns]')
>>> s
0   NaT
1   NaT
dtype: timedelta64[ns]
>>> s.sum()
Timedelta('0 days 00:00:00')
>>> s.mean()
NaT
>>> s.sum() / 2 # Mean
Timedelta('0 days 00:00:00')
```

#### Problem description

When there are `NaT` values in the series, the sum in the above case to returns `0`, which will result in incorrect/inconsistent calculations if other calculations rely on the result of `sum`, for instance if we try calculating a mean from the result of sum, we get `0` instead of correct result `NaT`(as returned by `Series.mean`).

#### Expected Output

When there are `NaT` values in the series, I'd expect the sum in the above case to return `NaT`, as `Series.mean` returns `NaT` as expected. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.0
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jreback** [comment] 2020-08-09 18:22
try with min_count=1
this is consistent with an all nan float for example

**Comment by jorisvandenbossche** [comment] 2020-08-10 08:48
As @jreback says, this is indeed the same for float data:

```
In [15]: s = pd.Series([np.nan, np.nan]) 

In [16]: s  
Out[16]: 
0   NaN
1   NaN
dtype: float64

In [17]: s.sum()   
Out[17]: 0.0

In [18]: s.mean()  
Out[18]: nan
```

But, `sum()` is actually *skipping* missing values, so if you would calculate the mean yourself from the "sum / n", you also need to skip missing values when doing the count of elements, so you would get:

```
In [19]: s.sum() / 0 # Mean                                                                                                                                                                                        
/home/joris/miniconda3/envs/arrow-dev/bin/ipython:1: RuntimeWarning: invalid value encountered in double_scalars
  #!/home/joris/miniconda3/envs/arrow-dev/bin/python
Out[19]: nan
```

(so dividing by 0 instead of 2, and then you get a consistent result with the `mean()` method)

**Comment by jbrockmendel** [comment] 2020-09-01 23:26
Closing as not a bug.

**Closed by jbrockmendel** 2020-09-01 23:26 UTC
