### ISSUE TITLE
BUG: expanding/rolling_quantile() inconsistent with Series.quantile()

### ISSUE THREAD

**Issue by seth-p** [pandas-dev/pandas#8084] opened 2014-08-20 23:36 UTC
It appears that `Series.quantile()` interpolates between the two bracketing values, whereas `expanding/rolling_quantile()` don't.

```
In [496]: x = Series([0,1])

In [497]: x.quantile(0.3)
Out[497]: 0.29999999999999999

In [498]: expanding_quantile(x, 0.3)
Out[498]:
0    0
1    0
dtype: float64

In [499]: rolling_quantile(x, 2, 0.3, min_periods=1)
Out[499]:
0    0
1    0
dtype: float64
```

**Comment by jreback** [comment] 2017-05-03 10:11
dupe of #9413

**Closed by jreback** 2017-05-03 10:11 UTC
Labels: API Design, Numeric
