### ISSUE TITLE
Groupby with rolling on MultiIndex duplicate index level

### ISSUE THREAD

**Issue by jesrael** [pandas-dev/pandas#15350] opened 2017-02-08 18:07 UTC
`Groupby` by level of `MultiIndex` with `rolling`  duplicate index level.

    df = pd.DataFrame(data=[[1, 1, 10, 20], [1, 2, 30, 40], [1, 3, 50, 60],
                            [2, 1, 11, 21], [2, 2, 31, 41], [2, 3, 51, 61]],
                      columns=['id', 'date', 'd1', 'd2'])
    
    df.set_index(['id', 'date'], inplace=True)
    print (df)
             d1  d2
    id date        
    1  1     10  20
       2     30  40
       3     50  60
    2  1     11  21
       2     31  41
       3     51  61
       
Double `id` level.

    df1 = df.d1.groupby(level='id').rolling(window=2).sum()
    print(df1)
    id  id  date
    1   1   1        NaN
            2       40.0
            3       80.0
    2   2   1        NaN
            2       42.0
            3       82.0
    Name: d1, dtype: float64
    
Solution with `apply` works nice.

    df2 = df.groupby(level='id').d1.apply(lambda x: x.rolling(window=2).sum())
    print(df2)
    id  date
    1   1        NaN
        2       40.0
        3       80.0
    2   1        NaN
        2       42.0
        3       82.0
    Name: d1, dtype: float64
    
[SO question](http://stackoverflow.com/questions/42119793/doing-a-groupby-and-rolling-window-on-a-pandas-dataframe-with-a-multilevel-index).

    print (pd.show_versions())
    
    INSTALLED VERSIONS
    ------------------
    commit: None
    python: 3.5.1.final.0
    python-bits: 64
    OS: Windows
    OS-release: 7
    machine: AMD64
    processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
    byteorder: little
    LC_ALL: None
    LANG: sk_SK
    LOCALE: None.None
    
    pandas: 0.19.2
    nose: 1.3.7
    pip: 8.1.1
    setuptools: 20.3
    Cython: 0.23.4
    numpy: 1.11.0
    scipy: 0.17.0
    statsmodels: 0.6.1
    xarray: None
    IPython: 4.1.2
    sphinx: 1.3.1
    patsy: 0.4.0
    dateutil: 2.5.1
    pytz: 2016.2
    blosc: None
    bottleneck: 1.0.0
    tables: 3.2.2
    numexpr: 2.5.1
    matplotlib: 1.5.1
    openpyxl: 2.3.2
    xlrd: 0.9.4
    xlwt: 1.0.0
    xlsxwriter: 0.8.4
    lxml: 3.6.0
    bs4: 4.4.1
    html5lib: 0.999
    httplib2: None
    apiclient: None
    sqlalchemy: 1.0.12
    pymysql: None
    psycopg2: None
    jinja2: 2.8
    boto: 2.39.0
    pandas_datareader: 0.2.1
    None

**Comment by jreback** [comment] 2017-02-08 18:08
duplicate of #14013

**Closed by jreback** 2017-02-08 18:08 UTC

**Comment by leeprevost** [comment] 2022-01-22 17:09
I think this bug has been reintroduced in 1.3.5.  I'm getting duplicate index values even with group_keys=False.
