### ISSUE TITLE
setitem type coercion fails when setting a datetime column in a single row dataframe

### ISSUE THREAD

**Issue by tambu-j** [pandas-dev/pandas#14179] opened 2016-09-07 22:40 UTC
xref #6942
xref #12499

``` python
import datetime
import pandas as pd
df1 = pd.DataFrame({'a': [0,1], 'b': [datetime.datetime.now(), datetime.datetime.now()]})
# next line works as expected
df1.loc[:,'b'] = [datetime.datetime.now(), datetime.datetime.now()]
df1 = pd.DataFrame({'a': [0], 'b': [datetime.datetime.now()]})
# next line blows up 
df1.loc[:,'b'] = [datetime.datetime.now()]
```

Exception:
/Users/<snip>/anaconda/lib/python2.7/site-packages/pandas/core/internals.py in _try_coerce_args(self, values, other)
   2103                 other_mask = isnull(other)
   2104 
-> 2105                 other = other.astype('i8', copy=False).view('i8')
   2106             except ValueError:
   2107 

TypeError: long() argument must be a string or a number, not 'datetime.datetime'

Incidentally, df1['b'] = [datetime.datetime.now()] will work, but i'm avoiding that as the performance is so poor when it's a copy (in my particular case the copy is dead and gc.collect(2) gets called for each column set operation, blowing out the runtime to 3x what it was pre-copy checking - should I open a separate issue for that?). 

pd.show_versions():
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Darwin
OS-release: 12.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.1
setuptools: 20.3
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.5.1
pytz: 2016.2
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.5
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.6.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.12
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.39.0
pandas_datareader: None

**Comment by evanzd** [comment] 2016-09-08 03:08
Just encounter this bug several minutes ago. pandas version: 0.18.1
>>> import pandas as pd
>>> import datetime
>>> df=pd.DataFrame()
>>> df['a']=[datetime.datetime.now()]
>>> df
                        a
0 2016-09-08 10:55:52.115
>>> df.loc[:,'a'] is df['a']
True
>>> df.loc[:,'a']=[datetime.datetime.now()]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python27\lib\site-packages\pandas\core\indexing.py", line 132, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "C:\python27\lib\site-packages\pandas\core\indexing.py", line 521, in _setitem_with_indexer
    setter(labels[0], value)
  File "C:\python27\lib\site-packages\pandas\core\indexing.py", line 461, in setter
    s._data = s._data.setitem(indexer=pi, value=v)
  File "C:\python27\lib\site-packages\pandas\core\internals.py", line 2917, in setitem
    return self.apply('setitem', **kwargs)
  File "C:\python27\lib\site-packages\pandas\core\internals.py", line 2890, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\python27\lib\site-packages\pandas\core\internals.py", line 642, in setitem
    values, _, value, _ = self._try_coerce_args(self.values, value)
  File "C:\python27\lib\site-packages\pandas\core\internals.py", line 2105, in _try_coerce_args
    other = other.astype('i8', copy=False).view('i8')
TypeError: long() argument must be a string or a number, not 'datetime.datetime'
>>> df['a']=[datetime.datetime.now()]
>>>

**Comment by jreback** [comment] 2016-09-08 10:07
this is the same cause as #6942, #12499

**Comment by jreback** [comment] 2016-09-08 10:08
@tambu-j 

> Incidentally, df1['b'] = [datetime.datetime.now()] will work, but i'm avoiding that as the performance is so poor when it's a copy (in my particular case the copy is dead and gc.collect(2) gets called for each column set operation, blowing out the runtime to 3x what it was pre-copy checking - should I open a separate issue for that?).

you are modifying a filtered frame. you should simply copy before you modify as the warning indicates.

**Comment by jreback** [comment] 2017-10-30 10:56
dupe of #6942

**Closed by jreback** 2017-10-30 10:56 UTC
Labels: Bug, Difficulty Intermediate, Duplicate, Effort Low, Indexing, Timeseries
