### ISSUE TITLE
BUG: Result of setting a cell to a single-element NumPy array changed with 2.0.1 -> 2.0.2

### ISSUE THREAD

**Issue by torokati44** [pandas-dev/pandas#53622] opened 2023-06-12 16:29 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np, pandas as pd

df = pd.DataFrame({"a": [np.array([0.0, 0.0])]})

print(df["a"].iloc[0])
print(df["a"].iloc[0].shape)
print(df["a"].iloc[0][0])

df["a"].iloc[0] = np.array([0.0])

print(df["a"].iloc[0])
print(df["a"].iloc[0].shape)
print(df["a"].iloc[0][0])
```

### Issue Description

With 2.0.1 this prints the following, as expected:
```
[0. 0.]
(2,)
0.0
[0.]
(1,)
0.0
```

With 2.0.2, it prints this, with the last line erroring out:
```
[0. 0.]
(2,)
0.0
0.0
()
# IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

Workarounds to keep the 2.0.1 result are also welcome.

### Expected Behavior

As 2.0.2 was a patch update, I wouldn't expect any changes in existing behavior.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.11.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 6.3.6-200.fc38.x86_64
Version          : #1 SMP PREEMPT_DYNAMIC Mon Jun  5 15:45:04 UTC 2023
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.1
pip              : 23.1
Cython           : None
pytest           : 7.3.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.6.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : 2023.1.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 2.0.7
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : 2.3.0
pyqt5            : None

</details>

**Comment by mroeschke** [comment] 2023-06-12 19:15
Thanks for the report. I think this is a duplicate of https://github.com/pandas-dev/pandas/issues/53565 so closing

**Closed by mroeschke** 2023-06-12 19:15 UTC
Labels: Bug, Needs Triage
