### ISSUE TITLE
Cannot initialize a data frame with None

### ISSUE THREAD

**Issue by jbao** [pandas-dev/pandas#14414] opened 2016-10-13 12:51 UTC
Hi all,

just figured out that the following code

    pd.DataFrame({'x':None}, index=[0])

works in 0.18.1 but not 0.19.0, is that the expected behavior? Thanks!

Best,
Jie

**Comment by chris-b1** [comment] 2016-10-13 13:13
Thanks for the report, this is a duplicate of #14381, which should be fixed for 0.19.1.

**Closed by chris-b1** 2016-10-13 13:13 UTC
