### ISSUE TITLE
Need way to get original column order (read_csv, read_json)

### ISSUE THREAD

**Issue by rfernand2** [pandas-dev/pandas#24962] opened 2019-01-27 20:27 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

Applications sometimes need to be able to present and manipulate data in the column ordering found in the source data file (CSV or JSON).  The column order in these files is significant to users in many cases.  The pd.read_csf() and pd.read_json() don't seem to have a parameter that prevents Pandas from sorting the columns and losing the original column order.  After the Dataframe has been created, there seems to be no way to get the original column order.  Please consider adding a parameter to read_csv() and read_json() to preserve the column ordering found in the first line of the file (for CSV) or in the first record (for JSON).  Thanks!

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by TomAugspurger** [comment] 2019-01-27 20:55
> The pd.read_csf() and pd.read_json() don't seem to have a parameter that prevents Pandas from sorting the columns and losing the original column order. 

Can you show an example where column order is lost with `read_csv`?

**Comment by rfernand2** [comment] 2019-01-28 00:10
I just checked CSV and TXT – my bad – these work perfectly.  The problem seems to only be with read_json().  Thanks!

**Comment by TomAugspurger** [comment] 2019-01-28 00:18
How about an example with read_json? Keep in mind that dictionaries aren’t necessarily ordered.


________________________________

**Comment by rfernand2** [comment] 2019-02-11 00:53
Sorry for the delay.  Here is a failing test case:

`# pandasJsonLoader: test out ability of pandas JSON loader to preserve column order
import pandas 

json_str = '''[
     {
      "Name":"chevrolet chevelle malibu",
      "Miles_per_Gallon":18,
      "Cylinders":8,
      "Displacement":307,
      "Horsepower":130,
      "Weight_in_lbs":3504,
      "Acceleration":12,
      "Year":"1970-01-01",
      "Origin":"USA"
   }
]'''

data = pandas.read_json(json_str)

print(list(data))
''' run output: ['Acceleration', 'Cylinders', 'Displacement', 'Horsepower', 'Miles_per_Gallon', 'Name', 'Origin', 'Weight_in_lbs', 'Year'] '''
`

**Comment by rfernand2** [comment] 2019-02-11 01:05
Not sure how I closed this issue - Reopening it again.

**Comment by WillAyd** [comment] 2019-03-26 05:52
@rfernand2 what you are asking for is achievable with `orient='table'` for JSON as that by design produces a schema with an ordered list of field descriptors (columns)

**Comment by WillAyd** [comment] 2019-03-26 05:53
Closing as I think this is already supported across formats requested

**Closed by WillAyd** 2019-03-26 05:53 UTC
Labels: Needs Info

**Comment by rfernand2** [comment] 2019-03-26 13:13
That doesn't seem to be a valid option for this.  When I add "orient='table'" to the above test case, I get the following error:

C:\multiNLI\multinli_1.0>python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    data = pandas.read_json(json_str, orient="table")
  File "c:\anaconda3\lib\site-packages\pandas\io\json\json.py", line 422, in read_json
    result = json_reader.read()
  File "c:\anaconda3\lib\site-packages\pandas\io\json\json.py", line 529, in read
    obj = self._get_object_parser(self.data)
  File "c:\anaconda3\lib\site-packages\pandas\io\json\json.py", line 546, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "c:\anaconda3\lib\site-packages\pandas\io\json\json.py", line 638, in parse
    self._parse_no_numpy()
  File "c:\anaconda3\lib\site-packages\pandas\io\json\json.py", line 864, in _parse_no_numpy
    precise_float=self.precise_float)
  File "c:\anaconda3\lib\site-packages\pandas\io\json\table_schema.py", line 298, in parse_table_schema
    col_order = [field['name'] for field in table['schema']['fields']]
TypeError: list indices must be integers or slices, not str

**Comment by WillAyd** [comment] 2019-03-26 13:42
Right your source data would need to be in the table format first. 

```python
pd.read_json(data[['Miles_per_Gallon', 'Cylinders', 'Name']].to_json(orient='table'), orient='table')
```

**Comment by rfernand2** [comment] 2019-03-26 15:53
Hi William - thanks for the quick response.
So, if my data is in the format shown in my test case (which is was when I ran into this problem), there is no way to load it and preserve the column order using Pandas.  Can you change to code to just preserve the column order for this common case? Maybe with a option for the behavior, if needed?  
Thanks, Roland.

**Comment by WillAyd** [comment] 2019-03-26 16:02
JSON objects are by definition unordered so I don't think there's a compliant way to get what you are asking for with your source data

https://json.org

**Comment by rfernand2** [comment] 2019-03-26 16:10
OK, I see the problem now.  Thanks for your help!

**Comment by Biprodeep** [comment] 2019-05-07 15:54
Hi,
Please provide a feature where we can turn off lexicographical sorting of columns in **read_json()** Currently it sorts lexicographically regardless of the original order which leads to loosing of format.
By this I mean - the dataframe should be reading columns in order as they are placed. In case of an unformated JSON file it will throw an **error** that it cannot replicate the default column order for every other field.
Thanks.

**Comment by apalii** [comment] 2019-06-18 19:12
```
# expected order
In [28]: qwe  = [{"question": "Who are you ?", "answer": "I am bot"}, {"question": "Are you production ready ?", "answer": "Definately not"},]

# expected order
In [29]: json.dumps(qwe)
Out[29]: '[{"question": "Who are you ?", "answer": "I am bot"}, {"question": "Are you production ready ?", "answer": "Definately not"}]'

# wrong order
In [30]: pandas.read_json(json.dumps(qwe))
Out[30]:
           answer                    question
0        I am bot               Who are you ?
1  Definately not  Are you production ready ?

In [31]: pandas.read_json(json.dumps(qwe)).to_csv()
Out[31]: ',answer,question\n0,I am bot,Who are you ?\n1,Definately not,Are you production ready ?\n'
```
I am going to use this function for converting json to csv, but mentioned function returns absolutely another object. 
@WillAyd 
> JSON objects are by definition unordered 

I agree, but it doesn't mean that `read_json` should change the object. So again, please reopen the issue and provide a key where we can turn off lexicographical sorting of columns:
# for example
`pandas.read_json(json.dumps(qwe), keep_order=True)`

**Comment by jacky82226** [comment] 2019-07-05 19:51
Same question here.
It seems that right now pandas.read_json would sort the JSON (as a dictionary in Python?) and then print it.
Still looking for an alternative to control the order because I would like to make certain column being the first order.
Providing the function for keeping order would be really helpful. 

Thank you so much.

**Comment by discover59** [comment] 2019-11-22 10:22
@jacky82226 's approach worked for me with minor adjustment.

**Comment by brakende** [comment] 2023-05-03 06:46
Shorter version of @jcwchen answer:

```python
with open(JSON_DB) as handle:
    j = json.load(handle, object_pairs_hook=OrderedDict)
    rowdicts = [{"idx": k} | vs for k, vs in j.items()]
print(pd.DataFrame.from_records(rowdicts).set_index("idx"))
```
