### ISSUE TITLE
to_sql is very slow for sql server with sqlalchemy

### ISSUE THREAD

**Issue by anjsudh** [pandas-dev/pandas#23274] opened 2018-10-22 14:01 UTC
df.to_sql is very slow, and takes hours, when connecting to sql server using sql alchemy connection
https://github.com/mkleehammer/pyodbc/wiki/Features-beyond-the-DB-API#fast_executemany

Performance is much faster after using fast_executemany
@event.listens_for(engine_local, 'before_cursor_execute')
def receive_before_cursor_execute(conn, cursor, statement, params, context, executemany):
    if executemany:
        cursor.fast_executemany = True

Can enable fast_executemany in to_sql implementation for SQL Server

**Comment by TomAugspurger** [comment] 2018-10-22 20:54
Duplicate of https://github.com/pandas-dev/pandas/issues/8953 I believe. https://github.com/pandas-dev/pandas/pull/21401 will fix this.

**Closed** 2018-10-22 20:54 UTC

**Comment by tauqeerhasan** [comment] 2020-04-06 07:54
please share the full code to export dataframe to database..
i have 10300000 rows and df.to_sql is working very very slow.. i need a fast performance code..

**Comment by sepjc96** [comment] 2021-03-24 00:24
@tauqeerhasan have you figured out how to enhance the speed?
