### ISSUE TITLE
BUG: Inputting a masked 64-bit integer array from numpy gets mangled by a hidden float conversion

### ISSUE THREAD

**Issue by erykoff** [pandas-dev/pandas#58173] opened 2024-04-06 18:52 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import numpy as np
import pandas as pd

data = np.array([2**52, 2**52+1, 2**53, 2**53+1, 1649900760361600113, 1649900760361609541, 0])
masked_data = np.ma.masked_array(data, mask=np.zeros(len(data), dtype=np.bool_))

s1 = pd.Series(data, dtype="Int64")
print(s1)
s2 = pd.Series(masked_data, dtype="Int64")
print(s2)

masked_data.mask[-1] = True

s3 = pd.Series(masked_data, dtype="Int64")
print(s3)
```
```


### Issue Description

When making a series or dataframe out of a masked 64-bit numpy array then it seems that it first gets converted to a 64-bit float which loses precision.  In the example above the presence of a masked value means that the final converted Series does not match the initial converted Series.  (This also happens when using an astropy MaskedColumn).

### Expected Behavior

Well, it should not change the datatype and round the large integer values.  I expect `np.all(s3 == s1)` to return `True`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.11.7.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.4.0
Version             : Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.24.4
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.3
pip                 : 23.3.2
Cython              : None
pytest              : 7.4.4
hypothesis          : 6.92.2
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : None
psycopg2            : 2.9.9
jinja2              : 3.1.2
IPython             : 8.19.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : 2023.10.1
fsspec              : 2023.12.2
gcsfs               : None
matplotlib          : 3.8.2
numba               : 0.58.1
numexpr             : 2.8.8
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 14.0.2
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : 2.0.25
tables              : 3.9.2
tabulate            : 0.9.0
xarray              : 2023.12.0
xlrd                : None
zstandard           : 0.22.0
tzdata              : 2023.4
qtpy                : None
pyqt5               : None

</details>

**Comment by dontgoto** [comment] 2024-04-07 12:05
This still happens on main and indeed seems to be an issue with the series constructor (the data sanitation in particular) and not with the numpy masked array constructor. I'll take a closer look.

**Comment by dontgoto** [comment] 2024-04-07 12:05
take

**Comment by dontgoto** [comment] 2024-04-07 22:00
This is a duplicate of #56566. And the issue seems to go further than that. When fixing your issue here in the array sanitising, Series.to_numpy() of the non-mangled ints fails similarly as the construction of the series prior to the fix. There might be more issues with such large ints and masked arrays in Series/DataFrames beyond that.

**Comment by mroeschke** [comment] 2024-06-03 18:08
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/56566

**Closed by mroeschke** 2024-06-03 18:08 UTC
Labels: Bug, Needs Triage
