### ISSUE TITLE
BUG: DataFrame.agg() on empty dataframe returns unexpected result

### ISSUE THREAD

**Issue by kdebrab** [pandas-dev/pandas#60424] opened 2024-11-26 15:41 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

index_empty = pd.MultiIndex.from_product([[], []], names=["one", "two"])
df_empty = pd.DataFrame({"a": [], "b": []}, index=index_empty)
df_empty.agg(lambda row: row.name[0], axis=1)
```

### Issue Description

The above returns:
```
Empty DataFrame
Columns: [a, b]
Index: []
```

### Expected Behavior

The expected result would be an empty series:
```
Series([], dtype: float64)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.11.3
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_Belgium.1252
pandas                : 2.2.3
numpy                 : 2.1.3
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 24.2
Cython                : None
sphinx                : None
IPython               : 8.28.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.10.0
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.4
lxml.etree            : 5.3.0
matplotlib            : 3.8.4
numba                 : None
numexpr               : 2.10.2
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : 1.4.6
pyarrow               : 18.0.0
pyreadstat            : None
pytest                : 8.3.3
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : 2.0.36
tables                : 3.10.1
tabulate              : 0.9.0
xarray                : 2024.10.0
xlrd                  : None
xlsxwriter            : 3.2.0
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

</details>

**Comment by rhshadrach** [comment] 2024-11-26 21:01
Thanks for the report. Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/47959.

**Closed by rhshadrach** 2024-11-26 21:01 UTC
Labels: Bug, Needs Triage

**Comment by kdebrab** [comment] 2024-11-27 08:55
@rhshadrach Thanks for linking with #47959. 

I would like to add a bit more context.

Note that e.g. following does work as expected on an empty dataframe:
```
df_empty.agg(lambda row: row.name, axis=1)
Out[3]: Series([], dtype: float64)
```
It's only when adding a subscript to `row.name` (which should be fine as the index is a multiindex), we suddenly get:
```
df_empty.agg(lambda row: row.name[0], axis=1)
Out[4]: 
Empty DataFrame
Columns: [a, b]
Index: []
```

**Comment by rhshadrach** [comment] 2024-11-28 14:23
@kdebrab - this is because `agg` will attempt to pass an empty Series, using the result to determine what it should return. By adding `[0]`, this attempt now raises an error, meaning that `agg` has no information whatsoever on what the UDF you're providing does. As such, it just returns the input as-is.
