### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by shadowbourne** [pandas-dev/pandas#35526] opened 2020-08-03 12:27 UTC
---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd
def edit(row):
    row["poo"] = 9
    return row
df = pd.DataFrame({"foo":[1,2,3,4],"Hi":[0,1,0,2]})
print(df.head())
print(df.apply(edit, axis=1))
```

#### Problem description
Returns completely wrong output on my system, but anyone else's it seems fine.  (pandas 1.1.0, python 3.8.4 and 3.7.8)
[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]
#### Bugged Output:
   foo  Hi  poo
0    1   0    9
1    1   0    9
2    1   0    9
3    1   0    9
#### Expected Output
   foo  Hi  poo
0    1   0    9
1    2   1    9
2    3   0    9
3    4   2    9
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.7.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : None.None

pandas           : 1.1.0
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
None
[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by simonjayhawkins** [comment] 2020-08-03 12:44
Thanks @shadowbourne for the report. This is a duplicate of #35462 so closing.

**Closed by simonjayhawkins** 2020-08-03 12:44 UTC
Labels: Bug, Needs Triage
