### ISSUE TITLE
BUG: KeyError on Column Name - Column Name Is 100% There 

### ISSUE THREAD

**Issue by DDZ12** [pandas-dev/pandas#38922] opened 2021-01-03 16:18 UTC
- [x] I have checked that this issue has not already been reported.
Yes
- [x] I have confirmed this bug exists on the latest version of pandas.
Yes 1.2.0
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.
No
---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.
```
AAPL
MultiIndex([('AAPL',   'open'),
            ('AAPL',   'high'),
            ('AAPL',    'low'),
            ('AAPL',  'close'),
            ('AAPL', 'volume')],
           )
<class 'pandas.core.frame.DataFrame'>

[False False False False False False False False False False False False
 False False False False  True  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]
<class 'numpy.ndarray'>

MultiIndex([('AAPL',   'open'),
            ('AAPL',   'high'),
            ('AAPL',    'low'),
            ('AAPL',  'close'),
            ('AAPL', 'volume')],
           )
<class 'pandas.core.frame.DataFrame'>
```

```python

import sqlite3
import config
import alpaca_trade_api as tradeapi
import pandas as pd
import numpy as np
from datetime import date


symbols  = [stock['symbol'] for stock in stocks]

api = tradeapi.REST(config.API_KEY, config.SECRET_KEY, base_url=config.API_URL)

current_date = "2020-12-31"

start_minute_bar = "2020-12-31 09:00:00-05:00"
end_minute_bar = "2020-12-31 09:45:00-05:00"

for symbol in symbols:
    
    minute_bars = api.get_barset(symbol, '5Min', start=pd.Timestamp(current_date), end=pd.Timestamp(current_date)).df

    print(symbol)
    print(minute_bars.columns)
    print(type(minute_bars))

    opening_range_mask = (minute_bars.index >= start_minute_bar) & (minute_bars.index < end_minute_bar)
    print(type(opening_range_mask))

    opening_range_bars = minute_bars.loc[opening_range_mask]

    print(opening_range_bars.columns)
    print(type(opening_range_bars))


    opening_range_low = opening_range_bars['low'].min() <<<<<< ERROR @ THIS LINE ('low') KeyERROR


```
#### Problem description

I keep getting a key error when calling the code line:
 opening_range_low = opening_range_bars['low'].min()

the error state being KeyERROR on the 'low' brackets. I've used 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 3e89b4c4b1580aa890023fc550774e63d499da25
python           : 3.8.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 71 Stepping 1, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : English_United Kingdom.1252

pandas           : 1.2.0
numpy            : 1.19.4
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
![image](https://user-images.githubusercontent.com/76912549/103483466-4f650b80-4ddf-11eb-8976-f94a830af401.png)

**Comment by phofl** [comment] 2021-01-03 18:44
Hey, thanks for your report. Could you please provide a minimal reproducible example including the stacktrace of your error? See https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by MarcoGorelli** [comment] 2021-02-14 14:12
closing as it's not clear how to reproduce this, will reopen if you include a reproducible example

**Closed by MarcoGorelli** 2021-02-14 14:12 UTC
Labels: Bug, Closing Candidate, Needs Info

**Comment by MarcoGorelli** [comment] 2021-02-15 10:05
(I suspect the KeyError is because you're trying to access a MultiIndex with a key from the second layer only, in which case the error seems correct)

**Comment by DDZ12** [comment] 2021-02-15 10:46
Hi Marco,


Can confirm your right! Apologies still learning my way through python!

Hence my limited capability to provide support/assistance.

Best wishes

Dave
