### ISSUE TITLE
BUG: cannot use category dtype in pandas read_json method 

### ISSUE THREAD

**Issue by alison199** [pandas-dev/pandas#40063] opened 2021-02-25 20:21 UTC
- [x] I have confirmed this bug exists on the latest version of pandas.

import pandas as pd

print(pd.__version__)

1.2.2

Problem described in other places:
1) https://github.com/pandas-dev/pandas/issues/21892
2) https://github.com/pandas-dev/pandas/pull/25573
3) https://github.com/pandas-dev/pandas/pull/30728

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```
import pandas as pd

content = '[{"score": 1,"color":"red"},{"score":10,"color":"green"}]'
dtypes_dict = {'score': 'uint8', 'colour': 'category'}

data_frame = pd.read_json(content, dtype=dtypes_dict)
print(data_frame.dtypes)

```

#### Problem description

When I run the above, I get the following dtypes for the dataframe columns:

score     uint8
color    object 

#### Expected Output

score     uint8
color    category

**Comment by jreback** [comment] 2021-02-25 23:04
duplicate of #21892

**Closed** 2021-02-25 23:04 UTC
Labels: Categorical, Duplicate, IO JSON
