### ISSUE TITLE
BUILD: 2.0.0 Cannot install with poetry

### ISSUE THREAD

**Issue by da1910** [pandas-dev/pandas#52778] opened 2023-04-19 10:47 UTC
### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).

### Platform

Windows-10-10.0.22000-SP0

### Installation Method

Other

### pandas Version

2.0.0

### Python Version

3.10.5

### Installation Logs

<details>

Warning: Validation of the RECORD file of pandas-2.0.0-cp310-cp310-win_amd64.whl failed. Please report to the maintainers of that package so they can fix their build process. Details:
In C:\Users\me\AppData\Local\pypoetry\Cache\artifacts\85\f6\63\51ca75625c80a076445e7ed2b95badf39f34916440f852dee63e76fce4\pandas-2.0.0-cp310-cp310-win_amd64.whl, pandas/_libs/window/msvcp140.dll is not mentioned in RECORD    
In C:\Users\me\AppData\Local\pypoetry\Cache\artifacts\85\f6\63\51ca75625c80a076445e7ed2b95badf39f34916440f852dee63e76fce4\pandas-2.0.0-cp310-cp310-win_amd64.whl, pandas/_libs/window/concrt140.dll is not mentioned in RECORD   
In C:\Users\me\AppData\Local\pypoetry\Cache\artifacts\85\f6\63\51ca75625c80a076445e7ed2b95badf39f34916440f852dee63e76fce4\pandas-2.0.0-cp310-cp310-win_amd64.whl, pandas/_libs/window/vcruntime140_1.dll is not mentioned in RECORD

</details>

Looks like the error is valid, the RECORD does not list any of the three DLLs but they are present in the whl file.

**Comment by MarcoGorelli** [comment] 2023-04-19 10:49
thanks for the report - looks like a dupe of https://github.com/pandas-dev/pandas/issues/52465, so closing for now

**Closed by MarcoGorelli** 2023-04-19 10:49 UTC
Labels: Build, Needs Triage
