### ISSUE TITLE
BUG 1.5.2: pytest is failing with latest `hypotesis`

### ISSUE THREAD

**Issue by kloczek** [pandas-dev/pandas#49840] opened 2022-11-22 15:16 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
```

### Issue Description

Lookks like some pytest units are failing with latest `hypotesis` 6.58.0 because they are using internal `hypotesis` API.

### Expected Behavior

pytest should not fail

### Installed Versions

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
appdirs                       1.4.4
asn1crypto                    1.5.1
attrs                         22.1.0
Babel                         2.11.0
bcrypt                        3.2.2
botocore                      1.29.13
Brlapi                        0.8.3
build                         0.9.0
cffi                          1.15.1
charset-normalizer            3.0.1
contourpy                     1.0.6
cryptography                  38.0.1
cssselect                     1.1.0
cycler                        0.11.0
distro                        1.8.0
dnspython                     2.2.1
docutils                      0.19
exceptiongroup                1.0.0
extras                        1.0.0
fixtures                      4.0.0
fonttools                     4.38.0
gpg                           1.17.1-unknown
guzzle-sphinx-theme           0.7.11
idna                          3.4
imagesize                     1.4.1
importlib-metadata            5.0.0
iniconfig                     1.1.1
Jinja2                        3.1.2
jmespath                      1.0.0
kiwisolver                    1.4.4
libcomps                      0.1.19
louis                         3.23.0
lxml                          4.9.1
MarkupSafe                    2.1.1
matplotlib                    3.6.2
numpy                         1.23.1
olefile                       0.46
packaging                     21.3
pbr                           5.9.0
pep517                        0.13.0
Pillow                        9.3.0
pip                           22.3.1
pluggy                        1.0.0
ply                           3.11
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.21
Pygments                      2.13.0
PyGObject                     3.42.2
pyparsing                     3.0.9
pytest                        7.2.0
python-dateutil               2.8.2
pytz                          2022.4
PyYAML                        6.0
requests                      2.28.1
rpm                           4.17.0
s3transfer                    0.6.0
scour                         0.38.2
setuptools                    65.6.0
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        5.3.0
sphinxcontrib-applehelp       1.0.2.dev20220730
sphinxcontrib-devhelp         1.0.2.dev20220730
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220730
sphinxcontrib-qthelp          1.0.3.dev20220730
sphinxcontrib-serializinghtml 1.1.5
testtools                     2.5.0
tomli                         2.0.1
tpm2-pkcs11-tools             1.33.7
tpm2-pytss                    1.1.0
urllib3                       1.26.12
wheel                         0.38.4
zipp                          3.10.0
```
</details>

**Comment by MarcoGorelli** [comment] 2022-11-22 15:34
pandas CI is green and is using hypothesis 6.58.0

which tests fail?

**Comment by MarcoGorelli** [comment] 2022-11-22 15:45
Can't reproduce, sorry:
```console
$ pytest pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.8.13, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/marcogorelli/pandas-dev, configfile: pyproject.toml
plugins: forked-1.4.0, cython-0.2.0, hypothesis-6.56.4, xdist-3.0.2, asyncio-0.20.2, cov-4.0.0, typeguard-2.13.3, anyio-3.6.1
asyncio: mode=strict
collected 56 items                                                                                                                                                                 

pandas/tests/io/parser/test_parse_dates.py ..................x...x.................................

--------------------------------------------------------- generated xml file: /home/marcogorelli/pandas-dev/test-data.xml ----------------------------------------------------------
=============================================================================== slowest 30 durations ===============================================================================
0.27s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%m %Y-True-.]
0.22s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%m %Y-False-.]
0.10s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-False--]
0.09s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%d %m %Y-True-.]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-True-/]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-False- ]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%d %m %Y-True- ]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-True--]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-False--]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-True- ]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-True-.]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-False- ]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-False-.]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-False-/]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-False-/]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y %m %d-False-.]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-True--]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%d %m %Y-True-/]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y%m%d-True-/]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y%m%d-True--]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-True- ]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y%m%d-True- ]
0.06s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y%m%d-False- ]
0.05s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-True-/]
0.05s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y%m%d-True- ]
0.05s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y %m %d-True-.]
0.05s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y%m%d-True-.]
0.05s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%m %d %Y-True--]
0.05s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%Y%m%d-False-.]
0.05s call     pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date[%y%m%d-True-.]
========================================================================== 54 passed, 2 xfailed in 3.88s ===========================================================================
(pandas-dev) marcogorelli@DESKTOP-U8OKFP3:~/pandas-dev$ 
```

Closing for now then, if you're following an installation procedure which isn't recommended by the docs then I think that's up to you to debug, but I don't think there's anything actionable here

**Closed by MarcoGorelli** 2022-11-22 15:45 UTC
Labels: Needs Info

**Comment by kloczek** [comment] 2022-11-23 13:40
You are using `hypothesis` 6.56.
In my case it is 6.58.0.
Could you please try upgrade you `hypothesis` to the latest version?

**Comment by MarcoGorelli** [comment] 2022-11-23 13:44
It's 6.58.0:

https://pipelines.actions.githubusercontent.com/serviceHosts/e1fa798b-a3de-4f41-9248-cf5942f5881f/_apis/pipelines/1/runs/368845/signedlogcontent/6?urlExpires=2022-11-23T13%3A45%3A27.9387804Z&urlSigningMethod=HMACV1&urlSignature=Q7EVOE0VD6K1marhDMQOJnIfV9sRLW5Dn1vYhmNnzTw%3D
```
2022-11-23T08:50:19.1665737Z   hypothesis                          6.58.0        pyha770c72_0          conda-forge
```

**Comment by MarcoGorelli** [comment] 2022-11-23 14:40
you can look at any recent CI job logs and see it

**Comment by kloczek** [comment] 2022-11-23 15:52
Indeed however looking on last commit CI https://github.com/pandas-dev/pandas/actions/runs/3532039965/jobs/5925906197 I see only small subset of modules which I have installed in buikd env
```console
+ python -m pip list
Package          Version                    Editable project location
---------------- -------------------------- -------------------------
attrs            22.1.0
Cython           0.29.32
exceptiongroup   1.0.4
execnet          1.9.0
hypothesis       6.58.0
iniconfig        1.1.1
numpy            1.23.5
packaging        21.3
pandas           2.0.0.dev0+741.gd1ecf63e20 /pandas
pip              22.3.1
pluggy           1.0.0
pyparsing        3.0.9
pytest           7.2.0
pytest-asyncio   0.20.2
pytest-xdist     3.0.2
python-dateutil  2.8.2
pytz             2022.6
setuptools       59.8.0
six              1.16.0
sortedcontainers 2.4.0
tomli            2.0.1
wheel            0.38.4
```
Looks like pytest is failing in my case in some optional units which are added because I have specified more build dependencies.
Coould you please repeat `pytest pandas/tests/io/parser/test_parse_dates.py::test_hypothesis_delimited_date` in your debel env after upgrade `hypotesis` as well?

**Comment by MarcoGorelli** [comment] 2022-11-23 15:53
https://github.com/pypa/pip/issues/11601#issuecomment-1317546885
