### ISSUE TITLE
DataFrame.interpolate(axis='columns') throws exception while DataFrame.interpolate(axis=1) not

### ISSUE THREAD

**Issue by heavelock** [pandas-dev/pandas#25190] opened 2019-02-06 16:06 UTC
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd

x = np.linspace(0,100,1000)
y = np.sin(x)
df = pd.DataFrame(data=np.tile(y, (10,1)), index=np.arange(10), columns=x)
df.reindex(columns=x*1.005).interpolate(method='linear', axis=1)

df.reindex(columns=x*1.005).interpolate(method='linear', axis='columns')
```
#### Problem description

The interpolation with argument `axis` set to 'columns' throws an exception from 
https://github.com/pandas-dev/pandas/blob/c460a929e19535335085c652e7e35eee1d9c7c2e/pandas/core/generic.py#L6800

The exception is:
```
UnboundLocalError: local variable 'ax' referenced before assignment
```

The same method for parameter `axis=1' works fine.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-44-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: 0.11.2
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: 4.2.5
bs4: None
html5lib: None
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by Vibhu-Agarwal** [comment] 2019-02-07 06:28
This behavior is also observed with passing `'index'` for axis (for axis=0)

**Comment by Vibhu-Agarwal** [comment] 2019-02-07 06:32
I want to work on this issue and solve it.

**Comment by gfyoung** [comment] 2019-02-07 06:41
@Vibhu-Agarwal : By all means!  Investigation and PR are welcome!

**Comment by YagoGG** [comment] 2020-01-26 17:35
I believe this issue has already been fixed in c983d52e3a3a8a191359814417f375b1dc8b04c1. Maybe it can be closed?

**Comment by gfyoung** [comment] 2020-01-26 18:16
@YagoGG : Good question!  If this issue has been resolved, you can submit the code sample in the issue as a test, and that will close the issue.

**Comment by gfyoung** [comment] 2020-01-26 18:55
Can confirm on [master](https://github.com/pandas-dev/pandas/commit/ca3bfcc54676b04ac5150c913328d26920bb2591) that the example works now.

**Comment by YagoGG** [comment] 2020-02-01 10:36
@gfyoung I can confirm that the bug was still present in 0.25, but has already been fixed in 1.0.0:

```python
In [1]: import numpy as np 
   ...: import pandas as pd 
   ...:  
   ...: x = np.linspace(0,100,1000) 
   ...: y = np.sin(x) 
   ...: df = pd.DataFrame(data=np.tile(y, (10,1)), index=np.arange(10), columns=x)                                                                                                                         

In [2]: df.reindex(columns=x*1.005).interpolate(method='linear', axis=1)                                                                                                                                   
Out[2]: 
   0.000000    0.100601    0.201201    0.301802    0.402402    0.503003    0.603604    0.704204    ...  99.795796   99.896396   99.996997   100.097598  100.198198  100.298799  100.399399  100.500000
0         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
5         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
6         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
7         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
8         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
9         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0

[10 rows x 1000 columns]

In [3]: df.reindex(columns=x*1.005).interpolate(method='linear', axis='columns')                                                                                                                           
Out[3]: 
   0.000000    0.100601    0.201201    0.301802    0.402402    0.503003    0.603604    0.704204    ...  99.795796   99.896396   99.996997   100.097598  100.198198  100.298799  100.399399  100.500000
0         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
1         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
2         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
3         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
4         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
5         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
6         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
7         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
8         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0
9         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0  ...         0.0         0.0         0.0         0.0         0.0         0.0         0.0         0.0

[10 rows x 1000 columns]
```
<details>
  <summary><b>Output of <code>pd.show_versions()</code></b></summary>
  
```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.3.0-26-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.0
numpy            : 1.17.3
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 42.0.2.post20191201
Cython           : 0.29.14
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.10.1
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : 1.3.11
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : 0.45.1
```
  
</details>

**Comment by gfyoung** [comment] 2020-02-01 10:53
@YagoGG : Thanks for re-confirming!  Since this issue has been resolved, you are welcome to submit the code sample in the issue as a test, and that will close the issue.

**Comment by YagoGG** [comment] 2020-02-02 00:37
@gfyoung just to be clear, you mean opening a PR that includes an additional test with the verbatim(ish) code sample?

I'm asking because the commit with the fix already included tests, just to avoid redundant testing.

**Comment by gfyoung** [comment] 2020-02-02 01:02
> @gfyoung just to be clear, you mean opening a PR that includes an additional test with the verbatim(ish) code sample?

Correct

**Closed** 2020-05-12 13:30 UTC
Labels: Bug, Indexing, Needs Tests, good first issue
