### ISSUE TITLE
BLD: pymysql 0.6.6

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#9608] opened 2015-03-07 00:51 UTC
looks like `pymsyql` just got updated from 0.6.3 to 0.6.6, see here: https://travis-ci.org/pydata/pandas/jobs/53409636

[changelog](https://github.com/PyMySQL/PyMySQL/blob/master/CHANGELOG)

and started breaking our builds (only 3.4 oddly)

**Comment by jreback** [comment] 2015-03-09 11:10
@jorisvandenbossche this is currently causing all builds to fail.

**Comment by jorisvandenbossche** [comment] 2015-03-09 19:52
@jreback Will try to look at this tomorrow. Maybe we can we just fix the version to 0.6.3 in the travis tests for now?

**Comment by jreback** [comment] 2015-03-09 21:40
ok I fixed the version so master will pass now.

**Comment by jorisvandenbossche** [comment] 2015-03-10 14:09
Hmm, strange, I can't reproduce this issue locally (Windows, pymysql 0.6.6, pandas master and sqlalchemy  0.9.6). I can try it later on linux

**Comment by jorisvandenbossche** [comment] 2018-07-06 22:21
We are not pinning the version of pymysql for all builds (so should test with latest), and have for the rest no complaints about something not working with pymysql, so closing this.

**Closed by jorisvandenbossche** 2018-07-06 22:21 UTC
Labels: CI, Compat, Effort Low, IO SQL, good first issue
