### ISSUE TITLE
BUG: `json_normalize` adding unexpected nesting

### ISSUE THREAD

**Issue by addisonklinke** [pandas-dev/pandas#46743] opened 2022-04-11 16:23 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

print(pd.json_normalize({'hello': 'world'}, sep='__').to_dict())
```

### Issue Description

I saw the `json_normalize` function suggested on this StackOverflow [answer](https://stackoverflow.com/a/41801708/7446465) for flattening nested dictionaries and compressing keys. In the example above, I'm confused why the value `world` is interpreted as a listed and expanded to `{0: 'world'}`

### Expected Behavior

It seems like this should output the dict unchanged, i.e. `{'hello': 'world'}` but instead it returns `{'hello': {0: 'world'}}`

Perhaps StackOverflow is misinterpreting the intended purpose of `json_normalize`? Otherwise I would consider this a bug

### Installed Versions

<details>

commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.15-76051515-generic
Version          : #202201160435~1642693824~20.04~97db1bb~dev-Ubuntu SMP Fri Jan 21
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8
pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2021.3
dateutil         : 2.8.1
pip              : 22.0.4
setuptools       : 59.5.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : None
IPython          : 8.2.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.3.18
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>

**Comment by connor-overjet** [comment] 2022-04-12 22:04
@addisonklinke Are you sure you don't mean `pd.json_normalize({'hello': 'world'}, sep='__').to_dict(orient="records")`? Pandas has a number of options for the `orient` param for `to_dict` that changes how the output appears.

**Comment by addisonklinke** [comment] 2022-04-14 17:35
@connor-overjet that would output `[{'hello': 'world'}]` which adds an extra set of square brackets. Is there another `orient` format which would preserve the JSON structure as-is?

**Comment by simonjayhawkins** [comment] 2022-06-03 18:03
Thanks @addisonklinke for the report.

Both functions are working as intended. This is not a bug.

`pd.json_normalise` creates a pandas DataFrame object (which has a Index by definition because it's a DataFrame) as expected ...

```python
pd.json_normalize({"hello": "world"}, sep="__")
```
```
   hello
0  world
```

> that would output `[{'hello': 'world'}]` which adds an extra set of square brackets

If the DataFrame contains more than one row then the output would be a list ...

```python
pd.json_normalize([{"hello": "world"}, {"hello": "world2"}]).to_dict(orient="records")
```

```
[{'hello': 'world'}, {'hello': 'world2'}]
```

For consistency, I would not expect the output data structure of a single row DataFrame to be any different from a DataFrame with more than one row.


> It's looking like my conclusion is `json_normalize` does not fulfill the intended role proposed on StackOverflow. Do you see anything I'm missing?

I think your conclusion is correct. or just access the first item in the list `print(df.to_dict(orient='records')[0])` as suggested in the StackOverflow answer.

`json_normalise` and `.to_dict()`/`.to_json()` are not intended to round trip.

feel free to look through open `.to_dict()`/`.to_json()` issues or open a new issue if you feel they should be able to create the output required. but there is no issue with `json_normalise` AFAICT so closing.

**Closed by simonjayhawkins** 2022-06-03 18:03 UTC
Labels: Bug, Needs Triage
