### ISSUE TITLE
BUG: `apply` behaviour changed when using function that returns tuple

### ISSUE THREAD

**Issue by martijnvanattekum** [pandas-dev/pandas#36042] opened 2020-09-01 15:20 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import seaborn as sns
import pandas as pd
import numpy as np

def get_mean_sd(column):
    return np.mean(column), np.std(column)

iris = sns.load_dataset("iris")[["sepal_length", "sepal_width", "petal_length", "petal_width"]]
iris.apply(get_mean_sd)
```

#### Problem description
In version 1.0, the result was a pandas series of tuples, whereas in 1.1 the result is a data frame, thus breaking existing code that depends on apply.

The result from 1.1 is
```
   sepal_length  sepal_width  petal_length  petal_width
0      5.843333     3.057333      3.758000     1.199333
1      0.825301     0.434411      1.759404     0.759693
```

#### Expected Output
The output from version 1.0 was:
```
sepal_length     (5.843333333333334, 0.8253012917851409)
sepal_width     (3.0573333333333337, 0.4344109677354946)
petal_length     (3.7580000000000005, 1.759404065775303)
petal_width     (1.1993333333333336, 0.7596926279021594)
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

For 1.0.3:
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1127.18.2.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.utf-8
LANG             : en_US.utf-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.3
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.4.0.post20200518
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

For 1.1.1:
INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1127.18.2.el7.x86_64
Version          : #1 SMP Sun Jul 26 15:27:06 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.utf-8
LANG             : en_US.utf-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.4.0.post20200518
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jbrockmendel** [comment] 2020-09-01 16:41
This looks like a duplicate of #35518.  @martijnvanattekum is that correct?

**Comment by martijnvanattekum** [comment] 2020-09-01 18:13
Yes, you are correct. I somehow did not find that report.

**Comment by simonjayhawkins** [comment] 2020-09-01 19:34
closing as duplicate

**Closed by simonjayhawkins** 2020-09-01 19:34 UTC
Labels: Bug, Needs Triage
