### ISSUE TITLE
ENH: Series should provide _repr_html_

### ISSUE THREAD

**Issue by AllenDowney** [pandas-dev/pandas#16857] opened 2017-07-07 19:36 UTC
DataFrame provides _repr_html_ so it looks great when it's displayed in a Jupyter notebook.  Why not Series?

**Comment by chris-b1** [comment] 2017-07-07 19:58
This is a duplicate of #5563 - also see stalled PR at #10300 - seems like an open issue was how to style a `Series` to visually differentiate from a `DataFrame`.  In any event, PRs welcome if you're interested!

**Closed by chris-b1** 2017-07-07 19:58 UTC

**Comment by AllenDowney** [comment] 2017-07-07 20:05
I thought this might be a duplicate, but my search didn't find it.  Thank you.

If I get a chance I will submit a PR or try to un-stall #10300

In the meantime I have a workaround.
