### ISSUE TITLE
ERR: Most consistent error handling when passing win_type='freq' in rolling

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#15969] opened 2017-04-10 20:14 UTC
Working on https://github.com/dask/dask/issues/2190 (df.rolling('5s') for dask), and I think these should all be equivalent.

```python
In [26]: import pandas as pd
In [27]: import numpy as np
In [31]: from pandas.tseries.frequencies import to_offset
In [28]: s = pd.Series(range(10), index=pd.date_range('2017', freq='s', periods=10))
```

```python
>>> s.rolling('2s')  # Case 1: correct
>>> s.rolling(window=2000000000, min_periods=1, win_type='freq')  # Case 2
>>> s.rolling(window=to_offset('2s'), min_periods=1, win_type='freq')  # Case 3
>>> s.rolling(window=pd.Timedelta('2s'), min_periods=1, win_type='freq')  # Same as 3
```

I don't *think* there are any parsing ambiguities.

Currently we have

```python
# Case 1
In [33]: s.rolling('2s')
Out[33]: Rolling [window=2000000000,min_periods=1,center=False,win_type=freq,axis=0]
```

```python
# Case 2
In [35]: s.rolling(window=2000000000, min_periods=1, win_type='freq')
```
```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-a24a29dff0ab> in <module>()
----> 1 s.rolling(window=2000000000, min_periods=1, win_type='freq')

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/generic.py in rolling(self, window, min_periods, freq, center, win_type, on, axis)
   5502                                    min_periods=min_periods, freq=freq,
   5503                                    center=center, win_type=win_type,
-> 5504                                    on=on, axis=axis)
   5505
   5506         cls.rolling = rolling

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/window.py in rolling(obj, win_type, **kwds)
   1795
   1796     if win_type is not None:
-> 1797         return Window(obj, win_type=win_type, **kwds)
   1798
   1799     return Rolling(obj, **kwds)

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/window.py in __init__(self, obj, window, min_periods, freq, center, win_type, axis, on, **kwargs)
     76         self.win_type = win_type
     77         self.axis = obj._get_axis_number(axis) if axis is not None else None
---> 78         self.validate()
     79
     80     @property

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/window.py in validate(self)
    505                 raise ValueError('Invalid win_type {0}'.format(self.win_type))
    506             if getattr(sig, self.win_type, None) is None:
--> 507                 raise ValueError('Invalid win_type {0}'.format(self.win_type))
    508         else:
    509             raise ValueError('Invalid window {0}'.format(window))

ValueError: Invalid win_type freq
```

```python
# Case 3
In [36]: s.rolling(window=to_offset('2s'), min_periods=1, win_type='freq')
```
```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-93e14a8d05f6> in <module>()
----> 1 s.rolling(window=to_offset('2s'), min_periods=1, win_type='freq')

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/pandas/core/generic.py in rolling(self, window, min_periods, freq, center, win_type, on, axis)
   5502                                    min_periods=min_periods, freq=freq,
   5503                                    center=center, win_type=win_type,
-> 5504                                    on=on, axis=axis)
   5505
   5506         cls.rolling = rolling

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/pandas/core/window.py in rolling(obj, win_type, **kwds)
   1795
   1796     if win_type is not None:
-> 1797         return Window(obj, win_type=win_type, **kwds)
   1798
   1799     return Rolling(obj, **kwds)

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/pandas/core/window.py in __init__(self, obj, window, min_periods, freq, center, win_type, axis, on, **kwargs)
     76         self.win_type = win_type
     77         self.axis = obj._get_axis_number(axis) if axis is not None else None
---> 78         self.validate()
     79
     80     @property

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/pandas/core/window.py in validate(self)
    507                 raise ValueError('Invalid win_type {0}'.format(self.win_type))
    508         else:
--> 509             raise ValueError('Invalid window {0}'.format(window))
    510
    511     def _prep_window(self, **kwargs):

ValueError: Invalid window <2 * Seconds>
```

**Comment by chris-b1** [comment] 2017-04-10 20:19
In the spirit of #15836, I'd be inclined to disallow case 2, although certainly should raise a better error message.

**Comment by TomAugspurger** [comment] 2017-04-10 20:25
> In the spirit of #15836, I'd be inclined to disallow case 2

Hmm, yeah I probably agree.

> although certainly should raise a better error message.

I've updated the original post to have the traceback with scipy installed, so yeah I better error message would be needed to prevent confusion :)

**Comment by jreback** [comment] 2017-04-10 21:35
this is a dupe of https://github.com/pandas-dev/pandas/issues/15584

and case 2 should not be supported.

**Comment by jreback** [comment] 2017-04-10 21:39
actually these all work (except case 2), except that specifying ``win_type='freq'`` is not allowed (nor should it, this would be just way too confusing, that applies to other arguments).

**Comment by jreback** [comment] 2017-04-10 21:41
I'll re-open but what is the justification for directly supporting ``win_type='freq'`` AND supporting an offset / convertible argument? that seems way to confusing. ``win_type`` is a *very* specialized argument (and invoked a completely different type of rolling window that is VERY limited - on purpose).

**Comment by TomAugspurger** [comment] 2017-04-10 21:55
Right, win_type is the issue.

The use-case is making the dask implementation a bit easier. Not super difficult to work around. And I was just surprised that

```python
In [16]: s.rolling('2s')
Out[16]: Rolling [window=2000000000,min_periods=1,center=False,win_type=freq,axis=0]

In [17]: s.rolling('2s', win_type='freq')  # TypeError
```

went down different code-paths. Not a big deal though.

**Comment by jorisvandenbossche** [comment] 2017-04-11 09:31
Can we change the `repr` of the rolling object to not show `win_type=freq` ? 
As I think this is just confusing, `win_type='freq'` isn't documented and also shouldn't work (win_type is for how the values in the window are weighted, so a whole different use case I think)

**Comment by TomAugspurger** [comment] 2017-04-11 11:28
Yeah, I'm fine with that, rather than allowing a user to specify `win_type='freq`'

**Closed** 2020-12-23 14:27 UTC
Labels: Error Reporting, Timeseries, Window
