### ISSUE TITLE
BUG: pandas groupby returns different results when one and two groups

### ISSUE THREAD

**Issue by ibigquant** [pandas-dev/pandas#58133] opened 2024-04-03 13:03 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

# df = pd.DataFrame({"a": [1, 1, 1, 1], "b": [1, 2, 3, 4]})
df = pd.DataFrame({"a": [1, 2, 2, 1], "b": [1, 2, 3, 4]})

def foo(xf):
    def bar(x):
        # here just some sample code ..
        return x['b'] + 1

    return xf.apply(bar, axis=1)

result_series = df.groupby("a", group_keys=False).apply(foo)

result_series
```

### Issue Description

it returns dataframe when there's only one group

![image](https://github.com/pandas-dev/pandas/assets/19626072/1390158c-7f98-4f17-9777-90fdaf963409)

### Expected Behavior

always returns series

![image](https://github.com/pandas-dev/pandas/assets/19626072/1e5b758b-1dd3-453c-8791-e5dbee1fc10b)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2
python                : 3.11.8.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.14.0-162.23.1.el9_1.x86_64
Version               : #1 SMP PREEMPT_DYNAMIC Tue Apr 11 19:09:37 UTC 2023
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : zh_CN.UTF-8
LANG                  : zh_CN.UTF-8
LOCALE                : zh_CN.UTF-8
pandas                : 2.2.1
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 65.5.0
pip                   : 24.0
Cython                : 3.0.9
pytest                : 8.1.1
hypothesis            : None
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.1.0
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : 8.22.2
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : 3.8.3
numba                 : 0.59.1
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
pyarrow               : 13.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.12.0
sqlalchemy            : 2.0.29
tables                : None
tabulate              : None
xarray                : None
xlrd                  : 2.0.1
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
</details>

**Comment by shriyakalakata** [comment] 2024-04-03 17:43
I have run the example above and it returned the expected behavior.

My output:
```
0    2
3    5
1    3
2    4
dtype: int64
```

Pandas version: 2.2.1

**Comment by rhshadrach** [comment] 2024-04-05 12:41
Thanks for the report, closing as a duplicate of #54992

**Closed by rhshadrach** 2024-04-05 12:41 UTC
Labels: Bug, Needs Triage
