### ISSUE TITLE
Pickling on Windows raises EOFError

### ISSUE THREAD

**Issue by alex-fe** [pandas-dev/pandas#24101] opened 2018-12-04 21:23 UTC
I am using Mac OS 10.13.6, and everything runs smoothly for me. However, I was sent a screenshot from a client running the code on Windows, and he is hitting an `EOFError` .

![program py-error](https://user-images.githubusercontent.com/32043053/49473534-2d939780-f7c7-11e8-9c2a-ab1559433ea4.jpg)

This is the code in question.

```python
if os.path.isfile(PICKLE_LOC_2):
    print('SEC pickle found')
    sec_df = pd.read_pickle(PICKLE_LOC_2)
```

**Comment by TomAugspurger** [comment] 2018-12-04 22:07
Can you provide a minimal example?  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by jschendel** [comment] 2019-05-05 17:40
Closing due to lack of minimally reproducible example. Feel free to reopen if you can provide code as requested above.

**Closed by jschendel** 2019-05-05 17:40 UTC
Labels: Needs Info
