### ISSUE TITLE
BUG: Inconsistent conversion of to_datetime

### ISSUE THREAD

**Issue by JulianWgs** [pandas-dev/pandas#36190] opened 2020-09-07 12:11 UTC
- [x] I have checked that this issue has not already been reported.
I've looked through all issues regarding `to_datetime`, but I could've missed something.
- [x] I have confirmed this bug exists on the latest version of pandas.
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

#### Code Sample, a copy-pastable example

```python
pd.to_datetime(["13.12.2020", "12.13.2020"])
# DatetimeIndex(['2020-12-13', '2020-12-13'], dtype='datetime64[ns]', freq=None)
```

#### Problem description

Two different inputs produce the same result. The reason is that the function uses a different format for different entries. I don't know what the usecase of this is, but usually all the data has the same format. The error also passes silently.

#### Expected Output
Either an error that something is wrong with the hint to use `days_first=True` or detect the format for all values and apply it.

I'm aware that the format can't always be determined, but it is possible to detect if something is wrong.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.8.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.1.1
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1.post20200622
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 0.7.4
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.1
pytables         : None
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.3.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : 0.48.0

</details>

**Comment by jreback** [comment] 2020-09-07 12:30
duplicate of #12585

a pull request to patch would be welcome

**Closed** 2020-09-07 12:30 UTC
Labels: Duplicate, Timeseries

**Comment by JulianWgs** [comment] 2020-09-07 13:04
Sorry, I missed that. Thank you for the fast response!
