### ISSUE TITLE
pandas.DataFrame.pivot_table  cannot generate a correct Pivot Table for financial data of `General Ledger`.

### ISSUE THREAD

**Issue by zefuirusu** [pandas-dev/pandas#42629] opened 2021-07-20 15:36 UTC
## description 
As I have to cope with financial data, like an accountant, pivot table is a powerful tool for me.Yet recently, calling method `pandas.DataFrame.pivot_table`, I encountered a problem.
With data of `General Ledgers` (17 columns and over 7000 rows) I had expected to get a pivot table with values = `debit amount minus credit amount` for each `journal ID`, which identifies each `journal entry`, columns = `account name`, and index = `journal ID`. According to the `primary accounting equation`, for each `journal entry` we have `sum of debit amount` equal `sum of credit amount`. Thus, sum of all data of a big pivot table, whose index is `journal ID`, whose columns is `account name` and whose values are `debit minus credit`, must be zero.
However, when having called `pandas.DataFrame.pivot_table`, I found that sum of all data of that pivot table, did not equals zero. To be carefully, I generated a pivot table with `Microsoft Excel`, and it was no doubt that sum of whole pivot table equaled zero.
## code
Talk is cheap, here is the code.
```python
#!/usr/bin/env python
from pandas import read_excel
d=read_excel(excel_file_of_gl,sheet_name='Sheet1',header=0,engine='openpyxl')
d.pivot_table(values=['drcr'],index=['jid'],columns=['accna']).to_excel(./data.xlsx')
# 'drcr' means 'debit minus credit','jid' means 'journal id', and 'accna' means 'account name'.
# open the output file, sum of all the 'drcr' value did not equaled zero, which was weird.
```

**Comment by phofl** [comment] 2021-07-20 17:20
Hey, could you provide your execl file?

**Comment by zefuirusu** [comment] 2021-07-21 16:24
No problem. yet how? could you please leave an email address?

**Comment by phofl** [comment] 2021-07-21 16:47
No not per email, in this issue so that People interested working on this can reproduce

**Comment by zefuirusu** [comment] 2021-07-22 12:58
[csgl.xlsx](https://github.com/pandas-dev/pandas/files/6862316/csgl.xlsx)
[df_pvt_question.md](https://github.com/pandas-dev/pandas/files/6862322/df_pvt_question.md)
Here's the Excel file (whose key columns have been marked red) and the Python script (in python version 3.8). And my device environment was "Linux 4.4.0-17763-Microsoft #1432-Microsoft Mon Aug 18 18:18:00 PST 2020 x86_64 GNU/Linux", or wsl on Windows 10 ltsc.

**Comment by phofl** [comment] 2021-07-25 00:34
Is the excel file minimal to reproduce the Bug? We will also need an expected result from you Bader on your minimal file

**Comment by zefuirusu** [comment] 2021-07-27 15:08
Well, in the Excel file that I uploaded, sheet "original" is the data of General Ledger, and the sheet "pivot_table" is the expected result of pivot table, where you can see the sum data is zero. 
When calling method pandas.DataFrame.pivot_table, I was expecting a table like that in the sheet "pivot_table", which of course, sum of all data must be zero.

**Comment by mroeschke** [comment] 2021-08-21 19:13
Thanks for the report so far, but as mentioned we would need a more minimal example (without a file input ideally since the claimed bug is in `pivot_table`) in order for the team to create a simple unit test based on the bug if there is one https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Since this report needs more paring down before action can be taken closing for now, but happy to reopen once we get a more minimal example.

**Closed by mroeschke** 2021-08-21 19:13 UTC
Labels: Reshaping, Needs Info
