### ISSUE TITLE
Many groupby tests depend on a bug in DataFrameGroupBy.apply

### ISSUE THREAD

**Issue by christopherzimmerman** [pandas-dev/pandas#28549] opened 2019-09-20 15:49 UTC
Discovered while fixing an issue in #28541 

A large number of tests relating to `DataFrameGroupBy.apply` depend on a bug in `apply` where the grouped column is not removed from the returned DataFrame.

Here are some examples:

- [`test_apply_chunk_view`](https://github.com/pandas-dev/pandas/blob/4edf938aedf55b9e6fbfb3199f70f857e8ec7e41/pandas/tests/groupby/test_apply.py#L366)
- [`test_apply_multiindex_fail`](https://github.com/pandas-dev/pandas/blob/4edf938aedf55b9e6fbfb3199f70f857e8ec7e41/pandas/tests/groupby/test_apply.py#L366)

There are around ~20 cases of this.

---

In general, they expect the result of something like this:

```
df = pd.DataFrame({"key": [1, 1, 1, 2, 2, 2, 3, 3, 3], "value": range(9)})
df.groupby('key').apply(lambda x: x.sum())
```

To include the "key" column in the result, which should not be the case.

```
     key  value
key
1      3      3
2      6     12
3      9     21
```

The underlying issue with `apply` is a straightforward fix, all that needs to be done is change [this return](https://github.com/pandas-dev/pandas/blob/master/pandas/core/groupby/groupby.py#L729) to use the `_group_selection_context`, but the PR will have to include updates to many tests.

**Comment by WillAyd** [comment] 2019-09-20 16:57
I think worth double checking the comprehensive functionality of `as_index`, i.e. making sure it works consistently for the reduction functions to put the groupings in the index when `True` and put in as columns when `False`

Not sure off the top of my head how that is covered in tests but would be great if you can take a look while reviewing all of this

**Comment by jbrockmendel** [comment] 2019-11-19 23:42
Not sure how much this overlaps, but I'm noticing in `_aggregate_frame` the `for name, data in self:` is yielding `data` `DataFrame`s with more columns than I expect.  I think this is explained by  `_GroupBy.__iter__` using `self.obj` instead of `self._obj_with_exclusions`.  If we change this, a handful of tests are broken, but most of thsoe are for merge ops

**Comment by rhshadrach** [comment] 2023-07-15 18:17
Closing as a duplicate of #7155.

**Closed by rhshadrach** 2023-07-15 18:17 UTC
Labels: Bug, Testing, Groupby
