### ISSUE TITLE
pandas.read_excel() close the io stream 

### ISSUE THREAD

**Issue by dujiaxin** [pandas-dev/pandas#31726] opened 2020-02-05 23:28 UTC
#### Code Sample, a copy-pastable example if possible

```python
with open(r'a.xlsx','rb') as f: # input the .xlsx
    df_top = pd.read_excel(f,'Sheet1',encoding = 'utf-8').iloc[:,0:2]
    df_less = pd.read_excel(f,'Sheet2',encoding = 'utf-8').iloc[:,0:2]
```
#### Problem description

The first read_excel() works fine. But the second read_excel() get the following:
Traceback (most recent call last):
  File "xxx.py", line 127, in <module>
    df_less = pd.read_excel(f,'Sheet2',encoding = 'utf-8').iloc[:,0:2]
  File "xxx\pandas\io\excel\_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "xxx\pandas\io\excel\_base.py", line 821, in __init__
    self._reader = self._engines[engine](self._io)
  File "xxx\pandas\io\excel\_xlrd.py", line 21, in __init__
    super().__init__(filepath_or_buffer)
  File "xxx\pandas\io\excel\_base.py", line 350, in __init__
    filepath_or_buffer.seek(0)
ValueError: seek of closed file

It seems the read_excel() change the io object "f". Is that some new feature in 1.0? Older versions don't have the problem.

I think it should be fixed because a function should not change the outer variable.

#### Expected Output
read_excel() should not change the io stream and should be able to read the same io stream several times.
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.2
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.3.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
numba            : None

</details>

**Comment by mroeschke** [comment] 2020-02-06 05:56
Thanks. I think this is a duplicate of https://github.com/pandas-dev/pandas/issues/31467

**Closed by mroeschke** 2020-02-06 05:56 UTC
