### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by strpeter** [pandas-dev/pandas#54195] opened 2023-07-19 14:42 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})
df['num'] = df.duplicated
# display(df, metadata=['text/markdown'])
print(df)
```

### Issue Description

1. Within Jupyter, the kernel dies before any error can be displayed.

2. In an isolated script, the run fails with an appearing `RecursionError`, which makes the tracing difficult:
```
RecursionError: maximum recursion depth exceeded
```

### Expected Behavior

Print `<function df.duplicated at 0x...>` in the column `num`.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6    
python           : 3.10.11.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_Switzerland.1252

pandas           : 2.0.3
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.2
Cython           : None
pytest           : 7.4.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by mroeschke** [comment] 2023-07-19 17:30
Not sure how practical this is to fix since you are essentially storing `df` in `df` hence the recursion.

If you really need this to work you can make a copy

```
In [2]: import pandas as pd
   ...: 
   ...: df = pd.DataFrame({
   ...:     'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
   ...:     'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
   ...:     'rating': [4, 4, 3.5, 15, 5]
   ...: })
   ...: df['num'] = df.copy().duplicated

In [3]: df
Out[3]: 
     brand style  rating                                                num
0  Yum Yum   cup     4.0  <bound method DataFrame.duplicated of      bra...
1  Yum Yum   cup     4.0  <bound method DataFrame.duplicated of      bra...
2  Indomie   cup     3.5  <bound method DataFrame.duplicated of      bra...
3  Indomie  pack    15.0  <bound method DataFrame.duplicated of      bra...
4  Indomie  pack     5.0  <bound method DataFrame.duplicated of      bra...
```

**Comment by jbrockmendel** [comment] 2023-07-19 20:24
Seems likely OP intend to call duplicated, not pass the function?

**Comment by mroeschke** [comment] 2023-07-19 22:00
From the `Expected Behavior` section it seems they wanted to repr to show that it stored the method I think

**Comment by strpeter** [comment] 2023-07-27 11:34
Thank you for your feedback. My issue was that the error message is cumbersome to debug. It would have been useful to receive a more meaningful flag why this recursion appeared at all. It does not happen for most other cases when storing a method within the object.

**Comment by phofl** [comment] 2024-03-18 02:08
yeah this is really odd, I don#t think that we want to do anything here, closing

**Closed by phofl** 2024-03-18 02:08 UTC
Labels: Bug, Output-Formatting, Closing Candidate
