### ISSUE TITLE
Category dtype lost after pd.melt

### ISSUE THREAD

**Issue by 77QingLiu** [pandas-dev/pandas#19185] opened 2018-01-11 13:26 UTC
#### Python Code

* **Before pd.melt**
```python
import pandas as pd
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                    'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})
df['A'] = df.A.astype('category')
df
```
![image](https://user-images.githubusercontent.com/32193271/34827065-e751911e-f713-11e7-8306-d68fba62d12d.png)
```python
df.A.dtype
```
![image](https://user-images.githubusercontent.com/32193271/34827604-a8323d06-f715-11e7-80d6-d7d07a6be5e5.png)

* **After pd.melt**
```python
pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])
```
![image](https://user-images.githubusercontent.com/32193271/34827660-e2112ac8-f715-11e7-97ab-e60d5880376d.png)

```python
df.A.dtype
```
![image](https://user-images.githubusercontent.com/32193271/34827628-c240e42c-f715-11e7-95d0-443aac91ebf6.png)

#### Problem description
As the example above. column A is category dtype before pd.melt. 
However, the category dtype lost after pd.melt.

#### Expected Output
Expected consistence before and after pd.melt
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.3.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.21.1
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.5.0.post20170921
Cython: 0.26.1
numpy: 1.13.3
scipy: 0.19.1
pyarrow: None
xarray: None
IPython: 6.1.0
sphinx: 1.6.3
patsy: 0.4.1
dateutil: 2.6.1
pytz: 2017.3
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
feather: None
matplotlib: 2.1.0
openpyxl: 2.4.8
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.2
lxml: 4.1.0
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.13
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by chris-b1** [comment] 2018-01-11 13:52
Thanks for the report, this is a duplicate of #15853, PR to fix welcome!

**Closed by chris-b1** 2018-01-11 13:52 UTC
