### ISSUE TITLE
QST: Integer floordiv by nullable integer series containing zero

### ISSUE THREAD

**Issue by brandon-b-miller** [pandas-dev/pandas#39847] opened 2021-02-16 19:18 UTC
- [ ] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

---

#### Question about pandas

Hello Pandas, while working on cuDF binops, I noticed this edge case:

```python
1 // pd.Series([0], dtype='Int64')
```

```
0    0
dtype: Int64
```

I'm not 100% sure what the right behavior here is, but we're thinking it's maybe to raise. I was wondering if anyone on the pandas side had thought about this and has strong feelings about what the answer _should_ be here. For standard division, casting to float and returning `inf` seems sensible. But with floor division the point is to return an int. 

Thanks so much for any thoughts.

**Comment by jorisvandenbossche** [comment] 2021-02-17 08:38
I think we "simply" follow numpy's behaviour in this case:

```
In [86]: np.array([1]) // np.array([0])
/home/joris/miniconda3/envs/dev/bin/ipython:1: RuntimeWarning: divide by zero encountered in floor_divide
  #!/home/joris/miniconda3/envs/dev/bin/python
Out[86]: array([0])
```

There have been some changes to floordiv in the latest numpy release related to this 1 // 0 case: https://numpy.org/doc/stable/release/1.20.0-notes.html#changed-behavior-of-divmod-1-0-and-related-functions. But that is for the float behavoiur, not integer. The PR changing it (https://github.com/numpy/numpy/pull/16161) mentions the integer case as well, but it was decided to focus on float because there the expected result is clear (for integer floordiv, if you want an integer as result, the only option is 0 or raise an error).

**Comment by jorisvandenbossche** [comment] 2021-02-17 08:39
Ah, and also see https://github.com/pandas-dev/pandas/issues/30188 for a longer discussion on this topic, will close this issue in favor of that.

**Comment by jorisvandenbossche** [comment] 2021-02-17 08:39
Duplicate of #30188

**Closed by jorisvandenbossche** 2021-02-17 08:39 UTC
Labels: Needs Triage, Usage Question
