### ISSUE TITLE
DOC: can't switch to the docs for a different version of pandas

### ISSUE THREAD

**Issue by dmitriyshashkin** [pandas-dev/pandas#46615] opened 2022-04-02 14:29 UTC
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

Any page

### Documentation problem

When I try to see the docs for a different pandas version and chose any version in the top right version select widget I get redirected to https://pandas.pydata.org/docs/dev/undefined and get 404 error

Might have something to do with the error I see in the browser console:

![Screenshot from 2022-04-02 18-26-34](https://user-images.githubusercontent.com/11873939/161387817-bdcf1560-f1b7-4d29-b46d-b380854a21ad.png)

### Suggested fix for documentation

Fix the version select widget  so it redirects to the documentation for the chosen version

**Comment by simonjayhawkins** [comment] 2022-04-03 13:52
https://pandas.pydata.org/pandas-docs/stable/ is now linked to https://pandas.pydata.org/pandas-docs/version/1.4.2/ since the release.

the version switcher still works for https://pandas.pydata.org/pandas-docs/version/1.4.1/ 

the version switcher does not work for the dev docs either. https://pandas.pydata.org/pandas-docs/dev/

so I assume that it is not directly related to the release, but maybe something that has been merged to master recently. Any changes to the web folders are uploaded to the web on merge to main and not tied to the release.

**Comment by samyberkane04** [comment] 2022-04-04 12:17
@dmitriyshashkin
can i work on this issue please ?

**Comment by dmitriyshashkin** [comment] 2022-04-05 11:46
@samyberkane04 I don't think I'm the right person to ask this. I'm just the user, not the maintainer. But if for some unknown reason you need my opinion I certainly don't mind yo fixing this issue :-)

**Comment by jorisvandenbossche** [comment] 2022-04-05 15:26
This is caused by a change in the upstream theme, see https://github.com/pydata/pydata-sphinx-theme/pull/604. So short-term fix is pinning pydata-sphinx-theme to 0.8.0, and the longer term fix is to update our versions.json file to follow the required changes.

**Comment by simonjayhawkins** [comment] 2022-06-22 13:17
removing milestone for now.

**Closed** 2022-09-16 17:32 UTC
Labels: Bug, Docs, Web
