### ISSUE TITLE
Unraisable error with TypeError: Cannot change data-type for object array

### ISSUE THREAD

**Issue by gnilrets** [pandas-dev/pandas#21630] opened 2018-06-26 00:16 UTC
#### Code Sample

```python
import pandas as pd
import datetime

df = pd.DataFrame({
    'my_date': [None],
    'my_datetime': [datetime.datetime.now()]
})

def doit(row):
    return len(row.apply(lambda v: str(v)))

def tryit(row):
    try:
        result = doit(row)
    except Exception as err:
        print("ERROR: {}".format(err))
        raise err
    return result
        
df.apply(tryit, axis=1)
```
#### Problem description

The above code will simultaneously print "ERROR: Cannot change data-type for object array." AND NOT raise an error.  Which seems impossible to me, since the exception should be re-raised.

This is a problem because I've got some code that is trying to catch errors, and whatever is going on above is give false-positives.  If I remove the try/except block, I get no errors.  But if it's there, errors are caught.  

I tried this in Pandas 0.22.0 and 0.23.1.  It ONLY happens in the latest version, 0.23.1.

It also only seems to be an issue if a datetime and None values are part of the row.

**Comment by WillAyd** [comment] 2018-06-26 00:33
I haven't looked in detail but I wouldn't be surprised if the runtime evaluation of your UDF occurs at a point in the call stack that catches a particular type of `Exception` before applying the function in some other fashion. In that case the flow is something like:

- Your function fails
- Your function catches the error, prints a message
- Your functions propoagates the error up the stack
- A call further up the stack catches the Exception, attempts lazy evaluation in some other fashion
- The "other fashion" succeeds in execution, yielding the result

If that's the case I think it would be generally tough to ever guarantee that error handling within a UDF would not interfere with what pandas is doing (especially if catching something as generic as Exception) but certainly welcome to take a look and see if there's a way to support that

**Comment by gnilrets** [comment] 2018-06-26 03:01
Any idea where that lazy evaluation could be happening?  Perhaps I could raise a certain kind of exception that wouldn't be caught by the lazy evaluation.  

I've often struggled with trying to deal with Pandas errors.  I do a lot of ETL with Pandas, and in many cases I don't want some strangeness in a single record to raise an error for an entire data pipeline.  I've specifically built a package in an attempt to handle this situation (https://github.com/inside-track/pandas-mapper).  It worked great with 0.22.0, but I'm having trouble with this scenario in 0.23.1.

**Comment by WillAyd** [comment] 2018-06-26 03:11
If you put a breakpoint in your except clause you should be able to debug the entire stack trace. Here's the lowest frame that throws:

https://github.com/pandas-dev/pandas/blob/1033e8b1195d4071253889ada60523832285354c/pandas/core/apply.py#L238

As you can see that alone is in fact catching an Exception, so should confirm my original thinking.

Just as a general design principle I'd question trying to catch Exceptions in your UDFs generally. You are basically interfering with the exception handling that pandas (or any arbitrary package) would offer during execution of the UDF. 

Is it not possible to put your exception handling outside of the UDF? That seems like a much safer route:

```python
try:
  df.apply(tryit, axis=1)  # Assuming you removed except clause from tryit
except Exception as e:  
  print("Error occurred!")
  raise e
```

**Comment by eric-wieser** [comment] 2018-06-26 07:48
Rethrowing it as a `BaseException` will cause it to not be caught by `pandas`

**Comment by jbrockmendel** [comment] 2022-01-10 19:29
cant reproduce on master, likely because libreduction paths have been removed.  Closing, can re-open if there's a different reproducer.

**Closed by jbrockmendel** 2022-01-10 19:29 UTC
Labels: Bug, Error Reporting, Apply
