### ISSUE TITLE
TypeError for mixed-type indices in python3

### ISSUE THREAD

**Issue by normanius** [pandas-dev/pandas#20900] opened 2018-05-01 11:30 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
table = pd.DataFrame(data=np.random.randn(5,2), index=[4,1,'foo',3,'bar'])
table = table.sort_index()
```
#### Problem description

The code above works in python2. However, in python3 a `TypeError` is raised: 
```
TypeError: '<' not supported between instances of 'str' and 'int'
```
The reason for this is described [here](https://stackoverflow.com/questions/50097704): mixed-type sequencing cannot be sorted anymore just like this. 

#### Expected Output

No exception when calling `sort_index` in python3.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None

pandas: 0.22.0
pytest: None
pip: 10.0.0
setuptools: 39.0.1
Cython: None
numpy: 1.14.2
scipy: 1.0.1
pyarrow: None
xarray: None
IPython: 6.3.1
sphinx: None
patsy: None
dateutil: 2.7.2
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.2.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by normanius** [comment] 2018-05-01 11:33
I am currently using this workaround that works for my type of indices (ints and strings).

```
import numpy as np
import pandas as pd 

# Stringify whatever needs to be converted.
# In this example: only ints are stringified.
def toString(x):
    if isinstance(x,int):
        x = '%03d' % x
    return x
# Stringify an index tuple.
def idxToString(idx):
    if isinstance(idx, tuple):
        idx = list(idx)
        for i,x in enumerate(idx):
            idx[i] = toString(x)
        return tuple(idx)
    else:
        return toString(idx)
# Replacement for pd.IndexSlice
class IndexSlice(object):
    @staticmethod
    def _toString(arg):
        if isinstance(arg, slice):
            arg = slice(toString(arg.start),
                        toString(arg.stop),
                        toString(arg.step))
        else:
            arg = toString(arg)
        return arg

    def __getitem__(self, arg):
        if isinstance(arg, tuple):
            return tuple(map(self._toString, arg))
        else:
            return self._toString(arg)

# Build the table.
index = [(10,3),(10,1),(2,2),('foo',4),('bar',5)]
index = pd.MultiIndex.from_tuples(index)
data = np.random.randn(len(index),2)
table = pd.DataFrame(data=data, index=index)
# 1) Stringify the index.
table.index = table.index.map(idxToString)
# 2) Sort the index.
table = table.sort_index()
# 3) Create an IndexSlice that applies the same
#    stringification rules. (Replaces pd.IndexSlice)
idx = IndexSlice()
# Now, the table rows can be accessed as usual.
table.loc[idx[10],:]
table.loc[idx[:10],:]
table.loc[idx[:'bar',:],:]
table.loc[idx[:,:2],:]
```

**Comment by TomAugspurger** [comment] 2018-05-01 11:36
FYI, the example in your original post doesn't run because `index` isn't defined.

I think we deliberately choose to follow how the language does things here. NumPy does the same ("sorts" on Py2, raises on Py3).

**Comment by normanius** [comment] 2018-05-01 11:56
> FYI, the example in your original post doesn't run because index isn't defined.
Fixed!

> I think we deliberately choose to follow how the language does things here. NumPy does the same ("sorts" on Py2, raises on Py3).
I agree that the [new ordering policy in python3](https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons) is a global change that not necessarily needs to be compensated for in all cases. However, as the index is represented internally by a `Categorical` object (and not just plain lists) and the fact that indices need to be lex-sorted for certain operations on the table (for example the notationally efficient slicing operators), I expect pandas to provide means to sort the indices such that these elementary operations do work. 

The alternative would be to prevent mixed-type indices all the way. Or to provide a cook-book recipe on how to deal with mixed-type indices.

**Comment by normanius** [comment] 2018-05-01 11:59
Here is an example with mixed-type indices that requires a table to be lex-sorted and currently fails on pandas3.

```
import pandas as pd
import numpy as np
index = [(10,3),(10,1),(2,2),('foo',4),('bar',5)]
index = pd.MultiIndex.from_tuples(index)
data = np.random.randn(len(index),2)
table = pd.DataFrame(data=data, index=index)

idx=pd.IndexSlice
table.loc[idx[:10,:],:]
# The last line will raise an UnsortedIndexError because 
# 'foo' and 'bar' appear in the wrong order.
```

**Comment by jreback** [comment] 2018-05-01 12:11
this is using pandas in a very non-idiomatic way as mixed types are not easily represented, except by object type. that said, the sorting mechanisms internally for object types could use ``safe_sort`` (see ``pandas.core.sorting``) which handles correctly these mixed types cases

**Comment by mroeschke** [comment] 2020-04-04 04:48
This looks like a duplicate of https://github.com/pandas-dev/pandas/issues/17010. Closing

**Closed by mroeschke** 2020-04-04 04:48 UTC
Labels: 2/3 Compat
