### ISSUE TITLE
BUG: pd.DataFrame.replace() with value=pd.NA in pandas v1.5.0 and v1.5.1 crushes python kernel

### ISSUE THREAD

**Issue by romanov-o** [pandas-dev/pandas#49439] opened 2022-11-01 12:56 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

pd.DataFrame([0,1,2,3]).replace(0, pd.NA)
```

### Issue Description

pd.DataFrame.replace() with value=pd.NA in pandas v1.5.0 and v1.5.1 crushes python kernel:

RecursionError: maximum recursion depth exceeded while calling a Python object

### Expected Behavior

<pre>
      0
0    &lt;NA&gt;
1     1
2     2
3     3
</pre>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.10.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1251

pandas           : 1.5.1
numpy            : 1.21.4
pytz             : 2021.3
dateutil         : 2.8.2
setuptools       : 57.4.0
pip              : 22.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.30.1
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.0
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by phofl** [comment] 2022-11-01 13:39
Hi, thanks for your report.
Duplicate of #45725

**Closed by phofl** 2022-11-01 13:39 UTC
Labels: Bug, Needs Triage

**Comment by gusutabopb** [comment] 2022-12-12 08:12
@phofl This issue is still present in 1.5.2 (worked fine in 1.4.x):

```python
pd.Series([0.0, 1.0]).replace(0.0, pd.NA)
```
throws
```
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Current work around I found is to cast to object before `replace`:

```python
pd.Series([0.0, 1.0]).astype(object).replace(0.0, pd.NA)
```
