### ISSUE TITLE
DOC: Docstrings Formatting error PR09,PR08 in pandas.DataFrame

### ISSUE THREAD

**Issue by josibake** [pandas-dev/pandas#28702] opened 2019-10-01 03:13 UTC
fix errors PR09,PR08 listed below:

```
pandas.DataFrame: Parameter "data" description should finish with "."
pandas.DataFrame: Parameter "index" description should finish with "."
pandas.DataFrame: Parameter "columns" description should finish with "."
pandas.DataFrame: Parameter "dtype" description should finish with "."
pandas.DataFrame: Parameter "copy" description should finish with "."
pandas.DataFrame.insert: Parameter "loc" description should finish with "."
pandas.DataFrame.insert: Parameter "column" description should start with a capital letter
pandas.DataFrame.insert: Parameter "column" description should finish with "."
pandas.DataFrame.lookup: Parameter "row_labels" description should finish with "."
pandas.DataFrame.lookup: Parameter "col_labels" description should finish with "."
pandas.DataFrame.corr: Parameter "method" description should finish with "."
pandas.DataFrame.corrwith: Parameter "method" description should finish with "."
pandas.DataFrame.mode: Parameter "axis" description should finish with "."
pandas.DataFrame.rank: Parameter "method" description should finish with "."
pandas.DataFrame.rank: Parameter "na_option" description should finish with "."
pandas.DataFrame.sem: Parameter "skipna" description should finish with "."
pandas.DataFrame.sem: Parameter "level" description should finish with "."
pandas.DataFrame.std: Parameter "skipna" description should finish with "."
pandas.DataFrame.std: Parameter "level" description should finish with "."
pandas.DataFrame.var: Parameter "skipna" description should finish with "."
pandas.DataFrame.var: Parameter "level" description should finish with "."
pandas.DataFrame.align: Parameter "axis" description should finish with "."
pandas.DataFrame.align: Parameter "level" description should finish with "."
pandas.DataFrame.align: Parameter "fill_value" description should finish with "."
pandas.DataFrame.align: Parameter "method" description should finish with "."
pandas.DataFrame.align: Parameter "fill_axis" description should finish with "."
pandas.DataFrame.align: Parameter "broadcast_axis" description should finish with "."
pandas.DataFrame.drop_duplicates: Parameter "subset" description should finish with "."
pandas.DataFrame.drop_duplicates: Parameter "inplace" description should finish with "."
pandas.DataFrame.duplicated: Parameter "subset" description should finish with "."
pandas.DataFrame.idxmax: Parameter "axis" description should finish with "."
pandas.DataFrame.idxmin: Parameter "axis" description should finish with "."
pandas.DataFrame.reindex: Parameter "index, columns" description should finish with "."
pandas.DataFrame.reindex: Parameter "method" description should finish with "."
pandas.DataFrame.reindex_like: Parameter "method" description should finish with "."
pandas.DataFrame.pivot_table: Parameter "aggfunc" description should finish with "."
pandas.DataFrame.pivot_table: Parameter "fill_value" description should finish with "."
pandas.DataFrame.pivot_table: Parameter "margins" description should finish with "."
pandas.DataFrame.pivot_table: Parameter "dropna" description should finish with "."
pandas.DataFrame.sort_values: Parameter "by" description should finish with "."
pandas.DataFrame.unstack: Parameter "level" description should finish with "."
pandas.DataFrame.unstack: Parameter "fill_value" description should finish with "."
pandas.DataFrame.asfreq: Parameter "method" description should finish with "."
pandas.DataFrame.asfreq: Parameter "how" description should finish with "."
pandas.DataFrame.asfreq: Parameter "normalize" description should finish with "."
pandas.DataFrame.slice_shift: Parameter "periods" description should finish with "."
pandas.DataFrame.tshift: Parameter "periods" description should finish with "."
pandas.DataFrame.tshift: Parameter "freq" description should finish with "."
pandas.DataFrame.tshift: Parameter "axis" description should finish with "."
pandas.DataFrame.tz_localize: Parameter "level" description should finish with "."
pandas.DataFrame.tz_localize: Parameter "copy" description should finish with "."
pandas.DataFrame.tz_localize: Parameter "ambiguous" description should finish with "."
pandas.DataFrame.tz_localize: Parameter "nonexistent" description should finish with "."
pandas.DataFrame.plot: Parameter "data" description should finish with "."
pandas.DataFrame.plot: Parameter "kind" description should finish with "."
pandas.DataFrame.plot: Parameter "use_index" description should finish with "."
pandas.DataFrame.plot: Parameter "grid" description should finish with "."
pandas.DataFrame.plot: Parameter "legend" description should finish with "."
pandas.DataFrame.plot: Parameter "style" description should finish with "."
pandas.DataFrame.plot: Parameter "logx" description should finish with "."
pandas.DataFrame.plot: Parameter "logy" description should finish with "."
pandas.DataFrame.plot: Parameter "loglog" description should finish with "."
pandas.DataFrame.plot: Parameter "rot" description should finish with "."
pandas.DataFrame.plot: Parameter "colorbar" description should finish with "."
pandas.DataFrame.plot: Parameter "position" description should finish with "."
pandas.DataFrame.plot: Parameter "mark_right" description should finish with "."
pandas.DataFrame.from_records: Parameter "index" description should finish with "."
pandas.DataFrame.from_records: Parameter "exclude" description should finish with "."
pandas.DataFrame.from_records: Parameter "columns" description should finish with "."
pandas.DataFrame.from_records: Parameter "coerce_float" description should finish with "."
pandas.DataFrame.from_records: Parameter "nrows" description should finish with "."
pandas.DataFrame.to_parquet: Parameter "partition_cols" description should finish with "."
pandas.DataFrame.to_pickle: Parameter "protocol" description should finish with "."
pandas.DataFrame.to_json: Parameter "orient" description should finish with "."
pandas.DataFrame.to_msgpack: Parameter "path" description should finish with "."
```

This is a subset of #28602 and #27977

**Comment by mroeschke** [comment] 2021-07-21 05:07
Looks like a duplicate of https://github.com/pandas-dev/pandas/issues/28602. Let's centralize discussion there. Closing.

**Closed by mroeschke** 2021-07-21 05:07 UTC
Labels: Docs
