### ISSUE TITLE
BUG: rolling does not accept MultiIndex name

### ISSUE THREAD

**Issue by metazoic** [pandas-dev/pandas#38877] opened 2021-01-01 09:50 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

If
```python
df = pandas.DataFrame()
df['date'] = pandas.date_range('2021-1-1', '2021-1-5', freq='h')
df.loc[df.date <= '2021-1-3', 'category'] = 'A'
df.loc[df.date > '2021-1-3', 'category'] = 'B'
df.set_index(['category','date'], inplace=True)
df['value'] = 1
```
then
```python
df.groupby('category').rolling('D', on='date')
```
breaks with
```python
ValueError: invalid on specified as date, must be a column (of DataFrame), an Index or None
```

#### Problem description

The [documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html?highlight=rolling#pandas.DataFrame.rolling) states that the `on` argument can be a `MultiIndex` level (and then confusingly adds "rather than the DataFrame's index").

#### Expected Output

`rolling` should accept a `MultiIndex` level. Interestingly,
```python
df.groupby('category').resample('D', level='date')
```
works, but it would be nice to unify the interfaces: `resample` accepts `level` and `on` for index and column respectively, while `rolling` accepts `on` for both.

**Comment by venaturum** [comment] 2021-01-01 10:52
I don't think the groupby is needed to illustrate the bug here

`df.rolling('D', on='date')`

fails with the same error

**Comment by venaturum** [comment] 2021-01-01 12:18
If we add

```
elif self.on in self.obj.index.names:
    self._on = self.obj.index.get_level_values(self.on)
```

to BaseWindow.__init__ on line 127 in pandas/core/window/rolling.py  then the following works

```
>>> df.groupby('category').rolling('D', on='date')
RollingGroupby [window=D,min_periods=1,center=False,axis=0,on=date,method=single]
```

Continuing the method chain with something like .sum gives us:

```
category category date
A        A        2021-01-01 00:00:00    1.0
                  2021-01-01 01:00:00    2.0
                  2021-01-01 02:00:00    3.0
                  2021-01-01 03:00:00    4.0
                  2021-01-01 04:00:00    5.0
...                                      ...
B        B        2021-01-04 20:00:00   24.0
                  2021-01-04 21:00:00   24.0
                  2021-01-04 22:00:00   24.0
                  2021-01-04 23:00:00   24.0
                  2021-01-05 00:00:00   24.0

[97 rows x 1 columns]
```

I thought the repeated category in the index might have been buggy but from discussions in #38737 maybe it is by design.

Happy to take this one, make changes and write tests, if I'm on the right track, but perhaps there needs to be a decision around whether the rolling should use a "level" parameter for index names (to be consistent with resample) as @metazoic suggested

**Comment by mroeschke** [comment] 2021-01-02 02:21
Thanks for the report @metazoic. We have a similar request in https://github.com/pandas-dev/pandas/issues/34642, so I'm going to consolidate the discussion to that issue and close this one. Happy to have a pull request implementing this feature.

**Closed by mroeschke** 2021-01-02 02:21 UTC
Labels: Bug, Needs Triage
