### ISSUE TITLE
Rolling Rank issues in pandas 

### ISSUE THREAD

**Issue by qirenjie2011** [pandas-dev/pandas#20602] opened 2018-04-04 05:58 UTC
When doing some math works in pandas,  the rolling function is very useful, such as pd.rolling().mean() or 
pd.rolling().max(). 
Here is my problem: when I want to get a time-series rank in a Series or a column in DataFrame, there is no function like pd.rolling().rank().  Is there any function can work as pd.rolling().rank() ?

**Comment by qirenjie2011** [comment] 2018-04-09 02:51
0    2.11
1    0.71
2   -1.07
3    0.09
4   -0.37
5    2.45
6    0.66
7   -1.08
8   -0.65
9   -0.22

like this. I want to use a function like pd.rolling(window=3).rank() and get the result below. Each number is the rank of past three period number.
0    nan
1    nan
2    1
3    2
4    2
5    3
6    2
7    1
8    2
9    3

**Comment by jreback** [comment] 2018-04-09 03:08
should we actual copy pastable code for construction -

**Comment by qirenjie2011** [comment] 2018-04-09 04:17
series_a = pd.Series([2.11,0.71,-1.07,0.09,-0.37,2.45,0.66,-1.08,-0.65,-0.22])

and I don't know the next step to get  a time-series rank of the series.

**Comment by jreback** [comment] 2018-04-09 16:28
you can do something like this:

```
In [8]: series_a.rolling(3).apply(lambda x: Series(x).rank()[0])
Out[8]: 
0    NaN
1    NaN
2    3.0
3    3.0
4    1.0
5    2.0
6    1.0
7    3.0
8    3.0
9    1.0
dtype: float64

```
duplicate of #9481

**Closed by jreback** 2018-04-09 16:28 UTC

**Comment by qirenjie2011** [comment] 2018-04-10 01:41
Thanks bro!

**Comment by d6tdev** [comment] 2019-02-15 16:18
I need to get the last value so `series_a.rolling(3).apply(lambda x: Series(x).rank().values[-1])`
