### ISSUE TITLE
ENH: Add some features like R data.table's fread() function.

### ISSUE THREAD

**Issue by b-niu** [pandas-dev/pandas#35043] opened 2020-06-28 15:01 UTC
#### Is your feature request related to a problem?

The fread() function in R library data.table has many features which are very usefull.

### 1. An argument treat tables with untidy columns
If we get a CSV file with shorter header line than table content, just like:
>A,B,C
>a,1,123,5,6
>b,123,3,3
>c,123,555,123  

By using "fill = TRUE", we can easily read it into R:
```
library(data.table)

df1 <- fread("test.csv", sep = ",", header = TRUE, fill = TRUE)
print.data.frame(df1)

  A   B   C  V4 V5
1 a   1 123   5  6
2 b 123   3   3 NA
3 c 123 555 123 NA
```

### 2. An argument skip to one line with particular pattern

If we get an VCF file just like this:
>##fileformat=VCFv4.2
>##FILTER=<ID=Bias,Description="Strand Bias">
>##FILTER=<ID=Cluster0bp,Description="Two somatic variants are within 0 bp">
>##FILTER=<ID=DIFF0.05,Description="Non-somatic or LOH and allele frequency difference < 0.05">
>##FILTER=<ID=InDelLikely,Description="Likely Indels are not considered somatic">
>#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
>chr2	79314684	.	G	C	154.0	PASS	AC=3;AF=0.273;AN=11;DP=146;SOMATIC
>chr2	119750833	.	G	T	165.0	PASS	AC=3;AF=0.273;AN=11;DP=149;SOMATIC
>chr2	203964409	.	G	A	89.0	PASS	AC=2;AF=0.250;AN=8;DP=137

By using "skip = "#CHROM"", fread() can search the whole file, and jump to the first line with the pattern "#CHROM",     
and read it into R:  
```
library(data.table)

df2 <- fread("test.vcf", skip = "#CHROM")
print.data.frame(df2)

  #CHROM       POS ID REF ALT QUAL FILTER                               INFO
1   chr2  79314684  .   G   C  154   PASS AC=3;AF=0.273;AN=11;DP=146;SOMATIC
2   chr2 119750833  .   G   T  165   PASS AC=3;AF=0.273;AN=11;DP=149;SOMATIC
3   chr2 203964409  .   G   A   89   PASS          AC=2;AF=0.250;AN=8;DP=137
```
#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by WillAyd** [comment] 2020-06-30 16:36
The second item I think is a duplicate of #32072

**Comment by StevenLi-DS** [comment] 2020-07-01 22:46
I'm not quite sure if the first one is a good idea. If you have a problematic file, you have a problematic file. 
How could you tell the header is  `A, B, C, V4, V5` instead of `V1, V2, A, B, C` or `A, V2, B, V4, C`.

**Comment by b-niu** [comment] 2020-07-03 02:42
Thanks for sharing your opinion, @StevenLi-DS . 
Because of the research area, I treat that the table is left aligned defaultly. Table files with this format is quitely ubiquitous in biological data. Manny biological software add information columns with no header at the end of each line...

**Comment by TomAugspurger** [comment] 2020-09-04 14:48
@b-niu personally, I'd recommend something like

```python
df = pd.read_csv(file, skiprows=0,  header=False)
```

And then manually handle the names (perhaps reading in the first line of the file).

**Comment by devrimcavusoglu** [comment] 2020-10-14 10:14
Yes, I agree with @TomAugspurger 's suggestion, I was a former R user, then it was a fancy tool to fill the headers, but @StevenLi-DS has a great point, it comes with some sort of confusion. For the second option I already opened an issue for the problem, consider taking a look at the discussion of [#32072](https://github.com/pandas-dev/pandas/issues/32072)

**Comment by mroeschke** [comment] 2021-08-08 16:47
Thanks for the suggestion, but it appears there's not much enthusiasm for this feature request and the `read_csv` work around is a suitable pandas way of handling this. Closing but happy to reopen if there is further support from the core team and community.

**Closed by mroeschke** 2021-08-08 16:47 UTC
Labels: Enhancement, Needs Discussion
