### ISSUE TITLE
BUG: ArrowExtensionArray' object has no attribute 'to_pydatetime when using  to_sql command with a dataframe with date columns

### ISSUE THREAD

**Issue by FerriLuli** [pandas-dev/pandas#52046] opened 2023-03-17 12:59 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import polars as pl

query = "SELECT getdate(), t.* FROM TABLE"
df_sql = pl.read_sql(query, connection_string_db1)
df_sql.schema
df2 = df_sql.to_pandas(use_pyarrow_extension_array=True)
df2.to_sql('table_name', connection_string_db2, if_exists='replace')
```

### Issue Description

This issue persisted from the 2.0.0rc0 version, I made the tests using the same code i've used in the issue https://github.com/pandas-dev/pandas/issues/51859 and made the confirmations about the code atualization looking at the file `pandas-2.0.0rc1\pandas\core\arrays\arrow\array.py` . 
But even so the error `ArrowExtensionArray' object has no attribute 'to_pydatetime` continues to happen. 

Full trace error <details>
```AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14268\424779397.py in <module>
----> 1 df_sql.to_pandas(use_pyarrow_extension_array=True).to_sql('teste_2', con, if_exists='replace')

~\Anaconda3\lib\site-packages\pandas\core\generic.py in to_sql(self, name, con, schema, if_exists, index, index_label, chunksize, dtype, method)
   2868         from pandas.io import sql
   2869 
-> 2870         return sql.to_sql(
   2871             self,
   2872             name,

~\Anaconda3\lib\site-packages\pandas\io\sql.py in to_sql(frame, name, con, schema, if_exists, index, index_label, chunksize, dtype, method, engine, **engine_kwargs)
    765 
    766     with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
--> 767         return pandas_sql.to_sql(
    768             frame,
    769             name,

~\Anaconda3\lib\site-packages\pandas\io\sql.py in to_sql(self, frame, name, if_exists, index, index_label, schema, chunksize, dtype, method, engine, **engine_kwargs)
   1914         )
   1915 
-> 1916         total_inserted = sql_engine.insert_records(
   1917             table=table,
   1918             con=self.con,

~\Anaconda3\lib\site-packages\pandas\io\sql.py in insert_records(self, table, con, frame, name, index, schema, chunksize, method, **engine_kwargs)
   1455 
   1456         try:
-> 1457             return table.insert(chunksize=chunksize, method=method)
   1458         except exc.StatementError as err:
   1459             # GH34431

~\Anaconda3\lib\site-packages\pandas\io\sql.py in insert(self, chunksize, method)
    995             raise ValueError(f"Invalid parameter `method`: {method}")
    996 
--> 997         keys, data_list = self.insert_data()
    998 
    999         nrows = len(self.frame)

~\Anaconda3\lib\site-packages\pandas\io\sql.py in insert_data(self)
    964             vals = ser._values
    965             if vals.dtype.kind == "M":
--> 966                 d = vals.to_pydatetime()
    967             elif vals.dtype.kind == "m":
    968                 # store as integers, see GH#6921, GH#7076

AttributeError: 'ArrowExtensionArray' object has no attribute 'to_pydatetime'
```
</details>

### Expected Behavior

I expect to be able to take my data (with date types) from my first database process it using pandas and then write it in my second database.  

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
python           : 3.9.13.final.0
python-bits      : 64
pandas           : 2.0.0rc1
numpy            : 1.21.5
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 63.4.1
pip              : 22.2.2
Cython           : 0.29.32
pytest           : 7.1.2
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.9.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.31.1
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.5.2
numba            : 0.55.1
numexpr          : 2.8.3
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2023.3.0
scipy            : 1.9.1
snappy           : 
sqlalchemy       : 1.4.39
tables           : 3.6.1
tabulate         : 0.8.10
xarray           : 0.20.1
xlrd             : 2.0.1
zstandard        : None
tzdata           : None
qtpy             : 2.2.0
pyqt5            : None

</details>

**Comment by phofl** [comment] 2023-03-17 13:46
Hi, thanks for your report. Can you please provide a reproducible example? ideally without any dependencies

**Comment by romiof** [comment] 2023-03-17 14:34
Hi @phofl  

I reproduce the bug using a SQLite connection.
If need more infos, please tell me.

<details>

```python
# Create a new Dataframe with NumPy
import pandas as pd
from datetime import datetime

df = pd.DataFrame({"integer": [1, 2, 3], 
                          "date": [
                              (datetime(2022, 1, 1)), 
                              (datetime(2022, 1, 2)), 
                              (datetime(2022, 1, 3))
                          ], 
                          "float":[4.0, 5.0, 6.0],
                          "strings": ["first", "second", "third"]
                        })

df.dtypes

# SQLite for tests... in producion i'm using SQL Server
ENGINE_PATH = "sqlite:///mydb.db"

df.to_sql(name="MyTable_NumPy", con=ENGINE_PATH, if_exists="replace")

#Lets query the new table
import sqlite3
conn = sqlite3.connect("mydb.db")
cur = conn.cursor()
cur.execute("SELECT * FROM MyTable_NumPy")
rows = cur.fetchall()
for row in rows:
    print(row)
```
```
(0, 1, '2022-01-01 00:00:00.000000', 4.0, 'first')
(1, 2, '2022-01-02 00:00:00.000000', 5.0, 'second')
(2, 3, '2022-01-03 00:00:00.000000', 6.0, 'third')
```
#### Now let's convert my DF to PyArrow back-end and try the method "to_sql"

```python
dfarrow = df.convert_dtypes(dtype_backend="pyarrow")

dfarrow.dtypes
#integer            int64[pyarrow]
#date       timestamp[ns][pyarrow]
#float              int64[pyarrow]
#strings           string[pyarrow]
#dtype: object

dfarrow.to_sql(name="MyTable_Arrow", con=ENGINE_PATH, if_exists="replace")
```

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[13], line 1
----> 1 dfarrow.to_sql(name="MyTable_Arrow", con=ENGINE_PATH, if_exists="replace")

File ~/.local/lib/python3.10/site-packages/pandas/core/generic.py:2870, in NDFrame.to_sql(self, name, con, schema, if_exists, index, index_label, chunksize, dtype, method)
   2705 """
   2706 Write records stored in a DataFrame to a SQL database.
   2707 
   (...)
   2866 [(1,), (None,), (2,)]
   2867 """  # noqa:E501
   2868 from pandas.io import sql
-> 2870 return sql.to_sql(
   2871     self,
   2872     name,
   2873     con,
   2874     schema=schema,
   2875     if_exists=if_exists,
   2876     index=index,
   2877     index_label=index_label,
   2878     chunksize=chunksize,
   2879     dtype=dtype,
   2880     method=method,
   2881 )

File ~/.local/lib/python3.10/site-packages/pandas/io/sql.py:767, in to_sql(frame, name, con, schema, if_exists, index, index_label, chunksize, dtype, method, engine, **engine_kwargs)
    762     raise NotImplementedError(
    763         "'frame' argument should be either a Series or a DataFrame"
    764     )
    766 with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
--> 767     return pandas_sql.to_sql(
    768         frame,
    769         name,
    770         if_exists=if_exists,
    771         index=index,
    772         index_label=index_label,
    773         schema=schema,
    774         chunksize=chunksize,
    775         dtype=dtype,
    776         method=method,
    777         engine=engine,
    778         **engine_kwargs,
    779     )

File ~/.local/lib/python3.10/site-packages/pandas/io/sql.py:1916, in SQLDatabase.to_sql(self, frame, name, if_exists, index, index_label, schema, chunksize, dtype, method, engine, **engine_kwargs)
   1904 sql_engine = get_engine(engine)
   1906 table = self.prep_table(
   1907     frame=frame,
   1908     name=name,
   (...)
   1913     dtype=dtype,
   1914 )
-> 1916 total_inserted = sql_engine.insert_records(
   1917     table=table,
   1918     con=self.con,
   1919     frame=frame,
   1920     name=name,
   1921     index=index,
   1922     schema=schema,
   1923     chunksize=chunksize,
   1924     method=method,
   1925     **engine_kwargs,
   1926 )
   1928 self.check_case_sensitive(name=name, schema=schema)
   1929 return total_inserted

File ~/.local/lib/python3.10/site-packages/pandas/io/sql.py:1457, in SQLAlchemyEngine.insert_records(self, table, con, frame, name, index, schema, chunksize, method, **engine_kwargs)
   1454 from sqlalchemy import exc
   1456 try:
-> 1457     return table.insert(chunksize=chunksize, method=method)
   1458 except exc.StatementError as err:
   1459     # GH34431
   1460     # https://stackoverflow.com/a/67358288/6067848
   1461     msg = r"""(\(1054, "Unknown column 'inf(e0)?' in 'field list'"\))(?#
   1462     )|inf can not be used with MySQL"""

File ~/.local/lib/python3.10/site-packages/pandas/io/sql.py:997, in SQLTable.insert(self, chunksize, method)
    994 else:
    995     raise ValueError(f"Invalid parameter `method`: {method}")
--> 997 keys, data_list = self.insert_data()
    999 nrows = len(self.frame)
   1001 if nrows == 0:

File ~/.local/lib/python3.10/site-packages/pandas/io/sql.py:966, in SQLTable.insert_data(self)
    964 vals = ser._values
    965 if vals.dtype.kind == "M":
--> 966     d = vals.to_pydatetime()
    967 elif vals.dtype.kind == "m":
    968     # store as integers, see GH#6921, GH#7076
    969     d = vals.view("i8").astype(object)

AttributeError: 'ArrowExtensionArray' object has no attribute 'to_pydatetime'
```
</details>

**Comment by phofl** [comment] 2023-03-17 14:40
@mroeschke Thoughts here? Should we special-case or add to the interface?

**Comment by mroeschke** [comment] 2023-03-17 17:13
Ah sorry for preemptively closing; I thought from the original issue `.dt.to_pydatetime` was called.

I think we need to special case here. Looks like this method expects numpy arrays.

**Closed** 2023-03-22 20:19 UTC
Labels: Bug, IO SQL, Arrow
