### ISSUE TITLE
Incosistent handling of 'None' when creating dataframe from list

### ISSUE THREAD

**Issue by markste-in** [pandas-dev/pandas#44383] opened 2021-11-10 10:00 UTC
When I create a pandas dataframe from a list 'None' handled differently depending on the size of list

```
test = [(None, None), (1, 2)]
test2 = [(None, None)]
```

`pd.DataFrame(test)`

0 | 1 | 2
-- | -- | --
0 | NaN | NaN
1 | 1.0 | 2.0

`pd.DataFrame(test2)`

0 | 1 | 2
-- | -- | --
0 | None | None

The sudden appearance of different types my break other code (it did so in my case)

I am using pandas version '1.0.5' on Windows Version 10.0.19042
Same on pandas version 1.1.5 on Linux

Here is a runnable colab example
https://github.com/markste-in/colab/blob/master/pandas_bug.ipynb

**Comment by attack68** [comment] 2021-11-10 16:57
Yes but doesn't that construction procedure make sense. Many people wont want a Float NaN where there is no evidence to support that cast, but a Float Nan in a column of containing other numbers.

And to fix it you become encouraged to be explicit with the dtypes of your columns, especially if it causes downstream bug?

**Comment by TheDerivator** [comment] 2021-11-10 20:22
It tries to find a common type per column.
```
import pandas as pd
import numpy as np
pd.Series([None, None])  # object
pd.Series([None, 'abc']) # object
pd.Series([np.nan, None])  # float64
pd.Series([1, 2])  # int64
pd.Series([None, 3])  # float64
```

It would be nicer if nan was always treated as any other float and None as the 'true' missing value imo. For instance:

```
pd.Series([None, None])  # object
pd.Series([None, 'abc'])  # object / nullable str
pd.Series([np.nan, None])  # nullable float64
pd.Series([1, 2])  # int64
pd.Series([None, 3])  # nullable int64
```

It still wouldn't deal with the problem that if you have only None it is impossible to deduce the type though. 

What you should do is probably just specify the dtypes explicitly.

```
pd.DataFrame([(None, None)], dtype=float)
```

**Comment by mroeschke** [comment] 2021-11-14 04:48
Yes this is working as intended due to the data type inference rules for the values composing the columns. Closing as a usage question

**Closed by mroeschke** 2021-11-14 04:48 UTC
