### ISSUE TITLE
Segfault when putting a pendulum datetime into a DataFrame

### ISSUE THREAD

**Issue by DanCardin** [pandas-dev/pandas#16805] opened 2017-06-30 17:44 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pendulum

test = pandas.DataFrame.from_dict([{
    'example': pendulum.Pendulum(2017, 1, 1, 7, tzinfo='America/New_York'),
}])
print(test)
```
#### Problem description

In the above example, specifically the `tzinfo` argument causes the it to segfault. I'm imagining this is because pendulum [subclasses tzinfo](https://github.com/sdispater/pendulum/blob/master/pendulum/tz/timezone.py#L14), but that's somewhat speculation.

#### Expected Output
not segfaulting, and printing the dataframe!

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.0.final.0
python-bits: 64
OS: Linux
OS-release: 4.10.0-24-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.2
pytest: 3.0.6
pip: 9.0.1
setuptools: 28.8.0
Cython: None
numpy: 1.13.0
scipy: None
xarray: None
IPython: 5.2.2
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: 2.4.5
xlrd: 1.0.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.9999999
sqlalchemy: 1.1.5
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.9.5
s3fs: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by jreback** [comment] 2017-06-30 17:54
dupe of #15986

see commentary there
no idea what this library is doing but they aren't using non supported and non standard time zones

**Comment by DanCardin** [comment] 2017-06-30 17:55
cannot believe i didn't see this! sorry!

**Closed by jreback** 2017-06-30 17:54 UTC
Labels: Duplicate, Timezones
