### ISSUE TITLE
BUG: Error while debugging

### ISSUE THREAD

**Issue by eddaz7** [pandas-dev/pandas#46890] opened 2022-04-28 12:29 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame()
df['col1'] = np.random.rand(100)
df['col2'] = np.random.rand(100)

df.to_parquet('test.parquet')

df = pd.read_parquet('test.parquet')

print(df)
```

### Issue Description

IMPORTANT: This only happens when debugging on line: pd.read_parquet('test.parquet')
I am using spyder on anaconda.
I can provide dependencies if necessary.

<details>
Traceback (most recent call last):

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\spyder_kernels\customize\spyderpdb.py", line 776, in run
    super(SpyderPdb, self).run(cmd, globals, locals)

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\bdb.py", line 597, in run
    exec(cmd, globals, locals)

  File "c:\users\edudv\downloads\test.py", line 16, in <module>
    df = pd.read_parquet('test.parquet')

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pandas\io\parquet.py", line 493, in read_parquet
    return impl.read(

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pandas\io\parquet.py", line 240, in read
    result = self.api.parquet.read_table(

  File "pyarrow\array.pxi", line 767, in pyarrow.lib._PandasConvertible.to_pandas

  File "pyarrow\table.pxi", line 1996, in pyarrow.lib.Table._to_pandas

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pyarrow\pandas_compat.py", line 788, in table_to_blockmanager
    columns = _deserialize_column_index(table, all_columns, column_indexes)

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pyarrow\pandas_compat.py", line 903, in _deserialize_column_index
    columns = _flatten_single_level_multiindex(columns)

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pyarrow\pandas_compat.py", line 1150, in _flatten_single_level_multiindex
    if not index.is_unique:

  File "pandas\_libs\properties.pyx", line 37, in pandas._libs.properties.CachedProperty.__get__

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pandas\core\indexes\base.py", line 2237, in is_unique
    return self._engine.is_unique

  File "pandas\_libs\properties.pyx", line 37, in pandas._libs.properties.CachedProperty.__get__

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pandas\core\indexes\multi.py", line 1097, in _engine
    return MultiIndexUIntEngine(self.levels, self.codes, offsets)

  File "pandas\_libs\index.pyx", line 635, in pandas._libs.index.BaseMultiIndexCodesEngine.__init__

  File "C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\pandas\core\indexes\multi.py", line 136, in _codes_to_ints
    codes <<= self.offsets

AttributeError: 'MultiIndex' object has no attribute 'offsets'

</details>

### Expected Behavior

Read parquet file

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : es_ES.cp1252

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 4.5.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.1
IPython          : 7.32.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
C:\Users\edudv\miniconda3\envs\test_pd\lib\site-packages\_distutils_hack\__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

</details>

**Comment by RyuuOujiXS** [comment] 2022-05-02 21:43
Is there a reason you need to read from a file you just overwrote? Why not just use the df that's already in memory since it should be identical? Asking because code is built around real-use cases.

**Comment by eddaz7** [comment] 2022-05-02 21:52
The code was just for recreation purpose.
It happens when I read any parquet file

**Comment by ba-tno** [comment] 2022-05-03 21:03
I have the same issue: appending a column to the index works fine while running, but fails when in debug mode. I'm using Spyder `5.3.0` on Windows with pandas `1.4.2`.

I've created some dummy code that shows the problem:
```py
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 3], "b": [100, 200, 300], "c": ["a", "b", "c"]})

df.set_index("a", inplace=True)
df.set_index("b", append=True, inplace=True)

print(df)
print(df.index)
```

Running this without debugging returns:
```txt
       c
a b     
1 100  a
2 200  b
3 300  c
MultiIndex([(1, 100),
            (2, 200),
            (3, 300)],
           names=['a', 'b'])
```

Running this with debugging in Spyder returns:
```txt
Traceback (most recent call last):

  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\spyder_kernels\customize\spyderpdb.py", line 776, in run
    super(SpyderPdb, self).run(cmd, globals, locals)

  File "C:\Users\username\Miniconda3\envs\some-env\lib\bdb.py", line 597, in run
    exec(cmd, globals, locals)

  File "c:\users\username\path\temp.py", line 6, in <module>
    df.set_index("b", append=True, inplace=True)

  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\frame.py", line 5560, in set_index
    index._cleanup()

  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\indexes\base.py", line 843, in _cleanup
    self._engine.clear_mapping()

  File "pandas\_libs\properties.pyx", line 37, in pandas._libs.properties.CachedProperty.__get__

  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\indexes\multi.py", line 1097, in _engine
    return MultiIndexUIntEngine(self.levels, self.codes, offsets)

  File "pandas\_libs\index.pyx", line 635, in pandas._libs.index.BaseMultiIndexCodesEngine.__init__

  File "C:\Users\username\Miniconda3\envs\some-env\lib\site-packages\pandas\core\indexes\multi.py", line 136, in _codes_to_ints
    codes <<= self.offsets

AttributeError: 'MultiIndex' object has no attribute 'offsets'
```

**Comment by eddaz7** [comment] 2022-05-04 07:36
yeah, it seems to be some issue with debugging in spyder last version.
Maybe it is spyder and not pandas

**Comment by MarcoGorelli** [comment] 2022-05-04 10:09
have you reported to `spyder`? debugging that code with `pdb` works fine for me

**Comment by ba-tno** [comment] 2022-05-04 11:54
As it only appears to happen with `spyder` I agree it's probably their issue. However, the error does appear to come from the `pandas` codebase, so perhaps it's good to have it here as well?

**Comment by eddaz7** [comment] 2022-05-04 18:35
yep, seems like a problem with pandas, spyder and python 3.10
@MarcoGorelli what version of python did you use?

**Comment by MarcoGorelli** [comment] 2022-05-04 18:36
3.8

**Comment by eddaz7** [comment] 2022-05-04 18:42
can you try with python 3.10?

**Comment by ba-tno** [comment] 2022-05-07 18:48
The Spyder issue was closed as:

> ... was able to reproduce it in terminal IPython, I think this is not a Spyder problem but a Pandas one. 

The Spyder issue has an [environment specification](https://github.com/spyder-ide/spyder/issues/17821#issuecomment-1117622458) that reproduces this issue. Is there anything else I can provide to help resolve this issue?

**Comment by FTL-Citepa** [comment] 2022-05-12 09:27
Same problem here with read_feather from pandas

**Comment by MarcoGorelli** [comment] 2022-05-12 09:36
> can you try with python 3.10?

Thanks - yup, can reproduce with Python3.10!

```

**Comment by FTL-Citepa** [comment] 2022-05-12 13:29
So I cannot debug no spyder if working with pandas on an environment ? this is a major problem considering I'm working on a big project and I have to control some functions independently

**Comment by ba-tno** [comment] 2022-05-12 14:43
> So I cannot debug on spyder if working with pandas on an environment ? 

Well, that's a bit of a broad statement... As stated in [this comment](https://github.com/spyder-ide/spyder/issues/17821#issuecomment-1117655087):

> As a workaround please use Python <=3.9

So, if you simply specify `python=3.9` in your conda environment then this issue should not occur.

**Comment by mzeitlin11** [comment] 2022-08-04 00:24
This looks related to #41935. Is this still an issue in 1.4.3?

**Comment by ba-tno** [comment] 2022-08-08 18:19
I have recreated the [environment linked to earlier](https://github.com/spyder-ide/spyder/issues/17821#issuecomment-1117622458), updated `pandas` to 1.4.3 and updated `spyder-kernels` to 2.3.2. 

Then I tested [the code snippet](https://github.com/pandas-dev/pandas/issues/46890#issuecomment-1116654680) I posted earlier. This works now as expected.

I also installed `ipdb` and tested [MarcoGorelli's example](https://github.com/pandas-dev/pandas/issues/46890#issuecomment-1124758743). This now also works as expected.

So it seems this issue is resolved.

**Comment by mzeitlin11** [comment] 2022-08-08 18:46
Thanks for checking @ba-tno, closing then!

**Closed by mzeitlin11** 2022-08-08 18:46 UTC
Labels: Bug, Needs Info, Python 3.10
