### ISSUE TITLE
BUG: read_parquet(list_of_files, engine='fastparquet') raises KeyError on windows

### ISSUE THREAD

**Issue by mvashishtha** [pandas-dev/pandas#51720] opened 2023-03-01 17:23 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df1 = pd.DataFrame([1], columns=['a'])
df2 = pd.DataFrame([2], columns=['a'])
df1.to_parquet('/tmp/a1.parquet')
df2.to_parquet('/tmp/a2.parquet')
print(pd.read_parquet(['/tmp/a1.parquet', '/tmp/a1.parquet'], engine='fastparquet'))
```

### Issue Description

works on mac and with pyarrow engine, but not on fastparquet. I'm sorry I can't give a reproducer as I don't have a windows machine, but this bug came up in a windows CI job: https://github.com/modin-project/modin/actions/runs/4305361672/jobs/7507797209

the test passed on linux and the bug doesn't apply on my macbook:

- python 3.10
- macOS Monterey 12.4 on MacBook Pro (16-inch, 2019)

### Expected Behavior

should read the files as with pyarrow

### Installed Versions

<details>
<summary>versions</summary>

```
/Users/maheshvashishtha/opt/anaconda3/envs/pandas-latest-version/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 6bb8f73e75bb5d25ca752f34f54705cdc533da54
python           : 3.10.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.1.0.dev0+93.g6bb8f73e75
numpy            : 1.25.0.dev0+831.g3b5eff00e
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.11.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : 2023.2.0
fsspec           : 2023.1.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : None
qtpy             : None
pyqt5            : None
```

</details>

**Comment by phofl** [comment] 2023-03-01 22:47
Hi, thanks for your report. This looks a lot like it's in fast parquet. Could you elaborate why you think this is a pandas problem?

**Comment by mvashishtha** [comment] 2023-03-01 23:35
@phofl `read_parquet` is a pandas method, so this is a pandas bug. It could have a dependency on a fastparquet bug.

**Comment by phofl** [comment] 2023-03-01 23:37
If the original bug is inside of fastparquet then we can't do anything about it and you should it report to the upstream project.

**Comment by phofl** [comment] 2023-03-16 19:32
Closing for now since this seems to be in fast parquet, please ping to reopen if this is in pandas.

**Closed by phofl** 2023-03-16 19:32 UTC
Labels: Bug, Needs Info, IO Parquet

**Comment by mvashishtha** [comment] 2023-03-17 13:59
@phofl it doesn't seem appropriate to me to resolve this issue. As I said earlier, this bug may have a dependency on fastparquet, but it's still a pandas bug.

**Comment by phofl** [comment] 2023-03-17 14:05
We are simply calling fastparquet with a valid input according to their docs. If this does not work the appropriate place to open the issue is in the fast parquet issue tracker, not the pandas issue tracker.

**Comment by mvashishtha** [comment] 2023-03-17 14:09
> We are simply calling fastparquet with a valid input according to their docs. If this does not work the appropriate place to open the issue is in the fast parquet issue tracker, not the pandas issue tracker.

I disagree again. Whatever the pandas implementation, `pandas.read_parquet(list_of_files, engine='fastparquet')` is a pandas feature that pandas should test for. It is broken. Fixing the bug may require fixing a fastparquet bug, but even if it does, pandas should have a unit test to check whether this behavior works in pandas.

I don't have the ability to reopen this issue, but you do, so the choice is yours. I have nothing else to say.

**Comment by anmyachev** [comment] 2023-08-05 14:14
@phofl It turns out that some users may accidentally rely on this implicit behavior. Do you think it makes sense to add a check for the allowed types of `path` parameter so that pandas behavior is consistent across different platforms?
