### ISSUE TITLE
BUG: MultiIndex converts `"\x00"` to `""`

### ISSUE THREAD

**Issue by andreareina** [pandas-dev/pandas#46764] opened 2022-04-13 10:18 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

l1 = ["", "\x00"]
i1 = pd.Index(l1)
print(i1.tolist()) # ['', '\x00']
print(i1.tolist() == l1) # True

l2 = [("",), ("\x00",)]
i2 = pd.Index(l2)
print(i2.tolist()) # [('',), ('',)]
print(i2.tolist() == l2) # False
```

### Issue Description

Null-character strings in tuples are converted to the empty string when used as an index.

### Expected Behavior

The null-character string should be preserved.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.11.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-104-generic
Version          : #118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_SG.UTF-8
LOCALE           : en_SG.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.3
setuptools       : 57.4.0
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment] 2022-04-13 12:52
Thanks @andreareina for the report. Can you give the issue an informative title.

> Null-character strings in tuples are converted to the empty string when used as an index.

Tuples used in the Index constructor create a single level MultiIndex. Under the hood the MultiIndex values are stored as factorized codes so this could be where the discrepancy occurs. Further investigation and PRs welcome.

**Comment by andreareina** [comment] 2022-04-14 05:36
Seems to be happening in `_libs.hashtable.StringHashTable` but I'm unable to follow the cython. Probably the underlying C(++?) expecting null-terminated strings.

```python
import numpy as np
import pandas as pd

values = np.array(["", "\x00"], dtype=object)
size_hint = None
na_sentinel = -1
na_value = None
mask = None

# Excerpted from https://github.com/pandas-dev/pandas/blob/4bfe3d07b4858144c219b9346329027024102ab6/pandas/core/algorithms.py#L524-L565 (factorize_array)

# hash_klass, values = _get_data_algo(values)
hash_klass = pd._libs.hashtable.StringHashTable

table = hash_klass(size_hint or len(values))
uniques, codes = table.factorize(
    values, na_sentinel=na_sentinel, na_value=na_value, mask=mask
)
print(repr(uniques)) #=> array([''], dtype=object)

# codes = ensure_platform_int(codes)
```

**Comment by mzeitlin11** [comment] 2022-04-15 00:49
Probably related to #34551?

**Comment by simonjayhawkins** [comment] 2022-05-12 16:07
> Probably related to #34551?

appears so. there is also a comment on that issue, https://github.com/pandas-dev/pandas/issues/34551#issuecomment-1013782984 regarding MultiIndex and comments regarding other methods that use the factorize algo for Null-character strings.

can probably close this as duplicate.

**Comment by mroeschke** [comment] 2022-07-05 23:00
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/34551

**Closed by mroeschke** 2022-07-05 23:00 UTC
Labels: Bug, Duplicate Report, Strings, MultiIndex, hashing, Closing Candidate
