### ISSUE TITLE
BUG: cannot safely cast non-equivalent float64 to Int64

### ISSUE THREAD

**Issue by aeslava97** [pandas-dev/pandas#37429] opened 2020-10-26 21:21 UTC
```python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(3,4), columns= list('ABCD'))
df_int = pd.to_numeric(df['A'], errors='coerce').astype('Int64')

```

#### Problem description
cannot safely cast non-equivalent float64 to Int64, it should happen like when you convert from float64 to int64, which is rounding down the number

#### Expected Output
0    0
1    0
2    0
Name: A, dtype: Int64

#### Output of ``pd.show_versions()``
pandas           : 1.0.1

You can pass to Int64 safely by doing:

```python
df_int = np.floor(pd.to_numeric(df['A'], errors='coerce')).astype('Int64')
```

<details>

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandas\core\arrays\integer.py in safe_cast(values, dtype, copy)
    143     try:
--> 144         return values.astype(dtype, casting="safe", copy=copy)
    145     except TypeError:

TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-14-8151dc1b5846> in <module>
----> 1 df_int = pd.to_numeric(df['A'], errors='coerce').astype('Int64')
      2 df_int

~\anaconda3\lib\site-packages\pandas\core\generic.py in astype(self, dtype, copy, errors)
   5696         else:
   5697             # else, only a single dtype is given
-> 5698             new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
   5699             return self._constructor(new_data).__finalize__(self)
   5700 

~\anaconda3\lib\site-packages\pandas\core\internals\managers.py in astype(self, dtype, copy, errors)
    580 
    581     def astype(self, dtype, copy: bool = False, errors: str = "raise"):
--> 582         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    583 
    584     def convert(self, **kwargs):

~\anaconda3\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, filter, **kwargs)
    440                 applied = b.apply(f, **kwargs)
    441             else:
--> 442                 applied = getattr(b, f)(**kwargs)
    443             result_blocks = _extend_blocks(applied, result_blocks)
    444 

~\anaconda3\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors)
    623             vals1d = values.ravel()
    624             try:
--> 625                 values = astype_nansafe(vals1d, dtype, copy=True)
    626             except (ValueError, TypeError):
    627                 # e.g. astype_nansafe can fail on object-dtype of strings

~\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy, skipna)
    819     # dispatch on extension dtype if needed
    820     if is_extension_array_dtype(dtype):
--> 821         return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)
    822 
    823     if not isinstance(dtype, np.dtype):

~\anaconda3\lib\site-packages\pandas\core\arrays\integer.py in _from_sequence(cls, scalars, dtype, copy)
    348     @classmethod
    349     def _from_sequence(cls, scalars, dtype=None, copy=False):
--> 350         return integer_array(scalars, dtype=dtype, copy=copy)
    351 
    352     @classmethod

~\anaconda3\lib\site-packages\pandas\core\arrays\integer.py in integer_array(values, dtype, copy)
    129     TypeError if incompatible types
    130     """
--> 131     values, mask = coerce_to_array(values, dtype=dtype, copy=copy)
    132     return IntegerArray(values, mask)
    133 

~\anaconda3\lib\site-packages\pandas\core\arrays\integer.py in coerce_to_array(values, dtype, mask, copy)
    245         values = safe_cast(values, dtype, copy=False)
    246     else:
--> 247         values = safe_cast(values, dtype, copy=False)
    248 
    249     return values, mask

~\anaconda3\lib\site-packages\pandas\core\arrays\integer.py in safe_cast(values, dtype, copy)
    150 
    151         raise TypeError(
--> 152             f"cannot safely cast non-equivalent {values.dtype} to {np.dtype(dtype)}"
    153         )
    154 

TypeError: cannot safely cast non-equivalent float64 to int64

</details>

**Comment by arw2019** [comment] 2020-10-28 05:37
Not sure this is a bug. The method does what it says on the tin - it will only cast float values that are equivalent to an int dtype

**Comment by efagerberg** [comment] 2020-10-28 19:56
I have hit a similar error when trying to coerce a series that includes whole numbers as strings with commas, and null values.

```python
x = pd.DataFrame(data={"dollars": ["1,234", None]})
x.to_csv("example.csv", index=False)
y = pd.read_csv("example.csv", thousands=',')
y['dollars']
0    1234.0
1       NaN
Name: dollars, dtype: float64
```

In this case it is a pretty reasonable expectation that if all the columns are whole numbers or nulls that the column is an Int64. But currently it defaults to float64, and you cannot use dtype to set it right.

This is in python 3.8 with pandas 1.0.5

```python
, dtype={'dollars': 'Int64'}
x = pd.DataFrame(data={"dollars": ["1,234", None]})
x.to_csv("example.csv", index=False)
y = pd.read_csv("example.csv", thousands=',', dtype={'dollars': 'Int64'})
y['dollars']
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
pandas/_libs/lib.pyx in pandas._libs.lib.maybe_convert_numeric()

ValueError: Unable to parse string "1,234"

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-116-91cf810cae8f> in <module>
      1 x = pd.DataFrame(data={"dollars": ["1,234", None]})
      2 x.to_csv("example.csv", index=False)
----> 3 y = pd.read_csv("example.csv", thousands=',', dtype={'dollars': 'Int64'})
      4 y['dollars']

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    452 
    453     try:
--> 454         data = parser.read(nrows)
    455     finally:
    456         parser.close()

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in read(self, nrows)
   1131     def read(self, nrows=None):
   1132         nrows = _validate_integer("nrows", nrows)
-> 1133         ret = self._engine.read(nrows)
   1134 
   1135         # May alter columns / col_dict

/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py in read(self, nrows)
   2035     def read(self, nrows=None):
   2036         try:
-> 2037             data = self._reader.read(nrows)
   2038         except StopIteration:
   2039             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_column_data()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_tokens()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._convert_with_dtype()

/opt/conda/lib/python3.8/site-packages/pandas/core/arrays/integer.py in _from_sequence_of_strings(cls, strings, dtype, copy)
    356     @classmethod
    357     def _from_sequence_of_strings(cls, strings, dtype=None, copy=False):
--> 358         scalars = to_numeric(strings, errors="raise")
    359         return cls._from_sequence(scalars, dtype, copy)
    360 

/opt/conda/lib/python3.8/site-packages/pandas/core/tools/numeric.py in to_numeric(arg, errors, downcast)
    147         coerce_numeric = errors not in ("ignore", "raise")
    148         try:
--> 149             values = lib.maybe_convert_numeric(
    150                 values, set(), coerce_numeric=coerce_numeric
    151             )

pandas/_libs/lib.pyx in pandas._libs.lib.maybe_convert_numeric()

ValueError: Unable to parse string "1,234" at position 0
```

I think the error message here is actually similar to the one discussed in this issue, read_csv is just bubbling up with a different error.

**Comment by aeslava97** [comment] 2020-10-29 01:05
@efagerberg NaN is a float value, so the column gets casted to float64

**Comment by efagerberg** [comment] 2020-10-29 13:30
Sure perhaps that is the issue though, I have indicated to the library I expect the Int64 version of a null value (I believe pd.na), and I think that is a reasonable expectation for this situation.

**Comment by adonig** [comment] 2021-04-15 13:47
It looks like I might be running into the same problem. I try to convert the results of an operation to UInt64 and write them out to a parquet file later. The astype call causes the program to crash. When I leave off the astype call, it'll write the data to the parquet file as floating point numbers with one decimal which is always zero.

```
            res = res.astype("float64")
            res = res.round(decimals=0)
            res = res.replace([np.inf, -np.inf], pd.NA)
            res = res.fillna(pd.NA)
            print("DEBUG", type(res), res.unique())
            res = res.astype("UInt64")
```

What I get including the DEBUG print statement is the following:

```
DEBUG <class 'pandas.core.series.Series'> [<NA>]
Traceback (most recent call last):
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/arrays/integer.py", line 155, in safe_cast
    return values.astype(dtype, casting="safe", copy=copy)
TypeError: Cannot cast array data from dtype('O') to dtype('uint64') according to the rule 'safe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/asd/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/asd/.pyenv/versions/3.9.4/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/asd/Projects/myproject/myproject/fetcher/xyz/__main__.py", line 3, in <module>
    main()
  File "/Users/asd/Projects/myproject/myproject/dask.py", line 51, in wrapper
    return f(*args, **kwds)
  File "/Users/asd/Projects/myproject/myproject/fetcher/xyz/__init__.py", line 9, in main
    data_source.execute()
  File "/Users/asd/Projects/myproject/myproject/fetcher/__init__.py", line 335, in execute
    logging.info(f"cleaning {source_name} data {df.index.size.compute()}")
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/dask/base.py", line 284, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/dask/base.py", line 566, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/distributed/client.py", line 2666, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/distributed/client.py", line 1975, in gather
    return self.sync(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/distributed/client.py", line 843, in sync
    return sync(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/distributed/client.py", line 1840, in _gather
    raise exception.with_traceback(traceback)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/dask/utils.py", line 34, in apply
    return func(*args, **kwargs)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/dask/dataframe/core.py", line 5665, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/Users/asd/Projects/myproject/myproject/fetcher/__init__.py", line 235, in transform
    df = df.assign(**mapping_dict)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/frame.py", line 3830, in assign
    data[k] = com.apply_if_callable(v, data)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/common.py", line 329, in apply_if_callable
    return maybe_callable(obj, **kwargs)
  File "/Users/asd/Projects/myproject/myproject/fetcher/__init__.py", line 47, in wrapper
    res = func(self, *args, **kwargs)
  File "/Users/asd/Projects/myproject/myproject/fetcher/__init__.py", line 145, in get_discount_percentage
    discount_percentage = price_original.mask(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/generic.py", line 9317, in mask
    return self.where(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/generic.py", line 9286, in where
    return self._where(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/generic.py", line 9136, in _where
    new_data = self._mgr.where(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 557, in where
    return self.apply(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 2018, in where
    result = self._holder._from_sequence(
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/arrays/integer.py", line 363, in _from_sequence
    return integer_array(scalars, dtype=dtype, copy=copy)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/arrays/integer.py", line 143, in integer_array
    values, mask = coerce_to_array(values, dtype=dtype, copy=copy)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/arrays/integer.py", line 258, in coerce_to_array
    values = safe_cast(values, dtype, copy=False)
  File "/Users/asd/Projects/myproject/.venv/lib/python3.9/site-packages/pandas/core/arrays/integer.py", line 162, in safe_cast
    raise TypeError(
TypeError: cannot safely cast non-equivalent object to uint64
```

From my understanding I should be able to cast a series of pd.NA values to UInt64 or is that assumption incorrect?

**Comment by mroeschke** [comment] 2021-08-13 05:27
Agreed, that the current error `TypeError: cannot safely cast non-equivalent float64 to int64` is the expected behavior. The workaround you have is the suitable "workaround" for what you exactly want. Closing

**Closed by mroeschke** 2021-08-13 05:27 UTC
Labels: Bug, Needs Triage

**Comment by efagerberg** [comment] 2021-08-13 14:41
> @efagerberg NaN is a float value, so the column gets casted to float64

The problem is there is a NaN equivalent for Int64 as well and in some cases like when no other data has a decimal place in the data, it is inappropriate to assume float.

**Comment by Nesuniken** [comment] 2022-05-24 03:47
> The workaround you have is the suitable "workaround" for what you exactly want. 
The workaround does work for this specific situation, but is the expectation really for someone to come up with a new workaround anytime a Float64 NaN needs to be converted into an Int64 one? I don't understand why astype() on its own isn't already explicit enough to force the conversion.

**Comment by efagerberg** [comment] 2022-05-24 14:45
> Agreed, that the current error `TypeError: cannot safely cast non-equivalent float64 to int64` is the expected behavior. The workaround you have is the suitable "workaround" for what you exactly want. Closing

I think a more honest answer from the maintainers is to accept this as an unexpected result that makes working with pandas harder.

There can be legitimate rational for not working on it for the past 2 years. The way this issue was closed feels more like the maintainers would rather sweep it under the rug, since the comment preceding the closing of this issue did not really address any of the criticism of earlier comment.

Those critiques being:
1. It is odd for a user who has a column of mostly whole numbers and one empty cell to get back a column of type float. There can be legitimate reasons why (NA is a float), but it is odd regardless.
2. Existing utilities that are supposed to facilitate the conversion from `float` to `Int64` when you know about it raise errors instead. For example `read_csv` `dtype` keyword arguments. `Int54` is a nullable integer type and thus should be convertable from float if the floats have no decimal values. This to me is the clearest point that this is in fact a bug not something more suitable for a feature request.

**Comment by Ark-kun** [comment] 2022-08-20 00:14
I've just realized that Pandas has been corrupting my data for a while.

Pandas reads integer column values as float and sometimes auto-corrupts them.

**Comment by silverops** [comment] 2022-09-13 13:37
Apparently the error still persists, I'm running OverSampling and Smote, when running OverSampling no error occurs but when running Smote this problem happens.
![image](https://user-images.githubusercontent.com/75681984/189915786-54360850-1988-4bc9-a411-0e6f1a1d2788.png)
![image](https://user-images.githubusercontent.com/75681984/189915885-4a497af1-03e4-4320-bb5c-1d623d8fa64e.png)

**Comment by ppt000** [comment] 2023-06-29 15:26
It seems to me as well that this problem still persists:

    import numpy as np
    import pandas as pd
    dfr = pd.DataFrame({'col1': np.random.randint(0,100, size=100)})
    dfr.dtypes
    > col1    int32
    > dtype: object
    (dfr / 10).dtypes
    > col1    float64
    > dtype: object
    (dfr / 10).astype(np.uint32).dtypes
    > col1    uint32
    > dtype: object
    (dfr / 10).astype('UInt32').dtypes
    > ... trace ...
    > TypeError: cannot safely cast non-equivalent float64 to uint32

**Comment by tr1ppyb0y** [comment] 2024-09-12 09:10
Problem still persists, I am trying to convert `age` column of `titanic` dataset,

```py
import pandas as pd
df = pd.read_excel("titanic3.xls")
df['age'] = df['age'].astype('Int64')
```

This is the error I get.
```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\arrays\integer.py:53, in IntegerDtype._safe_cast(cls, values, dtype, copy)
     52 try:
---> 53     return values.astype(dtype, casting="safe", copy=copy)
     54 except TypeError as err:

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[43], line 1
----> 1 df['age'] = df['age'].astype('Int64')

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\generic.py:6643, in NDFrame.astype(self, dtype, copy, errors)
   6637     results = [
   6638         ser.astype(dtype, copy=copy, errors=errors) for _, ser in self.items()
   6639     ]
   6641 else:
   6642     # else, only a single dtype is given
-> 6643     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
   6644     res = self._constructor_from_mgr(new_data, axes=new_data.axes)
   6645     return res.__finalize__(self, method="astype")

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\internals\managers.py:430, in BaseBlockManager.astype(self, dtype, copy, errors)
    427 elif using_copy_on_write():
    428     copy = False
--> 430 return self.apply(
    431     "astype",
    432     dtype=dtype,
    433     copy=copy,
    434     errors=errors,
    435     using_cow=using_copy_on_write(),
    436 )

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\internals\managers.py:363, in BaseBlockManager.apply(self, f, align_keys, **kwargs)
    361         applied = b.apply(f, **kwargs)
    362     else:
--> 363         applied = getattr(b, f)(**kwargs)
    364     result_blocks = extend_blocks(applied, result_blocks)
    366 out = type(self).from_blocks(result_blocks, self.axes)

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\internals\blocks.py:758, in Block.astype(self, dtype, copy, errors, using_cow, squeeze)
    755         raise ValueError("Can not squeeze with more than one column.")
    756     values = values[0, :]  # type: ignore[call-overload]
--> 758 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
    760 new_values = maybe_coerce_values(new_values)
    762 refs = None

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\dtypes\astype.py:237, in astype_array_safe(values, dtype, copy, errors)
    234     dtype = dtype.numpy_dtype
    236 try:
--> 237     new_values = astype_array(values, dtype, copy=copy)
    238 except (ValueError, TypeError):
    239     # e.g. _astype_nansafe can fail on object-dtype of strings
    240     #  trying to convert to float
    241     if errors == "ignore":

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\dtypes\astype.py:182, in astype_array(values, dtype, copy)
    179     values = values.astype(dtype, copy=copy)
    181 else:
--> 182     values = _astype_nansafe(values, dtype, copy=copy)
    184 # in pandas we don't store numpy str dtypes, so convert to object
    185 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\dtypes\astype.py:80, in _astype_nansafe(arr, dtype, copy, skipna)
     78 # dispatch on extension dtype if needed
     79 if isinstance(dtype, ExtensionDtype):
---> 80     return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)
     82 elif not isinstance(dtype, np.dtype):  # pragma: no cover
     83     raise ValueError("dtype must be np.dtype or ExtensionDtype")

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\arrays\masked.py:152, in BaseMaskedArray._from_sequence(cls, scalars, dtype, copy)
    150 @classmethod
    151 def _from_sequence(cls, scalars, *, dtype=None, copy: bool = False) -> Self:
--> 152     values, mask = cls._coerce_to_array(scalars, dtype=dtype, copy=copy)
    153     return cls(values, mask)

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\arrays\numeric.py:272, in NumericArray._coerce_to_array(cls, value, dtype, copy)
    270 dtype_cls = cls._dtype_cls
    271 default_dtype = dtype_cls._default_np_dtype
--> 272 values, mask, _, _ = _coerce_to_data_and_mask(
    273     value, dtype, copy, dtype_cls, default_dtype
    274 )
    275 return values, mask

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\arrays\numeric.py:229, in _coerce_to_data_and_mask(values, dtype, copy, dtype_cls, default_dtype)
    227     values = values.astype(dtype, copy=copy)
    228 else:
--> 229     values = dtype_cls._safe_cast(values, dtype, copy=False)
    231 return values, mask, dtype, inferred_type

File I:\PycharmProjects\chess\.venv\Lib\site-packages\pandas\core\arrays\integer.py:59, in IntegerDtype._safe_cast(cls, values, dtype, copy)
     56 if (casted == values).all():
     57     return casted
---> 59 raise TypeError(
     60     f"cannot safely cast non-equivalent {values.dtype} to {np.dtype(dtype)}"
     61 ) from err

TypeError: cannot safely cast non-equivalent float64 to int64
```
