### ISSUE TITLE
DataFrame.from_csv loses precision

### ISSUE THREAD

**Issue by brendam** [pandas-dev/pandas#2697] opened 2013-01-15 02:34 UTC
I've found a problem in importing a csv file with numbers that loses the precision of all the numbers in a column.

If any of the entries in a column are in scientific format, all of the entries are converted to that and loose precision. Only happens if a number in the column is 12 digits or more (either representation - so either 1E+11 or 123456789012). Much larger numbers in a column with no  scientific representation entries don't trigger the problem.

The mixed type is an error in my data, but thought I'd report the problem in pandas in case it effects legitimate data.
Happens in both 10.0 and 0.10.1.dev-6e2b6ea on OSX with numpy 1.6.2.

csv file:

``` csv
id, text
135217135789158401, 'testing lost precision from csv'
1352171357E+5, 'any item scientific format loses the precision on all other entries'
```

``` python
test = pandas.DataFrame.from_csv('test.csv')
print test.index[0] == 135217135789158401
print test.index[1] == 1352171357E+5
```

Example of large number - column A is effected, column C isn't.

``` csv
id, A, B, C
1, 99999999999, 'a', 99999999999
2, 123456789012345, 'b', 123456789012345
3, 1234E+0, 'c', 1234
```

This may be related to Issue #2069

**Comment by kokes** [comment] 2016-03-09 00:43
Testing these it seems the first two problems have been resolved, see [an example](https://gist.github.com/kokes/51a164426137f6fc387b).

The last one, as pointed out, may be impossible to solve given homogeneity of columns and float64/int64 max value discrepancies.

**Comment by gfyoung** [comment] 2016-08-22 05:57
Not quite.  The reason for the loss of precision in the first case is because `from_csv` defaults `parse_dates=True`, which causes those floats to be butchered by attempts to convert these values to dates during index creation.  You can see for yourself by passing in `parse_dates=True` to `read_csv`.
~~~python
>>> from pandas import read_csv, DataFrame
>>> from pandas.compat import StringIO
>>> data = 'a\n135217135789158401\n1352171357E+5'
>>> df = read_csv(StringIO(data), index_col=0, parse_dates=True)
>>> print(df.index[0] == 135217135789158401)
False
>>> print(df.index[0] == 1352171357E+5)
False
~~~
You can see here that specifying `parse_dates=False` does the trick:
~~~python
>>> df = DataFrame.from_csv(StringIO(data), parse_dates=False)
>>> print(df.index[0] == 135217135789158401)
True
>>> print(df.index[0] == 1352171357E+5)
True
~~~
As for the second example, I can't reproduce that anymore:
~~~python
>>> data = 'a\n99999999999\n123456789012345\n1234E+0'
>>> df = DataFrame.from_csv(StringIO(data), parse_dates=False)
>>> print(df.index[0] == 99999999999)
True
>>> print(df.index[1] == 123456789012345)
True
>>> print(df.index[2] == 1234)
True
~~~
The `parse_dates` behaviour is not bugged but intended behaviour, as it is stated clearly in documentation <a href="https://github.com/pydata/pandas/blob/df2d9ab917a1ef4732cfb6c3317432f60c071074/pandas/io/parsers.py#L150">here</a>.  While I do find it unusual that `parse_dates=False` by default, that too is laid out clearly in documentation <a href="https://github.com/pydata/pandas/blob/df2d9ab917a1ef4732cfb6c3317432f60c071074/pandas/core/frame.py#L1191">here</a>.

I think the "enhancement" here would be to just clarify documentation in `from_csv` to match that of `to_csv` so that no confusion is to be had.  @jreback what do you think?

**Comment by jreback** [comment] 2016-08-22 13:22
I think the issue is this:

parse_dates=True tries to convert to dates - if it fails it *might* be doing something that changes the data that is then passed thru (IOW it has a side effect)

**Comment by gfyoung** [comment] 2016-08-22 14:55
Right, it is doing some conversion as expected, but I think clearer documentation there might help just to avoid this confusion again.

**Comment by jreback** [comment] 2016-08-22 14:57
maybe I am not clear

it is doing a conversion, which fails (I think) and propagates it rather than using the original data (this is a guess FYI)

so if u can detect a failure then I think ok if it's unambiguous (that it failed)

**Comment by gfyoung** [comment] 2016-08-23 01:10
@jreback : I still don't understand what you said.  All I'm saying is that we should just update documentation and close this issue.

**Closed** 2017-11-06 18:18 UTC
Labels: IO CSV, Testing
