### ISSUE TITLE
BLD: 32-bit / 2.7 tests broken

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#17121] opened 2017-07-30 13:21 UTC
https://travis-ci.org/MacPython/pandas-wheels/jobs/258984636

not sure what exactly broke this

**Comment by gfyoung** [comment] 2017-07-30 19:23
@jreback : The failure started occurring about four days ago.  My guess is that #17062 is the culprit given that it was merged around the same time, and the location of the failure is near the location of the files that were modified.

cc @toobaz

**Comment by toobaz** [comment] 2017-07-30 22:49
Being unable to reproduce, I made the following simple experiment: I added error-triggering lines to each function I had modified in #17062 . The test still works fine. So the bug doesn't seem to be related to my patch.

**Comment by gfyoung** [comment] 2017-07-30 22:52
@toobaz : You can try reproducing via VM, but given your comment, that *might* be indicative of a flakey test, though not entirely sure.

**Comment by gfyoung** [comment] 2017-07-31 05:52
Tests seem to be passing again: https://travis-ci.org/MacPython/pandas-wheels/builds/259204266

Not 100% sure what happened to fix it, but closing for the time being (but will monitor).

**Comment by jreback** [comment] 2017-08-08 13:13
https://travis-ci.org/MacPython/pandas-wheels/jobs/262048673

still recurring. I think this has to do with the factorization on 32-bit somehow.

**Closed** 2017-09-25 14:12 UTC
Labels: 32bit, Compat
