### ISSUE TITLE
BUG: Creation of Empty Dataframes is failing as of (2/1)

### ISSUE THREAD

**Issue by Shivi127** [pandas-dev/pandas#39542] opened 2021-02-01 19:11 UTC
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
I tried making a dummy dataframe
```
python


     column_names = ["a", "b", "c"]

      df = pd.DataFrame(columns = column_names)

```

#### Problem description

I am not able to create an empty df with columns.
![Screen Shot 2021-02-01 at 2 10 41 PM](https://user-images.githubusercontent.com/22840351/106506190-5f801180-6497-11eb-92bc-60122d65667f.png)

**Comment by jreback** [comment] 2021-02-02 02:26
pls show_versions() as the instructions indicate

this is because of numpy 1.20

**Comment by jreback** [comment] 2021-02-02 03:15
duplicate of #39520

**Closed by jreback** 2021-02-02 03:15 UTC
Labels: Bug, Needs Triage
