### ISSUE TITLE
BUG: df1.equals(df2) doesnt work if you convert one of the columns to float32

### ISSUE THREAD

**Issue by Chuck321123** [pandas-dev/pandas#56774] opened 2024-01-08 12:40 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Create a DataFrame with 50 rows and two columns
data = {
    'Col1': np.random.randint(1, 1000, 10),
    'Col2': np.random.uniform(1, 1000, 10).round(3)         
}

x = pd.DataFrame(data)

y = x.copy()

y["Col2"] = y["Col2"].astype("float32")

print(x.equals(y))
```

### Issue Description

As the title says it doesnt work, even if the numbers are the same. Might also check for float16 (but with another example with smaller numbers and less decimals) in case. 

### Expected Behavior

That it prints True

### Installed Versions

<details>

commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.12.1.final.0
python-bits         : 64
OS                  : Windows
OS-release          : 10
Version             : 10.0.19045
machine             : AMD64
processor           : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder           : little
LC_ALL              : None
LANG                : en
LOCALE              : Norwegian Bokmål_Norway.1252

pandas              : 2.1.4
numpy               : 1.26.2
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : 7.2.6
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.19.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : 14.0.2
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.4
sqlalchemy          : None
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.4
qtpy                : 2.4.1
pyqt5               : None

</details>

**Comment by rhshadrach** [comment] 2024-01-08 21:07
Documentation: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html

The documented behavior is that the columns must be the same dtype:

> Corresponding columns must be of the same dtype.

**Comment by mroeschke** [comment] 2024-01-08 21:13
Thanks for the report but closing as the intended behavior

**Closed by mroeschke** 2024-01-08 21:13 UTC
Labels: Bug, Closing Candidate

**Comment by Chuck321123** [comment] 2024-01-08 21:18
@mroeschke @rhshadrach Then explain this: ```import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Create a DataFrame with 50 rows and two columns
data = {
    'Col1': np.random.randint(1, 1000, 10),
    'Col2': np.random.uniform(1, 1000, 10).round(3)         
}

x = pd.DataFrame(data)

y = x.copy()

y["Col2"] = y["Col2"].astype("float32")

# Convert back to float64
y["Col2"] = y["Col2"].astype("float")

print(x.equals(y))
print(x.dtypes)
print(y.dtypes)
```

**Comment by rhshadrach** [comment] 2024-01-08 21:25
Conversition to float32 is lossy. Add `print(x - y)` at the end:

```
   Col1          Col2
0     0 -4.516602e-06
1     0 -9.765625e-07
2     0  2.441406e-06
3     0  2.294922e-05
4     0  9.765625e-06
5     0  8.239746e-07
6     0 -2.441406e-06
7     0  1.464844e-05
8     0  1.098633e-06
9     0 -5.371094e-06
```
