### ISSUE TITLE
IndexableSkiplist - Segmentation fault - 💥

### ISSUE THREAD

**Issue by lsbardel** [pandas-dev/pandas#14590] opened 2016-11-04 22:16 UTC
**python**: 3.5.2
**pandas**: 0.19.1
**system**: Mac v 10.12.1 

```python
>>> from pandas._window import IndexableSkiplist
>>> sl = IndexableSkiplist()
>>> len(sl)
0
>>> list(sl)
```
**Segmentation fault: 11** :collision:

**Comment by chris-b1** [comment] 2016-11-04 22:22
`IndexableSkipList` is not part of the pandas api - what are you trying to accomplish?

**Comment by lsbardel** [comment] 2016-11-04 22:26
Using it!
Weather or not is part of the API that is not good at all!

**Comment by chris-b1** [comment] 2016-11-04 22:33
This is an internal method - and the internal callers (apparently) respect the condition that cause this segfault - not getting a value from an empty skiplist.  Many of the internal methods are unsafe (e.g. no bounds checking) for performance reasons.

If you would like to submit a PR that prevents this case without a performance impact, it would probably be fine, but again, this is an implementation detail that you shouldn't rely on - if you need a skiplist, probably best to implement it in your project, and of course you are free to use the pandas version as a starting point.

**Comment by lsbardel** [comment] 2016-11-04 22:42
I'm not relying on anything, especially software that segfaults!
I was just playing with it and I saw this.
Crazy if you ask me.
In addition, I'm calling an iterator, and that should just work, nothing to do with performance!

**Comment by chris-b1** [comment] 2016-11-04 22:57
I appreciate you looking at, but this isn't API, so I'm going to close this - there is no guarantee on internal methods.  For example `pandas.algos.take_1d_bool_bool` is unsafe by design - it may read out of bounds memory - but any user-facing code that uses that method is safe.

**Closed by chris-b1** 2016-11-04 22:57 UTC

**Comment by lsbardel** [comment] 2016-11-04 23:12
:flushed: ... :scream:
over 1,700 open issues and 100 pull requests and you close one with as segfault!?
Out of here
