### ISSUE TITLE
Initializing a Series from and Index discards the "dtype" argument

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#17088] opened 2017-07-26 23:33 UTC
#### Code Sample, a copy-pastable example if possible

```python
In [2]: pd.Series(pd.Index([1,2,3]), dtype='bool').dtype
Out[2]: dtype('int64')

In [3]: pd.Series(pd.Index([1,2,3]), dtype='int32').dtype
Out[3]: dtype('int64')

In [4]: pd.Series(pd.Index([1,2,3]), dtype='float64').dtype
Out[4]: dtype('int64')
```
#### Problem description

The dtype should be enforced when explicitly passed; instead the dtype of the original index is preserved. Compare to:
``` python
n [5]: pd.Series(pd.Index([1,2,3]).astype('bool'), dtype='bool').dtype
Out[5]: dtype('O')

In [6]: pd.Series(pd.Index([1,2,3]).astype('float64'), dtype='float64').dtype
Out[6]: dtype('float64')
```

#### Expected Output

Initialization with index should behave analogously to initialization from a list or numpy array:
``` python
In [7]: pd.Series([1,2,3], dtype='bool').dtype
Out[7]: dtype('bool')

In [8]: pd.Series([1,2,3], dtype='float64').dtype
Out[8]: dtype('float64')

```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: 395f712133a4f6003ec8029458ade7ab423096d0
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-3-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: it_IT.UTF-8
LOCALE: it_IT.UTF-8

pandas: 0.21.0.dev+301.g395f71213
pytest: 3.0.6
pip: 9.0.1
setuptools: None
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 5.1.0.dev
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.2
openpyxl: None
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.6
lxml: None
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: 0.2.1
pyarrow: None

</details>

**Comment by gfyoung** [comment] 2017-07-26 23:34
Yeah...that's not right (I wouldn't see why / how that's intended behavior).  PR to patch is welcome!

**Comment by jreback** [comment] 2017-07-26 23:54
hmm, we coerce when dtype is passed, but maybe this fails. [2] should raise. I *think* there is a PR out there (maybe closed, but not merged), which is re-factoring this to handle correctly, if you'd have a look.

**Comment by toobaz** [comment] 2019-06-28 19:52
The behavior was fixed at some time, adding a test

**Closed** 2019-06-28 22:13 UTC
Labels: Bug, Dtypes, Index, Needs Tests
