### ISSUE TITLE
BUG: Issue with Dtype after Converting Columns to Datetime in Pandas 2.0.3

### ISSUE THREAD

**Issue by ProtekDev** [pandas-dev/pandas#54163] opened 2023-07-17 14:02 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df_test = pd.DataFrame(columns=['Date','Enabled'])
df_test.loc[0] = pd.Series({'Date': '2015-02-04 17:51:00', 'Enabled': 1})
df_test.loc[1] = pd.Series({'Date': '2015-02-04 17:51:59', 'Enabled': 1})

df_test.loc[:, 'Date'] = pd.to_datetime(df_test.loc[:, 'Date'])

print("Pandas version: ", pd.__version__)
print("type: ", type(df_test.loc[0, 'Date']))
print(".dtype:", df_test['Date'].dtype)
print("=" * 100)
df_test.info()
```

### Issue Description

I encountered an unexpected behavior in Pandas version 2.0.3 while working with the DataFrame. 
After converting columns to datetime, the Dtype is not being updated correctly.

This seems to happen only when using .loc with newer pandas than 1.2.4:
df_test.loc[:, 'Date'] = pd.to_datetime(df_test.loc[:, 'Date'])

This works withouth problems:
df_test['Date'] = pd.to_datetime(df_test.loc[:, 'Date'])

### Expected Behavior

df_test['Date'] = pd.to_datetime(df_test.loc[:, 'Date'])

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 0f437949513225922d851e9581723d82120684a6
python           : 3.11.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 2.0.3
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 23.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.6
jinja2           : None
IPython          : 8.12.0
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : 1.0.9
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 2.0.15
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by phofl** [comment] 2023-07-17 21:28
Hi, thx for your report. This is a duplicate of #52712 
I’d recommend avoiding loc for operations like this

**Closed by phofl** 2023-07-17 21:28 UTC
Labels: Bug, Needs Triage
