### ISSUE TITLE
BUG: df.loc[:, col] type assignments doesn't propagate dtype changes

### ISSUE THREAD

**Issue by briochh** [pandas-dev/pandas#52612] opened 2023-04-11 23:46 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([1.0, 2.0, 3.0])
print(df[0].dtypes)
df.loc[:, 0] = df.loc[:, 0].astype(int)
print(df[0].dtypes)
```

### Issue Description

It used to be possible to modify a columns dtype using some thing like:
`df.loc[:, col] = df.loc[:, col].astype(int)`
Since version 2.0 it seems that the RHS is now cast to the LHS dtype when using this sort of assignment (if possible). Therefore the dtype of the Series associated with `col` maybe silently unchanged. 
 
Perhaps this is by design and not a bug. Should column modification not use this syntax and instead use `df[col]=`?

### Expected Behavior

Expected the second print statement to return `int64` not `float64`

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 478d340667831908b5b4bf09a2787a11a14560c9
python           : 3.11.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.4.0
Version          : Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_NZ.UTF-8
pandas           : 2.0.0
numpy            : 1.24.2
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.6.1
pip              : 23.0.1
Cython           : None
pytest           : 7.3.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.12.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by phofl** [comment] 2023-04-12 13:06
Duplicate of #52593

**Closed by phofl** 2023-04-12 13:06 UTC
Labels: Bug, Needs Triage
