### ISSUE TITLE
BUG: datetime index name droped after date_range selection

### ISSUE THREAD

**Issue by SylvainLan** [pandas-dev/pandas#47545] opened 2022-06-29 08:36 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'date': [pd.to_datetime(d) for d in ['20220101', '20220102', '20220103']], 'value': [1, 2, 3]})
df = df.set_index('date')

print(df.loc[slice('20220101', '20220102'), :].index.name)
print(df.loc[pd.date_range('20220101', '20220102'), :].index.name)
```

### Issue Description

Hello,

I realized that using a `date_range` object with `.loc` on a datetime indexed dataframe drops the name of the corresponding index.

I'm not sure this behavior is normal.

### Expected Behavior

The name of the index should be kept

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.20.0-042000-generic
Version          : #201812232030 SMP Mon Dec 24 01:32:58 UTC 2018
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.3
numpy            : 1.23.0
pytz             : 2022.1
dateutil         : 2.8.2
setuptools       : 44.0.0
pip              : 20.0.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment] 2022-07-08 14:13
Thanks @SylvainLan for the report. Looks like a duplicate of #45818

> ### Expected Behavior
> The name of the index should be kept

This was indeed the case in pandas-1.3.5

There was an intentional change in commit: [4a2096da37ce5f5ebadabec8ba0f0fa6fec2019d] CI: Fix doctests (#42790) to preserve the name from an `Index`

`pd.date_range('20220101', '20220102')` creates an `DatetimeIndex(['2022-01-01', '2022-01-02'], dtype='datetime64[ns]', freq='D')` without a name.

**Closed by simonjayhawkins** 2022-07-08 14:13 UTC
Labels: Bug, Needs Triage
