### ISSUE TITLE
BUG: `pd.CategoricalIndex([1, True])` becomes `[1, 1]`

### ISSUE THREAD

**Issue by olofahlen** [pandas-dev/pandas#47013] opened 2022-05-13 12:46 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

pd.CategoricalIndex([0, True])
# returns CategoricalIndex([0, True], categories=[0, True], ordered=False, dtype='category')

pd.CategoricalIndex([1, True])
# returns CategoricalIndex([1, 1], categories=[1], ordered=False, dtype='category')
```

### Issue Description

See code

### Expected Behavior

```
pd.CategoricalIndex([0, True])
# returns CategoricalIndex([0, True], categories=[0, True], ordered=False, dtype='category')

pd.CategoricalIndex([1, True])
# returns CategoricalIndex([1, True], categories=[1, True], ordered=False, dtype='category')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : None
pytest           : 7.1.1
hypothesis       : 6.29.3
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.8.0
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4
brotli           : 
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : 1.4.32
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>

**Comment by samukweku** [comment] 2022-05-13 22:21
Does it generate the same output if you explicitly pass the categories?

**Comment by JeremyVriens** [comment] 2022-05-14 17:37
@samukweku when passing the categories explicitly, a ValueError is raised that the categories must be unique. 

I dived a bit into it and I found out that the issue is in the [core algorithms factorize_array](https://github.com/pandas-dev/pandas/blob/main/pandas/core/algorithms.py#L499-L551), more specifically  in the PyObjectHashTable (`from pandas._libs.hashtable import PyObjectHashTable`) factorize method.

The most simple reproducable example ([a simplified version of this](https://github.com/pandas-dev/pandas/blob/main/pandas/core/algorithms.py#L543-L545)):
```
uniques, _ = PyObjectHashTable().factorize(np.array([1, True], dtype="object"))
```
The expected result of uniques is [1, True], however uniques is [1].

**Comment by simonjayhawkins** [comment] 2022-05-15 09:39
Thanks @olofahlen for the report and @JeremyVriens for the investigation.

> The most simple reproducable example ([a simplified version of this](https://github.com/pandas-dev/pandas/blob/main/pandas/core/algorithms.py#L543-L545)):
> 
> ```
> uniques, _ = PyObjectHashTable().factorize(np.array([1, True], dtype="object"))
> ```
> 
> The expected result of uniques is [1, True], however uniques is [1].

This issue is quite similar to others, most recently #46987, so am closing as a duplicate.

**Closed by simonjayhawkins** 2022-05-15 09:39 UTC
Labels: Bug, Needs Triage
