### ISSUE TITLE
nunique aggerigation failes on empty frames

### ISSUE THREAD

**Issue by redsum** [pandas-dev/pandas#14578] opened 2016-11-03 16:03 UTC
#### A small, complete example of the issue

```python
# Your code here
df = pd.DataFrame(columns=['a','b','c'])    
df.groupby('a',as_index=False).agg({'b':'nunique'})
```

#### Expected Output
We shouldn't get an Exception
#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Darwin
OS-release: 16.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.0
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.25.1
numpy: 1.11.2
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.8
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.7
blosc: None
bottleneck: 1.1.0
tables: 3.3.0
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.4.0
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.9
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.43.0
pandas_datareader: None

</details>
i get the following output 

Traceback (most recent call last):
File "/Users/ilangadassi/Documents/workspace/python/MyTests/test1.py", line 75, in <module>
testDfGroup()
File "/Users/ilangadassi/Documents/workspace/python/MyTests/test1.py", line 71, in testDfGroup
df.groupby('a',as_index=False).agg({'b':'nunique'})
File "/Users/ilangadassi/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 3774, in aggregate
return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
File "/Users/ilangadassi/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 3272, in aggregate
result, how = self._aggregate(arg, _level=_level, *args, **kwargs)
File "/Users/ilangadassi/anaconda/lib/python2.7/site-packages/pandas/core/base.py", line 549, in _aggregate
result = _agg(arg, _agg_1dim)
File "/Users/ilangadassi/anaconda/lib/python2.7/site-packages/pandas/core/base.py", line 500, in _agg
result[fname] = func(fname, agg_how)
File "/Users/ilangadassi/anaconda/lib/python2.7/site-packages/pandas/core/base.py", line 483, in _agg_1dim
return colg.aggregate(how, _level=(_level or 0) + 1)
File "/Users/ilangadassi/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 2660, in aggregate
return getattr(self, func_or_funcs)(*args, **kwargs)
File "/Users/ilangadassi/anaconda/lib/python2.7/site-packages/pandas/core/groupby.py", line 3023, in nunique
res = out if ids[0] != -1 else out[1:]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jreback** [comment] 2016-11-03 17:08
duplicate of #12553 

there is a PR #12560 which is stalled if you'd like to pick it up

**Closed by jreback** 2016-11-03 17:08 UTC
Labels: Bug, Duplicate, Groupby

**Comment by redsum** [comment] 2016-11-04 06:33
@jreback , what do you mean by pick it up ?
do u want me to suggest a fix ?

**Comment by jorisvandenbossche** [comment] 2016-11-04 11:11
@redsum With pick it up, we mean to continue the work that is still needed on PR #12560 to get this merged (see the comments over there. Among other things, there are still tests failing)

**Comment by redsum** [comment] 2016-11-07 11:40
Hi @jreback 
i have made the changes.
run the tests 
how do i push the changes?

**Comment by jorisvandenbossche** [comment] 2016-11-07 11:48
See http://pandas.pydata.org/pandas-docs/stable/contributing.html#pushing-your-changes on pushing your changes and making a pull request
