### ISSUE TITLE
Cannot install pandas 0.24.2 from source with Python 2.7 into an environment without NumPy

### ISSUE THREAD

**Issue by didip** [pandas-dev/pandas#27435] opened 2019-07-17 18:09 UTC
#### Code Sample, a copy-pastable example if possible

```bash
RuntimeError: Python version >= 3.5 required.
```
#### Problem description

Under this docs: https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html

0.24.x is supposed to be backward compatible to Python 2.

```
The 0.24.x series of releases will be the last to support Python 2. Future feature releases will support Python 3 only. See Plan for dropping Python 2.7 for more details
```

#### Expected Output

0.24.2 should still work on Python 2.

**Comment by jreback** [comment] 2019-07-17 18:38
are you sure you actually tried to install 0.24.x? and not the 0.25rc1

**Comment by didip** [comment] 2019-07-17 18:51
Looks like it is trying to download `numpy` that is really new.

Our specified version for numpy is `numpy==1.16.2`

```
      File "/tmp/pip-install-E4jz9w/pandas/setup.py", line 746, in <module>
        **setuptools_kwargs)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/code/.cicd/runtime/python/.python/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/code/.cicd/runtime/python/.python/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-dglvOb/numpy-1.17.0rc2/setup.py", line 31, in <module>
    
    RuntimeError: Python version >= 3.5 required.
```

**Comment by jreback** [comment] 2019-07-17 19:02
right so numpy 1.17 is also python 3 only. guess would be that you have a too old pip, or are doing some odd type of installation.

**Comment by didip** [comment] 2019-07-17 20:34
Inside `setup.py`, should this block of logic check for Python version first and set max version of numpy for Python 2?

```
min_numpy_ver = "1.13.3"
setuptools_kwargs = {
    "install_requires": [
        "python-dateutil >= 2.6.1",
        "pytz >= 2017.2",
        "numpy >= {numpy_ver}".format(numpy_ver=min_numpy_ver),
    ],
    "setup_requires": ["numpy >= {numpy_ver}".format(numpy_ver=min_numpy_ver)],
    "zip_safe": False,
}
```

**Comment by TomAugspurger** [comment] 2019-07-17 20:51
Can you show the command you're running? You shouldn't be executing `setup.py`, pip would be doing it for you if needed.

**Comment by didip** [comment] 2019-07-17 21:00
Fairly standard procedure: `pip install -r requirements.txt`.

```
...
numpy==1.16.2
pandas==0.24.2
...
```

During pandas collection
```
Collecting pandas==0.24.2 
```

pandas ended up downloading much newer numpy: `numpy-1.17.0rc2` instead of what I specified in requirements.txt: `numpy==1.16.2`. `numpy==1.16.2` is downloaded correctly.

**Comment by TomAugspurger** [comment] 2019-07-17 21:03
What platform? Are you passing `--pre` or `--no-binary` anywhere? I'm confused why you aren't getting a wheel for NumPy and pandas.

**Comment by TomAugspurger** [comment] 2019-07-17 21:03
You might also post the full output.

**Comment by didip** [comment] 2019-07-17 21:06
```
Collecting pandas==0.24.2 (from redacted==0.0.0)
  Downloading https://pypi.redacted.com/packages/b2/4c/b6f966ac91c5670ba4ef0b0b5613b5379e3c7abdfad4e7b89a87d73bae13/pandas-0.24.2.tar.gz (11.8MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-E4jz9w/pandas/setup.py", line 746, in <module>
        **setuptools_kwargs)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/code/.cicd/runtime/python/.python/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/code/.cicd/runtime/python/.python/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/code/.cicd/runtime/python/.python/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-dglvOb/numpy-1.17.0rc2/setup.py", line 31, in <module>
    
    RuntimeError: Python version >= 3.5 required.
```

**Comment by TomAugspurger** [comment] 2019-07-17 21:14
So `pip install -r requirements.txt` works?

**Comment by didip** [comment] 2019-07-17 21:24
I checked out `v1.16.2` tag, and found this commit sha: `badf2901ea`.

That commit is intended for `1.17.x`, yes? Should it exist on `v1.16.2`?

**Comment by didip** [comment] 2019-07-17 21:44
Should the `setup.py` be updated like this? Essentially check Python 2 version?

```
import sys

min_numpy_ver = "1.13.3"
max_numpy_ver = ""

if (sys.version_info < (3, 0)):
    max_numpy_ver = "1.16.4"

numpy_install_rule = "numpy >= {numpy_ver}".format(numpy_ver=min_numpy_ver)
if max_numpy_ver:
    numpy_install_rule += ", <= {numpy_ver}".format(numpy_ver=max_numpy_ver)

setuptools_kwargs = {
    "install_requires": [
        "python-dateutil >= 2.6.1",
        "pytz >= 2017.2",
        numpy_install_rule,
    ],
    "setup_requires": [numpy_install_rule],
    "zip_safe": False,
}
```

**Comment by didip** [comment] 2019-07-18 18:15
The above snippet works on our internal fork of pandas. All of our Py 2 apps have correct dependencies now.

**Comment by jreback** [comment] 2019-07-18 19:59
there are no more updates planned to the 0.24.x branch

closing this issue as won't fix.

**Comment by didip** [comment] 2019-07-19 01:20
Why not publish 0.24.3? There is no other changes beside setup.py. This way people who are unfortunately stuck on Python 2 won't have broken deployment.

**Comment by TomAugspurger** [comment] 2019-07-19 01:29
This seems more like an issue with build process than with pandas.

**Comment by maxsond** [comment] 2019-08-01 16:19
I ran into this as well and figured out how to work around it without code modifications thanks to the comments here. I was originally building a Docker image from alpine:3.7, and in that container pip downloaded archive files for Numpy and Pandas rather than wheels. But when I switched my container image to python:2.7-stretch instead, then pip downloaded wheels for the versions it was supposed to and everything installed fine (I haven't tried python:2.7-alpine, though).

So although if it was up to me I'd probably apply the proposed setup.py change just for ease of use, the actual source of the problem is external to pandas. If I was going to chase this further I'd probably start with pip's source and see how it would handle running in the alpine:3.7 image to figure out why it would select archive files in that situation.

**Comment by TomAugspurger** [comment] 2019-08-01 17:05
Just to summarize the workaround: if you're seeing this issue with Python 2.7, you need to ensure that you have NumPy installed in the environment `pip install pandas` is run.

**Comment by jorisvandenbossche** [comment] 2019-09-10 10:16
Note that this is very easy to run into, simply doing 

```
pip install pandas==0.24.2 --no-binary :all:
```

in a clean env with python 2.7 and latest pip gives the error (I am using `--no-binary` to mimic a platform that has no wheels).

Does anybody know what is actually the underlying reason, or if this has been reported to pip / setuptools?

**Comment by jorisvandenbossche** [comment] 2019-09-10 10:39
OK, there is https://github.com/pypa/pip/issues/6667. 

So if I understand correctly, this is (within the limitations of setuptools handling of `setup_requires`) not an issue due to pip or how people are using it (installing should work without first needing to install the dependencies), but something we can fix on our end. 

I think we should consider doing a 0.24.3 release for this.

**Comment by TomAugspurger** [comment] 2019-09-10 19:40
What's the fix? Adding a pyproject.toml to 0.24.3?

**Comment by jorisvandenbossche** [comment] 2019-09-11 07:00
Adding a "< 1.17" to numpy in `setup_requires` (and probably as well to install_requires, and probably only if you're running python 2). 

That's the basically the only change they did in the "pandas27" (https://github.com/Tuxprogrammer/pandas/pull/1, only need to look at changes in setup.py)

**Comment by jorisvandenbossche** [comment] 2019-09-11 07:01
The proper fix is to add a pyproject.toml, but let's try to do that again on master first and not in a bug-fix release. But as long as we don't use pyproject.toml, that means we don't get the proper build isolation of pip and we need to work with legacy setuptools / setup_requires.

**Comment by TomAugspurger** [comment] 2019-09-11 11:37
> Adding a "< 1.17" to numpy in setup_requires (and probably as well to install_requires, and probably only if you're running python 2).

It would have to be Py2 only right? Else you can't install 0.24.2 with Python 3 and NumPy 1.17.

Is anyone actually going to do the release though? I suppose we can cut corners and not build conda packages. Not sure if we can skip building docs. But we have to build both an sdist & wheels, even though the issue is just with the sdist.

**Comment by didip** [comment] 2019-09-11 18:10
@TomAugspurger I have a patch to `setup.py` above.

```
import sys

min_numpy_ver = "1.13.3"
max_numpy_ver = ""

if (sys.version_info < (3, 0)):
    max_numpy_ver = "1.17"

numpy_install_rule = "numpy >= {numpy_ver}".format(numpy_ver=min_numpy_ver)
if max_numpy_ver:
    numpy_install_rule += ", < {numpy_ver}".format(numpy_ver=max_numpy_ver)

setuptools_kwargs = {
    "install_requires": [
        "python-dateutil >= 2.6.1",
        "pytz >= 2017.2",
        numpy_install_rule,
    ],
    "setup_requires": [numpy_install_rule],
    "zip_safe": False,
}
```

**Comment by jorisvandenbossche** [comment] 2019-09-11 18:15
@didip would you like to do a PR for this?

**Comment by TomAugspurger** [comment] 2019-09-11 18:48
This came up in the dev call today. We're interested in fixing this, but
I'm not sure if any maintainer is willing to spend too much time on it.
That said,
we are happy to

1. Accept a PR on the 0.24.x branch adding a max NumPy version for Python
2.7 (and a release note in 0.24.3 indicating this)
2. Make a tag and GitHub release with an sdist for 0.24.3 with just that
change from 0.24.2
3. Upload binaries and an sdist to PyPI

So, from anyone interested in fixing this, we're looking for a PR against
0.24.x, and someone interested
in going through pieces of the release
https://github.com/pandas-dev/pandas-release. Mainly

1. Building docs for 0.24.3 (we'll take care of uploading them)
2. Opening a PR on GitHub.com/macpython/pandas-wheels building wheels for
0.24.3

**Comment by didip** [comment] 2019-09-11 23:15
@jorisvandenbossche yes I can send a PR.

**Comment by jorisvandenbossche** [comment] 2019-09-13 10:15
@didip that would be very welcome!

**Comment by WillAyd** [comment] 2019-10-22 01:24
At this point we don't have any further plans for a 24.x release, so unfortunately I don't think this is something we will address (if anyone disagrees feel free to reopen)

**Closed by WillAyd** 2019-10-22 01:24 UTC
Labels: Build

**Comment by jorisvandenbossche** [comment] 2019-10-22 06:25
For people reading this: there is an open PR fixing this, but that needs some further updates to get CI passing. 
If people are still interested in seeing this fixed, you can contribute to that PR: https://github.com/pandas-dev/pandas/pull/28511

**Comment by hudasami** [comment] 2020-04-03 14:57
This is how it worked for me for a similar problem:
Python Version : 2.7.12
First download .whl of compatible NumPy : https://pypi.org/project/numpy/1.12.1/#files
Install using pip install "above file"
Then download .whl of compatible pandas : https://pypi.org/project/pandas/0.20.1/#files
Install using pip install "above file"
