### ISSUE TITLE
the latest version of pd.Timestamp issue on transforming timestamp

### ISSUE THREAD

**Issue by foolcage** [pandas-dev/pandas#22498] opened 2018-08-24 08:34 UTC
```python
In [1]: import pandas as pd

In [2]: pd.Timestamp.fromtimestamp(1535097720.0).timestamp()
Out[2]: 1535126520.0
```

the input is:1535097720.0 and the output is:1535126520.0

It seems pd.Timestamp use the local time zone to format the time and then treat it as UTC+0,but it's wrong.

in version 0.21.0, it works:
```
In [56]: pd.Timestamp.fromtimestamp(1535097720.0).timestamp()
Out[56]: 1535097720.0

```

**Comment by ko-han** [comment] 2018-08-24 08:58
It's like pandas will automatic set timezone to your local timezone. In my location, this behave like:
```
In [5]: pd.Timestamp.fromtimestamp(0).timestamp()
Out[5]: 28800.0
```
28800 = 8 * 60 * 60, which means UTC+8. So you should do:
```
In [8]: pd.Timestamp.utcfromtimestamp(0).timestamp()
Out[8]: 0.0
```
Hoo, it works!

**Comment by foolcage** [comment] 2018-08-24 09:19
@ko-han I think this is confused,timestamp should not related with timezone.

It is just:
>
the number of seconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC)

So we could compare the timestamp in different timezone.

**Comment by jbrockmendel** [comment] 2018-08-24 12:54
Duplicate of #22450.

**Closed** 2018-08-24 15:07 UTC
