### ISSUE TITLE
 aggregate the dataframe according to the multi-layer in the axis=1 does not work！

### ISSUE THREAD

**Issue by CatNofishing** [pandas-dev/pandas#46995] opened 2022-05-11 06:46 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np

df=pd.DataFrame(np.random.rand(6,6))
df.columns=pd.MultiIndex.from_product([['b','c'],[1,2,3]])
df.groupby(level=0,axis=1).agg(['mean','max'])
```

### Issue Description

I tried to aggregate the dataframe according to the multi-layer index in the axis = 1 direction, but  it failed.
![image](https://user-images.githubusercontent.com/33288114/167784286-7967683b-53d6-44d6-9550-d918dd1cea12.png)

### Expected Behavior

I expect result is 
![image](https://user-images.githubusercontent.com/33288114/167785278-ca35d89a-437c-48cb-875f-34011087e852.png)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.30.1
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : 5.0.0
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2
</details>

**Comment by rhshadrach** [comment] 2022-05-19 03:43
Agreed - this is a duplicate of #46904. The result here is incorrect and this should raise instead.

**Comment by rhshadrach** [comment] 2022-05-19 03:45
While the core issue is the same, it is possible to close #46904 without fixing this issue. I'm reopening to ensure it's closed appropriately.

**Closed** 2022-05-21 19:36 UTC
Labels: Bug, Groupby, Regression, Duplicate Report
