### ISSUE TITLE
How to stop sorting in pivot_table and pivot?

### ISSUE THREAD

**Issue by SaiPrabhu611** [pandas-dev/pandas#40055] opened 2021-02-25 19:31 UTC
<img width="646" alt="stack1" src="https://user-images.githubusercontent.com/41958569/109206385-cb6f4480-77cd-11eb-8cee-f1cc90af0a10.PNG">
<img width="669" alt="stack2" src="https://user-images.githubusercontent.com/41958569/109206396-d0cc8f00-77cd-11eb-8633-42bd91a15877.PNG">

as in the image 2 the transformation from dataframe has been done but it is auto sorted, i couldn't find any way to unsort it or stop sorting!
Is there any way sorting it?

**Comment by attack68** [comment] 2021-02-25 20:33
link to #39143?

**Comment by phofl** [comment] 2021-02-26 00:32
Yes, this seems like a duplicate

**Comment by SaiPrabhu611** [comment] 2021-02-26 03:59
> link to #39143?

The issue isn't solved right?

**Comment by phofl** [comment] 2021-02-26 09:02
No it is still open. Why?

**Comment by rhshadrach** [comment] 2021-02-27 02:11
Thanks for the report @SaiPrabhu611. Closing as a duplicate of #39143. As mentioned, this is still open; any further discussion should happen there.

**Closed by rhshadrach** 2021-02-27 02:11 UTC
Labels: Closing Candidate, Duplicate, Reshaping
