### ISSUE TITLE
MemoryError on Left Merge

### ISSUE THREAD

**Issue by Shellcat-Zero** [pandas-dev/pandas#24698] opened 2019-01-10 08:34 UTC
#### Code Sample

```python
In [3]: mem_usage(ccn)
Out[3]: '29629.72 MB'

In [4]: mem_usage(namemaps)
Out[4]: '4259.97 MB'

In [5]: ccn.shape
Out[5]: (28858789, 20)

In [6]: namemaps.shape
Out[6]: (28858505, 2)

In [7]: ccn = pd.merge(ccn,namemaps,on='name',how='left')

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-7-0dd32481b665> in <module>
----> 1 ccn = pd.merge(ccn,namemaps,on='name',how='left')

~/miniconda3/lib/python3.6/site-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     60                          copy=copy, indicator=indicator,
     61                          validate=validate)
---> 62     return op.get_result()
     63
     64

~/miniconda3/lib/python3.6/site-packages/pandas/core/reshape/merge.py in get_result(self)
    580             [(ldata, lindexers), (rdata, rindexers)],
    581             axes=[llabels.append(rlabels), join_index],
--> 582             concat_axis=0, copy=self.copy)
    583
    584         typ = self.left._constructor

~/miniconda3/lib/python3.6/site-packages/pandas/core/internals.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
   5419         else:
   5420             b = make_block(
-> 5421                 concatenate_join_units(join_units, concat_axis, copy=copy),
   5422                 placement=placement)
   5423         blocks.append(b)

~/miniconda3/lib/python3.6/site-packages/pandas/core/internals.py in concatenate_join_units(join_units, concat_axis, copy)
   5563     to_concat = [ju.get_reindexed_values(empty_dtype=empty_dtype,
   5564                                          upcasted_na=upcasted_na)
-> 5565                  for ju in join_units]
   5566
   5567     if len(to_concat) == 1:

~/miniconda3/lib/python3.6/site-packages/pandas/core/internals.py in <listcomp>(.0)
   5563     to_concat = [ju.get_reindexed_values(empty_dtype=empty_dtype,
   5564                                          upcasted_na=upcasted_na)
-> 5565                  for ju in join_units]
   5566
   5567     if len(to_concat) == 1:

~/miniconda3/lib/python3.6/site-packages/pandas/core/internals.py in get_reindexed_values(self, empty_dtype, upcasted_na)
   5873             for ax, indexer in self.indexers.items():
   5874                 values = algos.take_nd(values, indexer, axis=ax,
-> 5875                                        fill_value=fill_value)
   5876
   5877         return values

~/miniconda3/lib/python3.6/site-packages/pandas/core/algorithms.py in take_nd(arr, indexer, axis, out, fill_value, mask_info, allow_fill)
   1653             out = np.empty(out_shape, dtype=dtype, order='F')
   1654         else:
-> 1655             out = np.empty(out_shape, dtype=dtype)
   1656
   1657     func = _get_take_nd_function(arr.ndim, arr.dtype, out.dtype, axis=axis,

MemoryError:


```
#### Problem description

This problem is occurring on a machine with 384GB memory (Linux), and 64bit python (provided by Miniconda).  The merge is successful on smaller subsets of the 'ccn' dataframe, so I am not sure why it is failing on the full data set, given the dataframe sizes in memory (shown above).  Monitoring the merge process in `top` shows that total memory consumption goes up to about 45% usage before throwing this exception.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-1021-aws
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: 18.1
setuptools: 39.2.0
Cython: None
numpy: 1.15.4
scipy: None
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.15
pymysql: 0.9.3
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

</details>

**Comment by WillAyd** [comment] 2019-01-10 22:03
Unfortunately there's not a lot to diagnose with the information provided. Are you sure you aren't generating some kind of cartesian product?

FWIW I'm not sure what the `mem_usage` function you are using is but those numbers seem way off from what I'd expect with normal construction

```python
In [12]: pd.DataFrame(np.zeros((28858789, 20))).info()                                                                       
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28858789 entries, 0 to 28858788
Data columns (total 20 columns):
0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
19    float64
dtypes: float64(20)
memory usage: 4.3 GB

In [13]: pd.DataFrame(np.zeros((28858505, 2))).info()                                                                        
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28858505 entries, 0 to 28858504
Data columns (total 2 columns):
0    float64
1    float64
dtypes: float64(2)
memory usage: 440.3 MB
```

**Comment by Shellcat-Zero** [comment] 2019-01-11 19:13
@WillAyd I'll try to get you a reproducible example.  My dataframes consist mostly of string objects rather than floats.  Here is my `mem_usage` function:
```python
def mem_usage(pandas_obj):
    if isinstance(pandas_obj,pd.DataFrame):
        usage_b = pandas_obj.memory_usage(deep=True).sum()
    else: # we assume if not a df it's a series
        usage_b = pandas_obj.memory_usage(deep=True)
    usage_mb = usage_b / 1024 ** 2 # convert bytes to megabytes
    return "{:03.2f} MB".format(usage_mb)
```


Can you elaborate on what cartesian product you are referring to?  The nature of the left merge should imply that the length of the resulting dataframe will match the left (ccn) dataframe supplied to the argument.  The 'name' column in `namemaps` are all unique in the series of that dataframe, while there exist duplicates in the 'name' column of `ccn`.

**Comment by neil-rubens** [comment] 2020-04-16 00:33
I had a similar problem.
After some debugging it seems that join was happening on NaN values:
resulting # of rows increased a lot (even though I was doing a left join with unique values in columns in both tables (with the exception for NaN).

Dropping NaN values from one of the tables fixes it.
(in my case I dropped from right one)

**Comment by kernc** [comment] 2021-11-14 15:34
The issue is simply the cartesian product between NaN values (notice index 1000000):
```py
>>> import numpy as np
>>> a = pd.DataFrame({'x': ['foo'] + 1000*[pd.NA]})
>>> b = pd.DataFrame({'x': 1000*[pd.NA] + ['foo']})
>>>
>>> pd.merge(a, b, how='inner', on='x')
            x
0         foo
1        <NA>
2        <NA>
3        <NA>
4        <NA>
...       ...
999996    NaN
999997    NaN
999998    NaN
999999    NaN
1000000   NaN

[1000001 rows x 1 columns]
```
Notice also the curious `<NA>` _and_ `NaN` values present when `pd.NA` is used. :raised_eyebrow:

`pd.merge()` likely should have a toggle for handling NaN values.

@WillAyd please reopen.

**Comment by lordgrenville** [comment] 2021-12-16 09:02
Can someone explain why this creates a Cartesian product? Granted that `NaN != NaN`, but shouldn't the index just contain the sum of the `NaN`s in each df (ie 2000)?

**Comment by mroeschke** [comment] 2024-01-28 00:22
Looks like this is fixed on main and I believe we have tests for this so closing

**Closed by mroeschke** 2024-01-28 00:22 UTC
Labels: Missing-data, Performance, Reshaping
