### ISSUE TITLE
ENH: specify function to determine NaN when using fillna()

### ISSUE THREAD

**Issue by JakobHenning** [pandas-dev/pandas#34637] opened 2020-06-08 07:13 UTC
#### Is your feature request related to a problem?

When using `pd.fillna(df)` it does not fill all of the values that `pd.isna(df)` returns as `True`. Furthermore you might have some `NaN` values you want to fill, and some you don't

#### Describe the solution you'd like
include a `nan_function` to be parsed to `fillna()`. The `nan_function` should take a value (or row, or Series) as input and return True/False. Based on that `fillna` determines which values to replace.

```python

#examples
df = df.fillna(nan_function = pd.isnull, values = np.nan) #What pd.isnull returns as True is set to np.nan
df = df.fillna(nan_function = lambda x: x<0, values = np.nan) #Makes all negative numbers np.nan
df = df.fillna(nan_function = np.nan, values = 0) #Only fills np.nan with zeroes
```

**Comment by jorisvandenbossche** [comment] 2020-06-08 10:59
If you want a customized selection, you could also work with boolean indexing directly? LIke

```
df[my_condition] = fill_value
```

That seems more generic than trying to add functionality to `fillna` that allows to fill other things than NA/NaN.

> When using pd.fillna(df) it does not fill all of the values that pd.isna(df) returns as True. 

This aspect sounds as a potential bug. Do you have a reproducible example?

**Comment by JakobHenning** [comment] 2020-06-08 11:19
```python
df = pd.DataFrame({"date":[pd.NaT,"2019-01-01"],"npnan":[np.nan,2],"number":[1,None]})
#date |             npnan | number
#-----------------------
#NaT                NaN   1
#2019-01-01    2.0      None

df.isnull()
#date | npnan | number
#------------------------
#True   True      False
#False   False    False


df.fillna(values=np.nan,inplace=True)
#date|             npnan  | number
#------------------------
#NaT                NaN   1
#2019-01-01    2.0      NaN
```

the `NaT` is not `np.nan` but `pd.NaT` (calling `np.isnan(df.iloc[0,0])` throws `TypeError`)

**Comment by jorisvandenbossche** [comment] 2020-06-08 12:10
If you fill with another value than `np.nan`, you will see it is actually filling all spots that `isnull()` gives True for:

```
In [11]: df = pd.DataFrame({"date":[pd.NaT,"2019-01-01"],"npnan":[np.nan,2],"number":[1,None]})  

In [12]: df.fillna(10)  
Out[12]: 
                  date  npnan  number
0                   10   10.0     1.0
1  2019-01-01 00:00:00    2.0    10.0
```

But, when filling with `np.nan`, this value gets coerced to pd.NaT for the timestamp column, since that is the missing value being used for this dtype.

**Comment by Jakobhenningjensen** [comment] 2020-06-08 12:44
Since no error/warning is cast when you specify `value=np.nan` you would assume that all NaNs are `np.nan` (also on Timestamp). If you try `np.isnan(pd.NaT)` then you get a `TypeError`, which is not expected, since you assume that all nans are `np.nan`

**Comment by TomAugspurger** [comment] 2020-06-08 13:12
I wouldn't recommend filling NaT values with `np.nan`. NaN is a float, while NaT is a datetime.

If you really need to do this you should cast the datetime columns to object or float dtype before filling with nan.

I don't think there's anything for pandas to do here.

**Comment by TomAugspurger** [comment] 2020-09-04 13:47
Going to close this, since casting before filling is probably clearest for this specific use case, and I don't think that fillna taking a callable will fit too well in related places.

**Closed by TomAugspurger** 2020-09-04 13:47 UTC
Labels: Enhancement, Needs Triage
