### ISSUE TITLE
Series.sort_index does not() implement optional argument kind

### ISSUE THREAD

**Issue by pelodelfuego** [pandas-dev/pandas#14971] opened 2016-12-23 11:07 UTC
#### Code Sample, a copy-pastable example if possible

```python

>>> import pandas as pd
>>> a = pd.Series(range(10))
>>> a.sort_index(kind='mergesort')

```
#### Problem description

The documentation present the 'kind' optional argument:
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.sort_index.html#pandas.Series.sort_index

But it is not implemented (while it is for depreciated _sort()_ )

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.9.final.0
python-bits: 64
OS: Linux
OS-release: 3.16.0-4-amd64
machine: x86_64
processor:
byteorder: little
LC_ALL: None
LANG: fr_FR.utf8
LOCALE: fr_FR.UTF-8
pandas: 0.19.0
nose: 1.3.4
pip: 1.5.6
setuptools: 5.5.1
Cython: 0.21.1
numpy: 1.8.2
scipy: 0.14.0
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: None
patsy: 0.4.1
dateutil: 2.2
pytz: 2012c
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.4.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: 4.4.0
html5lib: 0.999
httplib2: 0.9.1
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.7.3
boto: 2.38.0
pandas_datareader: None

</details>

**Comment by jreback** [comment] 2016-12-23 11:23
this is a dupe of #13859  and fixed in https://github.com/pandas-dev/pandas/pull/14445 (its in 0.20.0)

**Closed by jreback** 2016-12-23 11:23 UTC

**Comment by pelodelfuego** [comment] 2016-12-26 23:15
Ty for your quick reply and moreover your awesome work !
