### ISSUE TITLE
QST: Qcut and Interval Question

### ISSUE THREAD

**Issue by rm17tink** [pandas-dev/pandas#52622] opened 2023-04-12 12:32 UTC
### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).

### Link to question on StackOverflow

https://stackoverflow.com/questions/75987834/qcut-for-decile-and-interval-bins

### Question about pandas

I have an issue I cant seem to find the answer to. I linked my stackOverflow post as well. When creating qcut() and checking the min  and max values the min value call it X in one bin equals the (X - y] in that group. How is this possible given the interval rule of being excluded? 

Thanks

**Comment by topper-123** [comment] 2023-05-14 17:37
You need to give a working code example for us being able to look at your question. Can you also show what result you are expecting to get from the operation.

**Comment by topper-123** [comment] 2023-05-20 08:15
We can't progress on this because the issue isn't formulated precisely enough. I'm closing, but if you get back with a working example, I will of course reopen.

**Closed by topper-123** 2023-05-20 08:15 UTC
Labels: Usage Question, Needs Info, cut, Closing Candidate
