### ISSUE TITLE
Consistent API for suffixes in merge / join

### ISSUE THREAD

**Issue by ksyme99** [pandas-dev/pandas#22231] opened 2018-08-07 11:31 UTC
The way to add suffixes is inconsistent between join and merge:

```python
df1.merge(df2, suffixes=('left', 'right')
df1.join(df2, lsuffix='left', rsuffix='right')

```

I always have to look this up as I get it wrong every time! I do not have a strong preference for which to use, perhaps slightly prefer the merge syntax.

Can the API be updated to be consistent, with backwards support but deprecated?

**Comment by WillAyd** [comment] 2018-08-07 15:13
I'd be +1 on the join syntax and deprecating merge. Let's see what others think

**Comment by rhshadrach** [comment] 2022-07-28 21:08
Duplicate of #46046; there is a bit more discussion there (though not by much). Closing.

**Closed by rhshadrach** 2022-07-28 21:08 UTC
Labels: Duplicate Report, Deprecate, API - Consistency
