### ISSUE TITLE
`np.array([pd.Series({'a':'a'})])` works but `np.array([pd.Series({1:1})])` doesn't

### ISSUE THREAD

**Issue by soerenwolfers** [pandas-dev/pandas#38543] opened 2020-12-17 16:26 UTC
The last line here throws a `KeyError: 0`
```
import numpy as np
import pandas as pd
np.array([pd.Series({0:0})])
np.array([pd.Series({'a':'a'})])
np.array([pd.Series({1:1})])
```
Is that a bug?

**Comment by jorisvandenbossche** [comment] 2020-12-18 08:37
Can you show the output of `pd.show_versions()` ?

**Comment by MarcoGorelli** [comment] 2020-12-18 15:09
I can't reproduce this on v1.1.5

**Comment by soerenwolfers** [comment] 2020-12-18 15:12
Sorry, 

pandas           : 1.1.4
numpy            : 1.17.4

**Comment by MarcoGorelli** [comment] 2020-12-18 15:29
Thanks, can confirm this reproduces.

If you upgrade pandas to 1.1.5 you'll find it fixed - it would be good to do a git bisect to figure out when this was fixed, and (if it was fixed accidentally) to add a test

**Comment by simonjayhawkins** [comment] 2020-12-18 15:51
can't reproduce with 0.25.3, 1.0.5, 1.1.3, 1.1.4, 1.1.5, master (all envs using numpy 1.19+)

**Comment by MarcoGorelli** [comment] 2020-12-18 15:56
Same, just tried in 1.1.4 with numpy 1.19.4 and it works fine.

Conversely, on `master` and with numpy 1.17.4, it still fails. I think we can close this as an upstream bug anyway

**Comment by jorisvandenbossche** [comment] 2020-12-18 16:04
But is it an identified / reported upstream issue? 
It think it's still good to add a test (it's not given that this was an intentional/tested fix on numpy's side)

**Comment by MarcoGorelli** [comment] 2020-12-18 16:13
Sure - @soerenwolfers do you feel like contributing a test for this issue? If so, please check the [contributing guide](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html)

**Comment by seberg** [comment] 2020-12-18 17:00
Wow, there was an additional layer of confusion to unravel here :) (for myself). If there is only a single item in the dataframe, NumPy used to do use `series[0]` to get that item. But if there were more items it effectively used `list(series)`.  Since `list()` probably uses `__iter__` internally – and that goes by position and not index – the only thing that gives different results on new NumPy seems to be the specific case of a series with a single element and non 0 index.

**Comment by horaceklai** [comment] 2021-08-07 23:27
take

**Comment by horaceklai** [comment] 2021-08-10 22:41
Hi I'm not sure what to do now. I made a PR and did the changes requested, but when running the tests, it throws the Key error: 0 as stated in the beginning of this issue.

https://github.com/pandas-dev/pandas/pull/42939

**Closed** 2021-09-13 02:18 UTC
Labels: good first issue, Needs Tests, Upstream issue
