### ISSUE TITLE
BUG: Compare type `int64` with `Int64` fails

### ISSUE THREAD

**Issue by ChiQiao** [pandas-dev/pandas#43038] opened 2021-08-14 15:50 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
pd.api.types.pandas_dtype("int64") == "Int64"

```

#### Problem description

The code above fails (`TypeError: data type 'Int64' not understood`) while the following cases pass:
```Python
pd.api.types.pandas_dtype("int64") == "int64"
pd.api.types.pandas_dtype("Int64") == "Int64"
pd.api.types.pandas_dtype("Int64") == "int64"
```

#### Expected Output
`False`

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.7.11.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : None.None

pandas           : 1.3.1
numpy            : 1.20.3
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 52.0.0.post20210125
Cython           : 0.29.24
pytest           : 6.1.2
hypothesis       : 6.14.1
sphinx           : 4.0.2
blosc            : None
feather          : None
xlsxwriter       : 1.4.4
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 2021.07.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : 0.4.2
scipy            : 1.6.2
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.19.0
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.0

</details>

**Comment by jbrockmendel** [comment] 2021-08-14 18:31
This is an issue with `np.dtpye.__eq__`, should be fixed by https://github.com/numpy/numpy/pull/19228

**Comment by simonjayhawkins** [comment] 2021-08-16 10:48
can't reproduce on pandas 1.2.5 onwards.

```
>>> pd.__version__
'1.2.5'
>>> pd.api.types.pandas_dtype("int64") == "Int64"
False
```

> #### Expected Output
> `True`

numpy int dtypes can't hold missing values, so `False` seem more appropriate.

**Comment by ChiQiao** [comment] 2021-08-16 15:45
Thanks @jbrockmendel and @simonjayhawkins for the input

> can't reproduce on pandas 1.2.5 onwards.

Since it may be a bug from numpy, I wonder which numpy version you were using?
Also, I wonder if you were able to reproduce the bug given the environment I posted (pandas 1.3.1, numpy 1.20.3)?




> numpy int dtypes can't hold missing values, so `False` seem more appropriate.

Yes, that was a typo on my side. I've updated the description.

**Comment by kwhkim** [comment] 2021-08-30 17:35
In my case, no bug found. (But I can not understand how it can be a bug from `numpy` when `numpy` does not support integer `NA`s. Is it the reason that they named integer NA as `pd.NA`?)

```
>>> pd.api.types.pandas_dtype("int64") == "Int64"
False
>>> pd.__version__
'1.3.1'
>>> np.__version__
'1.21.1'
```

**Comment by mzeitlin11** [comment] 2021-10-13 02:02
See discussion in #43993 - this is fixed for newer versions of numpy, contributions welcome to add a regression test!

**Comment by paulvdbles** [comment] 2021-10-20 13:49
take

**Comment by paulvdbles** [comment] 2021-11-20 13:12
untake

**Comment by fotino21** [comment] 2021-11-24 20:00
take

**Comment by fotino21** [comment] 2021-11-24 20:04
Can you give me an example for how to add a regression test for this issue? Thank you :)

**Comment by mzeitlin11** [comment] 2021-11-24 20:20
> Can you give me an example for how to add a regression test for this issue? Thank you :)

I'd recommend looking at closed `good first issues` about testing (for example from https://github.com/pandas-dev/pandas/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aclosed+label%3A%22Needs+Tests%22). If you look at some pull requests which close the issue, those should be good examples

**Comment by simonjayhawkins** [comment] 2022-01-20 15:07
closing as tests added in #44840

**Closed by simonjayhawkins** 2022-01-20 15:07 UTC
Labels: Dtype Conversions, Compat, good first issue, Needs Tests
