### ISSUE TITLE
Group by column which contains None

### ISSUE THREAD

**Issue by semigodking** [pandas-dev/pandas#21419] opened 2018-06-11 07:33 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame([[None, 1], [None, 1]], columns=['a', 'b'])
grouped = df.groupby('a')
print(len(grouped.groups))
print(grouped.groups)
df = pd.DataFrame([[None, 1], [1, 1]], columns=['a', 'b'])
grouped = df.groupby('a')
print(grouped.groups)
```
#### Problem description
Not sure if this is design intent or a bug. When None appears in column grouped by, None is not counted as a group. If it is a design intent, is there any we to turn off this feature? 
#### Expected Output
None is counted as a group.
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.2.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-119-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_HK.UTF-8
LOCALE: en_HK.UTF-8

pandas: 0.23.0
pytest: 3.2.1
pip: 9.0.1
setuptools: 36.4.0
Cython: None
numpy: 1.14.3
scipy: None
pyarrow: None
xarray: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: None
tables: None
numexpr: 2.6.5
feather: None
matplotlib: None
openpyxl: 2.4.9
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: 1.1.15
pymysql: None
psycopg2: 2.7.3.1 (dt dec pq3 ext lo64)
jinja2: 2.9.6
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment] 2018-06-11 11:07
Duplicate of https://github.com/pandas-dev/pandas/issues/3729.

Not really by design, just hard to do in the current implementation.

**Closed by TomAugspurger** 2018-06-11 11:07 UTC

**Comment by ryancollingwood** [comment] 2018-06-26 02:38
At the very least some sort of warning would go some ways to diagnosing issues with groupby.
