### ISSUE TITLE
BUG: to_sql pandas segmentation fault (core dumped)

### ISSUE THREAD

**Issue by shakthifuture** [pandas-dev/pandas#49367] opened 2022-10-28 05:12 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
masteroutput_df.to_sql(name='master', con=engine,
                    schema='dbo_eg', if_exists='append', index=False, chunksize=5000)
```

### Issue Description

The above line gives me "segmentation fault (core dumped)" error when we have huge data, after that the application stopped. If we pass less data, we didn't this error.

### Expected Behavior

It should work even with huge(rows: 83148, columns: 46) data.

### Installed Versions

1.5.1

**Comment by mzeitlin11** [comment] 2022-10-28 19:50
Thanks for reporting this @shakthifuture! There's not much we can use to investigate here - if you can't share the data, can you build a minimal example with lots of random data that segfaults? Otherwise, it would be very helpful to know the backtrace, which you could obtain following https://pandas.pydata.org/docs/development/debugging_extensions.html so we can figure out what codepath is being hit or if the segfault is even in `pandas` code.

Also would be helpful to know if the issue was present in earlier versions of `pandas`.

**Comment by polaron-cao** [comment] 2022-12-01 05:28
I have a similar issue with to_sql function. The to_sql works well in the version of 1.3.2 but it can not work in the version of 1.5.2. Now my pandas version rolls back to 1.3.2 due to this issue

**Comment by phofl** [comment] 2022-12-09 11:52
Closing for now, please ping to reopen when you can provide something reproducible

**Closed by phofl** 2022-12-09 11:52 UTC
Labels: Bug, IO SQL, Needs Info, Segfault

**Comment by kutlay** [comment] 2024-04-16 13:52
I had this same problem and it took me a while to fix it. For me the problem was using the "**mysql**" driver. I switched to **mysql+pymysql**.


In my case, I was connecting to a MySQL a database using the URL creator:

```
database_connection_url = URL.create(drivername='mysql', host="mysql server host",
                                             database='database name',
                                             query={
                                                 'read_default_file': "my credential file"}
                                             )
````

I read online that the problem might be the driver so I wanted to change it to mysql+pymysql. I couldn't find a way to use URL generator to do that for me, so I switched to constructing the URL myself and created the engine like the following:

```
create_engine(url = f'mysql+pymysql://{host}?database={database}&read_default_file={file_path}')
```
