### ISSUE TITLE
Package installation failure due to pyqt

### ISSUE THREAD

**Issue by charlesdong1991** [pandas-dev/pandas#27643] opened 2019-07-29 18:58 UTC
When i am following the instruction and installing pandas packages listed in `requirement-dev.txt` on my new laptop, i get an error: `Could not find a version that satisfied the requirement pyqt (from -r requirement-dev.txt (line 48)). No matching distribution found for pyqt.`

And I need to change the package name to `pyqt5` to succeed the installation. Is it something that should also be changed in `requirement-dev` or it's due to issue of my virtualenv which i don't think it is though?

**Comment by TomAugspurger** [comment] 2019-07-29 19:05
Looks like a duplicate of https://github.com/pandas-dev/pandas/issues/26838

I think https://github.com/pandas-dev/pandas/issues/26838#issuecomment-509293185 provides a solution if you want to implement it.

**Closed by TomAugspurger** 2019-07-29 19:05 UTC
