### ISSUE TITLE
groupby/resample of boolean series can result in bool or float dtype depending on values

### ISSUE THREAD

**Issue by kevinsa5** [pandas-dev/pandas#24469] opened 2018-12-28 18:19 UTC
```python
>>> import pandas as pd
>>> pd.__version__
u'0.23.4'
>>> 
>>> df = pd.DataFrame({
...     'x': [1,1,2,2,3,3],
...     'y': [False, False, False, True, True, True]
... })
>>> 
>>> print df.loc[df['x'] < 3,:].groupby('x')['y'].sum()
x
1    False
2     True
Name: y, dtype: bool
>>> print df.loc[:,:].groupby('x')['y'].sum()
x
1    0.0
2    1.0
3    2.0
Name: y, dtype: float64
```

When performing groupby or resample summations on a boolean series, the output dtype will be `bool` if all of the sums are `0` or `1`, and `float` if any of the sums is greater than `1`.  I expected the dtype of the output series to be dependent only on the dtype of the input series, not the values of the input series.

**Comment by chris-b1** [comment] 2018-12-28 18:38
Duplicate of #7001 - PR to fix would be welcome.  I'm guessing we try to cast back to the original dtype after the sum - so if there are only 1s and 0s, it casts, otherwise doesn't - agree it should always be numeric.

**Closed by chris-b1** 2018-12-28 18:38 UTC
