### ISSUE TITLE
BUG: inconsistent `groupby.apply` behaviour depending on column dtypes

### ISSUE THREAD

**Issue by od-crypto** [pandas-dev/pandas#43206] opened 2021-08-25 10:16 UTC
I see strange `groupby.apply` behaviour: resulting index depends on the existence of the `Timestamp` dtype column. MWE: 

```python
import pandas as pd
df = pd.DataFrame({
    'date_val': {
        0: pd.Timestamp('2017-01-01 00:00:00'),
        1: pd.Timestamp('2017-01-01 00:00:00'),
        2: pd.Timestamp('2017-02-01 00:00:00'),
        3: pd.Timestamp('2017-02-01 00:00:00')
    },
    'uid': {
        0: '1',
        1: '2',
        2: '1',
        3: '2'
    },
    'str_val': {
        0: str('2017-01-01 00:00:00'),
        1: str('2017-01-01 00:00:00'),
        2: str('2017-02-01 00:00:00'),
        3: str('2017-02-01 00:00:00')
    }
})

df1 = df.groupby('uid', as_index=False)[['uid', 'str_val', 'date_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df2 = df.groupby('uid', as_index=False)[['uid', 'str_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df3 = df.groupby('uid', as_index=False)[['uid', 'date_val']].apply(lambda x: x.sort_values(by='date_val',ascending=True))

print(df1)
print(df2)
print(df3)
```

Output:

```
  uid              str_val   date_val
0   1  2017-01-01 00:00:00 2017-01-01
1   2  2017-01-01 00:00:00 2017-01-01
2   1  2017-02-01 00:00:00 2017-02-01
3   2  2017-02-01 00:00:00 2017-02-01
    uid              str_val
0 0   1  2017-01-01 00:00:00
  2   1  2017-02-01 00:00:00
1 1   2  2017-01-01 00:00:00
  3   2  2017-02-01 00:00:00
  uid   date_val
0   1 2017-01-01
1   2 2017-01-01
2   1 2017-02-01
3   2 2017-02-01
```
I expect the index to be like in the second output (`df2`). Indexes in `df1` and `df3` seem strange.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by simonjayhawkins** [comment] 2021-08-25 12:02
Thanks @od-crypto for the report.

> I expect the index to be like in the second output (`df2`). Indexes in `df1` and `df3` seem strange.

That was the result on 1.2.5

On master the second case now has the same index as the other two cases, a regular index.

not sure without investigating further which is correct or whether the changes were intentional.

will label as a regression for now pending further investigation.

**Comment by simonjayhawkins** [comment] 2021-08-25 12:57
> not sure without investigating further which is correct or whether the changes were intentional.

for 1st case

first bad commit: [a3bb751cc672b487e5ff464605661acbc22448fa] REF: back DatetimeBlock, TimedeltaBlock by DTA/TDA (#40456)

so the change was probably not intentional. @jbrockmendel is https://github.com/pandas-dev/pandas/issues/42921#issuecomment-898038166 relevant here?

**Comment by simonjayhawkins** [comment] 2021-08-25 15:06
> On master the second case now has the same index as the other two cases, a regular index.

first bad commit: [d037ff6a4757bf8af2ca2431ba7d4b22b1959075] REF: remove libreduction.apply_frame_axis0 (#42992)

as this is a very recent change, could considered reverting that.

**Comment by jbrockmendel** [comment] 2021-09-02 18:05
OK, some progress here.  within each group, each of the columns is already sorted, so the sort_values being applied doesn't do any reindexing, so it evaluates `mutated=False`, which i guess affects how it re-stacks the results, probably in _wrap_applied_output.

@od-crypto what does the [0, 1] index level in `df2` correspond to?  i.e. why is that what you expect?

**Comment by od-crypto** [comment] 2021-09-03 09:35
@jbrockmendel which behaviour to choose, df1/df2 or df3, is a second question, important is that it is consistent a the end. 
Yes, the date was already sorted within each 'uid' group also in the input df. However, if you change the input df to be NOT sorted by the date, you obtain the df2 behaviour in all three cases. just run the code below: 
```
import pandas as pd
df = pd.DataFrame({
    'date_val': {
        0: pd.Timestamp('2017-02-01 00:00:00'),
        1: pd.Timestamp('2017-01-01 00:00:00'),
        2: pd.Timestamp('2017-01-01 00:00:00'),
        3: pd.Timestamp('2017-02-01 00:00:00')
    },
    'uid': {
        0: '1',
        1: '2',
        2: '1',
        3: '2'
    },
    'str_val': {
        0: str('2017-02-01 00:00:00'),
        1: str('2017-01-01 00:00:00'),
        2: str('2017-01-01 00:00:00'),
        3: str('2017-02-01 00:00:00')
    }
})

dfg = df.groupby('uid', as_index=False)

df1 = dfg[['uid', 'str_val', 'date_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df2 = dfg[['uid', 'str_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df3 = dfg[['uid', 'date_val']].apply(lambda x: x.sort_values(by='date_val',ascending=True))

print(df1)
print(df2)
print(df3)
```

**Comment by od-crypto** [comment] 2021-09-03 10:05
@jbrockmendel answering your question above: it is not clear, what does the [0, 1] index level in df2 correspond to.

**Comment by jbrockmendel** [comment] 2021-09-04 20:40
> important is that it is consistent at the end

I agree.  On master it is currently consistent, but with the result that you said in the OP seems strange.  I'm trying to understand what the first level in the MultiIndex result corresponds to.  Can you help me understand this?

**Comment by simonjayhawkins** [comment] 2021-09-05 08:18
> > important is that it is consistent at the end
> 
> I agree. On master it is currently consistent ...

but to be clear, on released pandas it is not. so if we decide that the new behavior is correct and is a bugfix and not an api breaking change we may want to consider backporting #42992

**Comment by od-crypto** [comment] 2021-09-06 08:37
> > important is that it is consistent at the end
> 
> I agree. On master it is currently consistent, but with the result that you said in the OP seems strange. I'm trying to understand what the first level in the MultiIndex result corresponds to. Can you help me understand this?

@jbrockmendel, By "df1/df3 seem strange" I meant strange within the same pandas release 1.3.2, as when one feeds the above reported code with an unsorted input df, one obtains for all the three cases the df2 behaviour. The first level in the Multiindex of df2 seem to "correspond to the index of the 'uid' group, sorted by 'uid'." However if choosing between the df1/df3 and df2 for the next release, one might consider voting for the df1/df3, as backward compatibility is always a weighty argument...

**Comment by jbrockmendel** [comment] 2021-09-07 22:06
> The first level in the Multiindex of df2 seem to "correspond to the index of the 'uid' group, sorted by 'uid'."

The first level in df2.index in the OP is `[0, 0, 1, 1]` (only a single 0 and a single 1 are printed), and the UIDs are all either '1' or '2', so this doesn't make sense to me.  Is there a chance you were referring to a different level?

**Comment by simonjayhawkins** [comment] 2021-10-16 19:29
changing milestone to 1.3.5

**Comment by simonjayhawkins** [comment] 2021-11-28 14:14
> However, if you change the input df to be NOT sorted by the date, you obtain the df2 behaviour in all three cases. just run the code below:

This is on master so it does appear that this invalidates the consistency argument for master.

so we can probably rule out backporting #42992 https://github.com/pandas-dev/pandas/issues/43206#issuecomment-913108156 (This actually fixed another regression #41999 but was not backported)

so it looks like we effectively now have two regressions

1. on 1.3.x: undocumented/unintentional change to df1/df3 behavior, #40456
2. on master: undocumented/unintentional change to df2 behavior, #42992

**Comment by simonjayhawkins** [comment] 2021-11-28 14:28
I've added the blocker for rc label to increase priority if not fixed for 1.3.5

**Comment by simonjayhawkins** [comment] 2021-12-11 09:49
changing milestone

**Comment by jreback** [comment] 2021-12-23 19:10
we cannot block on this w/o a PR for the rc.

**Comment by jreback** [comment] 2021-12-30 02:11
@rhshadrach @jbrockmendel can you summarise the issue & what we need to decide here

**Comment by rhshadrach** [comment] 2021-12-31 12:54
I agree with previous comments that in the OP, the result for `df1` and `df3` should be the same as the reported result for `df2`. Currently on master, even `df2` gives the wrong result.

The core issue here is `apply` looking at the result and concluding "this is a transform" because the index is the same as the input in an operation where this is not generally true. It would be fixed by #34998.

A potential secondary issue is the resulting index containing the values 0 and 1 (ref: https://github.com/pandas-dev/pandas/issues/43206#issuecomment-914659448). This looked odd at first glance to me as well, but I believe it is correct behavior. With `as_index=False`, the resulting index is a RangeIndex enumerating the groups. That behavior is consistent across groupby.

**Comment by jbrockmendel** [comment] 2021-12-31 21:41
This is a hard problem, my only real opinion here is that reinstating libreduction.apply_frame_axis0 (which git blame suggests would fix this) would cause more problems than it solves.

**Comment by jreback** [comment] 2021-12-31 21:52
moving to 1.5 we cannot wait on this.

**Comment by rhshadrach** [comment] 2021-12-31 23:05
@jbrockmendel Are you thinking #34998 wouldn't fix? Agreed on not reintroducing apply_frame_axis0.

**Comment by jbrockmendel** [comment] 2022-01-02 16:15
> Are you thinking #34998 wouldn't fix?

Haven't looked at it closely.  It's plausible.

**Comment by NumberPiOso** [comment] 2022-06-11 19:25
Currently, running 
```python
df1 = df.groupby('uid', as_index=False)[['uid', 'str_val', 'date_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df2 = df.groupby('uid', as_index=False)[['uid', 'str_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df3 = df.groupby('uid', as_index=False)[['uid', 'date_val']].apply(lambda x: x.sort_values(by='date_val',ascending=True))
```
produces
```python
FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
```
and results to:
```python
>>> print(df1)
0   1  2017-01-01 00:00:00 2017-01-01
1   2  2017-01-01 00:00:00 2017-01-01
2   1  2017-02-01 00:00:00 2017-02-01
3   2  2017-02-01 00:00:00 2017-02-01
>>> print(df2)
  uid              str_val
0   1  2017-01-01 00:00:00
1   2  2017-01-01 00:00:00
2   1  2017-02-01 00:00:00
3   2  2017-02-01 00:00:00
>>> print(df3)
  uid   date_val
0   1 2017-01-01
1   2 2017-01-01
2   1 2017-02-01
3   2 2017-02-01
```

So now the behaviour is consistent which was the BUG. I think it should be closed now.

**Comment by NumberPiOso** [comment] 2022-06-11 19:26
However, the default behaviour will change in the future:

```python
>>> df1 = df.groupby('uid', as_index=False, group_keys=True)[['uid', 'str_val', 'date_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
>>> df2 = df.groupby('uid', as_index=False, group_keys=True)[['uid', 'str_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
>>> df3 = df.groupby('uid', as_index=False, group_keys=True)[['uid', 'date_val']].apply(lambda x: x.sort_values(by='date_val',ascending=True))
nt(df3)
>>> print(df1)
    uid              str_val   date_val
0 0   1  2017-01-01 00:00:00 2017-01-01
  2   1  2017-02-01 00:00:00 2017-02-01
1 1   2  2017-01-01 00:00:00 2017-01-01
  3   2  2017-02-01 00:00:00 2017-02-01
>>> print(df2)
    uid              str_val
0 0   1  2017-01-01 00:00:00
  2   1  2017-02-01 00:00:00
1 1   2  2017-01-01 00:00:00
  3   2  2017-02-01 00:00:00
>>> print(df3)
    uid   date_val
0 0   1 2017-01-01
  2   1 2017-02-01
1 1   2 2017-01-01
  3   2 2017-02-01

```

**Comment by NumberPiOso** [comment] 2022-06-11 19:26
Please check @rhshadrach

**Comment by rhshadrach** [comment] 2022-06-15 00:13
Thanks @NumberPiOso - agreed. This behavior can now be controlled by the user, is consistent, and will have the expected output in pandas 2.0. Closing.

**Closed by rhshadrach** 2022-06-15 00:13 UTC
Labels: Bug, Groupby, Regression, Apply
