### ISSUE TITLE
The setting xrot=0 in DataFrame.hist() doesn't work with by and subplots

### ISSUE THREAD

**Issue by PavloFesenko** [pandas-dev/pandas#30288] opened 2019-12-16 10:02 UTC
#### Code Sample, a copy-pastable example if possible

```python
df = pd.DataFrame({
    'length': [1.5, 0.5, 1.2, 0.9, 3],
    'animal': ['pig', 'rabbit', 'pig', 'pig', 'rabbit']
})
df.hist(column='length', by='animal', bins=5, xrot=0);
```
#### Problem description

The setting `xrot=0` doesn't work when I use the option `by` in DataFrame.hist() (see the screenshot below). The temporary workaround is to set it to a very small value like `xrot=0.001`.

![image](https://user-images.githubusercontent.com/16855796/70897591-38e0ec00-1ff3-11ea-9f35-c924727fad39.png)

#### Expected Output

Should look like this instead
![image](https://user-images.githubusercontent.com/16855796/70897647-5615ba80-1ff3-11ea-925d-f67377d5001e.png)

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1062.4.1.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.2
numpy            : 1.17.2
pytz             : 2019.3
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None

</details>

**Comment by TomAugspurger** [comment] 2019-12-20 20:55
https://github.com/pandas-dev/pandas/blob/0cd388fdc30f526f2f9729ee09c7d16513a1442d/pandas/plotting/_matplotlib/hist.py#L253

should probably be

```python
if xrot is None:
    xrot = rot
```

since 0 evaluates to False. A PR fixing that + adding a test would be welcome.

**Comment by souvik3333** [comment] 2019-12-20 21:38
Hi, Can I do it?

**Comment by souvik3333** [comment] 2019-12-23 13:34
I am taking this as no one seems to be working on this.

**Comment by souvik3333** [comment] 2019-12-23 13:35
take

**Comment by souvik3333** [comment] 2019-12-23 17:05
> should probably be
> 
> ```python
> if xrot is None:
>     xrot = rot
> ```
> 
> since 0 evaluates to False. A PR fixing that + adding a test would be welcome.

Looks like https://github.com/pandas-dev/pandas/blob/f505b74874b998cf929d82ea4d5c5fa16763819c/pandas/plotting/_matplotlib/core.py#L1208 is causing the error. Assigning ```self.rot=0``` solves the problem. I will add a PR on this. Also @TomAugspurger the solution you said fixes another issue. Should I add that in the same PR or create another issue on this?

**Comment by charlesdong1991** [comment] 2019-12-23 21:32
@souvik3333 i think the error is not caused by `self.rot=30`, this is only used for plotting ts data

and i do think if you follow @TomAugspurger 's suggestion, should be able to fix the error.

**Comment by souvik3333** [comment] 2019-12-24 15:42
> i do think if you follow @TomAugspurger 's suggestion, should be able to fix the bug.

I tried that but it's not working. Looks like https://github.com/pandas-dev/pandas/blob/0cd388fdc30f526f2f9729ee09c7d16513a1442d/pandas/plotting/_matplotlib/hist.py#L250 function is not even getting called during the execution of the example given above.

**Comment by souvik3333** [comment] 2019-12-24 17:23
I have my doubt but I think the following is the problem.
In ```dataframe.plot``` if we have either of ```subplots=True``` or ```sharex=True``` then it's treated as irregular TS object because of this condition:
 https://github.com/pandas-dev/pandas/blob/f505b74874b998cf929d82ea4d5c5fa16763819c/pandas/plotting/_matplotlib/core.py#L1199
So, when ```rot``` argument is not present in ```dataframe.plot``` then it is rotated 30deg. So should I update the condition @TomAugspurger @charlesdong1991 ?

**Comment by charlesdong1991** [comment] 2019-12-25 09:58
emm, okay, it seems indeed if both `subplots` and `sharex` are True, then will rot to 30. And this should be designed on purpose. 

Regarding your question: I didnt look at the codebase, but my assumption is when using `hist` and use `by`, then `subplots` and `sharex` are automatically set to True.

Just follow your investigation, and you could either submit a PR or open a new issue if you think there is another bug.

**Comment by souvik3333** [comment] 2019-12-25 10:59
Oh, actually this bug will be fixed as @TomAugspurger said. I misplaced it with another bug I found. My apologies. I will add a new issue on that bug and add a PR on this shortly.

**Closed** 2019-12-27 16:29 UTC
Labels: Visualization, good first issue
