### ISSUE TITLE
BUG: Unexpected behavior of sort_values

### ISSUE THREAD

**Issue by bhagyakjain** [pandas-dev/pandas#35511] opened 2020-08-01 23:53 UTC
df.sort_values(by=[col])  -
If column(=col) has some values occurring multiple times then it orders them randomly. Instead, it should inherit the order in the DataFrame for the rows having same value for column.

**Comment by MJafarMashhadi** [comment] 2020-08-02 00:18
It's not a bug. What you want is a stable-sort. Check out the docs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html?highlight=sort_values#pandas.DataFrame.sort_values

you need to use `kind` parameter to chose a stable sorting algorithm, i.e.:

```python
df.sort_values(by=[col], kind='mergesort')
```

**Comment by dsaxton** [comment] 2020-08-02 15:31
Closing as answered, thanks @MJafarMashhadi

**Closed by dsaxton** 2020-08-02 15:31 UTC
Labels: Usage Question
