### ISSUE TITLE
Problem in df.to_sql() with SQL Server in pandas 0.23

### ISSUE THREAD

**Issue by klonuo** [pandas-dev/pandas#21288] opened 2018-06-01 19:14 UTC
Hi,

I put data from dataframe to SQL Server:

```python
engine = create_engine('mssql+pyodbc://localhost/...')
# ...
df.to_sql(name='data', con=engine, if_exists='append', index=False)
```

With version 0.21.1 and previous version this is successfully executed, but with version 0.23 I get error:

```
sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError)

('42000', '[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]
    The incoming request has too many parameters. 
    The server supports a maximum of 2100 parameters. 
    Reduce the number of parameters and resend the request.
```

**Comment by chris-b1** [comment] 2018-06-01 20:32
Thanks for the report, duplicate of #21103

**Closed by chris-b1** 2018-06-01 20:32 UTC
