### ISSUE TITLE
Cannot load CSV file into SQL using to_sql where data contains literal "NA"

### ISSUE THREAD

**Issue by juler69** [pandas-dev/pandas#29614] opened 2019-11-14 06:51 UTC
Error
```
runfile('/Users/********/Documents/GitHub/********/Python/temp.py', wdir='/Users/********/Documents/GitHub/********/Python')
1 records processed.
2 records processed.
3 records processed.
Traceback (most recent call last):

  File "<ipython-input-14-3bcf066bc8aa>", line 1, in <module>
    runfile('/Users/********/Documents/GitHub/********/Python/temp.py', wdir='/Users/********/Documents/GitHub/********/Python')

  File "/Users/********/Library/Python/3.6/lib/python/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/********/Library/Python/3.6/lib/python/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/********/Documents/GitHub/********/Python/temp.py", line 37, in <module>
    chunk.to_sql('MyTable',sqldata,index=False,if_exists='append',chunksize=chunksize)

  File "/Users/********/Library/Python/3.6/lib/python/site-packages/pandas/core/generic.py", line 2712, in to_sql
    method=method,

  File "/Users/********/Library/Python/3.6/lib/python/site-packages/pandas/io/sql.py", line 518, in to_sql
    method=method,

  File "/Users/********/Library/Python/3.6/lib/python/site-packages/pandas/io/sql.py", line 1750, in to_sql
    table.insert(chunksize, method)

  File "/Users/********/Library/Python/3.6/lib/python/site-packages/pandas/io/sql.py", line 756, in insert
    exec_insert(conn, keys, chunk_iter)

  File "/Users/********/Library/Python/3.6/lib/python/site-packages/pandas/io/sql.py", line 1468, in _execute_insert
    conn.executemany(self.insert_statement(), data_list)

IntegrityError: NOT NULL constraint failed: MyTable.FileName
```

Code Snippet
```python
"""
SQL load fail example

CSV in Files.csv:
--8<--
"FileName","CreatedBy"
"File1","Jonathan"
"File2","Jonathan"
"File3","Derek"
"NA","Derek"
--8<--

"""
import pandas as pd
import sqlite3 as sql
sqldata = sql.connect('/Users/********/Downloads/myDB.db',isolation_level=None)
sqldata.execute('pragma journal_mode=wal;')
sqldata.execute('pragma cache_size=-16384;')
sqldata.execute('pragma synchronous=0;')
sqldata.execute('pragma temp_store=3;')
csr = sqldata.cursor()
create_table_stmt = f'''
CREATE TABLE MyTable (
	FileName TEXT COLLATE NOCASE NOT NULL,
	CreatedBy TEXT COLLATE NOCASE DEFAULT NULL
);
'''
columns={}
columns['FileName']=''
columns['CreatedBy']=''
csr.execute(f'DROP TABLE IF EXISTS MyTable;')
csr.execute(create_table_stmt)
with open('/Users/********/Downloads/Files.csv','r',encoding='utf-8') as evdfile:
    chunksize = 1
    chunktotal = 0
    for chunk in pd.read_csv(evdfile,delimiter=',',names=columns.keys(),skiprows=1,skip_blank_lines=True,engine='python',index_col=False,encoding='utf-8',chunksize=chunksize):
        chunk.to_sql('MyTable',sqldata,index=False,if_exists='append',chunksize=chunksize)
        chunktotal += len(chunk)
        print(f'{chunktotal} records processed.')
    sqldata.commit()
sqldata.close()
```
I can import this csv file to sqlite using the .import command and .mode csv without either error occurring and the data is intact so it appears that sqlite is not the issue per se.

```
sqlite> select * from Files2
   ...> ;
File1,Jonathan
File2,Jonathan
File3,Derek
NA,Derek
sqlite> 
```

#### Expected Output

As above for the sqlite import.

If I run the same code but don't drop/create the table beforehand it loads without error.

```
n [17]: runfile('/Users/********/Documents/GitHub/********/Python/temp.py', wdir='/Users/********/Documents/GitHub/********/Python')
1 records processed.
2 records processed.
3 records processed.
4 records processed.
```
BUT! The NA is missing from the filename in table.
```
sqlite> select * from myTable;
File1,Jonathan
File2,Jonathan
File3,Derek
,Derek
sqlite> 
```
#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.4.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 2.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : 3.0.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
xlsxwriter       : None
</details>

**Comment by asishm** [comment] 2019-11-17 01:21
The issue is unrelated to SQL inserts, but rather at reading the CSV.

The doc for `read_csv` states:


> na_filter : bool, default True
> Detect missing value markers (empty strings and the value of na_values). In data without any NAs, passing na_filter=False can improve the performance of reading a large file.


and if you look at the `na_values` it includes the string `"NA"` which is why it is marked as N/A when reading it in


> na_values : scalar, str, list-like, or dict, optional
> Additional strings to recognize as NA/NaN. If dict passed, specific per-column NA values. By default the following values are interpreted as NaN: ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.
> 

You can follow the recommendation in the documentation to

`In data without any NAs, passing na_filter=False can improve the performance of reading a large file.`

**Comment by mroeschke** [comment] 2019-11-17 19:49
Thanks for the explanation @asishm! As noted, You can modify `na_values` to exclude `NA` or pass  `na_filter=False`

**Closed by mroeschke** 2019-11-17 19:49 UTC
