### ISSUE TITLE
ENH: Extract all the datetime components

### ISSUE THREAD

**Issue by eaedk** [pandas-dev/pandas#52231] opened 2023-03-27 00:10 UTC
### Feature Type

- [X] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas

### Problem Description

I wish I could use pandas to extract all the components of columns/series of type datetime like for timedelta columns.

### Feature Description

The feature exists for timedelta ( [read the doc](http://pandas.pydata.org/docs/reference/api/pandas.Series.dt.components.html?highlight=dt%20components#pandas.Series.dt.components) ) . It might be interesting to add parameters to exclude some output feature or to set a suffix . 

### Alternative Solutions

The feature exists for timedelta ( [read the doc](http://pandas.pydata.org/docs/reference/api/pandas.Series.dt.components.html?highlight=dt%20components#pandas.Series.dt.components) )

### Additional Context

The feature exists for timedelta ( [read the doc](http://pandas.pydata.org/docs/reference/api/pandas.Series.dt.components.html?highlight=dt%20components#pandas.Series.dt.components) ) but not for datetime series while it might be very helpful to extract date features from datetime series easily and feed Machine Learning with it.

```python3
_ = train.loc[:, 'Policy End Date']
_.dt.components
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-32-171eb7443229>](https://localhost:8080/#) in <module>
      1 _ = train.loc[:, 'Policy End Date']
----> 2 _.dt.components

AttributeError: 'DatetimeProperties' object has no attribute 'components'
```

**Comment by topper-123** [comment] 2023-03-28 13:52
This is a duplicate of #44933, so closing. DFiscussion can continue in #44933.

**Closed by topper-123** 2023-03-28 13:52 UTC
Labels: Enhancement, Timeseries
