### ISSUE TITLE
Feature request: DataFrame.pop with argument axis

### ISSUE THREAD

**Issue by eXcuvator** [pandas-dev/pandas#22778] opened 2018-09-20 09:16 UTC
#### Comment

Pop works as in python lists: It returns an element by index and removes it from the original object.
Unlike lists however, `Dataframe` objects are two-dimensional. It should be possible to `pop()` by either axis, with the current behavior set up as default.

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
df = pd.Dataframe(np.arange(4).reshape((2,2)), columns=['a', 'b'])
df.pop('a', axis=0)  # works as pop() does right now, axis=0 is default
Out[14]: 
0    0
1    2
Name: a, dtype: int64

df = pd.Dataframe(np.arange(4).reshape((2,2)), columns=['a', 'b'])
df.pop(0, axis=0)
Out[19]: 
a    0
b    1
Name: 0, dtype: int64
# and of course, `0` is not in dataframe any longer:
print(df)
Out[26]: 
   a  b
1  2  3


```

**Comment by TomAugspurger** [comment] 2018-09-20 10:58
Duplicate of https://github.com/pandas-dev/pandas/issues/19501, if you want to chime in over there.

**Closed by TomAugspurger** 2018-09-20 10:58 UTC
