### ISSUE TITLE
Support for partial string matching in query

### ISSUE THREAD

**Issue by johanekholm** [pandas-dev/pandas#8749] opened 2014-11-07 11:46 UTC
Would be nice to have the query method support partial string matching, so you could do the equivalence of df[df['A'].str.contains("abc")] using query: df.query("A contains 'abc'").

**Comment by rea725** [comment] 2017-11-28 21:28
Maybe I'm missing something, but seems this is still an open issue.  I ended up here via a lot of googling. I'm having the same sort of challenge.  I've tried in both pandas 0.18.1 and 0.20.1.

I would love to be able to do df.query("A contains 'abc'") as @johanekholm suggested.  It's understood that this would be a slower operation than a simpler condition such as == or != but I don't see any downside to having the option.

**Comment by jreback** [comment] 2017-11-28 23:06
@rea725 this is an open issue as the tag indicates
if you want this implemented the quickest route would be a pull request to do so

**Comment by rea725** [comment] 2017-11-29 05:49
It looks like I found a solution, by reading the pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.query.html?highlight=query#pandas.DataFrame.query).  I get the behavior I seek by passing `engine='python'.`  The explanation totally makes sense, including the recommendation to avoid doing so unless you really need to, since this would be slow compared to the default option.  I'm not sure any additional action is merited.

**Comment by vijaysaimutyala** [comment] 2018-04-05 10:10
Not sure whether I need to open a new issue. If needed, will do.

So I've been using the Series string methods to do some comparisons with a input string. I'm using the 

`series.str.contains(word,case=False)`

and create a new dataframe with the results. What I've observed is that if there is a plus sign (+) in the word I supply for search, the method return 0 zero results
Below is a snippet
```
import os
import pandas as pd

datadf = pd.DataFrame()
resultdf = pd.DataFrame()

datadf = pd.DataFrame({'description':["i am good boy","i am a bad boy","i am an ugly boy","i am a + boy"]})
print(datadf)
word = "i am a + boy"
resultdf=resultdf.append(datadf[datadf['description'].str.contains(word,case=False)])
print(len(resultdf.index))

```
The issue is not only with +, but also with *

![image](https://user-images.githubusercontent.com/7084628/38360242-4d28835c-38e7-11e8-9e9c-898e075421ef.png)

Also does this have to do anything with the below note on official docs ?

![image](https://user-images.githubusercontent.com/7084628/38360378-9aaab05a-38e7-11e8-8926-bc3574c29475.png)

**Comment by wesm** [comment] 2018-07-06 21:34
Closing. Contributions welcome

**Closed by wesm** 2018-07-06 21:34 UTC
Labels: API Design, Community, Strings, Won't Fix
