### ISSUE TITLE
DOC: wiki testing page still refers to nose

### ISSUE THREAD

**Issue by mattip** [pandas-dev/pandas#20740] opened 2018-04-19 06:42 UTC
On the wiki https://github.com/pandas-dev/pandas/wiki/Testing seems to need an update for the `pytest` testing framework.

**Comment by jorisvandenbossche** [comment] 2018-04-19 10:11
Yes, that page should be updated. But, I think in general we should check if there is still content in there that is not in http://pandas-docs.github.io/pandas-docs-travis/contributing.html#test-driven-development-code-writing, and move that content over there.

**Comment by jreback** [comment] 2018-04-19 10:46
dupe of #20501

**Closed by jreback** 2018-04-19 10:46 UTC
