### ISSUE TITLE
column name dedupe when already deduped returns "column_name.1.1"

### ISSUE THREAD

**Issue by boldloop** [pandas-dev/pandas#27021] opened 2019-06-24 16:41 UTC
This isn't necessarily a bug, just something I think could be handled slightly cleaner. The code:
```python
from io import StringIO
csv = StringIO('a,a.1,a')
pd.read_csv(csv)
```
returns
```
a	a.1	a.1.1
```
where I think it could return
```
a	a.1	a.2
```
I encountered this when working with data that included the columns ["Column name", "COLUMN NAME", "COLUMN NAME"]. I work in multiple steps (i.e., separating each task into a separate script that takes the output from the previous task—works for auditability), so after the first step the columns became ["Column name", "COLUMN NAME", "COLUMN NAME.1"]. Down the pipeline, I renamed all columns to use all caps for consistency, but I ended up with ["COLUMN NAME.1.1", "COLUMN NAME", "COLUMN NAME.1"]. Not a huge problem, but a little bit annoying nonetheless.

I'm going to dig in and see if I can implement this later this week in a pull request—just filing it now so that I don't forget.

**Comment by phofl** [comment] 2021-11-27 12:46
duplicate of #14704

**Closed by phofl** 2021-11-27 12:46 UTC
Labels: Bug, IO CSV, Needs Discussion
