### ISSUE TITLE
Can't install pandas 0.24dev (with setup script) on mac

### ISSUE THREAD

**Issue by janvanrijn** [pandas-dev/pandas#24374] opened 2018-12-20 15:44 UTC
#### Code Sample, a copy-pastable example if possible

```
python setup.py install
```
#### Problem description
I checked the recent issues and it seems that this issue is not here before. I understand that this is kind of a environment dependent issue, and probably hard to debug, but I was wondering if I was the only one that has this problem, and if there is any way to conveniently debug this. (happy to provide a fix if I am able to conveniently debug this)

#### Expected Output
pandas 0.24dev installed in venv

#### Output of ``pd.show_versions()``
N/A (pandas is not installed)

#### Actual Output
```
(openml-defaults) l-145-118-224-211:pandas janvanrijn$ python setup.py  install --verbose
running install
running bdist_egg
running egg_info
writing pandas.egg-info/PKG-INFO
writing dependency_links to pandas.egg-info/dependency_links.txt
writing requirements to pandas.egg-info/requires.txt
writing top-level names to pandas.egg-info/top_level.txt
reading manifest file 'pandas.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'doc/build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '#*' found anywhere in distribution
writing manifest file 'pandas.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
UPDATING build/lib.macosx-10.7-x86_64-3.6/pandas/_version.py
set build/lib.macosx-10.7-x86_64-3.6/pandas/_version.py to '0.24.0.dev0+1332.g5d134ec1a'
running build_ext
building 'pandas._libs.window' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/janvanrijn/anaconda3/envs/openml-defaults/include -arch x86_64 -I/Users/janvanrijn/anaconda3/envs/openml-defaults/include -arch x86_64 -Ipandas/_libs -I./pandas/_libs -Ipandas/_libs/src/klib -Ipandas/_libs/src -I/Users/janvanrijn/anaconda3/envs/openml-defaults/lib/python3.6/site-packages/numpy/core/include -I/Users/janvanrijn/anaconda3/envs/openml-defaults/include/python3.6m -c pandas/_libs/window.cpp -o build/temp.macosx-10.7-x86_64-3.6/pandas/_libs/window.o -Wno-unused-function
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++
      standard library instead [-Wstdlibcxx-not-found]
pandas/_libs/window.cpp:658:10: fatal error: 'ios' file not found
#include "ios"
         ^~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
(openml-defaults) l-145-118-224-211:pandas janvanrijn$ 
```

Note: the problem is not my local installation, as ios is available and when importing it independent from this library in other projects, it does not crash. 

Also, the output of gcc --version:
```
(openml-defaults) l-145-118-224-211:pandas janvanrijn$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by TomAugspurger** [comment] 2018-12-20 16:06
See https://github.com/pandas-dev/pandas/pull/24274

Try setting `MACOSX_DEPLOYMENT_TARGET=10.9` before building.

**Comment by robbuckley** [comment] 2018-12-20 21:14
yep, looks like a duplicate of issue #23424

**Closed** 2018-12-20 21:32 UTC
