### ISSUE TITLE
pandas.rolling.apply skips calling function if window contains any NaN

### ISSUE THREAD

**Issue by AHG123** [pandas-dev/pandas#26181] opened 2019-04-21 20:53 UTC
This issue has been raised several times, but I do not think has been adequately addressed. 

The solution given is always min_periods, but that only includes the obvious issue where the NaN is at the beginning of the series. If there is any NaN then .apply will not call the function.

There should be a skipna=True option that works. Despite this question being asked in a dozen places, it has not been fixed. 

I see that @jreback has closed this issue multiple times with a reference to min_periods. Again... this is NOT an adequate answer. (See the followup here https://github.com/pandas-dev/pandas/issues/19218 that was ignored once the issue was marked closed.)

There should simply be a skipna=True flag in the rolling window function. As-is, it will not call the function in .apply() if there are ANY NaNs at any point in the window.

**Comment by jreback** [comment] 2019-04-21 21:21
@AHG123 if you have a solution the please make a pull request
further a reproducible example is a must

**Comment by AHG123** [comment] 2019-04-21 23:16
I don't have a solution, but here's the issue in code:

``import pandas as pd
import numpy as np

def movsum(data):
    print('called')
    return data.sum()

df1 = pd.DataFrame([1,2,3,4,5])
df1.rolling(2).apply(movsum, raw=True)

**Comment by AHG123** [comment] 2019-04-21 23:23
Apologies, but I'm not sure exactly how to format code here. Here's a snippet you can run that will reproduce the error:

import pandas as pd
import numpy as np

def movsum(data):
    print('called')
    return data.sum()

print("With no NaNs:\n")
df1 = pd.DataFrame([1,2,3,4,5])
df2 = df1.rolling(2).apply(movsum, raw=True)
print("\nWith a NaN. Note that the function is NOT called if there is any NaN:\n")
df1.loc[2] = np.nan
df3 = df1.rolling(2).apply(movsum, raw=True)

#---------------------

As far as I can see, .rolling is not calling apply() if there are any NaNs in the window. This might sometimes be desired behavior, but I would think the default behavior should be to pass the NaNs to the function being applied. 

At the very least, this MUST be an option... rolling windows should have a skipna=True, etc. flag.

Am I missing something?

Again, note that many times this has been answered by setting the minimum window length but that is not the issue here. min_periods is not relevant to this particular issue.

**Comment by jreback** [comment] 2019-04-21 23:30
@AHG123 you are welcome to do a pull request here

but it’s not about adding an option; rather min_periods needs to be respected

**Comment by AHG123** [comment] 2019-04-21 23:37
I'm sorry but I don't understand how min_periods is relevant here. Imagine I have a df with 5000 rows and an NaN in 4999. That's very different than the function returning NaNs because the minimum window wasn't passed at the beginning of the df.

Is there something I'm not understanding and why we keep going back to min_periods? 

I don't have the skills to modify the code myself. Where would this be submitted as a bug report?

**Comment by AHG123** [comment] 2019-04-21 23:39
Make the window length=1 and you will still have the same issue. rolling does not call apply if there is a NaN in the window. That is unrelated to min_periods unless I am misunderstanding something.

**Comment by jreback** [comment] 2019-04-21 23:56
@AHG123 only a community pull request here would help
pandas is open source and completely volunteer

**Comment by AHG123** [comment] 2019-04-22 03:34
I don't know how to submit the pull request... and fixing the code (I'm assuming this is written in C?) is beyond my capabilities. This issue has been raised numerous times and has been dismissed with the (faulty) min_periods reference. (Which you did again above. Unless I'm missing something min_periods is completely irrelevant with a window length=1 and/or with NaNs occurring in the middle of a df. Right?)

What is the procedure for submitting a pull request so someone can work on it? Can we at least agree this is not desired behavior for df.rolling()?

**Comment by WillAyd** [comment] 2019-04-22 15:26
I am not clear on what error is here. The behavior here is pretty well documented and as mentioned specifying `min_periods` gets the result it sounds like you are after:

```python
df3 = df1.rolling(1, min_periods=0).apply(movsum, raw=True)
```

**Comment by venaturum** [comment] 2021-01-13 03:02
@AHG123 

Came across this open issue though triage email.

To me it looks like the solution provided by @WillAyd is exactly what you need.

If you still wanted the *nan*s at the beginning of the array then your movsum method could check the length of the parameter "data" and if it is less than window length, return np.nan

Can you confirm this solves your problem?

**Comment by mroeschke** [comment] 2021-01-13 19:34
So I think this issue would essentially be an enhancement request to run the passed `func` _even if_ the `min_periods` condition is satisfied.

The current implementation is probably there is for performance reasons i.e. why call the function when we will override with `nan`.

Can be open for discussion but I'd be -1 to allow this. The pass `func` should only impact the data and not have any "side effects"

**Comment by venaturum** [comment] 2021-01-13 22:32
> So I think this issue would essentially be an enhancement request to run the passed func even if the min_periods condition is satisfied.

Isn't it currently the case that the passed func is run if, and only if, min_periods condition is satisfied?

**Comment by mroeschke** [comment] 2021-01-14 04:45
Sorry my phrasing was a bit confusing but you're correct (and is what I mean originally):

https://github.com/pandas-dev/pandas/blob/25110a92b291de6688c3accad4c34d84837445e8/pandas/_libs/window/aggregations.pyx#L1155

**Comment by venaturum** [comment] 2021-01-14 07:21
Yeh I'm still confused 😂

If the min_periods condition is satisfied then the passed func is executed.

If min_periods == 0, as per WillAyd's example, then the passed func is always executed.

AHG123's claim that

> ... that only includes the obvious issue where the NaN is at the beginning of the series. If there is any NaN then .apply will not call the function.

is simply not true.

**Comment by mroeschke** [comment] 2021-01-14 18:15
Ah good point. Yeah min_periods == 0 guarantees that the passed func is always executed.

So yes I believe this behavior is already possible so I'll close this issue.

**Closed by mroeschke** 2021-01-14 18:15 UTC
Labels: Enhancement, Needs Discussion, Window
