### ISSUE TITLE
BUG: nan values in dataframe index when reading from multiple parquet files

### ISSUE THREAD

**Issue by galipremsagar** [pandas-dev/pandas#38058] opened 2020-11-25 10:27 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import pandas as pd
>>> df1 = pd.DataFrame({'a':[1, 2, 3]}, index=['a','b','c'])
>>> df1.to_parquet('abc/one.parquet')
>>> df2 = pd.DataFrame({'a':[4, 5, 6]})
>>> df2.to_parquet('abc/two.parquet')
>>> df3 = pd.DataFrame({'a':[7, 8, 9]})
>>> df3.to_parquet('abc/three.parquet')
>>> pd.read_parquet('abc/')
     a
a    1
b    2
c    3
NaN  7
NaN  8
NaN  9
NaN  4
NaN  5
NaN  6
```

#### Problem description

When we are reading multiple parquet files using `pd.read_parquet` and one of them has a different index than other two then there are `NaN` values in the rest of Index positions, is this a desired behavior?

#### Expected Output

Ideally I would expect all Index objects to be appended, i.e., we'd have some duplicate Index values in this case. 

```python
>>> import pandas as pd
>>> df1 = pd.DataFrame({'a':[1, 2, 3]}, index=['a','b','c'])
>>> df1.to_parquet('abc/one.parquet')
>>> df2 = pd.DataFrame({'a':[4, 5, 6]})
>>> df2.to_parquet('abc/two.parquet')
>>> df3 = pd.DataFrame({'a':[7, 8, 9]})
>>> df3.to_parquet('abc/three.parquet')
>>> pd.read_parquet('abc/')
     a
a    1
b    2
c    3
0  7
1  8
2  9
0  4
1  5
2  6
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.7.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.1.0
Version          : Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.4
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 50.3.0
Cython           : None
pytest           : None
hypothesis       : 5.29.0
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by jorisvandenbossche** [comment] 2020-11-25 14:15
@galipremsagar thanks for the report. That's certainly not the expected behaviour. 

This is a bug in the library that is used under the hood, `pyarrow`, in the conversion to pandas. The problem is that you have 2 parquet files with a different type for the index, and apparently pyarrow is not correctly handling that case. 

Since this issue is in pyarrow, I opened an issue referencing this one on their tracker: https://issues.apache.org/jira/browse/ARROW-10726, and closing this one.

**Closed by jorisvandenbossche** 2020-11-25 14:15 UTC
Labels: Bug, IO Parquet

**Comment by jorisvandenbossche** [comment] 2022-01-18 10:38
After some discussion in https://issues.apache.org/jira/browse/ARROW-10726, we actually decided this is "expected" behaviour (or at least, there is no easy way to detect this inconsistency between the different files and correct for it. The actual underlying parquet reader is not aware of the pandas index concept, so at that point it makes sense to fill in the string column with nulls).
