### ISSUE TITLE
BUG: read_excel not accepting encoding on 1.1.0

### ISSUE THREAD

**Issue by staticdev** [pandas-dev/pandas#35753] opened 2020-08-16 17:22 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
def date_parse(value: str) -> datetime.datetime:
    return datetime.datetime.strptime(value.strip(), "%d/%m/%y")

df = pd.read_excel(
    filepath,
    encoding="iso-8859-1",
    usecols="B",
    date_parser=date_parse,
    skiprows=4,
)
```

#### Problem description

TypeError: read_excel() got an unexpected keyword argument 'encoding'.

#### Expected Output

No error, as in previous versions.

#### Output of ``pd.show_versions()``

```INSTALLED VERSIONS
------------------
commit           : d9fff2792bf16178d4e450fe7384244e50635733
python           : 3.8.2.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-42-generic
Version          : #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : pt_BR.UTF-8

pandas           : 1.1.0
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1
setuptools       : 41.2.0
Cython           : None
pytest           : 6.0.1
hypothesis       : None
sphinx           : 3.2.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : None
numba            : None```

</details>

**Comment by simonjayhawkins** [comment] 2020-08-16 17:59
Thanks @staticdev for the report. This is documented in the release notes.

from https://pandas.pydata.org/pandas-docs/version/1.0.5/whatsnew/v1.0.0.html

> read_excel() no longer takes **kwds arguments. This means that passing in the keyword argument chunksize now raises a TypeError (previously raised a NotImplementedError), while passing in the keyword argument encoding now raises a TypeError (GH34464)

were the constructed DataFrames different with and without the encoding parameter in 1.0.5?

**Comment by twoertwein** [comment] 2020-08-16 18:05
There have been similar requests about an encoding parameter: #25523 and #23444.

I haven't used `read_excel` but the documentation says that you can also provide a file-object instead of a path. Something like
```py
with open(path_to_excel_file, mode="r", encoding="iso-8859-1") as file:
    df = pd.read_excel(file, **other_kwargs)
```
might be a temporary work around? I haven't tested whether that works.

**Comment by staticdev** [comment] 2020-08-16 18:20
> Thanks @staticdev for the report. This is documented in the release notes.
> 
> from https://pandas.pydata.org/docs/whatsnew/v1.1.0.html
> 
> > read_excel() no longer takes **kwds arguments. This means that passing in the keyword argument chunksize now raises a TypeError (previously raised a NotImplementedError), while passing in the keyword argument encoding now raises a TypeError (GH34464)
> 
> were the constructed DataFrames different with and without the encoding parameter in 1.0.5?

Yes, and I was using 1.0.5 before 1.1.0 working fine.

> 
> **updated**: incorrect link
> 
> xref #34464

Another odd thing to add about this change is that I have another point in my code that hasn't broken:

```
        df = pd.read_excel(
            filepath,
            encoding="iso-8859-1",
            usecols="B",
            date_parser=date_parse,
            skiprows=4,
        )
```

**Comment by staticdev** [comment] 2020-08-16 18:51
> There have been similar requests about an encoding parameter: #25523 and #23444.
> 
> I haven't used `read_excel` but the documentation says that you can also provide a file-object instead of a path. Something like
> 
> ```python
> with open(path_to_excel_file, mode="r", encoding="iso-8859-1") as file:
>     df = pd.read_excel(file, **other_kwargs)
> ```
> 
> might be a temporary work around? I haven't tested whether that works.

I also tried that, but created many side-effects to my code. I have a test that checks if it is an empty file, it would raise `pd.errors.EmptyDataError`, now it is giving me `expected str, bytes or os.PathLike object, not NoneType`.

**Comment by twoertwein** [comment] 2020-08-16 19:58
> > There have been similar requests about an encoding parameter: #25523 and #23444.
> > I haven't used `read_excel` but the documentation says that you can also provide a file-object instead of a path. Something like
> > ```python
> > with open(path_to_excel_file, mode="r", encoding="iso-8859-1") as file:
> >     df = pd.read_excel(file, **other_kwargs)
> > ```
> > 
> > 
> > might be a temporary work around? I haven't tested whether that works.
> 
> I also tried that, but created many side-effects to my code. I have a test with a file-fake that checks if it is an empty file, it should raise `pd.errors.EmptyDataError`, now it is giving me `TypeError('expected str, bytes or os.PathLike object, not NoneType')`.

I just noticed that my suggestion doesn't make much sense. The excel file needs to be opened in binary mode but binary files don't take an encoding argument.

**Comment by twoertwein** [comment] 2020-08-17 03:37
Does someone know how to create an excel file with a specific encoding using either LibreOffice or gnumeric? There are no excel files needing a non-default encoding in pandas/tests/io/data/excel/. Need to have a test for the encoding argument.

**Comment by staticdev** [comment] 2020-08-17 10:12
@twoertwein what I can do is send you one with this "iso-8859-1" encoding. Would it suffice?

**Comment by twoertwein** [comment] 2020-08-17 13:00
@staticdev thank you, that would probably be the best. Ideally, just one sheet with only one cell filled with a bunch of special characters :)

**Comment by staticdev** [comment] 2020-08-17 14:19
Please rename it to xls, since github complains about extension.

[InfoCEI.txt](https://github.com/pandas-dev/pandas/files/5084802/InfoCEI.txt)

**Comment by twoertwein** [comment] 2020-08-17 16:25
thank you! I seem to be able to open this Excel file in pandas without specifying an encoding. Can you confirm that you can open it as well?

Let me know if you have a file that needs an encoding argument! Please try to create a minimal Excel file, ideally only one cell having content.

**Comment by staticdev** [comment] 2020-08-17 19:02
@twoertwein you are correct. I tried removing `encoding` arg, and I SEEMS to be working fine. I am not very confident though. This code was running for the past versions of pandas even before 1.0.0. But I didn't see on the 1.1.0 changelog that it automatically detects the encoding or something alike. I really don't know if just removing the encoding really solves the problem.

**Comment by staticdev** [comment] 2020-08-17 19:03
Does it solve for https://github.com/pandas-dev/pandas/issues/23444?

**Comment by twoertwein** [comment] 2020-08-17 21:18
> Does it solve for #23444?

I thought these issues were similar but I think they aren't. imho #23444 tries to allow `read_excel` to work with text file-objects.

**Comment by staticdev** [comment] 2020-08-17 22:43
I saw it in your PR.. so I think the most import question here is why the behavior changed. I didn't find a clear explanation from the https://pandas.pydata.org/docs/whatsnew/v1.1.0.html#deprecations. The only related thing is this one: Passing any arguments but the first two to read_excel() as positional arguments is deprecated. All other arguments should be given as keyword arguments (GH27573). When I click it, it is not even related to read_excel. So I conclude that something IS wrong (maybe the documentation). Maybe @alexitkes could help us figure that out.

**Comment by twoertwein** [comment] 2020-08-17 23:13
Do you mind trying the old pandas version to see whether you actually needed the encoding argument?

imho, `encoding` probably never worked: it was passed to `TextFileReader` but I think it isn't used there.

**Comment by staticdev** [comment] 2020-08-17 23:24
@twoertwein I can try, but I really doubt that one. I would never add this argument if it wasn't necessary and the code for [this component](https://github.com/staticdev/irpf-cei) was 100% written by me.

**Comment by WillAyd** [comment] 2020-08-18 14:43
Removing regression tag. Providing `encoding` here has always been a no-op you would just now getting an explicit error about that

**Comment by simonjayhawkins** [comment] 2020-08-20 13:57
moving off 1.1.1, associated PR closed

**Comment by nahuelalmeira** [comment] 2020-09-28 18:13
@staticdev could you find any workaround for the problem? I am currently facing the same issue.

**Comment by twoertwein** [comment] 2020-09-28 18:16
@nahuelalmeira can you successfully import the excel file without the encoding parameter?

**Comment by jmauler** [comment] 2020-10-06 23:15
Faced the same issue here. It was working with this parameter on version 1.0.5. It's not an issue for me, because I was just reinforcing utf8 in my code to make sure codes behaves the same always, and at least here it seems like the default. 
Anyways, I took the file from @staticdev , and ran in my version without the encoding parameter, and it was successfully read without any issues. So, it seems it's automatically decoded.
![image](https://user-images.githubusercontent.com/68169015/95269632-34025880-0810-11eb-8b35-ed92fb30d4cc.png)

**Comment by staticdev** [comment] 2020-10-06 23:32
So we assume encoded is not needed anymore? I am ok with that is other people are not facing issues with that.

**Comment by nahuelalmeira** [comment] 2020-10-07 10:57
@twoertwein In my case, the files ended up being successfully read.

**Comment by simonjayhawkins** [comment] 2020-10-29 15:41
moved off 1.1.4 milestone (scheduled for release tomorrow)

**Comment by WillAyd** [comment] 2020-10-29 15:48
At least since excel 97 text in excel documents has a well defined format.

https://xlrd.readthedocs.io/en/latest/unicode.html?highlight=encoding_override#handling-of-unicode

I don't think it is worth supporting Excel 95 and earlier file formats at this point

**Comment by WillAyd** [comment] 2020-10-29 15:49
Closing as a non-issue. Providing encoding as a keyword argument is unnecessary and only "worked" before because we silently accepted kwargs and discard it; it never had any functionality and should be removed from code

**Closed by WillAyd** 2020-10-29 15:49 UTC
Labels: Closing Candidate, IO Excel, Needs Discussion

**Comment by matthewahillman** [comment] 2020-11-02 11:32
I find I need to use the encoding for keeping the UTF-8 encoding on my files when other people on different platforms open them. I was having issues with the formatting of special characters on Windows machines but not on Macs due to the file changing encodings. Forcing the UTF-8 encodings on opening and saving documents meant my files work on all platforms. Without this encoding working I could run into problems again. Is there another workaround if this is being removed from the pandas code??

**Comment by boardtc** [comment] 2021-01-20 19:49
I have language accents in my excel, when reading from csv I can pass encoding='utf-8'. Why would Pandas remove this ability from reading excel files? This is a blocker for me now, all of my accented words are getting garbles when read in from excel. The after my wrangling I am writing to csv and get UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3c0' in position 69: character maps to <undefined>
What is the workaround that allowed you to remove this functinality?

**Comment by twoertwein** [comment] 2021-01-20 20:01
> **Why would Pandas remove this ability from reading excel files?**

As far as I remember: It was removed because it was never actually used internally. You were able to specify it but it didn't make a difference. Do you have an excel file for which you needed the encoding argument on 1.0.x (and you verfiy that it didn't work without the argument)?

Please create a new issue for the CSV problem you are encountering. [If you have this issue with 1.2.0, please upgrade first to 1.2.1 as your problem might have been fixed  - sound similar to #38989]

**Comment by boardtc** [comment] 2021-01-20 20:16
Thanks for the reply!
I am using the latest Anaconda which has Pandas 1.1.3
I might not have explained clearly, after the read_excel the words with accents are garbled, this is why there is an error outputting to CSV, so it's not a CSV issue.
(conda install pandas=1.2.0 seems to have issue with repodate source but it's till trying)

**Comment by asishm** [comment] 2021-02-15 05:10
If you believe there is a bug with the python stdlib modules - the bug tracker is at https://bugs.python.org/

**Comment by matthewahillman** [comment] 2021-03-04 11:55
> I have language accents in my excel, when reading from csv I can pass encoding='utf-8'. **Why would Pandas remove this ability from reading excel files?** This is a blocker for me now, all of my accented words are getting garbled when read in from excel. The after my wrangling I am writing to csv and get UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f3c0' in position 69: character maps to
> What is the workaround that allowed you to remove this functionality?
> 
> Note my excel is a .xlsx export from Google sheets.
> 
> I am disappointed nobody responded to Matthew over 2 months ago, what hope is there for me? Since this is closed should I open a new issue? I will wait a couple of hours.

Still no work around for this issue. Means if I switch from Mac to a PC my file is unable to run due to the 'charmap' code issue even with 1.2.3

How has this not been fixed yet??

**Comment by rdancy01** [comment] 2021-04-21 20:35
Hello all,

I'm new to Pandas and I can't solve these errors I'm getting. Any assistance would be appreciated.

Traceback (most recent call last):
  File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 515, in <module>
    main()
  File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 471, in main
    [all_data,suite_list] = openSpreadsheet()
  File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 91, in openSpreadsheet
    all_data = pd.read_excel(workbook_name, 1 ,usecols=['Name','Test Stand','Status',
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\util\_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'

C:\Users\HA_Report_Generation\Report Generator Legacy>python3 report_generator_1_5_3.py
Opening spreadsheet from .\Regression\CVB Logix Firmware-Test Run-20210411.xls...

Traceback (most recent call last):
  File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 515, in <module>
    main()
  File "C:\Users\HA_Report_Generation\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 471, in main
    [all_data,suite_list] = openSpreadsheet()
  File "C:\Users\HA_Report_Generation\Report Generator Legacy\report_generator_1_5_3.py", line 91, in openSpreadsheet
    all_data = pd.read_excel(workbook_name, 1 ,usecols=['Name','Test Stand','Status',
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\util\_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
TypeError: read_excel() got an unexpected keyword argument 'index'

**Comment by twoertwein** [comment] 2021-04-21 21:35
> TypeError: read_excel() got an unexpected keyword argument 'index'

I don't think your error is related to encoding. Please have a look at the possible arguments for `read_excel` (they are not the same as for `read_csv`): https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html
If that doesn't solve your error, feel free to create a new issue!

**Comment by rdancy01** [comment] 2021-04-23 14:23
Turns out instead of 'index=False' I needed to change it to 'index_cols'=False. That seemed to work. Many thanks!

**Comment by IloBe** [comment] 2021-07-08 17:55
Hi all,
I would like to ask again, how to solve the encoding topic with Pandas read_excel() of version>1.1? My xlxs Excel files including German text strings worked fine with encoding="ISO-8859-2", but now all specific characters are mapped to signs which are not acceptable for common German users of the final reports. First converting to .csv is no workaround for my files. and sorry, I cannot deliver such files. But perhaps you can try files with text strings including ä, ü, ö or ß. 
I tried the open file code snippet from the beginning, but had other issues with it.
If there is another solution I would appreciate if someone could share it. Thanks in advance.

**Comment by bsnresearcher** [comment] 2021-07-11 04:45
The encoding argument is very important. I want to come back "encoding=".

Excel application windows edition's default encoding ShiftJIS(cp932). The export file(.xlsx) causes character corruption in dealing with pandas in MacOS because the os default encoding UTF8.

**Comment by kapilhp** [comment] 2022-05-03 13:07
The workaround suggested [here](https://stackoverflow.com/a/62810839/9921041) seems to work.
```
wb = xlrd.open_workbook(path, encoding_override='CORRECT_ENCODING')
df = pd.read_excel(wb)
```

**Comment by Nacnano** [comment] 2022-06-23 10:54
I am not sure whether the developers see these comments since this issue is already closed. The encoding is very important for the program to interpret special characters. So, I would be pleased if there would be a solution to this problem (either the encoding or any other alternatives should be fine for me) 
Thank you

**Comment by hunter2009pf** [comment] 2023-08-03 05:56
encoding parameter is needed !!!
Year 2023 updated!
