### ISSUE TITLE
DF to CSV splits row if one of the data points ends in \r (Windows)

### ISSUE THREAD

**Issue by asishm** [pandas-dev/pandas#22678] opened 2018-09-12 10:45 UTC
#### Code Sample, a copy-pastable example if possible

```python
test_df = pd.DataFrame({"before": [1,2,3,4,6], "error": ["Water damage to 3 floor apartment building.  \r"]*5, "after": [8,9,10,11,12]})
test_df[['before', 'error', 'after']].to_csv("test_error.csv", index=False)
read_test_df = pd.read_csv("test_error.csv")
read_test_df
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>before</th>      <th>error</th>      <th>after</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>1.0</td>      <td>Water damage to 3 floor apartment building.</td>      <td>NaN</td>    </tr>    <tr>      <th>1</th>      <td>NaN</td>      <td>8</td>      <td>NaN</td>    </tr>    <tr>      <th>2</th>      <td>2.0</td>      <td>Water damage to 3 floor apartment building.</td>      <td>NaN</td>    </tr>    <tr>      <th>3</th>      <td>NaN</td>      <td>9</td>      <td>NaN</td>    </tr>    <tr>      <th>4</th>      <td>3.0</td>      <td>Water damage to 3 floor apartment building.</td>      <td>NaN</td>    </tr>    <tr>      <th>5</th>      <td>NaN</td>      <td>10</td>      <td>NaN</td>    </tr>    <tr>      <th>6</th>      <td>4.0</td>      <td>Water damage to 3 floor apartment building.</td>      <td>NaN</td>    </tr>    <tr>      <th>7</th>      <td>NaN</td>      <td>11</td>      <td>NaN</td>    </tr>    <tr>      <th>8</th>      <td>6.0</td>      <td>Water damage to 3 floor apartment building.</td>      <td>NaN</td>    </tr>    <tr>      <th>9</th>      <td>NaN</td>      <td>12</td>      <td>NaN</td>    </tr>  </tbody></table>

#### Problem description

The error column field ends with `\r`. When outputting this to csv, this splits the row into two lines.

#### Expected Output

'<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>before</th>      <th>error</th>      <th>after</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>1</td>      <td>Water damage to 3 floor apartment building.  \\r</td>      <td>8</td>    </tr>    <tr>      <th>1</th>      <td>2</td>      <td>Water damage to 3 floor apartment building.  \\r</td>      <td>9</td>    </tr>    <tr>      <th>2</th>      <td>3</td>      <td>Water damage to 3 floor apartment building.  \\r</td>      <td>10</td>    </tr>    <tr>      <th>3</th>      <td>4</td>      <td>Water damage to 3 floor apartment building.  \\r</td>      <td>11</td>    </tr>    <tr>      <th>4</th>      <td>6</td>      <td>Water damage to 3 floor apartment building.  \\r</td>      <td>12</td>    </tr>  </tbody></table>'

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by TomAugspurger** [comment] 2018-09-12 11:18
Dupe of https://github.com/pandas-dev/pandas/issues/10018. Pandas isn't escaping `\r` properly inside strings.

For now you can specify `line_terminator` when writing, or `lineterminator` when reading these files.

Let us know if you want to work on https://github.com/pandas-dev/pandas/issues/10018

**Closed by TomAugspurger** 2018-09-12 11:18 UTC
