### ISSUE TITLE
Can't use named aggregation with resample. 

### ISSUE THREAD

**Issue by alexjacobson95** [pandas-dev/pandas#30092] opened 2019-12-05 20:53 UTC
#### Code Sample, a copy-pastable example if possible
```python
import pandas as pd
import numpy as np
from functools import partial

df = pd.DataFrame(
    np.random.randn(1000, 3), 
    index=pd.date_range('1/1/2012', freq='S', periods=1000), 
    columns=['A', 'B', 'C']
)
dfg = df.resample('3T').agg(
    {'A': [
        partial(np.quantile, q=.9999), 
        partial(np.quantile, q=.90),
    ]}
)
```
#### Problem description
Resample, unlike groupby, has no ability to do named aggregation. This means if you use a function twice on the same column you get an error saying:

``pandas.core.base.SpecificationError: Function names must be unique, found multiple named quantile``. 

It would be very useful to make the resample agg interface similar to the groupby agg interface. An example of the named aggregation is here: https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#named-aggregation

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 0.25.3
numpy            : 1.17.4
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 18.1
setuptools       : 40.6.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by TomAugspurger** [comment] 2019-12-06 22:46
xref https://github.com/pandas-dev/pandas/issues/28380

**Comment by charlesdong1991** [comment] 2019-12-09 09:14
take

**Comment by MarcoGorelli** [comment] 2020-01-09 14:31
Tried reproducing this on master - didn't get an error, but now the two aggregations are the same:
```
import pandas as pd
import numpy as np
from functools import partial

df = pd.DataFrame(
    np.random.randn(1000, 3), 
    index=pd.date_range('1/1/2012', freq='S', periods=1000), 
    columns=['A', 'B', 'C']
)
dfg = df.resample('3T').agg(
    {'A': [
        partial(np.quantile, q=.9999), 
        partial(np.quantile, q=.1111),
    ]}
)
```
returns
```
                            A          
                     quantile  quantile
2012-01-01 00:00:00 -1.035997 -1.035997
2012-01-01 00:03:00 -1.326052 -1.326052
2012-01-01 00:06:00 -1.267661 -1.267661
2012-01-01 00:09:00 -1.321961 -1.321961
2012-01-01 00:12:00 -1.103027 -1.103027
2012-01-01 00:15:00 -0.987614 -0.987614
```

**Comment by charlesdong1991** [comment] 2020-01-09 14:47
thanks @MarcoGorelli I think you would need to give a name for this function since those two can not be distinguished for now, so it always takes the last one to use

```python
quant9 = functools.partial(np.percentile, q=.9999)
quant1 = functools.partial(np.percentile, q=.1111)
quant9.__name__ = "quant9"
quant1.__name__ = "quant1"
```
assigning different names for it should work

**Comment by MarcoGorelli** [comment] 2020-01-09 16:45
> i haven't had time to really work on this recently

Is this something you plan on coming back to? If so, that's fine, I'll leave it to you :) If not, I _might_ have a solution in mind which doesn't involve renaming the functions.

**Comment by charlesdong1991** [comment] 2020-01-09 16:52
awesome! pls go for it! @MarcoGorelli

**Comment by charlesdong1991** [comment] 2020-01-09 17:05
btw, i think you might need to open an issue and address this, because this seems not related to this issue, but quite general `groupby.agg` @MarcoGorelli since currently implementation does not distinguish the example you provided.

**Comment by otaviocv** [comment] 2020-03-21 14:31
Hello!

I posted a question on StackOverflow exactly about this issue. Could you, please, take a look? https://stackoverflow.com/questions/60788893/pandas-named-aggregation-not-working-with-resample-agg

Does anyone need help with this?

**Comment by MarcoGorelli** [comment] 2020-04-18 10:49
> Does anyone need help with this?

@otaviocv I have an open PR (#30858) to fix this issue, but still need to address some things. Feel free to take over if you have a solution in mind, else I hope to be able to fix it by the 1.1 release (current target is August 2020)

**Comment by MarcoGorelli** [comment] 2020-05-02 18:08
@otaviocv just got round to checking your SO post, and it seems different to this one (and indeed not fixed by the PR I have open). If you could open a new issue with it, that'd be great!

**Comment by MarcoGorelli** [comment] 2020-05-08 10:24
Have opened the issue reported by @otaviocv in #34064, as it's different to this one

@charlesdong1991 @jreback does this issue still need to be open? Because the original issue no longer errors, and I took the overwriting part forward here https://github.com/pandas-dev/pandas/issues/30880

**Comment by charlesdong1991** [comment] 2020-05-08 11:03
yeah, agree with it @MarcoGorelli ! could close this one already then to avoid duplication.

**Closed by charlesdong1991** 2020-05-08 11:03 UTC
Labels: Enhancement, Resample
