### ISSUE TITLE
pd.DataFrame.duplicated, drop_duplicates does not support column operation

### ISSUE THREAD

**Issue by matthewgson** [pandas-dev/pandas#31250] opened 2020-01-23 16:26 UTC
I was trying to use .duplicated to find identical columns, and possibly dropping them, but realized it doesn't do columnar operations.
It would be great if pd.DataFrame.duplicated or pd.DataFrame.drop_duplicates supports axis= argument. 

Current version 0.25.3 not supporting axis=
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html

Some workaround by custom function
https://thispointer.com/how-to-find-drop-duplicate-columns-in-a-dataframe-python-pandas/

**Comment by MarcoGorelli** [comment] 2020-01-27 17:54
Thanks for the suggestion - seems like a duplicate of #11250, so I'll close this for now (but please let me know if you disagree).

The original issue is still open by the way, feel free to submit a pull request!

**Closed by MarcoGorelli** 2020-01-27 17:54 UTC
