### ISSUE TITLE
API/DEPR: error_bad_lines/warn_bad_lines in pd.read_csv

### ISSUE THREAD

**Issue by h-vetinari** [pandas-dev/pandas#22677] opened 2018-09-12 06:28 UTC
From discussion started in #22639:

Currently, `pd.read_csv` has two booleans

* **error_bad_lines** : boolean, default True
  Lines with too many fields (e.g. a csv line with too many commas) will by default cause an exception to be raised, and no DataFrame will be returned. If False, then these “bad lines” will dropped from the DataFrame that is returned.
* **warn_bad_lines** : boolean, default True
  If error_bad_lines is False, and warn_bad_lines is True, a warning for each “bad line” will be output.

This is confusing (what happens if both are `True`), and not in line with other `errors`-kwargs that are all around the place. Clearer would be something like: `error_bad_lines = {'raise'|'warn'|'ignore'}`, and removing `warn_bad_lines`.

**Comment by gfyoung** [comment] 2018-09-12 06:36
This is a pretty reasonable suggestion and is consistent with what we do with other functions from an API standpoint (e.g. `to_numeric`).

**Comment by lithomas1** [comment] 2021-03-14 04:21
closing as duplicate of #15122

**Closed by lithomas1** 2021-03-14 04:21 UTC
Labels: API Design, Duplicate, IO CSV
