### ISSUE TITLE
DataFrame.__eq__ wrong for datetime64 vs timedelta64

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#18784] opened 2017-12-14 23:17 UTC
```
df = pd.DataFrame(pd.date_range('20130101', periods=3))
dt64 = np.datetime64('2013-01-01')
res = df - dt64
expected = pd.DataFrame([pd.Timedelta(days=0), pd.Timedelta(days=1),
                                              pd.Timedelta(days=2)])

>>> res
           0
0 1970-01-01
1 1970-01-02
2 1970-01-03

>>> expected
       0
0 0 days
1 1 days
2 2 days

>>> res == expected
      0
0  True
1  True
2  True

```

So both `__sub__` and `__eq__` are problematic.

**Comment by jreback** [comment] 2017-12-15 01:19
this is a duplicate of #12437

**Closed by jreback** 2017-12-15 01:19 UTC
