### ISSUE TITLE
BUG: pandas.read_sql does not trigger sqlalchemy "do_orm_execute" event

### ISSUE THREAD

**Issue by pbillante** [pandas-dev/pandas#45978] opened 2022-02-13 23:01 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

results = MyClass.query\
  .filter(MyClass.created >= last_week)\
  .with_entities(MyClass.name, cast(MyClass.created, Date).label('date'))

df = pd.read_sql(results.statement, results.session.bind)

......

@event.listens_for(Session, "do_orm_execute")
def _add_filtering_criteria(execute_state):
  print("This was triggered")
```

### Issue Description

When using the pd.read_sql function, the SQLAlchemy "do_orm_execute" event is not triggered, so logic tied to that event will not run.  If for example, the application is using the do_orm_execute event to enforce security rules, this can be a problem as no errors are triggered and all results are returned.

SQLAlchemy recommends using this event for public filters and other use cases.  See:
https://docs.sqlalchemy.org/en/14/_modules/examples/extending_query/filter_public.html

It is possible this is due to some logic missing in SQLAlchemy, but I noticed it only for queries using this pandas function.

### Expected Behavior

pd.read_sql() should trigger the do_orm_execute event from SQLAlchemy's events:
https://docs.sqlalchemy.org/en/14/orm/events.html

### Installed Versions

The output of pd.show_versions() results in an error.  This may be MacOS-related.

<details>

AssertionError: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py

</details>

**Comment by jreback** [comment] 2022-02-14 00:42
-1 on any logic in pandas
this is all delegated to sql alchemy anyhow

**Comment by mroeschke** [comment] 2022-02-14 23:00
I also agree. `read_sql/to_sql` is only scoped for simple read and writes and sqlalchemy is the abstraction to just read and write. Since I think this is out of scope and not a bug, closing

**Closed by mroeschke** 2022-02-14 23:00 UTC
Labels: Bug, Needs Triage
