### ISSUE TITLE
Code sample on pandas.Series.eq page is for pandas.Series.add

### ISSUE THREAD

**Issue by mmorang** [pandas-dev/pandas#26971] opened 2019-06-20 16:57 UTC
#### Problem description

The code sample shown in the "Examples" section on the [doc page for pandas.Series.eq](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.eq.html) appears to be for pandas.Series.add instead of eq.

![image](https://user-images.githubusercontent.com/14127094/59866977-c774f900-9341-11e9-9d15-6925da53b7c3.png)

**Comment by TomAugspurger** [comment] 2019-06-20 16:59
I think this is a duplicate of
https://github.com/pandas-dev/pandas/issues/24589

**Closed** 2019-06-20 18:45 UTC
