### ISSUE TITLE
BUG: pd.isna handles np.nan inconsistently between numpy and extension / arrow types

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#58151] opened 2024-04-04 15:22 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import numpy as np
import pyarrow as pa

np_arr = pd.Series([0, np.nan], dtype=np.float64) / 0
pd_arr = pd.Series([0, np.nan], dtype=pd.Float64Dtype()) / 0
pa_arr = pd.Series([0, np.nan], dtype=pd.ArrowDtype(pa.float64())) / 0
```

```
>>> np_arr
0   NaN
1   NaN
dtype: float64
>>> pd.isna(np_arr)
0    True
1    True
dtype: bool
>>> pd_arr
0     NaN
1    <NA>
dtype: Float64
>>> pd.isna(pd_arr)
0    False
1     True
dtype: bool
>>> pa_arr
0     NaN
1    <NA>
dtype: double[pyarrow]
>>> pd.isna(pa_arr)
0    False
1     True
dtype: bool

```

### Issue Description

In the NumPy case, the NaN value resulting from the 0 / 0 division is caught by `pd.isna` but not in the pandas / pyarrow case

### Expected Behavior

I think all should be True @jorisvandenbossche 

### Installed Versions

run on main

**Comment by jbrockmendel** [comment] 2024-04-25 00:50
There are several issues about this. We talked about it at the sprint

**Comment by phofl** [comment] 2024-05-13 19:57
agree with @jbrockmendel 

this is a duplicate of a bunch of issues, so closing here

**Closed by phofl** 2024-05-13 19:57 UTC
Labels: Bug, Needs Triage

**Comment by WillAyd** [comment] 2024-05-13 20:13
@phofl can you link to some of the issues you know about so readers can follow the discussion? I am not sure where to track this myself
