### ISSUE TITLE
DataFrame.replace: TypeError: “Cannot compare types 'ndarray(dtype=object)' and 'str' ”

### ISSUE THREAD

**Issue by mlitvinov** [pandas-dev/pandas#29279] opened 2019-10-30 02:04 UTC
I have a dataset in csv and a dictionary created by a classifier. It is necessary to put the key values in place of the keys . I use this code `df.replace(mapping,inplace = True) `and it works fine on 100 lines, but for 2000 and more, I get the error 

> "TypeError:“ Cannot compare types 'ndarray (dtype = object)' and 'str' ”.

 What am I doing wrong ??

**Comment by mroeschke** [comment] 2019-10-30 03:01
We would need a minimally reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by mlitvinov** [comment] 2019-10-30 07:15
> We would need a minimally reproducible example: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

I get an error of only 2,000 lines or more.  If I select a range from 2000 to 2100, an error does not appear :(

**Comment by MarcoGorelli** [comment] 2020-03-12 11:36
Closing due to lack of minimal reproducible example, feel free to open if you write one

**Closed by MarcoGorelli** 2020-03-12 11:36 UTC
Labels: Needs Info
