### ISSUE TITLE
"Cannot compare tz-naive and tz-aware datetime-like objects" when querying DatetimeIndex

### ISSUE THREAD

**Issue by hjfreyer** [pandas-dev/pandas#29463] opened 2019-11-07 14:54 UTC
## Code Sample, a copy-pastable example if possible

```python
import pandas as pd

df = pd.DataFrame({
    'val': range(10),
    'time': pd.date_range(start='2019-01-01', freq='1d', periods=10, tz='UTC')
})

# This works.
df.query('"2019-01-03 00:00:00+00" < time')

# This raises an exception.
df.set_index('time').query('"2019-01-03 00:00:00+00" < time')

# Perhaps interestingly, this works.
df.set_index('time').reset_index().query('"2019-01-03 00:00:00+00" < time')

```
#### Problem description

query shouldn't behave differently when the thing being queried is an index vs a column. Also, the error just seems objectively incorrect, as both values are tz-aware to start with (perhaps it's getting lost along the way).

May be related to #26236 , but the repro is different.

#### Expected Output
Not an exception.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.7.final.0
python-bits: 64
OS: Linux
OS-release: 4.3.5-smp-821.23.0.0
machine: x86_64
processor: 
byteorder: little
LC_ALL: en_US.UTF-8
LANG: None
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: None
pip: None
setuptools: unknown
Cython: None
numpy: 1.16.4
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 2.0.0
sphinx: None
patsy: 0.4.1
dateutil: 2.8.0
pytz: 2019.3
blosc: None
bottleneck: None
tables: 3.5.2
numexpr: 2.6.10dev0
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: 1.0.1
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10.3
s3fs: None
fastparquet: None
pandas_gbq: 0+unknown
pandas_datareader: None
gcsfs: None

</details>

**Comment by mroeschke** [comment] 2020-04-26 21:09
This looks fixed on master. Could use a test

```
In [31]: import pandas as pd
    ...:
    ...: df = pd.DataFrame({
    ...:     'val': range(10),
    ...:     'time': pd.date_range(start='2019-01-01', freq='1d', periods=10, tz='UTC')
    ...: })

In [32]: df.set_index('time').query('"2019-01-03 00:00:00+00" < time')
    ...:
Out[32]:
                           val
time
2019-01-04 00:00:00+00:00    3
2019-01-05 00:00:00+00:00    4
2019-01-06 00:00:00+00:00    5
2019-01-07 00:00:00+00:00    6
2019-01-08 00:00:00+00:00    7
2019-01-09 00:00:00+00:00    8
2019-01-10 00:00:00+00:00    9

In [33]: pd.__version__
Out[33]: '1.1.0.dev0+1390.gf3fdab389'
```

**Comment by vipulrai91** [comment] 2020-05-05 17:23
@mroeschke Hello , I am new here ,I see that this looks resolved, but "needs tests" label is still attached, if these needs to be tested again , shall I work on this? 

Please clarify.

**Comment by mroeschke** [comment] 2020-05-05 18:56
Sure feel free to work on it @vipulrai91. This needs a regression test to ensure the behavior

**Comment by vipulrai91** [comment] 2020-05-05 19:39
@mroeschke  Thank you. I will start working on this.

**Comment by vipulrai91** [comment] 2020-05-05 19:39
take

**Comment by vipulrai91** [comment] 2020-05-06 11:30
@mroeschke  I have added the test at : pandas/tests/frame/indexing/test_column_vs_index_tz.py
Since this is related to indexing , I have added in indexing directory.
Please let me know if this is what was required or something needs to be changed.

**Closed** 2020-05-20 05:40 UTC
Labels: Needs Tests, good first issue
