### ISSUE TITLE
BUG: TypeError: expected <class 'float'> when reading xlsx file

### ISSUE THREAD

**Issue by spsspro** [pandas-dev/pandas#47401] opened 2022-06-17 10:36 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [x] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
# this is the sample file: https://file.io/Z9PxHlfRY67I
df = pd.read_excel('Z9PxHlfRY67I.xlsx')
```

### Issue Description

above code will throw error below:
```
TypeError: expected <class 'float'>
```
the engine is `openpyxl`
pandas version: 1.4.2

### Expected Behavior

read this file successfully

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.9.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.5.0
Version          : Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : zh_CN.UTF-8
pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 62.0.0
Cython           : 0.29.17
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 7.25.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2022.5.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.2
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.4.22
tables           : None
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : None

</details>

**Comment by phofl** [comment] 2022-06-17 12:27
Hi, thanks for your report. Is it possible to create a example where the file is created in code? Also the traceback would be helpful

**Comment by rhshadrach** [comment] 2022-06-29 03:09
@spsspro - it seems the above file is no longer available. As mentioned above, it's best to provide an example that can be generated from code if possible. I'm closing this for now, but if you can post an example I'd be happy to reopen.

**Closed by rhshadrach** 2022-06-29 03:09 UTC
Labels: Bug, IO Excel, Needs Info

**Comment by agustinissidoro** [comment] 2023-01-16 04:33
Hi, I am having the same problem when loading .xlsx files. Is there a solution for this?

**Comment by rhshadrach** [comment] 2023-01-16 04:45
@agustinissidoro - If you can provide a reproducible example we can reopen this issue.

**Comment by agustinissidoro** [comment] 2023-01-16 15:34
Ok. I'm sorry for this question as I am new to GitHub: should I upload the code and files? The issue is actually an openpyxl module issue inside Pandas. Other libraries which make use of openpyxl report the exact same error in the module.

**Comment by rhshadrach** [comment] 2023-01-16 21:42
The best option, if it's possible, is to post the code in a comment. The code should be self-contained and about as small as possible to reproduce the issue. Only if that's not possible should things like data sources be uploaded.

See https://matthewrocklin.com/minimal-bug-reports

**Comment by nikolasusaomure** [comment] 2023-03-08 20:02
For anyone new running into this issues,
make sure your sheet isn't actually broken.
If you've used some shoddy exporter, that just might be the case.

Try opening it google sheets (or equivalent) and extracting it.

**Comment by rhshadrach** [comment] 2023-03-09 21:41
Thanks @nikolasusaomure. I'll also add that many readers try to "correct" for invalid files, many times silently. So just because a particular reader is able to load your file it does not necessarily means it's a valid excel file; though this should give more confidence that it is.

As mentioned above, happy to reopen if there is a reproducible example.

**Comment by LeidyWebdes** [comment] 2023-08-10 16:52
Hi!
@rhshadrach 
Here is a [file for the example](https://docs.google.com/spreadsheets/d/1BcxLqXDSXQr_ka5UAc-LgwahBtxVSI0G/edit?usp=drive_link&ouid=104338626414859106980&rtpof=true&sd=true). The original file had many columns, but the problem is in one column. I deleted each of the other columns and discovered that was the problem column. The solution was to delete the column and Ctrl+Z jejeje
