### ISSUE TITLE
Feature Request: Named aggregation for pandas rolling function

### ISSUE THREAD

**Issue by kunalkishore** [pandas-dev/pandas#47379] opened 2022-06-16 04:58 UTC
Two asks here:
1. Ability to do multiple aggregations on the same column within the same rolling window
2. Ability to do named aggregations on same or multiple columns

**Comment by mroeschke** [comment] 2022-06-16 22:59
Thanks for the request, this is a duplicate of https://github.com/pandas-dev/pandas/issues/28333 so closing in favor of that issue

**Closed by mroeschke** 2022-06-16 22:59 UTC
