### ISSUE TITLE
Add formatters parameter to DataFrame.to_csv()

### ISSUE THREAD

**Issue by adamboche** [pandas-dev/pandas#16840] opened 2017-07-06 17:19 UTC
`DataFrame.to_string()` has a formatters parameter for formatting columns individually, but `to_csv()` could benefit from that parameter as well. This is especially useful, for example, when formatting integers with missing values.

**Comment by jreback** [comment] 2017-07-06 23:07
duplicate of #4668 

yep, would be nice to have. interested in a PR?

**Comment by TomAugspurger** [comment] 2017-07-12 19:38
Closing in favor of #4668

**Closed by TomAugspurger** 2017-07-12 19:38 UTC
Labels: Duplicate, IO CSV, Output-Formatting

**Comment by moi90** [comment] 2023-07-12 18:49
Actually, this is NOT a duplicate of #4668. There, `float_format` is talked about, but this applies to all columns. A `formatters` parameter, similar to `to_string` could apply different formats to different columns (and this is exactly what I need).
