### ISSUE TITLE
Non-deterministic behavior of pandas

### ISSUE THREAD

**Issue by NexYY** [pandas-dev/pandas#26224] opened 2019-04-27 14:17 UTC
```python
# get value based on ID from data frame
# transfer ID to integer
ID = int(ID)
if not isinstance(ID, int):
    if isinstance(ID, list):
        case_id = "".join(case_id)
    ID = int(ID)
# make tmp of dataframe case_information but with enforced (casted) data type
tmp_ciq = self.case_information_q.copy(deep=True)
tmp_ciq = tmp_ciq.astype({self.case_id_identifier: int})
condition_df = tmp_ciq[self.case_id_identifier] == ID
# this data frame should have just one row
df_required_cases = tmp_ciq[condition_df]

# try to get the value with iloc
# this works 98% of the time
try:
    index_cf_from_x = int(df_required_cases.iloc[0][self.str_start])
except IndexError:
    e_error_string = "self.str_start: {}\nlist_IDs_temp: {}\ni: {} - ID: {}\ndf_required_cases:\n{}\n\nself.case_information_q:\n{}\n\ntype(ID): {}\ndf_required_cases.dtypes: {}\n\ncondition_df:{}\n" \
        .format(self.str_start, list_IDs_temp, i, ID, df_required_cases.to_string(), self.case_information_q.to_string(), type(ID), df_required_cases.dtypes, condition_df.to_string())
    try:
        # if iloc doesn't work repeat the same issue with isin().
        # this works 1% of the time
        ID_l = [ID]
        df_required_cases = \
            self.case_information_q.loc[self.case_information_q[self.case_id_identifier].isin(ID_l)].copy(deep=True)
        index_cf_from_x = int(df_required_cases.iloc[0][self.str_start])
    except:
        # even tho this is a example data set with right entries I fail in 1% of cases. 
        raise IndexError(e_error_string)
```
#### Problem description

I have the issue that pandas does not always get all rows if I filter on a data frame.
The behavior seems non-deterministic, as I sometimes apply the same method twice and get most of the time the right output.
I currently have a workaround, in which I do apply the same operations with different methods iteratively, until I get the result I need. For example: I first filter with loc and if I don't get the right result I use .isin().
Luckily, I know the number of rows which should return and can catch errors. If my workaround doesn't work, I transform the whole dataframe into a dictionary and work on it without pandas.
The example use cases features a use case in which I need to have exactly one row, in order to get an integer of a column. This fails, as no row is sometimes found, even tho I factually have the entry with the correct enforced data type in the data frame.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.2.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.2
pytest: None
pip: 19.0.3
setuptools: 40.8.0
Cython: None
numpy: 1.16.2
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.4.0
sphinx: None
patsy: None
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by jbrockmendel** [comment] 2019-04-27 16:27
Can you cut this down to a [MCVE](https://stackoverflow.com/help/mcve)?  i.e. in order to help, we need to be able to reproduce the problem ourselves.

**Comment by WillAyd** [comment] 2019-04-29 16:12
Closing due to lack of minimally reproducible example. If you can provide code as requested above feel free to reopen

**Closed by WillAyd** 2019-04-29 16:12 UTC
Labels: Needs Info
