### ISSUE TITLE
BUG: Pandas will always attempt to fetch all rows, even from a ResultProxy that does not return rows

### ISSUE THREAD

**Issue by ravisurdhar** [pandas-dev/pandas#40205] opened 2021-03-03 19:23 UTC
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
unload_query = f"""
    UNLOAD ('SELECT * FROM {schema}.{table}')
    TO '{s3_path}'
    IAM_ROLE '{iam_role}'
    PARQUET
    """

query_results = pd.read_sql(unload_query, connector)

```

#### Problem description
`ResourceClosedError: This result object does not return rows. It has been closed automatically.`

The example above is specific to Redshift, but will probably occur in other DBs with similar queries. The issue seems to be that after executing the query, Pandas will always attempt to run `fetchall()` on the ResultProxy object without first checking if there are any rows to fetch.
https://github.com/pandas-dev/pandas/blob/440a7de1c328aede3f566830c989922d46c254a8/pandas/io/sql.py#L1480  The Redshift `UNLOAD` command ([docs](https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html)) does not return rows, so this query will always result in an error being raised if executed with `pd.read_sql()`. 

I suggest wrapping that line with `if result.returns_rows is True:`

#### Expected Output
Nothing. I'd expect `pd.read_sql()` to execute silently. 

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.6.9.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.3.0
Version          : Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.1.5
numpy            : 1.19.5
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : 1.0.2
psycopg2         : 2.8.6 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : None
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : 3.0.0
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : 1.3.23
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by mroeschke** [comment] 2021-04-30 00:58
As commented in https://github.com/pandas-dev/pandas/pull/40229#issuecomment-829724287, I think `read_sql` is designed to load data from a sql database into a DataFrame and not designed to execute database transactions. So closing as the intended behavior

**Closed by mroeschke** 2021-04-30 00:58 UTC
Labels: Bug, IO SQL, Needs Triage
