### ISSUE TITLE
Reverse operators on integer-NA series and numpy scalars resulting in object dtype

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#22024] opened 2018-07-23 13:48 UTC
This is not necessarily a bug, but at least some unexpected results:

```
In [83]: s = pd.Series([1, 2, 3], dtype='Int64')

In [84]: s + s[0]
Out[84]: 
0    2
1    3
2    4
dtype: Int64

In [85]: s[0] + s
Out[85]: 
0    2
1    3
2    4
dtype: object
```

In the above `s[0]` is a numpy scalar, if you do a `radd` with a normal int, you do not get object:

```
In [86]: 1 + s
Out[86]: 
0    2
1    3
2    4
dtype: Int64

In [87]: type(s[0])
Out[87]: numpy.int64
```

**Comment by peterpanmj** [comment] 2018-08-08 06:48
I would like to work on a PR.

**Comment by jreback** [comment] 2018-08-08 09:18
go for it!

**Comment by peterpanmj** [comment] 2018-11-09 03:38
The issue is resolved by some other PR. In current master it behaves just like expected. @jorisvandenbossche 
```python
In [2]: import pandas as pd

In [3]: s = pd.Series([1, 2, 3], dtype='Int64')

In [4]: s[0]
Out[4]: 1

In [5]: s[0] + s
Out[5]:
0    2
1    3
2    4
dtype: Int64

In [6]: s + s[0]
Out[6]:
0    2
1    3
2    4
dtype: Int64

**Comment by jreback** [comment] 2018-11-09 03:48
lots of work by @jbrockmendel and others in ops likely fixed this
i believe we have good test coverage for this but pls take a look
if we do then can just close this

**Comment by TomAugspurger** [comment] 2018-11-09 04:11
We have https://github.com/pandas-dev/pandas/issues/22974 for testing ops between EA and ndarrays / sequences directly (we just do series right now). So we can close this in favor of the issue for creating a base test.

**Closed by TomAugspurger** 2018-11-09 04:11 UTC
Labels: ExtensionArray
