### ISSUE TITLE
DOC: Add automatic exclusion of prompts from the copies using sphinx-copybutton

### ISSUE THREAD

**Issue by mosc9575** [pandas-dev/pandas#59369] opened 2024-07-31 12:54 UTC
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

In the docs the sphinx extension `sphinx-copybutton` is added but the output is not stripped. This means, that code is copied with possible outputs.

https://github.com/pandas-dev/pandas/blob/73b5578967bedd1f94b8a54d9047f33364178783/doc/source/conf.py#L59

A possible solution is documented in the section [using regex prompt identifiers](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#using-regexp-prompt-identifiers).

### Documentation problem

The main problem is, that examples in code blocks can have some output and will not work in a plain jupyter notebook cell without touching the copied code.

One possible example is in [`pandas.DataFrame.to_dict`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html).

### Suggested fix for documentation

The solution is to add

```
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.{3,}: | {5,8}: "
copybutton_prompt_is_regexp = True
```

to `conf.py`.

**Comment by mroeschke** [comment] 2024-07-31 17:13
Thanks for the report, but IIRC this is essentially a duplicate of https://github.com/pandas-dev/pandas/issues/56388 so closing

**Closed by mroeschke** 2024-07-31 17:13 UTC
Labels: Docs, Needs Triage
