### ISSUE TITLE
to_clipboard undocumentedly changed from using to_csv to to_string downstream.

### ISSUE THREAD

**Issue by mvbentes** [pandas-dev/pandas#21385] opened 2018-06-08 14:49 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c'])}
df = pd.DataFrame(d)
dados.to_clipboard(index=False, header=False, line_terminator="\r\n")
```
#### Problem description

I just upgraded to `pandas 0.23.0` and this code on my program broke. This is likelly related to #21104.
According to `DataFrame.to_clipboard` documentation, it would pass any `**kwargs` down to `DataFrame.to_csv`, which has the `line_terminator` argument and used to work fine.

It seems that it now uses `DataFrame.to_string` albeit undocumented. This function does not support the same set of arguments as `DataFrame.to_csv` which is bound to cause some bugs.

I get the following error:

```python traceback
>>> df.to_clipboard(index=False, header=False, line_terminator="\r\n")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u5en\ArqProg\Anaconda3\lib\site-packages\pandas\core\generic.py", line 2246, in to_clipboard
    clipboards.to_clipboard(self, excel=excel, sep=sep, **kwargs)
  File "C:\Users\u5en\ArqProg\Anaconda3\lib\site-packages\pandas\io\clipboards.py", line 117, in to_clipboard
    objstr = obj.to_string(**kwargs)
TypeError: to_string() got an unexpected keyword argument 'line_terminator'
```

I also note that `Series.to_clipboard` seems to ***silently ignore*** the `line_terminator` parameter, which also is not good.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 32
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.0
pytest: 3.5.1
pip: 10.0.1
setuptools: 39.1.0
Cython: 0.28.2
numpy: 1.14.3
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.4
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.4
blosc: None
bottleneck: 1.2.1
tables: 3.4.3
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.3
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.4
lxml: 4.2.1
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
</details>

**Comment by anhqle** [comment] 2018-06-09 03:00
This is an interesting bug -- `to_string` was added to the codebase 5 years ago so that's not the problem.

The real change between `0.22` and `0.23` is that the default `sep` is changed from `'\t'` to `r'\t`, causing an exception that is simply suppressed (by `pass`ing in the `except` clause). Since the exception is passed, the method then passed the data frame to `to_string`. That's the real reason why `to_string` is used in `0.23`.

**Comment by jreback** [comment] 2018-06-09 10:11
duplicate of #21111 i think

**Comment by gfyoung** [comment] 2018-06-10 05:10
@jreback : I would agree with this assessment.

@mbventes : If there is anything you would like to add to #21111, feel free to comment there!

**Closed by gfyoung** 2018-06-10 05:10 UTC
Labels: Regression
