### ISSUE TITLE
two dataframes outer join on null values

### ISSUE THREAD

**Issue by socheon** [pandas-dev/pandas#7473] opened 2014-06-16 12:30 UTC
In pandas, unlike SQL, the rows seemed to be joining on null values. Is this a bug?
related SO: http://stackoverflow.com/questions/23940181/pandas-merging-with-missing-values/23940686#23940686

Code snippet

``` python
import pandas as pd 
import numpy as np

df1 = pd.DataFrame(
    [[1, None],
    [2, 'y']],
    columns = ['A', 'B']
)
print df1

df2 = pd.DataFrame(
    [['y', 'Y'],
    [None, 'None1'],
    [None, 'None2']],
    columns = ['B', 'C']
)
print df2

print df1.merge(df2, on='B', how='outer')
```

Output

```
   A     B
0  1  None
1  2     y

      B      C
0     y      Y
1  None  None1
2  None  None2

   A     B      C
0  1  None  None1
1  1  None  None2
2  2     y      Y
```

You can see row 0 in df1 unexpectedly joins to both rows in df2.

I would expect the correct answer to be

```
   A       B      C
0  1      None  None
1  2       y      Y
2 None None None1
3 None None None2
```

**Comment by pwrignall** [comment] 2020-08-19 13:50
@socheon Bit late after your comment but I notice this is still open and it helped me recently. I didn't quite get what I was looking for using your snippet but a bit of adjustment returned what I wanted and is more similar to the results expected doing a full outer join in SQL:

```
def merge_fullouter(df1, df2, on_col):
    """
    Does a SQLesque full outer join on two data frames without matching null values
    Input: df1, df2, Pandas data frames, data frames to full outer join
           on_col, string, the column on which to join the data frames by
    """
    return pd.concat([
        df1[pd.notnull(df1[on_col])].merge(df2[pd.notnull(df2[on_col])], how="outer", on=on_col),
        df1[pd.isnull(df1[on_col])],
        df2[pd.isnull(df2[on_col])]
])
```

**Comment by mroeschke** [comment] 2021-07-21 04:37
Closing as duplicate of https://github.com/pandas-dev/pandas/issues/32306 with a more recent discussion on the future policy we want.

**Closed by mroeschke** 2021-07-21 04:37 UTC
Labels: Docs, Missing-data, Reshaping
