### ISSUE TITLE
DataFrame.to_string(index=False) alignment bug

### ISSUE THREAD

**Issue by jzwinck** [pandas-dev/pandas#15467] opened 2017-02-21 09:34 UTC
```python
import pandas as pd
df = pd.DataFrame()
df['a'] = ['hello world', 'hi']
df['b'] = 0
print(df.to_string(index=False))
```

#### Problem description

It fails to align the first column header:

    a  b
    hello world  0
             hi  0

#### Expected Output

              a  b
    hello world  0
             hi  0

#### Output of ``pd.show_versions()``

    pandas: 0.19.2
    python: 3.5.1
    OS: Linux
    LC_ALL: None
    LANG: en_US.UTF-8
    LOCALE: en_US.UTF-8

**Comment by jreback** [comment] 2017-02-21 14:10
dupe of #13032 

PR's to fix welcome!

**Closed by jreback** 2017-02-21 14:10 UTC
