### ISSUE TITLE
Pandas UTF-8 handling is rubbish

### ISSUE THREAD

**Issue by james-martin-engineer** [pandas-dev/pandas#26290] opened 2019-05-06 06:21 UTC
I'm using Pandas as part of PDFKIT. The UTF-8 Handling in Pandas is abysmal. I've rendered a HTML from a DOC file using Microsoft Word. Word has rendered in some 96 and A0 ASCII characters (a minus and a space respectively) as part of this process (actually, it does it every time). Unfortuantely, Pandas can't handle either of these characters resulting in 

`UnicodeDecodeError: ‘utf8’ codec can’t decode byte 0x96 in position 1054: invalid start byte`
`UnicodeDecodeError: ‘utf8’ codec can’t decode byte 0xa0 in position 1054: invalid start byte`

**Comment by WillAyd** [comment] 2019-05-06 15:07
Can you provide a code sample to reproduce the issue?

**Comment by WillAyd** [comment] 2019-05-10 04:17
Closing due to lack of a reproducible example. Can certainly reopen if you have one to provide

**Closed by WillAyd** 2019-05-10 04:17 UTC
Labels: Needs Info
