### ISSUE TITLE
BUG: SettingWithCopyWarning

### ISSUE THREAD

**Issue by iliya-malecki** [pandas-dev/pandas#46869] opened 2022-04-25 19:09 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  available_data['loading'] = 1
```

### Issue Description

Sorry but for the life of me i cant create a reproducible example. It is just a dataframe that was created using `maindf.query('some_time > @todays_datetime')`
available_data.values.base is maindf.values.base # False

### Expected Behavior

not have the warning

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-1051-azure
Version          : #53~18.04.1-Ubuntu SMP Fri Jun 18 22:32:58 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.35
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by rhshadrach** [comment] 2022-04-25 20:36
Here is what I believe is happening:

```
df = pd.DataFrame({'a': [1, 2, 3]})
df2 = df.query('a > 1')
df2['a'] = 5
```

The method `.query` may return a view or copy; it will certainly return a view when the condition always holds (e.g. replace `a > 1` with `a > 0` in the example above. When it makes a copy and then you are setting new values on that copy, pandas is generating this warning in case you meant to modify the original (`df` in the example above) instead. To silence the warning, you can copy after doing the query: `df2 = df.query('a > 1').copy()`.

**Comment by iliya-malecki** [comment] 2022-04-26 12:42
@rhshadrach thank you, `.copy()` helped!
I have a couple of questions now:
1. Why is it a valid idea to return a view from `.query()`? What is the intention here? To me, it looks like a dangerous feature to have - conditionally ruining an original dataframe. I obviously dont understand what is happening under the hood, so i can only think about usage.
2. Is it a valid way to check whether a dataframe is a view or copy? `available_data.values.base is maindf.values.base`

**Comment by mroeschke** [comment] 2022-07-05 23:58
1. `query` tries to follow numpy indexing semantics which can also return a view or copy depending on the indexing operation
2. You can use `np.shares_memory` to also see if the underlying data shares memory. https://numpy.org/doc/stable/reference/generated/numpy.shares_memory.html

Closing as this is not a bug rather a usage question

**Closed by mroeschke** 2022-07-05 23:58 UTC
Labels: Usage Question, Warnings, Closing Candidate
