### ISSUE TITLE
pandas version

### ISSUE THREAD

**Issue by Pysion-lin** [pandas-dev/pandas#43012] opened 2021-08-13 03:03 UTC
pandas==1.0.3
In [16]: df.where(df.notnull(), None)
Out[16]: 
            A               B
0   2013-01-01      1
1          NaT           2
2  2013-01-03    None

but pandas==1.3.1
In [16]: df.where(df.notnull(), None)
Out[16]: 
           A             B
0 2013-01-01     1
1        NaT          2
2 2013-01-03  NaN

why?

@MarcoGorelli

**Comment by MarcoGorelli** [comment] 2021-08-13 09:08
Hi @Pysion-lin - duplicate of #42423?

**Comment by Pysion-lin** [comment] 2021-08-13 09:20
> Hi @Pysion-lin - duplicate of #42423?

Thankyou very much

**Comment by MarcoGorelli** [comment] 2021-08-13 09:21
no worries 😄

**Closed by MarcoGorelli** 2021-08-13 09:21 UTC
Labels: Closing Candidate
