### ISSUE TITLE
BUG: df reassignment following reorder_categories changed behavior in 1.1.0rc0

### ISSUE THREAD

**Issue by MaozGelbart** [pandas-dev/pandas#35369] opened 2020-07-21 20:48 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd

h = pd.Series(list("mn")).astype("category")
df = pd.DataFrame({"h":h})

df.h = df.h.cat.reorder_categories(["n", "m"])
print(df.h.cat.categories)

h = h.cat.reorder_categories(["n","m"])
print(h.cat.categories)
```

#### Problem description
Output with 1.1.0rc0:
```
Index(['m', 'n'], dtype='object')
Index(['n', 'm'], dtype='object')
```
The assignment of the reordered series back into the dataframe seems to remove the new order. This has changed from 1.0.5 but I could not find a note on this under the release notes.

#### Expected Output
As with 1.0.5:
```
Index(['n', 'm'], dtype='object')
Index(['n', 'm'], dtype='object')
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : bfac13628394ac7317bb94833319bd6bf87603af
python           : 3.8.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
Version          : Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.1.0rc0
numpy            : 1.19.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200712
Cython           : None
pytest           : 5.4.3
hypothesis       : None
sphinx           : 2.3.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.15.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by simonjayhawkins** [comment] 2020-07-22 10:58
Thanks @MaozGelbart for the report.

it appears #32831 resulted in this change of behaviour.

d4273353bc512e3b4e79c361b879633f33ec7289 is the first bad commit
commit d4273353bc512e3b4e79c361b879633f33ec7289
Author: jbrockmendel <jbrockmendel@gmail.com>
Date:   Sat Mar 21 14:00:30 2020 -0700

    BUG: ExtensionBlock.set not setting values inplace (#32831)

marking as regression for now, while further investigate.

cc @jbrockmendel

**Comment by TomAugspurger** [comment] 2020-07-27 14:12
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/33457

**Closed by TomAugspurger** 2020-07-27 14:12 UTC
Labels: Bug, Categorical, Regression
