### ISSUE TITLE
PERF: regression in DataFrame.shift method performance

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#42246] opened 2021-06-26 07:42 UTC
Performance regression in `shift` caused by #40536 

I don't know if it's a particularly useful benchmark, but there is a big slowdown potentially related to this PR: https://pandas.pydata.org/speed/pandas/#frame_methods.Shift.time_shift?python=3.8&Cython=0.29.21&p-axis=1&commits=05a0e98a-bc62e768

_Originally posted by @jorisvandenbossche in https://github.com/pandas-dev/pandas/issues/40536#issuecomment-808265872_

**Comment by jbrockmendel** [comment] 2021-06-26 17:13
2 possible improvements come to mind:

1) Change `concat` to allow disabling consolidation

2) the axis=1 path added in #40536 may be unnecessary (there's a comment that suggests otherwise; would need to look more closely) when `isinstance(self._mgr, BlockManager) and self._mgr.nblocks == 1`, in which case we could do `self.T.shift(n).T`

**Comment by simonjayhawkins** [comment] 2021-06-28 21:55
> 2 possible improvements come to mind:
> 

because the regression is a labelled as a refactor and the test fixed is for ArrayManager which is not yet public, is reverting for 1.3 also an option? (and do the refactor for 1.4 instead)

**Comment by jbrockmendel** [comment] 2021-06-29 02:14
> is reverting for 1.3 also an option? (and do the refactor for 1.4 instead)

sure

**Comment by simonjayhawkins** [comment] 2021-06-30 07:36
moving to 1.4, xref #42322

**Comment by jbrockmendel** [comment] 2021-12-13 23:56
Closing.  The PR that caused the perf regression was reverted, and my initial idea of eventually un-reverting looks very unlikely.

**Closed by jbrockmendel** 2021-12-13 23:56 UTC
Labels: Performance, Regression
