### ISSUE TITLE
BUG: Regression in quantile method when using Int64 extension dtype

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas#40395] opened 2021-03-12 10:37 UTC
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest version of pandas.
- [X] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import numpy as np
import pandas as pd
s =  pd.Series(np.arange(100), dtype=pd.Int64Dtype())
s.quantile(0.75)
```

produces 

```
AbstractMethodError: This method must be defined in the concrete class type
```

#### Problem description

A regression in the extension dtype not raises `AbstractMethodError`. This is only true in 1.3.0dev. Found in statsmodels prerelease testing.

#### Output of ``pd.show_versions()``

<details>
```
INSTALLED VERSIONS
------------------
commit           : 65abf6b2d8a1c109fca070ed95f9bc2106cfb818
python           : 3.8.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.104-microsoft-standard
Version          : #1 SMP Wed Feb 19 06:37:35 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0.dev0+1026.g65abf6b2d8
numpy            : 1.21.0.dev0+934.g6222e283f
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 54.1.1
Cython           : 0.29.22
pytest           : 6.2.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.0.dev0+5e9eb01
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```

</details>

**Comment by bashtage** [comment] 2021-03-12 10:37
Seems to want the extension dtype to have implemented `_from_factorized(cls, values, original`

**Comment by jorisvandenbossche** [comment] 2021-03-12 16:06
Yes, this was caused by a recent refactor of `quantile`, for which I opened https://github.com/pandas-dev/pandas/issues/39771 at the time, so going to close this issue as a duplicate of that.

**Comment by jorisvandenbossche** [comment] 2021-03-12 16:06
Duplicate of #39771

**Closed by jorisvandenbossche** 2021-03-12 16:06 UTC
Labels: Bug, Needs Triage
