### ISSUE TITLE
DOC: Switch to stable version redirection in banner

### ISSUE THREAD

**Issue by Abinashbunty** [pandas-dev/pandas#58221] opened 2024-04-11 14:31 UTC
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.Series.dt.tz_convert.html

This warning banner exists on all the pages.

### Documentation problem

![image](https://github.com/pandas-dev/pandas/assets/25522048/976a24f7-05d8-414f-a886-728a72be6ec5)

Even if I'm in the right version for the docs, the banner still shows up. And clicking on the **Switch to stable version** doesn't do anything. The banner still exists.

### Suggested fix for documentation

To remove the warning banner when the visitor is already in the stable version. This makes sure that you are indeed in the right documentation and not elsewhere.

**Comment by Aloqeely** [comment] 2024-04-11 15:14
Thanks for the report.
This has been temporarily fixed and there is already an open issue here: #57593

**Comment by mroeschke** [comment] 2024-04-11 15:34
Yes, closing a duplicate of https://github.com/pandas-dev/pandas/issues/57593

**Closed by mroeschke** 2024-04-11 15:34 UTC
Labels: Docs, Needs Triage
