### ISSUE TITLE
BUG: isin has unexpected behavirour when using a dataframe with a large amout of rows (1.000.001)

### ISSUE THREAD

**Issue by Hanspagh** [pandas-dev/pandas#36066] opened 2020-09-02 12:58 UTC
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import numpy as np
nans = np.repeat(np.nan, 1_000_001)
big = pd.DataFrame({"test":nans})
assert all(big["test"].isin([np.nan])) == True
 
nans = np.repeat(np.nan, 1_000_000)
small = pd.DataFrame({"test":nans})
assert all(small["test"].isin([np.nan])) == True
assert all(small.dtypes == big.dtypes)
```

#### Problem description
The above code fails on the first assert, but not on the second.

#### Expected Output
The excepted behavior would be that both asserts either fail or succeeds

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : f2ca0a2665b2d169c97de87b8e778dbed86aea07
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.3.0
Version          : Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.1
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : 0.29.17
pytest           : 5.4.3
hypothesis       : 4.57.1
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.0
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.15.1
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.48.0

</details>

**Comment by jreback** [comment] 2020-09-03 09:06
i think this is patched on master - pls check

**Comment by Hanspagh** [comment] 2020-09-03 09:55
It does not seem to be patched on master.
Running with the lastest master produces the same bug

```INSTALLED VERSIONS
------------------
commit           : 361166f86da1a665a1b5808e0935c28f8cf56d34
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.3.0
Version          : Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.0.dev0+233.g361166f86
numpy            : 1.19.0rc2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 41.2.0
Cython           : 0.29.21
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.3
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 1.0.1
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.7
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```

**Comment by jreback** [comment] 2020-09-03 10:23
pls look for a duplicate bug report

**Comment by Hanspagh** [comment] 2020-09-03 11:31
might be loosely related to #35565 and #34125

**Comment by Hanspagh** [comment] 2020-09-03 11:44
Seems to boil down to the use of `np.in1d` for more than 1mill rows, would it be better to disallow NaN in `isin`, since 
> NaN values never compare equal. That is, the test NaN==NaN is always False by definition of NaN.
and then ask the user to use `isna` instead?

**Comment by jreback** [comment] 2020-09-03 12:11
hmm we do properly handle man actually for smaller sizes

so would need to filter null out and then add back if it exists (and isin) as we want the perf of np.in1d for larger sizes

**Comment by TomAugspurger** [comment] 2020-09-04 11:04
I think fixing https://github.com/pandas-dev/pandas/issues/25395 will fix this as well, so closing as a duplicate of that.

**Closed by TomAugspurger** 2020-09-04 11:04 UTC
Labels: Bug, Needs Triage
