### ISSUE TITLE
DOC: getting started under coming from sql

### ISSUE THREAD

**Issue by mattwelke** [pandas-dev/pandas#39129] opened 2021-01-12 18:59 UTC
#### Location of the documentation

[this should provide the location of the documentation, e.g. "pandas.read_csv" or the URL of the documentation, e.g. "https://dev.pandas.io/docs/reference/api/pandas.read_csv.html"]

**Note**: You can check the latest versions of the docs on `master` [here](https://pandas.pydata.org/docs/dev/).

#### Documentation problem

[this should provide a description of what documentation you believe needs to be fixed/improved]

#### Suggested fix for documentation

[this should explain the suggested fix and **why** it's better than the existing documentation]

**Comment by MarcoGorelli** [comment] 2021-01-12 19:06
thanks for the report - duplicate of #39130 I guess?

**Closed by MarcoGorelli** 2021-01-12 19:06 UTC
Labels: Docs, Needs Triage

**Comment by mattwelke** [comment] 2021-01-12 19:08
Oh that's weird. Must have been an extra browser tab or early refresh or something. This can stay closed.
