### ISSUE TITLE
BUG: OverflowError when JSON serializing a dataframe/series with PeriodArray variable

### ISSUE THREAD

**Issue by bquistorff** [pandas-dev/pandas#58236] opened 2024-04-12 17:57 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
pd.DataFrame({'Date':pd.period_range("2000-01-01", periods=2)}).to_json()  # one error
pd.Series(pd.period_range("2000-01-01", periods=2)).to_json()  # another error
```

### Issue Description

Both lines give the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pandas/pandas/core/generic.py", line 2542, in to_json
    return json.to_json(
  File "/home/pandas/pandas/io/json/_json.py", line 201, in to_json
    ).write()
  File "/home/pandas/pandas/io/json/_json.py", line 252, in write
    return ujson_dumps(
OverflowError: Maximum recursion level reached
```

Note a PeriodIndex is fine (a similar bug, #46683,  was fixed).

### Expected Behavior

Valid json output.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------------

commit : 4fe49b160eace2016955878a1c10ebacc5f885f3
python : 3.10.8.final.0
python-bits : 64
OS : Linux
OS-release : 5.15.146.1-microsoft-standard-WSL2
Version : #1 SMP Thu Jan 11 04:09:03 UTC 2024
machine : x86_64
processor :
byteorder : little
LC_ALL : None
LANG : C.UTF-8
LOCALE : en_US.UTF-8
pandas : 3.0.0.dev0+706.g4fe49b160e
numpy : 1.26.4
pytz : 2024.1
dateutil : 2.9.0.post0
setuptools : 63.2.0
pip : 24.0
Cython : 3.0.10
pytest : 8.1.1
hypothesis : 6.100.1
sphinx : 7.2.6
blosc : None
feather : None
xlsxwriter : 3.2.0
lxml.etree : 5.2.1
html5lib : 1.1
pymysql : 1.4.6
psycopg2 : 2.9.9
jinja2 : 3.1.3
IPython : 8.23.0
pandas_datareader : None
adbc-driver-postgresql: None
adbc-driver-sqlite : None
bs4 : 4.12.3
bottleneck : 1.3.8
fastparquet : 2024.2.0
fsspec : 2024.3.1
gcsfs : 2024.3.1
matplotlib : 3.8.4
numba : 0.59.1
numexpr : 2.10.0
odfpy : None
openpyxl : 3.1.2
pyarrow : 15.0.2
pyreadstat : 1.2.7
python-calamine : None
pyxlsb : 1.0.10
s3fs : 2024.3.1
scipy : 1.13.0
sqlalchemy : 2.0.29
tables : 3.9.2
tabulate : 0.9.0
xarray : 2024.3.0
xlrd : 2.0.1
zstandard : 0.22.0
tzdata : 2024.1
qtpy : None
pyqt5 : None

</details>

**Comment by asishm** [comment] 2024-04-12 18:23
Duplicate of #55490

**Comment by mroeschke** [comment] 2024-04-12 19:09
Thanks for the find @asishm. Closing as a duplicate

**Closed by mroeschke** 2024-04-12 19:09 UTC
Labels: Bug, Needs Triage
