### ISSUE TITLE
Parallel processing in groupby operations

### ISSUE THREAD

**Issue by mhooreman** [pandas-dev/pandas#20817] opened 2018-04-25 09:07 UTC
Hello,

It would be nice to have the possibility to do parallel processing using `joblib` when applying something to a groupby. I'm dreaming about a `parallel` optional argument which defaults to `False`.

I think it's best to have that parallel argument while grouping

The only option I have now is to make list on the groupby results, apply a function on that list using joblib, and concatenate the results. It leads to unefficient and difficult to read code.

```python

############
# Examples #
############
data.groupby(...).fillna(..., parallel=True)
data.groupby(...).apply(..., parallel=True)
data.groupby(...).whatever(..., parallel=True)
data.groupby(...).whatever(...) # not parallel
```

**Comment by jreback** [comment] 2018-04-25 10:08
duplicate of #13111 this is non-trivial and should only have an api in pandas not an actual implementation, this is currently possible via ``dask`` (though not directly thru a pandas api).

Certainly would take a PR, but this is a fairly large effort / surface area.

**Closed by jreback** 2018-04-25 10:08 UTC
