### ISSUE TITLE
BUG: read_csv not understanding csv documents

### ISSUE THREAD

**Issue by pettzilla1** [pandas-dev/pandas#47303] opened 2022-06-10 08:34 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd
pd.read_csv("example")
```

### Issue Description

With the following valid csv file - 
"""
sep=|
col1|col2
row1|row1
row2|row2
"""
Pandas fails to understand the sep command  at the start of the file not reading it correctly 

### Expected Behavior

the  data should be read like a normal csv if the first line was missing and | replaced with , 

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by bhattbhuwan13** [comment] 2022-06-10 09:05
I saved the above contents to a csv and specified the value of `sep` parameter to `|`. The csv is read into a dataframe as required. 

```python
In [1]: import pandas as pd

In [2]: df = pd.read_csv("./example.csv", sep='|')

In [3]: df
Out[3]:
   sep= Unnamed: 1
0  col1       col2
1  row1       row1
2  row2       row2


```

**Comment by pettzilla1** [comment] 2022-06-10 09:09
That's not as required the output needed should be 
Out[5]:
   col1  col2
0  row1  row1
1  row2  row2

its a fairly common way to format a custom delaminated csv and excel reads the file correctly

**Comment by bhattbhuwan13** [comment] 2022-06-10 09:16
In pandas you need to specify separator while calling the `read_csv()` method. For your case, I think a good workaround is to skip the first row or drop it after reading.

```python
In [7]: df = pd.read_csv("./example.csv", sep='|',  skiprows=1)

In [8]: df
Out[8]:
   col1  col2
0  row1  row1
1  row2  row2

In [9]: df.columns
Out[9]: Index(['col1', 'col2'], dtype='object')
```

**Comment by phofl** [comment] 2022-06-10 10:56
Agreed with @bhattbhuwan13, labelling as usage question, since this is not supported on our side

**Comment by simonjayhawkins** [comment] 2022-06-10 12:18
> Agreed with @bhattbhuwan13, labelling as usage question, since this is not supported on our side

yep. not a bug.

> its a fairly common way to format a custom delaminated csv and excel reads the file correctly

closing but feel free to open a enhancement request with links to the specification to implement.

**Closed by simonjayhawkins** 2022-06-10 12:18 UTC
Labels: Usage Question, IO CSV, Closing Candidate
