### ISSUE TITLE
PERF: better memory footprint for intna

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#21839] opened 2018-07-10 10:41 UTC
xref #21160 

it maybe possible to change the impl of intna to be backed by

- ``bitarray`` (for mask)
- ``pyarrow`` (for both)

to improve the memory footprint of the mask

**Comment by jbrockmendel** [comment] 2021-12-21 01:57
closing as duplicate of #31293

**Closed by jbrockmendel** 2021-12-21 01:57 UTC
Labels: Performance, Dtype Conversions
