### ISSUE TITLE
Numpy Import Error

### ISSUE THREAD

**Issue by electromeow** [pandas-dev/pandas#41213] opened 2021-04-29 08:21 UTC
_Pandas frequently errors about importing NumPy. When I try to import pandas, it tries to import NumPy and creates an error.
I don't know why but when I delete venv folder and create a new venv and install pandas again, it automatically resolves but after 3-4 days, it throws an error about importing NumPy. There isn't a problem with the NumPy version because I don't manually install NumPy or any package with NumPy dependency before installing pandas. Anyway, I don't use another package using Numpy.
If you know what is the problem, please reply._

I opened this issue 1 week ago but it has closed because I didn't have that error at the time and don't have a full traceback.
I had the same error again and now I have the full traceback.

```
Traceback (most recent call last):
File "/pathtomyproject/main.py", line 22, in
import pandas as pd
File "/pathtomyproject/venv/lib/python3.9/site-packages/pandas/init.py", line 16, in
raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

    The Python version is: Python3.9 from "/pathtomyproject/venv/bin/python3"
    The NumPy version is: "1.20.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```
I didn't install any other packages or updated anything in that venv during last week. And as I mentioned above, I didn't use any library which is NumPy dependent.

**Comment by attack68** [comment] 2021-04-29 11:58
how did you install packages to your environment and have you confirmed the versions of the packages installed in your environment?

**Comment by electromeow** [comment] 2021-04-29 12:29
I installed using pip. I don't know what did you mean by "confirming versions", but let me write my versions:
pandas 1.2.4
numpy 1.20.2
six 1.15.0
pytz 2021.1
python-dateutil 2.8.1

My Environment:
Python 3.9.4
MacOS Catalina 10.15.4
I suppose it may be about C-extensions. Because of NumPy.
My Python C compiler(or what it is) is Clang 6.0

**Comment by electromeow** [comment] 2021-05-01 20:39
Nobody answers?

**Comment by MarcoGorelli** [comment] 2021-05-01 20:44
> when I delete venv folder and create a new venv and install pandas again, it automatically resolves but after 3-4 days, it throws an error about importing NumPy

Could you please try again and keep track of what you do in between when it works and when it stops working?

**Comment by electromeow** [comment] 2021-05-02 07:41
I install discord.py(dependent on aiohttp and it is dependent on so much libraries), pandas and psycopg2-binary(not dependent on any package) packages.
Then I don't install any other packages. I use pandas for easy tabular form manipulation. I access my database using psycopg2 and upload my data frames as SQL tables. I don't use the to_sql function. You can see what it does on my timetable repository.

**Comment by electromeow** [comment] 2021-05-02 07:48
But this problem also happened while an "ML with Python" education and the libraries we used on that were sklearn, pandas, and matplotlib. I suppose this problem isn't about discord.py or psycopg2.

**Comment by MarcoGorelli** [comment] 2021-05-02 10:02
OK, please make a new venv, install pandas, check it works, and then do the other steps one at a time. After each step, check you can import pandas. When it fails to import, let us know which step failed

**Comment by electromeow** [comment] 2021-05-02 10:05
ok

**Comment by rhshadrach** [comment] 2021-05-24 03:44
@electromeow - Any updates?

**Comment by ZurMaD** [comment] 2021-05-25 15:08
It looks like a numpy broken version with tensorflow, try with this

https://stackoverflow.com/a/56995002/10491422

```bash
pip install numpy --upgrade
```

**Comment by electromeow** [comment] 2021-05-30 14:39
This time it didn't happen. I suppose that's about using it. When I test it on a clear venv it doesn't happen. But when I add it to the project, the problem happens regularly each few days.

**Comment by MarcoGorelli** [comment] 2021-05-30 15:33
> the problem happens regularly each few days.

What do you do in those days between when you add pandas to the project and when it stops working?

**Comment by mroeschke** [comment] 2021-08-20 02:42
Thanks for the report, but from the sporadic success of installation it doesn't appear that this is a pandas specific issue so closing. Happy to reopen if you could pinpoint this problem to pandas.

**Closed by mroeschke** 2021-08-20 02:42 UTC
Labels: Bug, Build
