### ISSUE TITLE
BUG: wrong join with nan in multiindex

### ISSUE THREAD

**Issue by gertjac** [pandas-dev/pandas#34035] opened 2020-05-06 20:52 UTC
- [ ] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
df1 = pd.DataFrame([['1.','3.','4.'],
                    ['1.',pd.NA,'5.']],
                   columns=['i1', 'i2', 'v1']).set_index(['i1', 'i2'])
df2 = pd.DataFrame([['1.',pd.NA,'6.']],
                   columns=['i1', 'i2', 'v2']).set_index(['i1', 'i2'])
df1.join(df2, how='outer').loc[('1.', '3.')]['v2']
```

#### Problem description

the result is '6.'
so, the value of v2 in df2 appears as the value of v2 for index ('1.', '3.') after joining
this is unexpected for me, because the index is different from that in df2 ('1.',pd.NA)
this problem is also there with np.nan instead of pd.NA
and also in version 0.25.3 (when values are strings, but not when values are floats!)

#### Expected Output

NaN

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None
 
pandas           : 1.0.3
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.12
pytest           : 5.0.1
hypothesis       : None
sphinx           : 2.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.1.8
lxml.etree       : 4.3.4
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : 7.6.1
pandas_datareader: None
bs4              : 4.7.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.3.4
matplotlib       : 3.1.0
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 2.6.2
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.3.5
tables           : 3.5.2
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.8
numba            : 0.44.1

</details>

**Comment by gertjac** [comment] 2020-05-22 09:34
Just discovered that this bug has been already reported: https://github.com/pandas-dev/pandas/issues/29252

**Comment by TomAugspurger** [comment] 2020-09-04 13:12
Thanks. Closing as a duplicate of #29252.

**Closed by TomAugspurger** 2020-09-04 13:12 UTC
Labels: Bug, Needs Triage
