### ISSUE TITLE
pd.core.groupby.GroupBy docstrings missing endline

### ISSUE THREAD

**Issue by mrocklin** [pandas-dev/pandas#26232] opened 2019-04-28 16:53 UTC
```python
In [1]: import pandas as pd

In [2]: pd.core.groupby.GroupBy.min?
Signature: pd.core.groupby.GroupBy.min(self, **kwargs)
Docstring:
Compute min of group values
See Also   # <<<<-------- There should be an extra line between this and the line above
--------
pandas.Series.groupby
pandas.DataFrame.groupby
pandas.Panel.groupby
File:      ~/miniconda/envs/dev/lib/python3.7/site-packages/pandas/core/groupby/groupby.py
Type:      function
```

I tried going in to fix this, but it seems that these are auto-generated somewhere, so I decided to raise an issue instead.

**Comment by WillAyd** [comment] 2019-04-29 00:54
Thanks but closing as a duplicate of #24071

@alexcwatt has a PR in progress to fix

**Closed** 2019-04-29 00:55 UTC
Labels: Docs, Duplicate

**Comment by mrocklin** [comment] 2019-04-29 01:01
Thanks for the pointer!  My apologies for the duplicate.
