### ISSUE TITLE
"Function does not reduce" for multiindex, but works fine for single index.

### ISSUE THREAD

**Issue by frlnx** [pandas-dev/pandas#4293] opened 2013-07-19 16:10 UTC
When I use pd.Series.tolist as a reducer with a single column groupby, it works.
When I do the same with multiindex, it does not.

It seems the "fast" cython groupby function, which has no quarrel with reducing into lists, throws an exception if the index is "complex", which seem to mean multiindex. When that exception is caught, the groupby function falls back to the "pure_python" groupby, which throws a new exception if the reducing function returns a list.

Is this a bug or is there some logic to this which is not apparent to me?

Reproduce:

```
import pandas as pd
s1 = pd.Series(randn(5), index=['a', 'b', 'c', 'd', 'e'])
df = pd.DataFrame([s1], columns=['a', 'b', 'c', 'd', 'e'])
for i in range(0,10):
    s1 = pd.Series(randn(5), index=['a', 'b', 'c', 'd', 'e'])
    df2 = pd.DataFrame([s1], columns=['a', 'b', 'c', 'd', 'e'])
    df = pd.concat([df, df2])
df['gk'] = 'foo'
df['gk2'] = 'bar'

# This works.
df.groupby(['gk']).agg(pd.Series.tolist)

# This does not.
df.groupby(['gk', 'gk2']).agg(pd.Series.tolist)
```

**Comment by florianverhein** [comment] 2015-10-22 19:15
Just ran into this too. Rather than being forced to collect the unique values in a column into a string, I would have liked them to be collected into a list (e.g. for use later). 

reduce in python is really a fold left, and there's absolutely nothing wrong with a fold left returning a collection. e.g. the identity reduction for a list `s` is `reduce(lambda x,y: x+[y],s,[])`, which fails in `pd.agg`.

'reducing' the quantity of data is not a requirement of reduce (functionally speaking). 
That argument also fails considering that `str` works in `pd.agg`.

**Comment by nbateshaus** [comment] 2016-06-22 01:46
I run into this working with shredded (EAV) data. Often, there are multiple values for a single column. Take data representing authors on articles:
```
recordId,attributeName,value
1,title,"Map-Reduce Extensions and Recursive Queries"
1,author,"Foto N. Afrati"
1,author,"Vinayak Borkar"
1,author,"Michael Carey"
1,author,"Neoklis Polyzotis"
1,author,"Jeffrey D. Ullman"
```
This data is coming from a 3rd party, and I'd like to fix it so I can work with it. I want to create a 3-level index of ['recordId', 'attributeName', 'instance'] with a single column for the values. The way to create 'instance' is to:
1. `eav.set_index(['recordId', 'attributeName'], inplace=True)` to promote recordId and attributeName to indexes; then
2. `s=eav.groupby(level=['recordId', 'attributeName']).agg(pd.Series.tolist)` to aggregate into to a Series of lists of values, then 
3. use `t=pd.DataFrame(s.tolist(), s.index)` to split into columns with numeric labels, then
4. use `t.stack()` to create the 3rd level index.

Sadly, this doesn't work because `_aggregate_series_pure_python(self, obj, func)` has an explicit exclusion for the case when the aggregator returns a list for the first group.

Many other data processing platforms have recognized the utility of aggregating into lists: PostgreSQL has `array_agg`; Spark has `collect_list()`; MySQL has `group_concat`; etc.

The exclusion is even less sensical when you consider that many methods such as `Series.str.split()` will create columns of lists, but the exclusion in `_aggregate_series_pure_python(self, obj, func)` prevents creation of list values when grouping.

**Comment by TomAugspurger** [comment] 2016-06-22 02:39
@nbateshaus what's your desired output there? Is it

```python
In [12]: df['instance'] = df.groupby(['recordId', 'attributeName']).value.cumcount()

In [13]: df.set_index(['recordId', 'attributeName', 'instance'])
Out[13]:
                                                                       value
recordId attributeName instance
1        title         0         Map-Reduce Extensions and Recursive Queries
         author        0                                      Foto N. Afrati
                       1                                      Vinayak Borkar
                       2                                       Michael Carey
                       3                                   Neoklis Polyzotis
                       4                                   Jeffrey D. Ullman

```

I know that nested data is important, but the building-blocks aren't in place for pandas to support it well at the moment.

**Comment by nbateshaus** [comment] 2016-06-22 13:04
Yes, that's the output I want. Assuming I sort by ['e','a'] first, this is probably faster, too. It is still very convenient to be able to create list values.

Looking at the history of this restriction, it looks like it was accidentally introduced by a transcription error in f3c0a081e2cfc8e073f8461cac5c242d0e4219d0 - at the time, it was an assertion, and it went from
```
assert(not (isinstance(res, list) and len(res) == len(self.dummy)))
```
where, as far as I can tell, `dummy` is uninitialized, to
```
assert(not isinstance(res, list))
```
The original assertion was added without comment in 71e9046c52246535d4db1f350e82c3a84d748f88, in response to #612 "Pure python multi-key groupby can't handle non-numeric results". Which reveals another oddity: groupby().agg(pd.Series.tolist) works fine for single-key groupings; it only fails for multi-key groupings.
```
>>> eav.groupby(['attributeName']).agg(pd.Series.tolist)
                      recordId  \
attributeName                    
author         [1, 1, 1, 1, 1]   
title                      [1]   

                                                           value  
attributeName                                                     
author         [Foto N. Afrati, Vinayak Borkar, Michael Carey...  
title              [Map-Reduce Extensions and Recursive Queries]  
>>> eav.groupby(['recordId', 'attributeName']).agg(pd.Series.tolist)
Traceback (most recent call last):
  File "/Users/nik/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/groupby.py", line 1863, in agg_series
    return self._aggregate_series_fast(obj, func)
  File "/Users/nik/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/groupby.py", line 1868, in _aggregate_series_fast
    func = self._is_builtin_func(func)
AttributeError: 'BaseGrouper' object has no attribute '_is_builtin_func'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nik/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/groupby.py", line 3597, in aggregate
    return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)
  File "/Users/nik/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/groupby.py", line 3122, in aggregate
    return self._python_agg_general(arg, *args, **kwargs)
  File "/Users/nik/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/groupby.py", line 777, in _python_agg_general
    result, counts = self.grouper.agg_series(obj, f)
  File "/Users/nik/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/groupby.py", line 1865, in agg_series
    return self._aggregate_series_pure_python(obj, func)
  File "/Users/nik/anaconda/envs/python3/lib/python3.5/site-packages/pandas/core/groupby.py", line 1899, in _aggregate_series_pure_python
    raise ValueError('Function does not reduce')
ValueError: Function does not reduce
```

**Comment by toobaz** [comment] 2018-05-18 07:33
The example by @frinx seems to now work fine, _and_ @bobhaffner [said](https://github.com/pandas-dev/pandas/pull/18354#issuecomment-346960868) that #18354 "might" close this. So assuming this is solved. @nbateshaus please feel free to provide a reproducible example if this is still an issue.

**Closed by toobaz** 2018-05-18 07:33 UTC
Labels: Dtypes, Groupby, MultiIndex
