### ISSUE TITLE
BUG: Behaviour of numeric_only in aggregation methods like sum depends on length of dataframe.

### ISSUE THREAD

**Issue by michaelneururer** [pandas-dev/pandas#41351] opened 2021-05-06 13:34 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python

df = pd.DataFrame({'non_numeric': 10000*[pd.Timedelta(10)], 'numeric': 10000*[1]})
# Summing over axis 1 with numeric_only=True works as expected
assert_series_equal(df.sum(axis=1, numeric_only=True), df.numeric, check_names=False)
# Summing with the default numeric_only=None only works if df has <= 8192 = 2**13 rows
sample = df.sample(8192)
assert_series_equal(sample.sum(axis=1), sample.numeric, check_names=False)
# Summing over the whole dataframe we get a SystemError
df.sum(axis=1)
# The following also produces a SystemError
sample['numeric_2'] = 1
sample.sum(axis=1)
# The following does not produce a SystemError
sample.sample(1).sum(axis=1)

```

#### Problem description

In previous pandas versions the last line does not throw a TypeError. The default numeric_only=None will only sum over the numeric columns of the dataframe. 
In pandas 1.2.4 this is the case if the length of the dataframe is <= 8192 = 2**13. As soon as the length exceeds 8192 we get a SystemErrorbecause it tries to sum a Timedelta column and an int column. We also get a SystemError when df has more than one numeric column. Then the sum only works if the length of the dataframe is 1

The behaviour of sum is the same for other aggregation methods like mean.

#### Expected Output

I expect df.sum(axis=1) to return a series whose entries are the sum of the numeric columns of the dataframe along the axis 1 as is the case for dataframes of length <= 8192.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.9.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-693.5.2.el7.x86_64
Version          : #1 SMP Fri Oct 20 20:32:50 UTC 2017
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en.UTF-8
LOCALE           : None.None

pandas           : 1.2.4
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by phofl** [comment] 2021-05-06 13:42
Hi, thanks for your report.

Can you show the Traceback? Can not reproduce on master. I am getting a SystemError on 1.2.4

**Comment by michaelneururer** [comment] 2021-05-06 13:44
Ah, apologies, it is indeed a SystemError. I corrected my description.
Traceback:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: unsupported operand type(s) for +: 'Timedelta' and 'int'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-37-b02ad72dbe3f> in <module>
----> 1 sample.sum(axis=1)

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/generic.py in sum(self, axis, skipna, level, numeric_only, min_count, **kwargs)
  11069             **kwargs,
  11070         ):
> 11071             return NDFrame.sum(
  11072                 self, axis, skipna, level, numeric_only, min_count, **kwargs
  11073             )

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/generic.py in sum(self, axis, skipna, level, numeric_only, min_count, **kwargs)
  10789         **kwargs,
  10790     ):
> 10791         return self._min_count_stat_function(
  10792             "sum", nanops.nansum, axis, skipna, level, numeric_only, min_count, **kwargs
  10793         )

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/generic.py in _min_count_stat_function(self, name, func, axis, skipna, level, numeric_only, min_count, **kwargs)
  10771                 name, axis=axis, level=level, skipna=skipna, min_count=min_count
  10772             )
> 10773         return self._reduce(
  10774             func,
  10775             name=name,

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/frame.py in _reduce(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)
   8865 
   8866         try:
-> 8867             result = func(values)
   8868 
   8869         except TypeError:

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/frame.py in func(values)
   8815         def func(values: np.ndarray):
   8816             # We only use this in the case that operates on self.values
-> 8817             return op(values, axis=axis, skipna=skipna, **kwds)
   8818 
   8819         def blk_func(values):

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/nanops.py in _f(*args, **kwargs)
     71             try:
     72                 with np.errstate(invalid="ignore"):
---> 73                     return f(*args, **kwargs)
     74             except ValueError as e:
     75                 # we want to transform an object array

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/nanops.py in new_func(values, axis, skipna, mask, **kwargs)
    392             mask = isna(values)
    393 
--> 394         result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
    395 
    396         if datetimelike:

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/pandas/core/nanops.py in nansum(values, axis, skipna, min_count, mask)
    558         dtype_sum = np.float64
    559 
--> 560     the_sum = values.sum(axis, dtype=dtype_sum)
    561     the_sum = _maybe_null_out(the_sum, axis, mask, values.shape, min_count=min_count)
    562 

~/anaconda-box/envs/pandas12/lib/python3.9/site-packages/numpy/core/_methods.py in _sum(a, axis, dtype, out, keepdims, initial, where)
     45 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
     46          initial=_NoValue, where=True):
---> 47     return umr_sum(a, axis, dtype, out, keepdims, initial, where)
     48 
     49 def _prod(a, axis=None, dtype=None, out=None, keepdims=False,

SystemError: <cyfunction _binary_op_method_timedeltalike.<locals>.f at 0x7f9df83b6d40> returned a result with an error set

**Comment by phofl** [comment] 2021-05-06 13:45
Ok, can reproduce that. Since this is fixed on master we may need a test here. Would you be interested in submitting a pr?

**Comment by michaelneururer** [comment] 2021-05-06 13:48
Yes, I can do that. Tonight if you can wait that long.

**Comment by phofl** [comment] 2021-05-06 13:50
Great! This is not urgend :)

**Comment by michaelneururer** [comment] 2021-05-09 12:14
take

**Comment by Anupam-USP** [comment] 2021-06-03 06:26
Hey @michaelneururer, you still working on this issue?

**Comment by michaelneururer** [comment] 2021-06-07 08:32
Hi, yes sorry. I wrote the code but I haven't built pandas from source yet to run the tests... will get to it this week.

**Comment by simonjayhawkins** [comment] 2021-08-17 10:08
from https://github.com/pandas-dev/pandas/pull/41932#issuecomment-860040209

> The failure I reported in #41351 depends on the numpy version used (it works from numpy version 1.20.2).

**Comment by rhshadrach** [comment] 2024-01-18 22:25
Now that `numeric_only=None` has been removed, I think there is nothing more to do here.

**Closed** 2024-10-05 13:54 UTC
Labels: Bug, Timedelta, Reduction Operations, Closing Candidate
