### ISSUE TITLE
BUG: `DataFrame.groupby().apply()` with single group results in wrong output shape

### ISSUE THREAD

**Issue by peanutfun** [pandas-dev/pandas#53163] opened 2023-05-10 10:06 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame.from_dict({"A": [1, 1, 1, 1], "B": [1, 2, 2, 3]})

# Works: Returns the A column as series
assert(df.groupby("B", group_keys=False).apply(lambda x: x["A"]).equals(df["A"]))

# Fails: Returns a data frame with A column as row and weird indexing
assert(df.groupby("A", group_keys=False).apply(lambda x: x["A"]).equals(df["A"]))
```

### Issue Description

`DataFrame.groupby().apply()` returns a different output shape if the values in the grouped label are unique, i.e., if there is only one group. In my simple example above, I group the data frame by the values of either column A or B, then call apply to simply return the A column. I expect the result to be the original A column as series. This is the case if there are multiple groups. However, with only one group, the result is a data frame:

```python
# Expected behavior with multiple groups
>>> df = pd.DataFrame.from_dict({"A": [1, 1, 1, 1], "B": [1, 2, 2, 3]})
>>> df.groupby("B", group_keys=False).apply(lambda x: x["A"])
0    1
1    1
2    1
3    1
Name: A, dtype: int64

# Erroneous behavior with single group
>>> out = df.groupby("A", group_keys=False).apply(lambda x: x["A"])
>>> print(out)
A  0  1  2  3
A            
1  1  1  1  1
>>> print(out.columns)
Index([0, 1, 2, 3], dtype='int64', name='A')
>>> print(out.index)
Index([1], dtype='int64', name='A')

# Behavior is independent from which column is returned
>>> out = df.groupby("A", group_keys=False).apply(lambda x: x["B"])  # Now return B
>>> print(out)
B  0  1  2  3
A            
1  1  2  2  3
>>> print(out.columns)
Index([0, 1, 2, 3], dtype='int64', name='B')
>>> print(out.index)
Index([1], dtype='int64', name='A')
```

### Expected Behavior

The result of `DataFrame.groupby().apply()` does not change shape depending on the number of groups,

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.11.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 22.4.0
Version          : Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 2.0.1
numpy            : 1.24.3
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.13.2
pandas_datareader: None
bs4              : 4.12.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by peanutfun** [comment] 2023-05-11 09:17
@rhshadrach Thanks for the reply!

The above example is stripped down to demonstrate the issue. What I actually wanted to do is something like
```python
pd.DataFrame.from_dict({"A": [1, 1, 1, 1], "B": [1, 2, 2, 3]}).groupby("B").apply(
    lambda x: x["A"] / x["A"].sum() * x["B"].sum()
)
```
Following your comment, I think found a workaround using `transform`:
```python
df = pd.DataFrame.from_dict({"A": [1, 1, 1, 1], "B": [1, 2, 2, 3]})
group = groupby("B")
group["A"].transform(lambda x: x / x.sum()) * group["B"].transform(lambda x: x.sum())
```

Feel free to close this issue if there is no obvious way to resolve this. I certainly know too little of the pandas code base to come up with a solution for apply.

**Comment by rhshadrach** [comment] 2023-05-11 11:33
You can use `.transform('sum')`; it will be much faster. No need to supply a lamba here.

I believe this is a duplicate, I'll track down the other issue and then close.

**Comment by rhshadrach** [comment] 2023-05-12 09:19
Duplicate of #42749

**Closed by rhshadrach** 2023-05-12 09:19 UTC
Labels: Bug, Groupby, Apply
