### ISSUE TITLE
pd.to_datetime() Error in MacOS - TypeError(f"dtype {data.dtype} cannot be converted to datetime64[ns]") TypeError: dtype timedelta64[ns] cannot be converted to datetime64[ns]

### ISSUE THREAD

**Issue by CaioEuzebio** [pandas-dev/pandas#31743] opened 2020-02-06 12:05 UTC
#### Function Error in  MacOS

```python
df = pd.read_csv('filemane.csv', encoding='latin-1')

df1['ProcessFinishTime'] = pd.to_datetime(df1['ProcessFinishTime'],errors='ignore')
df1['ProcessStartTime'] = pd.to_datetime(df1['ProcessStartTime'],errors='ignore')
```

#### Problem description

Hi Guys,

This is a problem that a faced in MacOS only about DateTime, I trying to convert format (12:54:58)
in to DateTime.

It run correctly in Windows(10) and Linux(ubuntu) as well, however, in MacOS i faced this problem that returns an error message below:

```
raise TypeError(f"dtype {data.dtype} cannot be converted to datetime64[ns]")
TypeError: dtype timedelta64[ns] cannot be converted to datetime64[ns]
``` 

I search for and for while it's not cleary to me the reason for this error happens.

And my questions is:

**1**- This issue is particular for MAcOS?

**2**2 - I try to replace pd.to_datetime() for pd.to_timedelta(), however pd.to_datetime is too better.

**3**- I try to replace pd.to_datetime() for pd.to_timedelta(), however pd.to_datetime is too better.

Below is the documentation that i follow.:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

Using latest version in both systems.

**Comment by jorisvandenbossche** [comment] 2020-02-06 15:46
Can you provide a reproducible example? (https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) For example, create a small dataframe with some dummy data that shows the problem.

**Comment by MarcoGorelli** [comment] 2020-02-17 17:06
Closing due to lack of reproducible example (we don't have access to `'filemane.csv'`), but feel free to reopen if you write one

**Closed by MarcoGorelli** 2020-02-17 17:06 UTC
Labels: Needs Info
