### ISSUE TITLE
BUG: pd.read_sql returns wrong columns name for specific query

### ISSUE THREAD

**Issue by shentianhao1993** [pandas-dev/pandas#46876] opened 2022-04-26 13:46 UTC
### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
from sqlalchemy import create_engine
import pandas as pd

uri = 'clickhouse://user:password@host:8123'
engine = create_engine(uri)

sql = """
         SELECT 
             partition,
             sum(rows) AS rows,
             formatReadableSize(sum(data_uncompressed_bytes)) AS original_size,
             formatReadableSize(sum(data_compressed_bytes)) AS compressed_size,
             round((sum(data_compressed_bytes) / sum(data_uncompressed_bytes)) * 100, 0) AS compress_rate
         FROM system.parts
         WHERE (database IN ('system')) AND (table IN ('query_log')) AND (partition LIKE '2022-04-%%')
         GROUP BY partition
         ORDER BY partition ASC
         """

df = pd.read_sql(sql, con=cengine)
print(df)
```

### Issue Description

   2022-04-22   10124   18.19 MiB   1.11 MiB  6
0  2022-04-24   28892   51.88 MiB   3.16 MiB  6
1  2022-04-25   28800   51.73 MiB   3.14 MiB  6
2  2022-04-26  141150  342.90 MiB  19.50 MiB  6

### Expected Behavior

    partition   rows   original_size   compressed_size  compress_rate
0   2022-04-22   10124   18.19 MiB   1.11 MiB  6
1  2022-04-24   28892   51.88 MiB   3.16 MiB  6
2  2022-04-25   28800   51.73 MiB   3.14 MiB  6
3  2022-04-26  141150  342.90 MiB  19.50 MiB  6

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 166 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.3 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.10.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.3.24
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.54.1

</details>

**Comment by ParfaitG** [comment] 2022-04-27 03:48
Depending on which connector, this looks to be a known [issue](https://stackoverflow.com/questions/65627583/right-way-to-implement-pandas-read-sql-with-clickhouse) for [clickhouse-sqlachemy](https://github.com/xzkostyan/clickhouse-sqlalchemy) with user fixes such as `FORMAT TabSeparatedWithNamesAndTypes` at end of SQL query or using `clickhouse+native://...` in engine connection string.

For [sqlachemy-clickhouse](https://github.com/cloudflare/sqlalchemy-clickhouse), issue may not be [reproducible](https://stackoverflow.com/a/61250809/1422451). If so, what happens with running your raw SQL with engine cursor? Check returned columns in `cursor.description`:

```python
with engine.connect() as con:
    cur = con.cursor()
    cur.execute(sql)

    print(cur.description)
```

**Comment by mroeschke** [comment] 2022-08-11 18:28
Appears to be an upstream issue with an upstream library and not directly due to pandas. Closing, but if you are able to provide more information or try the suggestions above suggesting this is a pandas issue, we can reopen.

**Closed by mroeschke** 2022-08-11 18:28 UTC
Labels: Bug, IO SQL, Needs Triage
