### ISSUE TITLE
Period - Frequency conversion extremely slow

### ISSUE THREAD

**Issue by stefansimik** [pandas-dev/pandas#27390] opened 2019-07-14 22:10 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd

# Create series with 372,363 daily periods
series_day = pd.Series(pd.period_range(start='1000-01-01', end='2019-06-30', freq='D'))

# Convert daily periods to monthly periods
# HERE IS THE PROBLEM - CONVERSION IS UNUSUALLY SLOW
series_month = series_day.apply(lambda d: d.asfreq('M'))
```
#### Problem description

Conversion between Periods is unusually slow operation.
(I mean conversion between Period frequencies like:  daily period -> monthly period)

It can easily take longs hours to convert 100M periods (from daily -> monthly frequency) on modern i7 CPU.
Compared to other common date/time operations on same dataset, which can finish in seconds / or max a few minutes, conversion period frequencies takes extremely long time.

**Result of :**
```
%%timeit -r 3
series_month = series_day.apply(lambda d: d.asfreq('M'))
```
was:
`1min 51s ± 3.74 s per loop (mean ± std. dev. of 3 runs, 1 loop each)`

When ~350k conversions takes 2 mins, then 100M conversions takes above 7 hours.

**So let's compare:**
- conversion from datetime[ns] -> daily/monthly Period - runs very quickly
- conversion from Period -> Period - runs extremely slow

There really has to be some unusually slow or inefficient code in the period conversion,
which slows down the conversion process.

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.24.1
pytest: None
pip: 19.0.1
setuptools: 40.8.0
Cython: None
numpy: 1.15.4
scipy: 1.2.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml.etree: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by WillAyd** [comment] 2019-07-14 22:14
Have you tried using the `dt` accessor? This returns almost instantaneously for me:

```python
series_day.dt.asfreq('M')
```

Apply is not a vectorized solution (essentially a for loop) so performance of that will always lag behind vectorized ops that pandas offers

**Comment by jreback** [comment] 2019-07-14 22:15
why would you ever do an apply like this? of course the problem is that you are operating element by element 

there are many things u can do such as .asfreq in a DTI and resample

**Comment by stefansimik** [comment] 2019-07-14 22:31
Oh, guys, that was quick. Thank you!
 I was not aware of this `dt` accessor, but it works almost immediately.

Is it possible, that it is undocumented?
When I tried to search for `dt.asfreq` on page [doc page](https://pandas.pydata.org/pandas-docs/stable/reference/series.html#time-series-related), nothing was found.

**Comment by WillAyd** [comment] 2019-07-14 22:45
Here's the link in the docs:

https://pandas.pydata.org/pandas-docs/stable/getting_started/basics.html#dt-accessor

If you can think of any ways to improve we almost always accept PRs to improve documentation so let us know.

Closing this issue for now though

**Closed by WillAyd** 2019-07-14 22:45 UTC
