### ISSUE TITLE
crash using HDFStore in a loop

### ISSUE THREAD

**Issue by tacaswell** [pandas-dev/pandas#16693] opened 2017-06-13 20:57 UTC
#### Code Sample, a copy-pastable example if possible

```python

import pandas as pd
import numpy as np
import h5py  # unused, but checking if libraries are stepping on each other

new_chi1s = pd.DataFrame({'a': np.linspace(0, 1, 100)})

for j in range(100000):
    with pd.HDFStore('/tmp/chi1_angle.h5', 'a') as chi1s:
        chi1s.append('df', new_chi1s) 
```
#### Problem description

This was originally posted at https://github.com/h5py/h5py/issues/895 by @mkhoshle but this is either a pandas or pytables bug.  Gross-posting here as the top interface 

```python
original exception:HDF5 error back trace

  File "H5Dio.c", line 271, in H5Dwrite
    can't prepare for writing data
  File "H5Dio.c", line 352, in H5D__pre_write
    can't write data
  File "H5Dio.c", line 795, in H5D__write
    can't write data
  File "H5Dchunk.c", line 2006, in H5D__chunk_write
    unable to read raw data chunk
  File "H5Dchunk.c", line 2900, in H5D__chunk_lock
    unable to read raw data chunk
  File "H5Fio.c", line 120, in H5F_block_read
    read through metadata accumulator failed
  File "H5Faccum.c", line 263, in H5F__accum_read
    driver read request failed
  File "H5FDint.c", line 207, in H5FD_read
    addr overflow, addr = 3001503, size=75, eoa=3000871

End of HDF5 error back trace

Internal error modifying the elements (H5ARRAYwrite_records returned errorcode -6)

```

Tracing back, we go to https://github.com/PyTables/PyTables/blob/master/tables/hdf5extension.pyx#L1760 to https://github.com/PyTables/PyTables/blob/master/src/H5ARRAY.c#L344  to https://support.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-Write 

so something is broken at a low level.  My knee-jerk guess is that the context manager is not fully flushing to disk on exit and the file is being re-opened in an odd state or there is some race condition on pytables global state managing the file handle.

**Comment by jreback** [comment] 2017-06-13 22:57
would need to show versions and an actual repro (e.g. one that crashes). Pytables 3.3.0 has been stable for quite some time (and actually 3.2 IIRC as well).

**Comment by mkhoshle** [comment] 2017-06-14 01:25
Here is the version of the packages I am using:
```
Summary of the h5py configuration
---------------------------------

h5py    2.7.0
HDF5    1.8.18
Python  2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.12.1
```

**Comment by jreback** [comment] 2017-06-14 01:27
h5py is not supported

**Comment by jreback** [comment] 2017-06-14 01:27
show the PyTables version

**Comment by jreback** [comment] 2017-06-14 01:28
you also cannot operate with a file opened with h5py at all

it MUST be operated by PyTables

**Comment by mkhoshle** [comment] 2017-06-14 02:12
Here is the version of PyTable in my system:
```
In [1]: import tables

In [2]: tables.__version__
Out[2]: '3.4.2'
```

**Comment by mkhoshle** [comment] 2017-06-14 02:19
In another I used the following and it worked perfectly, but still I do not understand why the above version fails:
```
new_chi1s = df
chi1s = pd.HDFStore(datastore[sim.uuid][hdf5name].abspath, 'a', complib=str("zlib"), complevel=5) 
chi1s.put('table', new_chi1s, append=True, format='table', data_columns=new_chi1s.columns)
chi1s.close()
```

**Comment by jreback** [comment] 2017-06-14 10:05
closing as not reproducible. If you can have a completely self-contained example that reproduces great. HDFStore is not in any way compatible with h5py. You cannot use them in the same file, nor have any interaction. Sure it might work, but is not supported.

**Closed by jreback** 2017-06-14 10:05 UTC
Labels: Can't Repro, IO HDF5

**Comment by mkhoshle** [comment] 2017-06-14 17:49
Sorry I am a little bit confused. In the above example I am using HDFStore for appending new dataframes into a .h5 file. When I look at the documentation for pd.HDFStore, even in the example it is using HDFStore with .h5 file. If this is not compatible so what is the purpose of having HDFStore?

```
Examples
--------
>>> from pandas import DataFrame
>>> from numpy.random import randn
>>> bar = DataFrame(randn(10, 4))
>>> store = HDFStore('test.h5')
>>> store['foo'] = bar   # write to HDF5
>>> bar = store['foo']   # retrieve
>>> store.close()
```
Can you please give me an example of what you mean? I do not know how can I use pytables for adding dataframes to h5 files?

**Comment by TomAugspurger** [comment] 2017-06-14 18:24
With the original code, does `'/tmp/chi1_angle.h5'` exist before the first loop? I assumed it did since you're opening it in append mode (and I further assumed it was created by h5py, like Jeff). But there may be a bug here if it's newly created by pandas.

What iteration does it typically fail on? Mines at 28,000 and still going.

**Comment by tacaswell** [comment] 2017-06-14 18:37
I could not get it to crash and the file is created by pandas / pytables (I think h5py is a complete distraction here).

**Comment by mkhoshle** [comment] 2017-06-14 19:07
@TomAugspurger In my case, no it did not. The file is created at the first iteration in the loop. Here is the [https://github.com/h5py/h5py/issues/895](url) to the original issue I created.

**Comment by TomAugspurger** [comment] 2017-06-14 19:13
@mkhoshle what version of pandas? I wasn't able to get a crash either.

**Comment by mkhoshle** [comment] 2017-06-14 19:17
Here is the version of Panda: 
```
In [5]: pd.__version__
Out[5]: u'0.20.2'
```

**Comment by jreback** [comment] 2017-06-15 10:39
@mkhoshle your issues is that you are mixing a file opened by ``h5py`` with one by ``PyTables/pandas``. These dont' work.

**Comment by mkhoshle** [comment] 2017-06-16 02:16
@jreback I think I get your point now. Do you mean that in the following example, the usage of HDFStore in the append mode is causing the overlapping between the h5py and pytables? Because even when I tried this: 
```
new_chi1s = df
chi1s = pd.HDFStore(datastore[sim.uuid][hdf5name].abspath, 'a', complib=str("zlib"), complevel=5) 
chi1s.put('table', new_chi1s, append=True, format='table', data_columns=new_chi1s.columns)
chi1s.close()
```

At first, I thought it is working but it failed with the same error. But when I did the following and tested it, it worked, and I think it is because in the following example there is no overlapping of h5py and pytables. 
```
new_chi1s = df
chi1s = pd.HDFStore(datastore[sim.uuid][hdf5name].abspath) 
chi1s['df{}'.format(i)] = new_chi1s
chi1s.close()
```

Thanks,

**Comment by GGsamiku** [comment] 2019-04-19 01:21
@mkhoshle Have you encountered this bug later since you use the code ?
```
new_chi1s = df
chi1s = pd.HDFStore(datastore[sim.uuid][hdf5name].abspath) 
chi1s['df{}'.format(i)] = new_chi1s
chi1s.close()
```
I got the same bug and my code is just like
```
with pd.HDFStore(xx) as st:
    st.put(key, data)
```
the process get MemoryError (Hard disk memory is really exhausted), but after I quit the process, I can not open this HDF file again
