### ISSUE TITLE
concat ignore_index option doesnt work

### ISSUE THREAD

**Issue by Niroznak** [pandas-dev/pandas#31823] opened 2020-02-09 15:00 UTC
#### Code Sample, a copy-pastable example if possible

```python
pd.concat([df_general.iloc[:,2:],df],ignore_index=True).fillna(method='ffill')
tried vs.
pd.concat([df_general.iloc[:,2:],df],ignore_index=False).fillna(method='ffill')



```
#### Problem description
concatenating the tables leaves 1 partially empty row that shouldnt be there, on pandas version version (0.23.4) it didn't happen.
this happened after upgrading pandas to below version.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 7
machine          : AMD64
processor        : Intel64 Family 6 Model 30 Stepping 4, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.1
numpy            : 1.16.3
pytz             : 2018.5
dateutil         : 2.7.3
pip              : 20.0.2
setuptools       : 41.0.1
Cython           : 0.28.5
pytest           : 3.8.0
hypothesis       : None
sphinx           : 1.7.9
blosc            : None
feather          : None
xlsxwriter       : 1.1.0
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 6.5.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.2.5
matplotlib       : 2.2.3
numexpr          : 2.6.8
odfpy            : None
openpyxl         : 2.5.6
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 3.8.0
pyxlsb           : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : 1.2.11
tables           : 3.4.4
tabulate         : None
xarray           : None
xlrd             : 1.1.0
xlwt             : 1.3.0
xlsxwriter       : 1.1.0
numba            : 0.39.0
</details>

**Comment by dsaxton** [comment] 2020-02-09 20:35
Can you try to create a small reproducible example that demonstrates the issue since others don't have access to your data?

**Comment by simonjayhawkins** [comment] 2020-03-31 11:54
> Can you try to create a small reproducible example that demonstrates the issue since others don't have access to your data?

@Niroznak closing for now as not actionable.

**Comment by ATanalytics** [comment] 2020-04-22 16:33
Hi Guys, I would like you to check this issue, since I had a hard time trying to fix it.
Here a small example, I took from stackoverflow https://stackoverflow.com/questions/32801806/pandas-concat-ignore-index-doesnt-work/32802014#32802014

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 2, 3,4])

df2 = pd.DataFrame({'A1': ['A4', 'A5', 'A6', 'A7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D2': ['D4', 'D5', 'D6', 'D7']},
                    index=[ 5, 6, 7,3])
dfs = [df1,df2]
df = pd.concat( dfs,axis=1,ignore_index=True)     
 by running this I get:
dfs = [df1,df2]
df = pd.concat( dfs,axis=1,ignore_index=True)     

  0   A0   B0   D0  NaN  NaN  NaN  
 2   A1   B1   D1  NaN  NaN  NaN    
 3   A2   B2   D2   A7   C7   D7   
 4   A3   B3   D3  NaN  NaN  NaN  
 5  NaN  NaN  NaN   A4   C4   D4  
 6  NaN  NaN  NaN   A5   C5   D5  
 7  NaN  NaN  NaN   A6   C6   D6  

But the expected output should be a 4 by 6 DF.

I faced the same issue using my data.
Please let me know if this is something you guys can check.

Thanks,

Alfonso

**Comment by Rcubes** [comment] 2020-04-22 16:37
Hi Guys, I would like you to check this issue, since I had a hard time trying to fix it.
Here a small example, I took from stackoverflow https://stackoverflow.com/questions/32801806/pandas-concat-ignore-index-doesnt-work/32802014#32802014

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3'],
'D': ['D0', 'D1', 'D2', 'D3']},
index=[0, 2, 3,4])

df2 = pd.DataFrame({'A1': ['A4', 'A5', 'A6', 'A7'],
'C': ['C4', 'C5', 'C6', 'C7'],
'D2': ['D4', 'D5', 'D6', 'D7']},
index=[ 5, 6, 7,3])
dfs = [df1,df2]
df = pd.concat( dfs,axis=1,ignore_index=True)
by running this I get:
dfs = [df1,df2]
df = pd.concat( dfs,axis=1,ignore_index=True)

0 A0 B0 D0 NaN NaN NaN
2 A1 B1 D1 NaN NaN NaN
3 A2 B2 D2 A7 C7 D7
4 A3 B3 D3 NaN NaN NaN
5 NaN NaN NaN A4 C4 D4
6 NaN NaN NaN A5 C5 D5
7 NaN NaN NaN A6 C6 D6

But the expected output should be a 4 by 6 DF.

I faced the same issue using my data.
Please let me know if this is something you guys can check.

Thanks,

Alfonso

**Comment by simonjayhawkins** [comment] 2020-04-22 17:39
Thanks @Rcubes for the code sample.

> concatenating the tables leaves 1 partially empty row that shouldnt be there, on pandas version version (0.23.4) it didn't happen.

not sure if this code sample is representative of the OP, since get same output on 0.23.4 and master.

```
>>> import numpy as np
>>> import pandas as pd
>>>
>>> pd.__version__
'0.23.4'
>>>
>>> df1 = pd.DataFrame(
...     {
...         "A": ["A0", "A1", "A2", "A3"],
...         "B": ["B0", "B1", "B2", "B3"],
...         "D": ["D0", "D1", "D2", "D3"],
...     },
...     index=[0, 2, 3, 4],
... )
>>> df1
    A   B   D
0  A0  B0  D0
2  A1  B1  D1
3  A2  B2  D2
4  A3  B3  D3
>>>
>>> df2 = pd.DataFrame(
...     {
...         "A1": ["A4", "A5", "A6", "A7"],
...         "C": ["C4", "C5", "C6", "C7"],
...         "D2": ["D4", "D5", "D6", "D7"],
...     },
...     index=[5, 6, 7, 3],
... )
>>> df2
   A1   C  D2
5  A4  C4  D4
6  A5  C5  D5
7  A6  C6  D6
3  A7  C7  D7
>>>
>>> dfs = [df1, df2]
>>> df = pd.concat(dfs, axis=1, ignore_index=True)
>>> df
     0    1    2    3    4    5
0   A0   B0   D0  NaN  NaN  NaN
2   A1   B1   D1  NaN  NaN  NaN
3   A2   B2   D2   A7   C7   D7
4   A3   B3   D3  NaN  NaN  NaN
5  NaN  NaN  NaN   A4   C4   D4
6  NaN  NaN  NaN   A5   C5   D5
7  NaN  NaN  NaN   A6   C6   D6
>>>
>>> df = pd.concat(dfs, axis=1, ignore_index=False)
>>> df
     A    B    D   A1    C   D2
0   A0   B0   D0  NaN  NaN  NaN
2   A1   B1   D1  NaN  NaN  NaN
3   A2   B2   D2   A7   C7   D7
4   A3   B3   D3  NaN  NaN  NaN
5  NaN  NaN  NaN   A4   C4   D4
6  NaN  NaN  NaN   A5   C5   D5
7  NaN  NaN  NaN   A6   C6   D6
>>>
```

the ignore_index is not ignored, but applied to the columns labels.

from https://pandas.pydata.org/docs/dev/reference/api/pandas.concat.html

> ignore_indexbool, default False
If True, do not use the index values along the concatenation axis. The resulting axis will be labeled 0, …, n - 1. This is useful if you are concatenating objects where the concatenation axis does not have meaningful indexing information. Note the index values on the other axes are still respected in the join.

I'm closing this as I _think_ this is expected behaviour. ping me to reopen if I'm missing something.

**Closed by simonjayhawkins** 2020-04-22 17:39 UTC
Labels: Needs Triage
