### ISSUE TITLE
Broadcasting issue with 2d index in DataFrames 

### ISSUE THREAD

**Issue by dbelgrod** [pandas-dev/pandas#25416] opened 2019-02-22 22:38 UTC
```
#Under pandas==0.23.0
import pandas
df1 = pd.DataFrame([[1]], columns = [[1]], index = [ 1, 2 ])
print(df1)
df2 = pd.DataFrame([[1]], columns = [[1]], index = [ [ 1, 2 ] ])
print(df2)

Output:
   1
1  1
2  1

ValueError: Shape of passed values is (1, 1), indices imply (1, 2)

#Under pandas==0.22.0, this issue did not arise.
import pandas
df1 = pd.DataFrame([[1]], columns = [[1]], index = [ 1, 2 ])
print(df1)
df2 = pd.DataFrame([[1]], columns = [[1]], index = [ [ 1, 2 ] ])
print(df2)
Output:
   1
1  1
2  1
   1
1  1
2  1
```

It seems that if the index is just a list then broadcasting the values occurs. If it a list of lists, the index still maintains the same shape but broadcasting is not done in this case.

#### Output of ``pd.show_versions()``
<details>
pandas: 0.23.0
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: None
numpy: 1.11.3
scipy: 1.0.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.9
blosc: None
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.8
feather: None
matplotlib: 3.0.1
openpyxl: None
xlrd: 1.2.0
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.7
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0
</details>

**Comment by Liam3851** [comment] 2019-02-23 20:27
I cannot reproduce under latest version 0.24.1:

```python
In [1]: import pandas as pd

In [2]: df1 = pd.DataFrame([[1]], columns = [[1]], index = [ 1, 2 ])

In [3]: df1
Out[3]:
   1
1  1
2  1

In [4]: df2 = pd.DataFrame([[1]], columns = [[1]], index = [ [ 1, 2 ] ])

In [5]: df2
Out[5]:
   1
1  1
2  1

In [6]: pd.__version__
Out[6]: u'0.24.1'
```

Can you try the latest version?

**Comment by gfyoung** [comment] 2019-02-23 20:48
@Liam3851 : I can't reproduce either.  We should add the example as a test to close this unless someone can reproduce on the latest releases.

**Comment by jorisvandenbossche** [comment] 2019-03-04 13:33
I can reproduce it. It was indeed failing on 0.23.4, but now working on 0.24.1. So indeed good to add a test for it.

However, do we actually want to support 2D input as columns / index ?

**Comment by qudade** [comment] 2019-10-19 05:53
Added tests in #29083. ci is failing (for unrelated reasons). Will try to re-push later.

**Closed** 2019-10-19 17:08 UTC
Labels: Needs Tests, Reshaping
