### ISSUE TITLE
rename should warn when column does not exist

### ISSUE THREAD

**Issue by aamster** [pandas-dev/pandas#24311] opened 2018-12-16 19:50 UTC
`boston.rename(columns={'1': 'zn', '12': 'medv'}, inplace=True)`

had no effect since columns `'1'` and `'12'` don't exist. There should be a warning when column does not exist.

**Comment by TomAugspurger** [comment] 2018-12-16 20:39
Duplicate of https://github.com/pandas-dev/pandas/issues/13473.

We'd like to add a keyword to control this behavior.

**Closed by TomAugspurger** 2018-12-16 20:39 UTC
