### ISSUE TITLE
CI: build failing because of gbq testing

### ISSUE THREAD

**Issue by jreback** [pandas-dev/pandas#25910] opened 2019-03-28 13:50 UTC
see https://github.com/pandas-dev/pandas/pull/25554#issuecomment-477602786

added back the gbq dep and this is now failing.

**Comment by jreback** [comment] 2019-03-28 13:50
cc @h-vetinari @tswast

**Comment by h-vetinari** [comment] 2019-03-28 14:12
Seems to be https://github.com/conda-forge/pandas-gbq-feedstock/issues/18, compare [failed job](https://travis-ci.org/pandas-dev/pandas/jobs/512494733).

```
    def _test_google_api_imports():
    
        try:
            import pydata_google_auth
        except ImportError as ex:
            raise ImportError(
>               "pandas-gbq requires pydata-google-auth: {0}".format(ex)
            )
E           ImportError: pandas-gbq requires pydata-google-auth: No module named 'pydata_google_auth'
```

Note that `pandas-gbq` wasn't tested anywhere in the CI between #24942 was merged and now (after #25554). Seems we're still getting the old recipe somehow, because this is failing on the unpinned build. Simplest solution is to add `pydata-google-auth` to conda deps for the time being.

**Comment by jreback** [comment] 2019-03-28 14:29
what does the recipe have to do with this? we are installing the released package

**Comment by h-vetinari** [comment] 2019-03-28 14:56
The error is caused by a missing dependency (cf. `ImportError`) - exactly the one that was missing in the recipe. This dependency can be satisfied with conda, so that's IMO a better work-around than removing `pandas-gbq` from testing - this is what I've done in #25912.

**Comment by tswast** [comment] 2019-03-28 16:19
The condo package for pandas-gbq 0.8.0 is busted. Sorry about that. I fixed this issue in the second build of 0.9.0 in https://github.com/conda-forge/pandas-gbq-feedstock/commit/4c9a9873e2bc0650784bc0ff0f71b95570a71b8a

**Comment by tswast** [comment] 2019-03-28 16:22
Oh, except I see now that the build failed on that commit. I'll get a new build out soon.

**Comment by tswast** [comment] 2019-03-28 16:51
Reran the [conda-forge build for pandas-gbq-feedstock](https://circleci.com/workflow-run/94daa284-b7f6-4104-bb9f-eb275e07755c) and now the fixed build 1 should actually be published now. https://anaconda.org/conda-forge/pandas-gbq/files?version=0.9.0 Sorry about that!

**Closed** 2019-03-28 16:54 UTC
Labels: CI, Dependencies, IO Google
