### ISSUE TITLE
Crash with access violation (exit code -1073741819 (0xC0000005)) on Windows 10

### ISSUE THREAD

**Issue by Mereep** [pandas-dev/pandas#32776] opened 2020-03-17 14:51 UTC
```python
# Your code here
import pandas as pd
pd.__version__
Out[3]: '0.24.2'
t1 = {'a': 1, 'b': 1}
t2 = {'a': 2, 'b': 2}
test = [t1, t2],  # note the errernous comma at the end of the line 
type(test)
Out[7]: tuple
test
Out[8]: ([{'a': 1, 'b': 1}, {'a': 2, 'b': 2}],)
pd.DataFrame(test)
Process finished with exit code -1073741819 (0xC0000005)
```
Short:
```python
pd.DataFrame(tuple([[1],[2]]))
Process finished with exit code -1073741819 (0xC0000005)
```
#### Problem description
Problem was caused in my case by having an additional comma at the end of a line that caused
a list of dicts being a tuple of list of dicts which caused that behaviour. 

Althought the argument should not be accepted by Pandas, Pandas should raise an appropriate Exception instead of tearing Python down.

**Comment by jbrockmendel** [comment] 2020-03-17 17:50
Can you try this on a newer version of pandas?

**Comment by Mereep** [comment] 2020-03-17 21:48
New version seems to fix that

```python
t1 = {'a': 1, 'b': 1}
t2 = {'a': 2, 'b': 2}
test = [t1, t2],
pd.DataFrame(test)
 0                 1
{'a': 1, 'b': 1}  {'a': 2, 'b': 2}
pd.__version__
'1.0.2'
```
Latest version seems to fix it. However, I can reproduce the faulty behaviour in a fresh conda environment with the old pandas version.

The thread may be closed. However, it should be checked if this problem was intentionally fixed at some point or its fixed by chance.

**Comment by simonjayhawkins** [comment] 2020-04-01 11:20
> Latest version seems to fix it. However, I can reproduce the faulty behaviour in a fresh conda environment with the old pandas version.
> 
> The thread may be closed. However, it should be checked if this problem was intentionally fixed at some point or its fixed by chance.

Thanks @Mereep for the report. I can confirm this issue is a duplicate of #25691 was fixed in #25731

9fbb9e7c71cf10852b84c1f393263ee04bd790d5 is the first new commit
commit 9fbb9e7c71cf10852b84c1f393263ee04bd790d5
Author: Tao He <sighingnow@gmail.com>
Date:   Fri Apr 5 08:45:19 2019 +0800

    BUG: Convert tuple to list before `_list_to_arrays` when construct DataFrame. (#25731)

**Comment by BenjaminLiuPenrose** [comment] 2020-04-02 02:31
I just try to reproduce the bug.

For pandas<=0.24.2, running `pd.DataFrame(tuple([[1],[2]]))` will lead to python crash and exit
For pandas>=0.25.0, running `pd.DataFrame(tuple([[1],[2]]))` is fine as described by @Mereep

**Comment by BenjaminLiuPenrose** [comment] 2020-04-02 02:34
In pandas==0.24.2
<img width="526" alt="cap1" src="https://user-images.githubusercontent.com/24482664/78204918-e116a580-7468-11ea-8fe2-aaf85a9b2695.PNG">

In pandas==0.25.0
<img width="534" alt="cap2" src="https://user-images.githubusercontent.com/24482664/78204958-f68bcf80-7468-11ea-97b3-9650dace1246.PNG">

**Comment by BenjaminLiuPenrose** [comment] 2020-04-02 03:05
Guess this issue thread can be closed now...

**Closed** 2020-04-04 21:07 UTC
Labels: Needs Tests, good first issue
