### ISSUE TITLE
BUG: `to_parquet()` changes values using pyarrow

### ISSUE THREAD

**Issue by klezm** [pandas-dev/pandas#53798] opened 2023-06-22 17:19 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
import io

df = pd.DataFrame([
        [{"a": 1, "b": 2, "c": 3}],
        [{"a": 4, "b": 5}]
])

df2 = pd.read_parquet(io.BytesIO(df.to_parquet(engine = "pyarrow")), engine = "pyarrow")

pd.testing.assert_frame_equal(df, df2)
```

### Issue Description

Using pyarrow to store a DataFrame the values are changed when the values are dictionaries with different keys.

In the example the 1st row of `df` has a dict with 3 keys (`a`, `b`, `c`), whereas the 2nd row only has two keys (`a`, `b`). Using pyarrow to write and read the DataFrame the 2nd row of `df2` now also has the same 3 keys as in the 1st row:

df:

```
                          0
0  {'a': 1, 'b': 2, 'c': 3}
1  {'a': 4, 'b': 5}
```

df2:

```
                             0
0   {'a': 1, 'b': 2, 'c': 3.0}
1   {'a': 4, 'b': 5, 'c': None}
```` 

The assertion throws the following error:

```
AssertionError: DataFrame.iloc[:, 0] (column name="0") are different

DataFrame.iloc[:, 0] (column name="0") values are different (50.0 %)
[index]: [0, 1]
[left]:  [{'a': 1, 'b': 2, 'c': 3}, {'a': 4, 'b': 5}]
[right]: [{'a': 1, 'b': 2, 'c': 3.0}, {'a': 4, 'b': 5, 'c': None}]
At positional index 1, first diff: {'a': 4, 'b': 5} != {'a': 4, 'b': 5, 'c': None}
```

### Expected Behavior

Writing and reading the Dataframe should not change its values.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 965ceca9fd796940050d6fc817707bba1c4f9bff
python           : 3.10.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.107+
Version          : #1 SMP Sat Apr 29 09:15:28 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 2.0.2
numpy            : 1.22.4
pytz             : 2022.7.1
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 0.29.34
pytest           : 7.2.2
hypothesis       : None
sphinx           : 3.5.4
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.2
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.6
jinja2           : 3.1.2
IPython          : 7.34.0
pandas_datareader: 0.10.0
bs4              : 4.11.2
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2023.4.0
gcsfs            : None
matplotlib       : 3.7.1
numba            : 0.56.4
numexpr          : 2.8.4
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : 0.17.9
pyarrow          : 12.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 2.0.10
tables           : 3.8.0
tabulate         : 0.8.10
xarray           : 2022.12.0
xlrd             : 2.0.1
zstandard        : None
tzdata           : 2023.3
qtpy             : None
pyqt5            : None

</details>

**Comment by rhshadrach** [comment] 2023-06-22 21:38
I am wondering if this is a pyarrow issue; I do not believe pandas is doing anything with the values; we mostly just call `read` and `write`.

cc @jorisvandenbossche

**Comment by mroeschke** [comment] 2023-12-06 20:09
Yeah this looks like a intended behavior of how pyarrow reads a DataFrame of structs

```python
In [5]: pa.Table.from_pandas(df).to_pandas()
Out[5]: 
                             0
0   {'a': 1, 'b': 2, 'c': 3.0}
1  {'a': 4, 'b': 5, 'c': None}
```

I don't think there's anything that can be on the pandas side currently to avoid this behavior, but if there is ever an option on the pyarrow side to exclude missing keys, we can implement here so closing for now

**Closed by mroeschke** 2023-12-06 20:09 UTC
Labels: Bug, Upstream issue, Arrow
