### ISSUE TITLE
frequency issues

### ISSUE THREAD

**Issue by jseabold** [pandas-dev/pandas#6638] opened 2014-03-14 21:26 UTC
I'm just trying to get my head around what these tools actually do and what they're used for. I can't tell if I'm misunderstanding or this is all just unfinished.

```
from pandas.tseries import frequencies
frequencies._is_annual('AS') # oversight?
# can I go from quarterly to annual?
frequencies.is_subsample('Q', 'A') # yes
frequencies.is_subsample('Q', 'AS') # none?
frequencies.is_subperiod(frequencies.to_offset('Q'), frequencies.to_offset('AS')) # none
# what about weekly to annual?
frequencies.is_subperiod('W', 'A') # false?
```

 It looks like a combination of _is_annual and friends not also checking for `AS-`, etc. and the omission of frequency strings in the checks in `is_subperiod`. Easy fix, just want some sanity checking.

**Comment by mroeschke** [comment] 2021-04-11 04:21
`is_subperiod` is the only method that exists now which has the docstring

```
    Returns True if downsampling is possible between source and target
    frequencies
```

So the last 2 examples should unexpectedly return `False` since the going from the source to target in this case is upsampling.

So closing as the expected behavior but happy to reopen if misunderstood

**Closed by mroeschke** 2021-04-11 04:21 UTC
Labels: Bug, Frequency

**Comment by jseabold** [comment] 2021-04-11 12:13
I think these issues still persist, at least in 1.2.3. Are they fixed in master?

```
In [5]: pd.tseries.frequencies.is_subperiod('A', 'W')
Out[5]: False

In [6]: pd.tseries.frequencies.is_subperiod('W', 'A')
Out[6]: False
```

**Comment by jseabold** [comment] 2021-04-11 12:16
If my source is weekly and my target is annual, surely I can downsample from weekly to annual, which unless I'm missing something should be the result of `is_subperiod('W', 'A')`. Maybe it's False because of the boundary effects of trying to downsample weekly to annual, so pandas refuses to guess vs. trying to do something with ISO week dates.

**Comment by cancan101** [comment] 2021-04-12 16:18
I don't think that weekly should be a sub period of annual. Perhaps weekly should be a subperiod of ISO weeks (https://en.wikipedia.org/wiki/ISO_week_date).

I did notice that this seems wrong:
```
pd.tseries.frequencies.is_subperiod('REQ', 'RE')
> False
```
