### ISSUE TITLE
Duplicate row indices (bootstrapped dataframes)

### ISSUE THREAD

**Issue by hcorrada** [pandas-dev/pandas#2268] opened 2012-11-16 17:00 UTC
I'm running into issues using bootstrap samples of the rows of a DataFrame. Example:

<pre>
import pandas
import numpy

numpy.random.seed(1)
df=pandas.DataFrame({'a':numpy.random.randn(20),'b':numpy.random.randn(20)})
nrows=df.shape[0]

# make a bootstrap sample of the rows (nrows indices with replacement)
boot_indxs=numpy.random.random_integers(0,nrows-1,nrows)

# make a dataframe with sampled rows
df2=df.irow(boot_indxs)
print df2

# this complains but that's ok since row 5 of df wasn't sampled
print df2.ix[:5,:]

# this complains, but perhaps it shouldn't since I'm just asking for the first nine
# rows of the data frame
print df2.irow(range(10))

# this works however which is great
print df2.irow(slice(10))

# the problem is then accessing rows without slices
# use case: taking a random subset of the rows of the bootstrapped dataframe
# to fit a predictive model and test it on the remaining rows
print df2.irow(numpy.random.permutation(range(nrows))[:15])
</pre>

**Comment by petehuang** [comment] 2016-12-27 23:08
This issue's last interaction was 4 years ago. I wonder what the current state of discussion is. Given that it's not a bug, my gut instinct is to close this issue.

What do you think?

**Comment by jreback** [comment] 2016-12-29 11:24
aside from the fact that this is using lots of deprecated code, this is not very idiomatic (though valid code)

**Closed by jreback** 2016-12-29 11:24 UTC
