### ISSUE TITLE
PERF: groupby with many empty groups memory blowup

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#30552] opened 2019-12-29 22:59 UTC
Suppose we have a Categorical with many unused categories:

```
cat = pd.Categorical(range(24), categories=range(10**5))

df = pd.DataFrame({"A": cat, "B": range(24), "C": range(24), "D": 1})

gb = df.groupby(["A", "B", "C"])

>>> gb.size()  # memory balloons to 9+ GB before i kill it
```

There are only 24 rows in this DataFrame, so we shouldn't be creating millions of groups.

Without the Categorical, but just a large cross-product that implies many empty groups, this works fine:

```
df = pd.DataFrame({n: range(12) for n in range(8)})

gb = df.groupby(list(range(7)))
gb.size() # <-- works fine
```

**Comment by jreback** [comment] 2019-12-29 23:23
this is the point of the observed keyword

**Comment by WillAyd** [comment] 2020-01-02 21:16
So yea to second Jeff’s comment above is this a problem with observed=True?

**Comment by jbrockmendel** [comment] 2020-01-02 21:20
passing observed=True solves the problem.  id like to add a warning or something for users who find themselves about to hit a MemoryError

**Comment by WillAyd** [comment] 2020-01-02 21:29
Did we ever discussion changed the default observed keyword? @TomAugspurger

**Comment by TomAugspurger** [comment] 2020-01-02 21:33
I don't recall a discussion about that.

I vaguely recall that this will be somewhat solved by having a DictEncodedArray that has a similar data model to Categorical, without the unobserved / fixed categories semantics.

**Comment by WillAyd** [comment] 2020-01-02 23:38
Hmm I think that is orthogonal. IIUC the memory blowup is because by default we are generating Cartesian products. Would rather just deprecate that and switch the default value for observed

**Comment by TomAugspurger** [comment] 2020-01-02 23:40
I think it’s a good default for the original design semantics of Categorical. It’s a bad default for the memory-saving aspect of categorical.

**Comment by jbrockmendel** [comment] 2020-01-03 00:53
Sounds like we can close this as no-action?

**Comment by jreback** [comment] 2020-01-03 00:56
i suppose we would show a PerformanceWarning if we detect this would happen which is pretty cheap to do

might be worthwhile

**Comment by paulrougieux** [comment] 2020-01-14 11:21
I cannot reproduce the issue above with `cat = pd.Categorical(range(24), categories=range(10**5))` on pandas 0.25.3.
When upgrading from pandas 0.24.2 to 0.25.3, I have a new memory issue with a groupby().agg()  My groups are a mix of categorical and character variables. 
Using 

    df.groupby(index, observed=True)

fixes it.

**Comment by jangorecki** [comment] 2020-03-23 20:16
What are the actions to be taken in this issue? Changing the default, depreciating argument, documenting, or something else? It is not clear from current discussion.
Could anyone provide a use case for a observed=False?

**Comment by TomAugspurger** [comment] 2020-03-23 20:35
We're not changing the behavior. The only proposal that's on the table is detecting and warning when we have / are about to allocate too much memory. 

>  Could anyone provide a use case for a observed=False?

When you have a fixed set of categories that should persist across operations (e.g. survey results).

**Comment by jangorecki** [comment] 2020-03-23 20:50
Thanks. It is pretty significant regression, not very new one already, but still.

And how is it useful for grouping? Empty groups are being returned?
Usually it is addressed by a right outer join to such a categorical dictionary.

**Comment by TomAugspurger** [comment] 2020-03-23 20:53
What's the regression? All categories are present in the output of a groupby by design, including unobserved categories.

**Comment by jangorecki** [comment] 2020-03-23 22:17
Regression is that code that worked fine on 0.24.2 is not hitting MemoryError

**Comment by TomAugspurger** [comment] 2020-03-24 01:20
Did it have the correct output in 0.24.2? In pandas 0.24.2 I have

```python
In [8]: cat = pd.Categorical(['a', 'b'], categories=['a', 'b', 'c'])

In [9]: df = pd.DataFrame({"A": cat, "B": [1, 2], "C": [3, 4]})

In [10]: df.groupby(["A", "B"]).size()
Out[10]:
A  B
a  1    1
b  2    1
dtype: int64
```

which is incorrect. So it sounds like you were relying on buggy behavior.

**Comment by paulrougieux** [comment] 2020-03-25 07:52
>> @jangorecki 
>> Could anyone provide a use case for a observed=False?

> @TomAugspurger 
> When you have a fixed set of categories that should persist across operations (e.g. survey results).

In the context of multiple categorical variables used as the groupby index. Persisting a fixed set of categories (inside each categorical variable) is a different issue i.e. maybe the observed `argument` should be disentangled in two arguments: (1) one argument for the allocation of all possible combination of these categorical variables. For example `observed=False` would tell pandas to keep all possible categories inside the categorical variable. And (2)  another argument  would tell pandas to preallocate memory for all possible combination of categorical variables. For example `preallocate=True` would preallocate memory and `preallocate=False` would not. 
But I might have misunderstood what @TomAugspurger meant.

**Comment by TomAugspurger** [comment] 2020-03-25 12:59
Sorry @paulrougieux, I don't follow your proposal. Could you add an example what the two keywords would do?

`observed=True/False` doesn't affect the dtype of the index. That will always be the same dtype as the grouper.

```python
In [7]: pd.Series([1, 2, 3]).groupby(pd.Categorical(['a', 'a', 'a'], categories=['a', 'b']), observed=True).sum().index.dtype
Out[7]: CategoricalDtype(categories=['a', 'b'], ordered=False)

In [8]: pd.Series([1, 2, 3]).groupby(pd.Categorical(['a', 'a', 'a'], categories=['a', 'b']), observed=False).sum().index.dtype
Out[8]: CategoricalDtype(categories=['a', 'b'], ordered=False)
```

It only controls whether the aggregation function is applied to the unobserved category's groups as well.

**Comment by paulrougieux** [comment] 2020-03-25 13:05
@TomAugspurger I misunderstood your previous comment about the "fixed set of categories that should persist across operations ". Thanks for clarifying.

**Comment by arw2019** [comment] 2020-05-14 23:04
I'm interested in working on this, and the related issue (#34162)!

I'll dig into it and post my progress on the thread.

**Comment by jangorecki** [comment] 2020-05-14 23:10
@arw2019 recently discussed #32918 looks to be related as well

**Comment by jseabold** [comment] 2020-09-01 14:46
Trying to think through the examples here and whether my current "usual" columns are more or less prevalent to not want sql group by semantics by default. E.g., for the case of grouping by cities and states, they're both factors and they're not independent. I guess you could say that they should be single city-state factors?

> When you have a fixed set of categories that should persist across operations (e.g. survey results).

FWIW, I think this is what I use unstack for but am not sure. Could you post an example workflow to compare?

**Comment by cottrell** [comment] 2021-01-21 21:56
> Did we ever discussion changed the default observed keyword? @TomAugspurger
> […](#)
> Sent from my iPhone
> On Jan 2, 2020, at 4:21 PM, jbrockmendel ***@***.***> wrote: ﻿ passing observed=True solves the problem. id like to add a warning or something for users who find themselves about to hit a MemoryError — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I believe I warned about this last year here: https://github.com/pandas-dev/pandas/issues/17605#issuecomment-561716086

**Comment by simonjayhawkins** [comment] 2021-06-11 13:42
removing milestone

**Comment by psarka** [comment] 2021-10-14 01:03
Another datapoint on how one can get stumped by this issue:

I never use categoricals, and never expected to, but it so happens that they are used automatically when writing to parquet with partitions:

```
import pandas as pd

df = pd.DataFrame({'a': [1, 0, 1, 0], 'b': [1, 2, 3, 4]})
df.to_parquet('test.parquet', partition_cols='a')

# pd.read_parquet('test.parquet') will return a DataFrame with a categorical column a.
```

The rest of the story is the same, do a group by, everything explodes.

**Comment by joeyearsley** [comment] 2021-11-23 22:57
Ran into this issue recently as we switched from using csv's and strings, to categoricals and feather files. 

Took myself quite a while to stumble onto it being the datatype issue in the groupby, ➕ on changing the default to `observed=True`

**Comment by corriebar** [comment] 2022-02-18 09:48
In the last months, we had multiple issues due to this. We changed one column to categorical somewhere in our pipeline and got non-obvious errors in very different parts of our pipeline. From my side, also strong ➕  to change the defaults to`observed=True`.

As mentioned before and elsewhere in related issues, the behaviour imho is not very intuitive: SQL does not behave like this nor does the R tidyverse with factors.
I was especially confused that having a single categorical grouper in a list of multiple groupers turns all groupers (behaviourwise) categorical, i.e. it outputs the Cartesian product.
I think the only example I've seen mentioned so far as where this might be useful would be survey data with e.g. likert scales. I work with survey data but we have different answer options for different questions, some are likert scale, some are yes/no etc. When using groupby to get counts per question per answer option, the Cartesian product is not really what you want.
It is certainly not clear how to reasonably show empty groups when using multiple groupers and only one is categorical but to me using `observed=True` as the default seems like the better option than making non-intuitive assumptions.

I also noticed that when grouping by a categorical index column, `observed=True` does not drop empty groups.

**Comment by rhshadrach** [comment] 2022-10-04 23:51
> I think it’s a good default for the original design semantics of Categorical. It’s a bad default for the memory-saving aspect of categorical.

I definitely think this has some truth to it, but only partially. One reason to use categorical within groupby is to take advantage of `observed=True`. However another reason to use categorical generally is to save memory with e.g. string columns. I would hazard a guess that the latter is much more prevalent than the former, though I have nothing to back this up with.

I do find it surprising that changing from e.g. int to categorical alters the default groupby result, and since `observed=False` can result in memory issues, I think there is a good case to make `observed=True` the default. I'm +1 here.

**Comment by cottrell** [comment] 2022-10-05 06:32
> > I think it’s a good default for the original design semantics of Categorical. It’s a bad default for the memory-saving aspect of categorical.
> 
> I definitely think this has some truth to it, but only partially. One reason to use categorical within groupby is to take advantage of `observed=False`. However another reason to use categorical generally is to save memory with e.g. string columns. I would hazard a guess that the latter is much more prevalent than the former, though I have nothing to back this up with.
> 
> I do find it surprising that changing from e.g. int to categorical alters the default groupby result, and since `observed=False` can result in memory issues, I think there is a good case to make `observed=True` the default. I'm +1 here.

Replace "save memory" with "bound memory by data size and instead of merely by product of arities of dimensions of categoricals". I don't think people are understanding the cursive of dimensionality issue here. This is like taking a sparse tensor of N dimensions and going .todense() by default and calling the previous step merely "memory saving".

**Comment by paulrougieux** [comment] 2022-10-05 07:42
1.  A difference has to be made between 
    - the case where there are only one or two grouping variable and where there is no risk of combinatorial explosion 
    - and the case with many grouping variable and there is a risk of combinatorial explosion.
1. As already mentioned by @corriebar categorical variables do not behave like this in R.
1. Other users in this thread say that they have to specify `observed=False` explicitely at each function call. Alternatively, they could also not use categorical variables at all when groupby() operations are needed. The different uses for categorical variables should also be clarified: to keep survey options even if there was no reply, to keep and reorder named variables in a graph (such as ordering country names by population size instead of alphabetical order for example), many other uses come here ....
1. The `observed` argument was switched from `True` to `False` in pandas version 0.25. Maybe this was buggy behaviour as @https://github.com/TomAugspurger wrote at the beggining of this issue. At least that is when this behaviour started to appear. Maybe switching `observed` to `True` or `False` could be dealt with globally. I don't know if it makes sense, using for example an environment variable? 
1. There has been recent activity related to the `observed=False` argument in the [changelog of version 1.5.1](https://github.com/pandas-dev/pandas/blob/8bcc1ebb8babdfc95afe89219dabcaa98614caea/doc/source/whatsnew/v1.5.1.rst) in interaction with a bug when using `dropna=False`.
1. Sample code and data from actual users of `observed=True` could help understand how their work would be damaged by switching to a default of `observed=False`.
    -  Maybe the authors of [Quantipy](https://github.com/Quantipy/quantipy) or [PandaSurvey](https://github.com/InContextSolutions/PandaSurvey) can provide sample code and data? (these are returned for a google search of "pandas survey data package", but have not been in active development since 4 and 8 years respectively according to the latest commits)

**Comment by rhshadrach** [comment] 2023-03-07 00:22
@jbrockmendel 

> passing observed=True solves the problem. id like to add a warning or something for users who find themselves about to hit a MemoryError

If observed=True was the default, would you still find it beneficial to have a warning here?

**Comment by jbrockmendel** [comment] 2023-03-07 00:26
i think changing the default would close this

**Closed** 2023-03-17 17:03 UTC
Labels: Groupby, Performance, Categorical

**Comment by Alexia-I** [comment] 2024-01-15 11:19
Seems that this performance improvement could be backported to previous versions due to its severity? Also, the code change seems not too complex to backport.

**Comment by rhshadrach** [comment] 2024-01-15 20:59
The improvement here was changing the default value to `observed` from `False` to `True`. We should not be backporting API changes.
