### ISSUE TITLE
QST: Behaviour of `mean()` for a Series of strings.

### ISSUE THREAD

**Issue by shwina** [pandas-dev/pandas#34957] opened 2020-06-23 18:21 UTC
Greetings, Pandas devs! My question is about the behaviour of `mean()` for a Series of strings:

```
In [1]: import pandas as pd

In [2]: pd.Series(['1', '2']).mean()
Out[2]: 6.0
```

From https://github.com/pandas-dev/pandas/issues/34671#issuecomment-641927667, the result is `6` because:

> "1" + "2" is "12", and then we convert to numeric 12, and divide by the count

This feels like somewhat implicit behaviour that makes assumptions about how the mean is computed.

Would it be more desirable to throw here? Or perhaps return `1.5` instead?

**Comment by galipremsagar** [comment] 2020-06-23 18:31
commenting to follow thread.

**Comment by rhshadrach** [comment] 2020-06-23 21:40
Thanks for the question - as the discussion in the issue you mentioned indicates, `6.0` is not the desired output. If you have any feedback/suggestions, please feel welcome to mention them in the original issue rather than have discussions going on in two separate issues.

Closing as a duplicate of #34671

**Closed by rhshadrach** 2020-06-23 21:40 UTC
Labels: Needs Triage, Usage Question
