### ISSUE TITLE
pytest on test_html.py failing

### ISSUE THREAD

**Issue by JvPy** [pandas-dev/pandas#30168] opened 2019-12-09 20:51 UTC
When running pytest -v pandas/tests/io/test_html.py the following test fails:

pandas/tests/io/test_html.py::TestReadHtml::test_thousands_macau_index_col[bs4] FAILED [ 26%]

When I push the file, it passes all verifications on the pipeline.

**Comment by TomAugspurger** [comment] 2019-12-09 21:02
What does it fail with? An ImportError?

Most likely needs an importorskip on html5lib and / or beautiful soup.

**Comment by JvPy** [comment] 2019-12-09 21:11
Ill check for that! Thanks!

**Comment by JvPy** [comment] 2019-12-10 00:05
The test fails here:

pandas/tests/io/test_html.py:389: dfs = self.read_html(macau_data, index_col=0, header=0)
 
 AttributeError: 'NoneType' object has no attribute 'items' on formatter.py, line62.


Can you help me fix this issue?

**Comment by MomIsBestFriend** [comment] 2019-12-10 11:04
Same here, But the failing tests passed once I installed an older version of ```beautifulsoup4```, for example ```4.7.1```.

**Comment by JvPy** [comment] 2019-12-12 16:47
downgrading `beautifulsoup4 ` worked for me as well

**Comment by simonjayhawkins** [comment] 2019-12-12 19:16
duplicate of #29622 and #28125

**Closed by simonjayhawkins** 2019-12-12 19:16 UTC
Labels: Unreliable Test
