### ISSUE TITLE
ENH: add dtype to read_xml

### ISSUE THREAD

**Issue by MehdiALLALA** [pandas-dev/pandas#45341] opened 2022-01-13 09:30 UTC
#### Is your feature request related to a problem?

pandas column type detection is not precise. for some columns the type in not the actual data type when reading xml files with read_xml.

#### Describe the solution you'd like

the solution is to add dtype option in the read_xml utility that will provide pandas with the wanted column types, this feature exists already with read_json, read_csv and many other utilities.

#### API breaking implications

this will make the read_xml utility detect the right type for each column. to keep the data in the correct format.

#### Describe alternatives you've considered

creating a script that will use the default pandas.DataFrame(......) constructor that contains dtype option to parse the xml file.
![Capture6](https://user-images.githubusercontent.com/34867955/149307923-2da8e7b1-835f-4883-b7b4-21c6a991c279.PNG)
![Capture7](https://user-images.githubusercontent.com/34867955/149307927-f5956b50-6a4b-45ca-a76f-2c23b7304e32.PNG)

the loaded result from the read_xml is not the same as the xml file. the highlighted column is a string but pandas read it as an integer and with this the data is corrupted.

**Comment by ParfaitG** [comment] 2022-01-16 21:21
Thanks, @MehdiALLALA. The `dtypes` feature for `read_xml` was raised in a similar issue, #43567, and added to issue tracker, #40131.

**Comment by mroeschke** [comment] 2022-01-16 22:51
Closing as a duplicate of https://github.com/pandas-dev/pandas/issues/43567

**Closed by mroeschke** 2022-01-16 22:51 UTC
Labels: Enhancement, Dtype Conversions, IO XML
