### ISSUE TITLE
Series `sort_index` missing `kind` keyword

### ISSUE THREAD

**Issue by numerical** [pandas-dev/pandas#14444] opened 2016-10-17 22:17 UTC
#### A small, complete example of the issue

```python
>>> import pandas as pd
>>> pd.Series(index=[3,2,1,4,3]).sort_index(kind='mergesort')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sort_index() got an unexpected keyword argument 'kind'

```

#### Expected Output
A `Series` sorted by the index, i.e.:

```python
>>> pd.Series(index=[3,2,1,4,3]).sort_index()
1   NaN
2   NaN
3   NaN
3   NaN
4   NaN
dtype: float64
```

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Linux
OS-release: 4.4.0-42-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.18.1
nose: 1.3.1
pip: 1.5.4
setuptools: 3.3
Cython: 0.20.1post0
numpy: 1.11.0
scipy: 0.13.3
statsmodels: None
xarray: None
IPython: 1.2.1
sphinx: 1.2.2
patsy: None
dateutil: 2.5.3
pytz: 2016.4
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.3.1
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: 0.8.7
lxml: None
bs4: 4.4.1
html5lib: 0.999
httplib2: 0.8
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.7.2
boto: None
pandas_datareader: None
</details>

**Comment by brandonmburroughs** [comment] 2016-10-17 23:19
It looks like we use `_nargsort` in `DataFrame` ([relevant code](https://github.com/pandas-dev/pandas/blob/master/pandas/core/frame.py#L3323-L3341)), but `sort_values` in `Series` ([relevant code](https://github.com/pandas-dev/pandas/blob/master/pandas/core/series.py#L1788-L1792)).  We can update `sort_index` in `Series` to follow the same pattern.

**Comment by jreback** [comment] 2016-10-17 23:26
a dupe of #13589

**Closed by jreback** 2016-10-17 23:26 UTC
