### ISSUE TITLE
Feature request: adding read_ods function

### ISSUE THREAD

**Issue by Foadsf** [pandas-dev/pandas#21468] opened 2018-06-13 20:42 UTC
It came to me as a surprise that Pandas has builtin `read_excel` function but it is not able to read `.ods` fils natively

**Comment by jschendel** [comment] 2018-06-13 21:07
Thanks, this is a dupe of #2311

**Closed by jschendel** 2018-06-13 21:07 UTC

**Comment by Foadsf** [comment] 2018-06-13 22:18
@jschendel thanks. sorry for the dup. It did not show up in my search results!
