### ISSUE TITLE
Problem in Pandas 0.18.1 with Python 3.5

### ISSUE THREAD

**Issue by matiumerca** [pandas-dev/pandas#15225] opened 2017-01-25 16:26 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import pandas as pd
import numpy as np

u=pd.DataFrame([np.nan]*5)
u.sum()
```
#### Problem description

It returns 0.0 but it is written in http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sum.html.
That it should (and it seems normal) return nan.
"If an entire row/column is NA, the result will be NA"

#### Expected Output
It should return nan.

#### Output of ``pd.show_versions()``

<details>
# Paste the output here pd.show_versions() here
pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None

</details>

**Comment by bashtage** [comment] 2017-01-25 18:04
Is bottleneck >= 1.0 installed?  Bottleneck return 0.0 for all nan arrays.

**Comment by jreback** [comment] 2017-01-25 18:54
this is a dupe of #9422 (details show bottleneck 1.1)

**Closed by jreback** 2017-01-25 18:54 UTC
