### ISSUE TITLE
DOC: Wrong output in the example of Timedelta.isoformat

### ISSUE THREAD

**Issue by gurukiran07** [pandas-dev/pandas#38311] opened 2020-12-05 04:46 UTC
#### Location of the documentation

[`pandas.Timedelta.isoformat`](https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.isoformat.html#pandas.Timedelta.isoformat)

#### Documentation problem

The output on an example in the docs has the wrong output(`Timedelta.isoformat` works fine)

![Screenshot from 2020-12-04 16-40-36](https://user-images.githubusercontent.com/47276342/101234113-ce80fa00-36e2-11eb-8e2c-9623f41a69ae.png)

While it should've been `'P0DT1H0M10S'`

**Comment by arw2019** [comment] 2020-12-09 04:48
not sure what the issue is, aren't these the same

**Comment by gurukiran07** [comment] 2020-12-09 05:16
@arw2019 
Yes, the same example is given twice in the docs.

The issue is the outptut of `pd.Timedelta(hours=1, seconds=10)` is wrong in the docs (`pd.Timedelta` works perfectly fine).
```
pd.Timedelta(hours=1, seconds=10)
'P0DT1H0M10S'  # In docs it's 'P0DT0H0M10S'
```

**Comment by arw2019** [comment] 2020-12-09 05:19
is this an issue in the docs or with Timedelta?

**Comment by gurukiran07** [comment] 2020-12-09 05:27
@arw2019 
> is this an issue in the docs or with Timedelta?

Only related to the docs.

**Comment by simonjayhawkins** [comment] 2020-12-14 13:00
https://github.com/pandas-dev/pandas/blob/d85e9a23c5cb4ecd158a7759f97a0a8a58c132ef/pandas/_libs/tslibs/timedeltas.pyx#L1086-L1098

**Comment by simonjayhawkins** [comment] 2020-12-14 13:01
@gurukiran07 Thanks for the report. Interested in submitting a PR?

**Comment by gurukiran07** [comment] 2020-12-14 13:34
@simonjayhawkins Yes, will submit.

**Comment by gurukiran07** [comment] 2020-12-14 13:34
take

**Comment by simonjayhawkins** [comment] 2020-12-14 13:38
> How do I assign it to myself? "take" did not work.

strange. done it manually.

**Comment by aflah02** [comment] 2020-12-16 09:36
Just wanted to ask can someone else also do issues which have been assigned?

**Comment by MarcoGorelli** [comment] 2020-12-19 09:41
In the future could you please paste the code instead of a screenshot? Else searching through old issues becomes near impossible

**Comment by aflah02** [comment] 2020-12-19 09:44
Hey @MarcoGorelli 
I received a notification for your comment
Just wanted to ask since I'm new here can anyone take up assigned issues as well or is it reserved to the assigned person for some duration?

**Comment by MarcoGorelli** [comment] 2020-12-19 09:46
Looks like there's already a PR to close it https://github.com/pandas-dev/pandas/pull/38579

@gurukiran07 I hadn't noticed you'd already assigned yourself here - unless you already have a PR ready, shall we leave it to them, as they're a first-time contributor?

**Closed** 2020-12-19 10:23 UTC
Labels: Docs, good first issue

**Comment by gurukiran07** [comment] 2020-12-19 11:06
@MarcoGorelli Yes sure fine. I haven't really had the time to time make a PR. Glad some else did.
