### ISSUE TITLE
BUG: Int64 data casted to float64 when using [<column_name>] in a DataFrame

### ISSUE THREAD

**Issue by NicolasGrosjean** [pandas-dev/pandas#35156] opened 2020-07-07 07:24 UTC
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
df = pd.DataFrame([[0, 1.0], [2, 3.0]], columns=['intCol', 'floatCol'])
print(type(df.loc[0, 'intCol']))
print(type(df.loc[0]['intCol']))
```

#### Problem description
I have create a Dataframe with a int and a float column.
When accessing to a value of a row by .loc for the int column I have a numpy.int64.
But when accessing by a column selection I have a numpy.int64.

#### Expected Output
In the code sample the expected output is :
<class 'numpy.int64'>
<class 'numpy.int64'>

#### Output of ``pd.show_versions()``
<details>
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.0.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.15.0-109-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1.post20200622
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None
</details>

**Comment by jreback** [comment] 2020-07-07 09:38
duplicate of #35153

taking a cross section casts to a common dtype

**Closed** 2020-07-07 09:38 UTC
Labels: Indexing, Usage Question
