### ISSUE TITLE
DataFrame.groupby fails with MultiIndex containing pd.NaT

### ISSUE THREAD

**Issue by stevenmanton** [pandas-dev/pandas#9236] opened 2015-01-13 01:26 UTC
It seems that the `groupby` operation fails when the row index is a MultiIndex containing NaT values. For example, the following code fails (v0.15.2) with `TypeError: 'numpy.ndarray' object is not callable`:

``` python
midx = pd.MultiIndex(levels=[[pd.NaT, pd.datetime(2012,1,2), 
                     pd.datetime(2012,1,3)], ['a', 'b']],
                     labels=[[0, 1, 1, 2], [0, 0, 1, 0]], names=['date', None])
df = pd.Series(pd.np.random.rand(4), index=midx)
df.groupby(level=1)
```

However, it seems as though np.nan values are handled properly:

``` python
midx = pd.MultiIndex(levels=[[pd.np.nan, 10, 20], ['a', 'b']],
                     labels=[[0, 1, 1, 2], [0, 0, 1, 0]], names=['date', None])
df = pd.Series(pd.np.random.rand(4), index=midx)
df.groupby(level=1)
```

**Comment by shoyer** [comment] 2015-01-13 04:07
I can reproduce this on master.

Thanks for the report!

**Comment by jreback** [comment] 2015-01-13 04:10
iirc this is a dupe issue - if someone would like 2 find the reference

**Comment by jreback** [comment] 2015-01-13 11:00
this is covered by #6996, #6992, will xref it there.

pull-requests are welcome

**Comment by jreback** [comment] 2015-01-13 11:01
actually, will reopen in case it is slightly different.

**Comment by stevenmanton** [comment] 2015-01-14 01:08
Thanks for looking into this! I've been banging into this all day as I've been working on some analysis. I took a look at the pandas source, but it's not clear to me where the bug is and how to go about fixing it. Nonetheless, I've found a pretty quick workaround that produces the behavior I would expect. Maybe this will help others with a similar problem or give some direction in fixing the issue. Essentially, the workaround drops the `NaT` value within the level.

Here's an example of the workaround that works for me:

```python
midx = pd.MultiIndex(levels=[[pd.NaT, pd.datetime(2012,1,2), 
                     pd.datetime(2012,1,3)], ['a', 'b']],
                     labels=[[0, 1, 1, 2], [0, 0, 1, 0]], names=['date', None])
df = pd.Series(pd.np.random.rand(4), index=midx)
df.groupby(df.index.get_level_values(0)).count()
```

**Comment by mroeschke** [comment] 2019-02-08 05:15
Looks to be fixed on master. I imagine this edge case could use a test.

```
In [8]: In [4]: pd.__version__
   ...: Out[4]: '0.25.0.dev0+85.g0eddba883'

In [9]: In [7]: midx = pd.MultiIndex(levels=[[pd.NaT, pd.datetime(2012,1,2),
   ...:    ...:                      pd.datetime(2012,1,3)], ['a', 'b']],
   ...:    ...:                      labels=[[0, 1, 1, 2], [0, 0, 1, 0]], names=['date', None])
   ...:    ...: df = pd.Series(pd.np.random.rand(4), index=midx)
   ...:    ...: df.groupby(level=1).mean()
/anaconda3/envs/pandas-dev/bin/ipython:3: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  # -*- coding: utf-8 -*-
Out[9]:
a    0.849207
b    0.877276
dtype: float64

```

**Comment by TrigonaMinima** [comment] 2019-02-13 10:01
@mroeschke 
tried the code on the pandas version 0.24.0, it ran successfully. Could you point me to the file where this test should be added?

**Comment by mroeschke** [comment] 2019-02-13 17:27
`pandas/tests/groupby/test_groupby.py`

**Closed** 2019-02-19 13:32 UTC
Labels: Bug, Groupby, Missing-data, Needs Tests, good first issue
