### ISSUE TITLE
BUG: groupby.groups with multiple grouping columns always treats dropna as False

### ISSUE THREAD

**Issue by sfc-gh-mvashishtha** [pandas-dev/pandas#56850] opened 2024-01-12 21:03 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
        {
            "col1": [None, 1, 1, 0, None, 0],
            "col2": [4, 5, None, 7, 4, 5],
            "col3": [0, 1, 2, 3, 4, 5]
        }
    )

# these two are equal (note that we can't use == to compare because of nulls in the dict)
print(df.groupby(['col1', 'col2'], dropna=False).groups)
print(df.groupby(['col1', 'col2'], dropna=True).groups)
```

### Issue Description

Note that groupby.groups does seem to respect `dropna` for grouping by a single column with nulls, but groupbing by a single column with nulls with `dropna=False` raises `ValueError: Categorical categories cannot be null` due to https://github.com/pandas-dev/pandas/issues/35202.

### Expected Behavior

As with other groupby aggregations, `dropna=True` should drop any group keys where any key column is null.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.9.18.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.2.0
Version             : Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.2.2
pip                 : 23.3.1
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : None
IPython             : 8.18.1
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.4
qtpy                : None
pyqt5               : None

</details>

**Comment by rhshadrach** [comment] 2024-01-12 21:16
Thanks for the report, duplicate of #55919

**Closed by rhshadrach** 2024-01-12 21:16 UTC
Labels: Bug, Needs Triage

**Comment by sfc-gh-mvashishtha** [comment] 2024-01-12 21:44
duplicate of #55919
