### ISSUE TITLE
DataFrameGroupBy.quantile returns -> IndexError: indices are out-of-bounds

### ISSUE THREAD

**Issue by b060149ee** [pandas-dev/pandas#28594] opened 2019-09-24 10:18 UTC
#### Sample Code
```python
df1212 = pd.DataFrame([['a', 1, 1], ['a', 1, 2], ['a', 2, 8 ], ['b', 1, 9 ], ['b', 1, 7], ['b', 2, 1]], columns=['key', 'val', 'val1'])
df1212.groupby(['key','val']).quantile(q=[0.5,0.75])
```
#### Problem description

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-48-0067bad4e229> in <module>
----> 1 df1212.groupby(['key','val']).quantile(q=[0.5,0.75])

~/miniconda/envs/minimal_ds/lib/python3.7/site-packages/pandas/core/groupby/groupby.py in quantile(self, q, interpolation)
   1951             indices = np.concatenate(arrays)
   1952             assert len(indices) == len(result)
-> 1953             return result.take(indices)
   1954 
   1955     @Substitution(name="groupby")

~/miniconda/envs/minimal_ds/lib/python3.7/site-packages/pandas/core/generic.py in take(self, indices, axis, is_copy, **kwargs)
   3602 
   3603         new_data = self._data.take(
-> 3604             indices, axis=self._get_block_manager_axis(axis), verify=True
   3605         )
   3606         result = self._constructor(new_data).__finalize__(self)

~/miniconda/envs/minimal_ds/lib/python3.7/site-packages/pandas/core/internals/managers.py in take(self, indexer, axis, verify, convert)
   1387         n = self.shape[axis]
   1388         if convert:
-> 1389             indexer = maybe_convert_indices(indexer, n)
   1390 
   1391         if verify:

~/miniconda/envs/minimal_ds/lib/python3.7/site-packages/pandas/core/indexers.py in maybe_convert_indices(indices, n)
    199     mask = (indices >= n) | (indices < 0)
    200     if mask.any():
--> 201         raise IndexError("indices are out-of-bounds")
    202     return indices
    203 

IndexError: indices are out-of-bounds

#### Expected Output
Return a DF
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.0-29-generic
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_IN
LOCALE           : en_IN.ISO8859-1

pandas           : 0.25.1
numpy            : 1.17.2
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : 7.8.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : 1.3.8
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
</details>

**Comment by TomAugspurger** [comment] 2019-09-24 19:13
Duplicate of a couple other issues. Fixed on master and 0.25.x. We'll have a release soon.

**Closed by TomAugspurger** 2019-09-24 19:13 UTC
