### ISSUE TITLE
BUG: DataFrame[SparseArray] coerces to dense with .T

### ISSUE THREAD

**Issue by scottgigante** [pandas-dev/pandas#28477] opened 2019-09-17 03:22 UTC
#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
X = np.array([[0, 1, 0], [4, 0, 0]])
X = pd.DataFrame(X).astype(pd.SparseDtype(float, fill_value=0.0))
X.dtypes
X.T.dtypes
```
#### Problem description

Given the entire dataframe is sparse, it should probably remain sparse on transpose?

Current output:
```
>>> import numpy as np
>>> import pandas as pd
>>> X = np.array([[0, 1, 0], [4, 0, 0]])
>>> X = pd.DataFrame(X).astype(pd.SparseDtype(float, fill_value=0.0))
>>> X.dtypes
0    Sparse[float64, 0.0]
1    Sparse[float64, 0.0]
2    Sparse[float64, 0.0]
dtype: object
>>> X.T.dtypes
0    float64
1    float64
dtype: object
```

#### Expected Output

```
>>> import numpy as np
>>> import pandas as pd
>>> X = np.array([[0, 1, 0], [4, 0, 0]])
>>> X = pd.DataFrame(X).astype(pd.SparseDtype(float, fill_value=0.0))
>>> X.dtypes
0    Sparse[float64, 0.0]
1    Sparse[float64, 0.0]
2    Sparse[float64, 0.0]
dtype: object
>>> X.T.dtypes
0    Sparse[float64, 0.0]
1    Sparse[float64, 0.0]
dtype: object
```

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.3.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.0.10-arch1-1-ARCH
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.1
numpy            : 1.17.0
pytz             : 2019.2
dateutil         : 2.8.0
pip              : 19.2.3
setuptools       : 41.0.1
Cython           : None
pytest           : 5.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.1
sqlalchemy       : None
tables           : 3.5.2
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
```

</details>

**Comment by TomAugspurger** [comment] 2019-09-17 18:10
> Given the entire dataframe is sparse, it should probably remain sparse on transpose?

Yep. This is a duplicate of https://github.com/pandas-dev/pandas/issues/22120.

Note however, that there isn't necessarily an efficient way to do this for Sparse. The sparsity is encoded column-wise, so I suspect you'll need to have an intermediate dense representation before returning to sparse.

**Closed by TomAugspurger** 2019-09-17 18:10 UTC
