### ISSUE TITLE
pd.to_datetime throws OutOfBoundsDatetime parsing strings without the year

### ISSUE THREAD

**Issue by mikedeltalima** [pandas-dev/pandas#16154] opened 2017-04-26 22:56 UTC
#### Code Sample, a copy-pastable example if possible

```
pd.to_datetime(pd.Series('5pm april'))

```
#### Problem description
Strings that can be parsed by dateutil fail to parse in pandas. Also, it would be good to set the default date manually and have it default to the current date as it does in dateutil.
>>> print(dateutil.parser.parse('5pm april'))
2017-04-26 17:00:00

#### Output
line 401, in _convert_listlike
    require_iso8601=require_iso8601
  File "pandas/tslib.pyx", line 2374, in pandas.tslib.array_to_datetime (pandas/tslib.c:46691)
  File "pandas/tslib.pyx", line 2557, in pandas.tslib.array_to_datetime (pandas/tslib.c:45585)
  File "pandas/tslib.pyx", line 2525, in pandas.tslib.array_to_datetime (pandas/tslib.c:45052)
  File "pandas/tslib.pyx", line 2519, in pandas.tslib.array_to_datetime (pandas/tslib.c:44933)
  File "pandas/tslib.pyx", line 1538, in pandas.tslib.convert_to_tsobject (pandas/tslib.c:28700)
  File "pandas/tslib.pyx", line 1793, in pandas.tslib._check_dts_bounds (pandas/tslib.c:32835)
pandas.tslib.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-04-01 17:00:00

#### Expected Output
0   2017-04-01 17:00:00
dtype: datetime64[ns]

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.19.2
nose: None
pip: 9.0.1
setuptools: 18.2
Cython: None
numpy: 1.12.1
scipy: 0.18.0
statsmodels: None
xarray: None
IPython: 5.1.0
sphinx: 1.4.6
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
matplotlib: 1.5.3
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext)
jinja2: 2.8
boto: None
pandas_datareader: None

</details>

**Comment by jreback** [comment] 2017-04-26 22:58
this is a duplicate of https://github.com/pandas-dev/pandas/issues/16074
And discussed in #11430

**Closed by jreback** 2017-04-26 22:58 UTC
