### ISSUE TITLE
ENH: Support for multiple comment characters with readers

### ISSUE THREAD

**Issue by ebran** [pandas-dev/pandas#8727] opened 2014-11-04 16:19 UTC
I would be very pleased if Pandas supported multiple comment characters when reading data from files. According to:

```
import pandas as pd
df = pd.read_table("data.dat", comment=("#","@"), delim_whitespace=True)
```

I don't know if this is requires a minor or major implementation effort?

Best,
Erik

**Comment by dansondergaard** [comment] 2016-11-22 07:29
Related:

Would be great if a comment character could actually also be two characters, e.g. "##". For example, in VCF files, some meta data is specified at the beginning of the file with "##" before the actual table starts:

http://www.internationalgenome.org/wiki/Analysis/vcf4.0/

Often one just wants to ignore these, but:

```python
df = pd.read_csv("data.vcf", comment="##")
```

doesn't work. Note that for VCF it won't work to just use `comment="#"` since the header line actually starts with a single "#".

**Comment by wesm** [comment] 2018-07-06 21:53
This would be difficult. I'm closing this for now

**Closed by wesm** 2018-07-06 21:53 UTC
Labels: Difficulty Advanced, Effort Medium, Enhancement, IO CSV, Won't Fix

**Comment by loodvn** [comment] 2022-09-16 21:57
I ran into this feature request when reading a VCF file as the others did.
```
## Metadata
## ...
# Header
col1, col2, etc
```

Is the cparser the difficult part of this change?

**Comment by loodvn** [comment] 2022-09-18 05:55
Starting a draft PR at [#48615](https://github.com/pandas-dev/pandas/pull/48615), I imagine getting the look-ahead into the state machine of C might be a bit tricky but I'll try give it a go if necessary. Also will check benchmarking for any regressions
