### ISSUE TITLE
Enhance: Time series for different types of graphs using plot fuction

### ISSUE THREAD

**Issue by dfrusdn** [pandas-dev/pandas#5774] opened 2013-12-26 00:38 UTC
Basically the problem is if you want to do a bar plot with time series

```
df.plot(kind='bar')

```

it will create a label for every date entry instead one clean label and more dates when you zoom in.

**Comment by jorisvandenbossche** [comment] 2017-01-06 12:14
Closing as a duplicate of #1918

**Closed by jorisvandenbossche** 2017-01-06 12:14 UTC
Labels: Timeseries, Visualization
