### ISSUE TITLE
df.agg gives a TypeError when sending more than one argument with

### ISSUE THREAD

**Issue by taljaards** [pandas-dev/pandas#22079] opened 2018-07-27 09:39 UTC
#### Code Sample

```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(0,30,size=(30, 4)), columns=list('ABCD'))
df = df.set_index(pd.date_range('2018-04-18 06:00:00', '2018-04-22 06:00:00', periods=30))
df['B'][5:15] = np.nan

df.agg('sum', axis=1)  # this works
df.agg('sum', skipna=False)  # this works
# but I want both
df.agg('sum', axis=1, skipna=False)  # this breaks
# TypeError: ("'str' object is not callable", 'occurred at index 2018-04-18 06:00:00')
```
#### Problem description

I need to pass both arguments to `sum`, but giving both gives an error. It works separately.
I need to specify the `aggfunc` as a "variable", since it won't always be the same.

This is a working alternative, but feels hacky when a built-in method is there to do the job:
```py
getattr(df, 'sum')(axis=1, skipna=False)
```

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.23.3
pytest: 3.6.3
pip: 18.0
setuptools: 40.0.0
Cython: 0.28.4
numpy: 1.14.5
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 6.4.0
sphinx: 1.7.5
patsy: 0.5.0
dateutil: 2.7.3
pytz: 2018.5
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.5
feather: None
matplotlib: 2.2.2
openpyxl: 2.5.4
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: 1.0.5
lxml: 4.2.3
bs4: 4.6.0
html5lib: 1.0.1
sqlalchemy: 1.2.10
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment] 2018-07-27 18:55
I think the issue is that `np.sum`, which groupby.agg is using internally, doesn't support `skipna`.

Workaround for now:

```python
df.agg(pd.Series.sum, axis=1, skipna=False)
```

that will eventually go to `pandas.core.nanops.sum`, which accepts both. I'm not sure what the proper fix is here.

cc @WillAyd

**Comment by mroeschke** [comment] 2021-06-21 01:28
This looks to work on master now. Could use a test


```
In [16]:
    ...:
    ...: import pandas as pd
    ...: import numpy as np
    ...: df = pd.DataFrame(np.random.randint(0,30,size=(30, 4)), columns=list('ABCD'))
    ...: df = df.set_index(pd.date_range('2018-04-18 06:00:00', '2018-04-22 06:00:00', periods=30))
    ...: df['B'][5:15] = np.nan

In [17]: df.agg('sum', axis=1, skipna=False)
Out[17]:
2018-04-18 06:00:00.000000000    52.0
2018-04-18 09:18:37.241379310    42.0
2018-04-18 12:37:14.482758620    47.0
2018-04-18 15:55:51.724137931    64.0
2018-04-18 19:14:28.965517241    59.0
2018-04-18 22:33:06.206896551     NaN
2018-04-19 01:51:43.448275862     NaN
2018-04-19 05:10:20.689655172     NaN
2018-04-19 08:28:57.931034482     NaN
2018-04-19 11:47:35.172413793     NaN
2018-04-19 15:06:12.413793103     NaN
2018-04-19 18:24:49.655172413     NaN
2018-04-19 21:43:26.896551724     NaN
2018-04-20 01:02:04.137931034     NaN
2018-04-20 04:20:41.379310344     NaN
2018-04-20 07:39:18.620689655    63.0
2018-04-20 10:57:55.862068965    46.0
2018-04-20 14:16:33.103448275    71.0
2018-04-20 17:35:10.344827586    50.0
2018-04-20 20:53:47.586206896    92.0
2018-04-21 00:12:24.827586206    50.0
2018-04-21 03:31:02.068965517    47.0
2018-04-21 06:49:39.310344827    40.0
2018-04-21 10:08:16.551724137    54.0
2018-04-21 13:26:53.793103448    65.0
2018-04-21 16:45:31.034482758    76.0
2018-04-21 20:04:08.275862069    63.0
2018-04-21 23:22:45.517241379    47.0
2018-04-22 02:41:22.758620689    14.0
2018-04-22 06:00:00.000000000    28.0
dtype: float64
```

**Comment by felixDulys** [comment] 2021-06-25 15:53
take

**Comment by felixDulys** [comment] 2021-06-27 20:07
I am new to contributing to the pandas codebase, so please excuse any noob mistakes :)

Conclusion:
It looks to me like this combination is already being tested [here](https://github.com/pandas-dev/pandas/blob/v1.2.5/pandas/tests/frame/test_reductions.py#L349).

Thought process on this:
In `pandas/tests/frame/test_reductions.py::TestDataFrameAnalytics::test_stat_op_calc`, we are able to test several reductions directly on a DataFrame with various na handling techniques when calling on `assert_stat_op_calc()` ([here](https://github.com/pandas-dev/pandas/blob/v1.2.5/pandas/tests/frame/test_reductions.py#L31)). We can specify `sum` as the operation to test (`opname`) and the flag `has_skipna` (default `True`) assures that we test this functionality when `skipna=False`([here](https://github.com/pandas-dev/pandas/blob/v1.2.5/pandas/tests/frame/test_reductions.py#L90)). 

I propose we close this issue since it appears to work in master (verified +1) and it already has test coverage.

**Comment by mroeschke** [comment] 2021-06-27 20:25
Thanks for verifying @felixDulys! Yes, appears you're right that this is already tested and that we can close this issue.

Happy for you to help on other `good first issue` + `needs tests` open issues!

**Closed by mroeschke** 2021-06-27 20:25 UTC
Labels: Needs Tests, good first issue
