### ISSUE TITLE
ENH: Smaller package size

### ISSUE THREAD

**Issue by dazza-codes** [pandas-dev/pandas#37526] opened 2020-10-30 21:44 UTC
Could the `pandas.tests` package be an optional package?  It consumes a huge portion of the package size, which may not be required for many production purposes.

```
$ du -s /opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/* | sort -n
4	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/testing.py
4	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/_typing.py
4	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/_version.py
12	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/__init__.py
16	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/arrays
24	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/errors
32	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/conftest.py
64	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/api
92	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/compat
92	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/_testing.py
96	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/_config
100	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/tseries
140	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/__pycache__
160	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/util
472	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/plotting
2252	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/io
7360	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/core
16364	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/_libs
20060	/opt/conda/envs/myproject/lib/python3.6/site-packages/pandas/tests
```

The feature-request is that a default `pandas` install would exclude `pandas.tests` and a `pandas[tests]` install would include that package.  The general pattern is that production dependencies (requirements.txt) would use `pandas` and any dev/test/CI dependencies (requirements_dev.txt) would add the optional extra for `pandas[tests]`.

**Comment by jreback** [comment] 2020-10-30 21:48
duplicate of #30741

**Closed by jreback** 2020-10-30 21:48 UTC
Labels: Enhancement, Needs Triage
