### ISSUE TITLE
ENH: Implement to_json() for Panel

### ISSUE THREAD

**Issue by mtrbean** [pandas-dev/pandas#5428] opened 2013-11-04 01:11 UTC
related #4889

Currently the to_json() method only works for Series and DataFrame, and raises NotImplementedError when called on Panel. Would be great to implement it for Panel as well.

For me it is sufficient to loop through all items and convert each item (DataFrame) to json separately and then stitch them together.

Happy to contribute code if needed.

**Comment by nizamov** [comment] 2015-06-02 07:09
Is this issue still open? The functionality is described in docs. If it is still pending then at least it should be clearly documented as not implemented. 

http://pandas.pydata.org/pandas-docs/dev/generated/pandas.Panel.to_json.html#pandas.Panel.to_json

I am checking with 0.16.1 and get 

raise NotImplementedError("'obj' should be a Series or a DataFrame")
NotImplementedError: 'obj' should be a Series or a DataFrame

**Comment by jreback** [comment] 2015-06-02 10:34
well, the issue is still marked as open, and the errors message is pretty clear, so yes.

**Comment by jreback** [comment] 2017-07-10 21:09
closing as Panels are deprecated

**Closed by jreback** 2017-07-10 21:09 UTC
Labels: Enhancement, IO JSON, Panel
