### ISSUE TITLE
to_csv - parameter decimal

### ISSUE THREAD

**Issue by dornech** [pandas-dev/pandas#38981] opened 2021-01-05 22:53 UTC
I think that pandas.to_csv does not properly process the decimal parameter. It seems it is ignored whenever the dataframe to be exported contains a NaN value. This means it is not possible to export pandas in European CSV format.

I am aware that problems with to_csv have been discussed earlier and from these discussions I found the hint to check for NaN values. I am afraid I do not understand the final outcome of alle these previous discussions but I think the current behaviour is not quite correct.

**Comment by jreback** [comment] 2021-01-06 02:07
pls show a reproducible example and links to prior issues

**Comment by dornech** [comment] 2021-01-06 11:21
Thanks for the answer and requesting more info. Prior Issues are pretty
old (0.x releases), so I do not thinkt they are of help.
Here are short examples to demonstrate my issue:

df = pd.DataFrame({'a': [0, 1.1], 'b': [2.2, 3.3]})
df.to_csv("h:\\test1a.csv")
df.to_csv("h:\\test1b.csv", sep=";", decimal=",")

test1a.csv:
,a,b
0,0.0,2.2
1,1.1,3.3
-> OK

test1b.csv:
;a;b
0;0,0;2,2
1;1,1;3,3
-> OK

Now:
df = pd.DataFrame({'a': [0, 1.1], 'b': [2.2, "a"]})
df.to_csv("h:\\test2a.csv")
df.to_csv("h:\\test2b.csv", sep=";", decimal=",")

test2a.csv:
,a,b
0,0.0,2.2
1,1.1,a
-> still OK

test2b.csv
;a;b
0;0,0;2.2
1;1,1;a
-> not OK

expected file content:
;a;b
0;0,0;2,2    <- change here, last element in row
1;1,1;a

I assume that in a column with at least one non-numerical value, the
decimals setting is not applied. In the example I used a string value
but same happens for NULL / NaN values.
I would expect that the decimal setting applies to ALL numerical values.


Am 06.01.2021 um 03:08 schrieb Jeff Reback:

**Comment by attack68** [comment] 2021-01-08 21:01
The issue here might be the column dtypes. Try 

    print(df.dtypes)

And you will find something like:

    a    float64
    b     object
    dtype: object

The key item for column 'b' being 'object' or essentially string, meaning it interprets the 2.2 as "2.2"

**Comment by dornech** [comment] 2021-01-09 18:17
Well, if you download data from a source like Yahoo you will find that - while data is numerical - data my contain null row null symbolized by string "null" or a NULL Value. While this would lead to "wrong" column type, all entries in the row except the "null" entry would be numbers.

In general I would not expect the decimal-parameter to depend on the column type. 
Maybe a "forcedecimal" option is a compromise allowing all numerical values getting the decimal-setting applied irregardless of the column type.

**Comment by attack68** [comment] 2021-01-12 20:47
I think pandas ideology is to be data agnostic. Citing a source like yahoo and expecting pandas to automatically parse its "null"s ignores many other data sources and _their_ specific idiosyncrasies.

Pandas provides the tools deal with these by casting datatypes, and to identify and process values in columns, to allow the `decimal` parameter to work correctly.  

For example the following works fine and you need no additional processing, since both cols are `float64`:

    df = pd.DataFrame({'a': [0, 1.1], 'b': [2.2, None]})
    df.to_csv('file.csv', decimal=',', sep=';')

The following needs some data preprocessing, using functions provided by pandas:

```
df = pd.DataFrame({'a': [0, 1.1], 'b': [2.2, "null"]})
df = df.astype({'b': str})
df.loc[df['b'].str.isalpha(), 'b'] = None
df = df.astype({'b': float})
df.to_csv('file.csv', decimal=',', sep=';')
```
But it is simple to workaround. 

I think if anything a function for a boolean test of 'numeric' elements in columns could be handy here, but nothing else imo.

**Comment by MarcoGorelli** [comment] 2021-01-27 12:09
thanks @attack68 for triaging

closing as I don't think anything else needs doing here, but please do ping if I've misunderstood

**Closed by MarcoGorelli** 2021-01-27 12:09 UTC
Labels: Needs Info
