### ISSUE TITLE
pandas.DataFrame.is_copy has no description in the docs

### ISSUE THREAD

**Issue by stuz5000** [pandas-dev/pandas#19210] opened 2018-01-12 18:16 UTC
#### Code Sample, a copy-pastable example if possible

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.is_copy.html#pandas.DataFrame.is_copy

#### Problem description

It isn't clear what this property tells -- there's no documentation. When does it become true, and when does it become false?

**Comment by jorisvandenbossche** [comment] 2018-01-12 19:36
Thanks for the report. This is a duplicate of https://github.com/pandas-dev/pandas/issues/18799, which initiated the decision to deprecate `is_copy` altogether (although there is still some discussion about that), see the linked issues in that issue.

**Closed by jorisvandenbossche** 2018-01-12 19:36 UTC
