### ISSUE TITLE
BUG: mypy doesn't understand the ~ operand for Series

### ISSUE THREAD

**Issue by imrehg** [pandas-dev/pandas#37489] opened 2020-10-29 16:45 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [x] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# save it like test.py
import pandas as pd

s = pd.Series([False])
print(~s)
```
then running `mypy` on this code I get the following errors:
```bash
$ mypy test.py
test.py:3: error: Too many arguments for "Series"
tesrt.py:4: error: Unsupported operand type for ~ ("Series")
```

#### Problem description

Since the code is correct,  mypy is flagging things wrongly.

#### Expected Output

mypy should accept that `~` operand for Series (as well as the arguments).

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : 5532ae8bfb5e6a0203172f36c0738e9c345956a6
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.2.0.dev0+964.g5532ae8bf
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 50.3.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```

</details>

Also
```
mypy                   0.790
mypy-extensions        0.4.3
```

**Comment by BeanNan** [comment] 2020-11-01 13:54
In the same situation, I'm not reporting any errors here.

**Comment by rhshadrach** [comment] 2021-02-11 03:23
I can't duplicate with master/1.2.x/1.1.x and mypy 0.800/0.790. Can you check

**Comment by MarcoGorelli** [comment] 2021-02-28 13:04
closing as I can't reproduce either

**Closed by MarcoGorelli** 2021-02-28 13:04 UTC
Labels: Bug, Needs Info, Typing
