### ISSUE TITLE
"Concatenation will no longer sort" wording is very inconsistent

### ISSUE THREAD

**Issue by wkzhu** [pandas-dev/pandas#21112] opened 2018-05-17 23:36 UTC
### The wording in the update docs is (emphasis added):
In a future version of pandas `pandas.concat()` will no longer sort the non-concatenation axis when it is not already aligned. (...)

To keep the previous behavior (sorting) and silence the warning, pass `sort=True`.
**To accept the future behavior (no sorting), pass `sort=False`**

https://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#concatenation-will-no-longer-sort

### But the wording in the `FutureWarning` messages is (emphasis added):
Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

**To accept the future behavior, pass `sort=True`.**
To retain the current behavior and silence the warning, pass `sort=False`

https://github.com/pandas-dev/pandas/blob/c4da79b5b322c73d8e61d1cb98ac4ab1e2438b40/pandas/core/indexes/api.py

It needs to be clearer that current default is still `sort=True` but will revert to `sort=False` in a future version.

**Comment by TomAugspurger** [comment] 2018-05-18 02:04
It's confusing because it's wrong :)

Duplicate of https://github.com/pandas-dev/pandas/issues/21101 if you want to take a look at fixing it.

**Closed by TomAugspurger** 2018-05-18 02:04 UTC

**Comment by techvslife** [comment] 2018-05-21 16:56
(also:  Currently the warning doesn't get silenced if you pass "sort=False" (i.e. the true future default behavior)--presumably there should be no warning as long as the sort parameter is explicitly set (passed).)

**Comment by techvslife** [comment] 2018-05-21 18:30
Yes, what happens is that it does not produce the line in the warning (as it does when you omit the sort parameter), but it does print the warning (this is the exact text and line spacing, not sure why the last line looks so strange):

```
C:\Users\mlopez\Anaconda3\lib\site-packages\pandas\core\frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
```

**Comment by TomAugspurger** [comment] 2018-05-21 18:37
Can you make a small reproducible example (with data) that emits the
warning with `sort=False`?

**Comment by techvslife** [comment] 2018-05-21 19:06
Sorry, I'm not having luck reproducing with a small example; may not be a concat command, but a merge command instead.   Unfortunately I don't know what line in code is triggering the warning from the warning.

**Comment by TomAugspurger** [comment] 2018-05-21 19:07
You can make warnings raise. Something like

```
import warnings

warnings.simplefilter("error")
<your code>
```

**Comment by techvslife** [comment] 2018-05-23 22:17
Ok, I found it.  It actually was an append command (not concat or merge).  Adding the sort parameter did remove the warning.  I added the sort=False parameter to this:
`df_B = df_A.append(df_B, verify_integrity=True, sort=False).copy()`

**Comment by TomAugspurger** [comment] 2018-05-26 18:59
Thanks for checking.

**Comment by allayli** [comment] 2018-06-07 15:04
It seems that sort=None is NOT backward compatible.
Why NOT make it True by default? Or any Global config can set it be True?

**Comment by TomAugspurger** [comment] 2018-06-07 15:33
Do you have an example where it isn't backwards compatible?

**Comment by TasneemVKhan** [comment] 2019-05-22 08:57
i had the same error I resolved it using  
store_items = store_items.append(new_store , sort=True)

You just have to add sort =True to your code and the warning disappears

**Comment by Dougz00** [comment] 2020-01-21 20:23
If you are using glob and a loop to read a large number of csv files this also works:
    files = glob.glob(pattern)
    df = pd.DataFrame()
    for f in files:
        df = df.append(pd.read_csv(f),sort=True)

**Comment by jreback** [comment] 2020-01-22 01:35
> If you are using glob and a loop to read a large number of csv files this also works:
> files = glob.glob(pattern)
> df = pd.DataFrame()
> for f in files:
> df = df.append(pd.read_csv(f),sort=True)

@Dougz00 that is exponential time

concatenation a list of data frames ; don’t append 
see the append warnings in the docs
