### ISSUE TITLE
DOC: backslash removed for read_clipboard

### ISSUE THREAD

**Issue by wjandrea** [pandas-dev/pandas#51868] opened 2023-03-09 18:28 UTC
### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)

### Location of the documentation

https://pandas.pydata.org/docs/reference/api/pandas.read_clipboard.html

### Documentation problem

Backslash is missing in the Parameters section:

> `pandas.read_clipboard(sep='\\s+', **kwargs)`
> ...
> **Parameters**
> **sep : _str, default ‘s+’_**
> A string or regex delimiter. The default of ‘s+’ denotes one or more whitespace characters.

---

[Relevant source code](https://github.com/pandas-dev/pandas/blob/v1.5.3/pandas/io/clipboards.py#L23):

```python
def read_clipboard(sep: str = r"\s+", **kwargs):  # pragma: no cover
    r"""
    ...

    Parameters
    ----------
    sep : str, default '\s+'
        A string or regex delimiter. The default of '\s+' denotes
        one or more whitespace characters.

    ...
    """
```

### Suggested fix for documentation

I believe your documentation generator is removing the backslash at some point, so hopefully there's a way to turn that off.

I don't believe this issue has much impact. At worst it could confuse some newcomers, that's about it.

**Comment by topper-123** [comment] 2023-03-27 17:58
Hmm, if we escape the backslash, the raw doc string is wrong (people use that too, e.g. in editors). So this may not be fixable, though the problem is clear enough.

Suggestions welcome on how to fix this of course, but we may have to close it as a cantfix...

**Comment by wjandrea** [comment] 2023-03-29 19:10
@topper-123 How so? The default is `'\\s+'` (from `r'\s+'`). And actually, now that I think about it, `'\s'` is deprecated. So escaping it would be fine, no? The docs would end up with `'\s+'`, which is not ideal, but at least better.

To be extra clear:
signature: `r'\s+'` -> `'\\s+'`
docstring: `r"""... '\s+' ..."""` -> `"... '\\s+' ..."` -> but then print/render: `... '\s+' ...`

**Comment by topper-123** [comment] 2023-03-29 20:01
yes, I think you are right. PR on this welcome.

**Closed** 2023-03-29 23:47 UTC
Labels: Docs
