### ISSUE TITLE
API/BUG: silently-ignored dtype in DataFrame constructor

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#38842] opened 2020-12-31 02:57 UTC
I would expect this to raise rather than silently ignore:
```
df = pd.DataFrame({"A": ["foo", "bar"]}, dtype="i8")

>>> df
     A
0  foo
1  bar

>>> df.dtypes
A    object
dtype: object
```

**Comment by simonjayhawkins** [comment] 2020-12-31 15:36
duplicate of #24435?

**Closed** 2020-12-31 15:36 UTC
Labels: Bug, Constructors, Duplicate
