### ISSUE TITLE
DOC BUG DataFrame.plot() and Series.plot() documentation missing

### ISSUE THREAD

**Issue by jpeacock29** [pandas-dev/pandas#31234] opened 2020-01-23 02:07 UTC
In the [API reference for `DataFrame.plot()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.plot.html#pandas.DataFrame.plot) and [`Series.plot()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.plot.html#pandas.Series.plot) the documentation is missing.

**Comment by jorisvandenbossche** [comment] 2020-01-23 08:48
@jpeacock29 thanks for the report! This is a duplicate of https://github.com/pandas-dev/pandas/issues/29489, and there is an open PR to fix it (should be in 1.0.0)

**Closed by jorisvandenbossche** 2020-01-23 08:48 UTC
