### ISSUE TITLE
BUG: parse_dates in read_csv fails silently

### ISSUE THREAD

**Issue by metazoic** [pandas-dev/pandas#35430] opened 2020-07-28 04:16 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

If `timestamp.csv` contains the following:
```
timestamp
11:22:33.44
11:22:33:44
```
then
```python
df = pandas.read_csv('timestamp.csv', parse_dates=['timestamp'])
df.timestamp.dtype
```
results in
```
dtype('O')
```
because of the malformed timestamp.

#### Problem description

This is a problem because the silent fail does not alert to the malformed timestamp.

#### Expected Output

By contrast,
```python
pandas.to_datetime(df.timestamp)
```
results in an explicit error
```python
ParserError: Unknown string format: 11:22:33:44
```

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8
 
pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 49.2.0.post20200714
Cython           : 0.29.21
pytest           : 5.4.3
hypothesis       : None
sphinx           : 3.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.2
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.2
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.4.4
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.50.1
```

</details>

**Comment by simonjayhawkins** [comment] 2020-07-28 08:43
Thanks @metazoic for the report. This is expected behaviour.

from https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

> If a column or index cannot be represented as an array of datetimes, say because of an unparseable value or a mixture of timezones, the column or index will be returned unaltered as an object data type. For non-standard datetime parsing, use pd.to_datetime after pd.read_csv.

closing as not a bug.

**Closed by simonjayhawkins** 2020-07-28 08:43 UTC
Labels: Bug, Needs Triage

**Comment by metazoic** [comment] 2020-07-29 03:42
@simonjayhawkins Maybe not a bug then, but a requested change in behavior? Otherwise, every `read_csv` with `parse_dates` must be followed by a `dtype` check.

**Comment by simonjayhawkins** [comment] 2020-07-29 09:43
> @simonjayhawkins Maybe not a bug then, but a requested change in behavior? Otherwise, every `read_csv` with `parse_dates` must be followed by a `dtype` check.

feel free to open a feature request (using the supplied template) paying particular attention to `API breaking implications` in the proposal
