### ISSUE TITLE
BUG: Sorting DataFrame with MultiIndex in descending(ascending=False) order cause index slicing to fail with exception.

### ISSUE THREAD

**Issue by zzxttornado** [pandas-dev/pandas#55449] opened 2023-10-09 03:29 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame({"a": ["2023-01-01", "2023-01-01", "2023-02-01", "2023-02-01"], \
		"b": ["2023-01-02", "2023-01-03", "2023-02-02", "2023-02-03"], \
		"c": [1, 2, 3, 4]}).set_index(["a", "b"])
df[:"2023-02-01"]
#                       c
#a          b            
#2023-01-01 2023-01-02  1
#           2023-01-03  2
#2023-02-01 2023-02-02  3
#           2023-02-03  4
dfs = df.sort_index(level=1, ascending=False)
dfs[:"2023-02-01"]
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3879, in __getitem__
#    return self._getitem_slice(key)
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 4284, in _getitem_slice
#    slobj = self.index._convert_slice_indexer(key, kind="getitem")
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 4285, in _convert_slice_indexer
#    indexer = self.slice_indexer(start, stop, step)
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6601, in slice_indexer
#    start_slice, end_slice = self.slice_locs(start, end, step=step)
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 2789, in slice_locs
#    return super().slice_locs(start, end, step)
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6824, in slice_locs
#    end_slice = self.get_slice_bound(end, "right")
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 2733, in get_slice_bound
#    return self._partial_tup_index(label, side=side)
#  File "/home/jeff_zheng/.local/lib/python3.10/site-packages/pandas/core/indexes/multi.py", line 2793, in _partial_tup_index
#    raise UnsortedIndexError(
#pandas.errors.UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'
```

### Issue Description

Can't slice with index when a Dataframe is with MultiIndex, and sorted in Descending order. The slicing will work ok if the index is a single column when sorted in Descending order. 
Seems libalgos.is_lexsorted is returning False on reverse sorted array. 

### Expected Behavior

Would expect slicing to work on reverse sorted data with MultiIndex.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.90.1-microsoft-standard-WSL2
Version             : #1 SMP Fri Jan 27 02:56:13 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.25.1
pytz                : 2022.1
dateutil            : 2.8.2
setuptools          : 59.6.0
pip                 : 22.0.2
Cython              : 3.0.3
pytest              : 6.2.5
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.14.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.7.2
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : 3.0.9
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : 1.4.31
tables              : None
tabulate            : None
xarray              : None
xlrd                : 1.2.0
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by paulreece** [comment] 2023-10-09 22:35
Thanks for reporting the issue.

> Seems libalgos.is_lexsorted is returning False on reverse sorted array.

Since lexographic order is effectively alphabetic order I think the function is working as intended.

As of now I think slicing Multis is only implemented for lexographically sorted Data:

https://github.com/pandas-dev/pandas/blob/e74138cb1cd02211ecfa68e8ca187dcfc381f5f5/pandas/core/indexes/multi.py#L2730-L2757


I'm changing this to an enhancement request as a result.

**Comment by mroeschke** [comment] 2024-08-24 19:46
Thanks for the issue, but it appears this hasn't gotten traction in a while so closing

**Closed by mroeschke** 2024-08-24 19:46 UTC
Labels: Enhancement, MultiIndex
