### ISSUE TITLE
ENH: add an option to not install the tests

### ISSUE THREAD

**Issue by jamestwebber** [pandas-dev/pandas#34300] opened 2020-05-21 19:07 UTC
We've been using pandas as part of a project running on AWS lambda, which means we need it installed as a layer, and layers need to have a total size (when zipped) of 50MB. This is tricky with libraries like pandas which are pretty big (installed size for me is 41 MB by itself, although it compresses to less).

There are existing layers for pandas which we've been using, but recently I looked into getting all of our dependencies into a single layer that we generated ourselves. When I looked into it I was surprised to find a lot of space in pandas is from the tests: 17 MB, so nearly half, is in `pandas/tests`.

#### Describe the solution you'd like

The feature request is to add some logic to `setup.py` to make the tests an optional installation, which will save a lot of space for applications that need it.

#### API breaking implications

This shouldn't break the API unless tests are being imported/used in the main code (I certainly hope they aren't)

#### Describe alternatives you've considered

I can manually remove the tests when I package up the layer, as can anyone else who wants to save the space, but it'd be nice if this was a simple option.

**Comment by charlesdong1991** [comment] 2020-05-21 19:18
xref #30741

**Comment by jamestwebber** [comment] 2020-05-21 19:24
Whoops, I searched but didn't find that issue!

**Comment by mroeschke** [comment] 2020-05-21 19:26
Thanks for the suggestion, but since this looks like a duplicate of #30741, going to close in favor of that issue.

**Closed by mroeschke** 2020-05-21 19:26 UTC
Labels: Build, Testing
