### ISSUE TITLE
Pandas dev requirements broken

### ISSUE THREAD

**Issue by mzjp2** [pandas-dev/pandas#29465] opened 2019-11-07 15:32 UTC
#### Problem description

Trying to install `requirements-dev.txt` fails with 

```
ERROR: botocore 1.13.12 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
```

because of https://github.com/boto/botocore/commit/e87e7a745fd972815b235a9ee685232745aa94f9

I suspect CI/CD pipelines are still okay because it caches dependencies.

#### Expected Output

Installation successful

**Comment by WillAyd** [comment] 2019-11-07 15:45
Thanks for the report. This is a duplicate of https://github.com/pandas-dev/pandas/issues/29413

**Closed by WillAyd** 2019-11-07 15:45 UTC
Labels: Duplicate
