### ISSUE TITLE
Erroneous parsing of big integers with `read_json` 

### ISSUE THREAD

**Issue by oroszgy** [pandas-dev/pandas#24249] opened 2018-12-12 11:15 UTC
#### Code Sample, a copy-pastable example if possible

```python
>>> import pandas as pd
>>> data = pd.read_json('[{"id":"111111111111111111"}]')
>>> print(data)
                   id
0  111111111111111104
```
#### Problem description

The `read_json` method erroneously parses big integers represented as string.

#### Expected Output
```
                   id
0  111111111111111111
```

#### Output of ``pd.show_versions()``

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.0.final.0
python-bits: 64
OS: Darwin
OS-release: 18.0.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_us.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: 4.0.1
pip: 18.1
setuptools: 40.6.2
Cython: 0.29.1
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.1.1
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: 1.2.14
pymysql: None
psycopg2: None
jinja2: None
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by WillAyd** [comment] 2018-12-12 14:18
There should already be an issue about this if you search the tracker

**Comment by WillAyd** [comment] 2018-12-12 15:16
Duplicate of #20608

**Closed by WillAyd** 2018-12-12 15:16 UTC
