### ISSUE TITLE
BUG: _table_mod is 'NoneType' when it should not be

### ISSUE THREAD

**Issue by tmuntianu** [pandas-dev/pandas#27253] opened 2019-07-05 22:00 UTC
#### Code Sample, a copy-pastable example if possible

```python
import supereeg as se
brain_object = se.load('example_data')
brain_object.save('example.bo')
```
#### Problem description

The package I work on, [SuperEEG](https://github.com/ContextLab/supereeg), uses [deepdish](https://github.com/uchicago-cs/deepdish) for HDF5 loading and saving. Deepdish includes Pandas as a dependency, and when attempting to save an object, pandas throws the following error: `AttributeError: 'NoneType' object has no attribute 'exceptions'`
However, with pandas 0.23.4, the object saves to disk without issue.

#### Expected Output

File saves to disk

#### Full stacktrace

<details>

Traceback (most recent call last):
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\pandas\io\pytables.py", line 1160, in get_node
    return self._handle.get_node(self.root, key)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\tables\file.py", line 1644, in get_node
    node = where._v_file._get_node(nodepath)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\tables\file.py", line 1599, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\tables\file.py", line 437, in get_node
    node = self.node_factory(key)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\tables\group.py", line 1181, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\tables\group.py", line 398, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``//locs``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\supereeg\brain.py", line 638, in save
    dd.io.save(fname, bo, compression=compression)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\deepdish\io\hdf5io.py", line 584, in save
    filters=filters, idtable=idtable)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\deepdish\io\hdf5io.py", line 253, in _save_level
    store.put(group._v_pathname + '/' + name, level)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\pandas\io\pytables.py", line 889, in put
    self._write_to_group(key, value, append=append, **kwargs)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\pandas\io\pytables.py", line 1367, in _write_to_group
    group = self.get_node(key)
  File "C:\Users\Tudor\Anaconda3\envs\supereeg_env\lib\site-packages\pandas\io\pytables.py", line 1161, in get_node
    except _table_mod.exceptions.NoSuchNodeError:
AttributeError: 'NoneType' object has no attribute 'exceptions'

</details>

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2efb60717bda9fc64344c5f6647d58564930808e
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : None.None

pandas           : 0.25.0rc0+0.g2efb60717.dirty
numpy            : 1.16.4
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.1.1
setuptools       : 41.0.1
Cython           : 0.29.11
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.1
numexpr          : 2.6.9
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : None
scipy            : 1.3.0
sqlalchemy       : None
tables           : 3.5.2
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None

</details>

**Comment by jreback** [comment] 2019-07-05 22:10
not really clear how you are using pandas
needs a reproducible example

**Comment by tmuntianu** [comment] 2019-07-05 22:16
I'm not sure how to produce a reproducible example without using my package, but at the end of the day it's pretty clear from the [reducing import time comments](https://github.com/pandas-dev/pandas/blob/8ea102acdb45bb70cb30ea77108a50054c28c24d/pandas/io/pytables.py#L227) that it is definitely possible for _table_mod to be NoneType, which then doesn't allow the try except block to go through.

Although I can't really reproduce this using any other method, the _table_mod is can often be NoneType. Pandas 0.23.4 doesn't throw [NoSuchNodeError](https://github.com/pandas-dev/pandas/blob/8ea102acdb45bb70cb30ea77108a50054c28c24d/pandas/io/pytables.py#L1236), and as such the try except block works.

**Comment by jreback** [comment] 2019-07-21 00:37
closing, this is not a bug in pandas rather an issue in the subclass code.

**Closed by jreback** 2019-07-21 00:37 UTC
Labels: Data IO
