### ISSUE TITLE
import is failing in windows in 1.0.3 version

### ISSUE THREAD

**Issue by jaydave1988** [pandas-dev/pandas#32971] opened 2020-03-24 10:14 UTC
Import is failing in 1.0.3 version of panda in windows. It was working in 0.22 version

>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\groupby\generic.py", line 60, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\frame.py", line 124, in <module>
    from pandas.core.series import Series
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\series.py", line 4572, in <module>
    Series._add_series_or_dataframe_operations()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\generic.py", line 10349, in _add_series_or_dataframe_operations
    from pandas.core.window import EWM, Expanding, Rolling, Window
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\window\__init__.py", line 1, in <module>
    from pandas.core.window.ewm import EWM  # noqa:F401
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pandas\core\window\ewm.py", line 5, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: DLL load failed: The specified module could not be found.
>>> exit()

C:\Users\Administrator>pip uninstall pandas
Found existing installation: pandas 1.0.3
Uninstalling pandas-1.0.3:
  Would remove:
    c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pandas-1.0.3.dist-info\*
    c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\pandas\*
Proceed (y/n)? y
  Successfully uninstalled pandas-1.0.3

**Comment by jorisvandenbossche** [comment] 2020-03-24 11:05
Can you check if installing pandas 1.0.2 works? (there was a change in how the wheels are created in 1.03, so if 1.0.2 still works, it might be due to that)

**Comment by TomAugspurger** [comment] 2020-03-24 12:34
Duplicate of https://github.com/pandas-dev/pandas/issues/32857.

1.0.2 is also affected.

**Closed by TomAugspurger** 2020-03-24 12:34 UTC
