### ISSUE TITLE
Performance of ExtensionArray display in DataFrame/Series

### ISSUE THREAD

**Issue by samgd** [pandas-dev/pandas#43020] opened 2021-08-13 15:17 UTC
When printing a DataFrame/Series that is backed by an ExtensionArray the values are first converted to a numpy array:

https://github.com/pandas-dev/pandas/blob/c03ee857f880f94461d3344c11bfb703885fde00/pandas/io/formats/format.py#L1561-L1574

This is problematic for ExtensionArrays that are very expensive to convert to numpy arrays. i.e. converting an extremely large ExtensionArray to a numpy array to ultimately print ~10 values.

Can this be overcome or worked around? There is a already a special case for categorical here.

**Comment by samgd** [comment] 2021-08-13 15:19
Tagging @jreback as you may be able to help given the git blame?

**Comment by jbrockmendel** [comment] 2021-08-18 17:19
PR to address this would be welcome

**Comment by TomAugspurger** [comment] 2021-11-15 15:26
I believe this is a duplicate of / covered by https://github.com/pandas-dev/pandas/issues/26837.

https://github.com/pandas-dev/pandas/issues/26837#issuecomment-967268492 has a proposed addition to the ExtensionArray interface to allow the EA to control the conversion from array -> List[str]

**Closed by TomAugspurger** 2021-11-15 15:26 UTC
Labels: Performance, Output-Formatting, ExtensionArray
