### ISSUE TITLE
"Querying a table" within Sector HDF5 in User Guide

### ISSUE THREAD

**Issue by xushengun** [pandas-dev/pandas#32039] opened 2020-02-16 10:57 UTC
#### Code Sample, a copy-pastable example if possible

string = "HolyMoly'"
store.select('df','index == string')

```
#### Problem description
string = "HolyMoly'" do not work 

pandas 1.0.1

**Comment by MarcoGorelli** [comment] 2020-02-16 12:41
Thanks @xushengun 

The following works for me:
```
>>> import pandas as pd                                                                                     
>>> store = pd.HDFStore('store.h5')                                                                         
>>> df = pd.DataFrame([1], index=['HolyMoly'])
>>> store.append('df', df)
>>> string = "HolyMoly" 
>>> store.select('df', 'index == string')
          0
HolyMoly  1
```

Seems that there's a typo in the user guide:
```
string = "HolyMoly'"
```
instead of
```
string = "HolyMoly"
```
, are you interested in submitting a pull request to fix it?

**Comment by danjglick** [comment] 2020-02-17 00:01
take

**Comment by virajmavani** [comment] 2020-02-18 16:58
take

**Comment by PSY27** [comment] 2020-02-20 16:23
i am intrested in doing it

**Comment by MarcoGorelli** [comment] 2020-02-21 13:57
> Seems that there's a typo in the user guide:

closing there's no reproducible example, and as it turns out this was intentional

**Closed by MarcoGorelli** 2020-02-21 13:57 UTC
Labels: Docs, good first issue
