### ISSUE TITLE
pandas groupby RETURNS ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long long'

### ISSUE THREAD

**Issue by anuragupadhyaya** [pandas-dev/pandas#27270] opened 2019-07-07 03:55 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by anuragupadhyaya** [comment] 2019-07-07 03:57
Itrain_test.groupby(['col_1', 'col_2']).apply(lambda x: x['col_3'].nunique())
After updating to pandas 0.24 this is returning the below error.
ValueError                                Traceback (most recent call last)
<ipython-input-22-6e70ad33c60a> in <module>()
----> 1 train_test.loc[:, 'N_0'] = train_test.groupby(['molecule_name', 'atom_index_1']).apply(lambda x: x['atom_index_0'].nunique())

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\indexing.py in __setitem__(self, key, value)
    188             key = com.apply_if_callable(key, self.obj)
    189         indexer = self._get_setitem_indexer(key)
--> 190         self._setitem_with_indexer(indexer, value)
    191 
    192     def _validate_key(self, key, axis):

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\indexing.py in _setitem_with_indexer(self, indexer, value)
    364                         new_indexer = convert_from_missing_indexer_tuple(
    365                             indexer, self.obj.axes)
--> 366                         self._setitem_with_indexer(new_indexer, value)
    367 
    368                         return self.obj

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\indexing.py in _setitem_with_indexer(self, indexer, value)
    467 
    468             if isinstance(value, ABCSeries):
--> 469                 value = self._align_series(indexer, value)
    470 
    471             info_idx = indexer[info_axis]

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\indexing.py in _align_series(self, indexer, ser, multiindex_indexer)
    738                         return ser._values.copy()
    739 
--> 740                     return ser.reindex(new_ix)._values
    741 
    742                 # 2 dims

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\series.py in reindex(self, index, **kwargs)
   3732     @Appender(generic.NDFrame.reindex.__doc__)
   3733     def reindex(self, index=None, **kwargs):
-> 3734         return super(Series, self).reindex(index=index, **kwargs)
   3735 
   3736     def drop(self, labels=None, axis=0, index=None, columns=None,

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\generic.py in reindex(self, *args, **kwargs)
   4344         # perform the reindex on the axes
   4345         return self._reindex_axes(axes, level, limit, tolerance, method,
-> 4346                                   fill_value, copy).__finalize__(self)
   4347 
   4348     def _reindex_axes(self, axes, level, limit, tolerance, method, fill_value,

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4357             ax = self._get_axis(a)
   4358             new_index, indexer = ax.reindex(labels, level=level, limit=limit,
-> 4359                                             tolerance=tolerance, method=method)
   4360 
   4361             axis = self._get_axis_number(a)

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\indexes\multi.py in reindex(self, target, method, level, limit, tolerance)
   2234             else:
   2235                 # hopefully?
-> 2236                 target = MultiIndex.from_tuples(target)
   2237 
   2238         if (preserve_names and target.nlevels == self.nlevels and

E:\WorkSpace\Anaconda\lib\site-packages\pandas\core\indexes\multi.py in from_tuples(cls, tuples, sortorder, names)
    394                 tuples = tuples._values
    395 
--> 396             arrays = list(lib.tuples_to_object_array(tuples).T)
    397         elif isinstance(tuples, list):
    398             arrays = list(lib.to_object_array_tuples(tuples).T)

pandas\_libs\lib.pyx in pandas._libs.lib.tuples_to_object_array()

ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long long'

**Comment by jbrockmendel** [comment] 2019-07-07 05:43
The traceback looks like it is raising, not returning.  Am I missing something?

**Comment by anuragupadhyaya** [comment] 2019-07-07 05:50
Oops mybad, I m trying to edit the Issue Name but not able to do it.

**Comment by WillAyd** [comment] 2019-07-07 16:42
@anuragupadhyaya do you have a reproducible code example? Nothing here can be copy / pasted to replicate

**Comment by WillAyd** [comment] 2019-07-11 04:00
Closing for now but if you have a reproducible example feel free to reopen

**Closed by WillAyd** 2019-07-11 04:00 UTC
Labels: Needs Info
