### ISSUE TITLE
BUG: `read_parquet` gives "Passed non-file path" in v1.0.4 but works in v1.0.3

### ISSUE THREAD

**Issue by dmitry-kabanov** [pandas-dev/pandas#34803] opened 2020-06-15 15:23 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas as pd
pd.read_parquet("https://www.tangel.se/wind/wind_frames/wind-2018.parquet")
```

#### Problem description

There is some regression in the interaction of Pandas v1.0.4 and Pyarrow.

The above code downloads a Parquet file when Pandas is v1.0.3.
However, in v1.0.4 it generates the error:
```
  File "<python-env>/lib/python3.8/site-packages/pandas/io/parquet.py", line 315, in read_parquet
    return impl.read(path, columns=columns, **kwargs)
  File "<python-env>/lib/python3.8/site-packages/pandas/io/parquet.py", line 130, in read
    parquet_ds = self.api.parquet.ParquetDataset(
  File "<python-env>/lib/python3.8/site-packages/pyarrow/parquet.py", line 1171, in __init__
    self.metadata_path) = _make_manifest(
  File "<python-env>/lib/python3.8/site-packages/pyarrow/parquet.py", line 1367, in _make_manifest
    raise OSError('Passed non-file path: {}'
OSError: Passed non-file path: https://www.tangel.se/wind/wind_frames/wind-2018.parquet
```

I can confirm that the bug appears with Pyarrow of versions 0.15.1 and 0.17.1 on Python 3.7 and 3.8.

#### Expected Output

```
                     x             y          u          v  ...  altitude  height        date   time
0        361912.978162  6.139641e+06   5.338025   5.958648  ...         5      10  2018-01-01  06:00
1        361912.978162  6.139641e+06  10.008798  11.172465  ...         5      10  2018-01-01  09:00
2        361912.978162  6.139641e+06  14.252365   4.676546  ...         5      10  2018-01-01  12:00
3        361912.978162  6.139641e+06  14.107182   7.549001  ...         5      10  2018-01-01  15:00
4        361912.978162  6.139641e+06   8.650998   6.794132  ...         5      10  2018-01-01  18:00
...                ...           ...        ...        ...  ...       ...     ...         ...    ...
1449984  804603.972910  7.610557e+06  -1.789940   0.190043  ...       330      10  2018-12-31  19:00
1449985  804603.972910  7.610557e+06  -1.646950  -0.947394  ...       330      10  2018-12-31  20:00
1449986  804603.972910  7.610557e+06  -1.078928  -0.725200  ...       330      10  2018-12-31  21:00
1449987  804603.972910  7.610557e+06   0.302022  -1.057725  ...       330      10  2018-12-31  22:00
1449988  804603.972910  7.610557e+06   0.920168  -0.391524  ...       330      10  2018-12-31  23:00

[1449989 rows x 9 columns]
```

#### Output of ``pd.show_versions()``

<details>

```
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.7.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.4
numpy            : 1.18.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 46.4.0.post20200518
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.1.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 0.17.1
pytables         : None
pytest           : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.3.17
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : 0.49.1
```

</details>

**Comment by TomAugspurger** [comment] 2020-06-15 15:32
This is a duplicate of a couple other issues. We're prepping a 1.0.5 release to fix this. Should be out today or tomorrow.

**Closed by TomAugspurger** 2020-06-15 15:32 UTC
Labels: Bug, Needs Triage
