### ISSUE TITLE
BUG: can't install 2.1.0rc0. "Inconsistent version: expected '2.1.0rc0', but metadata has '0+unknown'"

### ISSUE THREAD

**Issue by sim-dt** [pandas-dev/pandas#54686] opened 2023-08-22 10:57 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
$ pip install pandas==2.1.0rc0
Defaulting to user installation because normal site-packages is not writeable
Collecting pandas==2.1.0rc0
  Downloading pandas-2.1.0rc0.tar.gz (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 3.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested pandas==2.1.0rc0 from https://files.pythonhosted.org/packages/a9/ec/e531733ff7f955e58ac45089cf72d085e587a731778b9dac1b82878815e9/pandas-2.1.0rc0.tar.gz, but installing version 0+unknown
Discarding https://files.pythonhosted.org/packages/a9/ec/e531733ff7f955e58ac45089cf72d085e587a731778b9dac1b82878815e9/pandas-2.1.0rc0.tar.gz (from https://pypi.org/simple/pandas/) (requires-python:>=3.9): Requested pandas==2.1.0rc0 from https://files.pythonhosted.org/packages/a9/ec/e531733ff7f955e58ac45089cf72d085e587a731778b9dac1b82878815e9/pandas-2.1.0rc0.tar.gz has inconsistent version: expected '2.1.0rc0', but metadata has '0+unknown'
ERROR: Could not find a version that satisfies the requirement pandas==2.1.0rc0 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0rc0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0rc0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0rc0)
ERROR: No matching distribution found for pandas==2.1.0rc0

```

### Issue Description

Failed to install pandas 2.1.0rc0 on aarch64 linux with pip version 22.3.1

### Expected Behavior

I would expect pip install to complete successfully.

### Installed Versions

None, pandas failed to install

**Comment by MarcoGorelli** [comment] 2023-08-22 12:32
first, thanks a tonne for trying out the release candidate - this will help find bugs

you're missing `--pre`:
```console
pip install --pre pandas==2.1.0rc0
```

**Comment by jorisvandenbossche** [comment] 2023-08-28 20:40
It's a very confusing error message, though .. (but that might be something to change in pip)

One aspect of the error message is about that it says pandas "0+unknown" is being installed, and this seems a bit suspicious to me? (whether it's actually causing an error or not) Shouldn't meson know the version that is being installed in case of an sdist? 

When doing this locally in a clean env with just python 3.11 and pip, and forcing to install from source (`pip install pandas==2.1.0rc0 --no-binary :all: -vv`), I see this in the logs:

```
  Running command Preparing metadata (pyproject.toml)
  + meson setup /tmp/pip-install-f8zrapsi/pandas_fc85d78ad59e4974b7f12ea4b78cf97a /tmp/pip-install-f8zrapsi/pandas_fc85d78ad59e4974b7f12ea4b78cf97a/.mesonpy-6m9c4vnf/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-f8zrapsi/pandas_fc85d78ad59e4974b7f12ea4b78cf97a/.mesonpy-6m9c4vnf/build/meson-python-native-file.ini
  The Meson build system
  Version: 1.0.1
  Source dir: /tmp/pip-install-f8zrapsi/pandas_fc85d78ad59e4974b7f12ea4b78cf97a
  Build dir: /tmp/pip-install-f8zrapsi/pandas_fc85d78ad59e4974b7f12ea4b78cf97a/.mesonpy-6m9c4vnf/build
  Build type: native build
  Project name: pandas
  Project version: 0+unknown
  C compiler for the host machine: ccache cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
  C linker for the host machine: cc ld.bfd 2.34
  C++ compiler for the host machine: ccache c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
  C++ linker for the host machine: c++ ld.bfd 2.34
  Cython compiler for the host machine: cython (cython 0.29.36)
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (/home/joris/miniconda3/envs/test-pip/bin/python3.11)
  Found pkg-config: /usr/bin/pkg-config (0.29.1)
  Build targets in project: 53

  pandas 0+unknown

    User defined options
      Native files: /tmp/pip-install-f8zrapsi/pandas_fc85d78ad59e4974b7f12ea4b78cf97a/.mesonpy-6m9c4vnf/build/meson-python-native-file.ini
      buildtype   : release
      b_ndebug    : if-release
      b_vscrt     : md

  Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-phixijme/normal/bin/ninja
  + /tmp/pip-build-env-phixijme/normal/bin/ninja
  [1/151] Generating pandas/_libs/khash_primitive_helper_pxi with a custom command
```

Shouldn't meson-python know the correct version for the sdist?

cc @lithomas1

**Comment by jorisvandenbossche** [comment] 2023-08-28 20:47
And I tried doing the same for a previous RC, pandas 2.0.0rc0, where this actually worked:

```
$ mamba create -n test-pip python=3.11
$ conda activate test-pip
(test-pip) $ pip install pandas==2.0.0rc0 --no-binary :all: -vv
...
Successfully installed numpy-1.25.2 pandas-2.0.0rc0 python-dateutil-2.8.2 pytz-2023.3 six-1.16.0
```

so this might actually be a regression?

**Comment by lithomas1** [comment] 2023-08-28 20:47
I think I patched this in #54525.

Can you try [from nightlies]https://anaconda.org/scientific-python-nightly-wheels/pandas/2.1.0rc0%2B111.g7a16d92286/download/pandas-2.1.0rc0%2B111.g7a16d92286.tar.gz?

(I realize now that the tag for the nightlies seems to be messed up as well, it should be 2.2.0dev0 not 2.1.0rc0, but that's since I repushed 2.1.0rc0 since the wheel builds didn't trigger for the rc. 
I'll repush the tags on Wednesday, so the version on dev should work)

**Comment by jorisvandenbossche** [comment] 2023-08-29 10:24
Indeed, installing the latest nightly sdist works. And since https://github.com/pandas-dev/pandas/pull/54525 was backported, assuming this will also work for 2.1.0. So closing as fixed.

**Closed by jorisvandenbossche** 2023-08-29 10:24 UTC
Labels: Build, Regression

**Comment by sim-dt** [comment] 2023-08-29 10:33
Thanks guys
