### ISSUE TITLE
BUG: groupby behavior changed since 1.4.x

### ISSUE THREAD

**Issue by Yikun** [pandas-dev/pandas#46893] opened 2022-04-29 03:51 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
# After 1.4.x
>>> import pandas as pd
>>> pdf = pd.DataFrame({"timestamp": [0.0], "car_id": ["A"]})
>>> pdf.groupby("car_id").apply(lambda _: pd.DataFrame({"column": [0.0]})).index
Int64Index([0], dtype='int64')
>>> pdf.groupby("car_id").apply(lambda _: pd.DataFrame({"column": [0.0]}))
   column
0     0.0
```

### Issue Description

groupby behavior changed since 1.4.x

### Expected Behavior
```python
# Before 1.4.x
>>> import pandas as pd
>>> pdf = pd.DataFrame({"timestamp": [0.0], "car_id": ["A"]})
>>> pdf.groupby("car_id").apply(lambda _: pd.DataFrame({"column": [0.0]})).index
MultiIndex([('A', 0)],
           names=['car_id', None])
>>> pdf.groupby("car_id").apply(lambda _: pd.DataFrame({"column": [0.0]}))
          column
car_id
A      0     0.0
```

### Installed Versions

<details>

1.4.x

</details>

**Comment by Yikun** [comment] 2022-04-29 04:00
First bad commit: https://github.com/pandas-dev/pandas/commit/d037ff6a4757bf8af2ca2431ba7d4b22b1959075

cc @jbrockmendel

**Comment by twoertwein** [comment] 2022-04-29 16:35
Potentially a duplicate of #45315

**Comment by jbrockmendel** [comment] 2022-04-30 01:55
The bisected commit removed apply_frame_axis0, which was a fastpath that behaved subtly differently from the non-fastpath in ways that we were never really able to consistently debug.  The non-fastpath (new and current) behavior is the canonically correct behavior.

**Comment by rhshadrach** [comment] 2022-04-30 23:16
In 1.5, you'll be able to specify the `group_keys` argument to groupby, and apply will adhere to it.

**Comment by simonjayhawkins** [comment] 2022-05-04 09:42
> Potentially a duplicate of #45315

closing as duplicate and resolved by calling out this breaking change in the 1.4 release notes https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html#groupby-apply-consistent-transform-detection

**Closed by simonjayhawkins** 2022-05-04 09:42 UTC
Labels: Bug, Groupby, Apply, Closing Candidate
