### ISSUE TITLE
BUG: strange behaviour in quantile with group by

### ISSUE THREAD

**Issue by abdullahodibat** [pandas-dev/pandas#33569] opened 2020-04-15 16:02 UTC
is this a bug in pandas? why null values in the grouped by field break the quantile?

``` 
df = pd.DataFrame({
    'category': ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B'],
    'value': [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
})
quantiles = df.groupby('category')['value'].quantile(0.75)
print(quantiles)

df2 = pd.DataFrame({
    'category': ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B', np.nan],
    'value': [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6,1]
})
quantiles2 = df2.groupby('category')['value'].quantile(0.75)
print(quantiles2) 
```

produces this output:
```
category
A    4.75
B    4.75
Name: value, dtype: float64
category
A    3.75
B    3.75
Name: value, dtype: float64
```

im using pandas 1.0.3

**Comment by simonjayhawkins** [comment] 2020-04-19 12:15
Thanks @abdullahodibat for the report. duplicate of https://github.com/pandas-dev/pandas/issues/33200#issuecomment-611049285


> im using pandas 1.0.3

this is a regression between 0.24 and 0.25 (#20405)

**Closed** 2020-05-25 21:58 UTC
Labels: Bug, Groupby, Numeric
