### ISSUE TITLE
BUG: Pandas 2.x iloc assignment does not reassign in some scenarios

### ISSUE THREAD

**Issue by KianShepherd** [pandas-dev/pandas#55302] opened 2023-09-26 20:17 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(data={'x': ['foo', 'bar', 'baz']})

print(df.dtypes)

df.iloc[:, 0] = df.iloc[:, 0].astype('category')

print(df.dtypes)
```
Output:
```
x    object
dtype: object
x    object
dtype: object

```

### Issue Description

Reassigning an existing column within a table to with a type converted version of itself does not work. In the given example I would expect the type of column x to be `category` but it seems to not get reassigned.

The output of `print(df.iloc[:, 0].astype('category'))` using the example table is correct. But the assignment seems to do nothing.
```
0    foo
1    bar
2    baz
Name: x, dtype: category
Categories (3, object): ['bar', 'baz', 'foo']
```

### Expected Behavior

The reassignment using `iloc` should replace the existing column with the new one.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.10.13.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 6.5.3-arch1-1
Version             : #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000
machine             : x86_64
processor           :
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.25.2
pytz                : 2022.7.1
dateutil            : 2.8.2
setuptools          : 65.5.0
pip                 : 23.2.1
Cython              : 3.0.0a11
pytest              : 7.1.2
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : 8.15.0
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 9.0.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : None
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.3
qtpy                : None
pyqt5               : None

</details>

**Comment by mroeschke** [comment] 2023-09-26 21:02
Thanks for the report. Closing as duplicate of https://github.com/pandas-dev/pandas/issues/52593

**Closed by mroeschke** 2023-09-26 21:02 UTC
Labels: Bug, Needs Triage
