### ISSUE TITLE
BUG: pandas read_csv silently switches date parsing scheme in the middle of reading file corrupting data

### ISSUE THREAD

**Issue by jontis** [pandas-dev/pandas#37895] opened 2020-11-16 17:55 UTC
In pandas 1.1.4

```python
# Your code here
pd.DataFrame(data={'timestamp':  ['13/06/2018', '12/06/2018']}).to_csv('test.csv', index=False)
pd.read_csv('test.csv', parse_dates=['timestamp'])

Out[84]: 
   timestamp
0 2018-06-13
1 2018-12-06
```

#### Problem description

I provoked pandas here (initially by mistake) by letting it parse a file with date format day / month / year, with it's default parser month / day / year. To my horror, it parses the ones that give a valid date with the default parser, and automatically uses the alternative parser on the ones that fails. Giving a mix of dates and without any warning. 

#### Expected Output
Pandas should have failed with an error, or a very severe warning when a date failed to parse with the same parser as the other dates. It should not be allowed to use different parsing schemes within the same data file.

<details>

pandas           : 1.1.4
numpy            : 1.19.4
pytz             : 2020.4
dateutil         : 2.8.1

</details>

**Comment by jreback** [comment] 2020-11-16 18:55
this is a duplicate issue
pls have a look - and welcome patches

**Comment by jontis** [comment] 2020-11-16 20:08
I have noticed some issues and discussions about pandas being "flexible" and being able to infer date format and handle different date formats within files. I may consider it a questionable strength to be able to read different date formats from different feature columns, but switching format within the same column is very dangerous and should be off by default.

**Comment by jreback** [comment] 2020-11-17 03:37
duplicate of #12585
bugs - even long standing ones are fixed by community contributions which we are happy to take

**Closed** 2020-11-17 03:38 UTC
Labels: Duplicate, IO CSV, Timeseries
