### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by TomAugspurger** [pandas-dev/pandas#29034] opened 2019-10-16 16:35 UTC
As discussed in https://github.com/pandas-dev/pandas/issues/27492.

The 0.25.x branch should be stable for the next release, so we can start on this at any time.

**Comment by topper-123** [comment] 2019-10-18 00:40
I'd be positive to deprecate python 3.5. It's old and 3.6 brings a lot of changes, so make sense to not support 3.5 in a long-term stable version.

An idea could be to make a dual release 0.26 and 1.0. They would have identical code bases, but 0.26 would support py3.5 and 1.0 would support py3.6, so it would only be a minor chang in setup.py.

**Comment by TomAugspurger** [comment] 2019-10-18 02:18
Why do you think we need a deprecation?

**Comment by topper-123** [comment] 2019-10-18 06:28
Sorry, I miswrote that, i meant drop.

**Comment by TomAugspurger** [comment] 2019-10-18 11:37
Gotcha, thanks.

FTR, https://numpy.org/neps/nep-0029-deprecation_policy.html has September 2019 as the cutoff for 3.5.

**Comment by WillAyd** [comment] 2019-10-24 16:18
@pandas-dev/pandas-core do we have thoughts on this? The only thing I can think of that warrants a 0.25.3 release right now might be the fix in #29173

If there isn't an appetite for that release I think we should drop 35 from CI now

**Comment by jreback** [comment] 2019-10-24 16:21
+1 in dripping 3.5 for 1.0

this wouldn’t affect 0.25.x

**Comment by WillAyd** [comment] 2019-10-24 16:24
I’m talking specifically about dropping from CI. I’m leaning towards maybe cutting a 25.3 for the regression fix and dropping 35 after that

**Comment by jreback** [comment] 2019-10-24 17:27
whether we cut 0.25.3 is irrelevant
we have no reason to change the 0.25.x CI

**Comment by WillAyd** [comment] 2019-10-24 17:28
Ah OK. So OK to drop from CI on master and if we want a 0.25.3 can target the 0.25.x branch directly?

**Comment by jreback** [comment] 2019-10-24 17:57
right as usual would merge a patch to master and back port to 0.25.x

**Comment by TomAugspurger** [comment] 2019-10-24 18:05
+1 for dropping from master.

**Comment by datapythonista** [comment] 2019-10-24 19:06
+1, let's do it then: #29212

**Comment by jorisvandenbossche** [comment] 2019-10-25 11:46
Are there specific 3.6 features we want to start using once 3.5 is dropped?

https://docs.python.org/3/whatsnew/3.6.html

f-strings seems to be one (although I would personally not do a "big cleanup" to move existing ones). And we can now also rely on dict ordering (although I think we already did for >= 3.6, so probably only need to remove the compat code for 3.5 regarding that).  
There are also some typing related enhancements (variable annotations).

**Comment by wesm** [comment] 2019-10-25 14:50
FYI

```
$ pypistats python_minor pandas
| category | percent | downloads  |
|----------|--------:|-----------:|
| 3.6      |  36.90% | 33,733,634 |
| 2.7      |  35.00% | 31,997,724 |
| 3.5      |  13.96% | 12,760,015 |
| 3.7      |  11.77% | 10,760,426 |
| 3.4      |   1.62% |  1,483,707 |
| null     |   0.67% |    616,051 |
| 3.8      |   0.06% |     58,035 |
| 2.6      |   0.02% |     18,017 |
| 3.3      |   0.00% |        835 |
| 3.9      |   0.00% |         57 |
| 3.2      |   0.00% |         55 |
| 3.1      |   0.00% |          3 |
| Total    |         | 91,428,559 |
```

**Comment by WillAyd** [comment] 2019-10-25 16:55
@jorisvandenbossche I commented in the PR instead of here (here would have been better...) but yea your list and my list for follow ups to this are pretty much aligned

https://github.com/pandas-dev/pandas/pull/29212#issuecomment-546065347

Can open follow up issues for those after we get this merged

**Comment by WillAyd** [comment] 2019-10-25 17:00
@wesm so one of the motivating factors for dropping this as well is alignment with NEP 29, which suggests dropping Py35 support for anything release Dec 19 onwards:

https://numpy.org/neps/nep-0029-deprecation_policy.html

Do you see that as problematic? I'm surprised 3.5 is as high on that list (I vaguely recall seeing other lists where it was much lower) but curious what you might be thinking

**Closed** 2019-11-08 14:48 UTC
Labels: Python 3.5
