### ISSUE TITLE
xticks missing for scatter plots with colors

### ISSUE THREAD

**Issue by adamgreenhall** [pandas-dev/pandas#10611] opened 2015-07-17 19:52 UTC
example: https://www.wakari.io/sharing/bundle/adamgreenhall/test-scatter

I think this happens specifically for pandas scatter plots with colorbars in ipython. The xticks are still working for:
- non-colorbar pandas scatter plots
- the same scatter plot using matplotlib
- standard python scripts using `plt.savefig`

related problem with `%matplotlib inline`?: https://github.com/ipython/ipython/issues/1443/

**Comment by sinhrks** [comment] 2015-07-17 21:47
Thanks for the report. 

Strange, may be related to the order or method of ax, plot and colorbar creation...? We should specify the occurrence condition.

**Comment by rubennj** [comment] 2015-07-23 13:34
I was checking previous versions of Pandas and I can confirm that the bug starts in 0.16.1 and it is still in 0.16.2

**Comment by denfromufa** [comment] 2015-08-11 16:21
I hit this bug as well (0.16.2), and I can confirm that this problem appears only with `%matplotlib inline`

**Comment by denfromufa** [comment] 2015-08-11 16:31
as a quick workaround use ax.xaxis.tick_top()

**Comment by denfromufa** [comment] 2015-10-26 20:06
`sharex=False` is better workaround, see answer on SO: http://stackoverflow.com/a/31633381/2230844

**Comment by dr-1** [comment] 2017-08-29 12:31
Still an issue in 0.20.3

**Comment by jreback** [comment] 2017-08-29 12:38
@dr-1 PR's to fix are welcome. or event a simple repro on 20.3, as this issue is still open

**Comment by labarba** [comment] 2017-10-20 17:11
I encountered this bug also. See screenshots of the two versions of the plot, one with colors, one without. The full notebook (without output, as it's still WiP) is at: http://go.gwu.edu/engcomp2lesson4

<img width="679" alt="screen shot 2017-10-20 at 1 07 56 pm" src="https://user-images.githubusercontent.com/4800109/31833240-fc0cc6ae-b597-11e7-894a-a5feeec28646.png">

<img width="678" alt="screen shot 2017-10-20 at 1 08 11 pm" src="https://user-images.githubusercontent.com/4800109/31833261-05b274ce-b598-11e7-9393-4ec1d2c50b60.png">

**Comment by javadnoorb** [comment] 2018-03-14 22:52
I'm having this issue in pandas 0.22.0 running in Jupyter notebook. Would it solve the issue to hardcode `sharex=False` as default into arguments of `ScatterPlot.__init__` in `/pandas/plotting/_core.py`?

**Comment by TomAugspurger** [comment] 2018-03-16 16:56
For reference, here's the MPL code that we're calling: https://github.com/pandas-dev/pandas/blob/8a5830305d2d9a087fbe46bd968218104ffdfc49/pandas/plotting/_core.py#L872-L877

**Comment by javadnoorb** [comment] 2018-03-19 15:18
Not sure if this is a duplicate, but I dug a bit deeper into the code. It is happening in _handle_shared_axes. If you comment the following line the issue disappears:
https://github.com/pandas-dev/pandas/blob/8a5830305d2d9a087fbe46bd968218104ffdfc49/pandas/plotting/_core.py#L255

it seems to stem from this line:
https://github.com/pandas-dev/pandas/blob/8a5830305d2d9a087fbe46bd968218104ffdfc49/pandas/plotting/_core.py#L426

I tried running the code from within _core.py to explore this more closely. Compare this:

```
%matplotlib inline
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random((100,3)),columns=['A','B','C'])

plot_obj = ScatterPlot(df, x='A', y='B',c='C')
plot_obj._args_adjust()
plot_obj._compute_plot_data()
plot_obj._setup_subplots()
plot_obj._make_plot()
plot_obj._add_table()
plot_obj._make_legend()


all_axes = plot_obj._get_subplots()
nrows, ncols = plot_obj._get_axes_layout()
_handle_shared_axes(axarr=all_axes, nplots=len(all_axes),
                    naxes=nrows * ncols, nrows=nrows,
                    ncols=ncols, sharex=plot_obj.sharex,
                    sharey=plot_obj.sharey)

for ax in plot_obj.axes:
    plot_obj._post_plot_logic_common(ax, plot_obj.data)
    plot_obj._post_plot_logic(ax, plot_obj.data)
```

![image](https://user-images.githubusercontent.com/26352146/37603970-44a9a398-2b66-11e8-8a12-bb8f8e923e00.png)

with this:

```
%matplotlib inline
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random((100,3)),columns=['A','B','C'])

plot_obj = ScatterPlot(df, x='A', y='B',c='C')
plot_obj._args_adjust()
plot_obj._compute_plot_data()
plot_obj._setup_subplots()
plot_obj._make_plot()
plot_obj._add_table()
plot_obj._make_legend()


all_axes = plot_obj._get_subplots()
nrows, ncols = plot_obj._get_axes_layout()
# _handle_shared_axes(axarr=all_axes, nplots=len(all_axes),
#                     naxes=nrows * ncols, nrows=nrows,
#                     ncols=ncols, sharex=plot_obj.sharex,
#                     sharey=plot_obj.sharey)

for ax in plot_obj.axes:
    plot_obj._post_plot_logic_common(ax, plot_obj.data)
    plot_obj._post_plot_logic(ax, plot_obj.data)
```

![image](https://user-images.githubusercontent.com/26352146/37604025-68987824-2b66-11e8-9154-75857ce4b9a6.png)

**Comment by TomAugspurger** [comment] 2018-03-19 15:26
@javadnoorb thanks for looking. So your suspicion is that if we excluded the newly created colorbar axes from `_handle_shared_axes`, everything would be OK? Do you have time to explore that further?

**Comment by TomAugspurger** [comment] 2018-03-19 15:28
FWIW, extracting the colorbar axes may be a tad difficult, but we should be able to hack something together.

**Comment by javadnoorb** [comment] 2018-03-19 15:45
That's my guess @TomAugspurger. I vaguely remember that I extracted colorbar axes before, and as you said it was not very straightforward. I'll look more into this within the next couple of days and will get back to you.

**Comment by TomAugspurger** [comment] 2018-03-19 15:47
FWIW, we're creating the colorbar axes, and we control every method here, so as a last resort you could add a private attribute like `__is_pandas_colorbar` to the colorbar axes and skip it during `_handle_shared_axes`

**Comment by javadnoorb** [comment] 2018-03-19 16:02
That's a good idea. `_handle_shared_axes` seems to be just a few `for` loops through the axes, so that would probably resolve this. Could that conflict with other subplottings with colorbars?

**Comment by TomAugspurger** [comment] 2018-03-19 16:07
No idea, but probably :)

IIRC, the only other code we have is from hexbin. I don't recall if it
shares an implementation with scatter.

On Mon, Mar 19, 2018 at 11:02 AM, Javad Noorbakhsh <notifications@github.com

**Comment by javadnoorb** [comment] 2018-03-20 00:51
@TomAugspurger  I'm going through this code. You're right. Extracting colorbars is not very easy. I think what you suggested with the private attribute is the way to go. The issue as far as I can tell is that axes are matploltlib objects, so I don't know of any clean way to define a private attribute for them without inheritance. Any ideas?

We also need to be careful with `_handle_shared_axes`:
https://github.com/pandas-dev/pandas/blob/8a5830305d2d9a087fbe46bd968218104ffdfc49/pandas/plotting/_tools.py#L299
It loops through all axes and uses `_remove_labels_from_axis` to remove the axes unless they are the last row/column or sharex/sharey=False. Simply skipping the colorbar axes wouldn't solve the problem, because by default when sharex=True, `_remove_labels_from_axis` will be applied to the axis. One solution I can think of is to set nrows=nrows-1 if  __is_pandas_colorbar is in axarr. This won't mess up with multiplots (although we might want to do the same to ncols as well?). But it's a bit hacky. Any better solution you can think of?

A second way to deal with this might be to alter layout:
https://github.com/pandas-dev/pandas/blob/8a5830305d2d9a087fbe46bd968218104ffdfc49/pandas/plotting/_tools.py#L308
whenever there is only one non-colorbar axis.

Beside scatter, colorbars seem to only be used by hexbin, and they don't seem to share any code except through PlanePlot. Their colorbar implementation is very similar. So I think resolving the issue with scatter should similarly affect hexbin.

**Comment by javadnoorb** [comment] 2018-03-20 01:06
The above hacks I was thinking of assume that we're dealing with a single scatterplot with a single colorbar. A more general solution to deal with multiplots will require more work.

**Comment by TomAugspurger** [comment] 2018-03-20 12:09
The hack I had in mind was getting the new cbar ax from

```
self.fig.colorbar(img, **kws)
```

and then directly adding a `_pandas_colorbar_axes` like `ax._pandas_colorbar_axes = True`

Then in the _handle_shared_axes we'll skip axes where `getattr(ax, '_pandas_colorbar_axes', False)` is True.

**Comment by javadnoorb** [comment] 2018-03-20 13:20
Interesting. I didn't know it was possible to assign attributes to objects in python. That's a pretty nice feature!

**Comment by TomAugspurger** [comment] 2018-03-20 13:28
It's rightly considered a hack :)

**Comment by javadnoorb** [comment] 2018-03-20 13:50
I like it! 

I think skipping `getattr(ax, '_pandas_colorbar_axes', False)` will avoid removing tick labels from all the axes except for colorbars. So it will interfere with subplots if there are multiple plots. Don't you think?

I think we need something like `axarr=[ax for ax in axarr if getattr(ax, '_pandas_colorbar_axes', False)]` and corresponding changes to `nplots, naxes, nrows, ncols` in the first line of `_handle_shared_axes`

**Comment by TomAugspurger** [comment] 2018-03-21 01:53
I’m not sure. I don’t even know what the interaction of a color at and subplots is.

________________________________

**Comment by javadnoorb** [comment] 2018-03-22 01:15
@TomAugspurger, I made your suggested changes in my own fork:
https://github.com/javadnoorb/pandas

seems to be working fine:

```
%matplotlib inline
import numpy as np
from mypandas import pandas as pd
df = pd.DataFrame(np.random.random((1000,3)),columns=['A','B','C'])
df.plot.scatter('A','B',c='C');
df.plot.hexbin('A','B', gridsize=25);
```

![image](https://user-images.githubusercontent.com/26352146/37745615-256baf16-2d4c-11e8-97b5-2ec4a4ceb835.png)

![image](https://user-images.githubusercontent.com/26352146/37745631-3eedf016-2d4c-11e8-88cd-d3b47a000b7f.png)

Will probably require more testing. But I've never done this. What's the proper testing procedure before PR?

**Comment by TomAugspurger** [comment] 2018-03-22 01:24
Ideally you'd write a test that fails without your changes, apply the
changes, and then make sure the test passes with your changes.

But feel free to make a PR whenever.

**Comment by TomAugspurger** [comment] 2018-03-30 11:39
So @javadnoorb has submitted #20446, but I notice that with matplotlib 2.2.2 I'm getting the correct output on pandas master (without @javadnoorb's fix).

Would the people in this thread mind updating to matplotlib 2.2.2 and try out this code:

```python

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

x = np.arange(20)
y = np.sin(x)
c = np.hstack([np.ones_like(x[:10]) * 0.25,
               np.ones_like(x[10:]) * 0.75])

ax2 = pd.DataFrame({'x': x, 'y': y, 'c': c}).plot.scatter(x='x', y='y', c='c', cmap='viridis');
```

My figure has the xaxis visible

![gh](https://user-images.githubusercontent.com/1312546/38136601-255c1f70-33e5-11e8-86c4-78160c1b5cc9.png)

**Comment by javadnoorb** [comment] 2018-03-30 13:42
I upgraded to matplotlib 2.2.2 and still get the old result? @TomAugspurger are you running this in Jupyter notebook?

**Comment by TomAugspurger** [comment] 2018-03-30 14:14
I was not. I'd forgotten that it was just for the inline backend. Nevermind
then.

**Comment by javadnoorb** [comment] 2018-03-30 14:21
I had forgotten too. But I think this is an issue. I suspect the tests we've written for the PR are going to always pass. We need tests to run with inline backend.

**Closed** 2018-07-04 12:59 UTC
Labels: Visualization

**Comment by Raquelie** [comment] 2019-03-25 11:31
I am having the same issue

**Comment by giliam** [comment] 2019-05-21 13:55
Same here, executing from a Jupyter Notebook (I haven't fully understood whether it is important or not) with Matplotlib version greater than 3.0.

**Comment by slsongge** [comment] 2019-08-18 14:39
I hit this bug as well, and I found a solution that add one ax.

https://stackoverflow.com/questions/52631031/make-pandas-plot-show-xlabel-and-xvalues

![image](https://user-images.githubusercontent.com/36298417/63225944-e0e2d600-c208-11e9-9c6e-a6642022cfa3.png)
