### ISSUE TITLE
DOC: convert_dtypes method is not converted to URL

### ISSUE THREAD

**Issue by jorijnsmit** [pandas-dev/pandas#33648] opened 2020-04-19 08:13 UTC
Somehow the method `convert_dtypes` in the "See also" box is not a URL, whereas all the other ones are: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html

**Comment by dsaxton** [comment] 2020-04-19 16:52
Thanks, I believe this is a duplicate of https://github.com/pandas-dev/pandas/issues/32295 and is now fixed

**Closed** 2020-04-19 18:11 UTC
Labels: Docs, Duplicate
