### ISSUE TITLE
printing Series in Jupyter/IPython opens and closes a terminal window

### ISSUE THREAD

**Issue by allthedata** [pandas-dev/pandas#14546] opened 2016-10-31 15:57 UTC
When Git for Windows is installed and the option to use Unix tools in the Windows command line is checked, printing a Series in Jupyter QTConsole or Notebook (or Jupyter consoles in IDEs like Spyder) causes a terminal window to quickly pop up and close. Sometimes this happens in other cases where the Series is not necessarily printed, and I have experienced many terminal windows popping up and closing one after the other.

```python
import pandas as pd
pd.Series([1])
```

This seems to be due to [series.py](https://github.com/pandas-dev/pandas/blob/47f117d18a99f8bbaf2ecbc7829d198d304b8c2a/pandas/core/series.py#L1005) calling the  `get_terminal_size()` function in [terminal.py](https://github.com/pandas-dev/pandas/blob/47f117d18a99f8bbaf2ecbc7829d198d304b8c2a/pandas/util/terminal.py). That function states that it should only be used when running in a terminal and not in IPython GUIs, but `series.py` is calling it regardless. It then fails to find the terminal size and falls back to calling the `tput` command, which only exists in Windows if Cygwin/Git for Windows is installed, and causes a terminal window to be briefly opened.

Possibly related issue: http://stackoverflow.com/questions/36133447/pandas-printing-tput-unknown-terminal-emacs

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.1.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.18.1
nose: 1.3.7
pip: 8.1.2
setuptools: 27.2.0
Cython: 0.24.1
numpy: 1.11.1
scipy: 0.18.1
statsmodels: 0.6.1
xarray: None
IPython: 5.1.0
sphinx: 1.3.1
patsy: 0.4.1
dateutil: 2.5.3
pytz: 2016.6.1
blosc: None
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: None
jinja2: 2.8
boto: 2.42.0
pandas_datareader: None

</details>

**Comment by jorisvandenbossche** [comment] 2016-11-23 12:55
@allthedata Thanks for the report. Would you like to try to do a PR to fix this? It should be fairly simple to detect if we are in a terminal or not.

**Comment by jorisvandenbossche** [comment] 2016-11-23 12:58
It can probably just use `get_console_size` (defined here https://github.com/pandas-dev/pandas/blob/04f6cde53126aafe55e883511b7e687a77ce80b0/pandas/formats/format.py#L2494) which already includes such a check.

**Comment by Foucl** [comment] 2017-03-14 14:01
@allthedata, @jorisvandenbossche thank you for figuring out the issue. I can confirm that replacing `pandas.util.terminal.get_terminal_size()` with `pandas.formats.format.get_console_size()` in series.py fixes the issue of cmd windows popping up due to `tput.exe` calls.

I am not a developer and also I wouldn't know how to write a test for this issue. Still, I'd be happy to submit a pull request (https://github.com/Foucl/pandas/commit/4fed3a51c6610b4071767e6c47e7fd1843722843) if you think that would be helpful.

**Comment by jreback** [comment] 2017-03-14 14:29
@Foucl yeah don't worry about a test for this, would be tricky to do that. If you'd make the change and add a release note would be enough.

**Comment by zlatkom** [comment] 2017-08-25 22:16
FYI, I have the same issue with  _Pandas 0.20.1_ on 
Python 3.6.1 
Anaconda 4.4.0 (64-bit)
IPython 5.3.0 

Is there a fix for this? The notes above don't seem to work for me.

**Comment by zlatko-minev** [comment] 2017-11-06 23:24
SOLVED:   Update to pandas=0.20.3 or better!

**Closed** 2017-11-07 19:57 UTC
Labels: Bug, Difficulty Novice, Effort Low, good first issue, Output-Formatting
