### ISSUE TITLE
BUG: df.to_excel returns an error

### ISSUE THREAD

**Issue by mukerong** [pandas-dev/pandas#34060] opened 2020-05-07 23:17 UTC
Hello,

I run the sample script in pandas [to_excel documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html). However, it throws an error.

#### Code Sample, a copy-pastable example

```python
# Your code here
df1 = pd.DataFrame([['a', 'b'], ['c', 'd']],
                   index=['row 1', 'row 2'],
                   columns=['col 1', 'col 2'])
df1.to_excel("output.xlsx")  
```

#### Problem description

Here is the screenshot of the issue:
![image](https://user-images.githubusercontent.com/23180334/81353467-01e0a500-907e-11ea-884f-c2dec2dd5b76.png)

Openpyxl installed while installing pandas through pip.

**Comment by vipulrai91** [comment] 2020-05-08 07:22
@mukerong  This works for me, can you please add the o/p of **pd.show_versions()**

**Comment by MarcoGorelli** [comment] 2020-05-11 18:41
thanks @vipulrai91 for the report

Closing as I can't reproduce this on 1.0.3 or on the master branch, feel free to reopen if you provide the output of `pd.show_versions()` (as in the issue template)

**Closed by MarcoGorelli** 2020-05-11 18:41 UTC
Labels: Needs Info

**Comment by mukerong** [comment] 2020-05-13 00:26
![image](https://user-images.githubusercontent.com/23180334/81758069-a8111e00-9475-11ea-9449-9893c2199aa6.png)
Still have issues running it. let me know if other info is needed.

**Comment by MarcoGorelli** [comment] 2020-05-13 06:53
Thanks @mukerong - does it work for you if you update to the latest version  (1.0.3)?
