### ISSUE TITLE
DOC: fix EX03 errors in docstrings

### ISSUE THREAD

**Issue by natmokval** [pandas-dev/pandas#56804] opened 2024-01-09 23:41 UTC
pandas has a script for validating docstrings

https://github.com/pandas-dev/pandas/blob/b7e2202459eadc9dd599cbe58251ecc930798b97/ci/code_checks.sh#L72-L172

Currently, some methods fail the EX03 check.

The task here is:
- take 2-4 methods
- run: scripts/validate_docstrings.py --format=actions --errors=EX03 `method-name`
- check if validation docstrings passes for those methods, and if it’s necessary fix the docstrings according to whatever error is reported
- remove those methods from code_checks.sh
- commit, push, open pull request

Please don't comment `take` as multiple people can work on this issue. You also don't need to ask for permission to work on this, just comment on which methods are you going to work.

If you're new contributor, please check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing.html)

thanks @MarcoGorelli for giving me the idea for this issue.

**Comment by roadrollerdafjorst** [comment] 2024-01-10 04:39
I can take the first two methods.
- `pandas.Series.dt.day_name`
- `pandas.Series.str.len`

**Comment by luke396** [comment] 2024-01-10 05:14
I will work for:
`pandas.Series.cat.set_categories`
`pandas.Series.plot.bar`
`pandas.Series.plot.hist`

**Comment by svrashank** [comment] 2024-01-10 09:52
Working on : 
* pandas.Series.plot.line 
* pandas.Series.to_sql

**Comment by Deekshita-S** [comment] 2024-01-10 10:51
working on:

- pandas.DataFrame.loc  
-  pandas.DataFrame.iloc 
-  pandas.DataFrame.describe

**Comment by asishm** [comment] 2024-01-10 13:25
> * scripts/validate_docstrings.py --format=actions --errors=EX03 name-of-the-method

looking at the script, it looks like it ignores all the arguments if there is `func_name` provided (unsure if intentional)
https://github.com/pandas-dev/pandas/blob/5fc2ed2703a1370207f4ebad834e665b6c2ad42f/scripts/validate_docstrings.py#L448-L458

This results in additional errors being returned. For instance running this for `pandas.DataFrame.sort_values` shows 2 errors as below. The first one is an ES01 check while the second is the actual EX03 error.

```
2 Errors found for `pandas.DataFrame.sort_values`:
        No extended summary found
        flake8 error: line 14, col 4: E121 continuation line under-indented for hanging indent
```

A minor tweak would be a nice enhancement to show the error code along with the description (in case it was intentional)

```patch
diff --git a/scripts/validate_docstrings.py b/scripts/validate_docstrings.py
index 76d64d27b2..d623efe8c1 100755
--- a/scripts/validate_docstrings.py
+++ b/scripts/validate_docstrings.py
@@ -432,7 +432,7 @@ def print_validate_one_results(func_name: str) -> None:
             if err_code == "EX02":  # Failing examples are printed at the end
                 sys.stderr.write("\tExamples do not pass tests\n")
                 continue
-            sys.stderr.write(f"\t{err_desc}\n")
+            sys.stderr.write(f"{err_code}:\t{err_desc}\n")
     else:
         sys.stderr.write(f'Docstring for "{func_name}" correct. :)\n')
 ```

which then shows the following for `pandas.DataFrame.sort_values`

```
2 Errors found for `pandas.DataFrame.sort_values`:
ES01:   No extended summary found
EX03:   flake8 error: line 14, col 4: E121 continuation line under-indented for hanging indent
```

**Comment by asishm** [comment] 2024-01-10 18:30
I wrote a comment but accidentally deleted it 🤦‍♂️

tl;dr - if a method is passed to `validate_docstrings.py` it ignores all the other arguments and returns all errors.

**Comment by lukasld** [comment] 2024-01-10 19:20
Im new to this and maybe I overlook something fundamental: <br> I wanted to take on some of these docstrings, I however run into an issue and am not sure what I am doing wrong.
<p>
After executing:

```
python3 validate_docstrings.py --format=actions --errors=EX03 pandas.errors.SpecificationError
```
I get a list of `flake8 - errors`:

```
flake8 error: line 4, col 40: E261 at least two spaces before inline comment
...
```
However, after adding an extra space and saving the docstring for `SpecificationError` in this case in
```
./pandas/errors/__init__.py
``` 
and rerunning the above `validation_docstrings.py` again, the script returns the same errors, as if the change had no effect.

**Comment by lukasld** [comment] 2024-01-10 19:36
Otherwise id take:

- `pandas.errors.SettingWithCopyWarning`
- `pandas.errors.SpecificationError`
- `pandas.errors.UndefinedVariableError`

**Comment by tiffanyxiao** [comment] 2024-01-11 03:54
Working on: 
- pandas.errors.DatabaseError 
- pandas.errors.IndexingError
- pandas.errors.InvalidColumnName
Thank you!

**Comment by svrashank** [comment] 2024-01-11 07:11
So for `pandas.Series.plot.line` its giving following errors: 
* `Unknown parameters {'color'}`
* `flake8 error: line 4, col 4: E121 continuation line under-indented for hanging indent`
* `flake8 error: line 6, col 4: E123 closing bracket does not match indentation of opening bracket's line`
I am new to this , can someone help me in understanding 'line 4,col 4' of what ? I can't seem to locate where it is pointing me towards. Thanks in advance

**Comment by jordan-d-murphy** [comment] 2024-01-11 07:27
Hi all, I've opened a PR for the following 

pandas.core.groupby.DataFrameGroupBy.describe 
pandas.core.groupby.DataFrameGroupBy.idxmax 
pandas.core.groupby.DataFrameGroupBy.idxmin 
pandas.core.groupby.DataFrameGroupBy.value_counts

**Comment by jordan-d-murphy** [comment] 2024-01-11 07:47
Hi all, I've opened a PR for the following

pandas.core.resample.Resampler.fillna 
pandas.core.groupby.SeriesGroupBy.describe 
pandas.DataFrame.last 
pandas.DataFrame.plot.hist

**Comment by svrashank** [comment] 2024-01-11 10:27
> Im new to this and maybe I overlook something fundamental: I wanted to take on some of these docstrings, I however run into an issue and am not sure what I am doing wrong.
> 
> After executing:
> 
> ```
> python3 validate_docstrings.py --format=actions --errors=EX03 pandas.errors.SpecificationError
> ```
> 
> I get a list of `flake8 - errors`:
> 
> ```
> flake8 error: line 4, col 40: E261 at least two spaces before inline comment
> ...
> ```
> 
> However, after adding an extra space and saving the docstring for `SpecificationError` in this case in
> 
> ```
> ./pandas/errors/__init__.py
> ```
> 
> and rerunning the above `validation_docstrings.py` again, the script returns the same errors, as if the change had no effect.

Even I am new and facing similar issue . Even after making the changes the error logs don't change

**Comment by asishm** [comment] 2024-01-11 10:33
EX03 is the errors for the example code-blocks in a function/method's documentation

for `pandas.errors.SpecificationError` the examples show:

```py
Examples
--------
>>> df = pd.DataFrame({'A': [1, 1, 1, 2, 2],
...                    'B': range(5),
...                    'C': range(5)})
>>> df.groupby('A').B.agg({'foo': 'count'}) # doctest: +SKIP
... # SpecificationError: nested renamer is not supported

>>> df.groupby('A').agg({'B': {'foo': ['sum', 'max']}}) # doctest: +SKIP
... # SpecificationError: nested renamer is not supported

>>> df.groupby('A').agg(['min', 'min']) # doctest: +SKIP
... # SpecificationError: nested renamer is not supported
```

line 4 here would be the 4th line in the examples which is `>>> df.groupby('A').B.agg({'foo': 'count'}) # doctest: +SKIP` 

line 6 would be `>>> df.groupby('A').agg({'B': {'foo': ['sum', 'max']}}) # doctest: +SKIP`

**Comment by natmokval** [comment] 2024-01-11 10:46
> EX03 is the errors for the example code-blocks in a function/method's documentation
> 
> for `pandas.errors.SpecificationError` the examples show:
> 
> ```python
> Examples
> --------
> >>> df = pd.DataFrame({'A': [1, 1, 1, 2, 2],
> ...                    'B': range(5),
> ...                    'C': range(5)})
> >>> df.groupby('A').B.agg({'foo': 'count'}) # doctest: +SKIP
> ... # SpecificationError: nested renamer is not supported
> 
> >>> df.groupby('A').agg({'B': {'foo': ['sum', 'max']}}) # doctest: +SKIP
> ... # SpecificationError: nested renamer is not supported
> 
> >>> df.groupby('A').agg(['min', 'min']) # doctest: +SKIP
> ... # SpecificationError: nested renamer is not supported
> ```
> 
> line 4 here would be the 4th line in the examples which is `>>> df.groupby('A').B.agg({'foo': 'count'}) # doctest: +SKIP`
> 
> line 6 would be `>>> df.groupby('A').agg({'B': {'foo': ['sum', 'max']}}) # doctest: +SKIP`

@asishm what kind of flake8 errors did you get?

**Comment by asishm** [comment] 2024-01-11 10:50
```
        flake8 error: line 4, col 40: E261 at least two spaces before inline comment
        flake8 error: line 6, col 52: E261 at least two spaces before inline comment
        flake8 error: line 8, col 36: E261 at least two spaces before inline comment
```

**Comment by jordan-d-murphy** [comment] 2024-01-11 10:55
@asishm can you try adding a space before each of these `#` symbols ![image](https://github.com/pandas-dev/pandas/assets/35613487/6307cc8a-c89a-45ac-b161-fa3902c428af)

**Comment by asishm** [comment] 2024-01-11 10:56
yeah that's the fix - sorry if it wasn't clear, it was more of an explanation for people that had trouble figuring out the lines affected.

**Comment by jordan-d-murphy** [comment] 2024-01-11 10:58
Okay! Makes sense. Hope the photo might help someone else then 🙂

**Comment by lukasld** [comment] 2024-01-11 15:08
> > Im new to this and maybe I overlook something fundamental: I wanted to take on some of these docstrings, I however run into an issue and am not sure what I am doing wrong.
> > After executing:
> > ```
> > python3 validate_docstrings.py --format=actions --errors=EX03 pandas.errors.SpecificationError
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I get a list of `flake8 - errors`:
> > ```
> > flake8 error: line 4, col 40: E261 at least two spaces before inline comment
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, after adding an extra space and saving the docstring for `SpecificationError` in this case in
> > ```
> > ./pandas/errors/__init__.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and rerunning the above `validation_docstrings.py` again, the script returns the same errors, as if the change had no effect.
> 
> Even I am new and facing similar issue . Even after making the changes the error logs don't change

Maybe it `numpydoc` or another library is caching the results? Not sure...

**Comment by jordan-d-murphy** [comment] 2024-01-11 22:17
I've fixed pandas.Series.to_latex

**Comment by jordan-d-murphy** [comment] 2024-01-12 09:31
I'll take these:

 pandas.core.resample.Resampler.interpolate 
 pandas.pivot  
 pandas.merge_asof 
 pandas.wide_to_long
 pandas.Index.rename 
 pandas.Index.isin 
 pandas.IndexSlice

**Comment by luke396** [comment] 2024-01-13 03:54
This is the name of the method that I have put together, and no one has yet taken on it. (Most likely there is an error, as this is what I checked completely manually)

- [ ] pandas.errors.CategoricalConversionWarning 
- [ ] pandas.errors.ChainedAssignmentError 
- [ ] pandas.errors.ClosedFileError  
- [ ] pandas.errors.NumExprClobberingError 
- [ ] pandas.errors.PossibleDataLossError 
- [ ] pandas.errors.PossiblePrecisionLoss 
- [ ] pandas.errors.SettingWithCopyError 
- [ ] pandas.errors.ValueLabelTypeMismatch 
- [ ] pandas.Timestamp.ceil 
- [ ] pandas.Timestamp.floor
- [ ] pandas.Timestamp.round 
- [ ] pandas.ExcelWriter 
- [ ] pandas.read_json 
- [ ] pandas.io.json.build_table_schema 
- [ ] pandas.io.formats.style.Styler.to_latex 
- [ ] pandas.read_parquet 
- [ ] pandas.DataFrame.to_sql 
- [ ] pandas.read_stata 
- [ ] pandas.plotting.scatter_matrix 
- [ ] pandas.Index.droplevel 
- [ ] pandas.CategoricalIndex.set_categories 
- [ ] pandas.MultiIndex.names 
- [ ] pandas.MultiIndex.droplevel 
- [ ] pandas.DatetimeIndex.month_name
- [ ] pandas.DatetimeIndex.day_name
- [ ] pandas.core.window.rolling.Rolling.corr
- [ ] pandas.Grouper
- [ ] pandas.core.groupby.SeriesGroupBy.apply
- [ ] pandas.core.groupby.DataFrameGroupBy.apply
- [ ] pandas.core.groupby.SeriesGroupBy.transform
- [ ] pandas.core.groupby.SeriesGroupBy.pipe
- [ ] pandas.core.groupby.DataFrameGroupBy.pipe
- [ ] pandas.core.groupby.DataFrameGroupBy.boxplot
- [ ] pandas.core.groupby.DataFrameGroupBy.hist
- [ ] pandas.io.formats.style.Styler.map
- [ ] pandas.io.formats.style.Styler.apply_index
- [ ] pandas.io.formats.style.Styler.map_index
- [ ] pandas.io.formats.style.Styler.format
- [ ] pandas.io.formats.style.Styler.format_index
- [ ] pandas.io.formats.style.Styler.relabel_index
- [ ] pandas.io.formats.style.Styler.hide
- [ ] pandas.io.formats.style.Styler.set_td_classes
- [ ] pandas.io.formats.style.Styler.set_tooltips
- [ ] pandas.io.formats.style.Styler.set_uuid
- [ ] pandas.io.formats.style.Styler.pipe
- [ ] pandas.io.formats.style.Styler.highlight_between
- [ ] pandas.io.formats.style.Styler.highlight_quantile
- [ ] pandas.io.formats.style.Styler.background_gradient
- [ ] pandas.io.formats.style.Styler.text_gradient
- [ ] pandas.DataFrame.values
- [ ] pandas.DataFrame.groupby
- [ ] pandas.DataFrame.skew
- [ ] pandas.DataFrame.var
- [ ] pandas.DataFrame.sort_values
- [ ] pandas.DataFrame.tz_convert
- [ ] pandas.DataFrame.tz_localize
- [ ] pandas.DataFrame.plot.bar
- [ ] pandas.DataFrame.plot.hexbin
- [ ] pandas.DataFrame.plot.hist
- [ ] pandas.DataFrame.plot.line
- [ ] pandas.DataFrame.hist

**Comment by luke396** [comment] 2024-01-13 03:55
And take 

- pandas.errors.CategoricalConversionWarning
- pandas.errors.ChainedAssignmentError
- pandas.errors.ClosedFileError
- pandas.errors.NumExprClobberingError

**Comment by tqa236** [comment] 2024-01-13 05:50
Take
- pandas.MultiIndex.names
- pandas.MultiIndex.droplevel

**Comment by asishm** [comment] 2024-01-13 15:40
PR opened for the following:

- pandas.DataFrame.var
- pandas.DatetimeIndex.day_name
- pandas.core.groupby.DataFrameGroupBy.apply
- pandas.DatetimeIndex.month_name
- pandas.core.groupby.DataFrameGroupBy.hist
- pandas.core.groupby.SeriesGroupBy.apply
- pandas.core.groupby.SeriesGroupBy.transform
- pandas.DataFrame.plot.hist
- pandas.DataFrame.tz_localize
- pandas.CategoricalIndex.set_categories
- pandas.core.groupby.DataFrameGroupBy.boxplot
- pandas.core.groupby.SeriesGroupBy.pipe
- pandas.DataFrame.plot.bar
- pandas.DataFrame.tz_convert
- pandas.core.groupby.DataFrameGroupBy.pipe
- pandas.DataFrame.skew
- pandas.core.window.rolling.Rolling.corr

**Comment by erichxchen** [comment] 2024-01-14 01:49
Working on:
- pandas.DataFrame.hist
- pandas.read_json
- pandas.DataFrame.to_sql

**Comment by erichxchen** [comment] 2024-01-14 03:16
Hi @natmokval, the cmd `scripts/validate_docstrings.py --format=actions --errors=EX03 method-name` outputs all kind of errors, not just the EX03 errors.

https://github.com/pandas-dev/pandas/blob/c778746f2219601ac3c38f4f287f9a4e68905655/scripts/validate_docstrings.py#L444-L458

**Comment by yuanx749** [comment] 2024-01-14 04:55
working on:

- pandas.errors.PossibleDataLossError
- pandas.errors.PossiblePrecisionLoss
- pandas.errors.SettingWithCopyError
- pandas.errors.ValueLabelTypeMismatch

**Comment by asishm** [comment] 2024-01-14 05:44
@erichxchen  you are correct, I've been using the patch I mentioned at https://github.com/pandas-dev/pandas/pull/56827#issuecomment-1886625433 so that it only catches the EX03 errors.

**Comment by luke396** [comment] 2024-01-14 06:27
Working for 
- pandas.io.formats.style.Styler.map
- pandas.io.formats.style.Styler.apply_index
- pandas.io.formats.style.Styler.map_index
- pandas.io.formats.style.Styler.format

**Comment by jordan-d-murphy** [comment] 2024-01-14 20:56
I'll take:
pandas.Timestamp.ceil 
pandas.Timestamp.floor
pandas.Timestamp.round

**Comment by tiffanyxiao** [comment] 2024-01-14 23:36
I'll take:
*  pandas.io.formats.style.Styler.to_latex
*  pandas.read_parquet

**Comment by jordan-d-murphy** [comment] 2024-01-14 23:48
I'll take these: 

 pandas.io.json.build_table_schema
 pandas.read_stata
 pandas.plotting.scatter_matrix
 pandas.Index.droplevel 
 pandas.Grouper

**Comment by jordan-d-murphy** [comment] 2024-01-15 00:25
I'll take: 

pandas.io.formats.style.Styler.format_index
pandas.io.formats.style.Styler.relabel_index
pandas.io.formats.style.Styler.hide
pandas.io.formats.style.Styler.set_td_classes

**Comment by yuanx749** [comment] 2024-01-15 04:54
Working on:

- pandas.ExcelWriter

**Comment by alpakpinar** [comment] 2024-01-15 22:19
Working on:
* pandas.DataFrame.groupby
* pandas.DataFrame.values

**Comment by jordan-d-murphy** [comment] 2024-01-15 23:29
I'll take these: 

pandas.io.formats.style.Styler.set_tooltips
pandas.io.formats.style.Styler.set_uuid
pandas.io.formats.style.Styler.pipe
pandas.io.formats.style.Styler.highlight_between

**Comment by alpakpinar** [comment] 2024-01-16 00:51
Working on:
* pandas.DataFrame.plot.hexbin
* pandas.DataFrame.plot.line

**Comment by jordan-d-murphy** [comment] 2024-01-16 01:26
I'll take these: 

pandas.io.formats.style.Styler.highlight_quantile
pandas.io.formats.style.Styler.background_gradient
pandas.io.formats.style.Styler.text_gradient

**Comment by alpakpinar** [comment] 2024-01-16 01:40
@natmokval should `pandas.arrays.DatetimeArray` be added to the list? I see a `flake8` error on my PR tests:

Error: /home/runner/work/pandas/pandas/pandas/core/arrays/datetimes.py:179:EX03:pandas.arrays.DatetimeArray:flake8 error: line 2, col 4: E121 continuation line under-indented for hanging indent

**Comment by jordan-d-murphy** [comment] 2024-01-20 11:21
Looking over what's been merged in, I see these remaining in [main](https://github.com/pandas-dev/pandas/blob/main/ci/code_checks.sh) 
```
    MSG='Partially validate docstrings (EX03)' ;  echo $MSG
    $BASE_DIR/scripts/validate_docstrings.py --format=actions --errors=EX03 --ignore_functions \
        pandas.Series.plot.line \
        pandas.Series.to_sql \
        pandas.errors.SettingWithCopyWarning \
        pandas.errors.SpecificationError \
        pandas.errors.UndefinedVariableError \
        pandas.read_json \
        pandas.DataFrame.to_sql \
    RET=$(($RET + $?)) ; echo $MSG "DONE"
```
I see there are PRs open for `pandas.read_json` and `pandas.DataFrame.to_sql` but the others may have been abandoned. I am happy to pick up any of these that still need work.

**Comment by lukasld** [comment] 2024-01-20 21:13
> Otherwise id take:
> 
> * `pandas.errors.SettingWithCopyWarning`
> * `pandas.errors.SpecificationError`
> * `pandas.errors.UndefinedVariableError`

I cannot work on these since I cannot make the `numpydoc` work to test for validity. So they are up for grabs.

**Comment by jordan-d-murphy** [comment] 2024-01-20 22:35
Thanks for the update @lukasld 

I can take: 

```
pandas.errors.SettingWithCopyWarning
pandas.errors.SpecificationError
pandas.errors.UndefinedVariableError
```

**Comment by jordan-betterman** [comment] 2024-01-22 16:15
I'll take:

`
pandas.errors.ValueLabelTypeMismatch
pandas.Timestamp.ceil
pandas.Timestamp.floor
`

**Comment by jordan-d-murphy** [comment] 2024-01-22 18:29
@jordan-betterman it looks like `pandas.errors.ValueLabelTypeMismatch` was fixed in https://github.com/pandas-dev/pandas/pull/56867 and `pandas.Timestamp.ceil` and `pandas.Timestamp.floor` were both fixed in https://github.com/pandas-dev/pandas/pull/56879

**Comment by jordan-betterman** [comment] 2024-01-22 18:31
@jordan-d-murphy sounds good! Are there any others that need fixing?

**Comment by jordan-d-murphy** [comment] 2024-01-22 18:33
yes, if you check https://github.com/pandas-dev/pandas/blob/main/ci/code_checks.sh on the main branch, it looks like these are still remaining: 

```
    MSG='Partially validate docstrings (EX03)' ;  echo $MSG
    $BASE_DIR/scripts/validate_docstrings.py --format=actions --errors=EX03 --ignore_functions \
        pandas.Series.plot.line \
        pandas.Series.to_sql \
        pandas.read_json \
        pandas.DataFrame.to_sql # There should be no backslash in the final line, please keep this comment in the last ignored function
    RET=$(($RET + $?)) ; echo $MSG "DONE"
```

**Comment by jordan-betterman** [comment] 2024-01-22 19:05
@jordan-d-murphy how do I update the `validate_docstrings` script with the changes I made?

**Comment by jordan-d-murphy** [comment] 2024-01-22 19:25
if you want to see some good examples you can look at some of the MRs that have been merged in, such as https://github.com/pandas-dev/pandas/pull/56989 or https://github.com/pandas-dev/pandas/pull/56878

**Comment by jordan-betterman** [comment] 2024-01-22 19:37
> Im new to this and maybe I overlook something fundamental: I wanted to take on some of these docstrings, I however run into an issue and am not sure what I am doing wrong.
> 
> After executing:
> 
> ```
> python3 validate_docstrings.py --format=actions --errors=EX03 pandas.errors.SpecificationError
> ```
> 
> I get a list of `flake8 - errors`:
> 
> ```
> flake8 error: line 4, col 40: E261 at least two spaces before inline comment
> ...
> ```
> 
> However, after adding an extra space and saving the docstring for `SpecificationError` in this case in
> 
> ```
> ./pandas/errors/__init__.py
> ```
> 
> and rerunning the above `validation_docstrings.py` again, the script returns the same errors, as if the change had no effect.

@jordan-d-murphy  I'm having the same issues as this comment.

**Comment by asishm** [comment] 2024-01-22 19:41
@jordan-betterman see if this comment helps - https://github.com/pandas-dev/pandas/issues/56804#issuecomment-1886817794

**Comment by jordan-betterman** [comment] 2024-01-22 20:01
@asishm I saw that comment and was really helpful! I think the issue is when I run the `validation_docstrings` script it's not checking the most updated version of the docs.

This are the changes I made:
```
>>> df = pd.DataFrame({
            ...    'pig': [20, 18, 489, 675, 1776],
            ...    'horse': [4, 25, 281, 600, 1900],
            ... }, index=[1990, 1997, 2003, 2009, 2014])
>>> lines = df.plot.line()
```

This is what the script evaluated
```
>>> df = pd.DataFrame({
            ...    'pig': [20, 18, 489, 675, 1776],
            ...    'horse': [4, 25, 281, 600, 1900]
            ...    }, index=[1990, 1997, 2003, 2009, 2014])
>>> lines = df.plot.line()
```

Is there something in the setup that I need to change for it to work? This is my first day working in the repo, so it could be something on my end!

**Comment by jordan-d-murphy** [comment] 2024-01-22 20:10
@jordan-betterman can you post the script you're running and the output?

**Comment by jordan-betterman** [comment] 2024-01-22 20:14
script:
`scripts/validate_docstrings.py --format=actions --errors=EX03 pandas.Series.plot.line`

Output:
```
################################################################################
##################### Docstring (pandas.Series.plot.line)  #####################
################################################################################

Plot Series or DataFrame as lines.

This function is useful to plot lines using DataFrame's values
as coordinates.

Parameters
----------
x : label or position, optional
    Allows plotting of one column versus another. If not specified,
    the index of the DataFrame is used.
y : label or position, optional
    Allows plotting of one column versus another. If not specified,
    all numerical columns are used.
color : str, array-like, or dict, optional
    The color for each of the DataFrame's columns. Possible values are:

    - A single color string referred to by name, RGB or RGBA code,
        for instance 'red' or '#a98d19'.

    - A sequence of color strings referred to by name, RGB or RGBA
        code, which will be used for each column recursively. For
        instance ['green','yellow'] each column's line will be filled in
        green or yellow, alternatively. If there is only a single column to
        be plotted, then only the first color from the color list will be
        used.

    - A dict of the form {column name : color}, so that each column will be
        colored accordingly. For example, if your columns are called `a` and
        `b`, then passing {'a': 'green', 'b': 'red'} will color lines for
        column `a` in green and lines for column `b` in red.

**kwargs
    Additional keyword arguments are documented in
    :meth:`DataFrame.plot`.

Returns
-------
matplotlib.axes.Axes or np.ndarray of them
    An ndarray is returned with one :class:`matplotlib.axes.Axes`
    per column when ``subplots=True``.

        See Also
        --------
        matplotlib.pyplot.plot : Plot y versus x as lines and/or markers.

        Examples
        --------

        .. plot::
            :context: close-figs

            >>> s = pd.Series([1, 3, 2])
            >>> s.plot.line()  # doctest: +SKIP

        .. plot::
            :context: close-figs

            The following example shows the populations for some animals
            over the years.

            >>> df = pd.DataFrame({
            ...    'pig': [20, 18, 489, 675, 1776],
            ...    'horse': [4, 25, 281, 600, 1900]
            ...    }, index=[1990, 1997, 2003, 2009, 2014])
            >>> lines = df.plot.line()

        .. plot::
           :context: close-figs

           An example with subplots, so an array of axes is returned.

           >>> axes = df.plot.line(subplots=True)
           >>> type(axes)
           <class 'numpy.ndarray'>

        .. plot::
           :context: close-figs

           Let's repeat the same example, but specifying colors for
           each column (in this case, for each animal).

           >>> axes = df.plot.line(
           ...     subplots=True, color={"pig": "pink", "horse": "#742802"}
           ... )

        .. plot::
            :context: close-figs

            The following example shows the relationship between both
            populations.

            >>> lines = df.plot.line(x='pig', y='horse')

################################################################################
################################## Validation ##################################
################################################################################

3 Errors found for `pandas.Series.plot.line`:
	PR02	Unknown parameters {'color'}
	EX03	flake8 error: line 4, col 4: E121 continuation line under-indented for hanging indent
	EX03	flake8 error: line 6, col 4: E123 closing bracket does not match indentation of opening bracket's line
```

**Comment by jordan-d-murphy** [comment] 2024-01-22 20:23
hmmm okay, yes your approach seems correct, but when I ran this on the latest branch I'm seeing no EX03 errors for `pandas.Series.plot.line` 
 
I've been using the following approach to set up my dev env and working branch before working on my PRs, which ensures my branch is up to date with the latest version of main. 

can you try running these commands, and then try running your script again and see if it helps?
 - - - 
[Updating the development environment](https://pandas.pydata.org/docs/dev/development/contributing.html#id12)

git checkout main
git merge upstream/main
mamba activate pandas-dev
mamba env update -f environment.yml --prune


[Creating a feature branch](https://pandas.pydata.org/docs/development/contributing.html#id7)

git checkout main
git pull upstream main --ff-only
git checkout -b shiny-new-feature

- - - 
After running the above, and entering this script, 
`scripts/validate_docstrings.py --format=actions --errors=EX03 pandas.Series.plot.line`
my output ends with this: 
```
################################################################################
################################## Validation ##################################
################################################################################

1 Errors found for `pandas.Series.plot.line`:
	PR02	Unknown parameters {'color'}
```

**Comment by jordan-betterman** [comment] 2024-01-22 22:27
I tried all of that and still didn't work. I'm going to stop working on it and find another issue to take on. Thanks for all the help!

**Comment by jordan-d-murphy** [comment] 2024-01-22 23:22
Okay, sorry to hear it didn't work out. Thanks for giving it a shot!

**Comment by jordan-d-murphy** [comment] 2024-01-23 05:03
I've opened a PR for the remaining 4 functions. I believe this will close this issue. 

pandas.Series.plot.line
pandas.Series.to_sql
pandas.read_json
pandas.DataFrame.to_sql

**Comment by jordan-d-murphy** [comment] 2024-01-23 18:35
@natmokval now that https://github.com/pandas-dev/pandas/pull/57025 has been merged in, I believe we can close this issue. Please let me know if you see any additional work that needs to be done, I'd be happy to clean up any loose ends!

**Comment by natmokval** [comment] 2024-01-23 21:21
@jordan-d-murphy, I agree, seems we fixed all flake8 errors. Thank you for working on this issue with intensity and helping other contributors. Now, we can close this issue.

**Closed** 2024-01-23 21:22 UTC
Labels: Docs, Code Style, good first issue

**Comment by MarcoGorelli** [comment] 2024-01-23 23:12
Awesome, thanks all!
