### ISSUE TITLE
NonExistentTimeError Trying to resample series.

### ISSUE THREAD

**Issue by jdavidagudelo** [pandas-dev/pandas#23873] opened 2018-11-23 18:30 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

user_timezone = 'America/Bogota'
new_series = pandas.Series([1, 2], index=pandas.to_datetime([1, 1542997018451], unit='ms'))
new_series.index = new_series.index.tz_localize( 'UTC', ambiguous='infer').tz_convert(user_timezone)
new_series.resample('1D').count()


```
#### Problem description

When I execute the previous python code it raises an exception saying NonExistentTimeError: 1992-05-03 00:00:00.

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

</details>

**Comment by mroeschke** [comment] 2018-11-23 19:01
This looks like a duplicate of #23742, and this will be fixed in the next release.

**Closed by mroeschke** 2018-11-23 19:01 UTC
