### ISSUE TITLE
BUG: .replace() of an empty string for None returns value from previous row

### ISSUE THREAD

**Issue by ertuganova** [pandas-dev/pandas#36701] opened 2020-09-28 11:57 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---
#### Code Sample, a copy-pastable example

```python
d = {'col1' : ['test']*9, 'col2': [0,'',3,4,'', '', 6, 7, '']}
test = pd.DataFrame(data=d)
In [4]:
test['col2']
Out[4]:
0    0
1     
2    3
3    4
4     
5     
6    6
7    7
8     
Name: col2, dtype: object
In [5]:
test['col2'].replace('', None)
Out[5]:
0    0
1    0
2    3
3    4
4    4
5    4
6    6
7    7
8    7
Name: col2, dtype: object
In [6]:
test['col2'].replace({'': None})
Out[6]:
0    0.0
1    NaN
2    3.0
3    4.0
4    NaN
5    NaN
6    6.0
7    7.0
8    NaN
Name: col2, dtype: float64
```

#### Problem description

.replace() of an empty string for None value returns the value of previous row (instead of None). However .replace() of the same empty strings using dict structure returns None as it was expected.
#### Expected Output

It is expected that .replace('', None) will return the same result as .replace({'': None})

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 2a7d3326dee660824a8433ffd01065f8ac37f7d6
python           : 3.7.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
Version          : Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.1.2
numpy            : 1.17.2
pytz             : 2018.7
dateutil         : 2.7.5
pip              : 19.3.1
setuptools       : 41.6.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.10
IPython          : 7.1.1
pandas_datareader: None
bs4              : 4.9.0
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.0.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : 0.8.3
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>

**Comment by asishm** [comment] 2020-09-28 13:22
This is currently documented behavior.
also duplicate of #36513

https://pandas.pydata.org/docs/reference/api/pandas.Series.replace.html

> When value=None and to_replace is a scalar, list or tuple, replace uses the method parameter (default ‘pad’) to do the replacement. So this is why the ‘a’ values are being replaced by 10 in rows 1 and 2 and ‘b’ in row 4 in this case. The command s.replace('a', None) is actually equivalent to s.replace(to_replace='a', value=None, method='pad'):
>
> s.replace('a', None)
> 0 10
> 1 10
> 2 10
> 3 b
> 4 b
> dtype: object

**Closed** 2020-09-28 13:27 UTC
Labels: Bug, Needs Triage
