### ISSUE TITLE
BUG: skipna parameter in series.any() returns wrong result

### ISSUE THREAD

**Issue by kbhutani0001** [pandas-dev/pandas#23109] opened 2018-10-12 14:28 UTC
```
#importing pandas module 
import pandas as pd 

#importing numpy module
import numpy as np

data=pd.DataFrame({'A':[1,2,3,4,0,np.nan,3],
                  'B':[3,1,4,5,0,np.nan,5]})

data.any(axis=1,skipna=True)
```

Expected output:
0     True
1     True
2     True
3     True
4    False
5    True
6     True
dtype: bool

Returned output:

0     True
1     True
2     True
3     True
4    False
5    False
6     True
dtype: bool

As written in documentation,  If an entire row/column is NA, the result will be NA
But NA isn't returned in any of the cases (Keeping skipna True or False)

**Comment by TomAugspurger** [comment] 2018-10-12 15:28
> As written in documentation, If an entire row/column is NA, the result will be NA

I think the docs at https://github.com/pandas-dev/pandas/blob/12a0dc49ac63b63bcc5f93bccf71bce51c60bdad/pandas/core/generic.py#L9728-L9730 are incorrect. Skipna should be the same as the operation on the values with NAs removed (is that right @jorisvandenbossche?).

**Comment by TomAugspurger** [comment] 2018-10-12 16:31
min_count I thikn

**Comment by dsaxton** [comment] 2018-10-14 04:58
My opinion: I think the problem is the documentation; the result is actually correct.  If you ask if any of an empty set of statements is True, the answer is no.  This is consistent with `numpy`:

```
In [1]: import numpy as np

In [2]: np.any([])
Out[2]: False
```

**Comment by jorisvandenbossche** [comment] 2018-10-15 08:39
> Skipna should be the same as the operation on the values with NAs removed (is that right @jorisvandenbossche?).

I suppose this as well. `any`/`all` can be seen as reductions like `sum` or `prod`, so we should probably follow their design.

So I think @dsaxton is right that it is only the documentation that is incorrect.

**Comment by dsaxton** [comment] 2018-10-17 00:51
@jorisvandenbossche What would you say is the appropriate fix for this?  If the documentation is a general statement about the `skipna` parameter, maybe it makes sense to just remove the claim that the result will be NA (since it's not true for `any`, but presumably would be true in other contexts)?

**Closed** 2018-12-10 15:22 UTC
Labels: Docs, good first issue
