### ISSUE TITLE
"map" and  "apply" is very slow for millions rows. Any native support with parallel computation?

### ISSUE THREAD

**Issue by thesby** [pandas-dev/pandas#23852] opened 2018-11-22 02:01 UTC
"map" and  "apply" is very slow for millions rows. Any native support with parallel computation?

**Comment by jbrockmendel** [comment] 2018-11-22 02:32
Can you comment on the use case?  What kind of function are you trying to map/apply?  What data dtype(s)?

**Comment by TomAugspurger** [comment] 2018-11-22 02:53
Dupe of https://github.com/pandas-dev/pandas/issues/13111.

Parallelism is mostly out of scope right now, but that could change in the future.

**Closed by TomAugspurger** 2018-11-22 02:53 UTC
