### ISSUE TITLE
Can't access multi-index names when iterating over rows

### ISSUE THREAD

**Issue by konstantinmiller** [pandas-dev/pandas#35538] opened 2020-08-04 09:54 UTC
When iterating over rows with either `iterrows()` or `itertuples()`, it is not possible to access index names if you have a multi-index.

So, I would expect something like that to work
```
import pandas as pd

df = pd.DataFrame(
    index=pd.MultiIndex(
        names=['ind1'],
        levels=[['a']],
        codes=[[0]]
    ),
    data={'C': [42]})

ind, row = next(df.iterrows())
row.C
ind.ind1
```
However, since `ind` is not a named tuple, it throws an `AttributeError: 'tuple' object has no attribute 'ind1'`

Same with `itertuples()`:
```
import pandas as pd

df = pd.DataFrame(
    index=pd.MultiIndex(
        names=['ind1'],
        levels=[['a']],
        codes=[[0]]
    ),
    data={'C': [42]})

row = next(df.itertuples())
ind = row.Index
row.C
ind.ind1
```
throws `AttributeError: 'tuple' object has no attribute 'ind1'`

**Comment by simonjayhawkins** [comment] 2020-08-04 12:32
Thanks @konstantinmiller for the report. closing as duplicate of #27407. you may want to add a comment there to maybe include `iterrows` in that discussion.

**Closed by simonjayhawkins** 2020-08-04 12:32 UTC
Labels: Bug, Needs Triage
