### ISSUE TITLE
Wrong output from isinstance on dataframes > 10000 lines

### ISSUE THREAD

**Issue by rhstanton** [pandas-dev/pandas#25951] opened 2019-04-01 23:39 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here

n = 10001

df = pd.DataFrame({'a' : [0] * n,
                   'b' : [1] * n})

df['c'] = df.a + df.b

print(type(df.a.values[0]))
print(type(df.b.values[0]))
print(type(df.c.values[0]))

print(isinstance(df.a.values[0], np.int64))
print(isinstance(df.b.values[0], np.int64))
print(isinstance(df.c.values[0], np.int64))

```
#### Problem description

The last print statement displays "False, " but it should be "True." You get the correct output as long as n in the first line is set to a number <= 10000, but the wrong output if n > 10000

**Note**: We receive a lot of issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates!

**Note**: Many problems can be resolved by simply upgrading `pandas` to the latest version. Before submitting, please check if that solution works for you. If possible, you may want to check if `master` addresses this issue, but that is not necessary.

For documentation-related issues, you can check the latest versions of the docs on `master` here:

https://pandas-docs.github.io/pandas-docs-travis/

If the issue has not been resolved there, go ahead and file it in the issue tracker.

#### Expected Output

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
True
True
True

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Darwin
OS-release: 17.7.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.2
pytest: 4.0.2
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: 1.8.2
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.12
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.2
lxml.etree: 4.2.5
bs4: 4.6.3
html5lib: 1.0.1
sqlalchemy: 1.2.15
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None

</details>

**Comment by WillAyd** [comment] 2019-04-02 01:00
I wasn't able to reproduce this. What type is it?

**Comment by rhstanton** [comment] 2019-04-02 01:05
It sets everything to np.int64.

**Comment by WillAyd** [comment] 2019-04-02 01:09
Your code suggests that isn't happening though?

**Comment by rhstanton** [comment] 2019-04-02 03:00
Worse. The first three lines of output show that the type of each column is np.int64. And when I ask the first two columns whether their first element is of this type, they say yes. But when I ask whether the first element of column 3 (‘c’) is of this type, it answers yes if the number of rows is up to 10000, and no if there are more than 10000 rows. This is rather odd…

**Comment by WillAyd** [comment] 2019-04-02 03:02
Hmm well I wasn't able to reproduce given the code sample you provided, which I assume should be failing. Can you try on master to see if it works there?

**Comment by rhstanton** [comment] 2019-04-02 05:02
I just installed master, and it shows the same problem. 

I also tried downloading and reinstalling the latest Anaconda from scratch (Python 3.7, https://repo.anaconda.com/archive/Anaconda3-2018.12-MacOSX-x86_64.pkg <https://repo.anaconda.com/archive/Anaconda3-2018.12-MacOSX-x86_64.pkg>), and still get the same result. Hopefully that will at least help you recreate the problem.

**Comment by WillAyd** [comment] 2019-04-02 05:03
So what type are you getting if not np.int64?

**Comment by rhstanton** [comment] 2019-04-02 05:09
I have no idea. It tells me it’s np.int64, but when I run isinstance against that type, it returns False.

**Comment by rhstanton** [comment] 2019-04-02 15:58
More information: If I uninstall numexpr, the problem goes away. Reinstall and it comes back.

Also, I notice that in my original code, even though type() returns np.int64 for all three columns, they produce slightly different results when displayed:

> df.a.values
array([0, 0, 0, ..., 0, 0, 0])

> df.b.values
array([1, 1, 1, ..., 1, 1, 1])

> df.c.values
array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

Note the dtype at the end of the last output.

I'm not sure why the arrays are displayed differently, but it's at least a clue. And if we set n to 10,000 or less, the last command produces output consistent with the other two (i.e., no dtype printed).

**Comment by jreback** [comment] 2019-04-02 16:25
the default for array creation on some platforms is int32 

pandas is subject to this

**Comment by jreback** [comment] 2019-04-02 16:25
closing as wont fix / not a bug

**Closed by jreback** 2019-04-02 16:25 UTC
Labels: Can't Repro, Needs Info

**Comment by rhstanton** [comment] 2019-04-02 17:25
That may be true, but I don’t think it’s the issue here. When I use type(), it tells me I’m looking at an int64, but then isinstance reports false when I ask if I’m looking at an int64:

> print(type(df.c.values[0]))
<class 'numpy.int64'>

> print(isinstance(df.c.values[0], numpy.int64))
False

In the second statement, what should I replace numpy.int64 with so I get a response of True?

**Comment by rhstanton** [comment] 2019-04-02 21:35
After further investigation, this is an issue with numexpr, so I'll move the discussion over there.
