### ISSUE TITLE
REGR: assert_frame_equal check_dtype=False no longer works for equal values but numpy vs extension dtype

### ISSUE THREAD

**Issue by jorisvandenbossche** [pandas-dev/pandas#56340] opened 2023-12-05 08:24 UTC
Noticed this from the geopandas CI, but on the latest released version, the following works:

```python
df1 = pd.DataFrame({"col": [1, 2, 3]})
df2 = df1.astype("Int64")

# expected error by default 
>>> pd.testing.assert_frame_equal(df1, df2)
...
AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="col") are different
Attribute "dtype" are different
[left]:  int64
[right]: Int64

# but the assertion passes with check_dtype=False
>>> pd.testing.assert_frame_equal(df1, df2, check_dtype=False)
```

On main we however get the following for this second check:

```
>>> pd.testing.assert_frame_equal(df1, df2, check_dtype=False)
...
AssertionError: DataFrame.iloc[:, 0] (column name="col") are different

DataFrame.iloc[:, 0] (column name="col") classes are different
[left]:  ndarray
[right]: IntegerArray
```

**Comment by jorisvandenbossche** [comment] 2023-12-05 08:25
Looking at the history of the file, I assume this is related to https://github.com/pandas-dev/pandas/pull/55934 (cc @parthi-siva @MarcoGorelli)

I am also seeing a bunch of TODO's and xfails added in that PR?

**Comment by lithomas1** [comment] 2023-12-21 19:51
Can we mark this as a dupe of #56131?

**Closed** 2023-12-28 21:44 UTC
Labels: Testing, Regression
