### ISSUE TITLE
BUG: Dataframe row not being updated after value update within iterrows

### ISSUE THREAD

**Issue by Aswin22-tech** [pandas-dev/pandas#57577] opened 2024-02-23 02:55 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# Import pandas library
import pandas as pd
 
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]
 
# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

for index,row in df.iterrows():
    df.loc[index,'Name'] = 'newer name'
    print(row['Name'])
```

### Issue Description

Within iterrows, when you are updating the value of a column using df.loc[index,'column name'], isn't the update supposed to happen immediately? I have read somewhere that iterrows uses a copy of dataframe and not the actual dataframe. But I feel it is more logical to have the update done immediately. In the example provided above, print statement prints the old values in name column and not "newer name", which definitely looks like an issue to me. At the same time, if I use the same .loc command, it is showing new value, which is weird. I have attached the screenshots.
<img width="430" alt="pandas_issue_1" src="https://github.com/pandas-dev/pandas/assets/80024139/6dbfac9d-cf93-4627-963a-bb2f7dfc00cb">
<img width="389" alt="pandas_issue_2" src="https://github.com/pandas-dev/pandas/assets/80024139/078468b7-9d1a-4e85-acdf-e10fe75c82d3">

### Expected Behavior

As mentioned above, expected behavior would be to have the values updated immediately

### Installed Versions

<details>

I am getting error when I call this function. Attached the screenshot.
<img width="823" alt="pandas_issue_3" src="https://github.com/pandas-dev/pandas/assets/80024139/aa032c98-32a9-4f9c-b36d-e5c1232c0e33">

</details>

**Comment by mroeschke** [comment] 2024-02-23 17:19
It's important to note that it's bad practice to modify the object you're iterating over.

Second, `row` is a distinct object from `df` so the assignment is only modifying `df`. Since this is the expected behavior closing.

**Closed by mroeschke** 2024-02-23 17:19 UTC
Labels: Bug, Needs Triage
