### ISSUE TITLE
problem in groupby-rank w/ multindex column

### ISSUE THREAD

**Issue by bridwell** [pandas-dev/pandas#27721] opened 2019-08-02 21:08 UTC
#### Example

```python
df = pd.concat({
    'a': pd.DataFrame({
        'col1': [1, 2],
        'col2': [3, 4]
    }),
    'b': pd.DataFrame({
        'col3': [5, 6],
        'col4': [7, 8]
    }),
}, axis=1)
```

<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="2" halign="left">a</th>
      <th colspan="2" halign="left">b</th>
    </tr>
    <tr>
      <th></th>
      <th>col1</th>
      <th>col2</th>
      <th>col3</th>
      <th>col4</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>4</td>
      <td>6</td>
      <td>8</td>
    </tr>
  </tbody>
</table>

```python
df.groupby(level=0, axis=1).rank(axis=1, ascending=False, method='first')

```
**_ValueError: Shape of passed values is (4, 2), indices imply (2, 2)_**

#### Problem description

Should return a data frame with values indicating the rank for each row and within each upper level column. This works in 0.22.0 but in 0.24.2 it fails with the ValueError. It fails in both py 2.7 and py 3.68.

#### Expected Output
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="2" halign="left">a</th>
      <th colspan="2" halign="left">b</th>
    </tr>
    <tr>
      <th></th>
      <th>col1</th>
      <th>col2</th>
      <th>col3</th>
      <th>col4</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2.0</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>1.0</td>
    </tr>
  </tbody>
</table>

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: 3.0.5
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.11.3
scipy: 0.18.1
pyarrow: None
xarray: None
IPython: 5.1.0
sphinx: 1.5.1
patsy: 0.4.1
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.4.2
numexpr: 2.6.1
feather: None
matplotlib: 2.0.0
openpyxl: 2.4.1
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.2
bs4: 4.5.3
html5lib: 1.0.1
sqlalchemy: 1.1.5
pymysql: None
psycopg2: 2.7.3.2 (dt dec pq3 ext lo64)
jinja2: 2.9.4
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by kmin-jeong** [comment] 2019-09-14 06:51
can I try it?

**Comment by mzeitlin11** [comment] 2021-03-29 20:55
Looks fixed on master. Contributions welcome to add a test!

**Comment by marceloid** [comment] 2021-04-05 17:40
Can confirm that the issue is fixed on pandas 1.2.3.

INSTALLED VERSIONS
------------------
commit           : f2c8480af2f25efdbd803218b9d87980f416563e
python           : 3.9.2.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : pt_BR.cp1252

pandas           : 1.2.3
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 54.0.0

**Comment by jreback** [comment] 2021-04-05 18:15
@marceloid would take a PR with a test for this

**Closed** 2021-04-21 21:55 UTC
Labels: Groupby, MultiIndex, Needs Tests, good first issue
