### ISSUE TITLE
pandas.read_csv of S3 gets inconsistent results within / outside Docker

### ISSUE THREAD

**Issue by fullflu** [pandas-dev/pandas#30770] opened 2020-01-07 05:59 UTC
## Overview
I found that the number of lines increased when I read a csv file by `pd.read_csv` from S3.
I also confirmed that several rows are duplicated with the transformation of types (their values are transformed into object-type).

This might be related to [pandas.read_csv duplicate issue](https://stackoverflow.com/questions/51790913/pandas-read-csv-duplicate-issue) , but I cannot solve the problem by removing the `.pyc` extension file.

Do you have any ideas about the reason for this phenomenon?
And how should I fix the problem?

## Details
The number of lines of the original S3 file is 34715 (one line is a header).
```
***$ wc -l data/foo.csv 
   34715 data/foo.csv
```

I build and run the following docker image.
Dockerfile:
```
FROM python:3.6.8-stretch

WORKDIR .
RUN set -x \
    apt-get -y install postgresql
COPY ./foo/requirements.txt ./
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
```
pipfile:
```
antiorm==1.2.1
boto3==1.9.218
botocore==1.12.218
certifi==2019.6.16
chardet==3.0.4
connection==2019.4.13
db==0.1.1
docutils==0.15.2
execute==1.2
fsspec==0.4.3
idna==2.8
Jinja2==2.10.1
jinjasql==0.1.7
jmespath==0.9.4
luigi==2.8.8
MarkupSafe==1.1.1
numpy==1.17.0
pandas==0.25.2
psycopg2==2.8.3
public==2019.4.13
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1.1
requests==2.22.0
s3fs==0.3.3
s3transfer==0.2.1
six==1.12.0
urllib3==1.25.3
yml==0.0.1
```
docker commands:
```
docker build -t pd-test -f ./Dockerfile . 
docker run -it pd-test /bin/bash
```

The number of rows (`df.shape[0]`) increases: 34714 -> 34851
```
$ python
>>> import pandas as pd
>>> df = pd.read_csv("s3://*/.*csv", converters={"foo": str})
sys:1: DtypeWarning: Columns (2,4,6,11,14,17,19,22,25,28,31,34,37,40,46,50,54,55,57,58,59,62,67,68,69,70,74,76,77) have mixed types. Specify dtype option on import or set low_memory=False.
>>> df.shape
(34851, 78)
>>> pd.__version__
'0.25.2'
>>> s3fs.__version__
'0.3.3'
```
Column names are included in the dataframe.
```
>>> df.iloc[34714].values == df.columns
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])
```
I also found that `df.iloc[0]` and `df.iloc[34715]` were the same except that the type of `df.iloc[34715]` was `object`.

On the other hand, the number of lines did not increase without the docker environment.
```
In [2]: df = pd.read_csv("s3://*/*.csv", converters={"foo": str})
*/.pyenv/versions/3.6.1/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (46) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
In [3]: df.shape
Out[3]: (34714, 78)

In [9]: pd.__version__
Out[9]: '0.25.2'

In [11]: s3fs.__version__
Out[11]: '0.3.3'
```

**Comment by fullflu** [comment] 2020-01-07 13:46
docker environment:
```
>>> pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.8.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.9.125-linuxkit
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 0.25.2
numpy            : 1.17.0
pytz             : 2019.1
dateutil         : 2.8.0
pip              : 19.3.1
setuptools       : 41.0.1
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.3 (dt dec pq3 ext lo64)
jinja2           : 2.10.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : 0.3.3
scipy            : None
sqlalchemy       : None
tables           : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
```

local environment:
```
In [18]: pd.show_versions()

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.1.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 16.3.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : ja_JP.UTF-8
LOCALE           : ja_JP.UTF-8

pandas           : 0.25.2
numpy            : 1.16.4
pytz             : 2018.3
dateutil         : 2.6.1
pip              : 18.1
setuptools       : 42.0.2
Cython           : 0.26.1
pytest           : 4.2.0
hypothesis       : None
sphinx           : 1.6.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.4.1
html5lib         : 1.0b10
pymysql          : None
psycopg2         : 2.7.3.2 (dt dec pq3 ext lo64)
jinja2           : 2.10
IPython          : 6.2.1
pandas_datareader: None
bs4              : 4.8.1
bottleneck       : 1.2.1
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.4.1
matplotlib       : 3.1.1
numexpr          : 2.7.0
odfpy            : None
openpyxl         : 2.5.0
pandas_gbq       : None
pyarrow          : None
pytables         : None
s3fs             : 0.3.3
scipy            : 1.1.0
sqlalchemy       : 1.2.5
tables           : None
xarray           : None
xlrd             : 1.1.0
xlwt             : None
xlsxwriter       : None
```

I wonder if the following differences might be the reason...
`python, OS, LANG, or LOCALE`

**Comment by gfyoung** [comment] 2020-01-07 21:18
No ideas at the moment.  Here is a suggestion:

Try reproducing the issue with a much smaller file.  Then, in the Docker container, save the result and retrieve it from your local filesystem (you'll need a volume mount).

If you can do a comparison, maybe we can get an idea of where the discrepancy is occurring.

**Comment by fullflu** [comment] 2020-01-17 06:26
OK, I will debug as you could suggest when I have time.

FYI: I found that the following code works well as a temporary solution.
```
s3 = boto3.client('s3')
obj = s3.get_object(Bucket=bucket_name, Key=s3_path)
df = pd.read_csv(io.BytesIO(obj['Body'].read()))
```

**Comment by mroeschke** [comment] 2021-07-25 04:46
Thanks for the report, but if there's an issue we would need more of a minimal example so that we can write a unit test for our CI system. Docker unfortunately isn't in scope of CI testing.

Closing since this debugging hasn't gotten much traction, but happy to reopen if you discover the issue that's independent of Docker

**Closed by mroeschke** 2021-07-25 04:46 UTC
Labels: IO CSV
