### ISSUE TITLE
BUG: Regression in sort_index with ascending=None

### ISSUE THREAD

**Issue by YarShev** [pandas-dev/pandas#39434] opened 2021-01-27 11:07 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import pandas
import numpy as np
df = pandas.DataFrame(np.arange(64))
length = len(df.index)
df.index = [(i - length / 2) % length for i in range(length)]
df.sort_index(axis=0, ascending=None, na_position="first")
ValueError: the 'axis' parameter is not supported in the pandas implementation of argsort()
```

#### Problem description

There was no such issue in pandas version 1.1.5

#### Output of ``pd.show_versions()``

pandas           : 1.2.1
numpy            : 1.19.5
pytz             : 2020.5
dateutil         : 2.8.1
pip              : 20.3.3
setuptools       : 51.1.2.post20210112
Cython           : None
pytest           : 6.2.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : None
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.7.2
odfpy            : None
openpyxl         : 3.0.6
pandas_gbq       : None
pyarrow          : 2.0.0
pyxlsb           : None
s3fs             : 0.5.2
scipy            : 1.6.0
sqlalchemy       : 1.3.22
tables           : 3.6.1
tabulate         : None
xarray           : 0.16.2
xlrd             : 2.0.1
xlwt             : None
numba            : None

</details>

**Comment by YarShev** [comment] 2021-01-27 12:43
The same is true for Series.sort_index(...).

**Comment by attack68** [comment] 2021-01-27 16:31
`ascending` is an argument which accepts boolean or list of booleans. I do not believe it should be considered a bug or a regression if the execution has changed from one version to another with an erroneous input argument.

I would not know what output to expect with `ascending=None`?

**Comment by jreback** [comment] 2021-01-27 16:34
we should be validating the ascending arg type as boolean - it's possible we r not

**Comment by YarShev** [comment] 2021-01-27 17:10
> I would not know what output to expect with `ascending=None`?

As I see, `ascending=None` and `ascending=False` behaviors were identical in 1.1.5 version. So, I think it would be good to add a check for `ascending`.

**Comment by simonjayhawkins** [comment] 2021-02-08 15:04
moving to 1.2.3

**Comment by simonjayhawkins** [comment] 2021-02-08 17:04
> There was no such issue in pandas version 1.1.5

first bad commit: [aa43f17357fec66e7cb2323dd3ba327bc16dd6c5] REF: nargsort incorrectly calling _values_for_argsort (#37266)

> As I see, `ascending=None` and `ascending=False` behaviors were identical in 1.1.5 version. So, I think it would be good to add a check for `ascending`.

@ivanovmg  an alternative could be to restore the old behaviour for 1.2.x and repurpose #39451 for 1.3 and then  can advertise the 'breaking change', which is permissible since the usage is incorrect.

**Comment by jreback** [comment] 2021-02-08 19:11
no i think we should just fix this - the. new is wrong

**Comment by ivanovmg** [comment] 2021-02-11 11:08
@jreback @simonjayhawkins 
Can you please clarify what will be the preferable way?
Should I restore the old behavior in nargsort as @simonjayhawkins recommends?
@jreback it is not clear for my what you suggest here.

**Closed** 2021-02-26 14:21 UTC
Labels: Bug, Reshaping
