### ISSUE TITLE
BUG: memory spike in DatetimeIndex after .loc based assignment

### ISSUE THREAD

**Issue by mdering** [pandas-dev/pandas#35215] opened 2020-07-10 15:28 UTC
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
n = 1500000
idx = pd.date_range(end = pd.Timestamp.now().floor("1T"), freq='1T', periods=n)
srs1 = pd.Series(np.random.random(n), idx)
srs2 = pd.Series(np.random.random(n), idx)
print(sys.getsizeof(srs1.index)) # 12000032
print(sys.getsizeof(srs2.index)) # 12000032
filter_srs = srs1[srs1 > .9].index
srs2.loc[filter_srs] = .9
print(sys.getsizeof(srs2.index)) # 53943072
assert (srs1.index == srs2.index).all()
```

#### Problem description

hi pandas, after filtering a series on some index, theres a strange spike in memory usage of the index where it can grow in size by a factor of > 4. I know this is a strange use case but its a MWE of a version where the `srs2` index might be mutated. The `nbytes` attributes of the indexes stay the same, but the overall memory usage according to sys grows larger and stays large. Also, if i do something like `srs2.index = pd.DatetimeIndex(srs2.index)` the memory usage falls back to a normal level
#### Expected Output
I would expect all of them to be the same.
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.5.0
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.0.5
numpy            : 1.18.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.1.1
setuptools       : 47.3.1.post20200622
Cython           : 0.29.20
pytest           : 5.4.3
hypothesis       : 5.18.3
sphinx           : 3.1.2
blosc            : None
feather          : None
xlsxwriter       : 1.2.9
lxml.etree       : 4.5.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.16.1
pandas_datareader: None
bs4              : 4.9.1
bottleneck       : 1.3.2
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.1
matplotlib       : 3.2.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.4
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.4.3
pyxlsb           : None
s3fs             : None
scipy            : 1.5.0
sqlalchemy       : 1.3.18
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.9
numba            : 0.50.1

</details>

**Comment by jbrockmendel** [comment] 2020-09-03 02:00
The difference here is because `idx._engine` is created lazily when it is needed (at the .loc call).  Attempts to trim the memory footprint of the IndexEngine are welcome, but this is expected behavior.  Closing.

**Closed by jbrockmendel** 2020-09-03 02:00 UTC
Labels: Bug, Needs Triage

**Comment by mdering** [comment] 2020-09-03 17:43
Understood. are there any best practices for this, then?

**Comment by jbrockmendel** [comment] 2020-09-03 18:02
> are there any best practices for this, then?

Well we generally dont think of this as a "problem" that requires any best practices.  If you are really low on memory, you _could_ do `idx._cache.clear(); gc.collect()` every time you do a lookup.  Or use something like dask to do things out-of-core.  But really this is more effort than it is likely worth.

**Comment by mdering** [comment] 2020-09-03 18:20
ok thanks so much for your help!
