### ISSUE TITLE
.merge() does not preserve the row-order at the output dataframe

### ISSUE THREAD

**Issue by PoeteMaudit** [pandas-dev/pandas#27452] opened 2019-07-18 11:05 UTC
Have a look here:
https://stackoverflow.com/q/57092373/9024698

**Comment by jreback** [comment] 2019-07-18 11:11
pls show a full example here; you can leave the SO link

**Comment by jreback** [comment] 2019-07-18 11:15
dupe of #27453

**Closed by jreback** 2019-07-18 11:15 UTC
