### ISSUE TITLE
BUG: min_periods strange behavior with rolling and center=True

### ISSUE THREAD

**Issue by horsto** [pandas-dev/pandas#47052] opened 2022-05-18 06:50 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

numbers = np.arange(100)
numbers_series = pd.Series(numbers)

# Rolling, centered window, no min_periods
numbers_series_perc = numbers_series.rolling(window = 20, center = True).quantile(0.1)
print(numbers_series_perc.values)

# Rolling, centered window, with min_periods half of window size
numbers_series_perc = numbers_series.rolling(window = 20, center = True, min_periods = 10).quantile(0.1)
print(numbers_series_perc.values)
```

### Issue Description

I am not sure this is a bug or whether I just don't understand the expected behavior. 
When using rolling with centered window and a window length of 20, I get 10 NaNs at the start (expected!). 
When I then put in a `min_periods = 10` I expect the length of NaNs at the start to shrink down to 5 (half the new minimum window size), however, magically all NaNs disappear. 

### Expected Behavior

I expect the count of NaNs at the start to gradually shrink when I put in a `min_periods` argument smaller than `window` size. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 19.6.0
Version          : Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.19.5
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 61.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.1.1
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.3.0
gcsfs            : None
markupsafe       : 2.1.1
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>

**Comment by simonjayhawkins** [comment] 2022-05-18 12:24
> I am not sure this is a bug or whether I just don't understand the expected behavior.

I think the behaviour is correct.

```
win = numbers_series.rolling(window=20, center=True, min_periods=10)
print(pd.DataFrame({"min": win.min(), "max": win.max()}))
```

```
     min   max
0    0.0   9.0
1    0.0  10.0
2    0.0  11.0
3    0.0  12.0
4    0.0  13.0
..   ...   ...
95  85.0  99.0
96  86.0  99.0
97  87.0  99.0
98  88.0  99.0
99  89.0  99.0

[100 rows x 2 columns]
```

each window has at least 10 values.

I don't personally use this so I could be wrong. @mroeschke

**Comment by no703** [comment] 2022-05-18 15:44
A centered window around the first value contains 10 values (the first ten values, assuming there are values in every position). You are missing 10 to your default min_periods of 20.
Setting min_periods =10 therefore gives you values from the first position.


I think your intuition of what should happen is incomplete.
'center = True' only sets the center of the window you get your input values from. Then it uses the available values in it.  If you are at the start or end or there are empty fields your result can even be further left or right than the input values with highest or lowest index. The window where the input values actually com from may therefore very well not be centered.
If you want to guarantee that the result is in the center of all its input values I don't think that this is the way to do it.

**Comment by mroeschke** [comment] 2022-05-18 16:26
Yeah nothing much too add to the responses above, but they both have the correct explanation. Since this is the expected behavior (and tested), closing as a usage question

**Closed by mroeschke** 2022-05-18 16:26 UTC
Labels: Usage Question, Window

**Comment by horsto** [comment] 2022-05-18 16:40
Great, thanks for your replies!
