### ISSUE TITLE
plotting: subplots_adjust prevents use of constrained_layout=True

### ISSUE THREAD

**Issue by michaelaye** [pandas-dev/pandas#25261] opened 2019-02-11 00:15 UTC
#### Code Sample, a copy-pastable example if possible

```python
# Your code here
import matplotlib.pyplot as plt
import pandas as pd

fig, axes = plt.subplots(2, constrained_layout=True)
times = pd.date_range(start='now', periods=10)
pd.DataFrame({'a': np.arange(10)}, index=times).plot(style='x', ax=axes[0])
```
#### Problem description
Plotting time-series uses pandas-internally a subplots_adjust, but due to this I am unable to use the new matplotlib constrained_layout that would take care of these things automatically.

#### Expected Output
A good layout that respects my constrained_layout setting to plt.subplots()

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.1.final.0
python-bits: 64
OS: Linux
OS-release: 3.10.0-862.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: 4.2.0
pip: 19.0.2
setuptools: 40.7.3
Cython: 0.29.5
numpy: 1.16.1
scipy: 1.2.0
pyarrow: None
xarray: 0.11.3
IPython: 7.1.1
sphinx: 1.8.4
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.9
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: 1.2.0
xlwt: 1.3.0
xlsxwriter: 1.1.3
lxml.etree: 4.3.1
bs4: None
html5lib: None
sqlalchemy: 1.2.17
pymysql: None
psycopg2: 2.7.7 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
gcsfs: None
</details>

**Comment by TomAugspurger** [comment] 2019-02-11 12:48
What does a fix for this involve?

**Comment by michaelaye** [comment] 2019-02-11 14:23
How about a config flag that is being checked that tells if user wants to have subplots adjusted?

**Comment by TomAugspurger** [comment] 2019-02-11 14:31
That'd be somewhat unusual for pandas. I don't think we have any other
config options.

Is matplotlib's constrained_layout strictly better than pandas current
stuff? I'd be happy to just let matplotlib take care of it.

**Comment by michaelaye** [comment] 2019-07-16 22:52
Well, when I want to combine several pandas timeseries plots into one figure, this mess happens. It wouldn't happen with constrained_layout, so I'd say, it is strictly better. ;)

<img width="846" alt="Screen Shot 2019-07-16 at 15 52 00" src="https://user-images.githubusercontent.com/69774/61335242-a937d700-a7e1-11e9-9405-b3554e0d9071.png">

**Comment by michaelaye** [comment] 2019-07-16 22:55
The issue is, at the moment pandas uses `subplot_adjust` pandas is robbing the user of the opportunity of letting matplotlib take care of it, b/c matplotlib says, "oh, you adjust layout yourself, then i don't help you laying it out".

**Comment by TomAugspurger** [comment] 2019-07-17 20:53
In that case, is there any reason to use DataFrame.plot rather than using
Matplotlib directly?

**Comment by michaelaye** [comment] 2019-07-17 21:18
As always, the reason is that somebody else did some coding for you. ;) In this case, it's rather tedious to go through the detail of setting up matplotlib for dates. Or maybe it was, it still was tedious when I started using pandas being so happy that it did plots over time automatically. ;)

**Comment by michaelaye** [comment] 2020-02-10 16:58
Here is an easy to reproduce minimal example:

```python
tseries = pd.date_range('now', freq='s', periods=100)
df = pd.DataFrame({'data': np.random.random(100)}, index=tseries)
df.plot()
```
Output:

<img width="969" alt="Screenshot 2020-02-10 09 55 00" src="https://user-images.githubusercontent.com/69774/74171381-b7b96600-4beb-11ea-8219-9603637589c1.png">

(Also here, for your convenience: https://gist.github.com/0b3c5f2ba247194fe84d8f620278dc7c )

I'm puzzled by the advise to plot using MPL instead of using df.plot(), isn't the functionality there to be used? It's a huge timesaver. Unless you claim I'm the only user that has constrained_layout as default MPL layouter. Do you officially not support plotting with the constraint_layout=True?

**Comment by jklymak** [comment] 2020-02-10 17:19
`constrained_layout` is typically set at figure creation, so pandas *could* check if its set and *not* do whatever it does to adjust things manually.  Whether it *should* is a cost-benefit question for pandas.  It will probably help some plots, but could break others?

**Comment by michaelaye** [comment] 2020-02-10 18:19
Could you give an example how existing plots could be broken if all pandas could do is to put an if in front of using subplots_adjust? I guess I'm underestimating some hidden complexity.
I'm open to other suggestion, like a wrapper on my side to switch off constrained_layout, although that would mean I either need to wrap all pandas plotters or all non-pandas plotters...

```python
if not constrained_layout:
    do_subplots_adjust
```

**Comment by jklymak** [comment] 2020-02-10 18:21
> Could you give an example how existing plots could be broken if all pandas could do is to put an if in front of using subplots_adjust?  

I cannot - I am not familiar enough with panda's plotting.  However, I'm sure if you made a PR that put this `if` in the appropriate place, pandas would consider adopting it...

**Comment by michaelaye** [comment] 2020-02-10 18:22
i certainly can try. although above comments don't make me hopeful that it would be considered.

**Comment by mdruiter** [comment] 2020-08-17 16:14
> Is matplotlib's constrained_layout strictly better than pandas current
> stuff? I'd be happy to just let matplotlib take care of it.

Yes!

> In that case, is there any reason to use DataFrame.plot rather than using Matplotlib directly?

Yes, because **I** am happy to let pandas take care of it...

I think the problem is that pandas used matplotlib `subplots_adjust` functionality, then matplotlib changed its details to have more possibilities (disallowing `subplots_adjust` when `constrained_layout` is enabled), but pandas didn't adapt to cope with those changes.

Pandas should just check whether `constrained_layout` is enabled before calling `subplots_adjust`...

**Comment by jklymak** [comment] 2020-08-17 16:22
... as a bit of a side issue, Matplotlib datetime handling *has* been improved (with some inspiration from pandas!), so I think directly plotting using matplotlib is not as painful as it might have been when `pd.plot` was originally written.  Not to say that `pd.plot` probably doesn't have other specific niceties.

**Closed** 2021-01-28 15:07 UTC
Labels: Visualization
