### ISSUE TITLE
BUG: error 'PandasArray' object has no attribute '_str_replace'

### ISSUE THREAD

**Issue by cjfarnold** [pandas-dev/pandas#42105] opened 2021-06-18 14:02 UTC
Got the above error when executing the following line in my code
df["CleanedCol"] = df[colname].str.replace(r'[^A-Za-z0-9]+', ' ')

details of the error is 
accessor.py", line 1312, in replace
    result = self._array._str_replace(

AttributeError: 'PandasArray' object has no attribute '_str_replace'

output of pd.show_version()
INSTALLED VERSIONS
------------------
commit           : b5958ee1999e9aead1938c0bba2b674378807b3d
python           : 3.7.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 1.1.5
numpy            : 1.17.4
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.2
setuptools       : 52.0.0.post20210125
Cython           : 0.29.21
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.0
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.2.1
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.0.3
numexpr          : 2.6.9
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.2.1
sqlalchemy       : 1.4.15
tables           : 3.5.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.43.1

**Comment by simonjayhawkins** [comment] 2021-06-18 14:08
Thanks @cjfarnold for the report. 

Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

Do you still get the same error with a more recent version of pandas?

**Comment by Rockrs** [comment] 2021-06-19 10:32
@cjfarnold 
Please try with the latest version.

I was not a able to reproduce your issue

Here is what I am getting as output:

Code:
`import pandas as pd

testdataframe = pd.DataFrame({'a':['Foo','Foh',np.nan],'b':['Foo','Foh',np.nan]})
testdataframe['c'] = testdataframe['a'].str.replace('Fo', 'BA')
print (testdataframe)`

Output :
  a    b    c
0  Foo  Foo  BAo
1  Foh  Foh  BAh
2  NaN  NaN  NaN

**Comment by mroeschke** [comment] 2021-08-23 03:58
Thanks for the report. As mentioned, the team would need a minimal, reproducible example to address the issue and please try on the latest release of pandas. Closing as the issue is currently not actionable.

**Closed by mroeschke** 2021-08-23 03:58 UTC
Labels: Bug, Needs Info, Needs Triage
