### ISSUE TITLE
.loc[] with MultiIndex sometimes yields Series, other times yields DataFrames

### ISSUE THREAD

**Issue by lbeltrame** [pandas-dev/pandas#4045] opened 2013-06-26 14:11 UTC
The behavior I'm experiencing is non-deterministic. DataFrames with different data but constructed at the same way behave differently.

The example from the documentation on indexing works:

``` python

 df.loc[("foo", "one")]
                0         1         2         3
foo one -1.465106  0.518888  0.901505 -0.250815

```

However in some occasions doing .loc with 3 or more keys gives me a Series with the index as name:

``` python

dataframe.loc[("chr1", 27106293, "Test")]
file                    NaN
gene                    NaN
reference               NaN
mutated_base            NaN
mutated_base_reads        0
reference_base_reads      0
other_reads               0
total_reads               0
mutated_percentage      NaN
Name: (chr1, 27106293, Test), dtype: object

```

A similarly-constructed DataFrame but with different data yields instead a DataFrame.

I can't paste the affected DataFrame to this bug tracker, but I can provide it privately if need be.

**Comment by TomAugspurger** [comment] 2017-05-04 13:42
Closing since we don't have a reproducible example

**Closed by TomAugspurger** 2017-05-04 13:42 UTC
Labels: Indexing, MultiIndex
