### ISSUE TITLE
Iterrows making incorrect assumptions about datetime

### ISSUE THREAD

**Issue by jim22k** [pandas-dev/pandas#12222] opened 2016-02-03 16:10 UTC
This is a very obscure bug in a corner-case, but it's still a bug which I ran into. It's easiest to understand by seeing it in action. I'm running **pandas version 0.17.1**.

```
>>> import pandas as pd
>>> import datetime
>>> df = pd.DataFrame({'a': [datetime.datetime(2015,1,1)], 'b': [None], 'c': [None], 'd': [''], 'e': [[]], 'f': [set()], 'g': [{}]})
>>> df
           a     b     c d   e   f   g
0 2015-01-01  None  None    []  {}  {}
```

The key to causing the bug is a row which starts with a datetime obj followed by at least two None's. Following that is any number of empty strings, empty lists, empty sets, or empty dicts. Indexing into the DataFrame by row works fine.

```
>>>> df.iloc[0]
a    2015-01-01 00:00:00
b                   None
c                   None
d                       
e                     []
f                     {}
g                     {}
Name: 0, dtype: object
```

Iterating over the rows using iterrows causes a weird behavior of converting to a datetime dtype with NaT's. **This is the bug:**

```
>>> df.iterrows().next()
(0, a   2015-01-01
 b          NaT
 c          NaT
 d          NaT
 e          NaT
 f          NaT
 g          NaT
 Name: 0, dtype: datetime64[ns])
```

The following properties **avoid the issue** entirely:
1. Having less than two None's following the datetime.
2. Having any of the items after the two None's be "truthy".
3. Including either a zero or a False in the items after the None's.

**Comment by TomAugspurger** [comment] 2016-02-03 16:27
This is probably working as intended. `.iterrows` returns a Series which must have a single dtype. Pandas will try to cast the items in a row to as precise a dtype as it can so all the Falsey things get cast as `NaT`s. If you want to preserve the items try `DataFrame.iteritems()` which will return namedtuples.

Just one thing though, I don't see

> Having less than two None's following the datetime

being required to get them to not cast

```python
In [39]: next(df[['a', 'b']].iterrows())
Out[39]:
(0, a   2015-01-01
 b          NaT
 Name: 0, dtype: datetime64[ns])
```

Can you check on that?

**Comment by jim22k** [comment] 2016-02-03 19:55
This shows the behavior I was noting:

```
In [39]: df[['a', 'e']].iterrows().next()
Out[39]: 
(0, a    2015-01-01 00:00:00
 e                     []
 Name: 0, dtype: object)

In [40]: df[['a', 'b', 'e']].iterrows().next()
Out[40]: 
(0, a    2015-01-01 00:00:00
 b                   None
 e                     []
 Name: 0, dtype: object)

In [41]: df[['a', 'b', 'c', 'e']].iterrows().next()
Out[41]: 
(0, a   2015-01-01
 b          NaT
 c          NaT
 e          NaT
 Name: 0, dtype: datetime64[ns])
```

Having only `None`s and empty strings always gives `NaT`s.

```
In [43]: df[['a', 'b', 'd', 'c', 'c', 'd', 'b']].iterrows().next()
Out[43]: 
(0, a   2015-01-01
 b          NaT
 d          NaT
 c          NaT
 c          NaT
 d          NaT
 b          NaT
 Name: 0, dtype: datetime64[ns])
```

But including a single `False` or zero in the row avoids the `NaT` conversion, even though those should also be considered "falsy".

```
In [45]: df['h'] = [False]

In [46]: df.iterrows().next()
Out[46]: 
(0, a    2015-01-01 00:00:00
 b                   None
 c                   None
 d                       
 e                     []
 f                     {}
 g                     {}
 h                  False
 Name: 0, dtype: object)

In [47]: df['h'] = [0]

In [48]: df.iterrows().next()
Out[48]: 
(0, a    2015-01-01 00:00:00
 b                   None
 c                   None
 d                       
 e                     []
 f                     {}
 g                     {}
 h                      0
 Name: 0, dtype: object)
```

**Comment by jreback** [comment] 2016-02-12 18:56
so the series inferer is a bit aggressive here.
```
In [18]: v
Out[18]: array([Timestamp('2015-01-01 00:00:00'), None, None, []], dtype=object)

In [19]: Series(v)
Out[19]: 
0   2015-01-01
1          NaT
2          NaT
3          NaT
dtype: datetime64[ns]
```

This is called and should not treat as a datetimeliek if this is the case.
```
In [21]: pd.lib.infer_dtype(v)
Out[21]: 'mixed'
```


pull-requests welcome

**Comment by simonjayhawkins** [comment] 2019-04-03 15:37
this is fixed in master. now only needs a test to close issue.

```
>>> import pandas as pd
>>> pd.__version__
'0.25.0.dev0+355.g4814a2875'
>>> import datetime
>>> df = pd.DataFrame({'a': [datetime.datetime(2015,1,1)], 'b': [None], 'c': [None], 'd': [''], 'e': [[]],
 'f': [set()], 'g': [{}]})
>>> next(df.iterrows())
(0, a    2015-01-01 00:00:00
b                   None
c                   None
d
e                     []
f                     {}
g                     {}
Name: 0, dtype: object)
>>> df.values[0]
array([Timestamp('2015-01-01 00:00:00'), None, None, '', list([]), set(),
       {}], dtype=object)
>>> pd.Series(df.values[0])
0    2015-01-01 00:00:00
1                   None
2                   None
3
4                     []
5                     {}
6                     {}
dtype: object
>>>
```

**Closed** 2019-05-18 14:16 UTC
Labels: Dtypes, Effort Low, Needs Tests, Reshaping, Timeseries, good first issue
