### ISSUE TITLE
Annotate DataFrame (API exposed items from pandas.core.api)

### ISSUE THREAD

**Issue by vaibhavhrt** [pandas-dev/pandas#26792] opened 2019-06-11 17:13 UTC
Part of #26766 

<details>
<summary>

- [x] Part 1 #26867
</summary>

  - `_constructor`
  - `_constructor_expanddim`
  - `__init__`
  - `axes`
  - `shape`
  - `_is_homogeneous_type`

</details>

<details>
<summary>

- [x] Part 2 (Rendering Methods) #28453
</summary>

  - `_repr_fits_vertical_`
  - `_repr_fits_horizontal_`
  - `_info_repr`
  - `__repr__`
  - `_repr_html_`
  - `to_string`
</details>
<details>
<summary>

- [ ] Part 3 #28575 
</summary>

  - `style`
  - `items`
  - `iteritems`
  - `iterrows`
  - `itertuples`
  - `__len__`
  - `dot`
  - `__matmul__`
  - `__rmatmul__`
</details>
<details>
<summary>

- [ ] Part 4 (IO methods)
</summary>

  - `from_dict`
  - `to_numpy`
  - `to_dict`
  - `to_gbq`
  - `from_records`
  - `to_records`
  - `from_items`
  - `_from_arrays`
  - `to_stata`
  - `to_feather`
  - `to_parquet`
  - `to_html`
</details>

**Comment by vaibhavhrt** [comment] 2019-06-11 17:14
PR coming soon

**Comment by WillAyd** [comment] 2019-06-13 17:51
This is probably tough to do in one pass. If you want to break up into a few PRs that should work too

**Comment by vaibhavhrt** [comment] 2019-06-14 10:55
Yeah it will be nice. PR with large changes are hard to review and debug. I am kinda busy these days but I will get to it soon.

**Comment by vaibhavhrt** [comment] 2019-06-14 12:52
Whew it's a big one ~8k lines class. I will annotate all the `@property` methods on top of class first. The methods of the class are grouped using comments(eg. `Rendering Methods`, etc.), I will pick one group at a time in one PR.

**Comment by jbrockmendel** [comment] 2020-09-25 22:43
closing a mostly-duplicate of #26766.  if you want to take this back up, let's put the checkboxes in a sublist over there.

**Closed by jbrockmendel** 2020-09-25 22:43 UTC
Labels: Typing
