### ISSUE TITLE
fillna after resample doesn't work on version 0.20.1

### ISSUE THREAD

**Issue by jmilhomens** [pandas-dev/pandas#16479] opened 2017-05-24 12:16 UTC
#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
df = pd.DataFrame({ 'values': range(5)}, index = pd.date_range(start = '2017-01-01 00:00:00', periods = 5, freq='S'))
resampled_df = df.resample('500ms').mean()
resampled_df.fillna(method='ffill')
```
#### Problem description

The `fillna` method is not working after a resample. The result of the above code is:

<table class="dataframe" border="1">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>values</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2017-01-01 00:00:00.000</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:00.500</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:01.000</th>
      <td>1.0</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:01.500</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:02.000</th>
      <td>2.0</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:02.500</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:03.000</th>
      <td>3.0</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:03.500</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:04.000</th>
      <td>4.0</td>
    </tr>
  </tbody>
</table>

This code worked with version 0.19.2

#### Expected Output

The expected output in this case can be also obtained with:

```python
df.resample('500ms').ffill()
```

The result is:
<table class="dataframe" border="1">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>values</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2017-01-01 00:00:00.000</th>
      <td>0</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:00.500</th>
      <td>0</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:01.000</th>
      <td>1</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:01.500</th>
      <td>1</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:02.000</th>
      <td>2</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:02.500</th>
      <td>2</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:03.000</th>
      <td>3</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:03.500</th>
      <td>3</td>
    </tr>
    <tr>
      <th>2017-01-01 00:00:04.000</th>
      <td>4</td>
    </tr>
  </tbody>
</table>

However, in some cases one may need to do the re-sample and fill missing values in separate steps.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.1.final.0
python-bits: 64
OS: Darwin
OS-release: 16.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.20.1
pytest: None
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.0
xarray: None
IPython: 6.0.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: None
tables: None
numexpr: None
feather: None
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.9.6
s3fs: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by TomAugspurger** [comment] 2017-05-24 13:06
Seems at least partially related to https://github.com/pandas-dev/pandas/blob/b0038ac72721058a3ae71f1dbcaa24d2f10f23c0/pandas/core/internals.py#L915 returning True, when it should be False (we have ints + nans, so it should be float). I guess the root cause is `resampled_df` having an IntBlock

```python
In [6]: resampled_df._data
Out[6]:
BlockManager
Items: Index(['values'], dtype='object')
Axis 1: DatetimeIndex([       '2017-01-01 00:00:00', '2017-01-01 00:00:00.500000',
                      '2017-01-01 00:00:01', '2017-01-01 00:00:01.500000',
                      '2017-01-01 00:00:02', '2017-01-01 00:00:02.500000',
                      '2017-01-01 00:00:03', '2017-01-01 00:00:03.500000',
                      '2017-01-01 00:00:04'],
              dtype='datetime64[ns]', freq='500L')
IntBlock: slice(0, 1, 1), 1 x 9, dtype: float64
```

potentially related to https://github.com/pandas-dev/pandas/issues/16361

**Comment by jreback** [comment] 2017-05-25 10:17
this is a dupe of #16361

**Closed by jreback** 2017-05-25 10:17 UTC
Labels: Missing-data, Numeric, Regression
