### ISSUE TITLE
read_csv does not correclty parse in header with BOM utf-8 

### ISSUE THREAD

**Issue by OlafEichstaedt** [pandas-dev/pandas#15280] opened 2017-02-01 12:01 UTC
This issues was #4793 ... but it has been closed although the issue still exists ... please see my last post there

**Comment by jreback** [comment] 2017-02-01 12:22
the issue is closed in a more recent version than you reported
try upgrading

**Closed by jreback** 2017-02-01 12:22 UTC

**Comment by OlafEichstaedt** [comment] 2017-02-01 12:54
Thanks for the feedback ... will try at once
