### ISSUE TITLE
API: read_excel's header and index_col handling rules

### ISSUE THREAD

**Issue by kuraga** [pandas-dev/pandas#34766] opened 2020-06-14 11:05 UTC
Good day!

`read_excel`'s `header` and `index_col` handling rules I see (a little chaotic [demo_suite.zip](https://github.com/pandas-dev/pandas/files/4776287/demo_suite.zip)):

- in all cases of `header`:
  - cells `(header, outside of index_col)` are used as `df.columns`.
- if `header` is a integer/one-item list:
  - `df.columns.name` is untouched,
  - cells `(greater than max(header), index_col)` are used for `df.index`,
  - cells `(header, index_col)` are used for `df.index.name`.
- else (i.e., `header` is a (2-up-items) list):
  - according to #34765, `index_col` should be `None` or `0` or `range(0, max_index_col+1, 1)`.
  - if row `max(header)+1` is empty except columns `index_col`:
    - cells `(greater than max(header)+1, index_col)` are used for `df.index`,
    - cells `(max(header)+1, index_col)` are used for `df.index.names`,
  - else:
    - cells `(greater than max(header), index_col)` are used for `df.index`,
    - `df.index.names` is untouched.
    - cells `(header, max(index_col))` are used for `df.columns.names`.
    - non-`max` columns of `index_col` aren't used for `df.index`/`df.columns`.

Other observations:

- rows above `min(header)` are omitted.
- `header` is 0-based or `skiprows-1`-based?

So,
1. Isn't it too complicated, is it?
2. Is each this rule is documented?
3. Is each this rule is tested?

Any thoughts? Thanks!

/cc @TomAugspurger @jreback

**Comment by kuraga** [comment] 2020-06-19 14:16
@TomAugspurger , @jreback , look at this, please!

**Comment by TomAugspurger** [comment] 2020-06-19 14:37
We have many open issues. Will take a look when we have a chance.

In the meantime, ensuring that you have well-specified, minimum
reproducible example that follows the issue template helps:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by kuraga** [comment] 2020-06-19 15:07
This issue has not only reproducible examples but total analysis. Thanks!

**Comment by TomAugspurger** [comment] 2020-09-04 13:52
@kuraga I don't know what to do with this issue. We'll need some more specificity in the actual issue itself to determine when it can be closed.

**Comment by kuraga** [comment] 2020-09-07 03:44
@TomAugspurger , propose to answer questions after "So,", first of all :smile: Thanks.

**Comment by mroeschke** [comment] 2021-08-08 00:43
Agreed that it would be easier for discussion here if:

1) Each point above is a separate issue to discuss
2) Each issue has an isolated, ideally copy-pastable example demoing the observation
3) Proposed behavior change or expected result

Otherwise since this issue hasn't gotten much traction and is fairly difficult for the team to take action on, closing for now.

**Closed by mroeschke** 2021-08-08 00:43 UTC
Labels: API Design, IO Excel, API - Consistency

**Comment by kuraga** [comment] 2026-07-19 14:01
@mroeschke , done:

- ~#34675 was fixed~,
- #34676 and https://github.com/pandas-dev/pandas/issues/34676#issuecomment-5172481873,
- ~#34747 is obsolete~,
- #66372,
- #66802 by @aleks-drozy ,
- #66374 (minor),
- #66376,
- #66377 and https://github.com/pandas-dev/pandas/issues/66377#issuecomment-5015981937,
- #66378,
- #66451,
- ~#34673 was fixed~,
- https://github.com/pandas-dev/pandas/pull/38517#issuecomment-5172365341, https://github.com/pandas-dev/pandas/pull/47496#issuecomment-5232617360,
- #67012.
