### ISSUE TITLE
ENH: Enable `append mode` to JSON lines

### ISSUE THREAD

**Issue by nullhack** [pandas-dev/pandas#35849] opened 2020-08-22 08:18 UTC
#### Is your feature request related to a problem?

[JSON Lines](http://jsonlines.org/) format allow appending to an existing file in a easy way (new line with valid JSON string). Historically `DataFrame().to_json` didn't allow`mode="a"` because It would introduce complications of reading/parsing/changing pure JSON strings. But for JSON lines It's done in an elegant way, as easy as a CSV files. 

The pandas way of using JSON lines is setting `orient='records'` together with `lines=True`, but It lacks a `mode="a"` for append mode. My feature proposal (PR already done, just need review) is simple: include the capability of append mode (`mode="a"`) on `to_json` IF `orient='records'` and `lines=True`

#### Describe the solution you'd like

The PR: https://github.com/pandas-dev/pandas/pull/35832

If I got It right, the solution is simple:
1. Include the [argument](https://github.com/pandas-dev/pandas/blob/dc5c1f5e3b85239bc8507cfb4b0d0a7f5f250bb5/pandas/io/json/_json.py#L53) `mode: str = "w"`on `to_json` this will NOT break anything as the default behavior continues as write mode
2. Include a [conditional](https://github.com/pandas-dev/pandas/blob/dc5c1f5e3b85239bc8507cfb4b0d0a7f5f250bb5/pandas/io/json/_json.py#L72) in case `mode="a"`, checking if `orient='records'` and `lines=True`, raising an Exception otherwise
3. In case `mode="a"` and the file already exists and is not empty, then add a new line to the [JSON string](https://github.com/pandas-dev/pandas/blob/dc5c1f5e3b85239bc8507cfb4b0d0a7f5f250bb5/pandas/io/json/_json.py#L103) (`s = convert_to_line_delimits(s)`) before sending to `handler`
4. Create the [handler using the correct mode](https://github.com/pandas-dev/pandas/blob/dc5c1f5e3b85239bc8507cfb4b0d0a7f5f250bb5/pandas/io/json/_json.py#L116) (`get_handle(path_or_buf, mode, compression=compression)` instead of the hardcoded `get_handle(path_or_buf, "w", compression=compression)` )

**Comment by nullhack** [comment] 2020-08-27 11:42
@gfyoung do you know maintainers/contributors that might be interested in commenting/reviewing this change?

As suggested, I created this issue just to raise discussion (as the PR is already done). But as not many comments were made, I'm trying to get some reviews here before conflicts can affect the PR and It becomes obsolete.

**Comment by charizard-knows** [comment] 2022-07-07 04:22
Hi. Can I get an update on this issue being fixed ?

**Comment by jreback** [comment] 2022-07-07 05:12
@charizard-knows pandas is all volunteer

issue will be fixed when a community member does a pull request 

pandas core will provide code review

**Comment by SFuller4** [comment] 2022-09-13 04:09
take

**Comment by SFuller4** [comment] 2022-09-14 14:37
@jreback I did a pull request for the code change. Looks like it failed a typing check but I can't see any information on why it failed. Do you have any insight on what the issue is?

**Closed** 2022-10-20 17:58 UTC
Labels: Enhancement, IO JSON
