### ISSUE TITLE
BUG: nlargest returns empty frame with NA + duplicates

### ISSUE THREAD

**Issue by LucasG0** [pandas-dev/pandas#45050] opened 2021-12-24 14:01 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the master branch of pandas.

### Reproducible Example

```python
>>> df
   c1   c2
0   1  NaN
1   0  0.0
2   1  NaN
>>> df.nlargest(n=1, columns=["c1", "c2"])
Empty DataFrame
Columns: [c1, c2]
Index: []
```

### Issue Description

The returned DataFrame is empty while it should have one row when rows having NA are duplicated.

### Expected Behavior

The first row should be returned, as when the row with NA is not duplicated.

```
>>> df.iloc[0:2].nlargest(n=1, columns=["c1", "c2"])
   c1  c2
0   1 NaN
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 11, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.5
numpy            : 1.19.5
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.2
setuptools       : 49.4.0.post20200813
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.0
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.52.0

</details>

**Comment by phofl** [comment] 2021-12-29 12:05
This is more or less a duplicate of #28984 and was fixed in #43060. Tests were also added

**Closed by phofl** 2021-12-29 12:05 UTC
Labels: Bug, Missing-data, Algos, NA - MaskedArrays
