### ISSUE TITLE
BUG: default for pd.Interval of closed/inclusive changed on main from right to both

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas#47365] opened 2022-06-15 11:47 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
print(pd.__version__)
i = pd.Interval(pd.Timestamp("2020-01-01"), pd.Timestamp("2020-01-02"))
print(repr(i))
print(i)

1.4.2
Interval('2020-01-01', '2020-01-02', closed='right')
(2020-01-01, 2020-01-02]

1.5.0.dev0+958.gf7be58a477
Interval('2020-01-01', '2020-01-02', inclusive='both')
[2020-01-01, 2020-01-02]
```

### Issue Description

This isn't mentioned in the release notes. We should decide on how to proceed.

### Expected Behavior

cc @simonjayhawkins 

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by jreback** [comment] 2022-06-15 11:50
on the PR changing to use inclusive this must have been accid changed
should change it back for the default o these cases

**Comment by phofl** [comment] 2022-06-15 12:07
One additional thing: The class attributes were also renamend, e.g.

```
x = pd.IntervalDtype(subtype='int64')

x.closed
```

raises now. Are these considered public or private?

**Comment by jreback** [comment] 2022-06-15 12:16
hmm let's add that back (and add a depreciation warning for it)

thanks!

**Comment by simonjayhawkins** [comment] 2022-06-15 13:54
is it ok for the repr change in a minor release or should this be changed back too?

**Comment by jreback** [comment] 2022-06-15 15:36
no this is for 1.5 only (as keyword change / deprecation)

**Comment by phofl** [comment] 2022-06-15 15:52
We will change the attribute back too. 

One other thing: The argument order changed, but I think we can live with that?

**Comment by phofl** [comment] 2022-06-15 21:46
I would like to give it a try on Friday, if this does not work out, reverting is probably the best option

**Comment by simonjayhawkins** [comment] 2022-06-16 14:59
> > One other thing: The argument order changed, but I think we can live with that?
> 
> not sure, it's only the third argument, so maybe a few users will be using positional here.
> 

if the default is changed then this may not be an issue. The `inclusive` argument accepts a `None` value as well as the strings `‘both’, ‘neither’, ‘left’, ‘right’`. These strings have the same meaning as the `closed` argument so effectively `inclusive` is just an alias for `closed` and should not be an issue.

ideally `inclusive` should have been lib.no_default (for the checking that both parameters are not passed at the same time) so that users don't explicitly pass `None`.

There is also
```python
        if closed is None:
            inclusive = "both"
```
in `_warning_interval` that also maybe allows users to now pass `None` explicitly but this will probably be removed when changing the defaults.

**Comment by simonjayhawkins** [comment] 2022-06-16 14:59
> > One other thing: The argument order changed, but I think we can live with that?
> 
> not sure, it's only the third argument, so maybe a few users will be using positional here.
> 

if the default is changed then this may not be an issue. The `inclusive` argument accepts a `None` value as well as the strings `‘both’, ‘neither’, ‘left’, ‘right’`. These strings have the same meaning as the `closed` argument so effectively `inclusive` is just an alias for `closed` and should not be an issue.

ideally `inclusive` should have been lib.no_default (for the checking that both parameters are not passed at the same time) so that users don't explicitly pass `None`.

There is also
```python
        if closed is None:
            inclusive = "both"
```
in `_warning_interval` that also maybe allows users to now pass `None` explicitly but this will probably be removed when changing the defaults.

**Comment by jorisvandenbossche** [comment] 2022-06-22 13:17
Should we maybe reconsider the actual deprecation of `closed` to start with (instead of fixing some issues caused by the deprecation)? 

I understand the strive for consistency in keyword arguments (and that certainly makes sense for things like `highlight_between`, `between` and `between_time` that those are consistent with each other), but specifically for the Interval-related methods, we already were consistently using the "closed" terminology. In addition:

* "closed" is standard terminology for intervals (and more than "inclusive" I think, or at least the rename is not fixing some unclear naming)
* It's not just a keyword argument rename, but also several attributes and methods on several classes that need to be renamed (eg `set_closed` should then also be deprecated/renamed?)
* Reading a parquet or pickle file written with a previous version of pandas no longer works (this can certainly be fixed, but is additional overhead that the deprecation causes)

**Comment by simonjayhawkins** [comment] 2022-06-22 13:22
+1 for closed for Interval etc. (i.e. +1 to revert all of https://github.com/pandas-dev/pandas/pull/46522)

**Comment by phofl** [comment] 2022-06-22 13:27
I don't have any preference there. I just saw that the default changed, hence this pr.

There where some cleanup prs after the initial one we would also have to revert

**Comment by simonjayhawkins** [comment] 2022-06-22 23:48
it seems weird to me that the docs state

```
inclusive{‘both’, ‘neither’, ‘left’, ‘right’}, default ‘both’
Whether the interval is closed on the left-side, right-side, both or neither. See the Notes for more detailed explanation.
```
i.e. we explain inclusive in terms of closed. strange.

**Comment by jbrockmendel** [comment] 2022-08-10 18:51
I agree with Joris here.

**Comment by mroeschke** [comment] 2022-08-10 19:29
xref https://github.com/pandas-dev/pandas/issues/40245 with @attack68's issue with standardizing the keyword argument

Personally, I think `inclusive` is a clearer name than `closed` (`closed_side` possibly even better ;)). 

Generally I would be +0 to standardize to inclusive. `+` for consistency for arguments that take `both, left, right, neither` in this context and `0` for this just being more of a style change that induces churn.

**Comment by mroeschke** [comment] 2022-08-15 21:59
Taking stock, appears we have:

- In favor of reverting `Interval.closed` deprecation: @jorisvandenbossche, @simonjayhawkins, @jbrockmendel 
- No preference: @phofl, @mroeschke 
- In favor of keeping `Interval.closed` deprecation: @jreback 

If we are aiming to release the 1.5rc next week (https://github.com/pandas-dev/pandas/issues/45223#issuecomment-1215891393), it appears we should revert this deprecation unless there are any other considerations

**Comment by jreback** [comment] 2022-08-15 22:51
ok to revert and discuss later

**Comment by mroeschke** [comment] 2022-08-20 18:49
This has been reverted in https://github.com/pandas-dev/pandas/pull/48116, and the discussion to change `closed` to `inclusive` can be discussed in https://github.com/pandas-dev/pandas/issues/40245 so closing in favor of that issue

**Closed by mroeschke** 2022-08-20 18:49 UTC
Labels: Bug, Interval, Blocker for rc
