### ISSUE TITLE
Inconsistent dtype of category in empty Series between dict and list input

### ISSUE THREAD

**Issue by toobaz** [pandas-dev/pandas#18515] opened 2017-11-27 10:48 UTC
#### Code Sample, a copy-pastable example if possible

```python
In [2]: pd.Series([], dtype='category')
Out[2]: 
Series([], dtype: category
Categories (0, object): [])

In [3]: pd.Series({}, dtype='category')
Out[3]: 
Series([], dtype: category
Categories (0, float64): [])

In [4]: pd.Series(dtype='category')
Out[4]: 
Series([], dtype: category
Categories (0, float64): [])
```
#### Problem description

The difference is unjustified.

#### Expected Output

The same. Probably ``Out[4]:``, which is also (implicitly) [tested](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/series/test_combine_concat.py#L184).

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-4-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8
LOCALE: en_GB.UTF-8

pandas: 0.22.0.dev0+241.gf745e52e1
pytest: 3.0.6
pip: 9.0.1
setuptools: 33.1.1
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.18.1
pyarrow: None
xarray: None
IPython: 5.2.2
sphinx: None
patsy: 0.4.1+dev
dateutil: 2.6.0
pytz: 2016.10
blosc: None
bottleneck: 1.2.0
tables: 3.3.0
numexpr: 2.6.1
feather: 0.3.1
matplotlib: 2.0.0
openpyxl: 2.3.0
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: None
lxml: 3.7.1
bs4: 4.5.3
html5lib: 0.999999999
sqlalchemy: 1.0.15
pymysql: None
psycopg2: None
jinja2: 2.8
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None

</details>

**Comment by jreback** [comment] 2017-11-27 11:20
dupe of #17261

**Comment by jorisvandenbossche** [comment] 2017-11-30 10:31
This takes a separate fix, so let's keep this open? 
I suppose this is due to this inconsistency in the Categorical constructor:

```
In [13]: pd.Categorical(np.array([]))
Out[13]: [], Categories (0, float64): []

In [14]: pd.Categorical([])
Out[14]: [], Categories (0, object): []
```

**Comment by jorisvandenbossche** [comment] 2017-11-30 10:46
Actually, the above is maybe not that wrong? As in the first case you actually pass it a float array, so it's OK that the categories are float. 
So then it does need to be fixed in the Series init, which I think @toobaz is doing in https://github.com/pandas-dev/pandas/pull/18496

**Comment by toobaz** [comment] 2017-11-30 11:03
> I suppose this is due to this inconsistency in the Categorical constructor:

The inconsistency is precisely the one described in my [opening example](https://github.com/pandas-dev/pandas/issues/18515#issue-276974367). Which is what I'm fixing in #18496  (and has nothing to do with passing an array - which would rightly keep its dtype).

But you are right that this can be considered separate from #17261, which doesn't involve categories. @jreback probably just viewed this as included in that (which was fine to me - but the fix is distinct).

So OK with reopening, I will just mention in #18496 that it closes this.

**Comment by jorisvandenbossche** [comment] 2017-11-30 11:08
> The inconsistency is precisely the one described in my opening example.

No, you are describing it with Series, which is something different as with Categorical :-) 

Anyhow, yes consider this as a separate issue, and mention it in #18496 (+ adding new tests, whatsnew note)

**Comment by toobaz** [comment] 2017-11-30 11:10
> No, you are describing it with Series, which is something different as with Categorical :-)

Indeed. This issue has nothing to do with (non-``Series``) ``Categorical``.

> Anyhow, yes consider this as a separate issue, and mention it in #18496 (+ adding new tests, whatsnew note)

OK

**Comment by jorisvandenbossche** [comment] 2017-11-30 11:15
> the inconsistency you are describing is unrelated to mine

No, the inconsistency I describe is the underlying cause of the bug you reported in this issue. Of course, the actual cause is in the implementation detail how Series handles no data or empty dict, previously it was passed as np.array([]), now you changed that to be passed as []. Which you are fixing, so perfect!

**Closed** 2017-12-01 19:02 UTC
Labels: Dtypes, Reshaping
