### ISSUE TITLE
Pandas 0.15.1 df.interpolate().plot() wrong result with NaT in datelike index

### ISSUE THREAD

**Issue by sorenwacker** [pandas-dev/pandas#8914] opened 2014-11-27 23:53 UTC
I am using a DataFrame df with dates as index and some data with missing values.
All dates are from the same year 1999 and the data has some missing vales.
There is one record in the dates that is NaT.

When I use df.interploate().plot() a line is plotted between 1996 and 1716. 
When NaT is committed the correct plot appears.

**Comment by jondo** [comment] 2016-11-14 14:22
Could the currently processed #12405 be a duplicate of this?

**Comment by jreback** [comment] 2016-11-14 21:26
@jondo could be; i'll put an xref on that issue.

**Closed** 2024-07-12 11:55 UTC
Labels: Bug, Visualization
