### ISSUE TITLE
BUG: tm.assert_index_equal ignores TimedeltaIndex.freq

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas#23826] opened 2018-11-21 00:33 UTC
```
tdi = pd.TimedeltaIndex(['1 Day', '2 Days'], freq='D')
tdi2 = tdi._shallow_copy(freq=None)

tm.assert_index_equal(tdi, tdi2)
```

The call to assert_index_equal should raise AssertionError, doesn't.

**Comment by jschendel** [comment] 2018-11-21 01:57
dupe of #13242, which includes some other things as well

**Closed by jschendel** 2018-11-21 01:57 UTC
