### ISSUE TITLE
BUG: test_orc segfault when missing /usr/share/zoneinfo/US/Pacific

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas#56292] opened 2023-12-02 00:05 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
python -m pytest pandas/tests/io/test_orc.py
```

### Issue Description

Segfault occurs:

```
pandas/tests/io/test_orc.py::test_orc_reader_basic terminate called after throwing an instance of 'orc::TimezoneError'
  what():  Can't open /usr/share/zoneinfo/US/Pacific
Fatal Python error: Aborted

Current thread 0x00007eff1a912780 (most recent call first):
```

Appears to be looking for /usr/share/zoneinfo/US/Pacific on my machine. My timezone directory has an America subdirectory but within that nothing called Pacific

### Expected Behavior

No segfault

A confirmed workaround is:

```sh
$ sudo mkdir -p /usr/share/zoneinfo/US
$ sudo ln -s /usr/share/zoneinfo/America/Los_Angeles /usr/share/zoneinfo/US/Pacific
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0cce0ed91cd23f17b412a0b345e6df79ed6b522b
python                : 3.10.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.5.0-13-generic
Version               : #13-Ubuntu SMP PREEMPT_DYNAMIC Fri Nov  3 12:16:05 UTC 2023
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.0.dev0+801.g0cce0ed91c
numpy                 : 1.26.0
pytz                  : 2023.3.post1
dateutil              : 2.8.2
setuptools            : 68.2.2
pip                   : 23.3.1
Cython                : 3.0.5
pytest                : 7.4.3
hypothesis            : 6.88.4
sphinx                : 7.2.6
blosc                 : None
feather               : None
xlsxwriter            : 3.1.9
lxml.etree            : 4.9.3
html5lib              : 1.1
pymysql               : 1.4.6
psycopg2              : 2.9.7
jinja2                : 3.1.2
IPython               : 8.17.2
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.2
bottleneck            : 1.3.7
dataframe-api-compat  : None
fastparquet           : 2023.10.1
fsspec                : 2023.10.0
gcsfs                 : 2023.10.0
matplotlib            : 3.7.3
numba                 : 0.58.1
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 14.0.1
pyreadstat            : 1.2.4
python-calamine       : None
pyxlsb                : 1.0.10
s3fs                  : 2023.10.0
scipy                 : 1.11.3
sqlalchemy            : 2.0.23
tables                : 3.9.1
tabulate              : 0.9.0
xarray                : 2023.10.1
xlrd                  : 2.0.1
zstandard             : 0.22.0
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

</details>

**Comment by mroeschke** [comment] 2023-12-02 00:16
I suspect that there's a pure pyarrow reproducer as `orc.py` just wraps `pyarrow.orc`

**Comment by phofl** [comment] 2024-03-18 02:03
Closing here, this seems to be an arrow only thing

**Closed by phofl** 2024-03-18 02:03 UTC
Labels: Bug, Closing Candidate, Upstream issue, Arrow
