### ISSUE TITLE
BUG: read_html - lxml - XPATH fails on huge HTML tables

### ISSUE THREAD

**Issue by PascalStehling** [pandas-dev/pandas#50200] opened 2022-12-12 12:50 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.

### Reproducible Example

```python
import pandas as pd

CONTENT = 1
OK_ROWS = 80000
FAIL_ROWS = 90000
COLUMNS = 40

print(f"Reading HTML with {OK_ROWS} rows")
row = [CONTENT]*COLUMNS
data = [row]*OK_ROWS
df = pd.DataFrame(data=data)
html = df.to_html()
html_df = pd.read_html(html)[0]
print(html_df)


print(f"Failing reading HTML with {FAIL_ROWS} rows")
row = [CONTENT]*COLUMNS
data = [row]*FAIL_ROWS
df = pd.DataFrame(data=data)
html = df.to_html()
html_df = pd.read_html(html)[0]
print(html_df)
```

### Issue Description

When an HTML Table gets to big the following error is thrown: `lxml.etree.XPathEvalError: Error in xpath expression`. Im not sure if this error, is because of the XPATH pandas uses or if it is an bug with `lxml`. The Bug does not occure with `bs4`. I also did NOT check if the problem is already fixed with #49929.

If the error not happens with the code snippet above, just increase the size of `FAIL_ROWS ` or `COLUMNS`, on my machine the table with 80k rows is read in as HTML without a problem, but with 90k lines the error occurs. I tried to find the number of rows where the error occurs, but it is non deterministic and changes.

### Expected Behavior

To read an html regardless of size.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 8dab54d6573f7186ff0c3b6364d5e4dd635ff3e7
python           : 3.10.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19045
machine          : AMD64
processor        : AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.5.2
numpy            : 1.23.5
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.6.3
pip              : 22.3
Cython           : None
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.1
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.5
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : 0.8.3
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.10
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : 1.4.44
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by ParfaitG** [comment] 2022-12-18 02:44
Looks like this does appear to be the `lxml` library as I also reproduce the issue with `read_xml` since your HTML is well-formed enough to be an XML. Specifically, `read_xml` succeeds at 80k nodes but fails to parse the 90k nodes with the default `lxml` parser. However, no issue occurs with the non-default `etree` parser:

```python
import pandas as pd

CONTENT = 1
OK_ROWS = 80000
FAIL_ROWS = 90000
COLUMNS = 40

print(f"Reading HTML with {OK_ROWS} rows")
row = [CONTENT]*COLUMNS
data = [row]*OK_ROWS
df = pd.DataFrame(data=data)
html = df.to_html(header=False)    # ONLY CHANGE: TO NOT PRINT HEADERS IN FIRST NODE

cols = [f"{i}" for i in range(COLUMNS + 1)]
html_df1 = pd.read_xml(html, xpath=".//tr", names=cols)
print(html_df1)

print()

print(f"Failing reading HTML with {FAIL_ROWS} rows")
row = [CONTENT]*COLUMNS
data = [row]*FAIL_ROWS
df = pd.DataFrame(data=data)
html = df.to_html(header=False)   # ONLY CHANGE: TO NOT PRINT HEADERS IN FIRST NODE

html_df2 = pd.read_xml(html, xpath=".//tr", names=cols)
print(html_df2)
````

Swapping out the non-default parser for Python's standard library `etree`, both calls work without error:

```python
...
html_df1 = pd.read_xml(html, xpath=".//tr", names=cols, parser="etree")
...
html_df2 = pd.read_xml(html, xpath=".//tr", names=cols, parser="etree")
```
---

Interestingly, neither `lxml` nor `etree` fails to parse the 80k or 90k `<tr>` nodes directly using their underlying libraries with your HTML outputs:

Generate html outputs

```python
...

row = [CONTENT]*COLUMNS
data = [row]*OK_ROWS
df = pd.DataFrame(data=data)
html = df.to_html(header=False)

with open("LargeRowsReadHTML8E4.html", "w") as f:
    f.write(html)

...

row = [CONTENT]*COLUMNS
data = [row]*FAIL_ROWS
df = pd.DataFrame(data=data)

with open("LargeRowsReadHTML9E4.html", "w") as f:
    f.write(html)
```

`lxml` and `etree` parse

```python
import lxml.etree as lx
import xml.etree.ElementTree as et

OK_ROWS = 80000
print(f"Reading HTML with {OK_ROWS} rows")
doc = et.parse("LargeRowsReadHTML8E4.html")
tr_nodes = doc.findall(".//tr")                           # SUCCEEDS

doc = lx.parse("LargeRowsReadHTML8E4.html")
tr_nodes = doc.xpath(".//tr")                             # SUCCEEDS


FAIL_ROWS = 90000
print(f"Failing reading HTML with {FAIL_ROWS} rows")
doc = et.parse("LargeRowsReadHTML9E4.html")
tr_nodes = doc.findall(".//tr")                           # SUCCEEDS

doc = lx.parse("LargeRowsReadHTML9E4.html")                
tr_nodes = doc.xpath(".//tr")                             # SUCCEEDS
```

However, running any type of conditional XPath, does raise the `XPathEvalError` error _only_ on 90k HTML output. So, both `read_html` and `read_xml` are running more complex `xpath` parsing.

```python
doc = et.parse("LargeRowsReadHTML9E4.html")
tr_nodes = doc.xpath(".//tr[td]")                         # FAILS

doc = et.parse("LargeRowsReadHTML9E4.html")
tr_nodes = doc.xpath(".//tr[1=1]")                        # FAILS

doc = et.parse("LargeRowsReadHTML9E4.html")
tr_nodes = doc.xpath(".//tr[position() > 1]")             # FAILS
````

Possibly, `lxml` imposes an upper computational limit by nodes or element size. Unsure if this is a bug, this can be a good post on their [mailing list](https://mail.python.org/mailman3/lists/lxml.python.org/) about this interesting issue! Thanks for posting!

**Comment by topper-123** [comment] 2023-05-16 22:52
That's some great analysis, @ParfaitG, really clear.

I ran example code in the newest dev version of pandas with newest version of lxml (v4.9.2) and the failure for 90k rows still exists.

From the analysis it looks to me that this is a lxml and not a pandas issue. I'll close the issue, but either of you feel there's a need to open it again, feel free to do so.

**Closed by topper-123** 2023-05-16 22:52 UTC
Labels: Bug, IO HTML, Needs Triage

**Comment by topper-123** [comment] 2023-05-16 23:00
If either of you could take this issue over to the lxml people to see they can fix this, that would be the best course forward, I think.
