### ISSUE TITLE
BUG: groupby(as_index=True).nth() does not return index values

### ISSUE THREAD

**Issue by idealcrouch** [pandas-dev/pandas#55334] opened 2023-09-30 16:31 UTC
### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

```python
# data
import pandas as pd
df = pd.DataFrame(data={'order_id': ['a1', 'a1', 'a2'], 'size_filled': [0, 2, 0], 'state': ['NEW', 'FILLED', 'NEW']})
print(df)

# groupby.first() changes behavior when as_index is True / False, as expected
df.groupby('order_id', observed=True, as_index=True).first()
df.groupby('order_id', observed=True, as_index=False).first()

# however groupby.nth() does NOT change behavior when as_index is True / False
df.groupby('order_id', observed=True, as_index=True).nth(0)
df.groupby('order_id', observed=True, as_index=False).nth(0)
```

### Issue Description

In pandas 2.1.1, when calling groupby.nth(0) in the example, you can see that the index values are not returned. As a sanity check, I verified that groupby(as_index=True).first() behaves as expected.

I compared this behavior to pandas 1.5.2 and saw groupby(as_index=True).first() and groupby(as_index=True).nth(0) both return the index values as expected. So I believe there is a legitimate bug in pandas 2.x.

### Expected Behavior

>>> import pandas as pd
>>> df = pd.DataFrame(data={'order_id': ['a1', 'a1', 'a2'], 'size_filled': [0, 2, 0], 'state': ['NEW', 'FILLED', 'NEW']})
>>> df.groupby('order_id', observed=True, as_index=True).nth(0)
          size_filled state
order_id
a1                  0   NEW
a2                  0   NEW

### Installed Versions

<details>

>>> pd.show_versions()
/Users/john/miniconda3/envs/pandas2/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit              : e86ed377639948c64c429059127bcf5b359ab6be
python              : 3.11.5.final.0
python-bits         : 64
OS                  : Darwin
OS-release          : 23.0.0
Version             : Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020
machine             : arm64
processor           : arm
byteorder           : little
LC_ALL              : None
LANG                : en_US.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.1
numpy               : 1.26.0
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 68.0.0
pip                 : 23.2.1
Cython              : None
pytest              : 7.4.2
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : 4.9.3
html5lib            : 1.1
pymysql             : None
psycopg2            : None
jinja2              : 3.1.2
IPython             : None
pandas_datareader   : None
bs4                 : 4.12.2
bottleneck          : 1.3.7
dataframe-api-compat: None
fastparquet         : None
fsspec              : None
gcsfs               : None
matplotlib          : 3.8.0
numba               : None
numexpr             : 2.8.6
odfpy               : None
openpyxl            : 3.1.2
pandas_gbq          : None
pyarrow             : None
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.11.2
sqlalchemy          : None
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : None
zstandard           : 0.21.0
tzdata              : 2023.3
qtpy                : None
pyqt5               : None
</details>

**Comment by AmeyaVerma** [comment] 2023-09-30 19:13
I can fix this please assign me with it

**Comment by paulreece** [comment] 2023-09-30 20:15
@idealcrouch just to confirm, you're referring to  `df.groupby('order_id', observed=True, as_index=True).first()` dropping the indexes but  `df.groupby('order_id', observed=True, as_index=True).nth(0`) not as the bug?

```Python
>>> df
  order_id  size_filled   state
0       a1            0     NEW
1       a1            2  FILLED
2       a2            0     NEW
>>> df.groupby('order_id', observed=True, as_index=True).first()
          size_filled state
order_id
a1                  0   NEW
a2                  0   NEW
>>> df.groupby('order_id', observed=True, as_index=False).first()
  order_id  size_filled state
0       a1            0   NEW
1       a2            0   NEW
>>> df.groupby('order_id', observed=True, as_index=True).nth(0)
  order_id  size_filled state
0       a1            0   NEW
2       a2            0   NEW
>>> df.groupby('order_id', observed=True, as_index=False).nth(0)
  order_id  size_filled state
0       a1            0   NEW
2       a2            0   NEW
```

**Comment by idealcrouch** [comment] 2023-09-30 20:36
Thanks for clarifying. The bug is with groupby(as_index=True).nth(0).

Groupby.first() behaves as expected.

Please let me know if I can send any other info to help.

**Comment by rhshadrach** [comment] 2023-10-01 13:50
Thanks for the report, this is the intended behavior. The change was documented in the whatsnew notes:

https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#dataframegroupby-nth-and-seriesgroupby-nth-now-behave-as-filtrations

`nth` will either return 0, 1, or many values per group. It is therefore not a reduction, but rather a filter. pandas groupby operations have different behaviors depending on whether they are reductions, transformations, or filters:

https://pandas.pydata.org/docs/user_guide/groupby.html#filtration

**Comment by idealcrouch** [comment] 2023-10-01 14:06
Thank you. Since it's intended, this shouldn't be considered a bug. How
should I resolve the ticket?

**Comment by rhshadrach** [comment] 2023-10-01 14:07
We can close this, thanks for the response.

**Closed by rhshadrach** 2023-10-01 14:07 UTC
Labels: Bug, Groupby, Closing Candidate, Filters
